### ISSUE TITLE
 Bug: typeclass force-reloading not cleaning old cmdset

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1000]
#### Brief summary of issue / Description of requested feature:

If using `@typeclass/force` on a typeclass that has `self.cmdset.add` in its `at_object_creation` hook, that cmdset will be added over and over to the resulting object. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use an object with a cmdset added in its `at_object_creation` hook. 
2. Use `@typeclass/force` to reload the object. 
3. `ex object` shows the cmdset has been replicated. Using /reset does not matter. 

#### Error output / Expected result of feature

Resetting the typeclass (at least with /reset) should clean out old cmdsets to start from scratch. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is a matter of expanding the `typeclasses.models.swap_typeclass` function.

**Comment by BlauFeuer** [comment]
Is this possibly related?  My command set attached to an object lost the command set somehow - or it's corrupted - I can no longer examine it.

```
Traceback (most recent call last):
  File "/home/evennia/commands/cmdhandler.py", line 464, in _run_command
    ret = yield cmd.func()
  File "/home/evennia/commands/default/building.py", line 2071, in func
    get_and_merge_cmdsets(obj, self.session, self.player, obj, mergemode).addCallback(get_cmdset_callback)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/evennia/commands/default/building.py", line 2016, in get_cmdset_callback
    string = self.format_output(obj, cmdset)
  File "/home/evennia/commands/default/building.py", line 1939, in format_output
    all_cmdsets = [(cmdset.key, cmdset) for cmdset in avail_cmdset.merged_from]
exceptions.AttributeError: 'NoneType' object has no attribute 'merged_from'
```

**Comment by Griatch** [comment]
@BlauFeuer 

No, that doesn't seem related, the issue is about cmdsets *not* getting removed; it looks like your `avail_cmdset` has been set to `None` for some reason. Can you reproduce this somehow?

**Comment by Griatch** [comment]
`self.obj` is indeed the object on which the command sits yes. This is often the same as `caller` unless the command sits on a non-Character/Player/Session object. 

Before making a new issue, check to make sure this is actually the cause of the problem: put checks in your command to print what `self.obj` actually is and test if you can reproduce with and without that call.
