### ISSUE TITLE
MXP not escaping single quote character when generating link.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1002]
#### Brief summary of issue / Description of requested feature:

The single quote can't be escaped, and isn't automatically escaped when included as part of a MXP response. Trying to substitute `&#39;` yields `&amp;#39;` as it escapes the `&` character instead.
#### Steps to reproduce the issue / Reasons for adding feature:
1. `say |lc' Aye!|lt|gAll in favor?|n|le`
2. `say |lcget lady's coin purse|lt|gpick up the item that the merchant dropped|n|le`
3.  Notice no effect when clicking on links with MXP-enabled client or webclient
#### Error output / Expected result of feature

`You say, "<SEND HREF='' Aye!'>All in favor?</SEND>"`
`You say, "<SEND HREF='get lady's coin purse'>pick up the item that the merchant dropped</SEND>"`

Expected escape of single quote as an HTML entity when within single quotes or use of double quotes when no double quote exists in the HREF:

`You say, "<SEND HREF='&#39; Aye!'>All in favor?</SEND>"`
`You say, "<SEND HREF='get lady&#39;s coin purse'>pick up the item that the merchant dropped</SEND>"`

or

`You say, "<SEND HREF="' Aye!">All in favor?</SEND>"`
`You say, "<SEND HREF="get lady's coin purse">pick up the item that the merchant dropped</SEND>"`
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

current

The raw links are visible by forcing `@option mxp=on` in a non-MXP client.

**Comment by BlauFeuer** [comment]
I tested a possible solution in evennia/server/portal/mxp.py:

`MXP_SEND = MXP_TEMPSECURE + \`
`           "<SEND HREF=\"\\1\">" + \`
`           "\\2" + \`
`           MXP_TEMPSECURE + \`
`           "</SEND>"`

which corrects the link to:
`<SEND HREF="get lady's coin purse">pick up the item that the merchant dropped</SEND>`

and also to the parsing:

`text = text.replace("&", "&amp;") \`
`           .replace("'", "&#39;") \`
`           .replace("<", "&lt;") \`
`           .replace(">", "&gt;")`

which corrects the link to:

`<SEND HREF='get lady&#39;s coin purse'>pick up the item that the merchant dropped</SEND>`

If either or both solutions are undertaken, it looks like it exposes another problem in the webclient's behavior of encoding the `onclick` which would be malformed: `<a id="mxplink" href="#" onclick="Evennia.msg(&quot;text&quot;,[&quot;get lady" s="" coin purse"],{});="" return="" false;'="">`

As for the mxp standard mentioned [here](http://www.mushclient.com/mushclient/mxp.htm#quoting), it seems to suggest the standard had not yet decided what to do about quoting the ' mark, offering forth the idea that " might be substituted. in its entities section, it would disallow the `&#39;` escape by requiring only letters in the entity keyword, thus `&apos;` would be the alternative entity.

**Comment by Griatch** [comment]
@BlauFeuer It looks like you have looked into this, would you be willing to put together a PR for it? I have no particular preference for how to replace the single quote or not.

**Comment by BlauFeuer** [comment]
I will submit a PR right away to give it a try and move this one forward, but I'm not sure I can solve the whole issue.

Part of the problem is that the MXP standard as written doesn't match the HTML entities standard - not such a big deal if the MXP-enabled client follows the MXP standard...  Then the next problem was encoding it properly for the webclient.

**Comment by Griatch** [comment]
This issue has been mostly addressed except for the use of the double-quote (") in the MXP command component. In the webclient this leads to JS errors and a malformed onClick definition. Leaving this open for a little longer in case inspiration strikes; otherwise this may be one of the quirks of doing an automatic HTML-conversion.

**Comment by BlauFeuer** [comment]
I was able to escape the double quote in the command section of an MXP link by inputting this command from one character either by Telnet or Webclient:

#### Works
`say |lcsay Able to process a quote character: (\")|ltClick on this!|le`

When the same or another player/character clicks on it in webclient, it works, and it is confirmed by @CloudKeeper1 
While the unescaped case still fails as expected:
#### Fails
`say |lcsay Able to process a quote character: (")|ltClick on this!|le`

The working case could be a possible solution or work around.

**Comment by Griatch** [comment]
I cannot reproduce this test on a vanilla setup. On the webclient I get a different error which has to do with the ansi->html converter putting its end `</span>` inside the field: 

    say |lcsay Able to process a quote character: (\")|ltClick on this!|le
    No match for /span

**Comment by Griatch** [comment]
My bad, the environment wasn't as clean as I thought it was. Running with a clean game dir and applying the `\\&quote;` in the replacement seems to have resolved the issue so that 

    say |lcsay Able to process a quote character: (")|ltClick on this!|le 

(and other combinations of " or ' in the cmd) now appears to work. I have not tested with the RPsystem though.

**Comment by BlauFeuer** [comment]
I was probably having the same problem with a test environment.  Anyway, I can close this now!
I tested on 4 different game folders, one of them a vanilla+RP system, another a vanilla, and two different game folders in various levels of development, one of them on a different computer.  Now, the MXP link _does nothing if you do escape the double quote_.  We'll just call that "expected behavior" and leave it at that.
