### ISSUE TITLE
Missing variable reference in "already puppeting" message in players.py

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1003]
#### Brief summary of issue / Description of requested feature:

Missing variable reference in "already puppeting" message in players.py
https://github.com/evennia/evennia/blob/master/evennia/players/players.py#L257

#### Steps to reproduce the issue / Reasons for adding feature:

1. Default setting: MULTISESSION_MODE = 0
2. Have one player session puppet a character. 
3. Have another player `@ic <same character>`

#### Error output / Expected result of feature
`%s is already puppeted by another Player.`

should be

`Sleipnir  is already puppeted by another Player.`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.6.0 (rev acf3daf) master branch, any OS.

**Comment by Griatch** [comment]
Closed with #1004.
