### ISSUE TITLE
Couldn't perform move ('location change'). Contact an admin. (location-loop)

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1005]
#### Brief summary of issue / Description of requested feature:
Trying to move something into something that is inside of it is the simplest form of location loop, which triggers the following message: `Couldn't perform move ('location change'). Contact an admin. (Error: BlauFeuer.location = The Ghostblade creates a location loop.)`

Related to issue #964

#### Steps to reproduce the issue / Reasons for adding feature:

1. hold `<something>` in your inventory
2. `@tel me=<something>`

Reason for feature - shorter, more direct error message for the simplest form of location loop.
(Other longer location loops would still generate the longer message, but they are less likely.)

#### Error output / Expected result of feature
 `Couldn't perform move ('location change'). Contact an admin. (Error: BlauFeuer.location = The Ghostblade creates a location loop.)`
expected something like:
`You can't teleport an object inside something it holds!`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.6.0 (rev 8f320ac) main branch

**Comment by Griatch** [comment]
Closed as implemented in #1006.
