### ISSUE TITLE
Bug: ContribRPObject's search method does not honor typeclass

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#1017]
#### Brief summary of issue / Description of requested feature:

The `search()` method on `ContribRPObject` objects does not seem to be honoring the `typeclass` kwarg if it is entered.

#### Steps to reproduce the issue / Reasons for adding feature:

In Evennia:
```
>>> @typeclass/force me = evennia.contrib.rpsystem.ContribRPCharacter
Ainneve changed typeclass from typeclasses.characters.Character to evennia.contrib.rpsystem.ContribRPCharacter.
Creation hooks were run. Attributes set before swap were not removed.

>>> @create/drop obj:evennia.contrib.rpsystem.ContribRPObject
You create a new ContribRPObject: obj.

>>> @py o = me.search('obj', typeclass='evennia.contrib.rpsystem.ContribRPCharacter'); me.msg(str(o)); me.msg(str(type(o)))
obj
<class 'evennia.contrib.rpsystem.ContribRPObject'>
```

#### Error output / Expected result of feature

The `@py` command above should be limited to `ContribRPCharacter` types, and therefore should not return a result.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Observed in the current Evennia master. I took a brief look at the `search()` function within `ContribRPObject`, and it does not appear that the typeclass kwarg is passed into or used by the `parse_sdescs_and_recogs` helper function when it generates matches, nor are its results filtered by typeclass after the fact.

**Comment by BlauFeuer** [comment]
I remember scratching my head over this situation a few weeks ago and had to write up a specific function to do this:

```python
        def find_by_name(search):
            search = search.strip().split(';', 1)[0]
            keyquery = Q(db_key__istartswith=search)
            aliasquery = Q(db_tags__db_key__istartswith=search,
                           db_tags__db_tagtype__iexact='alias')

            results = ObjectDB.objects.filter(keyquery | aliasquery).distinct()
            nresults = results.count()

            if nresults:  # convert multiple results to typeclasses.
                results = [result for result in results]
                room_typeclass = settings.BASE_ROOM_TYPECLASS  # Narrow results type room
                results = [obj for obj in results if inherits_from(obj, room_typeclass)]
            return results 
```
