### ISSUE TITLE
Bug: Mudlet Isssues Displaying < and >

### ISSUE THREAD

**Issue by itsalkaid** [evennia/evennia#1020]
#### Brief summary of issue / Description of requested feature:
In some but not all circumstances Mudlet will display ;lt and ;gt instead of < and > when sent text by Evennia. The default connection screen dialogue displays them properly, for example, but text drawn from helpfiles and some commands will not.

Example: 
![image](https://cloud.githubusercontent.com/assets/20212597/17954892/1ca723ac-6a4c-11e6-8ee9-5b52048a52a1.png)

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I've experienced this issue on Windows 10 with Mudlet 2.1 and 3.0.0-delta. Evennia version is in the screenshot. It's possible this is a bug with the client but I'm unsure.

**Comment by BlauFeuer** [comment]
What's the output of `@options` after login when using that particular client?
It might help to know which features Evennia believes the client is using.

**Comment by itsalkaid** [comment]
```
+--------------+--------------------+
| Name         | Value              |
+~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~~~~+
| ANSI         | True               |
| CLIENTNAME   | MUDLET 3.0.0-DELTA |
| ENCODING     | utf-8              |
| INPUTDEBUG   | False              |
| MCCP         | True               |
| MXP          | True               |
| NOMARKUP     | False              |
| NOPKEEPALIVE | True               |
| OOB          | False              |
| RAW          | False              |
| SCREENHEIGHT | 62                 |
| SCREENREADER | False              |
| SCREENWIDTH  | 100                |
| TERM         | Mudlet 3.0.0-delta |
| XTERM256     | True               |
+--------------+--------------------+
```

**Comment by BlauFeuer** [comment]
@itsalkaid I highly suspect the MXP code.  To eliminate or confirm it, try `@option MXP=off` and view the help entry again.

If it disappears, you can use `@option/save MXP=off` as a work-around, unless you are using the MXP features in Mudlet 3.0.0-delta.   If Mudlet 3.0.0-delta doesn't have an MXP feature, then it's more likely to be a bug in Mudlet 3.0.0-delta.

**Comment by itsalkaid** [comment]
@BlauFeuer Seems like you've nailed it. Mudlet does have an MXP feature but I'm not too familiar with the state it's in. `@option/save MXP=off` does fix the display issue entirely.

I'm not if it makes a big difference but the very first time I connected after a fresh install of Mudlet the connection screen <> symbols showed up improperly as well. I haven't been able to replicate it since, though. I'm going to close the issue unless anything else comes up.
