### ISSUE TITLE
execute_cmd() prioritizes key instead of sdesc

### ISSUE THREAD

**Issue by stefanludlow** [evennia/evennia#1021]
#### Brief summary of issue / Description of requested feature:
self.execute_cmd('say This is a tick') results in "an orc npc says, "This is a tick"" -- this is utilizing the key of the npc, rather than the sdesc. 

#### Error output / Expected result of feature
I would expect self.execute_cmd would prioritize the sdesc, if available, and then if one is not set, go to the key. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Encountered on Avennia codebase

**Comment by maxsond** [comment]
Evennia assumes that the key is the name of a character when dealing with characters. From the admin interface description for the key field: "Main identifier, like 'apple', 'strong guy', 'Elizabeth' etc. If creating a Character, check so the name is unique among characters!"

**Comment by Griatch** [comment]
@stefanludlow 

There should be no difference between using `execute_cmd` and using `say` as that object. If you puppet the orc and use say "being" the orc, will you see the same output?
 Also you don't mention if the orc is a child of ContribRPCharacter or some other class.

**Comment by stefanludlow** [comment]
Closing this per discussion in the IRC, this is an issue we will have to address on Avennia.
