### ISSUE TITLE
xterm256 on Potato requires change to ansi.py to work

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1024]
#### Brief summary of issue / Description of requested feature:
For some reason, Potato (and possibly other clients), will not display the full list of xterm256 colors based on the formatting of the command string - if you submit a single value it works, but if you build the number by adding the 3 digits together into a string, it doesn't.
I ran into this issue long ago on my ancient version of evennia, and did a change to ansi.py that resolved it, and assumed it had been fixed in the newest version. In the process of updating, I saw it again, and then logged into BlauFeuer's mud (also the latest version of evennia) to check.

#### Steps to reproduce the issue / Reasons for adding feature:

Log into Evennia with Potato. Turn on xterm256 with @options, then use @color xterm256. You'll see the far left columns be gray, and other colors will be muted - essentially, blue is missing from the color map.

This occurs with the following line at: https://github.com/evennia/evennia/blob/master/evennia/utils/ansi.py#L140
return "\033[%s8;5;%s%s%sm" % (3 + int(background), colval // 100, (colval % 100) // 10, colval%10)

It's resolved by, instead, having this line:
return "\033[%s8;5;%sm" % (3 + int(background), colval)

The only difference between them is that in the second example, it doesn't have leading zeroes, which I guess is what causes the issue in Potato/other clients.

**Comment by Griatch** [comment]
Ok, can confirm the issue in Potato. Since the change does not seem to affect other clients, I implemented it. I also added an exception to the TTYPE handshake for Potato to make us know Potato does actually support xterm256 despite not telling us correctly.

**Comment by Griatch** [comment]
Closed in 668029e82e2f4f457386304fde665c5024222452.
