### ISSUE TITLE
Calling the index() and remove() methods for lists of lists and lists of dictionaries of lists stored in .db raises errors

### ISSUE THREAD

**Issue by andrei-pmbcn** [evennia/evennia#1027]
#### Brief summary of issue / Description of requested feature:

Attempting to get an index in a list of lists, or a list of dictionaries of lists, when the outer list is stored as a database atrribute, raises an error.
Command:
@py self.db.data = [[], []]; self.msg(str(self.db.data.index(self.db.data[0])))

Result:
File "<path>/vienv/lib64/python2.7/_abcoll.py", line 628, in index
    raise ValueError
ValueError

Command:
@py self.db.data = [{'test1':[]}, {'test2':[]}]; self.msg(str(self.db.data.index(self.db.data[0])))

Result:
File "<path>/vienv/lib64/python2.7/_abcoll.py", line 628, in index
    raise ValueError
ValueError

Attempting to get an index in a list of dictionaries does not, however, raise an error.
Command:
@py self.db.data = [{}, {}]; self.msg(str(self.db.data.index(self.db.data[0])))

Result:
0

Likewise, attempting to get an index in a list of dictionaries of dictionaries does not raise an error.
Command:
@py self.db.data = [{'test1':{},'test2':{}}]; self.msg(str(self.db.data.index(self.db.data[0])))

Result:
0

All the commands that would raise an error when attempted if the outer list were stored as a database attribute do not raise the error when the outer list is not in fact stored as a database attribute. The following commands all return zero: 
@py self.ndb.data = [[], []]; self.msg(str(self.ndb.data.index(self.ndb.data[0])))
@py self.ndb.data = [{'test1':[]}, {'test2':[]}]; self.msg(str(self.ndb.data.index(self.ndb.data[0])))

Any list that gives an error when attempting to index one of its items also gives an error when attempting to remove that item.
Command:
@py self.db.data = [[], []]; self.msg(str(self.db.data.remove(self.db.data[0])))

Result:
File "<path>/vienv/lib64/python2.7/_abcoll.py", line 689, in remove
    del self[self.index(value)]
File "<path>/vienv/lib64/python2.7/_abcoll.py", line 628, in index
    raise ValueError
ValueError

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia version 0.6.0

**Comment by Griatch** [comment]
Thanks for a detailed issue description, will look into that.
