### ISSUE TITLE
Bug: user defined aliases for channels don't appear to function

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1038]
#### Brief summary of issue / Description of requested feature:
I thought it might just be something I messed up in my database migration when converting between versions, but I made a test character on Horizondark and ran into the same issue - aliases added with 'addcom' don't seem to be recognized currently. You'll see the alias listed under @channels, but attempting to execute the command <alias> <message> will return a command not found error.

#### Steps to reproduce the issue / Reasons for adding feature:

1. addcom foo=public
2. @channels
3. foo testing

**Comment by Griatch** [comment]
Confirmed. This appears to be unrelated to the latest Attribute/Nick changes but an effect of the inputfunc not correctly handling the input to the nickreplace.

**Comment by Griatch** [comment]
Closed in PR #1055
