### ISSUE TITLE
Suggestion: change exit cmdset default priority to be the same as channel cmdset priority

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1059]
#### Brief summary of issue / Description of requested feature:
I did the above in order to solve an issue that sounds obscure, but is very confusing to players. When the priority of channels is higher than that of exits, exit aliases being blocked confuses players. For example, say you have a channel 'noun', and then you have an exit with a name like 'adjective noun adverb', with aliases for adjective, noun, and adverb. Players would be very confused when they try to use the exit with any of the aliases, and see that it's not a valid command - they're particularly confused because aliases aren't inherently visible to players, so they may be trying to enter an exit command that has no apparent connection to a channel name. However, when exits and channels are the same priority, there's no collision at all due to the different regex for exits - exits don't take arguments, while channels do. So a player can cheerfully use the exit, but also can use the channel command without issue.

**Comment by Griatch** [comment]
This is a good argument, hadn't considered that the two don't collide due to the enforced arg restriction.

**Comment by Griatch** [comment]
Changed. Closing.
