### ISSUE TITLE
Feature Request: Change how auto-login works

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1063]
#### Brief summary of issue / Description of requested feature:

Currently the auto-login feature is asymmetric: 
1. Logging in to the _website_ logs the Player in to _both_ website and webclient
2. Logging out of the _website_ logs the Player out of _both_ website and webclient
3. Logging in to _weclient_ logs the Player in to _both_ website and webclient
4. Logging out from the _webclient_ logs the Player out of _only_ the webclient 

Case 4. should behave as 2.
#### Steps to reproduce the issue / Reasons for adding feature:
1. Log out from the webclient
2. One is still logged into the website.
#### Error output / Expected result of feature

The original reason for the auto-login is to avoid the case of having to log in twice (once for website and once for webclient). While one could argue that there is a potential advantage to be able to just auto-login to the webclient if still logged into the website, now _logging out_ is a two-step process instead, where one has to go to the website in order to actually be able to login anew to the webclient. In short, logging out of the webclient should also log one out of the website. 
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This requires going through and refactor the auto-login mechanism. There are several issues, such as #1061 and #1037.

**Comment by Griatch** [comment]
Whereas the other issues have been closed, actually implementing this is more complex than expected. Notably because the webclient must somehow track so that it does not log out of the website if there are remaining (webclient-)Sessions connected; which is not immediately obvious how to determine.

**Comment by Kelketek** [comment]
@Griatch Can the webclient send an OOB command that queries all active sessions?

**Comment by whitenoiseoss** [comment]
Something like reference counting would have to be implemented here. A way to query either by an API call, OOB command, whatever, and increment/decrement a "session count" and on log out if that count - 1 == 0, log out fully and destroy the website session.

**Comment by Griatch** [comment]
@Kelketek 

It could, but it's not really up to the webclient itself to handle this I don't think, but the webclient's backend. 

@whitenoiseoss

I did try querying the session count connected to a given player as my first attempt but ran into edge cases with the implementation. Will likely revisit to see if I can figure out a stable way to do it.

**Comment by Griatch** [comment]
This was moved to the devel branch leading up to Evennia 0.7.

**Comment by Griatch** [comment]
Implemented in devel.
