### ISSUE TITLE
Confusing behavior for players for EvMore

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1074]
#### Brief summary of issue / Description of requested feature:
Because EvMore covers player commands, this includes the character look command. But what is often happening is if a player doesn't understand the syntax for EvMore, they'll get something like 'Command 'more' is not available' then hit look, and see: 'You are out-of-character (OOC). Use @ic to get back into the game.' because the player OOCLook is still available. So they'll hit @ic, and then see that they're already in-game, and be thoroughly confused, not knowing that they're stuck in the EvMore window.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Open an EvMore message that's 2 or more pages
2. enter 'more'
3. 'look'
4. '@ic'

#### Error output / Expected result of feature
The player will receive the confusing message that they're currently @ooc, while being told they're IC if they try to use @ic

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Perhaps EvMore should cover the OOCLook command as well to replay the current window. I'd also suggest 'return' be replaced with 'next', because for non-ansi terminals they can't tell the N is highlighted in return, and 'return' itself is an invalid command.

**Comment by Griatch** [comment]
I see what you mean; it sounds reasonable to change the distribution of commands while inside the more command space.

**Comment by Griatch** [comment]
Closed with a rebase.
