### ISSUE TITLE
Telnet Clients receiving newlines/junk data from JSON Send

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#1077]
#### Brief summary of issue / Description of requested feature:
When .msg() is called and sends JSON/OOB data to a telnet client without GMCP enabled.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Connect a telnet client to Evennia.
2. Enable packet debug on client - I recommend MUSHclient.
2. @py self.msg(testing=((),{}))
3. Notice THIS happens... (see below)

#### Error output / Expected result of feature

Incoming packet: 3997 (6 bytes) at Sunday, September 25, 2016, 11:39:09 PM

.[0m..             1b 5b 30 6d 0d 0a

This packet causes a newline to appear in the client.

Very not cool.

Why is a client that can't receive OOB data receiving junk? Shouldn't Evennia strip the meaningless data from a protocol instance that didn't WILL GMCP?

**Comment by volundmush** [comment]
To give you a little more context, here's the thing I've got going on:

```python
class WhoManager(Script):

    def at_script_creation(self):
        self.key = 'Who Manager'
        self.desc = 'Maintains the Who List for webclients.'
        self.interval = 30

    def at_start(self):
        from athanor.library import connected_characters
        self.ndb.characters = connected_characters()

    def add(self, character):
        if character in self.ndb.characters:
            return
        self.ndb.characters.append(character)
        self.update_character(character)
        for char in [chr for chr in self.visible_characters(character)]:
            char.msg(who_add=((character.id), {'data': character.serialize(char)}))

    def rem(self, character):
        if character not in self.ndb.characters:
            return
        for char in [chr for chr in self.ndb.characters if chr.can_see(character)]:
            char.msg(who_remove=((character.id), {}))
        self.ndb.characters.remove(character)

    def at_repeat(self):
        for char in self.ndb.characters:
            self.update_character(char)

    def update_character(self, character):
        all_data = [chr.serialize(character) for chr in self.visible_characters(character)]
        character.msg(who_all=((), {'data': all_data}))

    def visible_characters(self, character):
        return [chr for chr in self.ndb.characters if character.can_see(chr)]
```

This thing sends JSON data to all connected characters and is maintained as they login and logout. And every 30 seconds my telnet client gets a newline...

**Comment by Griatch** [comment]
I'm pretty sure MUSHclient supports GMCP, no? But either way, it's correct that there should be no newline being sent when the command in question is an OOB instruction.

**Comment by volundmush** [comment]
MUSHclient actually does not support GMCP! At least, it does not support it entirely on its own. It does support it through plugins. None are installed on my MUSHclient...
