### ISSUE TITLE
Use a password control module

### ISSUE THREAD

**Issue by robbintt** [evennia/evennia#1079]
#### Brief summary of issue / Description of requested feature:

Use a module for managing passwords when using the `create` or `connect` commands.

Django has some good inspiration when creating a superuser with manage.py

https://github.com/django/django/blob/92053acbb9160862c3e743a99ed8ccff8d4f8fd6/django/contrib/auth/management/commands/createsuperuser.py#L148

**Comment by Griatch** [comment]
Evennia uses `django.contrib.auth.authenticate`  for processing the password:

```python
from django.contrib.auth import authenticate
[...]
player = authenticate(username=name, password=password)
```

Could you elaborate on in what capacity you feel something like the django management infrastructure is needed compared to what is currently there?

**Comment by robbintt** [comment]
I see how this is tied into Django now, I'll reopen once I understand typeclass better, if what I was thinking still makes sense.
