### ISSUE TITLE
Running `@batchcommand` removes stored CmdSets

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#1085]
#### Brief summary of issue / Description of requested feature:

In `at_object_creation()` for ContribRPCharacter, the `RPSystemCmdSet` is added to the cmdset handler with `permanent=True`.

I have noticed that after building with the `@batchcommand` command, my character no longer has the `RPSystemCmdSet`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Fresh install
2. Change character typeclass with `@type me = evennia.contrib.rpsystem.ContribRPCharacter`
3. Run `@ex me` to confirm that the `RPSystemCmdSet` is stored on the character.
4. Run any build script with `@batchcommand`.
5. Run `@ex me` - `RPSystemCmdSet is no longer present

#### Error output / Expected result of feature

Output:

```
Stored Cmdset(s):
commands.default_cmdsets.CharacterCmdSet [DefaultCharacter] (Union, prio 0)
```

Expected:

```
Stored Cmdset(s):
commands.default_cmdsets.CharacterCmdSet [DefaultCharacter] (Union, prio 0)
evennia.contrib.rpsystem.RPSystemCmdSet [Unnamed CmdSet] (Union, prio 0)
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

It would appear that this is happening because `cmdset.clear()` is being called in [evennia.commands.default.batchprocess.py Line 210](https://github.com/evennia/evennia/blob/master/evennia/commands/default/batchprocess.py#L210).

It looks as though there are only two cmdsets that are used in this module, so an easy fix would be to just remove the module-specific cmdsets instead of clear()-ing all of them.

Is the desired behavior for `cmdset.clear()` to remove even those cmdsets added with `permanent=True`? Should there be a variant that does not remove "permanent" cmdsets? I'm happy to make a PR for this with some guidance as to whether the change should be in batchprocess.py, or in cmdsethandler.py

**Comment by Griatch** [comment]
The reason for the clear() is that the very nature of the batchcmd process means that the caller (which is literally walking around performing all those commands in sequence) may end up with all sorts of command sets on it as it progresses through the script.
 I agree the clear() is too aggressive however. The best solution may be to store the cmdsets from pre-batchcmd, clear and then add them back manually to make sure you have the same setup as when you entered the command.
