### ISSUE TITLE
Feature Request: Let `CommandTest` gracefully handle msg() calls not using the text outputfunc

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#1091]
#### Brief summary of issue / Description of requested feature:

In command unit tests, it would appear that the `CommandTest` class does not handle output from a command similar to:

caller.msg(prompt='myprompt>')

The error does not occur if text is included with the prompt, but only when `prompt` is the only argument.

#### Steps to reproduce the issue / Reasons for adding feature:

* Fresh install; create mygame/commands/tests.py:
```:python
from evennia import Command, CmdSet
from evennia.commands.default.tests import CommandTest
from evennia.contrib.rpsystem import ContribRPCharacter


class CmdTest(Command):
    key = 'test'
    
    def func(self):
        self.caller.msg("Test message.")
        self.caller.msg(prompt="NOW BREAK IT!")
        

class TestTestCase(CommandTest):
    character_typeclass = ContribRPCharacter
    
    def test_msg_with_prompt(self):
        self.call(CmdTest(), '','')

```
* Run 'evennia test'

#### Error output / Expected result of feature
```
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_msg_with_prompt (mygame.commands.tests.TestTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dan\Sandbox\mygame\commands\tests.py", line 19, in test_msg_with_prompt
    self.call(CmdTest(), '','')
  File "c:\users\dan\sandbox\evennia\evennia\commands\default\tests.py", line 74, in call
    returned_msg = "||".join(_RE.sub("", mess) for mess in stored_msg)
  File "c:\users\dan\sandbox\evennia\evennia\commands\default\tests.py", line 74, in <genexpr>
    returned_msg = "||".join(_RE.sub("", mess) for mess in stored_msg)
TypeError: expected string or buffer

----------------------------------------------------------------------
Ran 1 test in 0.296s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Current evennia:master.

**Comment by Griatch** [comment]
This is not really an bug with Evennia though? The Mock() handling of Commands deal with text-message returns for Evennia's default commands, none of which uses anything but `msg(text)`. If you want custom message handling and parsing for your own commands, this sounds like something for a custom Testing class? 
If the idea is the expand the Command tester with the intention of handle all possible command classes (not sure how feasible this would be), this would be something for an Feature Request.

**Comment by feend78** [comment]
I guess I was just assuming that since the out-of-box webclient handles the `prompt` argument, that its presence would be supported throughout, even though the CommandTest class is designed only to check the text output of a command. In my current use case, I don't care about the value of `prompt`, only `text`, but a call to `msg` without `text` does not fail gracefully. 

I am not advocating that the CommandTest be capable of handling any and all command classes, but rather that it should discard the output of any calls that contain only a `prompt` or other OOB data and no `text`.

That said, I will probably take the suggestion of creating a custom command test case, as I will be needing to test against the value of `prompt` as well.

**Comment by Griatch** [comment]
Ok, changing this to a feature request for the feature.

**Comment by Griatch** [comment]
Made non-text kwargs safe for the Mock by converting all of the extra kwarg to strings (rather than ignoring it). Closing.
