### ISSUE TITLE
Caching bug with relations

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1098]
#### Brief summary of issue / Description of requested feature:
A small quirk I've noticed with stale foreignkeys for models. Suppose you have an Account model that has a OneToOne relationship with PlayerDB, and Account has a foreignkey to another model, say Org. Doing something like the following: 'org = player.account.org; org.attr = val; org.save()' works as expected. However, if you retrieve and alter the org object directly, such as by using django admin or Org.objects.get, then PlayerDB will have a stale reference to the old version of org, which must then be fixed by player.flush_from_cache(force=True). Oddly, this doesn't seem to happen to every set of models, and I can't figure out exactly why. When it happens, it will reproduce every time, but some pairs of relationships don't seem to do it. For example, a foreignkey from a model to itself seems to behave normally. A model that has 1-to-1 relationships with ObjectDB and PlayerDB and then a fkey relationship might update one of the 1-to-1 relationships when the fkey is changed, but not both.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a model with a one-to-one relationship to a typeclass with a foreignkey to another model
2. Change the foreignkey model instance and save it from django admin
3. Check typeclass.onetoone.foreignkey

#### Error output / Expected result of feature
Stale version when the object is modified externally, correct version when modified by traversing relations. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
If this is too much of a horrible pain to change, maybe just note in the new models tutorial that you should always retrieve and change objects by traversing from a typeclass through their related models?

**Comment by Griatch** [comment]
I'm not sure this is an Evennia problem but is rather a limitation of Django. Django caches ForeignKey and OneToOne relations, this is not something we have changed. Django does not share their select_related cache between instances. See e.g. here: https://code.djangoproject.com/ticket/17. So I'm pretty sure you would see this effect, Typeclass or not; it's just that Typeclasses last much longer in memory than Django models usually do, which Django normally does not expect. 

So I'm not convinced this is a Typeclass problem; Testing this with three vanilla django models (all set and dereferenced in the same function) would be needed to really show if this is a typeclass problem only.

**Comment by TehomCD** [comment]
I think I see what you mean, you're right that this is just django behavior I was unfamiliar with.  Looking at the docs, I found the refresh_from_database method, which I hadn't seen before, and looks like it's specifically for this sort of thing. I'm still confused why some objects seem to update fine/immediately with django admin while others don't, but I can just have things refresh_from_database when there's any doubt about whether they'd be stale or not.

**Comment by Griatch** [comment]
One hypothesis could be that it's a matter of access order. If Player accesses Account, it will cache Account and Account will in turn cache Org. Now, if Org updated before Player first dereferenced Account, then Player will see the latest version of Org. If Org updates later the change will not be transferred down to Player. 

At any rate I don't think this is an issue against Evennia, and Django has decided it's behavior that should not be changed (as per the linked ticket). I'll add a mention of it to the wiki. Closing this now.
