### ISSUE TITLE
nick/alias delete option does not delete by index

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1099]
#### Brief summary of issue / Description of requested feature:
After creating a functioning nick/alias,  list option shows created nick, but delete option does not actually delete, despite message "Nick removed"

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create nick
2. Attempt to delete nick

#### Error output / Expected result of feature
`> alias/list`
No nicks defined.
`> alias a=b`
Nick 'a' mapped to 'b'.
`> alias/list`
Defined Nicks:
`#   Type         Nick match   Replacement`
1   inputline   a                   b 
`> alias/delete 1`
Nick removed: 'a' -> b.
`> alias/list`
Defined Nicks:
`#   Type         Nick match   Replacement`
1   inputline   a                   b 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.6.0 (rev 997014e) 
current horizondark.com

**Comment by Griatch** [comment]
Confirmed. This appears to only happen with doing `alias/delete 1`, not when doing `alias/delete a` (then it deletes the nick correctly).

**Comment by BlauFeuer** [comment]
You're right, I can delete by alias name!  I renamed the issue to reflect that.

What confused me is the help entry regarding delete:
`delete    - remove nick by number of by index given by /list`

Now I'm wondering what happens if the alias is a number, like `nick 1=use blaster`  ...

**Comment by Griatch** [comment]
The nick/delete mechanism will first try to find the nick based on the actual given name (like "1"), only if no such match is found, will it test if a number was given and interpret it as an index.
