### ISSUE TITLE
Bug: Persistent repeating script not repeating after shutdown

### ISSUE THREAD

**Issue by Curudan** [evennia/evennia#1100]
#### Brief summary of issue:

The following script does not continue repeating for me after a cold shutdown and restart of the server.

``` python
class WeatherManager(DefaultScript):

    def at_script_creation(self):
        self.key = 'weather_manager'
        self.desc = 'Echoes weather messages to all outdoor rooms.'
        self.interval = 20
        self.persistent = True

        self.db.count = 0

    def at_repeat(self):
        self.db.count += 1
        for obj in search_tag("outdoors"):
            obj.msg_contents("This is message number %s. " % self.db.count)
```

Interestingly enough, the script will resume repeating following a `@reload`
#### Steps to reproduce the issue:
1. Install the latest version of Evennia following the [Getting Started ](https://github.com/evennia/evennia/wiki/Getting-Started)guide.
2. Add the script to the bottom of mygame\typeclasses\scripts.py, and change the import line to `from evennia import DefaultScript, search_tag`
3. Tag Limbo with `@tags here = outdoors` and then initiate the script with `@scripts/start typeclasses.scripts.WeatherManager`.
4. Shutdown the server with 'evennia stop' from the console, and then bring it back up with 'evennia start'.
#### Error output:

The Script will no longer repeat, and the output from `@scripts` has '--' in the 'next' column.
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Windows 10
Evennia version 0.6.0 (rev cd9c11f) (The latest version)

**Comment by Curudan** [comment]
I was just able to reproduce this issue on a different computer running Windows 8 with completely fresh installs of all required programs.

I noticed this time that when reloading to fix the 'stuck' script the message is echoed immediately; before the restart messages are finished.

```
Server restarting ...
This is message number 5.
... Server restarted.
```

**Comment by Griatch** [comment]
I cannot replicate this on Linux. Will need to test in Windows.

**Comment by CloudKeeper1** [comment]
I have replicated this issue on a fresh install on Windows 7

**Comment by Griatch** [comment]
Can confirm it on Windows too. The reason for this turns out to be Windows' abysmal signal processing. On Linux os.kill() sends the SIGINT signal which tells the Server process to shut down itself. This is where the Server saves all running scripts and makes sure they will restart properly next start. On Windows however, what is sent appears to be the equivalent to the Linux SIGTERM signal, which kills the process abruptly without giving it a chance to clean up. 
Reading up on this, this is a known issue with Windows and it''s surprisingly hard to achieve the effect in this OS. There are some hacks that look promising though; are looking into those.

**Comment by Griatch** [comment]
... So, it it was not clear, the error lies in how Windows handles `evennia stop` (`@shutdown` from in-game doesn't have this problem) and not with how Scripts work - the Script failing to restart is just a symptom.

**Comment by Griatch** [comment]
The latest commit will fix the issue with `evennia stop` by forcing Windows to emit signals the way Linux do. Scripts now work correctly after a stop / start. 
Windows' console however insists on asking if "one wants to terminate the batch process". There is no way to remove this short of using a better console than the default one - it's just something Windows programmers thought was a good idea, somehow. A single press of Ctrl-C will bypass the questions though. 
Closing.
