### ISSUE TITLE
Task: Add unit tests to all contribs

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1105]
#### Brief summary of issue / Description of requested feature:

All contribs in `evennia/contribs` should have full (edit: as full as feasible?) unittest coverage.
#### Steps to reproduce the issue / Reasons for adding feature:

This is a sub-task of #120 (add more unittests to Evennia), arguably with a higher priority. This is because contribs are optional and thus errors in them or changes relative core may go undetected longer. 

Having existing contribs under unittesting will also make it more natural to demand unittests for new contribs as well.

**Comment by gtaylor** [comment]
whew, full coverage? There is no universal truth with testing, but covering the right 20-40% is often as good as 100%. It's a matter of making sure that you've got the right bases covered. I fear that you're going to see less contrib activity if there's a 100% requirement.

**Comment by Griatch** [comment]
Maybe my definition of "full" is too imprecise. I'd be happy to just have each contrib have unittests ... any at all at this point. :)

**Comment by gtaylor** [comment]
Fair enough!

**Comment by Griatch** [comment]
Added coverage testing with [coverall](https://coveralls.io/github/evennia/evennia) which should help a little with this.

**Comment by Griatch** [comment]
Added unit tests for the contrib barter system in b12a850 (forgot to reference this issue from it).

**Comment by Griatch** [comment]
This is moved to development towards Evennia 0.7, since finishing this will lead to us being able to demand unittest coverage for all new contribs.

**Comment by Griatch** [comment]
All contribs are now covered by unittests to some degree and this can be closed. We will henceforth request that new contribs also come with unit tests. Removed devel branch tag since this is already live in master. Closing.
