### ISSUE TITLE
Webclient: Enter on a blank line no longer unidles the session.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1111]
#### Brief summary of issue / Description of requested feature:

Simply pressing the enter key in webclient with an active session should unidle that session.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Connect to Evennia server via webclient
2. login
3. observe idle time
4. press enter key in webclient
5. observe idle time unchanged

#### Error output / Expected result of feature
Idle time in who list unchanged, expected to change due to use input (albeit an empty line).

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Since revision 73633f0 in main branch from pull request #1110 , behavior regarding empty line input has changed, but #1109 did not specify the change.

The javascript `else if (line.length < 1)` skips doing anything for a blank line, but probably should only do nothing when `lines.length > 1` also.

**Comment by robbintt** [comment]
Where is the code that unidles the client?

**Comment by BlauFeuer** [comment]
By default, it's the `no-input` command, triggered by an empty line.

**Comment by Griatch** [comment]
@robintt 

The main point is that the client must be allowed to send no-input. This is used explicitly in the line editor, for example.

**Comment by robbintt** [comment]
Ah, the else if is defensive coding gone wrong and can be deleted.

**Comment by BlauFeuer** [comment]
That makes my suggested change (don't send empty lines if it's part of a multi-line) not a good one, 

because you might be pasting in multi-line text into the editor.  So per Griatch's patch (already removed the else if), it's back to how it should be now.  Thanks to you both for the new multi-line send in webclient. It's all good now.
