### ISSUE TITLE
Bug: TagHandler fails for Msg and HelpEntry objects

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1114]
#### Brief summary of issue / Description of requested feature:

Msg objects have tags, but their manager, MsgManager, does not inherit from TypedObjectManager, so it doesn't have the create_tag method, get_tag, etc. Attempting to create a new tag with msg.tags.add() will cause an attribute error. Same thing happens for HelpEntry objects, for the same reason.
#### Steps to reproduce the issue / Reasons for adding feature:
1. Create a new Msg object, then attempt to add a tag that does not currently exist to it
2. create_tag will be called, and raise an Attribute Error
3. same thing will happen with a HelpEntry object
#### Error output / Expected result of feature

File "evennia\evennia\typeclasses\tags.py", line 252, in add
    tagobj = self.obj.**class**.objects.create_tag(key=tagstr, category=category, data=data,
AttributeError: 'MsgManager' object has no attribute 'create_tag'
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

I'm not sure the best way to resolve this, since Msg and HelpEntry aren't TypedObjects, so I wasn't sure if having their managers just inherit from a TypedManager would cause any issues. I guess that maybe the Tag methods could be refactored out and made a mixin that go into Typed Manager, and then also into the managers for Msg and HelpEntry, something like that?

**Comment by TehomCD** [comment]
I was glancing at typeclasses/manager.py, and I think I might have seen a possible issue that's not directly related to this.  https://github.com/evennia/evennia/blob/master/evennia/typeclasses/managers.py#L209 is the get_tag method for TypedManager. One of the arguments is obj, which is supposed to allow you to specify an object to search against. But if global_search is set to true, it just searches Tag.objects.filter with the ID of obj, which would match a tag by that ID rather than the object. It looks like it needs the same type of query as used below in line 219.

**Comment by TehomCD** [comment]
Another thing I just noticed is that db_model doesn't appear to be populated currently for tags: adding a random tag to myself has the db_model for the tag return None. I think when I did my migration from the old version I just added the classname (eg: objectdb, playerdb, msg, etc) to all of em, but I'm unsure what the intent behind the field is - whether it's supposed to match the model of where the tag is assigned for possible use in queries, or if it's intended to eventually act as a constraint on what the tag is allowed to be attached to. In the latter case, db_model could be a comma seperated charfield in which queries would check whether the object's classname is in it for permission, for example.

**Comment by Griatch** [comment]
Good point on Msg/HelpEntries objects, should add that. 

`db_model` is the model type naturalkey the Tag is attached to (`objectdb`, `scriptdb` etc). It is needed since returning mixed object matches from a given tag search is an error. It used to be an integral part of defining the tag, similar to how it's done for Attributes, but looking at it now, the db_model is not actually used in the queries. Not sure what happened there, it seems to have been lost somewhere along the way.

**Comment by Griatch** [comment]
Resolved in #1115. Closing.

**Comment by Griatch** [comment]
Reopening this again since even with #1115, `@py msg=evennia.Msg();msg.tags.add("foo")` leads to a recursion error:
```python
File "/home/samreg/Misc/OwnStuff/Evennia/evennia/evennia/comms/models.py", line 150, in __senders_get
    list(self.db_sender_objects.all()) + \
  File "/home/samreg/Misc/OwnStuff/Evennia/vienv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 468, in __get__
    return self.related_manager_cls(instance)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Griatch** [comment]
Never mind, `msg.tags.add()` works fine, I was just being a dummy by not saving the Msg object before trying to do stuff with it.
