### ISSUE TITLE
EvMenu options formatting problem

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#1117]
#### Brief summary of issue / Description of requested feature:

A recent change to EvTable seems to have introduced problems to how EvMenu options are formatted. Options that contain ANSI color characters appear to have their contents wrapped incorrectly, and the ansi characters are stripped from the first line of the option, though they do seem to appear after the wrap.

#### Steps to reproduce the issue / Reasons for adding feature:

This issue appears by running the Ainneve chargen menu with any evennia commit later than 242fb0e.

#### Error output / Expected result of feature

Below is before and after output from the Ainneve chargen menu.
```
# commit 5f5ffe4
# this is the correct output

Your character's traits influence combat abilities and skills.
Type 'help' to see individual trait definitions.

Allocate additional trait points as you choose.

  8 Points Remaining
Please select a trait to increase:
______________________________________________________________________________________________________________________________________________________________________________________

  1: |CStrength|n        : |x[|w   4|x]|n   5: |CCharisma|n        : |x[|w   1|x]|n 
  2: |CPerception|n      : |x[|w   6|x]|n   6: |CVitality|n        : |x[|w   1|x]|n 
  3: |CIntelligence|n    : |x[|w   6|x]|n   7: |CMagic|n           : |x[|w   0|x]|n 
  4: |CDexterity|n       : |x[|w   4|x]|n   8: Start Over               



# commit 242fb0e
# this is the incorrect output

Your character's traits influence combat abilities and skills.
Type 'help' to see individual trait definitions.

Allocate additional trait points as you choose.

  8 Points Remaining
Please select a trait to increase:
__________________________________________________________________________________________________________________________________________________________________________________________

1: Strength        : [     5: Charisma        : [    
4|x]|n                          1|x]|n                         
2: Perception      : [     6: Vitality        : [    
6|x]|n                          1|x]|n                         
3: Intelligence    : [     7: Magic           : [    
6|x]|n                          0|x]|n                         
4: Dexterity       : [     8: Start Over             
4|x]|n   
```
(The ansi characters were manually added to this output.)

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

As listed in the comments above, it seems that the change appeared at or around commit 242fb0e.

**Comment by TehomCD** [comment]
Might have to change .lstrip() and .rstrip() to .lstrip(" ") and .rstrip(" ") so it doesn't catch ansi characters when trying to fix alignment and just removes the single offending whitespace.

**Comment by Griatch** [comment]
Merged #1118. @feend78, would you mind checking if @TehomCD's fix resolved the issue or if we need to dig deeper?

**Comment by Griatch** [comment]
Closing, after confirmation over IRC.

**Comment by feend78** [comment]
I think I may have messed up on checking this. When I went to deploy Ainneve on an online instance and checked out the current evennia:master branch, I find that the menu options are still displaying incorrectly.

**Comment by Griatch** [comment]
Ok, we'll need a small example in order to get to the bottom of this.

**Comment by feend78** [comment]
```python
"""
Test case for Issue #1117
"""
from evennia import Command, CmdSet
from evennia.utils.evmenu import EvMenu


class TestCase1117CmdSet(CmdSet):
    def at_cmdset_creation(self):
        self.add(CmdTestCase1117())


class CmdTestCase1117(Command):
    key = 'test_case_1117'
    help_category = 'test cases'

    def func(self):
        EvMenu(self.caller, 'world.test_case_1117')


def start(*args):
    options = [
        {'desc': '|CStrength           |x[|w  6 |x]|n', 'goto': 'end'},
        {'desc': '|CPerception         |x[|w  3 |x]|n', 'goto': 'end'},
        {'desc': '|CIntelligence       |x[|w  5 |x]|n', 'goto': 'end'},
        {'desc': '|CCharisma           |x[|w  4 |x]|n', 'goto': 'end'},
    ]
    return None, options


def end(*args):
    return None, None

```

**Comment by Griatch** [comment]
Latest push should fix the offset problem with things ending up on the next line. There are no colors in the desc still though, so this is still not closed.

**Comment by Griatch** [comment]
In the end it turns out I had to implement custom versions of the ANSIString `.strip()`, `.lstrip()` and `.rstrip()` methods in order to correctly strip characters on all sides of a color/mxp tag. This is not all that simple once must be able to strip strings so that the ANSIString `"       |r test       |n      ").strip()` becomes  `"|rtest|n"` which is what an onlooker expects (since they don't see the color tags). Also added unittests for the new ANSIString feature. 

Anyway, this incorporates the adjustment of the leading/trailing whitespace while allowing for stripping in an ANSI-aware manner. The example evmenu seen in this issue is now both correctly formatted and comes with color so this can be considered fixed.
