### ISSUE TITLE
Strange char displays on Potato from Linux with newlines

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1131]
#### Brief summary of issue / Description of requested feature:
When receiving the \r\n characters sent from using |/ in ansi, users in Potato from Linux (but not Windows, I couldn't see this myself) will see some strange characters pop up. The player reporting this switched to Windows and could no longer see the behavior.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use Potato from Linux
2. Enter |/ or other newline characters

#### Error output / Expected result of feature
I don't know which character they're seeing, I wasn't given a pastebin. But more than one person reported this.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Player having this issue said they were on the latest version of Xubuntu, as far as their Linux distribution goes.

**Comment by Griatch** [comment]
What is returned by `|/` is `\r\n`, where `\r` is the Windows/DOS line break symbol and `\n` is the Linux/Unix one. Most clients ignore or hide the one of them not suitable for their OS. It appears Potato does not hide it on Linux, displaying the `\r` character verbatim (it's actually pretty hard to spot):

![image of token](https://s12.postimg.org/oqi3ch4al/Screenshot_2016_12_02_21_32_01.png)

Trying it on Windows, it appears Potato does not recognize the `\r` symbol at all when given on its own - it seems to only use the Unix ´\n`. 

I *could* remove the `\r` in `\r\n` but I fear there may be other (Windows) clients that *do* require the `\r` to work...

**Comment by Griatch** [comment]
Not sure how to really proceed with this one.

**Comment by Griatch** [comment]
I'm closing this. This appears to be an error with Potato not handling `\r`.
