### ISSUE TITLE
Stale session in ObjectSessionHandler

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1153]
#### Brief summary of issue / Description of requested feature:
This has only happened once or twice, and I haven't yet been able to reproduce it. Very rarely, if a player connects/goes linkdead a number of times in rapid succession, they'll wind up in a state where they're connected but have no active session, so any input they receive is directed nowhere. Their ObjectSessionHandler will have a `count()` of 1, while `get()` will return `[]`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Player connects/disconnects many times quickly
2. Player is no longer able to see input from their puppet

#### Error output / Expected result of feature
Character no longer sends messages to the correct session, so player is blind.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Calling `character.sessions.clear()` and making the player relog/repuppet resolved the issue. Maybe just adding a call to unpuppet if it's not there already? Not sure.

**Comment by Griatch** [comment]
@Tehom: I added extra verification to the ObjectSessionHandler to catch if the SessionHandler and Character ObjectSessionHandler should go out of sync.
