### ISSUE TITLE
Freak error in AMP/logger caused users to lose cmdsets

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1160]
#### Brief summary of issue / Description of requested feature:
To preface this, on my fork I changed the `callLater(0, reactor.stop())` to be `callLater(1, reactor.stop())` in an attempt to resolve the server hangs. So I'm not sure if it could produce the following behaviior.

To start with, seemingly out of nowhere, I first saw a '...server reloaded' message, which I thought was damned strange, since I didn't reload the server myself within the last half an hour or so. Then I looked at the log and saw this error message which had happened immediately before:
```
2017-01-09T22:55:08-0500 [AMPProtocol,0,127.0.0.1] Unhandled Error
[8CTraceback (most recent call last):
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
[8C    return callWithContext({"system": lp}, func, *args, **kw)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
[8C    return context.call({ILogContext: newCtx}, func, *args, **kw)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
[8C    return self.currentContext().callWithContext(ctx, func, *args, **kw)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
[8C    return func(*args,**kw)
[8C--- <exception caught here> ---
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
[8C    why = selectable.doRead()
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
[8C    return self._dataReceived(data)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
[8C    rval = self.protocol.dataReceived(data)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 2411, in dataReceived
[8C    return Int16StringReceiver.dataReceived(self, data)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 765, in dataReceived
[8C    self.stringReceived(packet)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 877, in stringReceived
[8C    self.state = statehandler(string)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 2464, in proto_key
[8C    self.boxReceiver.ampBoxReceived(self._currentBox)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1063, in ampBoxReceived
[8C    self._answerReceived(box)
[8C  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 989, in _answerReceived
[8C    question = self._outstandingRequests.pop(box[ANSWER])
[8Cexceptions.KeyError: '245c'
2017-01-09T22:55:10-0500 [evennia.server.amp.AmpServerFactory] AMPProtocol connection established (HOST:IPv4Address(TCP, '127.0.0.1', 5000) PEER:IPv4Address(TCP, '127.0.0.1', 44662))
```

This error apparently prompted '...server reloaded.' a second later, when the AMPProtocol connection reestablished.

After that, I began to see a slew of errors like the following:
```
2017-01-09T22:56:28-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@107.141.116.26
2017-01-09T22:56:31-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@24.252.51.38
2017-01-09T22:56:34-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@107.141.116.26
2017-01-09T22:56:41-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@107.141.116.26
2017-01-09T22:56:50-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@73.214.62.109
2017-01-09T22:56:53-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@24.67.168.21
2017-01-09T22:56:56-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@73.214.62.109
2017-01-09T22:56:56-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@24.67.168.21
2017-01-09T22:56:58-0500 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@24.67.168.21
```
As players could no longer connect their session to their players, I believe. I'm uncertain if this is a totally freak error, or a result of my tinkering with the restart process and putting in a delay to try to resolve possible timing issues.

#### Steps to reproduce the issue / Reasons for adding feature:

1. No idea how to reproduce this.

#### Error output / Expected result of feature
AMP error, players losing their cmdsets.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Using my server-logging fork which raised the `self.callLater(0, reactor.stop())` in `server.py` timeout from 0 to 1, which may possibly have caused this somehow. I don't know yet.

**Comment by Griatch** [comment]
Curious. Not sure why changing the timeout would affect you this way, especially since you didn't actually reloaded. Did some other admin reload maybe?

**Comment by TehomCD** [comment]
No other admin reloaded. I was guessing that the '...server restarted' message was a consequence of the `AMPProtocol` reestablishing connection, but I don't really know how that works.

**Comment by Griatch** [comment]
@TehomCD My guess is that this is likely unrelated to your `callLater` change. Rather it looks like something interrupted the AMP connection, causing the client to have to reconnect. Could it be that your AMP port is visible from the outside (it shouldn't be) and someone sent something to it (which is then not on the right format AMP expects)? It could happen if someone entered the AMP port instead of the telnet port in their client for example.

**Comment by TehomCD** [comment]
Ah! Yeah, you were right, I did have port 5000 open. In my ignorance about ports I just had opened everything that seemed relevant. So I'm guessing someone tried to connect to 5000 by mistake, and that messed everything up. Thank you!

**Comment by TehomCD** [comment]
Tagging this as possibly being related to #1305 due to same traceback. So the question is how logging commands produce the same effect as having the port open on the AMP bridge, if that was even what caused this before.
