### ISSUE TITLE
TTYPE negotiation with MUDRammer client

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1165]
#### Brief summary of issue / Description of requested feature:
A player linked me a discussion with the developer of the Mudrammer client in which they seemed to have issues with ttype negotiation. The relevant bits are here:
```
@Roz I connected to Arx with the debugger attached. Arx does engage in TTYPE negotiations with the client, which rather directly contradicts Arx's own in-game help on the @color command that you posted above.

Arx says DO TTYPE
MUDRammer says TTYPE MUDRAMMER
Arx says SEND TTYPE (per RFC 1091, if the server rejects a terminal type, the server can enumerate multiple ttypes in the client by requesting ttype again)
MUDRammer says TTYPE XTERM
Arx says SEND TTYPE
MUDRammer says TTYPE ANSI
Arx says SEND TTYPE
MUDRammer says TTYPE ANSI (MUDRammer has exhausted its list of ttypes and signals this by repeating the last ttype a second time)
It appears that Arx rejected all of MUDRammer's ttypes and ended up with ANSI, either because it was the default or because it was the last one that MUDRammer sent.

So... is it a bug in MUDRammer or in Arx? Probably both? ¯\_(ツ)_/¯
```
Link to the full thread: http://musoapbox.net/topic/1382/mudrammer-help/18

#### Steps to reproduce the issue / Reasons for adding feature:

1. TTYPE negotiation for MUDRammer appears to fail

#### Error output / Expected result of feature
Lack of ANSI color in game

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
See above thread/quoted text.

**Comment by Griatch** [comment]
@TehomCD: From what I understand from that thread, ANSI colors work, but xterm256 does not? I think this was a bug with Evennia's TERM check; fixed that but I can't test Mudrammer so I'll keep this open for now until your user confirms the fix was successful.

**Comment by TehomCD** [comment]
Players confirmed that the fix was successful and they can now see xterm256 on mudrammer. Thanks a ton!
