### ISSUE TITLE
Alias handler's clear method removes more than aliases

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1170]
#### Brief summary of issue / Description of requested feature:
The alias handler manages aliases for objects, which are alternate names for them, like nicknames used for reference.

When renaming an object, I also remove old aliases and begin again.  Using `object.aliases.clear()` calls the alias handler to clear them on the referenced `object`, but it also removes other things from the object that aren't aliases!

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create an `object` or use an existing object.
2. Give the `object` some tags and aliases
3. Run `object.aliases.clear()`

#### Error output / Expected result of feature
Examining the object reveals that not only are the aliases gone, but tags were removed, also.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Latest evennia, master branch, all OS.

Looking at the database, it seems that tags (and some other things) are stored in the same table as the aliases. Apparently, all table entries related to the object are removed, not just the aliases.  Aliases have the db_tagtype field set to "alias" in the typeclass_tag table, but there are others, such as "permission" and `NULL` (I'm assuming these are tags) stored there.  So it looks like the records in the objects_objectdb_db_tags table that match the objectdb_id are being removed, regardless of the db_tagtype field in the typeclass_tag table.  Digging into how the alias handler removes aliases might be where the bug (if this is unintended behavior) lies.

**Comment by Griatch** [comment]
I think the use of the `db_tagtype` in the handler got lost somewhere along the way; not sure how that regtession happened. I have a local dev branch looking into this but this is the first example of an adverse effect prompting fixing.
