### ISSUE TITLE
Feature Request: Rename "Player" to "Account"

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1174]
#### Description of requested feature:

Rename the `PlayerDB` database model to `AccountDB`. Rename its child typeclass from `DefaultPlayer` to `DefaultAcccount` and `Player` to `Account`. 

#### Reasons for adding feature:

A common source of confusion in Evennia is the separation between "Player" and "Character". The problem is that "Player" is usually what our "Character" is called in other code bases. 

The "Player" is an OOC entity whose main purpose is to act as the central account for the connected user - it holds the password info and any global settings. While we won't rename Character, renaming Player to Account should hopefully make it very clear how this relationship works, with no confusion as to what the Account level is or that multiple Characters are sharing a single Account instance. 

An effect of this change is the renaming of the use of "player" in other places of Evennia to "account", such as on Commands. 

#### Extra information

This is such a major API change that it belongs in a development branch leading up to Evennia 0.7. It must also come with database migrations and detailed help on how to update a game to use the new naming scheme.

**Comment by Griatch** [comment]
It would be good with more people trying to migrate their databases to see the process is stable across many different uses. Here's the process (it will be documented more fully when devel is released for real):

0. First make sure you have pulled and migrated everything to the latest on `master` branch. Make a copy of your entire `mygame` dir just to be safe!
1. From your evennia repo, run `git checkout -b devel origin/devel` - this will download and place you on Evennia's current devel branch (which is not yet ready for production!)
2. Run `pip install -e .` This will fetch the latest dependencies needed by Evennia 0.7. 
3. In `evennia/bin/` is a program `project_rename.py`. Copy this to the top of your `mygame` folder.
4. `git checkout player-account-step1` - this will place you in an "detached HEAD state", at an earlier point of the migration history, where both `player/` and `account/` still co-existed (the rename program is not included yet at this point so make sure you copied it befor this).
4. We must rename all mentions of "Player" in your game dir to "Account". Go to your `mygame` folder and launch the rename program you copied like this: `python project_rename.py -i 'a player' -o 'an account' -i 'player' -o 'account' -x '*/migrations/*' -x '*/mssp.py' -r .` This starts an interactive program I've written that interactively renames all occurrences of "Player" in all your files. You should generally accept all renames unless you know you have added your own stuff separate from Evennia or is using `Player` in some other context (such as in a doc string). Use `h` in the program for help. If you don't want interactivity, add `-a` as a flag to the command.
5. Still in your `mygame` folder, make sure your virtualenv is active and run `evennia migrate`. This migrates your old database to a state where Player and Account co-exist and Account is a copy of Player. 
6. Once you have migrated, go back to `evennia/` a second time and run `git checkout devel`. You are now back at the latest Evennia devel version. 
7. Back to the `mygame` folder again, for good this time.  Enter `evennia dbshell`. This brings you into the command shell for your database. What you want to do is to delete the contents of the `django_migrations` table. In sqlite3 (default) you do this with `delete from django_migrations;`. You can then exit the shell with `.exit`. 
8. Run `evennia migrate --fake`. We rebuild the migration history as if "Player" was always named "Account".
9. Run `evennia migrate --fake typeclasses 0007`. This steps us back so we can re-run a few migrations we faked in the step before but which we really need to run. 
10. Run `evennia migrate`. The last few migrations are re-run, which finalizes the migration and removes the last vestiges of "player" from the database.

You should now have converted your old database to use Account instead of Player everywhere. You should be able to start and run as normally, except everything previously named Player, PlayerDB, DefaultPlayer, PlayerCmdset etc is now Account, AccountDB, DefaultAccount, AccountCmdset and so on. Report any problems with the migration process here (but note that devel branch could have other issues since it's not yet finished)!

**Comment by TehomCD** [comment]
I got an unrecognized argument error in trying to run the `project_rename.py` script. Here's the pastebin: https://pastebin.com/BRPyjsGv

Also, when running `pip install -e .` should it not install any new dependencies and make no mention of it being evennia 0.7.0? I double checked that I was on the devel branch and had pulled from upstream, but wasn't sure if I was missing anything there.

**Comment by Griatch** [comment]
Hm your invocation works for me on Linux. I wonder if Windows don't understand `'` as a replacement for `"`. What happens if you use `"` instead?

As for `pip install -e ., this should be `pip install --upgrade -e .` maybe you tried it before I upgraded the post. :)

**Comment by TehomCD** [comment]
Aha! It works with `"`. Hm, there might be something wrong with trying to upgrade the requirements in windows. I switched back to HEAD for the devel branch to try to run `pip install --upgrade -e .`, and it still didn't grab the new requirements. For example, I'm still at django 1.9, and trying to run `evennia start` as a test throws an error about it. I can just install all the dependencies manually, but no idea why that's not working for me.

**Comment by Griatch** [comment]
@TehomCD Good, I updated it to use `"` instead. And oh - you are on Windows. I haven't updated requirements_win.txt, my bad, hold on.

**Comment by TehomCD** [comment]
Small issue with rename script - it seems to be slightly off with preserving capitalization on replacement lines. It renames `AccountOrNpc` into `PlayeroRnPc`.
```
(arx) c:\arx\arx>python project_rename.py -i "AccountOrNpc" -o "PlayerOrNpc" -i "assets.account" -o "assets.player" -i "
AccountAccount" -o "PlayerAccount" -x "*/migrations/*" -x "*/mssp.py" -r .
 20 orig: from world.dominion.models import (CraftingMaterialType, AccountOrNpc, CraftingMaterials)
    new : ←[33mfrom world.dominion.models import (CraftingMaterialType, PlayeroRnPc, CraftingMaterials)←[0m
215 orig:                 dompc = AccountOrNpc.objects.get(account=caller.account)
    new : ←[33m                dompc = PlayeroRnPc.objects.get(account=caller.account)←[0m
216 orig:             except AccountOrNpc.DoesNotExist:
    new : ←[33m            except PlayeroRnPc.DoesNotExist:←[0m
←[32m.\commands\cmdsets\market.py (3 lines changed)←[0m
←[32mchoose: [q]uit, [h]elp, [s]kip file, [i]gnore lines, [c]lear ignores, [a]ccept/save file: ←[0mq
Quit renaming program.
```

**Comment by TehomCD** [comment]
Finished going through the process. The migrations themselves seemed to run with no errors, though the comms 14 (I think?) migration took a really long time for me. I let it run overnight, so I'm not certain exactly how long (maybe half an hour before I stopped watching?), but you might want a warning note similar to your Tags/Attribute migration before that things might take a really long time so people don't think it's hanging on them.

**Comment by BlauFeuer** [comment]
@Griatch Just a note that the version in `@about` still displays "Evennia 0.6.0 (rev ac65c9f)"

**Comment by BlauFeuer** [comment]
For the first migration I tested, the server started, but when trying to stop, gives the following error:

https://pastebin.com/g9DHb21Q *in case Cloud_Keeper or anyone else wants to peek at it*  His typeclasses/ircpuppetbot.py is found here: https://bitbucket.org/Cloud_Keeper/ircpuppetbot

**chainso**l: Blau: Looks like it's unpickling whatever is in db.bot. What a fun exception!

Second of 4 I have to test was a database with 100000+ objects in it, and updated flawlessly, though the migration steps that involve "Applying typeclasses.0008_lock_and_perm_rename..." did take awhile, which wasn't surprising.

I'll do the next two over the weekend and might have more feedback.

**Comment by BlauFeuer** [comment]
Tested 2 of 4 unique game code + database

#### 1. Puppetbots
The first migration I tested was the IRC Puppetbots by @CloudKeeper1 , the server started, but when trying to stop, gives the following error:

https://pastebin.com/g9DHb21Q *in case Cloud_Keeper or anyone else wants to peek at it*  His typeclasses/ircpuppetbot.py is found here: https://bitbucket.org/Cloud_Keeper/ircpuppetbot

**chainso**l: Blau: Looks like it's unpickling whatever is in db.bot. What a fun exception!

I followed the db.bot trail and believe that the picked reference to the bot account was causing the problem, since the migration step didn't reach it and it's no longer pointing to a valid account object. Removing the ircbot-PM-listener(#896) object made the error go away, but I'm not sure of a clean way to  regenerate it properly, other than perhaps delete and remake the PM(#14) account.  I'll leave it up and running and maybe Cloud_Keeper can peek in or leave me a note on how to remake the bot.

Otherwise, the database migrated and the game runs and stops normally after removing the object (though I think it was simply the "bot" attribute on that object).

#### 2. Large Database converted from another mu*
Second of 4 I have to test was a database with 100000+ objects in it, and updated flawlessly, though the migration steps that involve "Applying typeclasses.0008_lock_and_perm_rename..." did take awhile, which wasn't surprising.

**Comment by TehomCD** [comment]
Is it possible to use bulk_create for the updates in the comms migration `0014_auto_20170705_1736.py`? It looks like it's iterating through each Msg object and adding accounts in place of the existing players, which takes a very long time when you have over 30k Msg objects in the database. I've used bulk_create in the past specifically for Msg objects for letting players mark many Msg objects as 'read' simultaneously, using bulk_create on the through model that represents the many-to-many relationship so that a player marking all Msg objects as read didn't lock up the game for a noticeable amount of time.

I'm not certain if it'd work in this case, but it'd be something like this for each different relationship, if you think it'd work:
```
        MsgAccountReceiverThroughModel = Msg.db_receivers_accounts.through
        bulk_list = []
        for msg in Msg.objects.filter(db_receivers_accounts__isnull=False):
            for player in msg.db_receivers_accounts.all():
                account = AccountDB.objects.get(id=player.id)
                bulk_list.append(ReadJournalModel(accountdb=account, msg=msg))
        MsgAccountReceiverThroughModel.objects.bulk_create(bulk_list)
```

**Comment by TehomCD** [comment]
It looks like players inside attributes are raising errors in dbserialize when it tries to figure out what to do with them:
```
Traceback (most recent call last):
  File "c:\fresh_evennia\evennia\evennia\commands\cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File "c:\fresh_evennia\evennia\evennia\commands\default\unloggedin.py", line 238, in func
    session.sessionhandler.login(session, account)
  File "c:\fresh_evennia\evennia\evennia\server\sessionhandler.py", line 481, in login
    account.at_post_login(session=session)
  File "c:\fresh_evennia\testarx\typeclasses\accounts.py", line 129, in at_post_login
    super(Account, self).at_post_login(session)
  File "c:\fresh_evennia\evennia\evennia\accounts\accounts.py", line 744, in at_post_login
    self._send_to_connect_channel("%s connected" % self.key)
  File "c:\fresh_evennia\evennia\evennia\accounts\accounts.py", line 715, in _send_to_connect_channel
    _CONNECT_CHANNEL.tempmsg("[%s, %s]: %s" % (_CONNECT_CHANNEL.key, now, message))
  File "c:\fresh_evennia\testarx\typeclasses\channels.py", line 213, in tempmsg
    self.msg(message, senders=senders, header=header, keep_log=False)
  File "c:\fresh_evennia\evennia\evennia\comms\comms.py", line 341, in msg
    self.distribute_message(msgobj, online=online)
  File "c:\fresh_evennia\evennia\evennia\comms\comms.py", line 275, in distribute_message
    if entity in self.mutelist:
  File "c:\fresh_evennia\testarx\typeclasses\channels.py", line 80, in mutelist
    if self.db.mute_list is None:
  File "c:\fresh_evennia\evennia\evennia\typeclasses\models.py", line 117, in __getattribute__
    return _GA(self, _GA(self, 'name')).get(attrname)
  File "c:\fresh_evennia\evennia\evennia\typeclasses\attributes.py", line 458, in get
    ret = ret if return_obj else [attr.value for attr in ret if attr]
  File "c:\fresh_evennia\evennia\evennia\typeclasses\attributes.py", line 143, in __value_get
    return from_pickle(self.db_value, db_obj=self)
  File "c:\fresh_evennia\evennia\evennia\utils\dbserialize.py", line 602, in from_pickle
    dat._data.extend(process_tree(val, dat) for val in data)
  File "c:\fresh_evennia\evennia\evennia\utils\dbserialize.py", line 602, in <genexpr>
    dat._data.extend(process_tree(val, dat) for val in data)
  File "c:\fresh_evennia\evennia\evennia\utils\dbserialize.py", line 560, in process_tree
    return unpack_dbobj(item)
  File "c:\fresh_evennia\evennia\evennia\utils\dbserialize.py", line 390, in unpack_dbobj
    obj = item[3] and _TO_MODEL_MAP[item[1]].objects.get(id=item[3])
AttributeError: 'NoneType' object has no attribute 'objects'
```
That was from trying to log in and the announce channel distributing the message, which brought up the mute list, which is a list of players.

**Comment by Griatch** [comment]
@TehomCD : Hm, that is a pretty serious case. I suspect the problem is that the pickle module stores the class and when it unpickles it can no longer find it and returns None. Maybe I have to add another migration that tries to identify the serialized Player-class string in the database and convert it.

**Comment by TehomCD** [comment]
I wonder if there'd be any way for us to tell it if a model has been renamed when Attributes unpickle things? I would guess this same error would happen if a user renamed any model that could be stored in Attributes. I have no idea if it'd be feasible to check that somewhere, like in the table django creates for recording stuff about migrations or content types or whatever.

**Comment by Griatch** [comment]
@TehomCD No, there is no way to tell this at pickle-time - loading the class is a part of the pickle module itself which we don't have access to. Only thing we can do is to process the serialized data in string form while it sits in the database. So it's something that might be possible to doin a migration, but hardly a run-time I'd think.

**Comment by Kelketek** [comment]
@Griatch During the migration, you might Monkey-patch the models file to have a reference to Player that points to the new Account model, and then load all attributes and resave them. The loading might use whatever path is stored in the pickling, while the saving probably would use the actual class path.

**Comment by BlauFeuer** [comment]
"player object references inside an attribute" is the issue I had with the puppet bot listening object referencing the "player" account in an attribute named "bot".  I had to remove and remake the object to have the reference to the new `ircbot-PM` account in the `ircbot-PM-listener(#896)` object.

The most recent issue I had was with an object that had no permissions set at all, which required a code patch to proceed.

I still have more code and databases to test, but it has been an otherwise straight-forward process thanks to Griatch's work.

**Comment by TehomCD** [comment]
One possibility to do this at pickle time is maybe using ServerConfig to store a list of tuples of the natural keys it uses for the `TO_MODEL_MAP` dict to a path to a classname that the model has been replaced with, then updating the `TO_MODEL_MAP` with that key and the imported class. You could add this process as an evennia manager command, like `evennia post_table_rename <old natural key> <path to new class>` and specify people run this if they ever rename one of their models that could be stored in Attributes.

**Comment by Griatch** [comment]
@Kelketek You already changed your mind on this suggestion but, apart from efficiency, I'm not sure how you could use a model to fake its type so pickle is happy and takes the "wrong" one of your chosing. In py3 an object can dictate what type it appears as, not so in 2.7. For that matter, the `players` package is gone, so one would then need to introduce this in the git tree only for that single migration ...

@BlauFeuer Yeah, it's great feedback. I simply didn't consider pre-saved Attributes and that they store the class reference. We definitely need a migration for those. 

@TehomCD This is such a niche thing that I can't help but think it's not a complexity we should hide away. You should really handle it manually if it is an issue. It's also hard to generalize since this problem is not unique to Database models, but all Python classes - if you save a class instance and then delete the class definition, pickle will balk at you, typeclass or dbserialize nonwithstanding.

**Comment by Griatch** [comment]
@TehomCD, @BlauFeuer I have pushed a hotfix for the player-in-attribute thing. After looking at how to do this, I concluded it's not really possible to do in a migration. The reason is that the picklefield will process the return through the dbserializer before I can get to it in the migration. Alternative would be to deal with serialized pickled code in SQL, which I don't feel like doing. So I have instead followed advice in this thread and added `settings.ATTRIBUTE_STORED_MODEL_RENAME`, which allows for the dbserializer to translate a renamed model class to another at load-time. For this to work it must be a straight rename, with matching pk's, creation dates etc - what it does is simply tell the serializer that what it tries to load should be mapped to a different natural-key than the one it was saved with. 

It would be interesting if you would try this with your databases. I won't help on already lost Players though, those Attributes are already `None` at this point. But since it's not a migration it will apply dynamically.

**Comment by BlauFeuer** [comment]
The effect of that issue on me was strictly with the irc bot account, and I didn't lose the account, I just lost the attribute on the listener object that pointed to it

The missing attribute was regenerated during the process of reconnecting the bot.  It took awhile for me to fully understand that it was caused by this issue.  I'll try pulling the update and migrating the database again.

**Comment by TehomCD** [comment]
No more tracebacks! old playerdb objects will return as None due to ` return _TO_DATESTRING(obj) == item[2] and obj or None`, since the datestring of `db_date_created` for the player object and their new account object don't match. Easy enough to just add a hacky check before it, though:
```
    if item[1] in [(u"players", u"playerdb"), (u"typeclasses", u"defaultplayer")]:
        return obj or None
    return _TO_DATESTRING(obj) == item[2] and obj or None
```
is what I did to check that they'd return normally.

**Comment by Griatch** [comment]
@TehomCD Hm, that hack will not cover custom Player objects, which is why I didn't hard-code it this way but used a setting. I didn't think the datestring would be different since I copied these over on the SQL level ... but maybe the datestring check should be ignored overall when matching the `ATTRIBUTE_STORED_MODEL_RENAME`  setting.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
