### ISSUE TITLE
Task: Reduce number of alerts found with LGTM Static Analysis Tool

### ISSUE THREAD

**Issue by robbintt** [evennia/evennia#1176]
This tool might be helpful for starting to secure and harden Evennia.

https://lgtm.com/projects/g/evennia/evennia/alerts/

**Comment by Griatch** [comment]
Thanks for the link, looks interesting. I rephrased this issue into something actionable and made it a long-term task.

**Comment by Griatch** [comment]
While this task is essentially endless, I think us bringing down the number of alerts from hundreds and hundreds to a mere 20, most of which might be invalid as alerts, seems like a good spot for considering this task complete.

**Comment by robbintt** [comment]
Cool!!  I'm glad this helped.
