### ISSUE TITLE
Feature Request: Make scripts valid message senders

### ISSUE THREAD

**Issue by SquirrelFu** [evennia/evennia#1179]
#### Brief summary of issue:
For those of us familiar with MUSH systems as staffers, we likely know about job systems. In my efforts to create one for my own MUSH, I ran into a snag. Specifically, that I could not set the job handler script as a message's sender as it only supports objects, players, and external sources as senders.

#### Steps to reproduce the issue:

1. Create a new message manually with create from evennia.utils
2. Pass a script object as the sender
3. Watch the system bork itself up (Optional)

#### Error output
In concrete terms, any attempts to send a message with a script as a sender results in a None-type object being saved to the field. This can cause significant issues when attempting to display or retrieve the message later. Hence, any attempts to do so tend to throw an AttributeError.

#### Extra information: 
Well, the basic idea I have is adding the script DB as a valid list of objects (In the object-oriented coding sense) to compare the incoming script against. I'm not sure if there is a reason here, but it seems to be problematic what I was attempting to do.

**Comment by TehomCD** [comment]
You can attach tags to Msg objects with arbitrary data, so for custom models I have that I wanted to associate with Msg objects, I just made tags of a category that identified the model and then made a tag that corresponded to some combination of the model/id to identify it uniquely. You could do the same by having tags like `msg.tags.add("script_15_sender", category="script sender")`

**Comment by Griatch** [comment]
This is not a bug but a well-documented feature of Msg:es. They originally only supported Players, but was extended to also support ObjecDBs by popular demand. We could by all means extend it to Scripts too, there was just never a reason to.

Changed to a feature request.

**Comment by Griatch** [comment]
Moved to devel for Evennia 0.7.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
