### ISSUE TITLE
Bug: A bug in evennia.js's msg function.

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#1192]
#### Brief summary of issue / Description of requested feature:
Line 127 in evennia.js's msg function:
        msg: function (cmdname, args, kwargs, callback) {
            if (!cmdname) {
                return;
            }
127            kwargs.cmdid = cmdid++;
If the kwargs is null, an error may occur.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Send a message from the webclient to the evennia server.

**Comment by Griatch** [comment]
Since you have full control of the client it is up to the client to correctly format the messages sent to the server. So this should never happen. But I put in a check for it nevertheless. :)
