### ISSUE TITLE
EvEditor with basic handling of code

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1203]
#### Brief summary of issue / Description of requested feature:

As promised, I'm working on my PR to add a new keyword, `code`, to the `EvEditor`.  This keyword, if active, will add a few additional commands to the `EvEditor` and will handle basic indentation.  But there are some problems in manual indenting.

#### What works

So far, it works pretty well.  Automatic indentation is handled if it uses standard Python keywords, like if or finally.  It's sometimes necessary to reduce the indentation level, because there is no keyword to close a for, while or if statement in Python.  There's the `:-` command which decreases by one level the following indentation and it works.

The `:+` does the same thing (in reverse, increasing indentation level by 1) and the `:=` command switches manual indentation on or off.

#### What doesn't work

Manual indentation doesn't seem to work.  When I set it on (with the `:=` command), when I enter code beginning by spaces to represent indentation, Evennia seems to remove these spaces automatically.  I can understand why it would do so... but in this context, it's a pain.  What work around do you think I could use?

Manual indentation is useful if you want to copy/paste code, for instance: indentation is already there, you don't need to use automatic indentation, and it could actually create errors.

If you want to see the source code, it's here (I will open the PR when I fix this bug): https://github.com/vlegoff/evennia/blob/evcode/evennia/utils/eveditor.py

**Comment by Griatch** [comment]
If you want feedback or help, please make this into a Push Request and write that it's "WIP" while you are working on it. Closing.
