### ISSUE TITLE
Feature Request: collecttemplates

### ISSUE THREAD

**Issue by titeuf87** [evennia/evennia#1210]
#### Brief summary of issue / Description of requested feature:
Currently when modifying static files in Evennia, you have to use `evennia collectstatic` before they actually get used. When modifying templates this is not the case and your changes go through immediately.

It would be nice if there was a `evennia collecttemplates` that works for templates, the same way how `collectstatic` works. The reason for this is that if you change css or javascript files, then very often, you also need to change the templates.
It is weird that the changes in the templates already get applied while missing eventual css/js changes that are also needed.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Maybe instead of a separate `collectstatic` and `collecttemplates` having one `collectweb` is more desirable?

**Comment by Griatch** [comment]
So templates are updated immediately while other files require collectstatic.. so you run collectstatic and templates work on their own. What is the problem here?

**Comment by titeuf87** [comment]
It's not a problem. More of an inconsistency.
To give an example: someone on irc showed his mud. He had the latest Evennia changes pulled in but because he did not run collectstatic, it looked wrong: the options button of the webclient was displayed, but the css to skin it or the js to handle it was not present cause that one needed collectstatic.

It is a really minor thing though and not that important, just more of a nice to have to keep handling of templates and static files consistent with each other. Totally fine if this gets closed :)

**Comment by Griatch** [comment]
Collectstatic is actually run automatically when you start Evennia, you might have to do a full shutdown though. Either way this is not really an inconsistency; static files and templates are different things. Their behavior is how Django works.

**Comment by titeuf87** [comment]
Okay, fair enough! Didn't know it was different in Django too. Good to know.
