### ISSUE TITLE
Task:  Convert deprecated {- markup in code/contribs/tutorials toward full deprecation.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1212]
#### Brief summary:
Use of `{` in markup (or rather, Evennia responding to it) causes unintentional markup when someone is using the braces to demonstrate code or for other reasons.

An ongoing task should be to update markup in modules that are edited or receive PRs, and eventually to any remaining depreciated markup in isolated modules.

#### Reasons for making a task of converting:
Use of depreciated markup in code/contribs/tutorials perpetuates further use, which slows the migration to the current markup.   A task would encourage contributors to update markup in submitted code, and remind me to update modules as I have the time.

#### Error output / Expected result of feature
At some future point, Evennia should stop interpreting `{` as markup by default.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Perhaps first step should be use of a setting to opt out of responding to depreciated markup by 0.7.0 (Ability with setting to choose to turn off responding to `{`), then off by default in 0.8.0 (Ability with setting to choose to turn it on), and finally only by user-defined extension by 0.9.0. This progression would be slow and deliberate.

**Comment by Griatch** [comment]
Actually I would suggest a (potentially) faster process: Once the core Evennia is stripped of the use of deprecated `{`-type color tags, we leverage Tehom's color-plugin system and move the `{`- type color codes into a contrib. From there people can just plug it back in if they want it. We could even add `%c` type tags in the same contrib for those that want that.

**Comment by BlauFeuer** [comment]
#1228 should be the last of the old markup changeover.  IRC bot still has old markup in `IRC_COLOR_MAP' dictionary, but Tehom's color-plugin system should handle allowing alternate markup after full deprecation occurs, which potentially could take place in the 0.7.0 dev

**Comment by Griatch** [comment]
@BlauFeuer Ok, excellent! I'm closing this and opening a new task for the moving of the deprecated markup into a contrib for use with @TehomCD 's new color settings (that one will go into devel).
