### ISSUE TITLE
Higher permission levels can't control lower

### ISSUE THREAD

**Issue by stephenvogler** [evennia/evennia#1223]
#### Brief summary of issue / Description of requested feature:
A player with Immortals permission cannot pass the control lock of lower objects. Easy enough to redo, but it seems this should be default behavior according to the wiki.

#### Steps to reproduce the issue / Reasons for adding feature:

1. From non-superuser immortal, @perm/player <another player> = builders
2. Receive message that you don't have permission to edit that object.
3. You can add permissions to the character, but that doesn't give them access to the build commands

#### Error output / Expected result of feature
You are not allowed to edit this object's permissions / players should be able to grant permission up to their level

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Running current branch

**Comment by BlauFeuer** [comment]
Not sure if this is just a typo or the actual problem, but in step 1...

`@perm/player = builders` should be `@perm/player <player name> = builders`

Otherwise, you're attempting to give the player named `<empty string>` permission to build.

**Comment by stephenvogler** [comment]
Yeah, it was a typo. The command works fine from superuser. The actual issue comes down to players not passing the control check.
