### ISSUE TITLE
Failures on 2 unittests

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1234]
#### Brief summary of issue / Description of requested feature:

I get a repeated error when running 'evennia test evennia' even from a fresh install.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Run `evennia test evennia` (the game directory could have been created just previously, without any changes to the default configuration).

#### Error output / Expected result of feature

```
======================================================================
FAIL: test_cmdgametime (evennia.contrib.tests.TestExtendedRoom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\vincent\src\mud\evennia\evennia\contrib\tests.py", line 219, in test_cmdgametime
    self.call(extended_room.CmdGameTime(), "", "It's a spring day, in the evening.")
  File "c:\users\vincent\src\mud\evennia\evennia\commands\default\tests.py", line 83, in call
    raise AssertionError(retval)
AssertionError: 
==============================Wanted message==================================
It's a spring day, in the evening.
==============================Returned message================================
It's a spring day, in the afternoon.
==============================================================================

======================================================================
FAIL: test_return_appearance (evennia.contrib.tests.TestExtendedRoom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\vincent\src\mud\evennia\evennia\contrib\tests.py", line 198, in test_return_appearance
    self.assertEqual("evening", self.room1.ndb.last_timeslot)
AssertionError: 'evening' != 'afternoon'

----------------------------------------------------------------------
Ran 193 tests in 31.328s

FAILED (failures=2)
```

**Comment by BlauFeuer** [comment]
I'll give this a try.
## Only a fresh install, current version:

>> Ran 193 tests in 66.773s
>> OK
>> Destroying test database for alias 'default'...

## On my game code, with working database:

>> Ran 193 tests in 68.380s
>> FAILED (failures=4, errors=1)
>> Destroying test database for alias 'default'...

I've customized some messages and commands and removed some default commands in my own game, so I expect it to fail some tests.

**Comment by Griatch** [comment]
Looks like there may be a time dependence remaining in the unittest that does not appear for me and Travis since the TravisCL time zone is similiar to mine. :)

**Comment by vlegoff** [comment]
Another user reported to have the same error on Windows.  I wonder if it's not operating system-related.  I ran the tests using my own time zone (in UTC-8) or the default time zone (UTC 0) and got the same error, but it doesn't prove anything, of course.

**Comment by Griatch** [comment]
@vlegoff I cannot replicate this on Linux. I did a test change to the unit test to see if that could be caught. Could you try again with your setup?

**Comment by vlegoff** [comment]
Unfortunately it still fails... there is even an additional test that fails now, `FAIL: test_return_appearance (evennia.contrib.tests.TestExtendedRoom)`.  Here's the traceback, if it helps you in any way:

```
FAIL: test_return_appearance (evennia.contrib.tests.TestExtendedRoom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\vincent\evennia\evennia\contrib\tests.py", line 196, in test_re
turn_appearance
    self.room1.return_appearance(self.char1))
AssertionError: '|cRoom(#1)|n\nA spring description.\n|wExits:|n out(#3)\n|wYou
see:|n Obj(#4), Obj2(#5), Char2(#7)' != '|cRoom(#1)|n\nroom_desc\n|wExits:|n out
(#3)\n|wYou see:|n Obj(#4), Obj2(#5), Char2(#7)'
```

**Comment by vlegoff** [comment]
The problem seems partially resolved for 1 test, but still there for two.  After some debugging, I confirm that the problem is in time zones:

`ExtendedRoom.get_time_and_season` creates a `datetime` from a timestamp, which is affected by the time zone of my computer (not influenced by Evennia's settings).  Since I'm in UTC - 8, when it runs on 2975000766L, Python tells me it creates a `adatetime` that corresponds to `2064, 4, 9, 14, 6, 6`.  If I create the same date using naive notations:

```python
(Pdb) !datetime.utcfromtimestamp(2975000766L)
datetime.datetime(2064, 4, 9, 21, 6, 6)
```

So whether we specify it or not, `datetime.fromtimestamp` works with the system's time zone, which isn't influenced by Evennia's settings as far as I could tell.
