### ISSUE TITLE
Webclient and auto-scroll for screen reader users

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1241]
#### Brief summary of issue / Description of requested feature:

When new messages are appended in the web client, the cursor is moved back in the input area automatically, which means reading with a screen reader is very difficult if the game sends in updates on a regular basis.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Download a screen reader? Seriously, if you're willing to try, you can download [NVDA](https://www.nvaccess.org/download/) which is free and open-source.
2. Open the web client, and start reading in browse mode (more on that below, if needed).
3. Wait for a message to arrive on the web client, don't leave the window if possible.

#### Error output / Expected result of feature

No error.  The expected result is a bit tricky: should the user use a screen reader, I suggest automatic moving of the cursor in the input area be deactivated.  I'm not sure if there's a proper way to know whether a screen reader is active in the browser.  Probably, but I can't confirm it.  Other, less elegant solutions, would be to have a checkbox or an option to disable auto-focus.

#### Accessibility detail:

I'll try to summarize the issue as best I can: when using a screen reader to navigate through the web, the screen reader is usually in what we call "browse mode", meaning there's a virtual cursor that enables users to use their arrow keys and browse through the page like a normal document.  This browse mode isn't only used in browsers, incidentally.  One can use shortcut keys to navigate more efficiently in the page.  For instance, when I'm in browse mode with NVDA, I can type h to have the virtual cursor placed on the next heading.  When editing, screen readers move into a different mode: it's not browse mode anymore, keys are sent to the browser, which allows to write.  Users can navigate between both modes.

So when I open the webclient, I'm in browse mode.  I can use the arrow keys to read the text.  When I want to type a command, I type e (move to the next Edit field), then enter (to switch from browse mode to edit mode), type in my command, press Enter.  The text will be read by the screen reader as it's sent by the server (this is a nice feature by the way).  I'm still in edit mode by that point, so I can type in several commands.  But when I want to leave this field to browse, there's a problem: everything would work at first, I quit edit mode (pressing escape) and navigate using the arrow keys.  But if a new message is received by the webclient, it moves the cursor back to edit field.  I guess this is a single line of Javascript.  It makes things difficult to read with a screen reader in browse mode.

I hope I explained it right, but don't hesitate to comment!

**Comment by Griatch** [comment]
This sounds like something we should definitely add;  it's excellent to get your perspective on this. Maybe it's something that could automatically switch on when activating the screenreader mode.

**Comment by friarzen** [comment]
As of 0.8, the new webclient auto-focuses on keydown, instead of when a message is received, so I'm wondering if it still exhibits the same behavior.  Can this be retested/updated for any problems?

**Comment by vincent-lg** [comment]
After some testing, I can safely say: the last changes have improved the webclient's accessibility.  The  auto-focus bit is still a little problematic (because we tend to use the keyboard a lot and sometimes, the screen reader will pass the key to the webclient, which makes it a bit unpredictable at times) but the auto-focus on scrolling doesn't happen at all.  In fact, if we are reading the previous messages in the output window, and one appears at the bottom, the virtual cursor doesn't even shift, making reading very comfortable.  So I think we could close this issue.
