### ISSUE TITLE
Extra symbols being added to messages and cannot be removed by normal means.

### ISSUE THREAD

**Issue by Kalman98** [evennia/evennia#1245]
This seems to me to not fit the ordinary categories for the issue tracker, so hopefully it will be alright that I didn't use the template. Well, here we go:

I've been working on my own MUD server using Evennia (https://github.com/Kalman98/acton), and as I am knew to the software in general I have been using the Tutorial docs a lot. At the same time, I have a friend who is using an NPM package to create a MUD client bot for our private chat (running Rocket.Chat, for the record). The chat server does not understand ANSI formatting and thus all messages received from the MUD server were riddled with visible ANSI codes. I found the tutorial on "Manually Configuring Colour" in the Tutorial Docs, which I followed to add an "@togglecolor" command. However, the code listed on the wiki did not work. It suggested that you create a new character class and overload the `msg()` function with this code:

```
text = ansi.parse_ansi(text, strip_ansi=True, xterm256=False, mxp=False)
super(Character, self).msg(text=text, from_obj=from_obj,
                                                 session=session, **kwargs)
```
That code did nothing, only sending the message as usual with the same ANSI formatting. So I did some research on my own and came up with the evennia.utils.ansi.strip_ansi() function. I updated my code, replacing the parse_ansi line with the strip_ansi function, and viola, it worked! Almost. All color codes and formatting was gone except for at the end of message. At the end of every message sent to the client from the server, there is a "[0m " attached. Like this:

```
Server restart initiated ...[0m
Server restarting ...[0m
... Server restarted.[0m
 ```

I couldn't figure out what the problem was, so I went to the developer chat to see if I could get some help. You can find the log of that here:

https://irclogs.jackgrigg.com/irc.freenode.net/evennia/2017-03-06#i_4050796

From that conversation we seemed to find that msg() should be passed the `ansi: False` kwarg in order to make it stop adding any formatting at all. We found this in `server/portal/telnet.py`. It seems that a flag called "TTYPE" needs to be set in order for the ansi tag to do anything, but unfortunately I have no idea what that means or how it would work. We tested the `raw` kwarg as well, which looked like it should produce the same result. The raw tag never seemed to make it through, however, and so I'm not sure why it is even there.

To attempt to sum things up, as the title says, even when I strip_ansi my messages, some extra characters get added to the end, and we have not been able to find a way to remove them without directly modifying the Evennia source code.

vincent-lg helped me a whole lot on the chat with figuring out where things were going wrong. So thank you to him. :smile:

**Comment by BlauFeuer** [comment]
Have you tried `@option NOCOLOR=True` to toggle off color?  The tutorial is quite the long way around to the problem and is more about the method of overriding `msg`.

For the sake of Telnet and SSH, all lines sent have the ANSI reset appended, no matter if there's any ANSI in the line.  PR #1243 addresses an edge case where lines ending with the markup character would escape the ANSI reset, but it seems you've discovered a need to not always append ANSI reset.  The RAW tag would just send through the markup uninterpreted, Having the output chain respect the ansi kwarg when it's passed into the msg method would be a feature request, I suppose.

**Comment by BlauFeuer** [comment]
Alright, I'll talk to Vincent and other great minds - maybe I can fix it and add it to my PR.

Those extra ANSI codes are bugging me, too, because the IRC bots are adding them, but for some reason they appear as character 0x0F which some people see as a musical note.

**Comment by Kalman98** [comment]
No, I hadn't tried that option. It works _exactly_ as I wanted. For the time being I will use `@option NOCOLOR = True` for non-color clients, thank you for that suggestion. And referring to the musical note, my friend actually sees the character as a little arrow pointing to the left, like this: `<--` It took me forever to figure out what he was talking about.

Also, I feel like I should point out because I forgot to in the main post that I updated the wiki page about Manually Configuring Color to use the strip_ansi function instead, which is why it looks different from what I had mentioned.

**Comment by BlauFeuer** [comment]
The little arrow pointing to the left is the escape character, the first character in all ANSI sequences. The rest of the characters are printable, but don't really make sense if you don't know what the ANSI sequences are.

As for the `@option NOCOLOR=True` You can include the `/save` option like this:
`@option/save NOCOLOR=True`  and that will be the new default for the player on every login, so it doesn't have to be set every time. To undo, use `/clear` See `help @options`

**Comment by Kalman98** [comment]
Status update, courtesy of Griatch in the dev chat:

It turns out I was using `msg()` wrong all along. The following code in my overloaded `msg()` function works perfectly:

```
if not self.db.config_color:
    super(Character, self).msg(text, from_obj=None, session=None, options={"nocolor": True}, **kwargs)
else:
    super(Character, self).msg(text, from_obj=None, session=None, **kwargs)
```

The important part being that you need to pass `options={"nocolor":True}` to the `msg` function. This removes all ANSI formatting on its own _and_ seems to remove the ANSI escape character at the end. So, I think this is "fixed"?

**Comment by BlauFeuer** [comment]
So it seems the solution for this from the client/user perspective is to use `@option NOCOLOR=True` setting, but from the coder side, `obj.msg('Your text here.', options={"nocolor": True})` and that should close this for you!

**Comment by Kalman98** [comment]
@BlauFeuer : ninja'd!

**Comment by Kalman98** [comment]
Okay, closing this issue. Thanks for the help, everyone!
