### ISSUE TITLE
Feature request: auto-rotate of channel log files

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1253]
#### Brief summary of issue / Description of requested feature:
Although log files like `portal.log` and `http_requests.log` will automatically rotate when over a 1MB threshold, the channel logs do not appear to do so, and seem to grow unbounded in size. It might be nice to have something that would automatically rotate log files when they pass over a certain length, while keeping the most recent lines in order to not empty the channel's `/history`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Rotation of channel logs to prevent them from growing too huge

#### Error output / Expected result of feature
Older log files becoming something like `public.log.1` while a new `public.log` is created that has the most recent messages once it passes some threshold defined in settings (or as an attribute in the channel, possibly?)

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I know that twisted has something to automatically rotate logs, but I'm unsure if it'd be best to use that or just something custom for evennia.

**Comment by Griatch** [comment]
I see no reason not to - just need to figure out a sane and safe way to do it to an open file handle.
