### ISSUE TITLE
mIRC reset \017 not translated when received by Evennia from IRC via bots

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1255]
#### Brief summary of issue / Description of requested feature:
The mIRC reset character \017 is not translated when received by Evennia from IRC via bots, and is passed along to other clients instead of being translated into ASCII reset, typically when there's no mIRC color or style preceding the reset in the line of text from IRC.

#### Steps to reproduce the issue / Reasons for adding feature:

1. From Telnet or webclient, view `public` channel traffic from IRC in demo server.
2. When an Evennia bot speaks on behalf of a character or user in an Evennia channel, the reset character is produced.
3.  Observe lines frequently terminated with \017 untranslated from IRC bot

#### Error output / Expected result of feature
Telnet and Telnet-based MU* clients, along with webclient receive untranslated mIRC reset character, SHIFT IN, /017, Control O, 0x0f, character 15, (``) which might be displayed as a visible glyph or might not be - but all clients receive it.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
* The problem appears to be IRC->Evennia coms do not translate the offending character back into ANSI reset sequence. 
* Removing the outgoing translation (Evennia->IRC), as inadvertently done in #1248 solves the symptom, which was a red-herring, allowing me and others to conclude that I had solved the issue.
* The problem is not related to the little "note" character in Potato.
* Some Telnet clients do not display or interpret the offending character, but webclient displays it consistently. If a screenshot or HEX dump of received data will help, I can supply it.

**Comment by BlauFeuer** [comment]
#1367 is a similar somewhat-related issue, however it's an outgoing (Evennia to IRC) translation problem, whereas this one seems to be an IRC to Evennia translation problem for a different code sequence.

**Comment by Griatch** [comment]
@BlauFeuer Actually, Evennia does not convert at all between IRC and ANSI (only the other way around). I have now (in `devel` branch) added support for this in the `irc` module. I don't see IRSSI sending the /0017 reset symbol so I haven't tested that, but it is supported in the regex and now it does handle the first 20 or so mIRC colors (after that they start to repeat). So it works for me but I had no issues with the reset flag before either. if you run devel you could maybe check if this behaves as expected related to this issue?

**Comment by BlauFeuer** [comment]
I'll try migrating over to devel this week - thanks!

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
