### ISSUE TITLE
User clients reporting SCREENWIDTH=0 cause EvMore ZeroDivisionError

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1257]
#### Brief summary of issue / Description of requested feature:
User clients reporting SCREENWIDTH=0 cause EvMore  ZeroDivisionError as seen in Error output section below.  

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use a client that reports screenwidth = 0 or manually `@option screenwidth=0`
2. `help` or `?` for traceback

#### Error output / Expected result of feature
```
Traceback (most recent call last):
  File "/home/evennia/game/evennia/evennia/commands/cmdhandler.py", line 509, in _run_command
    ret = yield cmd.func()
  File "/home/evennia/game/evennia/evennia/commands/default/help.py", line 208, in func
    self.msg_help(self.format_help_list(hdict_cmd, hdict_topic))
  File "/home/evennia/game/evennia/evennia/commands/default/help.py", line 70, in msg_help
    evmore.msg(self.caller, text)
  File "/home/evennia/game/evennia/evennia/utils/evmore.py", line 286, in msg
    justify_kwargs=justify_kwargs, **kwargs)
  File "/home/evennia/game/evennia/evennia/utils/evmore.py", line 184, in __init__
    height = min(10000 // width, height)
 ZeroDivisionError: integer division or modulo by zero
 User input was: 'help'.
```

Expected result... see below.  My thoughts are to treat a 0 value as not wanting pagination or line splitting, assuming the client is doing the pagination or has infinite or very large scrollback and auto-wraps so does not need line splitting, but I leave it open for discussion.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Should `SCREENHEIGHT = 0` not paginate at all, bypassing EvMore pagination?  And should `SCREENWIDTH = 0` not bother splitting lines, or should these just be defaulted to typical ranges?

**Comment by Griatch** [comment]
The trivial fix for this is to enforce a `max(1, SCREENWIDTH)` which is what I went for to handle this issue. If one wants a setting (like -1 to be clear) to turn off evmore handling completely, that should probably go as a separate feature request.
