### ISSUE TITLE
Evennia's IRC Bot does not pass /me messages into Evennia as poses/channel poses anymore.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1258]
#### Brief summary of issue / Description of requested feature:
IRC Bots do not pass `/me` messages into Evennia as poses/channel poses anymore. It seemed like they used to, but now when IRC users use `/me` messages, they do not appear.  This caused a few messages in the conversation to be missing.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Inhabit demo server (create character/log in)
2. Send `/me` message pose in `#Evennia`
3. Observe no message goes into public channel

#### Error output / Expected result of feature
Expected `/me` messages to appear in channel as poses

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Current, main, any OS

**Comment by Griatch** [comment]
Closed with PR merger.
