### ISSUE TITLE
Some links in wiki are broken

### ISSUE THREAD

**Issue by benabhi** [evennia/evennia#1259]
#### Brief summary of issue / Description of requested feature:
Links in docs (wiki) are broken or not display correctly. 

#### Steps to reproduce the issue / Reasons for adding feature:
1. Just go to https://github.com/evennia/evennia/wiki and see so many link broken

#### Error output / Expected result of feature
The links show something like that [Getting Started](Getting Started)  [Admin Docs](Administrative Docs) [Builder Docs](Builder Docs) [Developer Central](Developer Central) [Tutorial: Version Control](Version Control)  

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Until 2 or 3 days ago the links works fine, sure is something in markdown files

**Comment by BlauFeuer** [comment]
The markdown in the wiki entries is unchanged, but the problem appears to be with github's rendering of relative links, so there may not be anything we can do about it, except forward to github as a bug report.

**Comment by benabhi** [comment]
Ok so the problem it self seems to be from github, thanks! until they fix the issue i try to study from the pdf docs ;). Keep with the good work! (sry for my english)

**Comment by Griatch** [comment]
This turns out to be due to GitHub recently switching to use CommonMark. See #1260 which tracks the progress of resolving this. I'm keeping this issue open for now for others to find.

**Comment by Griatch** [comment]
This should be fixed with the conclusion of #1260. If there are any remaining buggy links in auto-generated pages, make a new issue for them. Any eventual errors in non-autogenerated pages should hopefully be few enough to fix manually from here on out. Closing.
