### ISSUE TITLE
Quick Typo Fix for RSS

### ISSUE THREAD

**Issue by lmclarke** [evennia/evennia#1263]
There is a minor typo in evennia/evennia/players/bots.py, makes enabling RSS on a channel buggy.

On line 372, "_RSS_EMABLED" should be "_RSS_ENABLED".

**Comment by BlauFeuer** [comment]
I did add commit 7738d06 to PR #1261 when I noticed it.  When it's pulled, that should resolve it. Thanks for keeping an eye out for these things!

**Comment by Griatch** [comment]
Closed with PR merger.
