### ISSUE TITLE
Bug: User-defined Room/Exit/Character don't inherit from user-defined Object

### ISSUE THREAD

**Issue by xelaadryth** [evennia/evennia#1281]
#### Brief summary of issue / Description of requested feature:
Right now, by default the user-defined typeclasses `Room`, `Exit`, and `Character`, all inherit from `evennia.objects.objects.DefaultObject`. This means that if you want to add functionality to `Object`

#### Steps to reproduce the issue / Reasons for adding feature:

1. It was annoying to redefine all typeclasses to inherit properly.
2. Wanted to add a default lock on all things inheriting from `DefaultObject` within my own game repo

#### Error output / Expected result of feature

1. Overriding a function in `mygame.typeclasses.objects.Object` affects all of my game objects

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Change inheritance for `Room`, `Exit`, and `Character` to inherit from `Object` in the generated game folder...somehow...is there a way to make stuff like `DefaultRoom` inherit from `typeclasses.objects.Object` somehow?

**Comment by eldritchsemblance** [comment]
I feel like the original intent of Object was for items that are neither Rooms, nor Exits, nor Characters, perhaps.

**Comment by xelaadryth** [comment]
Thanks for the quick response! I was thinking on this too hard from a code standpoint as opposed to a usability standpoint, and I see now that this was a conscious decision to separate the kinds of objects.

Instead of adding a shared parent which would probably impact the base evennia install, I'm thinking of adding a module with shared static functions that check for `isinstance(DefaultObject)`, and overriding the methods I want to replace in `Room`, `Exit`, and `Character` to just call the shared static function. This explicitly and purposefully changes functionality for each typeclass.
