### ISSUE TITLE
NoneType error issue for newly created Players

### ISSUE THREAD

**Issue by eldritchsemblance** [evennia/evennia#1286]
UPDATED 28 MARCH 2017

#### Brief summary of issue:
When an account is created in multiplayer mode 3 then given immortal perms, its attributes are set to NoneType rather than the expected values upon next login, causing attribute access to fail.

#### Steps to reproduce the issue:
This issue has been occurring in multiplayer mode 3.  Other modes have not been tested.

1. Create an account in multiplayer mode 3
2. Ensure that a character was not auto created
3. Assign immortals permissions to the Player
4. Log out the newly created Player
5. Log back in with that Player
6. Run the create character command.  Note that the traceback below is shown, but the character will have been created in the database, without being linked to a Player account.  They do not show in the character listing for the player.

#### Error output
Many commands fail with:  `AttributeError: 'NoneType' object has no attribute X` where X is any attribute the command needed.  e.g. trying to create a character:

`Traceback (most recent call last):
 File "/home/evennia/evennia/evennia/commands/cmdhandler.py", line 509, in _run_command
 ret = yield cmd.func()
 File "/home/evennia/evennia/evennia/commands/default/player.py", line 167, in func
 player.db._playable_characters.append(new_character)
AttributeError: 'NoneType' object has no attribute 'append'"`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
The server in question is Ubuntu 16.10 running on Digital Ocean, current master branch, this issue has persisted through Evennia updates.

**Comment by Griatch** [comment]
@eldritchsemblance I have tested this back and forth on the `devel` branch and I cannot replicate the issue: no matter how many times I follow you recipe above I can successfully create the character. Could you try with devel to see if you still see this? If not, this will close when devel closes.

**Comment by eldritchsemblance** [comment]
Okay, I will give that a try when I can.

I had it happen recently to me just a few commits back on the main branch.  It actually happened when I erroneously gave Wizards permission to a Character instead of the Player

**Comment by Griatch** [comment]
@eldritchsemblance Since I've not heard more from you, I'm closing this now.
