### ISSUE TITLE
Feature Request: Version tagging docker images

### ISSUE THREAD

**Issue by xelaadryth** [evennia/evennia#1296]
#### Brief summary of issue / Description of requested feature:
Each game will override base functionality of Evennia in their own way. If the docker images only have the "latest" tag then any breaking change may break any new docker builds of the game.

https://hub.docker.com/r/evennia/evennia/

#### Error output / Expected result of feature
Being able to specify EITHER latest tagged evennia version OR a semver version.

**Comment by feend78** [comment]
Hi @xelaadryth,

We do have tagged docker image automated builds enabled, however, there was an issue with tags being missing on the repository. Griatch has updated the repository with the release tags for v0.5 and v0.6, and these tagged images should be built the next time a commit is pushed to the repository.

That being said, the time between tagged releases for Evennia has traditionally been fairly long, which could potentially cause other problems, such as not being able to incorporate bug fixes committed between minor versions.

It is always possible to create your own custom evennia base docker image based on any arbitrary commit, as long as that commit is from some time after the Dockerfile was added to the repository. The steps for this would be:

1. Use git tools to checkout the commit that you want to base your image upon. (In the example below, we're checking out commit a8oc3d5b.)
```
git checkout -b my-stable-branch a8oc3d5b 
```
2. Change your working directory to the `evennia` directory containing the Dockerfile.
3. Use the `docker build` command to build the image based off of the currently checked out commit. The example below assumes your docker account is **mydhacct**.
```
docker build -t mydhacct/evennia .
```
4. Now you have a base evennia docker image built off of a specific commit. To use this image to build your game, you would modify **FROM** directive in the **Dockerfile** for your game directory to be:
```
FROM mydhacct/evennia:latest
``` 
Note: From this point, you can also use the `docker tag` command to set a specific tag on your image and/or upload it into Docker Hub under your account.

5. At this point, build your game using the same `docker build` command as usual. Change your working directory to be your game directory and run
```
docker build -t mydhacct/mygame .
```

I will add these instructions to the Evennia-Docker wiki page as well.

**Comment by feend78** [comment]
Unfortunately, the tagged builds for v0.5 and v0.6 failed, as there was no Dockerfile present at that time. However, when v0.7 is tagged, Docker Hub is configured to automatically build and tag that release.
