### ISSUE TITLE
inconsistency with docstring in shipped command.py file

### ISSUE THREAD

**Issue by texdarkstar** [evennia/evennia#1300]
In the command.py file that is shipped out, in the docstring for the Command class it says:

    Inherit from this if you want to create your own command styles
    from scratch.  Note that Evennia's default commands inherits from
    MuxCommand instead.

    Note that the class's `__doc__` string (this text) is
    used by Evennia to create the automatic help entry for
    the command, so make sure to document consistently here.

    Each Command implements the following methods, called
    in this order (only func() is actually required):
        - at_pre_command(): If this returns True, execution is aborted.
        - parse(): Should perform any extra parsing needed on self.args
            and store the result on self.
        - func(): Performs the actual work.
        - at_post_command(): Extra actions, often things done after
            every command, like prompts.

But the evennia docs say that the name is actually supposed to be 'at_pre_cmd', and 'at_post_cmd'.
MuxCommand has the right ones according to the docs.

**Comment by Griatch** [comment]
Ah, good point.
