### ISSUE TITLE
Bug: Mail contrib: Negative indexing is not supported error

### ISSUE THREAD

**Issue by Ockad** [evennia/evennia#1311]
#### Brief summary of issue:
After having implemented the mail.py contrib module, I started to fiddle around with it and saw that after inputting @mail 1 (to check mail with id 1) it would be executed as it should be.
However, when you try a negative number, like @mail 0, it would give the Assertion Error: Negative indexing is not supported, which is generated from the django package.

#### Steps to reproduce the issue:

1.  Implement the mail.py module from evennia/contrib
2.  Type in '@mail 0' or '@mail -42' for example
3. 

#### Error output
```
Traceback (most recent call last):
  File "c:\mud\evennia\evennia\commands\cmdhandler.py", line 509, in _run_command
    ret = yield cmd.func()
  File ".\commands\mail.py", line 214, in func
    message = self.get_all_mail()[int(self.lhs) - 1]
  File "c:\mud\pyenv\Lib\site-packages\django\db\models\query.py", line 277, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:
Happened on rev ae2c2be8, but doesn't matter which revision as long as the mail.py contrib module is implemented in the system.

**Comment by Griatch** [comment]
This is because it is trying to index in a queryset, which does not support indexing. This should be handled as part of the input verification. Pinging @grungies1138 in case he wants to peek at it.

**Comment by grungies1138** [comment]
Most likely raised because someone typed @mail 0.  The table that shows the list of messages is a 1-based index, but the in-memory list is 0-based.  the -1 is to allow for selection of the list item based on it's position in the list.  If the user is using a 0-based attempt to pull the message, then they will not get the right message, regardless of the number they enter.  Best I can do/recommend is to catch then entrance of a 0 in the input and display a message.  Unless someone else has a better idea.

**Comment by Ockad** [comment]
Indeed to catch the input of a 0 on @mail is what I thought about - just lack the knowledge about the system to implement it.

**Comment by BlauFeuer** [comment]
This might work as a technique to get it in range: once the input string is converted to a number, to make sure the value is positive and an integer:
`value = int(max(1, value))`

**Comment by TehomCD** [comment]
Maybe something like:
```
                    try:
                        num = int(self.lhs) - 1
                        if num < 0:
                            raise ValueError
                        message = self.get_all_mail()[num]
                    except (ValueError, IndexError):
                        self.caller.msg("'%s' is not a valid mail id." % self.lhs)
                        return
```
That way you're using the same error message.

**Comment by Griatch** [comment]
@grungies1138 Are you interested in resolving this?

**Comment by Griatch** [comment]
I fixed the contrib with more elaborate index error checking. So this should not happen any more. Closing.
