### ISSUE TITLE
Channels + IRC connector doesn't handle ANSI sequences well

### ISSUE THREAD

**Issue by josephhackman** [evennia/evennia#1313]
#### Brief summary of issue / Description of requested feature:

Sending ANSI text (i.e. colors!) to an IRC-connected channel results in the input being passed as-is (as far as I can tell) to all telnet clients. However, it is escaped before being displayed to the IRC connector, resulting in messages being garbled.

Perhaps it could strip the escape sequences?

#### Steps to reproduce the issue / Reasons for adding feature:

1. I used the following snippet to generate a gradient of magenta 'm's (testing for 24-bit color support):
```
def magenta() -> list:
    s = ''
    for i in range(256):
        s+=('\033[38;2;%i;%i;%im%s\033[0m' % (i, 0, i, 'm'))
    return ['public %s' % s]
```

#### Error output / Expected result of feature
```
[Public] guest: mmmmmmmmmmmmmmmmm...
<evdemo> [Public] guest: [38;2;0;0;0mm[0m[38;2;1;0;1mm.....
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

I was using the demo Evennia server

**Comment by BlauFeuer** [comment]
Mostly, Evennia should just strip sending ANSI text. As it is, I think it did strip the initial escape character, rendering the sequences into just gibberish.   Most mu* don't allow clients sending the low ASCII range of characters into the mu*, but do often allow markup entered to be interpreted and sent back out.

**Comment by BlauFeuer** [comment]
Anyway, to output color to others and avoid this: `[Public] guest: ;0;0;0mm;1;0;1mm;2;0;2mm;3;0;3mm;4;0;4mm;5;0;5mm;6;0;6mm;`..., try the in-game command `@color xterm256` to list the markup for sending these codes.

Alternately, they're [explained in the wiki here](https://github.com/evennia/evennia/wiki/TextTags).

**Comment by Griatch** [comment]
As Blau said, raw ANSI sequences are not expected to be entered manually by the developer, rather Evennia color tags are used - these both support standard 16-color ANSI as well as xterm256. The point of using generic color tags is that they themselves don't know which client will then display your text. So when you use Evennia's color tags they will be converted to ANSI/Xterm256 for telnet, CSS div names for the webclient and to IRC MiRC colors for IRC clients etc. Entering raw ANSI sequences bypasses this generalization.

Hope that explains what you are seeing. Closing.
