### ISSUE TITLE
In-use session assigned to new connection in webclient

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1315]
#### Brief summary of issue / Description of requested feature:
A player was using the webclient when suddenly they saw text of someone else attempting to log in. They saw the output of a few 'look' commands and someone trying to do `co <name> <password>`. The player who was trying to log in saw no text display, since it was being sent to the other session.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Both players were using the webclient, but no idea what caused it.

#### Error output / Expected result of feature
Bad session assignment. It's possible this may be related to the other strange errors that I occasionally see, like the loss of cmdsets, etc.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
N/A

**Comment by Griatch** [comment]
Ouch, this is a serious issue. :/ Were both users returning players - That is, were they auto- connecting to their session in the web client or did they log in 'fresh' by entering their credentials on the login screen?

**Comment by TehomCD** [comment]
Both were logging in fresh from the login screen, I believe. I've never seen the issue with auto-connection, as far as I know.  As of yet, I'm not able to reproduce it by clearing cache enough times and logging in on the webclient simultaneously in a few windows, or just trying to log in while other people are already connected with the webclient, or with any combination of autologin/cleared cache so far.

Checking the log, I did see some reports of 'No cmdsets found' from an unnamed session that only lists an IP address that's happened as a result of AMP errors, so it may have been related to that in some way.

**Comment by TehomCD** [comment]
It happened again, though this time there wasn't any accompanying AMP error as a possible cause. It's only happened to this one player, so I'm not sure if it's something specific to them yet or not. She mentioned it happened after being idle for a fairly long time (half an hour in the second incident), though who knows if that's a cause, or it's just somehow based on her account or cookies or what have you. I've disabled multisession mode for safety for the time being.

**Comment by TehomCD** [comment]
Multisession mode doesn't seem like it was to blame. This time was a different player - I'm going to turn off autologins by calling `session.flush()` on the request's session object before calling to the webclient view, and see if that resolves the issue.

**Comment by Griatch** [comment]
Changing the autologin code is on my todo list for 0.7, it is too aggressive at this point, and possibly a bit too fickle, being spread out over multiple locations in the code.

**Comment by Griatch** [comment]
@TehomCD Did your experimentation with autologins help for this issue?

**Comment by TehomCD** [comment]
I haven't had a recurrence of the issue since I disabled auto-logins and started wiping the webpage's session data after logging in. I still have no clue what the root cause of the issue was, though.

**Comment by Griatch** [comment]
@TehomCD Auto-logins have been reworked and fixed to act more sanely. For now I will close this, if this rears its ugly head again, please let me know.
