### ISSUE TITLE
Don't check Non-testable files with Coveralls

### ISSUE THREAD

**Issue by eldritchsemblance** [evennia/evennia#1318]
#### Brief summary of issue / Description of requested feature:
Adding a non-testable file such as an example shell script causes a decrease in code coverage

#### Steps to reproduce the issue / Reasons for adding feature:

1. Add a non-code file that is not unit-testable
2. Run Coveralls

#### Error output / Expected result of feature
Code coverage is reported as decreasing.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
These types of files should be ignored by Coveralls

**Comment by Griatch** [comment]
Good point. You can however only exclude specific file regexes in coveralls. I added exclusions of a few text types, `*.sh` as well as the `*.service` file that will be added once your PR is updated.
