### ISSUE TITLE
Run evennia migrate Error

### ISSUE THREAD

**Issue by MarsZone** [evennia/evennia#1323]
#### Brief summary of issue / Description of requested feature:
when I run the evennia migrate command , it will show the error.

#### Steps to reproduce the issue / Reasons for adding feature:

![image](https://cloud.githubusercontent.com/assets/3784198/26237109/5a445554-3ca6-11e7-9b01-15f759bebd9c.png)

#### Error output / Expected result of feature
![image](https://cloud.githubusercontent.com/assets/3784198/26237144/74cb2f6a-3ca6-11e7-8d2e-e526aa6ca03f.png)

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Enviroment
-Centos 6.5 64bit
-locale
![image](https://cloud.githubusercontent.com/assets/3784198/26237013/dda12428-3ca5-11e7-84a4-f368a0a78908.png)
-python 
![image](https://cloud.githubusercontent.com/assets/3784198/26237046/0e59f64e-3ca6-11e7-9733-5119b5f7f5ac.png)

PS:
when I changed the locale language.
![image](https://cloud.githubusercontent.com/assets/3784198/26238366/4ff2586c-3cab-11e7-8705-16cde2c307fb.png)
The error become.
![image](https://cloud.githubusercontent.com/assets/3784198/26238390/6f1016c6-3cab-11e7-9993-ecbfb76269ce.png)

Do you need more information?

**Comment by Griatch** [comment]
This was solved in chat as being due to running MySQL without proper permissions. Closing.
