### ISSUE TITLE
OLC system

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1326]
Create prototype OLC using EvMenu. And OnLine Creation system that searches, edits, saves and updates prototypes and the objects created by those prototypes.

**Comment by Griatch** [comment]
This was popped off into a separate `olc` branch for now to make it block less and work more in parallel with the other structure changes in devel branch.

**Comment by Griatch** [comment]
I might delay this until after devel merges actually. It's a lot of work and blocks other changes scheduled for 0.7.

**Comment by stefanludlow** [comment]
Roger

**Comment by Griatch** [comment]
Closed with release of 0.8.
