### ISSUE TITLE
Feature request: have an evennia.exe file instead of an evennia.bat created for Windows

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1337]
#### Brief summary of issue / Description of requested feature:

I suggest that, in the `setup.py` file of Evennia, steps be taken to create, on Windows, an `evennia.exe` in the virtual environment, instead of an `evennia.bat` file.

#### Reasons to add

Windows is a bit touchy about .bat files when it comes to stopping them.  That's why Windows users have a hard time using `evennia stop`: the initial evennia instance is stopped... but Windows wants to ask for confirmation.  Since Evennia runs in daemon mode (a thing which is poorly supported by Windows), the standard input isn't set on the script.  Which makes things a bit hard.  On `cmd.exe`, the trick consists in doing `evennia stop`, then pressing `CTRL + C` several times when the message "Terminate batch job? (Y/N)" appears.  But some other consoles, like git-bash, prefer to crash rather than stopping Evennia in such a way.

Instead, if Evennia would run on an evennia.exe file, Windows wouldn't be bothering about stopping it.  It would probably never ask any confirmation and allow daemon mode or interactive mode without such issues.

> Note: creating a .exe instead of a .bat doesn't seem to require much changes in the `setup.py` file.

**Comment by vlegoff** [comment]
I just tried, and it doesn't solve the issue.  Forcing the `setup.py` file to create a .exe still displays the same confirmation when using `evennia stop`.  Not sure why.  You can easily test by modifying your `setup.py` file (I did this modification for Windows, but I believe it is the same for Linux):

```python
# ... rest f the file before the setup function
setup(
    name='evennia',
    version=get_version(),
    # ...
    entry_points={
        'console_scripts': [
            'evennia = evennia.server.evennia_launcher:main',
        ],
    },
    # ... rest of the function, without script
)
```

**Comment by vlegoff** [comment]
After running some tests on Windows, the results are really not encouraging.  Couldn't it be better to use the AMP to control "signals" to terminate either processes?  It would complicate a bit, as it would mean the command in console, at some point, has to require communication with both processes.  But Windows has a poor handling of signals, and both `evennia stop` and `evennia reload` would benefit from an alternative system to communicate between processes.  Which wouldn't be that complex to setup, I believe, since the system already exists.  Therefore @Griatch, you're free to close this issue or rename it if more appropriate.  I'm here for further testing on Windows if needed.

**Comment by Griatch** [comment]
@vlegoff The Evennia runner is already using signals to control the processes. AMP has nothing to do with it. And yes, Windows is very poor at inter-process communication, like with so much else. So if you are having issues with your terminal of choice you should probably stick to using the in-game commands for controlling the server. Closing this.
