### ISSUE TITLE
Feature request: remove system signals from evennia stop/reload

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1339]
#### Description of requested feature:

Relying on system signals to stop/reload Evennia isn't the best solution on Windows.  Even though the system handles these signals, it doesn't do a very good job.  Relying on an alternative system would allow:

1. To stop Evennia no matter how it was started in Windows.
2. To reload Evennia in Windows.

#### Possible leads:

- Relying instead on messages sent on the local network, perhaps on the AMP.  It would require the console to connect to the AMP server, and of course, it might not be running.
- Have the console issue REST request to the web server, assuming it's running.
- Possibly Django channels, if appropriate (and moving to the right Django version).
- Have the console connect to Telnet in privilege mode to issue shutdown or reload.  This is not a terrific solution, as the telnet protocol might not always be running when we want to reload or start the server.

Feel free to add suggestions in comments!

**Comment by Griatch** [comment]
It's an interesting variant to do this over REST requests (would make more sense than Django Channels although those would be possible in principle). This would require us to implement the Django Rest Framework, which is something that is planned but not on the docket in the near future.

**Comment by Griatch** [comment]
It's an interesting idea to send commands over REST (Django Channels/websockets is also possible but not as logical as REST I think). This would require us to add the Django REST framework. Which is not impossible, especially since I'm using it myself at work these days. It's planned to happen, but it's not something for the immediate future (at least not from me).

**Comment by Griatch** [comment]
This was resolved by using AMP communication in develop.

**Comment by Griatch** [comment]
Closed with release of 0.8.
