### ISSUE TITLE
Protocol flags aren't always reported on the session

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1340]
#### Brief summary of issue / Description of requested feature:

I'm trying to use the TTYPE negotiation to activate the screen reader supports from the early beginning.  Evennia responds well and the flags are accurately modified, but these flags don't seem to be reported to the session (`@options` still show them as `False`).

#### Steps to reproduce the issue / Reasons for adding feature:

1. Bind a local copy of Evennia.
2. You can run the basic twisted client I've written (it's just to test, it's ugly, see below).
3. Use the client to connect.  The client should send the `@options` command and quit.
4. Check in your `@options` output.  The client has activated the screen reader support but it doesn't show in `@options`.

Detail of the handshake:

1. Server - IAC DO TTYPE
2. Client - IAC WILL TTYPE
3. Server - IAC SB TTYPE SEND IAC SE
4. Client - IAC SB TTYPE IS "COCOMUD" IAC SE
5. Server - IAC SB TTYPE SEND IAC SE
6. Client - IAC SB TTYPE IS "ANSI" IAC SE
7. Server - IAC SB TTYPE SEND IAC SE
8. Client - IAC SB TTYPE IS "MTTS64" IAC SE
9. Server - IAC SB TTYPE SEND IAC SE

#### Error output / Expected result of feature

After some additional logging in Evennia, it seems, in `server.portal.ttype`, the option is indeed active after the handshake:

```
>>> self.protocol.protocol_flags
{'ANSI': True, 'MCCP': False, 'NOGOAHEAD': False, 'ENCODING': 'utf-8', 'XTERM256': False, 'NOPKEEPALIVE': True, 'INPUTDEBUG': False, 'NOCOLOR': False, 'MXP': False, 'TERM': 'ANSI', 'RAW': False, 'OOB': False, 'CLIENTNAME': 'COCOMUD', 'TTYPE': False, 'SCREENREADER': True, 'SCREENWIDTH': {0: 78}, 'SCREENHEIGHT': {0: 45}}
```

#### Resources

- Script to show the active handshake: https://hastebin.com/fewotojigi.py

**Comment by vlegoff** [comment]
After additional debugging, it seems that the TTYPE handshake, which consists of three options, is completed just fine.  However, the session is not synchronized before 2 additional seconds.  Evennia doesn't seem to acknowledge that handshake is done (TTYPE handshake completes, but the `handshake_done` method isn't called on telnet itself).

In other words, if waiting for 2 additional seconds, `@options` will actually show the screen reader option turned on.

**Comment by Griatch** [comment]
The reason for the delay is due to the Portal making sure to catch all the handshakes and eventually timing out because your client doesn's send any of the other handshakes - that's when it syncs what it has to the Server and options becomes aware of them. The process has been reworked a bit in development to be more stable. Either way I don't think this is an actual bug. Closing.
