### ISSUE TITLE
Feature request: a persistent utils.delay()

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1341]
#### Description of requested feature:

`utils.delay()` is great, but it gets erased when the game reloads or shuts down.  I suggest a persistent `utils.delay()` to solve this.  If accepted I would be happy to work on this to integrate to Evennia vanilla.

#### Suggested implementation:

The event system offers a similar approach when it creates differed tasks: it will call a callback in a specified time with specified arguments.  If the game reloads or shuts down, it will just call the callback whenever possible, keeping track of time.

This system is less simple than `utils.delay()`, which simply create a Twisted differ (actually, the event system uses `utils.delay()` for its task system).  Having a permanent `utils.delay()` would mean storing both the callback and arguments in the database, with the usual problems regarding persistence:

- Not all callbacks can be saved.  Top-level functions or instance methods should be okay.
- Not all arguments can be saved, following the usual strategy for attributes.

In other words, we could have something like this:

1. When calling the persistent `utils.delay()`, an entry will be stored in database containing the callback and the arguments if it has been able to pickle them.
2. The normal `utils.delay()` will then be called to create the differed task.
3. When the server is started (after a reload or shutdown), the entries in the database would be checked.  If they should have fired but haven't, then a normal `utils.delay()` will be called again.

#### Questions:

Assuming this implementation is accepted, there are some questions to consider:

1. Where to store the entries?  A script could be the solution but it would require to start the script in order to use the feature.  Not an "out-of-the-box" feature.
2. How to call it?  We must keep `utils.delay()` as it is and just add a layer.  Probably not a keyword (`persistent=False`) like on a lot of features, since `utils.delay()` accepts random keyword arguments, and that might break compatibility for some users.  Besides, having a non-persistent `utils.delay()` makes sense, again, not to break compatibility.  So another function in `utils.py` might be the solution, not sure how to call it.

Thank you for your feedback,

**Comment by Griatch** [comment]
A persistent `utils.delay` fulfilling your requirements is called a *Script* and had been in Evennia much longer than `utils.delay` ever was. Is there a reason you can't use `create_script` for this use?

**Comment by vlegoff** [comment]
@Griatch It's just a design "reluctance", you could say.  Scripts to do just a little pause, particularly on simple actions, would mean lots of scripts being created/destroyed in a very brief moment.  I have a "Wrong Password" script for instance, when you enter the wrong password to login, you have to wait 3 seconds to re-try.  Well with this kind of strategies on an entire world, with moving NPC, pauses between elevators (and of course, vehicles), it will create and destroy lots of scripts.  It's true that the "permanent delay" could be held in a storage script, I was just wondering if something easier to use might not be a good idea.

**Comment by Griatch** [comment]
One way or another, an object will be written to the database, be it a Script or an Attribute. The Script already had all the mechanisms for handling starting up the timer after a reload, so it would be wasteful to reinvent this. On could of course consider offering a default script type which accepts an arbitrary callback (wrapped by Script.at_repeat) and gets created by some persistent version of utils.delay.  A second alternative may be to wrap the Tickerhandler and create a subscription. This will lack precision though; once you subscribe to existing tickers your first repeat may happen faster than you want.  So a Script is likely the best way here.

**Comment by vlegoff** [comment]
I was thinking a single global script, actually, because the point is just to avoid script ID multiplication, a lot of scripts being created and destroyed for small tasks.  But yeah, the script could be provided in a contrib or something, with a dedicated function to add a callback with arguments in it.  It could automatically start the global script if it's not already running too.  But if you don't think it's a really useful idea, I'll just code it for my own game, it's open-source in any case.

**Comment by Griatch** [comment]
I might have re-thought this a bit. Maybe there is a need for this even though it essentially duplicates the functionality of a Script. It would be easy enough to add I guess; but I'd not use a global script, but borrow and use serialization in the same vein as the TickerHandler. I could look into this post-0.7.

**Comment by vlegoff** [comment]
A first draft has been added in the (pull request #1371)[https://github.com/evennia/evennia/pull/1371}.  It looks good to me but is probably far from perfect.

**Comment by Griatch** [comment]
This is closed with the merger of #1371.
