### ISSUE TITLE
Feature request: `@spawn` and utility has no documented way to set tag category.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1352]
#### Brief summary of issue / Description of requested feature:
[Spawner Wiki entry](https://github.com/evennia/evennia/wiki/Spawner) gives an example for setting tags as 

`@spawn {"prototype":"TROLL_SHAMAN", "key":"Gorat the wise", "tags"=["evil", "quest-giver"]}`

Whereas it is documented that ***tags - string or list of strings for use as Tags. These will have no set tag category.***

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@spawn {"prototype":"TROLL_SHAMAN", "key":"Borat the Kazakh journalist", "tags"=["evil", "quest-giver", "libra:zodiac"]}`
2. `@tag Borat`
3. Observe tags have no categories

#### Error output / Expected result of feature
Parsing tag list of strings for `:` and split, allowing the setting category field of tag at spawn, similar to how aliases split on `;` and are set at spawn.

**Comment by Griatch** [comment]
This is already supported in devel. Closing this when devel merges.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.

**Comment by BlauFeuer** [comment]
Now that this is documented, and implemented, I still can't get it to work:
`@py evennia.utils.spawner.spawn({'key': 'Fedora', 'tags': ('size', '18')})`
produces an object with two tags, not one tag with a category.

**Comment by BlauFeuer** [comment]
Alright, the _batch_create_object docstring is much more succinct than the longer module docstring, which I found confusing. But I did finally come to understand that
`@py evennia.utils.spawner.spawn({'key': 'Fedora', 'tags': [('size', '18')]})`
is what it implies to do, which works.  Although tuples make sense for grouping, the `@tag` command usage:
>Usage:
  `@tag`[/del] <obj> [= <tag>[:<category>]]
  `@tag`/search <tag>[:<category]

implies that a valid tag could never contain a colon (:) character, which makes it the more intuitive way to express a tag category pair (using the colon as a delimiter), and the implementation is certainly different from my expected result of feature.
