### ISSUE TITLE
Bug: ANSI failing for some clients after reload

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1353]
#### Brief summary of issue / Description of requested feature:
A few players have reported an issue where after server reloads, their clients will no longer use ANSI correctly. It varies for client: for TinyFugue, one user reported that his `@options xterm256` flag becomes toggled to False, while one on MushClient reported the opposite. A player using SimpleMU, which does not support xterm256 at all, mentioned that after and server `@reload` his colors will go haywire - he'll see things like at random it seems that some things will have their background ansi color set to the same as the foreground, making them invisible. https://www.dropbox.com/s/08ddg5ttf5dhf99/Screen_%202017-06-23_580.jpg?dl=0 is an example he linked.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@reload` server, some users reporting strange behavior in ANSI following.

#### Error output / Expected result of feature
Above link for SimpleMU, different protocol flags changing toggles for other clients.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
There's been mention of the protocol flag toggling on reloads for a while but it's been such a tiny subset of users I never bothered to make an issue for it. The SimpleMU one seems like the most troublesome, and he mentioned it started roughly ~2 weeks ago or so, so possibly may be related to #1335 somehow.

**Comment by BlauFeuer** [comment]
I periodically lose the XTERM256 setting and have to turn it back on again.  The client does display it, but Evennia has a fair chance of losing the setting on reconnect, as if the handshaking for it fails or times out, and the server is on the LAN, so I doubt it's network latency.

**Comment by BlauFeuer** [comment]
I've noticed this occurring before the update related to #1335  but it's difficult to quantify if it's happening more often now.Others have reported losing the NOCOLOR option, and I will often lose NOPKEEPALIVE, which will be set to False, but only appear if I set it. (Doesn't appear on list, set it off, receive "Option NOPKEEPALIVE was changed from 'False' to 'False'.", now it appears on list.)

**Comment by Griatch** [comment]
I believe all issues with telnet settings has to do with Evennia's delayed sync, where it times out waiting for the client to finish sending its handshake (some clients can take a surprisingly long time to do this, which would make you think it's Evennia that's sluggish). So if the client takes longer than a second Evennias portal goes ahead with syncing up to the Server anyway. The two are meant to sync up again once all protocols have finished hand shaking, but it appears this is not always working the way it should.

**Comment by Griatch** [comment]
Since this issue was filed I have reworked the way the telnet protocol handshakes to make this whole process a lot more reliable - at least that's my hope. Along with the fix in #1555, could those who can reliably see this (@BlauFeuer?) see if their issues still remain?

**Comment by Griatch** [comment]
Is this still an issue or can it be closed after the latest patch?

**Comment by BlauFeuer** [comment]
I haven't seen lately. The delay to give more time for handshaking, and the changes in develop seems to have chased this bug away.   I used to see it, myself, every few days, but haven't seen it dropping option settings in a while. (like suddenly NOPKEEPALIVE would disappear, etc.).

So my theory is if it's not fixed in master, it's probably fixed in develop branch now at least.

**Comment by Griatch** [comment]
Ok, I'm closing this for master for now. If it's still an issue in master we can reopen this until `develop` merges.
