### ISSUE TITLE
Feature Request: `@link` exits always searches globally. Searching local-first is more helpful.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1355]
### Brief summary of issue / Description of requested feature:
When `@link` is used on a local exit to link or relink an exit to a proper destination, it returns a global list of exits when searching by name, even though there may be a single match locally.  This then requires all exits to be referenced by `#dbref`.

An initial local search, assuming the builder is in a valid location and exits are also in that location, would allow by-name searches to quickly match the intended local exit instead of returning all global exits.  Listing global exits should only occur under the condition that no local exits match the given exit name.

### Steps to reproduce the issue / Reasons for adding feature:
Example use, not reproduced error.
1.  `@link south=#2`
2. (Have 1000+ exits returned, as "south" is a common exit name.)
3. `@link #523=#2` (after resorting to using the `#dbref`

### Error output / Expected result of feature
`@link south=#2` would first look locally, find the south exit, then link it.  If multiple south exits are local, then multimatch only those.  If no matches are found, then look for a match globally.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Current version, all OS.

**Comment by Griatch** [comment]
Resolved in #1694.
