### ISSUE TITLE
ChannelCommand enforcing arg_regex

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1357]
#### Brief summary of issue / Description of requested feature:

The `ChannelCommand` created by `evennia.comms.channelhandler.ChannelHandler` enforces `arg_regex`, which means it's not possible to add other formats to the command.

#### Reasons for adding feature:

The question at this point is to know whether this is a desired behavior, and why.  When customizing the class for channel commands (using the `CHANNEL_COMMAND_CLASS` setting), it is not possible to add switches to channels.  The only switch that is supported is `/history`.  Everything else is considered an invalid command and will trigger the "no match" command of the handler.

#### As an example

I have changed `CHANNEL_COMMAND_CLASS` to point to a class where two switches would be supported: `/me` and `/who`.  This way, one could use `public/who`.  Other switches might be useful as well, like `/emit` or `/kick` for administrators.  The culprit is in [evennia/comms/channelhandler.py:215](https://github.com/evennia/evennia/blob/master/evennia/comms/channelhandler.py#215), in the `ChannelHandler.add` method.

#### Possibilities

I'm not sure I understand why the `arg_regex` is enforced in the first place.  But assuming this is a requirement, it might be good to allow, at least, to override it, to add other switches.  It can be done through modifying the chanell handler itself, but it's not pretty.  If one defines an `arg_regex` class attribute, it gets replaced each time by the `r"\s.*?|/history.*?"` regex.

Another possibility (but perhaps not prettier) would be to have a setting for this.  Something like `CHANNEL_COMMAND_ARG_REGEX`.  But it seems a little too much for a simple use case.

**Comment by Griatch** [comment]
That is a good point. The reason several of the things are set in the ChannelHandler is probably just because the ability to use `CHANNEL_COMMAND_CLASS` is relatively new and those things were not moved over or considered to be a restrictive issue at the time.

 It makes sense to move most of the things set in the initialization call (the things that does not have to be created dynamically) to the Channel command class instead so they can be more easily overwritten.

**Comment by Griatch** [comment]
This is closed with the merger of #1358.
