### ISSUE TITLE
Wilderness.py exits created in wilderness aren't added to manifest

### ISSUE THREAD

**Issue by BigJMoney** [evennia/evennia#1364]
#### Brief summary of issue / Description of requested feature:
When a regular exit is placed into coordinates in a wilderness, it will not persist there because it is never added to the WildernessScript's manifest.

Long explanation:
The wilderness.py special room class overrides a room's *at_object_receive()*; this is where things are saved to the wilderness manifest or not.

I beleive the assumption here is "if an exit's destination = location, it must be one of the special wilderness exits that loops into itself"

However, *at_object_receive()* is run in the middle of *create_object()*, but after a function called *basetype_setup()*; a function that sets every DefaultExit.destination = DefaultExit.location.

So the final value for WildernessExit.destination is determined after it is checked by the contrib.

#### Steps to reproduce the issue / Reasons for adding feature:
Note that it might not be possible to reproduce this without #1362 blocking
1. In a sample game, set up the pyramid tutorial explained in the Wilderness contrib
2. Once inside the pyramid, `@open` an exit (default class) that leads to Limbo#2
3. Walk out of this room and back in (west; east)

#### Error output / Expected result of feature
The exit placed in the previous room is no longer there

**Comment by BigJMoney** [comment]
I'll submit a PR fix and link to this

**Comment by BigJMoney** [comment]
I have a one line fix Pr for this, but I need PR #1363 approved first.

**Comment by Griatch** [comment]
#1363 was merged.

**Comment by Griatch** [comment]
Closed by the merger of #1370.
