### ISSUE TITLE
Feature Request: OOB tutorial for the wiki

### ISSUE THREAD

**Issue by texdarkstar** [evennia/evennia#1366]
Can someone do a OOB tutorial for evennia with mushclient?

I know roughly how it works and what it is, and could probably figure out the MSDP,
but I don't know enough to do a tutorial for it, also I am guessing for a lot of it.

**Comment by Griatch** [comment]
It's not in the tutorial section, but the [OOB](https://github.com/evennia/evennia/wiki/OOB) wiki page should take much of the guesswork out of working with OOB messaging. People are welcome to add further tutorials but I consider this issue resolved with this. Closing.
