### ISSUE TITLE
MySQL has gone away - Webclient fails to connect

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1376]
#### Brief summary of issue / Description of requested feature:
The webclient, after Evennia has been running for a while ( 8+ hours ), will refuse to connect, however telnet connections still work fine, and the website stays up.

#### Steps to reproduce the issue / Reasons for adding feature:

1.  Start Evennia with a MySQL connection set up
2.  Leave Evennia running for 8+ hours
3.  Webclient will refuse to connect.

#### Error output / Expected result of feature
```
File "/home/nmatlaga/.virtualenvs/evennia/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I know a previous issue addressed this, I think #619. However, as telnet has no problems, it seems pretty obvious that this is an issue with Evennia leaving open a connection for an extended period of time.
Edit: Of course, I could be off the mark here - maybe there's a setting in Evennia to time out webclient connections that I don't know about. I don't think that setting the MySQL timeout longer is a good idea, though.

**Comment by Griatch** [comment]
Hm, are you using the websocket client or are you falling back to the AJAX client? You can check this in the web console when you connect. 
.
Griatch

**Comment by chainsol** [comment]
It seems to be using the websocket - you can double check me. It's up at dev.perfectdisorder.net.

**Comment by Griatch** [comment]
It's interesting in itself that the AJAX client would have an issue with too long database connections. If you fall back to AJAX on a modern browser ( Firefox/Chrome shouldn't matter), it usually means you have not opened your web socket port. 
.
Griatch

**Comment by chainsol** [comment]
Ready for even more fun? It's not falling back to AJAX because of a port not being open - it's failing back to AJAX because of this issue. I restarted the server, and for the next 8 hours or so, you'll be able to connect with the websocket client.

**Comment by chainsol** [comment]
@Griatch 
Websocket Connection
```
	  File "/home/someone/evennia/evennia/utils/txws.py", line 576, in dataReceived
	    if not self.validateHeaders():
	  File "/home/someone/evennia/evennia/utils/txws.py", line 541, in validateHeaders
	    self.validationMade() # custom Evennia addition
	  File "/home/someone/evennia/evennia/server/portal/webclient.py", line 60, in validationMade
	    uid = csession and csession.get("logged_in", False)
```
AJAX Connection
```
	  File "/home/someone/evennia/evennia/server/portal/webclient_ajax.py", line 265, in render_POST
	    return self.mode_init(request)
	  File "/home/someone/evennia/evennia/server/portal/webclient_ajax.py", line 165, in mode_init
	    uid = csession and csession.get("logged_in", False)
```

**Comment by Griatch** [comment]
@chainsol: Is this still the case or was it indeed related to the closed #1378?

**Comment by chainsol** [comment]
Still the case with MySQL, idle timeout is default 8 hours, but if you set that lower you can see it happen.

_Sent from my Motorola Moto G (5) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chainsol** [comment]
This issue is the same base problem as #619. That one is closed, but the issue still exists and the Django solution needs to be implemented by Evennia. The "crappy" solution is to greatly increase the timeout.
