### ISSUE TITLE
In a pickle about pickling

### ISSUE THREAD

**Issue by DamnedScholar** [evennia/evennia#1389]
#### Brief summary of issue:
I'm trying to make a class that will hold a list of slots for controlling how many add-ons can be attached to an object. I could do this as a complicated dict, but I would like for this to be a class so that it can have its own methods. I'm able to instantiate it and set everything I want to set, but every time I reload Atom, it forgets everything, returning to the state it was in right after the `__init__()` ran.

#### My code right now:
```python
class SlotArray:
    """
    Instantiate an array of slots on an object for controlling the available
    choices for Extras.

    self.db.body = SlotArray("body", "Augments, mutations, and physical qualities.", ["head", "torso", "right_upper_arm", "right_lower_arm", "right_hand", "left_upper_arm", "left_lower_arm", "left_hand", "right_upper_leg", "right_lower_leg", "right_foot", "left_upper_leg", "left_lower_leg", "left_foot"])

    Arguments:
        kind (str): What does this SlotArray represent? Extras will look for this.
        desc (str): Human-readable description.
        options (sequence): All of the available slots (more can be added).

    Methods:
        add(to_add): Adds to the options list.
        remove(to_remove): Removes from the options list.
    """

    # def __init__(self, kind, desc, options):
    #     self.kind = kind
    #     self.desc = desc
    #     self.options = list(options)

    def add(self, to_add):
        self.options.append(list(to_add))

    def remove(self, to_remove):
        new = []

        for option in self.options:
            if option not in to_remove:
                new.append(option)

        self.options = new

    def __getstate__(self):
        # Copy the object's state from self.__dict__ which contains
        # all our instance attributes. Always use the dict.copy()
        # method to avoid modifying the original state.
        state = self.__dict__.copy()
        return state

    def __setstate__(self, state):
        # Restore instance attributes.
        self.__dict__.update(state)
```

#### Log from Evennia:
```python
>>> from sr5.system import SlotArray;self.db.slots = SlotArray("magic items", "Gizmos of all sorts.", ["wand"])
 Done (use self.msg() if you want to catch output)
>>> self.db.slots.options
['wand']
>>> self.db.slots.add("ring")
None
>>> self.db.slots.options
['wand', 'ring']
>>> import pickle;self.msg( repr(pickle.loads(pickle.dumps(self.db.slots)).options) )
['wand', 'ring']
 Done (use self.msg() if you want to catch output)
 Server restart initiated ...
 Server restarting ...
 ... Server restarted.
>>> import pickle;self.msg( repr(pickle.loads(pickle.dumps(self.db.slots)).options) )
['wand']
 Done (use self.msg() if you want to catch output)
```

[The Evennia documentation](https://github.com/evennia/evennia/wiki/Attributes#storing-single-objects) has the following to say on what can be stored in an attribute:

> With a single object, we mean anything that is not iterable, like numbers, strings or custom class instances without the __iter__ method.
> * You can generally store any non-iterable Python entity that can be pickled.

It also links to [the help page about `pickle`](https://docs.python.org/3/library/pickle.html), which describes how things work in what seem to me to be pretty clear terms. If you have a class that can be pickled, its state is preserved by copying its `__dict__` attribute, and classes can manipulate their storage by the `__getstate__()` and `__setstate__()` methods. There are also some methods to manipulate the pickling itself. I can use `loads()` and `dumps()` to follow the translation from objects to bytes and back again, and if I put them together, I should be able to pickle and unpickle the class myself. So I do that, with the `pickle.loads(pickle.dumps(self.db.slots)).options` construction. That works. When I pickle the class and feed the bytestream to the unpickler, what comes back to me is exactly what was put in. It's only when Evennia does it while it's reloading that the class reverts to its initial state. The `pickle` help *does* mention that `__init__()` may be called after unpickling, but I've tried it with that method commented out and no dice.

So what does Evennia do when pickling that's different from what `pickle` does by itself?

**Comment by TehomCD** [comment]
The problem here is that the Attribute where the class is pickled is not being saved when changes are made, for example when you call `self.db.slots.add()`. Iterables stored in Attributes have special wrappers made for them to call save on the underlying Attribute when changes are made, but the class that you store doesn't. A workaround would be to call something like `self.db.slots = self.db.slots` to force a save due to assignment to the Attribute.

Clearly this isn't ideal, and I do wonder if we could do better somehow. Maybe something like check if the class isn't a django model, and if so, put it in a wrapper kind of similar to how the `SaverDict` and `SaverList` wrappers work?

**Comment by DamnedScholar** [comment]
I feel like the wrapper idea is great. There are some things that you might want to attach to a character without having their own database table, but where you want them to be more elaborate than a simple dict or tuple can manage.

For the immediate future, I can get by reassigning `self.db.slots` every time, and this is a fix that won't break if a wrapper is introduced for classes.

**Comment by Griatch** [comment]
@TehomCD I'm not sure this is something we can automate. The whole point of a custom model is that it's, well custom. Evennia cannot know what internal data it should track and update. Each default wrapper is different. For example a list and dict must handle nested structures (it must save to the database wherever you update in your nested structure) and exactly how those nested structures look depend on the type. 

Not sure how one could automate this. Even if you looked for some special-named method on the object if is not clear how the serializer would know what to feed to it. See e.g. https://github.com/evennia/evennia/blob/master/evennia/utils/dbserialize.py#L427 .

**Comment by Griatch** [comment]
@DamnedScholar So to be clear - your object pickles just fine, but it does not tell the `.db` handler to update the underlying Attribute when it itself updates. Having it do so is not trivial and something Evennia  only implements (can only implement) for previously known mutable types.

**Comment by DamnedScholar** [comment]
After sleeping on it, I decided to try to create a handler with the same sorts of methods, but storing the data directly in attributes. I'm closing this issue because it worked, and it was so easy to set up that I no longer believe that custom classes should be instantiated on attributes since this other way is so much easier. Thanks for all the input. :)

For future reference, here's my current code:

### On the character object:
```python
    @lazy_property
    def slots(self):
        return SlotsHandler(self)
```

### Handler class in utils.py
```python
class SlotsHandler:
    "Handler for the slots system."

    def __init__(self, obj):
        self.obj = obj
        self._objid = obj.id

    def add(self, name, num=0, *slots):
        """
        Create an array of slots, or add additional slots to an existing array.

        Args:
            name: The name of the array.
            *slots: A set of lists, strings, and/or tuples defining slot names.
            num: Any unnamed slots.
        """

        name = "slots_{}".format(name)
        existing = self.obj.attributes.get(name)
        slot_list = []
        for arg in slots:
            if isinstance(arg, list):
                slot_list += arg
            elif isinstance(arg, str):
                slot_list.append(arg)
            elif isinstance(arg, tuple):
                slot_list.append(list(arg))
            else:
                raise ValueError
        # To find where the numbers should start, iterate through numerical
        # keys and store the highest value.
        highest = 0
        if existing:
            for key in existing.keys():
                if isinstance(key, int) and key > highest:
                    highest = key
        for i in range(highest, highest + num):
            slot_list.append(i+1)
        slots = dict(zip(slot_list, [""] * len(slot_list)))

        if not existing:
            new = self.obj.attributes.add(name, slots)

            self.obj.obj.msg("Attribute {} added with contents {}".format(name, slots))

            return True
        else:
            existing.update(slots)
            return True

    def delete(self, name, num=0, *slots):
        """
        This will delete slots from an existing array.
        WARNING: If you have anything attached in slots when they are removed,
        the slots' contents will also be removed. This function will return a
        dict of any removed slots and their contents, so it can act as a pop(),
        but if you don't catch that data, it WILL be lost.
        """

        name = "slots_{}".format(name)
        existing = self.obj.attributes.get(name)
        if not existing: # If the named array isn't there, don't bother.
            return False
        slot_list = []
        for arg in slots:
            if isinstance(arg, list):
                slot_list += arg
            elif isinstance(arg, str):
                slot_list.append(arg)
            elif isinstance(arg, tuple):
                slot_list.append(list(arg))
            else:
                raise ValueError
        # To find where the numbers should start, iterate through numerical
        # keys and store the highest value.
        highest = 0
        if existing:
            for key in existing.keys():
                if isinstance(key, int) and key > highest:
                    highest = key
        self.obj.obj.msg("{} > {}".format(highest, highest - num))
        for i in range(highest, highest - num, -1):
            self.obj.obj.msg("{}".format(i))
            slot_list.append(i)

        deleted = {}

        self.obj.obj.msg(repr(slot_list))

        for slot in slot_list:
            deleted.update({slot: existing.pop(slot)})

        return deleted
```
