### ISSUE TITLE
Character of type DefaultObject even after @reload

### ISSUE THREAD

**Issue by scyfris** [evennia/evennia#1391]
#### Brief summary of issue / Description of requested feature:
I am new to Evennia, and I was following the "First Steps" tutorial here: https://github.com/evennia/evennia/wiki/First-Steps-Coding, and I ran into an issue

In the part about "Tweak default Character", I got this to work.  But in the Troubshooting section, it talks about what would happen if I introduce a syntax error.  So I did, and the player in-game defaulted back to "DefaultObject" as explained.

But the problem is, after fixing this error, I do @reload (also tried evennia start / stop from terminal), and the player is still a DefaultObject. I even tried @typeclass/force self , but still it thinks that the player is a DefaultObject.

The only way I could fix this was by deleting the database entirely and recreating a new data base.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Install new instance of Evennia
2. Follow steps in "Tweak Default Character" at https://github.com/evennia/evennia/wiki/First-Steps-Coding.
3. Aftewards, performing @py self.get_abilities() works fine.
    @py self.get_abilities()
    <<< (None, None, None) 
3. Introduce syntax error, as described in "troubleshooting" subsection of that section in the guide.
4. Do an @reload 
6. Try the @py self.get_abilities(), and will get an error (as expected) like this:
    AttributeError: 'DefaultObject' object has no attribute 'get_abilities'
7.  FIX the syntax error
8. Perform @reload (or do evennia stop/start from command line).
9. Reconnect, and try @py self.get_abilities() again
10. The error  AttributeError: 'DefaultObject' object has no attribute 'get_abilities' **still** gets displayed, even though the logs indicate that there are no python syntax errors.

#### Error output / Expected result of feature

AttributeError: 'DefaultObject' object has no attribute 'get_abilities' 

After fixing syntax errors in characters.py, and reloading, I would expect that error to go away.  I get no syntax errors in the console log, so the I know the python file "character.py" was fixed, so I would expect Evennia to reload the default Character class.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is from latest master branch, at commit 96c4b0c805fe6d448e4656d9237f8f14990ec537

**Comment by Griatch** [comment]
@scyfris Thanks for the well-explained issue! I cannot replicate your problem though.  I retraced your steps as per your instructions. And once fixing the syntax error a reload brings me back to the Character class and the `get_abilities` works again for me.

First, make doubly sure that you see no errors in the console (you may have to scroll up sometimes). If not, my guess is that you have done one too many experiments with `@typeclass/force` and permanently changed yourself to another typeclass somehow - or maybe you mis-spelled the typeclass so it cannot be found. To see if this is the case, look at the result of 

```
@py self.db_typeclass_path
```
The result should be `typeclasses.characters.Character` and nothing else.  If it has the right value it means Evennia cannot load it which means you still have some critical syntax error that you have missed. As said, scroll up in your log. If it is mis-spelled or otherwise has the wrong value (which must be due to some use of `@typeclass`), you can fix it by 

```
@py typeclass self = typeclasses.characters.Character
```
> PS: `db_typeclass_path` is a database field holding the permanently stored path to the typeclass your character is using. This is not touched on an error, which is why it will automatically try again once critical errors are solved.

**Comment by scyfris** [comment]
Thanks for the super quick feedback!  TL;DR: It looks like forcing the typeclass back to Character as you suggest works as expected.  I must have done something with `@typeclass` as I was experimenting quite a bit.

The following is what happened as I followed your comment/suggestion:

> First, make doubly sure that you see no errors in the console (you may have to scroll up sometimes).

So it doesn't look like I have any errors, here is log after "evennia start":

```
(pyenv) Billys-MacBook-Pro:air bclack$
Starting Evennia Server (output to stdout).

Starting Evennia Portal in Daemon mode (output to portal logfile).
--------------------------------------------------
 Air Portal (0.6.0 (rev 96c4b0c)) started.
  amp (to Server): 5000
  telnet: 4000
  webproxy:8000 (<-> 5001)
   + webclient:8001
--------------------------------------------------
--------------------------------------------------
 Air Server (0.6.0 (rev 96c4b0c)) started.
  amp (to Portal): 5000
  webserver: 5001
--------------------------------------------------
2017-08-12T22:25:24+0000 [-] Loading /Users/bclack/python/mechantania/evennia/evennia/server/server.py...
2017-08-12T22:25:24+0000 [-] Loaded.
2017-08-12T22:25:24+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/Users/bclack/anaconda/envs/pyenv/bin/python 2.7.13) starting up.
2017-08-12T22:25:24+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2017-08-12T22:25:24+0000 [-] AmpServerFactory starting on 5000
2017-08-12T22:25:24+0000 [-] Website starting on 5001
2017-08-12T22:25:26+0000 [evennia.server.amp.AmpServerFactory] AMPProtocol connection established (HOST:IPv4Address(TCP, '127.0.0.1', 5000) PEER:IPv4Address(TCP, '127.0.0.1', 49756))
```

I tried what you suggested:

> `@py self.db_typeclass_path`

And output was this:

`evennia.objects.objects.DefaultObject`

So it does appear it's the incorrect object.  What you said about `@typeclass/force` overusage might be accurate, I was playing around with this command quite a bit.  I'm not sure the details of this command yet (still new), but I tried the next suggestion you gave:

> `@py typeclass self = typeclasses.characters.Character`

but got syntax error:

`typeclass self = typeclasses.characters.Character ^ SyntaxError: invalid syntax`

I think maybe that was typo?  I instead removed `@py` and used `@typeclass self = typeclasses.characters.Character`, reran `@py self.db_typeclass_path` and I seem to get correct results:

```
>>> self.db_typeclass_path
typeclasses.characters.Character
```

Just to confirm, I did an `@reload` and tried again and it seems the fix was persistent.  I then tried `self.get_abilities()` and it worked as expected:

```
>>> self.get_abilities()
(6, 4, 2)
```

(Note the 6, 4, 2 were just params modified from tutorial that I had set in at_object_creation).

> PS: db_typeclass_path is a database field holding the permanently stored path to the typeclass your character is using. This is not touched on an error, which is why it will automatically try again once critical errors are solved.

Ahh okay, then maybe I was breaking things while I was experimenting with `@typeclass` somehow...I'm guessing that `@typeclass` then might overwrite the typeclass path in the database field.  Good to know, I probably shot myself in the foot :-D

**Comment by Griatch** [comment]
Ah, sorry, yes I wrote `@py typeclass self ...` when I meant `@typeclass self ...`. Glad you figured it out anyway. Closing this now. :)
