### ISSUE TITLE
Bug: Core unittest suite fails on heavily modified game dir

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1396]
#### Brief summary of issue:

Relatively recent changes of the unittest runner allows the user to use `evennia --settings settings.py .` to execute tests in the game directory only. Accompanying this change was that the notion that the "core" unittest suite would fall back to only use `evennia/settings_default.py`, so that core tests always behave in the same way regardless of the game.

Unfortunately, this "isolation" is currently not fully working. In the example of all of [Ainneve's issues](https://github.com/evennia/ainneve/pull/96), they all fail the Evennia core unittest suite. The same suite passes with a default, newly created game dir. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Clone the [Ainneve game dir repository](https://github.com/evennia/ainneve) and `cd` to it.
2. `evennia migrate` to create a new database
3. `evennia test evennia` to run the (now failing) unittest suite.

#### Error output / expected

The unit test suite fails with Ainneve. The core unittest suite (`evennia test evennia`) should always pass independently of what changes was done to the game dir. 

#### Extra information:

I suspect we'll have to mock the unittest internal settings to make sure to not accept any overrides from the game dir the game is running from. Ainneve makes for a good test case since it's a relatively heavily modified example game with its own unit test suite and CI setup.

**Comment by Kelketek** [comment]
@Griatch The `@override_settings` decorator is the proper way to handle tests that require static settings values.

**Comment by TehomCD** [comment]
I'm unsure if this is the same issue, or just related - when using the test runner for Arx, it succeeds if I test it on individual packages/apps, like `evennia --settings settings.py test commands` will work, or `evennia --settings settings.py test world.dominion` will work, but `evennia --settings settings.py test .` fails with a message about models in my apps not being in `INSTALLED_APPS`/having an explicit app_label declared.

**Comment by Griatch** [comment]
This has been resolved by adding a Makefile that allows for running `make test` in the evennia repo itself (no need for doing so from inside a previous game dir). This guarantees the Evennia test suite always runs with the default settings. One can stull run the suite from the game dir as before (but are then susceptible to the effects of this issue of course).
