### ISSUE TITLE
IRCBot doesn't like objects subscribed to his channel

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1397]
#### Brief summary of issue / Description of requested feature:

When you subscribe objects (like characters instead of players) to a channel IRCBot uses, there's an error on every message sent from IRC.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Subscribe a character to the public channel.  This channel should be connected to IRC with IRCBot.
2. Speak on the IRC channel.

#### Error output / Expected result of feature

In the console can be found the following, tiny traceback:

```
Traceback (most recent call last):
  File "/home/avenew/evennia/evennia/objects/objects.py", line 511, in msg
    from_obj.at_msg_send(text=text, to_obj=self, **kwargs)
AttributeError: 'list' object has no attribute 'at_msg_send'
```

A few things appear quite clearly:

- The message gets sent to the character anyway.
- The error indicates that `from_obj` contains a list, which is not supported by the `Object` class.

#### What to do

From there there are two obvious possibilities:

- Fix the IRCBot, finding the original error.
- Add the ability, for objects, to have a `from_obj` containing a sequence instead of only an object.

**Comment by chainsol** [comment]
+1, I've replicated this on the devel branch as well. I can see others wishing to subscribe characters instead of players to channels, especially in the multisession modes.

**Comment by Griatch** [comment]
Good catch. I think it makes sense to make the Object's `from_obj` in line with however the Player(Account) does it. 
.
Griatch

**Comment by Griatch** [comment]
Implemented. This will close when devel merges.
