### ISSUE TITLE
How about add this project to awesomo?

### ISSUE THREAD

**Issue by lk-geimfari** [evennia/evennia#1403]
Sorry, for creating this issue, but how about add this project to [awesomo](https://github.com/lk-geimfari/awesomo)?

**Comment by texdarkstar** [comment]
This might actually belong on the forums.
It is located at https://groups.google.com/forum/m/#!categories/evennia/evennia-questions

**Comment by chainsol** [comment]
Hey, know you closed this, but just FYI, submitted a PR adding Evennia to Awesomo.

https://github.com/lk-geimfari/awesomo/pull/85
