### ISSUE TITLE
attributes.clear() appears to not affect attributes not in the cache

### ISSUE THREAD

**Issue by DamnedScholar** [evennia/evennia#1404]
#### Brief summary of issue:
In testing and ideating, I've been setting a lot of attributes on myself and leaving them there. I wanted to clean up, so I used `self.attributes.clear()`. That didn't seem to do anything, until I took a second look at `ex me`. It turned out that some attributes *had* gone away, and those were the specific ones I had looked at recently.

#### Steps to reproduce the issue:

1. Have an object with attributes dating to before the cache was flushed recently.
2. Use `.attributes.clear()`.
3. `examine` should show no changes.
4. Use `.attributes.get()` on one of the attributes, then `.attributes.clear()`.
5. `examine` should show that specific attribute deleted.

#### Expected results
`.attributes.clear()` shouldn't care about whether an attribute has been accessed recently.

#### Versions
```
Evennia 0.6.0 (rev d9e8ab84)
```

**Comment by Griatch** [comment]
Fixed in `devel`. Will close with Evennia 0.7.
