### ISSUE TITLE
Split return_appearance to call more easily overridable methods

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1406]
#### Brief summary of issue / Description of requested feature:

The `return_appearance` method does a lot of things, and it can be hard to customize just one part without re-doing it all, which might break compability in future Evennia versions.  I suggest to have `return_appearance` calling hooks like `get_display_desc`, `get_display_exits`, `get_display_things` and so on.  Details below.

#### Steps to reproduce the issue / Reasons for adding feature:

1. The `return_appearance` hook does a lot of things.  Changing one part of the display for each room, for instance, usually means replacing the entire hook with all the other features we don't need to change.
2. This partial copy/pasting is a bit problematic if the functions slightly change between versions, which shouldn't be a major concern.
3. Having a "big" method doing lots of things would deserve splitting in smaller methods.  Usually good programming practice, though I don't always follow it.

#### Error output / Expected result of feature

I suggest a few methods that would behave exactly like `get_display_name`, that is take the looker and return a `str`.  `return_appearance` would just get this text and form a big string to send to the looker.  It could do some additional filtering too.  Here are the hooks I propose (open to debate, of course):

* `get_display_header(self, looker)`: the name might not be explicit, but it's what returns the first line (for the time being, the display name itself).  Why override this method?  Some MUDs don't even display a room titles, just the description right away.
- `get_display_desc(self, looker)`: return the description itself.  Again, the default would simply return the value of `db.desc`.
- `get_display_exits(self, looker, exits)`: return the list of exits.  We would pass it the list of exits (objects) for slight optimization.
- `get_display_things(self, looker, things)`: return the string describing the objects in this location.

Here a question arises: should we split between `get_display_characters`, `get_display_objects` and more?  All games won't need it but some would.  On the other hand, some would still display all "things" in a single string without differentiating at all.

> If this feature is accepted I will be happy to provide a PR against devel.

**Comment by Griatch** [comment]
Not convinced doing separate hooks for this is the way to go. Providing an ever growing number of hooks makes the API more and more cluttered. Also, how you do this is highly game-dependent (even exits are game dependent). I can see your point concerning a huge hook doing many things though. I think the way to do this would be to instead split the internals of `return appearance` into nicer sub-functions are are easier to swap out. That is, you keep `return_appearance` but makes the defeault implementation of it a little more flexible. This is similar to how we have- or have considered improving certain default commands to make them more modular.

**Comment by DamnedScholar** [comment]
I agree with the statement of the problem. One of the items I'm working on for my project is to provide additional parents that override some functions with ones that serve the needs of myself and my intended audience more precisely, and that's going to include `return_appearance`. There are some problems with`@descformat`, `@conformat`, `@exitformat`, but I feel like I can improve on that structure and make it easier for people to design components without having to mess with a monolithic function.

**Comment by BlauFeuer** [comment]
What `return_appearance` does depends on the object's typeclass, and though it's possible to be inside an exit and have an exit on an exit (which then makes `get_display_exits` useful on exits), breaking down the hook into API subsections for me will mean restructuring my custom subsections to match the API, and updating it every time that part of the API gets updated.

I don't yet see how it improves on my own custom structuring; I've already broken down my version of `get_display_things` to include characters first, then vehicles and furniture, food, and clothing -- all of which are game-specific. Is this where the API will be heading?

**Comment by Griatch** [comment]
@BlauFeuer If we go by an internal restructuring as I suggested above, it's *not* an API change. There'd still just be one `return_appearance` hook called by Evennia. How it looks inside and if that differs from the way upstream develops is then up to you. If we were to go for actual new sub-hooks though, then yes that would be an API change that matters.

**Comment by BlauFeuer** [comment]
Ah... I'm certainly not against internal restructuring that doesn't affect current behavior.  I'd like to stay current with Evennia and not modify game code too much to maintain its current behavior. Thanks for the response.

**Comment by vlegoff** [comment]
@Griatch: I might be the only one here but I'm not sure I understand what you mean by international restructuration.  Do you mean providing functions inside of `return_appearance`?  I'm not sure that's it, since that won't be easy to override.

**Comment by Griatch** [comment]
@vlegoff: There are a few different ways to do it. One problem many have with big hooks is it can be hard to replace only parts of them - you need to copy the whole thing. Providing helper methods is one way of battling this. That is, `return_appearance` is the main hook Evennia calls, but it in turn calls a few helper-methods on the object. Evennia will still only call one hook (so the hook-API doesn't change in that sense), and you can rework the internal of it as you want if you don't care about the defaults. But if you only wanted to replace a particular default section you could make use of that, or plug in a replacement a little easier.

**Comment by vlegoff** [comment]
@Griatch: ha, that's what I had in mind actually.  Keep the `return_appearance`, but have it call helper functions.  I imagined these helper functions are other hooks, but I guess this is not great for the API.  It could also be sent by keyword arguments to `return_apperance`.  Again, if you want to replace the entire `return_appearance`, you could still do so with no problem.  If you just want to change a line or some the of information, that might be useful.  We could, for instance, pass a list of "functions" to be called in order.  It would allow to change the order of the list without affecting it.  Each list element would be a function though, and where would that be needs to be determine.  I guess if it's on the object, it's a hook.

```python
class Room(DefaultRoom):
    # ...
    def return_appearance(self, looker):
        super(Room, self).return_appearance(looker, [self.get_display_name, self.get_description, ...])
```

**Comment by Griatch** [comment]
@vlegoff You know what - I misread your original suggestion. I read it as you wanting to split it into multiple actual hook calls from the engine. :) I guess @BlauFeuer's original concern does come into play here though. If you already have split the hook internally, this does, in a way, introduce new things to take into consideration. It's not necessary (since the call happens from a hook you have control over), but it does extend the possible API overrides.

**Comment by vlegoff** [comment]
@Griatch and @BlauFeuer: what about providing `return_appearance` with a list of functions as I suggested in the previous comment?  If the list isn't provided (the default), then just display the usual, but one could override `return_appearance` and just call `super()` on it to pass in a list of functions.  Not sure it would be an improvement but we could have something like that:

```python
class DefaultObject(...):
    def return_appearance(self, looker, funcs=None):
        if funcs:
            string = ""
            for func in funcs:
                string += "\n" + func(looker)
            looker.msg(string.rstrip("\n"))
```

This way you could easily override, change the order of information, bypass some, add lines and such.  And there's no need to create hooks either.  That was a demonstration, it needs optimization, but that might explain the concept a bit more.  Don't know if it's a good idea.

**Comment by j-f1** [comment]
You could also default `funcs` to the list of items that the `return_appearance` hook uses by default.

For example:

```py
class DefaultObject(...):
    def return_appearance(self, looker, funcs=None):
        if funcs is None:
            funcs = [
                self.render_display_name,
                self.render_desc,
                self.render_exits,
                self.render_contents,
            ]

        string = ""
        for func in funcs:
            string += "\n" + func(looker)
        looker.msg(string.rstrip("\n"))
```

**Comment by vlegoff** [comment]
Good point.  However it would require creating these functions so they could be overridden, which sounds to me like sub-hooks.  A third option would be to provide a dictionary of default sub-functions, and add to it (that would be two different parameters and that might be less readable, but that might be easier to customize).

```python
class Room(DefaultRoom):
    def return_appearance(self, looker):
        super(Room, self).return_appearance(["title", "desc", "exits", ...], mapping=dict(title=self.get_display_name, desc=get_description, ...))
# in the mapping, title, desc, exits, things and users could be pre-defined
```

**Comment by j-f1** [comment]
I don’t see an issue with having sub-hooks, though. You can just override `return_appearance` as you’ve always done, and it’s unlikely<sup>[citation needed]</sup> that people already have methods with those names by accident.

**Comment by Griatch** [comment]
No, I don't think it's a good idea to supply a specific `funcs` argument just to specify which sub-hooks is to be called by `return_appearance` ... at some point you just need to override `return_appearance` and be done with it. Splitting into sub-hooks is just a code-convenience, it's not something necessary for functionality. If you still want to customize the call sequence for your own game you can use the `**kwargs` of `return_appearance`.

**Comment by Griatch** [comment]
Closing this, it's not going to be implemented any time soon.
