### ISSUE TITLE
Persistent delays connected to deleted objects can break server restart

### ISSUE THREAD

**Issue by Flabsy** [evennia/evennia#1407]
#### Brief summary of issue / Description of requested feature:
Connecting utils.delay(persistent=True) to an object and then deleting that object causes server reloads to break early. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create an object.
2. Create a utils.delay(persistent=True) with a callback method on that object.
3. Delete the object, then restart the server.

#### Error output / Expected result of feature
"564h, 100s, 0m -flr>@reload
 Server restart initiated ...
 Server restarting ...
The bright sun shines all around you.
564h, 100s, 0m -flr>"

As you see above, "Server restarted" never shows, but the server appears to finish booting and runs. No errlogs were created during this bug.

"564h, 100s, 0m -flr>@py evennia.scripts.taskhandler.TASK_HANDLER.tasks
evennia.scripts.taskhandler.TASK_HANDLER.tasks
{}"

Oddly enough, no persistent tasks appear even though the server seems to be attempting to call them.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
As per Vincent's suggestion, using '@py evennia.scripts.taskhandler.TASK_HANDLER.save()' solved the problem, and the server is properly restarting once more.

**Comment by vlegoff** [comment]
Fixed in PR #1411.  Thanks for the notice!

**Comment by Griatch** [comment]
This will close when devel branch merges.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
