### ISSUE TITLE
EvForm and automatic cropping

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1410]
#### Brief summary of issue / Description of requested feature:

While `EvForm` automatically crops text that is too long for a line or set of lines, giving it a different `crop_string` does seem to be ignored.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create an EvForm (can contain a single field).

```python
# testform.py
FORMCHAR = "x"
TABLECHAR = "c"

FORM = """
.--------------------.
|                    |
|  Desc: xxxxxxxxxxx |
|                    |
.--------------------|
"""
```
2. Connect to the server and display the EvForm with something like: `@py ev.utils.evform.EvForm("testform", {1: "A very long name with more characters"})`
3. Do the same thing but provide a `crop_string`: `ev.utils.evform.EvForm("testform", {1: "A very long name with more characters"}, crop_string="[ ... ]", crop=True)`

#### Error output / Expected result of feature

This will result in the long text being cropped, as expected.  However, the `crop_string` (step 3) doesn't seem to be taken into account.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

- Evennia devel.

**Comment by chainsol** [comment]
This is caused at [line 530 in evtable.py](https://github.com/evennia/evennia/tree/master/evennia/utils/evtable.py#L530)
Instead of using the set crop_string, enforce_size just uses a hardcoded string, ".."

**Comment by Griatch** [comment]
Fixed in devel, this will close when devel merges.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
