### ISSUE TITLE
nicks command fails to take into account non-"inputline" categories

### ISSUE THREAD

**Issue by RyanStein** [evennia/evennia#1415]
#### Brief summary of issue / Description of requested feature:
The stock nicks command does not take into account any of the non-"inputline" categories due to default arguments on the NickHandler class, which causes issue for the command's list and delete switches, when it tries to figure out what's in the nicklist.

#### Steps to reproduce the issue / Reasons for adding feature:

1. nick/object smith = rock
2. nicks

#### Error output / Expected result of feature
No nicks defined.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

https://github.com/evennia/evennia/blob/63ccac825a4300574c73716bcfb36d7b1a855b0a/evennia/commands/default/general.py#L126

**Comment by chainsol** [comment]
The NickHandler only accepts one category - how shall we pass on possible multiple categories?
@Griatch, any thoughts about that?

One way to solve it is to add multiple calls to caller.nicks.get with each category.

**Comment by Griatch** [comment]
@RyanStein: Yes, this indeed looks wrong. :)

@chainsol: Heh, I actually have a local branch trying to work out an effective way to query Tags using a combination of categories and keys. I've not managed to make that one work yet though. Should maybe revisit it to take another turn so as to get that into `devel`.

**Comment by chainsol** [comment]
@Griatch OK, I'll hold off on that hacky solution then, filtering with multiple categories would be good!

**Comment by Griatch** [comment]
This is no longer reproducible in develop, likely as a side effect of improvements in tag handling.

**Comment by Griatch** [comment]
Closed with merger of develop branch.
