### ISSUE TITLE
"You can't whisper to yourself."

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1416]
### Brief summary of issue / Description of requested feature:
The relatively new `whisper` command doesn't allow whispering to self/me, but there is a reasonable use case for it in some situations.

#### Steps
1. `whisper me = What?`
#### Reasons
When using multi-session modes, two or more sessions using two or more players (on the same or different accounts) puppeting the same character may need to communicate without speaking to the room.  Although `tell`/`page` allows same character cross-session communication, the users may not want or need the history of the conversation.

### Error output / Expected result of feature
Current output:
> You can't whisper to yourself.

Expected:
> You whisper "What?" to yourself.

### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Latest revision Evennia master and devel branch, all OSes.

If a special case is made for self-whispering to deny it, then it should be just as simple to allow and format the success to indicate you are whispering to yourself instead of naming the character, though either is usable.

**Comment by Griatch** [comment]
I guess it does no harm to remove the block on self-whispering. Implemented in `devel`, this will close when it merges.

**Comment by BlauFeuer** [comment]
With the additions in #1419 , `CmdWhisper` will now suppress `msg_self` when whispering to self so you just receive the whisper, skipping the notice that you sent it (because you might be the session that didn't send it to yourself).
