### ISSUE TITLE
`@uptime` only reports server uptime, not portal

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1420]
### Brief summary of issue / Description of requested feature:
Server uptime only tells half the story:

The dual nature of portal/server construction in Evennia isn't unique, but it's still uncommon, so it can be confusing to some to see server uptime shorter than the login times of some users (i.e. Some characters have been connected longer than the server's been up!).

I'd like to find the best way to also have the server report the portal's uptime in `@uptime` command, also.

### Steps to reproduce the issue / Reasons for adding feature:

1. Run Evennia for awhile, then `@reload`
2. `@uptime`

### Error output / Expected result of feature
`@uptime` doesn't show portal uptime.

### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
All Evennia branches, all OS

I've considered the easiest way might be to look at the creation date on server/portal.pid, but another way could be to have portal tell server when it was started, when server connects to portal, so server will always have portal's most recent startup timestamp (unless portal is restarted but server is not, which isn't common, but may be possible).

**Comment by Griatch** [comment]
Resolved in #1695.
