### ISSUE TITLE
Feature Request: Explicit API links

### ISSUE THREAD

**Issue by DamnedScholar** [evennia/evennia#1431]
I think it would be useful for the pages that explain how to use various features of Evennia to have explicit and easily visible links to the respective API entry or entries. Some pages do, but not all. I imagine this as a single entry at the top of the page, as in this mock-up:

![A screenshot of the Tags page with a line that reads "API: evennia.typeclasses.tags" right beneath the header. The typeclass path is a link to the API.](https://puu.sh/xCt2i/caaf0a74b4.png)

**Comment by Griatch** [comment]
This is a good idea I think. I wonder if it could be automated somehow.

**Comment by DamnedScholar** [comment]
I don't know that it would come up often enough to be worth automating. These links aren't likely to change outside of major version updates. I'd be satisfied with a style guide tweak to say that if the API documentation is on a different page from the prose documentation, there should be a link like that.

**Comment by Griatch** [comment]
I'm closing this issue and copying its content to [The documenation update planning document](https://github.com/evennia/evennia/wiki/Docs-refactoring)
