### ISSUE TITLE
`CmdSay`/`CmdWhisper` no longer call msg with OOB tuple using "type" kwarg

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1432]
### Brief summary of issue / Description of requested feature:
Per my https://github.com/evennia/evennia/issues/1174#issuecomment-326747235 regarding `at_say` code change and subsequent change in `CmdSay` from 0.6 to 0.7, `CmdSay`/`CmdWhisper` no longer call msg with OOB tuple using "type" kwarg. 

### Steps to reproduce the issue / Reasons for adding feature:

1. Run IRC Puppetbots by @CloudKeeper1 under Evennia 0.6
2. Follow merge procedure in https://github.com/evennia/evennia/issues/1174#issuecomment-315171643
3. Run IRC Puppetbots by @CloudKeeper1 under Evennia 0.7

### Error output / Expected result of feature
Bots are no longer able to identify text spoken by `CmdSay` or `CmdWhisper`; only `CmdPose` retains functionality.

### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
 #1419 solves the issue, though the remaining confusion with implementation and what was/is and was not/is not part of the API and what will be part of the API is too fluid or nebulous for me to make further alterations in the time I have to the PR for it to maintain or develop the intended design.

**Comment by Griatch** [comment]
`CmdSay`/`CmdWhisper` can by all means be updated to (again) pass the outputfunc tuple (including the `type` keyword) to `msg`. The *outputfunc tuple* should however *not* be passed into `at_say` - use the `whisper` kwarg to let that hook know of the difference.
