### ISSUE TITLE
`objects.py` `at_say` method forces `msg_self` message sent to caller

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1433]
### Brief summary of issue / Description of requested feature:
When rewriting `CmdSay` for the use case where the caller also sees the message others do (`msg_location`) in what has been called Director's perspective, `at_say` hook can not be used e.g. `at_say` hook does not support Director's perspective, only Actor's perspective (not fully).

@TehomCD  mentions the full Actor's perspective use case in https://github.com/evennia/evennia/pull/1419#issuecomment-328311528

### Steps to reproduce the issue / Reasons for adding feature:

1. Try to implement full Actor's perspective or Director's perspective `CmdSay` by using Evennia's 0.7 `at_say` object typeclass method.

Adding ability of `at_say` to handle multiple use cases.

### Error output / Expected result of feature
Abandoning the use of `at_say` is required to write a `CmdSay` that uses Director's perspective.

With some work, the `at_say` hook becomes useful to any who want more than the default output in the sample `CmdSay` command provided "out of the box".

### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
current Evennia devel branch, latest revision 

#1419 solves `at_say` method's limitation of requiring `msg_self` be sent to the `caller` of `CmdSay`/`CmdWhisper`, allowing a simple Director's perspective, but for an extended Actor's perspective use case, `at_say` requires ability to accept `receivers` as @TehomCD  describes.

**Comment by Griatch** [comment]
@BlauFeuer The practice of passing the outputfunc tuple into the `at_say` hook (as addressed in my last comment there) was/is my real concern with #1419. As for which perspective it supports or not, I might need to do do the implementation of Director/Actor stance to really see what is needed though, it's not clear to me neither from this issue nor from the PR.

**Comment by Griatch** [comment]
This should be resolved in da58d82
