### ISSUE TITLE
@tunnel doesn't support setting the exit typeclass

### ISSUE THREAD

**Issue by Pbizzel12** [evennia/evennia#1435]
#### Brief summary of issue / Description of requested feature:
I was creating tunnel locations and would go and change the typeclass for the exit after the object was already created, this would break all the connetions from room to room. After looking further it appears the tunnel class doesn't have the ability to accept a typeclass for the exit

digstring = "@dig%s %s = %s;%s%s" % (telswitch, roomname,
                                             exitname, exitshort, backstring)
the dig string is passed from tunnel class into @dig this doesn't allow one to pass exit to and here typeclass on creation

@dig[/switches] <roomname>[;alias;alias...][:typeclass]
            [= <exit_to_there>[;alias][:typeclass]]
               [, <exit_to_here>[;alias][:typeclass]]

#### Steps to reproduce the issue / Reasons for adding feature:

1. @tunnel e = supply shop
2.  @typeclass e = typeclasses.exit.door.Door
3.  All room connections break

#### Error output / Expected result of feature
cant move from room to room

**Comment by Griatch** [comment]
Closed by #1436. Will close when `devel` merges.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
