### ISSUE TITLE
execute_cmd custom passed kwargs persist until reload

### ISSUE THREAD

**Issue by RyanStein** [evennia/evennia#1444]
#### Brief summary of issue / Description of requested feature:
According to [the Object docs](https://github.com/evennia/evennia/blob/fb773a9e75f041d3865c37007b6050b4a2db047b/evennia/objects/objects.py#L457), it is possible to pass extra keyword arguments to `execute_cmd` which the Command instance object will then have access to on its attributes. This appears to be true, but the attributes are lasting indefinitely, as if they were being assigned to the class and not the instance: [here.](https://github.com/evennia/evennia/blob/b3c6e9d2cc836bc45ff93407a96e20f65d191141/evennia/commands/cmdhandler.py#L570)

#### Steps to reproduce the issue / Reasons for adding feature:

Run the following minimal test case in `@py/edit`.

```
def fn(self):
    from evennia.commands.cmdset import CmdSet
    from evennia.commands.command import Command

    class CmdDemo(Command):
        key = "demo"

        def func(self):
            self.msg('result: {}'.format(getattr(self, 'testing', False)))

    class CmdSetDemo(CmdSet):
        def at_cmdset_creation(self):
            self.add(CmdDemo())

    self.cmdset.add(CmdSetDemo())

    self.execute_cmd('demo')
    self.execute_cmd('demo', testing=True)
    self.execute_cmd('demo') # should theoretically be False, but...

fn(self)
```

#### Error output / Expected result of feature

At least according to how I've interpreted the documentation, the output should have read `False`, `True`, then `False` again, but it seems to persist the `kwargs` passed.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia version 0.7.0 (rev b3c6e9d2)

**Comment by Griatch** [comment]
It's the documentation that may be unclear in this case. A single Account/Object will re-use the same `Command` instance over and over - it's not recreated anew every run. This is allows you to store state on Commands for really complex styles of command syntax implementations. You can test this like this: 

```python
import time 
from evennia import Command
class CmdTest(Command):
    key = "test"
    def func(self):
        try:
            self.caller.msg("Stored time: %s" % self.time)
        except AttributeError:
            self.time = time.time()
            self.caller.msg("Storing current time: %s" % self.time)
```
Add this to your character cmdset and you'll find that the `self.time` remains the same after the first call. What happens in the example of `execute_cmd('demo', testing=True)` is that your Object's instance of the `demo` Command is assigned a new property `testing=True`.  This functionality of `execute_cmd` is not used by normal Evennia (there Command objects are manipulated directly), but it does behave as expected. 

The doc string is certainly not clear on this though, that should indeed be updated.

**Comment by Griatch** [comment]
This was added to wiki and docstring updated in `develop` branch.
