### ISSUE TITLE
Feature Request: Inconsistent naming of hooks

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1454]
#### Description of requested feature:

Current hooks are inconsistently named. For example we have `at_pre/post_puppet` but `at_before/after_say`. There is no reason to use both pre/before and post/after when they mean the same thing. This suggests homogenizing the hook names to all use pre/post (so `at_pre_say`/`at_post_say` etc. 

#### Reasons for adding feature:

It should be easy to remember what a pre/post hook is named. Using also before/after makes no sense except that it's due to organic growth and no hard naming guidelines over the years. 

#### Error output / Expected result of feature

A better homogenized API. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

No rush to implement this. This is something for develop branch and a future Evennia 0.8.

**Comment by trhr** [comment]
Assume the idea is a deprecation of the old commands in 1.0 and a removal somewhere further down the roadmap?

**Comment by Griatch** [comment]
This has been on the docket for years. The change would happen for 1.0. If it makes sense to leave redirect-stumps for the old hooks will be decided on a case-per-case basis - no matter how we do it, it's likely to break for some, considering how much you can modify these things.

**Comment by Griatch** [comment]
Implemented in develop.
