### ISSUE TITLE
@spawn objects have no location or home after ev 0.7

### ISSUE THREAD

**Issue by scyfris** [evennia/evennia#1455]
#### Brief summary of issue / Description of requested feature:

I recently switched to Evennia 0.7.  Spawning objects seems to have regressed, where objects without an explicit location are given locations of "None".  Previously, the behavior was to give a location of the caller if location was not specified (unless using the "noloc" switch).

#### Steps to reproduce the issue / Reasons for adding feature:

1. Add a prototype to prototypes.py, such as  
`TREE = {
    "key" : "Tree", 
    "typeclass" : "typeclasses.object", 
    "desc" : "A simple tree"
}
`
2. evennia stop/start to reload server.
3. In game, do @spawn TREE

#### Error output / Expected result of feature
After spawning tree, observe that there is no object spawned in current location.
@examine <tree's dbref> shows location to be "None.

The result previously was the location was caller's location.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is Evennia master branch , at commit 080c2a3b9f71a880811526b9884095013f24828b

As FYI - I think I found the root cause of the issue, it looks like potentially two issues:

1) in "evennia/commands/default/building.py", in CmdSpawn towards end of function:

`if "noloc" in self.switches and not "location" not in prototype:`

I think should be:

`if "noloc" not in self.switches and "location" not in prototype:`

2) In evennia/utils/spawner.py

```
def _handle_dbref(inp):
    dbid_to_obj(inp, ObjectDB)
```

should be 

```
def _handle_dbref(inp):
    return dbid_to_obj(inp, ObjectDB)
```

**Comment by scyfris** [comment]
I made a fix patch on a forked copy, I'm not sure if it's correct, but for reference I put it here: https://github.com/scyfris/evennia/commit/635200ca176caf28981a49e391beb1ef899c1979

It looks like both of these spots were changed recently, so perhaps it is a regression..but not sure.

**Comment by Griatch** [comment]
Fixed with the merger of the PR. Thanks!
