### ISSUE TITLE
EvForm tracebacks with certain dissimilar line lengths of form

### ISSUE THREAD

**Issue by RyanStein** [evennia/evennia#1459]
#### Brief summary of issue / Description of requested feature:
EvForm throws an exception, apparently if the form has a shorter line following a line with a cell.

In addition, [the EvForm documentation](https://github.com/evennia/evennia/blob/2bc76538d858edc03f5780557c3a17179bb252c3/evennia/utils/evform.py#L187) reports that `"CELLCHAR"` is the key name to use for the inline dict, but it is actually `"FORMCHAR"` which provides the functionality.

#### Steps to reproduce the issue / Reasons for adding feature:
```python
from evennia.utils.evform import EvForm

TEST_A = """
Test form: xx1xx
Won't crash?
"""

TEST_B = """
Test form: xx1xx
Crashhhhhh.
"""

TEST_A_FORM = {"FORMCHAR": "x", "TABLECHAR": "c", "FORM": TEST_A}
TEST_B_FORM = {"FORMCHAR": "x", "TABLECHAR": "c", "FORM": TEST_B}

form_a = EvForm(form=TEST_A_FORM, cells={1: 'hello'})
self.msg(form_a)

form_b = EvForm(form=TEST_B_FORM, cells={1: 'hello'})
self.msg(form_b)
```

#### Error output / Expected result of feature

```
File "evennia/utils/evform.py", line 215, in __init__
  self.reload()
File "evennia/utils/evform.py", line 418, in reload
  self.mapping = self._parse_rectangles(self.cellchar, self.tablechar, self.raw_form, **kwargs)
File "evennia/utils/evform.py", line 276, in _parse_rectangles
  if all(form[iy + i][ix] == cellchar for ix in range(leftix, rightix)):
File "evennia/utils/evform.py", line 276, in 
  if all(form[iy + i][ix] == cellchar for ix in range(leftix, rightix)):
File "evennia/utils/ansi.py", line 888, in __getitem__
  raise IndexError("ANSIString Index out of range")
IndexError: ANSIString Index out of range
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.7.0 (rev 2bc76538)

**Comment by Henddher** [comment]
Hello all, 

After a "quick" look with `pdb`, I arrived to the following:

The issue happens in line 312 when `form` is accessed with the indices obtained from matching the first `xxNxx` row.  
https://github.com/evennia/evennia/blob/a53957096f33ce991a52921fe9a26e1984367ede/evennia/utils/evform.py#L308-L315

It seems like a `form` object is always expected to be a rectangle. In @RyanStein's test form, that's not the case. See line 410
 
https://github.com/evennia/evennia/blob/a53957096f33ce991a52921fe9a26e1984367ede/evennia/utils/evform.py#L410-L411

I'm thinking that the following could do the trick:

```python
        # split into a list of list of lines. Form can be indexed with form[iy][ix]
        self.raw_form = _to_ansi(to_unicode(datadict.get("FORM", "")).split("\n"))
        _rectangularize(self.raw_form)
       ...
```

The `_rectangularize` function calculates the longest line and forces all lines to be of that max length, effectively converting the *jagged* `form` into a `rect`.

WDYT @Griatch?

**Comment by Henddher** [comment]
Another option is to modify `_to_ansi` and if `obj.__iter__` exists, extend each line to max.

https://github.com/evennia/evennia/blob/a53957096f33ce991a52921fe9a26e1984367ede/evennia/utils/evform.py#L164-L165

**Comment by Griatch** [comment]
@Henddher Yes, that looks like a good explanation and solution to this problem! Thanks for the analysis! Would you be willing to make a PR for it? If not, it's fine too, just let me know. :)

**Comment by Henddher** [comment]
Sure @Griatch! PR coming up

**Comment by Henddher** [comment]
PR #1648

**Comment by Griatch** [comment]
Closed with merge of PR
