### ISSUE TITLE
Giving multiple permissions to an account at once results in extra output lines

### ISSUE THREAD

**Issue by marco262** [evennia/evennia#1460]
#### Brief summary of issue / Description of requested feature:
Giving multiple permissions to an account at once results in extra output lines

#### Steps to reproduce the issue / Reasons for adding feature:

1. Login to the superuser
2. Use @perm to give another account multiple permissions at the same time

#### Error output / Expected result of feature

**Expected result:**
A single output line showing that all the permissions have been given.

**Actual result:**
Multiple identical output lines all showing that all the permissions have been given.

**Example command:**
`@perm *Lumos=Immortals, Wizards, Builders`

**Example result:**
```
Permission 'Immortals, Wizards, Builders' given to Lumos (the Account).
Permission 'Immortals, Wizards, Builders' given to Lumos (the Account).
Permission 'Immortals, Wizards, Builders' given to Lumos (the Account).
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

The number of duplicated lines seems to correspond to the number of permissions trying to be given. For example, if in the example above I'd only tried to provide two permissions, I would have received only two output lines.

**Environment:**
Master branch (pulled 2017-10-02 ~0200 GMT), server running on Windows 7. The client is connecting to the server via Telnet (MUSHclient)

**Comment by marco262** [comment]
Found the issue. In admin.py, lines 532 and 533 are within the `for perm in self.rhslist:` but they reference `rhs` instead of `perm`.

I simple solution would be to just change `rhs` to `perm`. That way, each line will only show the specific permission being granted.

A more elegant solution would be to refactor the latter part of that function to properly group the result messages.

**Comment by Griatch** [comment]
@marco262 Thanks for the report and the diagnostic! Should be easy enough to fix. :)

**Comment by dhruvhacks** [comment]
@Griatch May I take up this issue?

**Comment by Griatch** [comment]
@dhruvhacks Sure, go ahead.

**Comment by dhruvhacks** [comment]
@Griatch I have made the changes mentioned within this issue by @marco262 .
Please review. #1461 :slightly_smiling_face:
