### ISSUE TITLE
Feature Request: Add a switch to @tel to allow teleporting to an object's location

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1462]
#### Description of requested feature:
Evennia's `@tel` command defaults to teleporting your character into another object, for instance:
`@tel Griatch`
would teleport my puppeted character into Griatch's inventory.
This is a little odd, but expected, since `@tel` is meant to be used to teleport objects into other objects, e.g. `@tel an apple = chainsol` will teleport the apple to your inventory. For teleporting to other characters, this gets a little odd.

#### Reasons for adding feature:
Most people would expect `@tel chainsol` to teleport their character to the location. For a room or a container, Evennia's current behaviour makes sense. However, for teleporting to another character, it's a little odd - you end up part of their "inventory".

This is because Evennia treats objects differently than most systems - characters don't actually have an inventory, they have "contents". However, usually if you're teleporting to a character you expect to be in their location, not their inventory.

#### Expected result of feature/ideas on how to implement
One easy way to solve this is to add a switch to `@tel`, something like `@tel/loc` that teleports to the target's location.

**Comment by Griatch** [comment]
Just to clarify: This feature request is for adding `@tel/loc` functionality. It is also important that the command gives a clear error and cancels if the target object has a location of `None`.
