### ISSUE TITLE
Add a /delete switch to @accounts

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1477]
#### Brief summary of issue / Description of requested feature:

I suggest we remove the `@delaccount` command, instead, we could add a `/delete` switch to the `@accounts` command.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Most Evennia commands respect this syntax: a master command, switches for operations.  They are few exceptions, but I believe it would be worth having a uniform system.
2. `@accounts` could have an alias on `@account` and allow additional switches in the future to perform more advanced searches or operations.

#### Error output / Expected result of feature

`@accounts/delete <name>`

If you approve of it, I would be happy to offer a PR.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

* Evennia : current develop.

**Comment by Griatch** [comment]
I think this is a good idea. There are overall way too many commands doing very similar things. While these are all inspired by MUX, it's not like the concept of `Account` is present in MUX anyway.

**Comment by Griatch** [comment]
Implemented in #1682.
