### ISSUE TITLE
Starting Evennia as Described Runs the Server Interactively

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1483]
#### Brief summary of issue / Description of requested feature:
Evennia's source code, as well as the help for the Evennia command, seems to suggest that the default when calling Evennia from the command line is daemon mode - that is, a mode where input from the command line is not expected.

This would make sense, since Evennia could then be started from the command line simply and easily, without the need for GNUScreen/Tmux/etc, but instead, Evennia seems to start the *server* interactively no matter what command line options it's given.

Edit: To clear this up for anyone reading this in the future, as Griatch comments below, the server isn't starting interactively - there's a third process, the `runner` that is outputting to the terminal.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Install Evennia 0.7 on Linux ( Haven't tried with Windows )
2. Start the server with `evennia start`, which is described as defaulting to daemon mode.
3. Exit your terminal session
4. Reload the server from in-game, or take any action that would print information to the terminal

#### Error output / Expected result of feature
Evennia's server process crashes, the portal stays running. The source and the help for `evennia start` reads as if it should start both the server and the portal in daemon mode, but what actually happens is the server process expects to be able to output to STDOUT, and crashes when it can't.

Edit: Again, to clear this up for anyone in the future, running `@py print('whatever')` doesn't crash the server - as Griatch explains below, the reason the server crashes when running `reload` is due to the `runner`, not the `server` or `portal`.

Overall, I think this is a two part fix - fix the bug that causes daemon mode to be ignored for the server, and also change the default for `evennia start` to be interactive mode - it makes more sense that way for new users. Then daemon mode could be a flag instead, for those of us running a production server.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I've only tested this on Linux but it's been consistent. Screen/Tmux is the current solution for this, but overall for me, logging to a file is sufficient for production, and interactive mode is nice for development - the current thing we have is neither of those modes.

**Comment by Griatch** [comment]
I actually don't see any crashing when trying to print to stdout after having closed the terminal in which the server started. STDOUT should just be redirected nowhere, and that is what I see. Can you give an example, not related to reloading, where the Server crashes for not being able to write to STDOUT?

**Comment by chainsol** [comment]
No, it seems that's spot on - as you said, it's not the STDOUT crashing, it's only reload. I tried `@py print('testing')`, which didn't crash the server even without a terminal session. I would say, yes, looking at having the runner as a daemon would clear up some of the confusion!

**Comment by chainsol** [comment]
In the IRC, Griatch suggested running Evennia with `evennia start > server/server.log` would fix this issue - it does. For the moment that works much better, and is such a simple solution that I'll use that, but I'm looking at how the runner works anyway.

**Comment by Griatch** [comment]
Pondering this a little, I wonder if we, in principle, could get rid of the `runner` program. The reason it exists is because I had the idea that you'd want to reload both the portal and server independently. In practice though, I find that I reload the Server all the time, but when the Portal does need an update I just shut it down and start it again. Since you lose connections when reloading the Portal the need for a reload functionality is small - you must have access to the console to reboot it anyway. 

So it would be most possible to move the Server's reload functionality, now sitting in the runner, into the Portal instead. So that when shutting down the Server, it ends its existence by passing its launch arguments over AMP to the Portal, which uses these to simply start a new Server to connect to. Since things work well as they are, this is hardly something of high-priority, but it would make things more streamlined and self-contained.

**Comment by chainsol** [comment]
Is it possible to fix the current behaviour, where the `-l` flag doesn't fix the crashing problem?

**Comment by Griatch** [comment]
No, I don't think so. The way it is currently implemented, the Server *must* run in non-daemon mode for the Runner to be able to see its process ending and then restart it. That is regardless of where the log is stored, so while using `-l` will happily redirect to the log, the reload issue remains. What I think happens when you do `evennia start > server/logs/server.log` is that you are rerouting everything coming from that command - server and runner both - which is not the same thing as telling twisted to send the log to a particular file.

**Comment by Griatch** [comment]
Thinking a little more about this, I think that removing the ability to restart the Portal would work really well. This is how it might work: 

1. The `evennia_launcher` is used, same as today.
2. `evennia_launcher` starts the Portal as a detached process. It passes all launch parameters needed for *both* the Server and the Portal to the Portal. 
3. The Portal stores the Server's startup parameters. 
4. As part of the Portal's startup sequence, it will now start a new detached Server process using its launch parameters. It connects to the newly started Server as an AMP-client, same as now. 
5. When reloading, `evennia_launcher` will send the reload signal to the Server, same as now (or you use `@reload` in-game). 
6. The Server will send a new `SRELOAD` AMP command to the portal. It will then shutdown. 
7. The Portal acts on the `SRELOAD`. It spawns a new Server process (using its stored launch parameters) and connects to it. 

I'm not exactly sure what this would do on the interactive-mode front or how to output the server log to the console the way we do today. It's possible that this would mean everything will just log to file. On the other hand it would remove dependency on screen/tmux for running the server and truly make it self-contained in that sense.

**Comment by BlauFeuer** [comment]
Although I was used to the runner displaying the console output and never logging it (or if so, by output redirect), the server portal reload solution seems much cleaner and more like what I think most people would expect.  Not having to keep the runner process wrapped in screen/tmux to view it, but instead view via `tail -f` even outside of pyenv is more flexible, and easier to look through to find tracebacks or to search for any information. 

But now that server logging is forced, it's combined with portal.log by default, so there's still only one server log to manage.  Can we  have that server.log file rotated like the channel logs do in #1324  ?

**Comment by Griatch** [comment]
I mentioned this in chat already, but for completeness: the server+portal log is already set to rotate on a weekly basis.

**Comment by Griatch** [comment]
This is resolved in develop by the introduction of the new portal-server run mechanism.

**Comment by Griatch** [comment]
Closed with release of 0.8.
