### ISSUE TITLE
Feature Request: EvMenu Test Suite

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1484]
#### Brief summary of issue / Description of requested feature:
An EvMenu test suite would be much appreciated - relying on calling commands to enter the menu is fragile, and directly calling the menu nodes works, as long as you can identify any values you must set up before calling the menunode. A test suite could handle some of these things for us, and really make testing EvMenu a lot easier.

#### Steps to reproduce the issue / Reasons for adding feature:
Currently to test, for instance, Ainneve's chargen, we directly call session.execute_cmd, with a pattern of esoteric numbers to get to specific nodes. This depends on the current state of the character, session, and various variables - for instance, without a specific settings change, Ainneve's tests were failling with odd error messages.

#### Error output / Expected result of feature
A test suite that makes testing EvMenu easier and cleaner

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Right now, I'm unsure of how this would be best implemented. @Griatch has suggested some sort of crawler, to build up a map of the nodes in an EvMenu and then use that map for the test suite. Chime in!

**Comment by Griatch** [comment]
This is now implemented and available in the develop branch!

**Comment by chainsol** [comment]
Amazing. I'll start implementing tests based on it in the development version of Ainneve then!
