### ISSUE TITLE
Start up issues

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#1489]
#### Brief summary of issue / Description of requested feature:
With the latest pulls getting a trace back on 'evennia start'

#### Steps to reproduce the issue / Reasons for adding feature:

1. Shutdown server
2. Pulled latest Evennia code
3.  Started server

#### Error output / Expected result of feature

> 2017-10-24 16:18:39+0000 [-] Log opened.
> 2017-10-24 16:18:39+0000 [-] twistd 16.0.0 (/home/evennia/pyenv/bin/python2 2.7.12) starting up.
> 2017-10-24 16:18:39+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
> 2017-10-24 16:18:39+0000 [-] Traceback (most recent call last):
> 2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/bin/twistd", line 18, in <module>
> 2017-10-24 16:18:39+0000 [-]     run()
> 2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
>2017-10-24 16:18:39+0000 [-]     app.run(runApp, ServerOptions)
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/application/app.py", line 617, in run
>2017-10-24 16:18:39+0000 [-]     runApp(config)
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
>2017-10-24 16:18:39+0000 [-]     _SomeApplicationRunner(config).run()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/application/app.py", line 352, in run
>2017-10-24 16:18:39+0000 [-]     self.postApplication()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 207, in postApplication
>2017-10-24 16:18:39+0000 [-]     self.startApplication(self.application)
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 394, in startApplication
>2017-10-24 16:18:39+0000 [-]     service.IService(application).privilegedStartService()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/application/service.py", line 278, in privilegedStartService
>2017-10-24 16:18:39+0000 [-]     service.privilegedStartService()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/application/service.py", line 278, in privilegedStartService
>2017-10-24 16:18:39+0000 [-]     service.privilegedStartService()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/application/internet.py", line 106, in privilegedStartService
>2017-10-24 16:18:39+0000 [-]     self._port = self._getPort()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/application/internet.py", line 134, in _getPort
>2017-10-24 16:18:39+0000 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 478, in listenTCP
>2017-10-24 16:18:39+0000 [-]     p.startListening()
>2017-10-24 16:18:39+0000 [-]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 984, in startListening
>2017-10-24 16:18:39+0000 [-]     raise CannotListenError(self.interface, self.port, le)
>2017-10-24 16:18:39+0000 [-] twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:4006: [Errno 98] Address already in use."

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
'Evennia 0.7.0 (rev 781de86) (rev 781de86)
    OS: posix
    Python: 2.7.12
    Twisted: 16.0.0
    Django: 1.11.5
    Evennia MUD/MUX/MU* development system'

**Comment by Griatch** [comment]
This is not an Evennia bug. As it says in the traceback, this is because the port address is already in use on your server. Most likely by a previous instance of Evennia (because you didn't stop the old one properly or still have it running in a different console, for example). 

Evennia runs off Twisted so on linux you can try to stop all instances of Evennia with `killall twistd` (exactly like that). You may then need to remove the `.pid` files in `mygame/server` (but Evennia will tell you if that's necessary). If this still doesn't work, some other service is using Evennia's port. Shut that down or move Evennia to some other ports. 

Closing.
