### ISSUE TITLE
Feature request: Pass kwargs to 'exec' callables in EvMenu options

### ISSUE THREAD

**Issue by FlutterSprite** [evennia/evennia#1495]
#### Description of requested feature:
You can specify a function to call when an option is selected in EvMenu, but since there's no way to pass any kind of arguments to it, this severely limits its usefulness. 

#### Reasons for adding feature:
Being able to call the same function with different arguments for different menu options would be able to make code much more efficient and less redundant, as well as open up many more possibilities for what selecting an option in an EvMenu can do.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
In addition to 'key', 'goto', and 'exec', an optional field like 'exec_kwargs' would be a pretty intuitive way to implement this!

**Comment by Griatch** [comment]
Implemented in develop.
