### ISSUE TITLE
Feature request: Better display of no-description options in EvMenu

### ISSUE THREAD

**Issue by FlutterSprite** [evennia/evennia#1497]
#### Brief summary of issue / Description of requested feature:
When an option is defined in EvMenu without a description given, the menu option will be given the description "No description." There's no in-built way to present a menu option completely without a description.

#### Steps to reproduce the issue / Reasons for adding feature:
Simple menus may have options that are self-explanatory and require no descriptions, but even defining the description as an empty string will still leave a ":" character at the end of the option's key. There's currently no way to present a menu option with no displayed description at all - of course, best practice will be to provide descriptions in most menus, but there's lots of situations in which a description wouldn't be necessary.

#### Expected result of feature
Currently, a menu displaying options without descriptions looks like this:
```
Colors: A bunch of colors to pick from.
_________________________________________________________

Blue: Everyone likes blue, right?  
Red: No description.               
Yellow: No description.            
Green: No description.       
```
Ideally, if no description is given, this would look more pleasing:
```
Colors: A bunch of colors to pick from.
_________________________________________________________

Blue: Everyone likes blue, right?  
Red              
Yellow            
Green      
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
One last thing - currently, setting a description as `None` returns a traceback, which is a problem I ran into trying to dynamically generate menu options with no descriptions - I worked around it, but it would be nice if specifying a description as `None` worked the same way as not defining a description.

**Comment by Griatch** [comment]
Implemented in devel.
