### ISSUE TITLE
No way to clear object descs without resorting to @py

### ISSUE THREAD

**Issue by rnmissionrun** [evennia/evennia#1499]
#### Brief summary of issue / Description of requested feature:

Typing '@desc object=' does not clear the object description like it should.
 
#### Steps to reproduce the issue / Reasons for adding feature:

1. Typing the following command:

>> @desc here=
2. 
results in the description of the current room being set to 'here=', rather than being cleared.
3.

**Comment by rnmissionrun** [comment]
I wrote a small patch that fixes this issue.

https://pastebin.com/idRRgu5J

**Comment by Griatch** [comment]
Closed with #1691
