### ISSUE TITLE
No command sets found error after using guest account and quitting.

### ISSUE THREAD

**Issue by Ockad** [evennia/evennia#1500]
#### Brief summary of issue / Description of requested feature:
I enabled the guest system and decided to test this out by 'connect guest' on my localhost server.
After a couple of seconds I 'quit' and am met with the standard quit message. Then any command I enter does not get registered anymore (as it should be, but should it not take me to the connection screen again?)
Now I reload the server, reload the webclient, and still am being met with this error message and no connection screen:
> No command sets found! This is a critical bug that can have
> multiple causes.

This is what I have on my serverlog that occured when I did the guest stuff:

> 2017-10-29T00:19:37+0200 [AMPProtocol,0,127.0.0.1] [..] Logged in: Guest1(account 3) 127.0.0.1 (1 session(s) total)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [..] Logged out: Guest1(account 3) 127.0.0.1 (0 sessions(s) remaining) (quit)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 591, in _run_command
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     ret = cmd.func()
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\commands\default\account.py", line 673, in func
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     account.disconnect_session_from_account(self.session, reason)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\accounts\accounts.py", line 207, in disconnect_session_from_account
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     _SESSIONS.disconnect(session, reason)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\sessionhandler.py", line 508, in disconnect
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     session.at_disconnect(reason)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\serversession.py", line 257, in at_disconnect
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     self.sessid)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\scripts\monitorhandler.py", line 160, in remove
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     obj = obj.attributes.get(fieldname, return_obj=True)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 441, in get
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     attr_objs = self._getcache(keystr, category)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 285, in _getcache
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     conn = getattr(self.obj, self._m2m_fieldname).through.objects.filter(**query)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 513, in __get__
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     return self.related_manager_cls(instance)
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 830, in __init__
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::]     (instance, self.pk_field_names[self.source_field_name]))
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [::] ValueError: "<Guest: Guest1(account#None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
> 2017-10-29T00:20:05+0200 [AMPProtocol,0,127.0.0.1] [EE] User input was: 'quit'.
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\sessionhandler.py", line 762, in call_inputfuncs
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     _INPUT_FUNCS[cname](session, *cmdargs, **cmdkwargs)
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\inputfuncs.py", line 82, in text
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     categories=("inputline", "channel"), include_account=False)
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 901, in nickreplace
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     self.get(category=category, return_obj=True)) if nick and nick.key})
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 837, in get
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     return super(NickHandler, self).get(key=key, category=category, **kwargs)
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 441, in get
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     attr_objs = self._getcache(keystr, category)
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 310, in _getcache
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     in getattr(self.obj, self._m2m_fieldname).through.objects.filter(**query)]
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 513, in __get__
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     return self.related_manager_cls(instance)
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 830, in __init__
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::]     (instance, self.pk_field_names[self.source_field_name]))
> 2017-10-29T00:20:12+0200 [AMPProtocol,0,127.0.0.1] [::] ValueError: "<Guest: Guest1(account#None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\sessionhandler.py", line 762, in call_inputfuncs
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     _INPUT_FUNCS[cname](session, *cmdargs, **cmdkwargs)
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\inputfuncs.py", line 82, in text
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     categories=("inputline", "channel"), include_account=False)
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 901, in nickreplace
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     self.get(category=category, return_obj=True)) if nick and nick.key})
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 837, in get
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     return super(NickHandler, self).get(key=key, category=category, **kwargs)
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 441, in get
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     attr_objs = self._getcache(keystr, category)
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 310, in _getcache
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     in getattr(self.obj, self._m2m_fieldname).through.objects.filter(**query)]
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 513, in __get__
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     return self.related_manager_cls(instance)
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 830, in __init__
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::]     (instance, self.pk_field_names[self.source_field_name]))
> 2017-10-29T00:20:15+0200 [AMPProtocol,0,127.0.0.1] [::] ValueError: "<Guest: Guest1(account#None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\sessionhandler.py", line 762, in call_inputfuncs
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     _INPUT_FUNCS[cname](session, *cmdargs, **cmdkwargs)
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\server\inputfuncs.py", line 82, in text
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     categories=("inputline", "channel"), include_account=False)
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 901, in nickreplace
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     self.get(category=category, return_obj=True)) if nick and nick.key})
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 837, in get
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     return super(NickHandler, self).get(key=key, category=category, **kwargs)
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 441, in get
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     attr_objs = self._getcache(keystr, category)
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\evennia\evennia\typeclasses\attributes.py", line 310, in _getcache
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     in getattr(self.obj, self._m2m_fieldname).through.objects.filter(**query)]
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 513, in __get__
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     return self.related_manager_cls(instance)
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]   File "c:\muddev\pyenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 830, in __init__
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::]     (instance, self.pk_field_names[self.source_field_name]))
> 2017-10-29T00:20:16+0200 [AMPProtocol,0,127.0.0.1] [::] ValueError: "<Guest: Guest1(account#None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
> 2017-10-29T00:20:38+0200 [AMPProtocol,0,127.0.0.1] [..] Logged out: Guest1(account None) 127.0.0.1 (-1 sessions(s) remaining)
> 2017-10-29T00:20:39+0200 [AMPProtocol,0,127.0.0.1] [EE] No cmdsets found: None@127.0.0.1

And I when I try to use the webclient I keep on getting the serverlog:
> [AMPProtocol,0,127.0.0.1] [EE] No cmdsets found: None@127.0.0.1

When I telnet to localhost with the terminal all is fine though and I can see the connection screen.
#### Steps to reproduce the issue / Reasons for adding feature:

1. 'connect guest'
2. 'quit' as guest
3. In webclient try to login again and meet the error

#### Error output / Expected result of feature
No command sets found! This is a critical bug that can have
multiple causes.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
0.7.0 - webclient on Windows 10 in Firefox.

**Comment by Ockad** [comment]
Apparently, clearing the browser cookies solved this bug for the webclient.

**Comment by Griatch** [comment]
I can reproduce this. It seems like the webclient's auto-login mechanism and the way guest-accounts are not 'persistent' between logins are not jiving well.

**Comment by Griatch** [comment]
I have a partial fix for this in local development, but it turned out to be a little fiddly to get right.
