### ISSUE TITLE
Combine default commands @script and @scripts

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1502]
### Brief summary of issue / Description of requested feature:
Similar to #1477, I suggest we remove the `@scripts` command, and move its functionaly to `@script`.  An example is to add a /list switch to the CmdScript (`@script` command), or present the list when no args are provided.

There's a bit more involved with these two commands, which are easily confused.  Both start and stop scripts, and one adds scripts.  There's a reference to an /add switch in CmdScript, instructing the use of that switch in `@scripts`, but there is no /add switch documented in it.  See: https://github.com/evennia/evennia/blob/master/evennia/commands/default/building.py#L2453

Whereas the singular is to work on single scripts and the plural works on global scripts and all scripts (with the start/stop sub command), as far as I understand, the global script is simply a script that isn't attached to an object.  

`@scripts` does also kill and validate _a script_, which is confusing since you'd think the singular `@script` command would have that function, instead.

I believe it's possible to add all functionality of both into one command with a more intuitive syntax and use of more switches.

### Steps to reproduce the issue / Reasons for adding feature:
Quoting and paraphrasing @vlegoff 
1.   _Most Evennia commands respect this syntax: a master command, switches for operations. They are few exceptions, but I believe it would be worth having a uniform system._
1.    `@scripts` could have an alias on `@script` and allow additional switches in the future to perform more advanced searches or operations.

#### Error output / Expected result of feature
`@script`  (or `@script/list`)

yields:

`Usage: @script[/switch] <obj> [= script_path or <script key>]`

Instead of something like:
```
+-------+------------+------------+--------+------+------+----+------------+---------------------+
| dbref |        obj |        key | intval | next | rept | db |  typeclass |                desc |
+~~~~~~~+~~~~~~~~~~~~+~~~~~~~~~~~~+~~~~~~~~+~~~~~~+~~~~~~+~~~~+~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~~~~~+
|     4 | ircbot-ZZZ | ircbot-ZZZ |     -- |   -- |  -/- |  * | BotStarter | bot start/keepalive |
+-------+------------+------------+--------+------+------+----+------------+---------------------+
```
### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This is probably best done in the development branch

**Comment by Griatch** [comment]
Yeah, in line with #1477, I'd agree that a merger/homogenization of these commands are in order. The `@scripts` command was originally created as an analogue to the `@objects` and `@players` commands (now `@accounts`), which together represented the only Typeclass bases in Evennia at the time. The `@script` command was the original one, and inherited from an ancient time when a "Script" meant something very different. At the time there were also no other time-keeping mechanisms. 

In principle I guess something similar should be done for `@objects` for consistency, but it's equivalent would be  `@create`, `@dig` etc, and messing with those would just confuse everyone. :)

**Comment by BlauFeuer** [comment]
Looking at the syntax for both:
`@script[/switch] <obj> [= script_path or <scriptkey>]`
`@scripts[/switches] [#dbref, key, script.path or <obj>]`

`@script` wants an in-game object, and `@scripts` wants a script object.

Perhaps an /on switch would indicate referencing an in-game object:
`@script/on ball [= script_path or <scriptkey>]`  without the right-hand side would display all scripts on that object, and with the right-hand side would "add and start" 

Then without the /on switch, the reference is assumed to be to a specific script object directly.


That's just some thoughts.  I use `@objects` command to view newly created in-game objects, that of course `@spawn`, `@create`, `@dig`, `@open`, etc. have created.  I don't think it'd be as intuitive to have a `@dig/list` to show recent digs, though -- it'd be better to have more switches to filter `@objects'. The command doesn't deal with non-in-game objects like accounts and scripts, though.  It could be something to add. Those things I use the web admin interface to view -- not really seeing a need for updating `@objects` yet.

**Comment by Griatch** [comment]
Scripts are different from objects/accounts in that they are both their own thing (something which has become a lot more commonly useful than I originally imagined) as well as something stored "on" an object (which I used to think would be their main use). As it turns out, my experience is that storing "on" something else tend to be something mostly handled in code rather than assigned as part of building. So making the on-object storage a switch (rather than the default) sounds like a good idea, while trying to retain consistency with `@account` where functionality overlap.
