### ISSUE TITLE
MSDP LIST command unrecognized

### ISSUE THREAD

**Issue by RyanStein** [evennia/evennia#1507]
#### Brief summary of issue / Description of requested feature:
The MSDP `LIST` OOB command is unrecognized, which raises an error but does not prevent the client from connecting. The [list command](http://tintin.sourceforge.net/msdp/) appears to be integral to the protocol but also something which may be game specific.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Make sure GMCP is disabled on client, just in case that is preferred.
2. Enable MSDP.
3. Connect to Evennia and check stdout for the error.

#### Error output / Expected result of feature
```
[AMPProtocol,0,127.0.0.1] [EE] Session 2: Input command not recognized:
[AMPProtocol,0,127.0.0.1] [EE]  name: 'list'
[AMPProtocol,0,127.0.0.1] [EE]  args, kwargs: ('COMMANDS',), {}
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.7.0 (rev bc868f8f)

It might be possible to alias or modify `client_options` to support this, but there will likely have to be a rename for it somewhere along the way to `inputfuncs.py` as `list` is obviously a keyword for the list type in Python. Perhaps a conditional that renames it to `msdp_list` before running the inputfunc would work.

**Comment by Griatch** [comment]
Whether or not this is triggered on first connect depends on which client you are using I believe. So which client is this tested with?

**Comment by RyanStein** [comment]
This was tested with Mudlet 3.5.0.

**Comment by Griatch** [comment]
The LIST command is an optional part of the MSDP standard. Mudlet is wrong by force-sending it.

**Comment by Griatch** [comment]
Implemented in develop.
