### ISSUE TITLE
@delaccount does not delete account - gives error

### ISSUE THREAD

**Issue by Belameephus** [evennia/evennia#1514]
#### Brief summary of issue:

@delaccount does not delete account - gives error

#### Steps to reproduce the issue:

1. Logged onto mygame as #1 account (superuser) 
2. attempted to delete a test account using @delaccount Testperson 
3. Testperson account not deleted and error displayed.

#### Error output 

Traceback (most recent call last):
  File "/home/mark/muddev/evennia/evennia/commands/cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File "/home/mark/muddev/evennia/evennia/commands/default/admin.py", line 304, in func
    account = accounts.pop()
AttributeError: 'QuerySet' object has no attribute 'pop'

An untrapped error occurred.
(Traceback was logged 2017-11-11 14:49:35-0000).

#### Extra information: 

Evennia 0.7.0 (rev 4a282b8)
OS Linux Mint 17.2 Rafaela 
Python 2.7.6
Twisted 16.0.0
Django 1.11.6

I had this occur on my previous Evennia mygame (same game same Evennia revision) so I restarted/reloaded and reinitialized as a new game starting from scratch. 

Same results:

**Comment by chainsol** [comment]
Huh, that's a really interesting one. It seems we used to provide a list instead of a QuerySet. Anyway, this is a one-line fix, I'll put PR in a minute!
