### ISSUE TITLE
Notifications popup window obscured by help window

### ISSUE THREAD

**Issue by christophermstaats** [evennia/evennia#1531]
#### Brief summary of issue / Description of requested feature:
When the notifications window pops up it is obscured partially by the help window when the browser is not maximized, there does not appear to be a way to resize either or move them independently. Closing the help window via the escape key results in both windows closing.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Set the browser to take up half or less of the horizontal screen real estate.
2. Open help file from command prompt then play until a notification is triggered (requires popup notifications to be enabled)
3. Hit esc. to clear the help window and lose the notification with it.

#### Error output / Expected result of feature
Being able to resize the help window or move it independently of the web client would give us the option to reveal the underlying message. Or step the esc. key so it only closes one window at a time.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Browser is Firefox ESR running in an offline Kali Linux development / network security testing distro of Debian. Evennia is ver. 0.7.0 (rev 5986f994) ((yeah I intend to update, thought I was on 0.8 already))
![20171213_184320_hdr](https://user-images.githubusercontent.com/34146579/33970180-393a4cda-e037-11e7-8d2d-af70ed1b3191.jpg)

**Comment by chainsol** [comment]
The problem here is the pop-up is part of the initial window. It can't be moved outside of the window - it's a JavaScript controlled piece of HTML.

**Comment by christophermstaats** [comment]
So we implement a control that causes the first esc. entered to only close the help window before the notifications window can be closed.

**Comment by chainsol** [comment]
That would be quite easy! This weekend I'll be submitting a first patch that changes some of this stuff, but I'll submit a bug fix for the escape behavior.

**Comment by Griatch** [comment]
> Evennia is ver. 0.7.0 (rev 5986f99) ((yeah I intend to update, thought I was on 0.8 already))

There is no Evennia 0.8. Version 0.7 is the latest.

**Comment by christophermstaats** [comment]
Sorry about that, different project I was thinking of with the 0.8 thing.
