### ISSUE TITLE
ChannelDB.objects.search_channel does not correctly use aliases

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1534]
#### Brief summary of issue / Description of requested feature:
In a stock Evennia game, attempt to search for the OOC channel via its alias:
```
@py ev.ChannelDB.objects.search_channel('pub')
```
You'll get an empty list - aliases don't work for search_channel
This causes problems when one sets an alias for a channel, you'd still be able to chat on that channel, but addcom and delcom won't work, since they rely on search_channel.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Look at [the source code for search_channel](https://github.com/evennia/evennia/blob/master/evennia/comms/managers.py#L386). We seem to be grabbing a list and looping through it, instead of querying? Maybe a query instead.

**Comment by chainsol** [comment]
@v-legoff suggested we use ChannelDB.objects.get_channel instead, which seems to work much much better.

**Comment by Griatch** [comment]
Whereas `get_channel` is ok, the `search_channel` should use similar mechanics under the hood and work similarly. So it's weird that they don't/

**Comment by chainsol** [comment]
If I recall, the cause is that we use a list comprehension in `search_channel` to query aliases, instead of using the alias handler.
