### ISSUE TITLE
Feature Request: Change arg_regex default

### ISSUE THREAD

**Issue by tricuspa** [evennia/evennia#1541]
#### Brief summary of issue / Description of requested feature:
Some wiz commands due to smart capacity "arg_regex" are overly generalized resulting in unusual results. 

#### Steps to reproduce the issue / Reasons for adding feature:

1.  When trying to use "Bank" from wiz+ account results in  @ ban k
2. It would be helpful to be able to lock down certain commands so the suggested command does not autorun or at least provide a warning before initiating some of the stronger commands..  

#### Error output / Expected result of feature
Whether through a prompt **Did you mean to @ban k (y/n)?** and then wait for input or optionally "There is no 'bank' here did you mean @ban k?**

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Perhaps provide a way to separate autorun of command, warnng about command and must be used as explicitly stated.

**Comment by TehomCD** [comment]
You can specify a default regex for commands in settings under `COMMAND_DEFAULT_ARG_REGEX`. I didn't want the behavior you described so I set my default arg regex to prevent it: `COMMAND_DEFAULT_ARG_REGEX = r'^[ /]+.*$|$'`

**Comment by Griatch** [comment]
As @TehomCD points out, it is already possible to add this functionality using the `COMMAND_DEFAULT_ARG_REGEX` setting. I agree that the default behavior, while the most generic and flexible, has caused people some confusion when expecting the workings of a more strict parser. So changing the default could be an idea, but one would need to carefully consider the effects of this on default commands and general command recommendations.

**Comment by TehomCD** [comment]
In my experience, there aren't that many exceptions where not having whitespace before args is desired/expected behavior - the ones I ran across were pose and emit. In the former case, players have an expectation of making a command as a possessive statement with different aliases like `;`, and in the latter case there was the conflict with switches for the regex when using the alias `\\`. I feel that the exceptions are rare enough where we might just put a comment in both commands where we set their arg_regex to None to explain why, and hope that users who want to emulate the behavior for similar commands would find it easy enough to adopt.

**Comment by BlauFeuer** [comment]
I've seen this behavior, too, and agree with TehomCD 

I suspect that just say and pose are the two main ones.
Just add `arg_regex = None` in the command class for those exceptions and change your COMMAND_DEFAULT_ARG_REGEX and that should defeat the confusion with the other commands that you'd expect to require a space.

As for the other part, if you want an Are you sure? dialog, the get_input utility would be good for that.

**Comment by tricuspa** [comment]
Thank you all for your assistance!

We put it to work, and  now understand the use arg_regex = None for some commands, but prefer the default be r'^[ /]+.*$|$'  

Basically putting a space for most commands.

**Comment by chainsol** [comment]
I agree on that, I think that defaulting to a space between the command and arguments would make the most sense - It's not intuitive and leads to some odd edge cases when we assume commands based on partial matches.

**Comment by Griatch** [comment]
I now implemented this in `develop` branch by changing the default `COMMAND_ARG_REGEX` to the regex suggested by @TehomCD above (and setting `arg_regex=None` for the commands that require it). So by default commands now expect to end by a space or by `/` (to match `MuxCommand` base)

As a bonus I also added a confirmation question to the `ban`/`unban` commands.
