### ISSUE TITLE
Typo in online wiki

### ISSUE THREAD

**Issue by texdarkstar** [evennia/evennia#1542]
#### Brief summary of issue / Description of requested feature:
Minor typo in the online wiki.
I would issue a PR but I'm not sure how to.

#### Steps to reproduce the issue / Reasons for adding feature:
[wiki page](https://github.com/evennia/evennia/wiki/evennia.objects.objects#defaultobjectsearch)

>exact (bool): if unset (default) - prefers to match to beginning of string rather than not matching at all. If set, requires exact mathing of entire string.

**Comment by BlauFeuer** [comment]
One doesn't need to submit a PR to edit the wiki page.

Might be generated content, in which case @Griatch fixes it so it doesn't generate the typo again next time, but otherwise I just press the edit button and fixed it for now.

**Comment by texdarkstar** [comment]
Ahh. Okay, I'll keep that in mind next time I see that.

The speed with which you guys respond is amazing.

**Comment by BlauFeuer** [comment]
Thanks!

I think the typo was in 4 places. I edited it again to get the others.  I'll leave it to @Griatch to close this, though, just in case it's part of generated content.

**Comment by BlauFeuer** [comment]
The typo is in generated content, in the docstrings of the code, so it is a valid issue and can be resolved with a PR...

https://github.com/evennia/evennia/blob/781de86777dfb8e8cfdf023e8663f41297360fc0/evennia/contrib/extended_room.py#L192
https://github.com/evennia/evennia/blob/5ad10d70558dd09aa6ea42a37d7d47ac017c7ba4/evennia/contrib/rpsystem.py#L1203
https://github.com/evennia/evennia/blob/1e6f9bc00139bd2df2b359943f1be4387aff573d/evennia/objects/objects.py#L338

And maybe one other place. I can't tell at the moment.  I only fixed it temporarily in the wiki.

**Comment by Griatch** [comment]
Yes, this needs to be fixed in the sources. It will be part of the wiki when I rerun the wiki source build tools (which I run locally on the sources now and then).

**Comment by Griatch** [comment]
Updated in the sources and synced to the wiki.
