### ISSUE TITLE
'look' issue in Tutorial at Cliff by the Coast (#9)

### ISSUE THREAD

**Issue by thenomain** [evennia/evennia#1544]
#### Brief summary of issue / Description of requested feature:

Typing 'look old' in the Cliff by the Coast doesn't offer any feedback at all.

('look old w' or 'look old b' seem to be fine.)

#### Steps to reproduce the issue / Reasons for adding feature:

1. Build the tutorial.
2. Go to the Cliff by the Coast
3. Type 'look old'.

#### Error output / Expected result of feature

Output: Null, nothing, not even a blank line. Game does not appear to respond.

Expected Output: Some kind of multi-match error.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

I'm using the latest Evennia, as per the Intro Document, as of today, December 30th, because I have no life.

**Comment by Griatch** [comment]
Ah, yes that looks strange. You are supposed to get a multi-match menu from that.

**Comment by Griatch** [comment]
@thenomain As it turned out, the tutorial uses a custom version of the look command for certain rooms, and somewhere along the way it got the call of the multimatch-handler wrong, passing `None` instead of the matches (so it returned nothing). Fixed now, thanks for the catch!
