### ISSUE TITLE
Feature Request: Adding Support for  the gametime module to link 1:1 realtime including down times

### ISSUE THREAD

**Issue by roymcsp** [evennia/evennia#1545]
#### Brief summary of issue / Description of requested feature:
I would like to request adding support for the gametime module to mirror real time including downtimes when the time factor is set to 1.0 for a 1:1 gametime/realtime ratio

**Comment by Griatch** [comment]
Implemented in `develop` branch.

**Comment by Griatch** [comment]
Closed with release of 0.8.
