### ISSUE TITLE
available_languages() not returning languages

### ISSUE THREAD

**Issue by grungies1138** [evennia/evennia#1554]
#### Brief summary of issue / Description of requested feature:
when using the rplanguage contrib, I have added several languages and was able to successfully use obfuscate_language to 'translate' them to the new language.  However, when I attempt to use the available_languages() function, it only returns 'default'

#### Steps to reproduce the issue / Reasons for adding feature:

1. Add language to rplanguage's language_handler
2. test that language is working with obfuscate_language()
3. utilize the available_languages() method.

#### Error output / Expected result of feature
only returning 'default' instead of list of languages in the language_handler

**Comment by grungies1138** [comment]
FYI, I was able to work around this problem by doing

`rplanguage.LanguageHandler.objects.get(db_key='language_handler').db.language_storage.keys()`

**Comment by Griatch** [comment]
@grungies1138 I cannot reproduce this issue. Here's an example test: 
```
from evennia.contrib import rplanguage
> rplanguage.add_language(key="testlanguage1")
> rplanguage.add_language(key="testlanguage2")
> rplanguage.add_language(key="testlanguage3")
> rplanguage.LanguageHandler.objects.all()[0].add(key="testlanguage4")
> rplanguage.available_languages()
['testlang1', 'testlang3', 'testlang2', 'testlang4']
```
Does the above work for you? Could you give a more explicit example for how you reliably reproduce this problem?

**Comment by grungies1138** [comment]
I discovered that I was expecting a string back instead of a list and failed to convert it properly.  Upon further testing I discovered it working successfully.
