### ISSUE TITLE
session.at_sync has typo, but is never called

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1555]
#### Brief summary of issue / Description of requested feature:
`session.py` has a typo at https://github.com/evennia/evennia/blob/master/evennia/server/session.py#L136

`account.attributs` instead of `account.attributes`. But this doesn't seem to be called anywhere and generate an error, since it looks like serversession just overrides the method entirely and doesn't call super.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Check link

#### Error output / Expected result of feature
No AttributeError is raised because code doesn't seem to be called.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I'm not sure if the code is a relic of something that isn't used anymore and should be replaced by a simple pass, or if a super() call is missing and it has to be fixed.

Edit: Possibly related to #1353 ?

**Comment by Griatch** [comment]
@TehomCD As noted, this was overridden in the serversession child class, but that one never called `super()`. Fixed now. We'll see if this has an effect on those having trouble with #1553
