### ISSUE TITLE
Feature Request: Safe .update() method for SharedMemoryModel

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1559]
#### Brief summary of issue / Description of requested feature:
Doing an `update()` call currently on SharedMemoryModel is not a safe operation with caching, because instances in the cache will not have the most current value. If they're saved, they'll override any updated value in the database.

#### Reasons for adding feature:

1. To have the performance gains of update while keeping the cache current.

#### Expected result of feature
No more mismatches between cached instances and the database.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Probably the first step would be converting the current SharedMemoryManager into a queryset that's used `as_manager()`. Otherwise, doing any `filter()` calls would prevent custom update from working (and also stops the current `get()` method from working, for that matter, in the same situation). After a `super().update` call, determine which cached instances are in the queryset (filter it further with an __in check against the IDs of instances in the cache, maybe?) and update their values. Ideally you'd do this without hitting the database, just changing the values in memory, otherwise there'd be no real performance gain from using update() at all - but I'm not sure how to handle things if they use an `F()` expression.

**Comment by Griatch** [comment]
@TehomCD Not sure exactly how `as_manager` operates, but maybe? Also, just to be clear, are you sure caching mismatches is due to problems in the SharedMemoryModel and not due in-handler caches not updating (if an on-object handler has its own cache, changes in SharedMemoryModel would help ltittle)? It might be useful with a small code snippet to exemplify this with certainty.

**Comment by TehomCD** [comment]
I haven't used `as_manager` before, but I had to do a much more arduous process of defining QuerySets and assigning them to managers in order to get the same effect. Using `as_manager` seems to be the much simpler solution to be able to have custom manager methods work when you chain them or have them after a filter or whatever.

As for the problem itself, here's an example. We have a resource called `action_points` that represents 'offscreen' actions characters can take during the week, which looks something like this:
```
class RosterEntry(SharedMemoryModel):
    action_points = models.IntegerField(default=0)
```
Say you have Bob, a RosterEntry with action_points currently of 50, currently running around the game and cached. In a script that's meant to update everyone, you do: `RosterEntry.objects.all().update(action_points=F('action_points') + 20)` to try to increment everyone by 20. Bob, in game, still shows as 50, while in the database he'd be 70. However, the real problem is that if Bob does something that spends it, it'll use his current value, then save it. So if Bob spends 10 points, he'd go down to 40, save, then override the value in the database, winding up with 40 rather than the 60 that was intended.

So what I was trying to suggest is that if we changed the manager to override the `update()` method, we could look at objects in the cache and try to change them appropriately. If they're all just changed in-memory by the same values, they should then match what was intended in the database. The trick, though, is that trying to figure out what the intended value is if an `F()` expression is passed could be really difficult. While we could just flush or reload all the affected instances, that largely cancels out any performance gain we'd get from caching - it might be the only way to make them match up, though.

**Comment by robotfactory** [comment]
Any PRs or work elsewhere that can be tied to this one? Triaging some older issues.

**Comment by TehomCD** [comment]
I don't think so, no - as far as I know the caching mechanism hasn't been touched since I opened it. Figuring out which objects in the cache to update and how with inspection of Q and F objects seems so difficult that flushing the cache entirely on update might be the way to go. However, there were some issues with flush cache, which #1354 is about, if you want to look at that as well - from what it looked like, some of django's internal caching mechanisms could conflict with cache invalidation in the SharedMemoryModel, but I never was able to dive enough into django's internals to figure out the cause.

**Comment by robotfactory** [comment]
I'll go through some other issues and PRs to see if there has been any
other relevant work done and I'll reference it here.

I'm new to the project so diving in too deep on this one isn't something in
going to be able to do myself.

**Comment by Griatch** [comment]
No further work has been done with this as far as I know, no.

**Comment by Griatch** [comment]
Not sure how to proceed with this; the above would likely also need to be revisited and reviewed for Django 2.2.

**Comment by Griatch** [comment]
@TehomCD Any ideas for how to continue with this one, or if it should be continued at all?

**Comment by TehomCD** [comment]
Unfortunately I don't think there's a good way to do this in a performant way - unless they're calling update on an already evaluated queryset there wouldn't be a way of getting objects from it without executing the query again, which would violate the point of caching. A possibility would be to put in a `logger.warn` or `logger.warning` into the update method for SharedMemoryModel managers to notify them that it's not a cache-safe operation and they should operate accordingly -- notifying people of a possible gotcha in logs that they could ignore or act upon might be the best thing we can do.

**Comment by aarcro** [comment]
For caching ORM stuff I've used https://github.com/Suor/django-cacheops in the past, don't know if you could save some headache by leveraging that. It's really cleaver about invalidating caches.

**Comment by Griatch** [comment]
Closing this, it has been sitting for forever with little progress.
