### ISSUE TITLE
Test Runner fails to find models in installed apps if using relative imports

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1560]
#### Brief summary of issue / Description of requested feature:
Although this is very easy to work around, this is a bizarre issue that might be a django problem, not an evennia problem. If a test case for Evennia's command test runs a command in a module that has a relative import for a model (eg: `from .models import MyModel`), the test runner will report an error that MyModel is not in installed apps/does not declare an explicit app label. If you change the import to use the full path (eg: `from world.conditions.models import MyModel`), it'll work fine. Same thing happens with views, I believe.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Have testrunner test a module that uses a relative import of a model

#### Error output / Expected result of feature
Something like this:
```
======================================================================
ERROR: arx.world.conditions.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: arx.world.conditions.tests
Traceback (most recent call last):
  File "C:\Python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "c:\arx\arx\world\conditions\tests.py", line 6, in <module>
    from . import condition_commands
  File "c:\arx\arx\world\conditions\condition_commands.py", line 5, in <module>
    from .models import Modifier
  File "c:\arx\arx\world\conditions\models.py", line 13, in <module>
    class Modifier(SharedMemoryModel):
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 206, in __new__
    return super(SharedMemoryModelBase, cls).__new__(cls, name, bases, attrs)
  File "c:\arx\Lib\site-packages\django\db\models\base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class arx.world.conditions.models.Modifier doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I have no idea if this is an Evennia problem or a Django problem or what, and it's trivial to work around, but I figured it'd bear mentioning even if it's too much trouble to fix just so people realize why tests might fail.

**Comment by Griatch** [comment]
Yeah, it's unclear if this is an Evennia issue or something with Django or its test-framework.

**Comment by TehomCD** [comment]
I've been trying to research this and I've seen a few mentions of people running into the same issue when running tests in django, so at least that confirms it's not an Evennia issue.

**Comment by Kelketek** [comment]
This is expected behavior for Django. When importing modules, the machinery for the ORM is initiated. As of the latest version of Django, they've taken to adding explicit app labels to Django apps so that when importing, the internal machinery knows whether or not the models imported have already been initialized, and what module they belong to in an absolute sense. You should declare an explicit app label if you haven't already, as this will fix the problem. The latest Django tutorial should have an example, but I'm not sure.

**Comment by TehomCD** [comment]
@Kelketek 

To be clear, the app does have an explicit app label, as far as I can tell:
```
# in settings.py
INSTALLED_APPS += ( # other models omitted
                                     'world.conditions.apps.ConditionsConfig'
 )

# in world.conditions.apps.py
class ConditionsConfig(AppConfig):
    name = 'world.conditions'
```

A test imports a command class, which has a top level import of one of my models. If the import is done in the form of `from world.conditions.models import MyModel` everything works fine. The error occurs if I do `from .models import MyModel`.

It does appear that relative imports cause it to get confused with the path of the model, trying to find it at `arx.world.conditions` rather than `world.conditions`. If I were to add the following to my model:
```
    class Meta:
        app_label = "conditions"
```
I get the following traceback instead:
```
======================================================================
ERROR: arx.world.conditions.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: arx.world.conditions.tests
Traceback (most recent call last):
  File "C:\Python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "c:\arx\arx\world\conditions\tests.py", line 6, in <module>
    from . import condition_commands
  File "c:\arx\arx\world\conditions\condition_commands.py", line 5, in <module>
    from .models import Modifier
  File "c:\arx\arx\world\conditions\models.py", line 13, in <module>
    class Modifier(SharedMemoryModel):
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 206, in __new__
    return super(SharedMemoryModelBase, cls).__new__(cls, name, bases, attrs)
  File "c:\arx\Lib\site-packages\django\db\models\base.py", line 319, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "c:\arx\Lib\site-packages\django\apps\registry.py", line 224, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'modifier' models in application 'conditions': <class 'world.conditions.models.Modifier'> and
<class 'arx.world.conditions.models.Modifier'>.
```

With an `arx.world.conditions.models.Modifier` and a `world.conditions.models.Modifier` in conflict. Removing the `class Meta` explicit app_label and changing the path in `INSTALLED_APPS` and AppConfig's name attribute generates different errors, but note that this is after the test is actually run - one is during `tearDown` and the other is a result of the `CommandTest`'s call method, just making a test failure:
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
FE
======================================================================
ERROR: test_modifiers_cmd (arx.world.conditions.tests.ConditionsCommandsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\arx\evennia\evennia\utils\test_resources.py", line 64, in tearDown
    flush_cache()
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 465, in flush_cache
    cls.flush_instance_cache()
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 331, in flush_instance_cache
    cls.__dbclass__.__instance_cache__ = dict((key, obj) for key, obj in cls.__dbclass__.__instance_cache__.items()
AttributeError: type object 'Modifier' has no attribute '__dbclass__'

======================================================================
FAIL: test_modifiers_cmd (arx.world.conditions.tests.ConditionsCommandsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\arx\arx\world\conditions\tests.py", line 14, in test_modifiers_cmd
    "You have added a modifier to Char2: "
  File "c:\arx\arx\server\utils\test_utils.py", line 69, in call_cmd
    self.call(self.cmd_class(), args, msg, caller=self.caller)
  File "c:\arx\arx\server\utils\test_utils.py", line 123, in call
    raise AssertionError(retval)
AssertionError:
==============================Wanted message==================================
'You have added a modifier to Char2: Modifier on Char2 of +10 against abyssal for Any Combat checks.'
==============================Returned message================================
'Traceback (most recent call last):\n  File "c:\\arx\\arx\\server\\utils\\test_utils.py", line 104, in call\n    cmdobj.
func()\n  File "c:\\arx\\arx\\world\\conditions\\condition_commands.py", line 74, in func\n    return self.add_mod()\n
File "c:\\arx\\arx\\world\\conditions\\condition_commands.py", line 56, in add_mod\n    mod = targ.add_modifier(value, c
heck_type=check, target_tag=tag_name)\n  File "c:\\arx\\arx\\typeclasses\\mixins.py", line 542, in add_modifier\n    fro
m world.conditions.models import Modifier\n  File "c:\\arx\\arx\\world\\conditions\\models.py", line 13, in <module>\n
  class Modifier(SharedMemoryModel):\n  File "c:\\arx\\evennia\\evennia\\utils\\idmapper\\models.py", line 206, in __new
__\n    return super(SharedMemoryModelBase, cls).__new__(cls, name, bases, attrs)\n  File "c:\\arx\\Lib\\sitepackages\\d
jango\\db\\models\\base.py", line 118, in __new__\n    "INSTALLED_APPS." % (module, name)\nRuntimeError: Model class wor
ld.conditions.models.Modifier doesn\'t declare an explicit app_label and isn\'t in an application in INSTALLED_APPS.'
==============================================================================

----------------------------------------------------------------------
Ran 1 test in 0.546s

FAILED (failures=1, errors=1)
Destroying test database for alias 'default'...
```

If you have any idea why this happens just with relative imports, I'm all ears. But I'm happy enough to just use the full path names and move on with my life.

**Comment by TehomCD** [comment]
Similar to the relative import model problem, exceptions are the same way, which can be very confusing.

```
# in filea.py
from .exceptions import MyException
try:
  do_some_code()
except MyException:
  other_stuff()
```
And then, where the exception is raised...
```
# in fileb.py
from .exceptions import MyException
def do_some_code():
  raise MyException
```

The result is an uncaught exception - MyException isn't MyException, as far as the test runner is concerned.

**Comment by ramonwenger** [comment]
Answering here because I found the question via Google:

The unittest runner seems to have a problem if you have a __init__.py in the same folder as the manage.py. Removing the __init__.py resolved the error message for me.

For more information see:
https://code.djangoproject.com/ticket/22280#comment:20

**Comment by TehomCD** [comment]
I've run into this now in another work project that also has a cli that wraps` manage.py`. So this does seem to not be Evennia-specific at all, but an issue with django's test runner, or python's discovery runner, whichever. Either way, not an Evennia bug.
