### ISSUE TITLE
allcom who crashes when non-Account objects are subscribers

### ISSUE THREAD

**Issue by arumford** [evennia/evennia#1568]
#### Brief summary of issue / Description of requested feature:
When a non-Account object is a subscriber to a channel, running allcom who generates the following error:
AttributeError: '<subscriber type>' object has no attribute 'is_connected'

#### Steps to reproduce the issue / Reasons for adding feature:

1. create Object
2. add Object as a subscriber to a Channel
3. type allcom who

#### Error output / Expected result of feature
AttributeError: '<subscriber type>' object has no attribute 'is_connected'

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
In chat, Griatch thinks this might be a holdover from when Channels were Account-only.

**Comment by chainsol** [comment]
Ooh, this is relevant to me! I was planning on using the channel system for inter-object messaging, and that might get odd with this error!

**Comment by grungies1138** [comment]
I had an idea for this if it's not too much of a hassle.  Maybe there is an option that will accept a typeclass as a sort of 'end of the line' class for displaying.  I figured that someone might want to derive from Channel and possibly have those derived object listed in allcom and similar commands.  

For example, say I have a Derived Class of ICComm(Channel) and maybe something like PrivateComm(ICComm)

there could be an option for comms to allow me to enter the ICComm as the end of line.  that would allow the ICComm channel to appear but no the PrivateComm channels.

Just an idea.

**Comment by busbyra** [comment]
Can you add the is_connected attribute to the object?

**Comment by grungies1138** [comment]
I could, but that doesn't make sense for a non-Account Object.  it's just a work around.

**Comment by grungies1138** [comment]
Changed my perspective on this and see it as an asset rather than a liability now.  This can be closed unless someone else has issues.

**Comment by chainsol** [comment]
To add here - the `is_connected` property can be used to designate if an object should receive messages, regardless of if someone's actually connected to it

**Comment by Griatch** [comment]
Nevertheless, the `allcom` command should not traceback in this case so there are still things to fix here.

**Comment by ChrisLR** [comment]
I wanted to fix this but after reading the last comment I'm not sure whats expected.
The error in allcom seems to happen because of the channel wholist property.
Even if we catch the attribute error in the command the property is accessed at multiple times in the code.
Should we add the property to the base class?

**Comment by Griatch** [comment]
This is resolved in `develop`, by letting the `is_connected` property on the object check if there is a connected Account or not. Default for objects is to return `False`, meaning that if the channel should be used for some other purpose than to communicate between players, this would need to be overridden.

**Comment by Griatch** [comment]
Closed with merger of develop branch.
