### ISSUE TITLE
Item still found in character contents cache after moving

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1573]
#### Brief summary of issue / Description of requested feature:
A player today opened a bug report in which two items were still in her inventory after moving them. Inspecting I did find two that were still in her inventory and her `contents_cache._pkcache` while their `db_location` was correctly set to the new place they were moved.

#### Steps to reproduce the issue / Reasons for adding feature:

1. No idea what caused it originally. Player put the items in the contents of another item. They showed in the new place, while still showed in her inventory. Checked both her contents cache and the location of the items to see the mismatch.
2. The player retrieving the items and moving them out again did properly update her contents cache.

#### Error output / Expected result of feature
Error was the character's contents cache not being properly updated after movement.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
On master branch. I've seen this pop up once or twice before, but usually accompanied by error reports in a log of contents cache failing. No error reports here, just a stale contents cache.

My theory is that this could possibly be related to cache flushing, so may be related to #1354  - that somehow when she executed the command to move them, post-flush db_location retrieved a different character instance than her current one, and the wrong instance's contents_cache was updated: say `self.db_location` for updating the contents cache returns the new instance, while `self.caller` in command returned the old one, possibly?

**Comment by Griatch** [comment]
@TehomCD Any more occurrences of this since?

**Comment by TehomCD** [comment]
Haven't seen this happen again, though I moved away from having the cache flush at all have done more regular server reloads to avoid it.

**Comment by Griatch** [comment]
Ok, will close this for now then. Let me know if it happens again and we'll reopen.
