### ISSUE TITLE
installing for the fist time in ubuntu 16.04

### ISSUE THREAD

**Issue by gregariomansa** [evennia/evennia#1574]
#### Brief summary of issue / Description of requested feature:
When I try to install evennia, I keep receiving this error message

bashmuddev/pyenv/bin/python2: bad interpreter: Too many levels of symbolic links

I tried the suggestions in the troubleshooting section, but the error message keeps showing.

#### Steps to reproduce the issue / Reasons for adding feature:
1. For what I saw in google searches, env might be calling to itself. The recommendation is to uninstall previous instances of env, which I do not not how to do.
2.  This is the first suggestion I found
I had the same issue, and solved it simply by removing the old env file with rm -rf env. Then I created a new environment with virtualenv env, followed by installing the requirements, normally pip install -r requirements.txt, then I was able to run my app successfully.
3. A complement to this:
I can vaguely speculate that the reason for this is that you have a virtualenv pointing to itself. I can further vaguely speculate that this would happen if you attempt to create a virtualenv, but then somehow decide to do it again without running deactivate. Then you have python in the virtualenv pointing back to ... python in (effectively) the same virtualenv by a symbolic link.

Since this is speculative, I hope someone who actually has this problem can confirm or deny that this is what happened.

Anyway, if this is the case, the other answers here saying remove the env and start over are basically correct, but remember to deactivate first.

Again, I do not know how to deactivate.

Another question is from where should I do the installation. I am doing it with this prompt:
julio@julio-Aspire-A515-51G:~$

Maybe I should be doing it in the muddev directory?

Sorry for this very bad explanation. I am brand new to linux.

**Comment by Griatch** [comment]
You can usually know if you are in a virtualenv already by the text `(pyenv)` by the side of your prompt (or `env` or whatever you chose to name your virtualenv). To deactivate a virtualenv you simply write `deactivate`. The `(pyenv)` prompt will then go away. You could also simply close and start a new terminal and then activate the virtualenv fresh. 

Haven't seen the particular error before and I haven't tested what happens if you try to start a new virtualenv when already inside a previous virtualenv, so that *might* be the issue; will try it out when I have the time.

**Comment by gregariomansa** [comment]
Thank you for your reply.

I can tell you I am making good progress. With the aid of the video https://www.youtube.com/watch?v=tjiS2Bx5xb0&feature=youtu.be I have evennia running. But, as you might expect, I ran into trouble. After creating the superuser, 78 static files copied ok, and then Starting evennia server is what's not working. Looks like something called zope is required, and is not there. I copy the messages now.

78 static files copied to '/home/julio/jvevennia/eljuegoquesea/web/static', 1 unmodified.

Starting Evennia Server (output to stdout).

Starting Evennia Portal in Daemon mode (output to portal logfile).
Traceback (most recent call last):
  File "/home/julio/jvevennia/evennia/evennia/server/evennia_runner.py", line 357, in <module>
    main()
  File "/home/julio/jvevennia/evennia/evennia/server/evennia_runner.py", line 353, in main
    start_services(server_argv, portal_argv, doexit=args.doexit)
  File "/home/julio/jvevennia/evennia/evennia/server/evennia_runner.py", line 198, in start_services
    from twisted.internet.error import ReactorNotRunning
  File "/home/julio/jvevennia/jvevennia/local/lib/python2.7/site-packages/twisted/__init__.py", line 55, in <module>
    _checkRequirements()
  File "/home/julio/jvevennia/jvevennia/local/lib/python2.7/site-packages/twisted/__init__.py", line 39, in _checkRequirements
    raise ImportError(required + ": no module named zope.interface.")
ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.

    STOP: Caught keyboard interrupt while in interactive mode.
    
Traceback (most recent call last):
  File "/home/julio/jvevennia/jvevennia/bin/twistd", line 17, in <module>
    from twisted.scripts.twistd import run
  File "/home/julio/jvevennia/jvevennia/local/lib/python2.7/site-packages/twisted/__init__.py", line 55, in <module>
    _checkRequirements()
  File "/home/julio/jvevennia/jvevennia/local/lib/python2.7/site-packages/twisted/__init__.py", line 39, in _checkRequirements
    raise ImportError(required + ": no module named zope.interface.")
ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.
Traceback (most recent call last):
  File "/home/julio/jvevennia/jvevennia/bin/twistd", line 17, in <module>
    from twisted.scripts.twistd import run
  File "/home/julio/jvevennia/jvevennia/local/lib/python2.7/site-packages/twisted/__init__.py", line 55, in <module>
    _checkRequirements()
  File "/home/julio/jvevennia/jvevennia/local/lib/python2.7/site-packages/twisted/__init__.py", line 39, in _checkRequirements
    raise ImportError(required + ": no module named zope.interface.")
ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.

Any suggestions will be greatly appreciated. Thanks for your patience.

**Comment by Griatch** [comment]
Hi again. This is an issue with zope on Ubuntu. If you scroll down on the Evennia GettingStarted page, you will find a section called [Linux Troubleshooting](https://github.com/evennia/evennia/wiki/Getting-Started#linux-troubleshooting). The third point there exactly describes why this error occurs and how to fix it. Follow the instructions and you should be fine. :) 

I'm closing this issue now.
