### ISSUE TITLE
Request:  Alias support for @detail

### ISSUE THREAD

**Issue by spellsmith** [evennia/evennia#1577]
#### Brief summary of issue / Description of requested feature:

Modify the @detail command to support aliases in the form of:   @detail name;alias;alias2;alias3 = 'Descriptive text'

If the command itself cannot support aliases due to the 'name' not being an actual database object, perhaps this could be parsed as split commands, e.g.  @detail name;alias;alias2 = 'Desc' is parsed as three separate commands:

@detail name = 'Desc'
@detail alias = 'Desc'
@detail alias2 = 'Desc'

#### Steps to reproduce the issue / Reasons for adding feature:

Allows @detail to follow the (otherwise universal?) command syntax of supporting aliases for objects/descriptions/exits.  Also, build.ev in the tutorial_world suggests that this syntax is already supported (see build.ev line 220 for an example).

#### Error output / Expected result of feature

N/A

**Comment by Griatch** [comment]
Somewhat confusingly, the tutorial world uses its own room-type along with its own custom `@detail`. This was originally to avoid depending on contribs. *This* version of the `@detail` command does support alliases. It makes sense to add this also to the contrib's version.

**Comment by Griatch** [comment]
@spellsmith Btw, a hint when writing github entries is to always hide `@`-style command names in code tags (backticks). The reason is that otherwise github interprets it as you trying to call a github user that happens to be named "detail". We have gotten some confused questions from users in the past on this.

**Comment by Griatch** [comment]
This was implemented in develop branch as of PR #1577. Closing this.
