### ISSUE TITLE
Request: Add file paths to wiki pages

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1578]
It would help me (and probably a couple of others) if there is a way to show the file path where a particular thing exists.  Maybe up under the 'last edited' line we could have a line like:
`evennia/locks/lockhandler.py`

This would help in development to quickly refer to where a resource is located.

**Comment by BlauFeuer** [comment]
Github's web code search is sometimes useful, but quicker and more flexible is git's grep.

For example, if you are looking for where the lockhandler is defined, 
`git grep 'class LockHandler' --`
answers with
`evennia/locks/lockhandler.py:class LockHandler(object):`

Or maybe I've misunderstood your need.  Can you give a more specific example, citing an actual page and what information that you deem helpful is missing?  I can probably work on this in my spare time.

**Comment by strikaco** [comment]
Is this related/duplicate of #1431?

**Comment by Griatch** [comment]
This looks like it's not a duplicate of #1431, since that other one deals with the API pages (which could be automated) whereas this one is for general wiki pages covering a particular entry or concept, I believe. 

This one requires a lot more work overall :)

**Comment by Griatch** [comment]
I'm  closing this issue and instead copying the suggestion [into the documenation update planning document](https://github.com/evennia/evennia/wiki/Docs-refactoring).
