### ISSUE TITLE
Typo/doc error in RPSystem contrib

### ISSUE THREAD

**Issue by spellsmith** [evennia/evennia#1583]
Typo/documentation error in 'mask' command in RPSystem contrib.

1)  Typing 'mask' without arguments results in the message "Usage: (un)wearmask sdesc" instead of expected "Usage: (un)mask desc".   Verified 'wearmask' and 'unwearmask' are not valid aliases.

2)  When unmasking, the caller.msg is "You remove your mask and is again '%s'." % old_sdesc".   The "is" should be replaced with "are" for grammatical correctness  ("You remove your mask and are again....")

**Comment by ChrisLR** [comment]
I think this issue should be closed
