### ISSUE TITLE
Can't disconnect in dark room of tutorial

### ISSUE THREAD

**Issue by MrDowntempo** [evennia/evennia#1584]
#### Brief summary of issue / Description of requested feature:

You can't use the quit command when you're in the dark cell of the tutorial

#### Steps to reproduce the issue / Reasons for adding feature:

1. Fall off bridge and find yourself in the room with the vine puzzle
2. Don't light the splinter
3. Try to disconnect, doesn't work.

#### Error output / Expected result of feature

Disconnect should exit you from the game even in a darkened room.

**Comment by Griatch** [comment]
This is deliberately done this way. But I can see the argument of not blocking the quit as a general principle.
