### ISSUE TITLE
evennia.evennia.utils.evmore won't formfeed

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1585]
In using the docstrings as help files, evmore should respect either \f or \x0c (preferably both for utility) to allow formfeeds to be forced on the more pager so that output can be controlled in owner manageable chunks instead of where-ever the parser finds the limit of lines to add.  It currently doesn't.

Server: Evennia 0.7.0 (rev 5aaa0fcf)
OS: Linux Mint 18

**Comment by Griatch** [comment]
The evmore utility currently bases the formfeed on the number of rows of the client window, assuming the client reports such. The drawback of using an explicit formfeed is that different users may have different window sizes and number-of rows per page. A too-short page length when the entire page could have fit on the screen can be perceived as annoying, so this would need to be handled if this were to be added.

**Comment by Griatch** [comment]
Implemented in `develop` branch.
