### ISSUE TITLE
Wiki issue: Object to object communications documentation

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1588]
https://github.com/evennia/evennia/wiki/Object-to-Object-Communications

It would help to see a few examples of object to object communications when dealing with channels.

**Comment by chainsol** [comment]
This would be pretty nice, however I don't know of anyone doing object-to-object communications yet! I'd be interested in this.

**Comment by Griatch** [comment]
@grungies1138 need to either actually *write* that tutorial or remove the page I think. I don't know exactly what is requested here - communication between objects is like communication between Accounts, the Channels should handle both transparently.

**Comment by chainsol** [comment]
@Griatch Vincent and I had worked on a system of object-to-object messaging for event notifications - for instance, a gunshot going off might notify NPCs in the area. Maybe that's the style of thing @grungies1138 was going for?

**Comment by arumford** [comment]
Yes, I know. I wanted to finish working out the bugs of my system and any gotchas along the way.  But I got sidelined with RL. :)

**Comment by BlauFeuer** [comment]
I know it says "Coming Soon....", but I'm curious if this is to use channels (in which case it's objects subscribed to a channel, and not object to object specifically), or msg objects with send/receive set to the sender and receiver object.  Or is this something else entirely e.g. something like the page command?

**Comment by taladan** [comment]
I would like to be able to see working examples of inter-channel communication whereby one channel can send/alert/notify another channel object and maybe have those messages routed correctly.  I can imagine that something like that might be useful, but right now I have no implementation in mind.

**Comment by Griatch** [comment]
I have deleted the empty page, rather than have people speculate on what it *might* contain it's better if people write specific request issues for documentation they would like to see, concerning this or something else. Still not sure what the original plan for that wiki page was.
