### ISSUE TITLE
SSL_ENABLED prevents the portal from loading

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1591]
#### Brief summary of issue / Description of requested feature:

When `SSL_ENABLED` is set to `True` but the machine doesn't have the requirements (as the proper packages on Windows), the portal just doesn't work.  It might be preferable to launch the portal on non-secure telnet and log the error.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a new Evennia game.
2. Set `SSL_ENABLED` to `True` in the settings.
3. Start Evennia.  If you are not properly set for SSL, the portal won't work at all.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia develop (and probably master).

**Comment by Griatch** [comment]
While this is deliberate, I suppose there is some merit to still allowing the portal to start despite not fullfilling all import dependencies. At least until someone tries to use SSL and then may get a far harder-to-debug error, maybe.

**Comment by Griatch** [comment]
The error handling when missing the needed security library imports should change to log the error instead of stopping the server upstart.

**Comment by Griatch** [comment]
@strikaco That's the same functionality we have right now then ... it makes little sense to have a whole new setting in order to ignore the setting; in that case the setting should not have been activated instead.

**Comment by Griatch** [comment]
Hm. I think it's better to leave the current behavior then. I don't think it makes sense to activate SSL only to immediately say it's ok if it's not activated. 
Closing.
