### ISSUE TITLE
Message is not spelled 'messsage' 

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1595]
https://github.com/evennia/evennia/blob/b3e97b5c3d8f094bc4853b51423460b33d89da98/evennia/comms/models.py#L110

Not sure how this mis-spelling impacts the code yet, still digging through it.

**Comment by Griatch** [comment]
This will only change the `verbose_name` of the field, so it will display mis-spelled in the admin. So it should be fixed but it should have no impact on code functionality.
