### ISSUE TITLE
Feature Request: Update to higher version of pillow

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1598]
#### Brief summary of issue / Description of requested feature:

As pointed out by one of our users, the currently used version of `pillow` has some security issues and should be updated. 

We should update to at least 3.3.2 but a quick test shows upgrade within the current environment is not working effortlessly, with errors in a missing `jpeg` package etc.; will need to look into reasons for that some more.

**Comment by MichaelDays** [comment]
Identified using "pipenv check" for anyone wondering.

**Comment by Griatch** [comment]
Resolved with Evennia 0.8 release.
