### ISSUE TITLE
Python basic tutorial part two - "type" command output not as described from the webclient.

### ISSUE THREAD

**Issue by MichaelDays** [evennia/evennia#1605]
#### Brief summary of issue / Description of requested feature:
When working through Python basic tutorial part two, I noticed the `type` commands do not output expected feedback when invoked from the webclient.

https://github.com/evennia/evennia/wiki/Python-basic-tutorial-part-two

#### Steps to reproduce the issue / Reasons for adding feature:

1. Sign on to web portal as admin account, select "Play Online" 
2. `@py type(me)`

#### Error output / Expected result of feature
`>>> type(me)`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

If connected via tinyfugue, output is displayed as described in the tutorial.

```
>>> type(me)
<class 'typeclasses.characters.Character'>
```

**Comment by Griatch** [comment]
This is because of the webclient swallowing the `< >` when sending via the @py command. I could have sworn there was an issue open for verbatim handling of HTML tags in the client, but now I can't find it.

**Comment by Griatch** [comment]
A note about this was added to the tutotial for the time being.

**Comment by TehomCD** [comment]
I think it was the issue about Mudlet, #1058 where this popped up most often.

**Comment by Griatch** [comment]
This has now been resolved on `develop` branch with the closing of the 'raw html' issue.

**Comment by Griatch** [comment]
Closed with merger of develop branch.
