### ISSUE TITLE
Wiki Example issue - Evennia Async Process

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1608]
#### Brief summary of issue / Description of requested feature:
In the process pool section of the document it gives the following example to be run inside the game:

`@py from src.utils.utils import run_async;run_async("_return(1+2)",at_return=self.msg)`

However when I run that command I get the following in return:

```
>>> from evennia.utils.utils import run_async;run_async("_return(1+2)",at_return=self.msg)
File "/home/swift/muddev/evennia/evennia/utils/utils.py", line 1062, in run_async raise RuntimeError("'%s' could not be handled by run_async" % to_execute) RuntimeError: '_return(1+2)' could not be handled by run_async
```
### Evennia version info:
Evennia 0.7.0 (rev b3e97b5c)
MU* development system

Licence https://opensource.org/licenses/BSD-3-Clause
Web http://www.evennia.com
Irc #evennia on irc.freenode.net:6667
Forum http://www.evennia.com/discussions
Maintainer (2010-)   Griatch (griatch AT gmail DOT com)
Maintainer (2006-10) Greg Taylor

OS posix
Python 2.7.14
Twisted 16.0.0
 Django 1.11.10

**Comment by Griatch** [comment]
At the top of the process-pool section is the following text: 

> Note: The Process pool is currently not available nor supported, so the following section should be ignored. An old and incompatible version of the procpool can be found in the evennia/procpool repository if you are interested.

So this section is not supported at this time and the code is expected to give errors.

**Comment by taladan** [comment]
thanks for the clarification.  My fault entirely for skimming for the parts I needed instead of braindumping the whole docstring.
