### ISSUE TITLE
Feature Request - Server-centric contribs vs. in-game system contribs

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1612]
#### Description of requested feature:
In perusing the Contribs folder, I can see a growing need for a further delineation of contributions into separate directories indicating whether they are snapins designed to implement something on the backend for server administrators or on the front end for game staff/players. 

#### Reasons for adding feature:

1.  Better organization of the directory tree leads to easier parsing and automation within scripts
2. Reduces eye-time looking for server-only scripts vs. the kitchen sink
3. Flat may be better than nested, but Explicit is better than implicit

**Comment by Griatch** [comment]
I'm open to further suggestions on how to organize the contribs better. Since reorganizing will break imports, we better change to something that is pretty future-proof.

**Comment by Griatch** [comment]
I opened a discussion on this topic here: https://github.com/evennia/evennia/discussions/2585

**Comment by Griatch** [comment]
The contrib folder has been restructured (in develop branch) as per #2585, including a new, auto-generated documentation of each contrib. Closing.
