### ISSUE TITLE
implement @ofail equivalent

### ISSUE THREAD

**Issue by drandre2014** [evennia/evennia#1617]
In Fuzzball MUCK, there is this command, @ofail, I believe, that allows you to set a message that will be outputted to everybody except you when you try to use a lock that fails. You implement the @fail command by err_traverse attribute already in def at_failed_traverse.

**Comment by Griatch** [comment]
If the original is for 'locks' in the sense of traversing doors, this sounds rather limited compared to the vast uses of locks in Evennia. I suppose one could add some more generic solution for returning error messages when locks fail though.

**Comment by Griatch** [comment]
Implementing this would be quite game-specific; considering the amount of locks supported. So better to leave this up to the developer.
