### ISSUE TITLE
Recursive Containment

### ISSUE THREAD

**Issue by drandre2014** [evennia/evennia#1618]
For the inside lock function, it appears as if it doesn't check for recursive containment (i.e. an object inside of an object). That might be useful to implement.

**Comment by Griatch** [comment]
One may not actually want the recursive check though; for example you may only pass the lock if you are in the actual Room location but not if you are inside the giant-robot object that happens to be in said room.

**Comment by chainsol** [comment]
```
@create/drop a box
@tel self=a box
@dig some room
@tel a box=self
```
Or similar.

**Comment by strikaco** [comment]
As implemented, the `inside()` lock is a tautology without the recursive search though.

Ex: 
* Create a generic "TARDIS" object to serve as a container another object can enter or exit ad-hoc. 
* Define a command `CmdEnter` that performs the object move but is locked with a `cmd:not inside()`.
* Add this command to the TARDIS cmdset (we don't need it globally).

The lockcheck for `inside` will presume the accessing object is the **cmdset** on TARDIS, not the invoker of the command, and IIRC always resolves to `False` (`True` in the example here).

**Comment by Griatch** [comment]
@strikaco: I presume you didn't actually test your example? It works fine, because what you describe is not how command lock-checks, nor the `inside()` lock function works.

As the cmdsets are collected by the cmdhandler, access will be checked on them When determining which commands to use from the available cmdsets, the cmdhandler will run a "cmd" - access check against all locks on the command, passing `caller` into the check (this is what determines which commands are actually going to be available in the cmdset merge). 
So the accessing object will be the caller that is responsible for merging all those cmdsets, and the `inside()` lock will check so that the caller's location is equal to the object we are accessing (TARDIS in this case). 

I just took TARDIS out for a spin. Entering it works just fine.

**Comment by Griatch** [comment]
In the end I added a new `inside_rec` lockfunc. It will check down to a depth of 10 recursions to determine if something is nested "inside" the accessed object.

**Comment by strikaco** [comment]
@Griatch Still having some trouble with this one.

> I presume you didn't actually test your example? It works fine

I did test the example. It works fine _if you are a superuser_. It breaks when you are quelled. 

`Enter` will always work (incorrectly)--you can recursively enter the same object--and `Exit` is never added to the usable cmdset:

```
class CmdEnter(Command):
    
    key = 'enter'
    locks = 'cmd:not inside()'
    
    def func(self):
        self.msg("You enter.")
        self.caller.move_to(self.obj)
    
class CmdExit(Command):
    
    key = 'exit'
    locks = 'cmd:inside()'
    
    def func(self):
        self.msg("You leave.")
        self.caller.move_to(self.obj.location)

class ContainerCmdSet(CmdSet):
    
    key = "Container"

    def at_cmdset_creation(self):
        self.add(CmdEnter())
        self.add(CmdExit())

class Container(Object):
    
    def at_object_creation(self):
        super().at_object_creation()
        self.cmdset.add(ContainerCmdSet(), permanent=True)
```

Errors are raised in the log concerning the absence of a srcobj when the commands are invoked. Superusers simply bypass this and the lock-checking altogether.

```
20-10-06 23:27:08 [EE] objects.container#581: 'NoneType' object has no attribute 'access'
20-10-06 23:27:10 [EE] objects.room#108: 'NoneType' object has no attribute 'access'
```

Before I switched over to manual lock-checking altogether, I had reimplemented the `inside` lockfunc as a workaround:

```
def inside(accessing_obj, accessed_obj, *args, **kwargs):
    """
    Usage:
       inside()
    Only true if accessing_obj is "inside" accessed_obj
    """
    if inherits_from(accessed_obj, 'evennia.commands.command.Command'):
        accessed_obj = getattr(accessed_obj, 'obj', accessed_obj)
            
    return accessing_obj.location == accessed_obj
```

...but that is a pain and I'd really like to go back to using `cmd` locks. 

`Enter` should only be made callable to objects _in the same location as_ the container. `Exit` should only be made callable to objects _inside_ the container. This seems like it should be straightforward to implement using locks; what am I doing wrong?

**Comment by strikaco** [comment]
Just noticed that even the `tag` lockfunc had to implement a similar workaround to address the appropriate object:

https://github.com/evennia/evennia/blob/367db031fa9e5727c3fbf90e624ab06bd9b6f82f/evennia/locks/lockfuncs.py#L523-L527

**Comment by Griatch** [comment]
Ok, opening this again then.

**Comment by strikaco** [comment]
@Griatch I've opened a new ticket to address the deviation in scope. This one can be closed.
