### ISSUE TITLE
SaverList __add__ changes SaverList in place

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1624]
#### Brief summary of issue / Description of requested feature:
So the expected behavior for adding two lists together with the `+` operator is to add the two lists together and to return the new list. But if one of the lists is a list in an Attribute, the original list gets the result of the operation - it becomes an in-place add.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@py self.db.my_list_test = []`
2. `@py 5 in self.db.my_list_test + [5]`
3. `@py self.db.my_list_test`

#### Error output / Expected result of feature
`seldf.db.my_list_test` now contains the result of adding the lists together. I discovered this through something similar - adding a number of lists together in order to do an `in` check, and the first attribute acquired the result of adding them together.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Master branch

**Comment by Griatch** [comment]
Good catch! I'll try to look at the PR this weekend.
