### ISSUE TITLE
Feature Request: disable Channel-names-as-commands

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#1625]
#### Brief summary of issue / Description of requested feature:
If you create a channel named 'Public', then anyone who types 'Public blah' sends to the channel.

This is not what I want.

Can we get a Setting in settings_default for disabling this? Might also go along with an option to specify a custom ChannelHandler object?

#### Steps to reproduce the issue / Reasons for adding feature:

1. Basically I don't want this due to clashing commands and other confusion.
2. I want channels to be available exclusively through adding an 'addcom' alias!
3. Customization is good!

**Comment by Griatch** [comment]
Implemented in `develop` branch as part of the channel-refactor. While a `public <msg>` will still be automatically created, a user can themselves remove their ability to use this, and by changing the channel class one can remove such aliases being generated completely.
