### ISSUE TITLE
Connection lost when exceeding `amp.MAX_VALUE_LENGTH` sends

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1636]
#### Brief summary of issue / Description of requested feature:

When sending a data packet that on its own is larger than the `amp.MAX_VALUE_LENGTH` constant (65535), the AMP data connection is lost. On some implementations the puppeting is lost by this, leading to OOC accounts (the Portal connection is not lost). 

#### Steps to reproduce the issue / Reasons for adding feature:

This is tested with the webclient. 

1. Introduce a test command that sends random data packets (to avoid gzip optimization) and add to the default cmdset: 

```python
class CmdSendBig(BaseCommand):
    """
    Usage:
        sendbigdata <N>

    Send random block of N chars to portal. <N> is given in thousands of characters.

    """
    key = "sendbigdata"

    def func(self):

        if not self.args:
            self.caller.msg("Usage: sendbigdata <N>")
            return

        try:
            N = int(self.args)
        except ValueError:
            self.caller.msg("{} must be an integer.".format(self.args))
            return
        N *= 1000
        bigdata = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N))
        self.caller.msg("Sending random string data of size {} chars to client ...".format(N))
        self.caller.msg(testdata=(bigdata, {}))
        self.caller.msg("... sent.")
```
2. Add a receiver of the `testdata` message type in the webclient's `webclient_gui.js` and collect the static files to make sure it's active:

```javascript
function onTestData(args, kwargs) {
     var mwin = $("#messagewindow");
     mwin.append(
         "<div class='msg err'>"
         + "Received data block."
         +"</div>");
     mwin.scrollTop(mwin[0].scrollHeight);
}

[...]

 Evennia.emitter.on("testdata", onTestData);
```
3. Restart server/portal and call `sendbigdata 65` (works) and then `sendbigdata 66`, which triggers the error.

#### Error output / Expected result of feature

Exceeding `amp.MAX_VALUE_LENGTH` causes the AMP connection to drop and confuses the server/portal to think characters are disconnecting when they are not. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

The `amp.MAX_VALUE_LENGTH` limit of AMP is well known and we have a custom amp protocol implementation which intends to handle it by splitting the message into smaller chunks and send those in sequence. Clearly something is going wrong with this automatic splitting.

**Comment by friarzen** [comment]
Fix confirmed for my use case.  Thanks!
