### ISSUE TITLE
Feature Request: Add support for Gossip/Grapewine chat network

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1646]
#### Brief summary of issue / Description of requested feature:

[Gossip](https://gossip.haus/) is a new inter-MUD chat network using websockets and JSON packets for communication through a centrally hosted server. 

#### Reasons for adding feature:

It's good to support initiatives like this, and Evennia already uses websockets for the webclient anyway.

#### Expected result of feature

A new `gossip` prototocol in `evennia/server/portal/`. It's probably not needed to work in the same way as the IRCbot (there is no bot to launch onto the gossip network), but on the Evennia server side one could probably still represent the connection through a Bot class so it's easy to relay data back to the respective Evennia channels. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is for development branch; and definitely open for those wanting to help out.

**Comment by whutch** [comment]
I've been tinkering with this for a couple days and the biggest hurdle so far seems to be that txWS does not support websockets in client mode. It only handles header parsing from the server perspective, it does not support masking outgoing frames, etc. So either drastic changes would need to be made to the included txWS library or we would need a new dependency for Twisted-friendly websockets that support being opened in client mode.

**Comment by Griatch** [comment]
@whutch We have not used txWS since more than a year; it's not even part of the distribution anymore, so where are you finding the "included txWS library) now? (but I realize it's not in the 0.8 changelog, should add that!). 
We are using [autobahn](https://autobahn.readthedocs.io/en/latest/) for our websocket needs these days.

**Comment by oestrich** [comment]
While I can't help directly with this effort, if anyone has questions about Gossip's protocol I am more than happy to answer them (and maybe update the documentation so it's clear!). Looking forward to seeing this in Evennia!

**Comment by whutch** [comment]
@Griatch the txWS library is currently included at https://github.com/evennia/evennia/blob/develop/evennia/utils/txws.py. It's factory gets imported at https://github.com/evennia/evennia/blob/develop/evennia/server/portal/portal.py#L328. I don't see autobahn referenced anywhere in the master or develop branches, though its inclusion would certainly make this easier.

**Comment by Griatch** [comment]
@whutch You are right - I'm looking at the wrong branch. The Autobahn library was added in the `develop-py3` branch last year, which is what I was looking at - txWS does not work well with py3 either as it turned out (it's an old library from the time before the websocket specification was even stable). 

We are not quite at the point where we can merge `develop-py3` into `develop`, but one solution may be to backport the autobahn dependency before that of course.

**Comment by Griatch** [comment]
@whutch Note: The develop-py3 branch has now merged into `develop` branch and the Autobahn library should now be the library we use for websockets.

**Comment by Griatch** [comment]
This was already implemented in Evennia 0.9, just forgot to close this.
