### ISSUE TITLE
Webclient browser useragent string identification

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1650]
#### Brief summary of issue / Description of requested feature:

It would be useful to have some identification of the client being used to access the server.

#### Steps to reproduce the issue / Reasons for adding feature:

I'm finally getting back to #1535 with some new insights and this would be a useful data point. Currently we can categorize traffic by protocol ('telnet', 'telnet/ssl', 'ssh', 'webclient/websocket' or 'webclient/ajax'), but having some equivalent of a useragent string would be useful for correlating activities back to specific users or debugging client-specific issues ("why does this issue only affect these users? hmm, they're all using client x.").

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Fingerprinting has its shortcomings, but this site has some tips:

http://mud-dev.wikidot.com/article:telnet-client-identification

**Comment by chainsol** [comment]
Hmmmmmmmmm. OK, I could see that you could store the terminal type response, but I can't see the usefulness of implementing any sort of sniffing. Especially as there are only 4 there.

**Comment by strikaco** [comment]
Debugging client-specific issues and narrowing the scope of whack-a-mole bannings (someone cycling IPs is unlikely to cycle clients) . The idea should not be limited to just those 4 Telnet clients; if we can grab the browser useragent from webclient users, the scope drastically expands. I don't think ssh has a clear fingerprinting method.

(While the browser useragent could also be grabbed via reverse proxy, now you have two disparate log sources to correlate versus just having that artifact available within the session).

**Comment by Griatch** [comment]
Added as part of the webclient `CLIENTNAME` protocol flag, such as `Evennia webclient (websocket:firefox)`.
