### ISSUE TITLE
error in scripts with repeats = 1

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1663]
#### Brief summary of issue / Description of requested feature:
When creating custom scripts I cannot set repeats = 1 or it crashes.

#### Steps to reproduce the issue / Reasons for adding feature:

1. create script below
```
class TestScript(DefaultScript):
    def at_script_creation(self):
        self.key = 'testing_script'
        self.interval = 10
        self.repeats = 1
        self.persistent = False
```

2. apply in game either through create_script or @scripts command

#### Error output / Expected result of feature
```
Traceback (most recent call last):
  File "f:\repositories\evennia\evennia\commands\cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File "f:\repositories\evennia\evennia\commands\default\building.py", line 2504, in func
    ok = obj.scripts.add(self.rhs, autostart=True)
  File "f:\repositories\evennia\evennia\scripts\scripthandler.py", line 78, in add
    autostart=autostart)
  File "f:\repositories\evennia\evennia\utils\create.py", line 217, in create_script
    new_script.save()
  File "f:\repositories\evennia\evennia\utils\idmapper\models.py", line 413, in save
    _MONITOR_HANDLER.at_update(self, fieldname)
  File "f:\repositories\evennia\evennia\scripts\monitorhandler.py", line 99, in at_update
    if obj in self.monitors and fieldname in self.monitors[obj]:
  File "f:\repositories\pyenv\Lib\site-packages\django\db\models\base.py", line 615, in __hash__
    raise TypeError("Model instances without primary key value are unhashable")
TypeError: Model instances without primary key value are unhashable
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Happens when game is hosted on Windows and LInux. Same error happened when I tried to manually stop the script using at_repeat when repeats was greater than 1. Doesn't happen if start_delay is used in at_script_creation.

**Comment by Henddher** [comment]
Is this as simple as it sounds?

The stacktrace looks tricky but the description seems straight forward.

**Comment by Henddher** [comment]
I'm about to place a simple test in `evennia/utils/test_resources.py` as it seems like the closest place to test `create_script` function. 

I don't think that's the wrong place but I can't find where `evennia.utils.create_script` function has its tests ... I'll be happy to move it to the correct location afterwards.

**Comment by kaleara** [comment]
I'm essentially using it as a short term buff for the duration of the script, with messaging when it starts and ends. If there's a better way to do this, I couldn't find it.

**Comment by kaleara** [comment]
Sorry, I wasn't clear - it doesn't just do messaging, so a delay won't work. The debuff would also decrease defensive rolls in combat, show up in an effects list, as well as some other things.

Although it's clear to me now, when I was first creating this, my assumption was that with 1 repeat and an interval of 10, the script would last for 10 seconds (it would trigger, then repeat once 10 seconds later). I think it could be clearer in the wiki documentation.
