### ISSUE TITLE
Auto-convert old, lenient prototype format to new, strict format

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1675]
#### Brief summary of issue / Description of requested feature:

With Evennia 0.8, the [prototype format](https://github.com/evennia/evennia/wiki/Spawner#the-prototype) has become stricter compared to the one in 0.7.0. For example, passing tags require that the tag be represented as a tuple `(tagname, category, data)` so as to allow to fully present it when batch-creating.  Same is true e.g. for Attributes. 

For those entering prototypes manually to the spawner it would be good to convert them to the stricter format for convenience. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Try spawn using the old, looser format.  

#### Error output / Expected result of feature

Entering the old loose-format prototype to the spawner should work since it would be converted to the stricter format automatically. For example, entering a list of `tags` as `["tagname", "tagname2"]` would be translated to `[("tagname", None, None), ("tagname2", None, None)]`. Also, single-entry Attributes would be converted in the same way by moving them into the `attrs` prototype property. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Question remains just how flexible this auto-conversion should be. It can quickly be rather complex to catch all possibilites.

**Comment by Henddher** [comment]
See https://github.com/evennia/evennia/pull/1653#issuecomment-427592279

See https://github.com/evennia/evennia/pull/1653#issuecomment-427595771

**Comment by Griatch** [comment]
@Henddher I implemented this feature now. Will look at your tag issues.

**Comment by Henddher** [comment]
> @Henddher I implemented this feature now. Will look at your tag issues.

Nice!
... but I can't find the corresponding PR ... was this committed to master branch or another branch?
