### ISSUE TITLE
AMP Error for MsgPortal2Server

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1679]
#### Brief summary of issue / Description of requested feature:
Occasionally get the following message:
AMP Error for MsgPortal2Server: ("UNHANDLED, u"Unhandled Command: 'MsgPortal2Server'"

#### Steps to reproduce the issue / Reasons for adding feature:

1. Seems to be after reloading, when the reload takes a very long time

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I know I've seen it on my Windosw server, not sure about the Linux one. Will update if I keep seeing it.

**Comment by Griatch** [comment]
This is *probably* benign and related to timing - maybe because the connection has time to goes away before a closing message is sent. More examination needed to pin it down, it's pretty annoying.

**Comment by kaleara** [comment]
Reload seems to be stuck and have gotten this message twice (some time between messages). I just reloaded a few minutes ago without any trouble.

**Comment by kaleara** [comment]
Twice today my reload has stopped after the server stopped. Both times I got multiple AMP Error messages (with time between them). When I would go to use evennia stop or evennia reload in the cmd, I would get a traceback. Both times were from a prototype module that was missing a comma. Hopefully the specifics help.

**Comment by Griatch** [comment]
@kaleara Since there has been no further updates on this, I'm closing the ticket for now. If the problem remains and/or there is more info on reproducing it, let me know and I'll reopen.
