### ISSUE TITLE
Spawn - not all switches work

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1684]
#### Brief summary of issue / Description of requested feature:
Edit and examine are listed as switches of spawn in the command's help but don't function.

#### Steps to reproduce the issue / Reasons for adding feature:

1. help spawn (examine and edit) are listed as switches
2. spawn/edit returns "spawn: Extra switch "/edit" ignored" and gives usage message
3. same for spawn/examine

**Comment by Henddher** [comment]
Can I tackle this one too?

🎣  **Hacktoberfest**

**Comment by Henddher** [comment]
@Griatch, after merging #1699. This can be closed right?

**Comment by Griatch** [comment]
@Henddher Correct, thanks for reminding me.
