### ISSUE TITLE
Feature Request: Cursor at end of line when using up arrow key in webclient

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1686]
#### Brief summary of issue / Description of requested feature:
Currently when using the up arrow key, your cursor goes to the beginning of the line. It should probably be at the end.

#### Steps to reproduce the issue / Reasons for adding feature:
I realize it's minor, but I think most of the reasons to change a command that you used the up arrow to get to are at the tail of the command and it makes the most sense for it to be there. I seem to recall that most clients work this way.

**Comment by Griatch** [comment]
Yeah, this makes sense. I seem to recall the cursor indeed used to go at the end, so this may be a regression.
