### ISSUE TITLE
PIP Update on Mac before using it to install Evennia

### ISSUE THREAD

**Issue by thenomain** [evennia/evennia#1703]
#### Brief summary of issue / Description of requested feature:

https://github.com/evennia/evennia/wiki/Getting-Started#mac-install

Right now pip on the Mac, if installed via Homebrew, needs to be upgraded before it will properly install Pillow. I strongly recommend running:
`pip install --upgrade pip`

Before:
`pip install -e evennia`

#### Mind You...

This is pretty obvious if you run it on an older pip, as pip will ask you to update it after all the errors.

**Comment by Griatch** [comment]
Added to the mac instructions, thanks.
