### ISSUE TITLE
`@spawn` traceback within evennia.prototypes.prototypes.protfunc_parser

### ISSUE THREAD

**Issue by Henddher** [evennia/evennia#1704]
#### Brief summary of issue / Description of requested feature:

Based on https://github.com/evennia/evennia/wiki/evennia.prototypes.protfuncs, it seems like all `protofunc`s are preceeded by `$` character. However, prototype values without preceding `$` are getting treated as `$protofunc`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@spawn {'key':'stone(#1234)'}`

#### Error output / Expected result of feature

```
18-10-24 01:46:49 [::] Traceback (most recent call last):
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/commands/cmdhandler.py", line 594, in _run_command
18-10-24 01:46:49 [::]     _progressive_cmd_run(cmd, ret)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/commands/cmdhandler.py", line 193, in _progressive_cmd_run
18-10-24 01:46:49 [::]     value = generator.next()
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/commands/default/building.py", line 3098, in func
18-10-24 01:46:49 [::]     for obj in spawner.spawn(prototype):
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/prototypes/spawner.py", line 694, in spawn
18-10-24 01:46:49 [::]     create_kwargs["db_key"] = init_spawn_value(val, str)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/prototypes/prototypes.py", line 735, in init_spawn_value
18-10-24 01:46:49 [::]     value = protfunc_parser(value)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/prototypes/prototypes.py", line 583, in protfunc_parser
18-10-24 01:46:49 [::]     stacktrace=stacktrace, testing=testing, **kwargs)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/utils/inlinefuncs.py", line 425, in parse_inlinefunc
18-10-24 01:46:49 [::]     retval = "".join(_run_stack(item) for item in stack)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/utils/inlinefuncs.py", line 425, in <genexpr>
18-10-24 01:46:49 [::]     retval = "".join(_run_stack(item) for item in stack)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/utils/inlinefuncs.py", line 423, in _run_stack
18-10-24 01:46:49 [::]     retval = "" if strip else func(*args, **kwargs)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/prototypes/protfuncs.py", line 315, in obj
18-10-24 01:46:49 [::]     obj = _obj_search(return_list=False, *args, **kwargs)
18-10-24 01:46:49 [::]   File "/usr/src/evennia/evennia/prototypes/protfuncs.py", line 295, in _obj_search
18-10-24 01:46:49 [::]     raise ValueError("$obj: Query '{}' gave no matches.".format(query))
18-10-24 01:46:49 [::] ValueError: $obj: Query '#1234' gave no matches.
18-10-24 01:46:49 [EE] User input was: '@spawn {'key':'stone(#1234)'}'.
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

It seems like the parsing and its regular expression is incorrect?

**Code lifted from `evennia.prototypes.prototypes.protfunc_parser`**

```python
import re
_RE_DBREF = re.compile(r"(?<!\$obj\()(#[0-9]+)")
v = 'stone(#1234)'
_RE_DBREF.sub('$obj(\\1)', v)
'stone($obj(#1234))'
 ```

**Comment by Henddher** [comment]
According to python 2.7 docs for regex:

>(?<=...)
Matches if the current position in the string is preceded by a match for ... that ends at the current position. This is called a positive lookbehind assertion. (?<=abc)def will find a match in abcdef, since the lookbehind will back up 3 characters and check if the contained pattern matches. The contained pattern must only match strings of some fixed length, meaning that abc or a|b are allowed, but a* and a{3,4} are not. Group references are not supported even if they match strings of some fixed length. Note that patterns which start with positive lookbehind assertions will not match at the beginning of the string being searched; you will most likely want to use the search() function rather than the match() function:

>>> import re
>>> m = re.search('(?<=abc)def', 'abcdef')
>>> m.group(0)
'def'
This example looks for a word following a hyphen:

>>> m = re.search('(?<=-)\w+', 'spam-egg')
>>> m.group(0)
'egg'
(?<!...)
Matches if the current position in the string is not preceded by a match for .... This is called a negative lookbehind assertion. Similar to positive lookbehind assertions, the contained pattern must only match strings of some fixed length and shouldn’t contain group references. Patterns which start with negative lookbehind assertions may match at the beginning of the string being searched.


Perhaps `_RE_DBREF` the following?

```python
_RE_DBREF = re.compile(r"(?<=\$obj\()(#[0-9]+)")
```

```python
>>> v = 'obj(#123)'
>>> _RE_DBREF = re.compile(r"(?<=\$obj\()(#[0-9]+)")
>>> _RE_DBREF.sub('$obj(\\1)', v)
'obj(#123)'
>>> v = 'hp(#123)'
>>> _RE_DBREF.sub('$obj(\\1)', v)
'hp(#123)'
>>> v = '$obj(#123)'
>>> _RE_DBREF.sub('$obj(\\1)', v)
'$obj($obj(#123))'  ### Although this doesn't look right either

```

**Comment by Henddher** [comment]
Hi @Griatch, what do you recommend?

I think it's just a matter of defining the requirements - no?

**Comment by Griatch** [comment]
The first error is not really a bug  - what the regex does is to convert `#1234` into the protfunc `$obj(#1234)` just before passing it into the protfunc parser (this way the protfunc parser can just deal with `$protfuncs` without needing any special cases for `#dbrefs`) . The ValueError says that the object with dbref `1234` does not exist - so it's a real error raised by the `$obj` protfunc. 

What can rather be discussed is the suitability of letting that `ValueError` pass to the user uncaught. Better would likely be for the system to let through `stone(#1234)` as a normal string in this case. 

```### Although the following don't look right either
>>> _RE_DBREF.sub('$obj(\\1)', v)
'$obj($obj(#123))'  
### perhaps just `$obj(#123)````
Yes, this is an error - if you manually put `$obj(#123)`, the regex should not add another nesting.

**Comment by Henddher** [comment]
> what the regex does is to convert #1234 into the protfunc $obj(#1234) 

So any ‘r”#\d+”’ regex will always translate into ‘$obj()’ call?

Isn’t that too strict?

I would think that “stone(#123)” just means that. If it were a protfunc, it must be preceded by $. No?

**Comment by Henddher** [comment]
I found the tests and they verify the current regex is correct. 

So it's not the parser but the step before maybe?

https://github.com/evennia/evennia/blob/6ca5b83802bf3b230f774ea5f8e1f3af1d4519ac/evennia/prototypes/tests.py#L315-L319

**Comment by Griatch** [comment]
> I would think that “stone(`#123`)” just means that. If it were a protfunc, it must be preceded by $. No?

Maybe; `#1234` is always a `#dbref` in other parts of Evennia though, so it should be a pretty intuitive thing for builders to use `#dbref` in the prototype. But I can see the argument for always requiring `$` to perform a substutution. 

> Coincidentally, github treats # followed by number as a ref to bug. Unless correctly quoted. `#123`
Yes, note how I always use backticks for those? That's why. :smile: Same thing for talking about  `@command`, or you'll ping a user named `command` somewhere on Github ...

As for the unit tests, might well be that that particular example (`$obj($obj(...))`) was not covered?

**Comment by Griatch** [comment]
It indeed looks like the `#dbref` conversion is not covered in the docs. This (and protfuncs overall) is a new functionality in recent Evennia 0.8 so it's very new. Thinking more about it, maybe it *is* better to be explicit here and require `$obj()` (or maybe an alias `$dbref()`) to specify an object reference in a prototype. Clearly it was not intuitive behavior to you, so that's one data point right there :wink:. 

That would be a separate issue from preventing the traceback though; I would not be surprised if the traceback is converted into a message if this is done within the OLC menu but let through when passing the protototype directly to the `@spawn` command like here.

**Comment by Griatch** [comment]
The `$obj` protfunc is more general since it allows you to free-form search for an object by key, alias or dbref. Having a separate `$dbref()` only for dbrefs could be pretty intuitive though, I agree.
 
The wiki is normally edited in-place, in the web interface. Usually no permission is needed. If you have some big change and are unsure about it you can always ask about it in IRC/Discord.

**Comment by Henddher** [comment]
> The `$obj` protfunc is more general since it allows you to free-form search for an object by key, alias or dbref. Having a separate `$dbref()` only for dbrefs could be pretty intuitive though, I agree.

So to summarize:

1. `#1234` would be treated as plain text. No implicit conversion to `dbref` will be done and no object search will occur.
2. `$obj(#1234)` will treat `#1234` as a `dbref` and will perform object search.
3. `$dbref(#1234)` would *typecast* `#1234` as a `dbref` and it will perform object search. `$dbref()` is a subset of `$obj()`.

Correct?

**Comment by Henddher** [comment]
@Griatch,

Turned out that after introducing `$dbref`, the tracebacks are gone as there is no automatic conversion of `#number` into `$obj(#number)`. Instead, searches are now explicit either by `$obj(#number)` or by `$dbref(#number)`

So two birds with one stone 😄
