### ISSUE TITLE
Feature Request: @restart as alias to @reset

### ISSUE THREAD

**Issue by thenomain** [evennia/evennia#1707]
#### Brief summary of issue / Description of requested feature:

For us Mushers, we use "@restart" to, er, restart the game. So I think it'd be a good alias for @reset.

Thanks.

**Comment by Griatch** [comment]
Thanks for the suggestion! I think having a `@restart` alias in game is fine, but it should apply to the `@reload` command instead of the `@reset` (see comments in #1708). So closing this since the PR could be changed. 

> Hint for the future: When you refer to `@restart`, try to put it within backticks. Otherwise you are pinging another github user named `restart` (I'm sure there is one). :)

**Comment by Griatch** [comment]
Closing this, but you can still comment in the thread if you want :)
