### ISSUE TITLE
RFC: Non-alphanumeric chars in account/character names

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1709]
#### Brief summary of issue / Description of requested feature:
There is nothing stopping players from creating nonsensical or confusing names such as `+desc`, `@2@@@jds+-cjn` or even names mimicking default commands (`look`, `@ban`, etc.).

I thought I had addressed some of this with the Django ASCIIUsernameValidator but it allows more nonsense than it should in this context. Its criteria is `This value may contain only English letters, numbers, and @/./+/-/_ characters`.

I can fix this myself (considering replacing AUV with a regex validator and making commands/aliases reserved) but before I do, I wanted to see if it would be worth the effort-- under what circumstances do any of you *want* names to allow special characters (excluding hyphens)? Only if it's not the first character, or only if it isn't repeating, or only if it follows a string of three-but-no-more-than-four consonants and the name keeps a 1:3 vowel:consonant ratio? Trying to get a feel for diverse use-cases when coming up with a sane default.

**Comment by Griatch** [comment]
It's a good question. I think it makes sense to to limit nonsensical and particularly command-like names. The main problem may be how to relay the error correctly to the user in an informative way. It's really hard to tell what kind of logic would be acceptable for the most people but it does feel like most people will not be too adventurous with the letter-combinations and would be ok with having those exotic variations restricted.

**Comment by Griatch** [comment]
@jaggiJ: As a hint, a more efficient way to implement this without having to loop over the string character for character (which is slow), you could use sets: 
```python
allowed_set = set(allowed_input)
user_set = set(user_input.split())

# the difference is what is in user_set but is not in allowed_set
forbidden_set = user_set.difference(allowed_set)
if forbidden_set:
    print("{} characters are invalid for name".format(' '.join(forbidden_set))
# ...
```

**Comment by strikaco** [comment]
@jaggiJ Wow, you allow 79-character usernames? I couldn't imagine having to type that out every time I need to `kill` someone-- they'd get multiple hits on me before I finish typing their name :)

Thanks for the contribution. I'm trying to take advantage of Django's existing validation framework, which uses things like regular expressions as parameters rather than custom functions (although your function could certainly be implemented as a standalone Validator). 

I think you might benefit from regex as well with your code, see:

```
import re
regex = '^([a-zA-Z0-9\&\.\-\_\s]{,79})$'    
users = (
    'pickle rick',
    'Wolfeschlegelsteinhausenbergerdorffvoralternwarengewissenhaftschafers wesenchafewarenwholgepflegeundsorgfaltigkeitbeschutzenvonangereifen duchihrraubgiriigfeindewelchevorralternzwolftausendjahresvorandieer scheinenbanderersteerdeemmeshedrraumschiffgebrauchlichtalsseinu rsprungvonkraftgestartseinlangefahrthinzwischensternartigraumaufde rsuchenachdiesternwelshegehabtbewohnbarplanetenkreisedrehensichund wohinderneurassevanverstandigmenshlichkeittkonntevortpflanzenundsiche rfreunanlebenslamdlichfreudeundruhemitnichteinfurchtvorangreifenvon andererintlligentgeschopfsvonhinzwischensternartigraum',
    'whyyyyyyyy!!!!!!'
)
for user in users:
    if re.match(regex, user):
        print('%s is acceptable' % user)
    else:
        if len(user) >= 79:
            reason = 'too long'
        else:
            reason = 'invalid characters'
        
        print('%s is not acceptable, %s' % (user, reason))
```

**Comment by strikaco** [comment]
@Griatch Is there a way to get a list of all loaded command sets, or a list of all registered commands? I can't find a way to get anything like that without Evennia trying to calculate which ones are in scope for a specific object.

**Comment by Packetdancer** [comment]
@strikaco — I don't think there's a convenient way to do that, especially given that some command sets are dynamically generated (like a player's comm aliases).  

Griatch might have a better way, but what I'd do is make a container class like `evennia.default_cmds` (an `_EvContainer` instance defined in `evennia/__init__.py`) using your game's main command sets, and have functionality to check a string against all the commands registered in that container and return a True if it matches anything or a False otherwise.  That way you'll have the union of all the command sets you added to it, and it won't include things like user-specific comm aliases and whatnot.

**Comment by strikaco** [comment]
#1445 should also be considered in any solution to this.

**Comment by Griatch** [comment]
This is handled by a latinification method now in `develop` branch. Closing this now for better overview.
