### ISSUE TITLE
EvTable "borders off" causes spacing issues in the webclient

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#1710]
#### Brief summary of issue / Description of requested feature:

I am reporting this one for @Packetdancer from an IRC conversation so that it isn't forgotten/missed.

#### Steps to reproduce the issue / Reasons for adding feature:

<Packetdancer> Apparently EvTable does some odd alignment stuff under the webclient if you turn off borders.  For instance, under telnet, you'll still have a space where the border should be, and under the webclient you won't.  In some cases things don't line up properly because of this.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

I'm guessing this is an issue with a &lt;div&gt; &lt;/div&gt; getting 
generated, instead of an explicit &lt;div&gt; &amp;nbsp; &lt;/div&gt;

**Comment by Griatch** [comment]
![Screenshot from 2019-09-02 08-37-07](https://user-images.githubusercontent.com/294267/64094755-03263900-cd5d-11e9-99d5-8682801291b7.png)

As far as I can tell, this is not an issue in the current webclient. The spaces (above selected with the mouse in the webclient for visibility) extends correctly beyond the written text (the same distance as it does with borders applied). 

So this appears to have be resolved. Closing. Re-open if finding some other way to reproduce the problem.
