### ISSUE TITLE
Typeclass web_get_*_url methods improperly handle CamelCased model names

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1712]
#### Brief summary of issue / Description of requested feature:
If you try to retrieve a URL using the web_get_*_url() methods for a model with a CamelCased name, the result includes an unwanted space.

#### Error output / Expected result of feature
`2018-10-27T06:39:52+0000 [stdout#info] Reverse for 'help entry-detail' not found. 'help entry-detail' is not a valid view function or pattern name.`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I either need to slugify all terms before sticking them in the URL (probably ideal), regex/replace any spaces in the string or find a better Django meta-method that returns the model name without spaces.

**Comment by Griatch** [comment]
Resolved in #1714
