### ISSUE TITLE
Feature Request: Make start of Script's timer component explicit 

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1715]
####  Description of requested feature:

This feature tries to decouple the timer component of Scripts from the starting of the Script to something that can be manipulated directly by the user with an explicit call to `.start()`. Also, running `Script.stop()` should not automatically delete the script (this can be implemented in the `at_stop` hook if so desired and for backwards compatibility).

For the sake of backwards-compatibility, there should be possible (through creation keywords to keep the old behavior. Possibly we could supply a default `AutoStartScript` for people to plug in who wants exactly the original behavior. 

#### Reasons for adding feature:

The original purpose of Scripts were purely to act as persistent timers and their functionality reflects that - when you create a script with `period > 0` the script is immediately started. When you do `script.stop()` the script timer is not only stopped, the Script instance is also automatically deleted. Overall these mechanisms are old parts of Evennia and rather hard to track and debug. 

Today though, there are many more light-weight ways to run persistent timers (such as `utils.run_async(..., persistent=True)` and the `TickerHandler`) and while the timer component of Scripts are still useful, Scripts are often taking on a more diverse role as custom OOC data storage and acting as a building component in system handlers. 

Problems with this tied connection to the Script creation becomes evident for example in a recent issue where `repeats=1` and `start_delay=False`, leading to the Script starting, repeating and stopping (=deleting) itself before the `save()` operation had even finished running. 

#### Error output / Expected result of feature

Users should have more control over the Scripts's execution and lifetime in the role it has today.  

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Development branch. This change should probably make the Script class simpler in structure.  Unclear what other refactorings can be done as part this change.

**Comment by whitenoiseoss** [comment]
I am working on a minimally invasive path forward on this right now.

A few things off the top of my head:

- Change ScriptHandler's `autostart` default to False
- Add necessary flag/arg for delete Script on stop()

This type of approach will allow the smallest number of code changes to accomplish the idea. Then we can go bigger from there if desired.

**Comment by Griatch** [comment]
This is now implemented in develop.
