### ISSUE TITLE
More obvious admin point of contact

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1719]
#### Brief summary of issue / Description of requested feature:
There are a few stock error messages that suggest players contact an admin if the error is raised or persists, but we don't make it obvious how or where to do this. If someone can't connect, they won't be contacting anybody in-game...

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
There are many ways this could be solved, but two ideas would be to prompt for either the webmaster's email address or the web URL for a contact form during init, or make it just another setting, and display it on the connection screen and in a help entry.

**Comment by strikaco** [comment]
Django does already have an ADMINS setting, it seems. It integrates with the built-in mail modules and could be used for other purposes too.

https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-ADMINS

**Comment by Griatch** [comment]
@strikaco We already have `ADMINS` in the default settings file (although defaulting to an empty tuple obviously). I think this one may more be a documentation issue on how to use it?

**Comment by strikaco** [comment]
Possibly, but I'm not convinced `ADMINS` is the best remedy for this particular issue anyway. It's intended for admin/developer recipients of error emails, which may not coincide with whichever staff member(s) are tasked with general customer service. Admins may not also want their (likely personal) email listed for this purpose.

I'm thinking `WEBMASTER_EMAIL` would be more appropriate, and if set, will display on the default connection screen ("`If you are having issues logging in, contact webmaster@yourgame.org.`")

**Comment by Griatch** [comment]
Separating ADMIN'd be okay with me.  `WEBMASTER_EMAIL` suggests (to me) this is tied to the web-component of things though, whereas there could be all sorts of reasons for wanting to contact people. Maybe `STAFF_EMAIL` is more suitably generic?

**Comment by strikaco** [comment]
I agree re: 'webmaster'; only reason I went for that term is because it's a self-descriptive public point of contact by convention.

`STAFF_EMAIL` is almost too generic though; it isn't obvious that it's going to be a *public* point of contact.

How about `CONTACT_EMAIL`, `STAFF_CONTACT_EMAIL`, or `PUBLIC_CONTACT_EMAIL`?

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/pull/1741
