### ISSUE TITLE
Log rotation - make dates in filename follow YYYY-MM-DD format

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1721]
#### Brief summary of issue / Description of requested feature:
When logs are written and rotated, the date appended to the end of the filename is variable in length. This leads to incorrect sorting on the filesystem. Both the month and day can be one or two digits in length.

```
-rw-rw-r-- 1 ubuntu ubuntu      0 Oct 28 08:40 server/logs/server.log.2017_10_27
-rw-rw-r-- 1 ubuntu ubuntu      0 Sep 27 17:50 server/logs/server.log.2017_9_27
```

#### Error output / Expected result of feature
```
-rw-rw-r-- 1 ubuntu ubuntu      0 Sep 27 17:50 server/logs/server.log.2017_09_27
-rw-rw-r-- 1 ubuntu ubuntu      0 Oct 28 08:40 server/logs/server.log.2017_10_27
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
It would be preferable if the month and day were padded to a consistent length.

**Comment by Griatch** [comment]
Implemented in `develop`.
