### ISSUE TITLE
develop: Website not correctly logging in when logged in in-game

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1723]
#### Brief summary of issue / Description of requested feature:

When logging in in-game, the website does not detect it, but if you try to log in you still get a warning saying that you are already logged in.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Don't log into the website but open the web client
2. Log into the webclient as usual.
3. Go back to the website - you are not shown as logged in, but clicking `Log in` will still give you an error. 

#### Error output / Expected result of feature

When logged into the game, this should be reflected by the web site. See closed #1063. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is a regression, probably from changes in the session handling/sharing between client and website.

**Comment by Griatch** [comment]
@strikaco Any ideas on this one off the cuff?

**Comment by strikaco** [comment]
Hmm. Looking at the webclient view, I notice it copy/pastes the same
shared_login function that was implemented on the website. So off the cuff
I'm wondering if this is causing some sort of conflict with the middleware.

I'll take a look today.

**Comment by strikaco** [comment]
Ok, so while there is duplicated code and both methods are being executed unnecessarily, the reason for this issue is likely my getting the order of operations wrong when calling the middleware-- I need to formalize testing but I think make_shared_login must be called before rendering the view.

**Comment by Griatch** [comment]
Closed in #1725. Great!
