### ISSUE TITLE
Inconsistent application/handling of Delete lock on Character objects

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1729]
#### Brief summary of issue / Description of requested feature:
* Existing character creation methods (`CmdCharCreate` / `Character.create()`) do not set a `delete` lock on Character objects (by contrast, `CmdCreate` does for generic Objects).
* `CmdCharDelete` *does not* check locks to see if the caller is authorized to delete it, only whether the character is in the caller's playable characters list.
* `CharacterDeleteView` *does* check locks to see if the caller is authorized to delete it (in addition to playable characters), which breaks the view for non-admins.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I don't know if the lock omission is intentional or not, but we should reach a consensus on whether players should be able to delete their own characters by default and set locks appropriately. `CmdCharDelete` should check both the lockstring and the playable characters list to see if the caller is allowed to delete it.

**Comment by Griatch** [comment]
I think these are inconsistencies due to organic growth of the various systems - at a point the `control` lock was considered to serve this purpose I think. But it makes sense that a `delete` lock should be set as well as checked on deletion.

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/pull/1741
