### ISSUE TITLE
Debug tools should not be enabled by default

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1732]
#### Brief summary of issue / Description of requested feature:
One thing Evennia does smarter than Django is not shipping with DEBUG set to True by default.

However, Evennia does an end-run around itself by instead shipping with IN_GAME_ERRORS set to True.

#### Error output / Expected result of feature
Even though Django themselves do it, shame on them. Debugging tools should not be enabled by default. 

In Django's defense, they do make it clear in many, many places that "you are seeing this error message because DEBUG is True and if you're running this in production fix it immediately." Evennia does not do this.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I understand the convenience considerations of turning debugging on for the sake of not hiding errors from new developers but this is bad practice. If new users are not aware of such tools' existence or how to turn them on, there is no way they're going to be innately aware of the fact that they need to turn them off before going live.

Currently we don't discuss debugging at all in the getting started/deployment guides. The only awareness raised about this matter is buried in comments in settings.conf, which assumes all developers are continuously aware of all settings, upstream changes to them, their default state and their implications.

It would be better practice to ship with all debugging tools turned off by default and making enabling them a step during the post-installation process. Given the number of developers with no programming experience this project attracts, it would raise awareness of the existence of debugging tools and their security implications much earlier on in their educational and development lifecycle. We don't do them any favors by handing them a footgun they don't understand the dangers of and expecting them to do the right thing with it.

**Comment by Griatch** [comment]
`IN_GAME_ERRORS` started out being turned off since that made most sense to me from a security standpoint. Cue questions as to why a server who wanted to be friendly to newcomers didn't default to friendly settings for newcomers. Damned if you do, damned if you don't.

**Comment by strikaco** [comment]
I figured as much. Either way works but at the end of the day it's a matter of user education and awareness. We could keep either/both enabled if we did a better job informing users that potentially dangerous settings are enabled by default, why that's a potential problem and how to fix it.

A blurb in "Getting Started" and perhaps a periodic nag in the logs while these settings are active?

**Comment by Griatch** [comment]
It may be worth testing although I fear adding even more steps to the install instructions (a semi-mandatory post-install setup?) is not necessarily going in the right direction from the lower-the-entry-threshold perspective.

**Comment by strikaco** [comment]
Eh, I'm not insisting we add steps to the installation process; it was just an idea-- on the contrary, we should keep the install process as simple as possible to get users in the door. My concern is about what happens when they deploy it as-is.

If we don't broadcast debug warning banners everywhere, then we could do better by perhaps shipping with `LOCKDOWN_MODE` enabled. Enable *all* the debug flags while we're at it. `ALLOWED_HOSTS` is already set to a wildcard, so it's not like we're checking host headers. Devs can hack away to their hearts' content with full debug info on localhost. When the time comes where they want to expose the application to the internet, that's when you slap them with the pre-flight checklist. Then they can either do the right thing or say screw it, disable lockdown and let it fly. Either action they take is now informed--they either care about security or they don't--and by this point they've invested time and effort into the game so it's unlikely they'd abandon their work because of an additional few steps.

**Comment by Griatch** [comment]
I have now added so that on `evennia start -l`, the settings file will be checked for various non-production-ready settings and print warning messages in the terminal about them.

**Comment by strikaco** [comment]
Excellent compromise, thanks!
