### ISSUE TITLE
Unique constraint not imposed on email addresses

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1734]
#### Brief summary of issue / Description of requested feature:
Email addresses are optional but we do not enforce uniqueness when it is provided. Two accounts can have the same email address. In the case of a password reset, which account gets the reset?

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This is an unclear workflow.

There really shouldn't be any circumstances where ownership of multiple accounts is desirable from the sysadmin POV; alts are facilitated by the greater multisession modes. It would be better if the email field set unique=True, but pulling this off with an optional field requires an override of the model's `clean` method to set blank email to None, else blank strings count against cardinality (but this may or may not work with the SharedMemoryModel? I'm unfamiliar with it). See:

https://stackoverflow.com/a/27021872

Alternately, the password reset workflow could confirm both the username and the email address and send the token for the correct account, but this hacks around the problem instead of solving it.

**Comment by strikaco** [comment]
Also worth noting is that addressing this at the model level would likely cause problems with existing games where duplicate email addresses have already been provided. Migrating the schema when duplicates already exist will fail. Devs would have to blow away or otherwise resolve duplication conflicts.

**Comment by strikaco** [comment]
Given the above and an existing userbase (per @Packetdancer) whose connection scripts depend on abusing multisession mode 0/1, perhaps the uniqueness should be enforced using username and email as a composite key.

**Comment by Griatch** [comment]
One could of course make a data migration to find accounts sharing emali and wiping one of them. Not sure we want to do that though, as mentioned there are valid game types where this is desirable even though I agree it's not desirable from an administrative standpoint. In the case of a password reset, the user manually specifying the username/email combo should be the most reasonable way. 
Closing this.
