### ISSUE TITLE
Webclient - No scrolling on mobile

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1737]
#### Brief summary of issue / Description of requested feature:
The webclient does not provide a mechanism to scroll (or just peg the view to the bottom of the buffer) when messages extend beyond the height of the screen. Game quickly becomes unplayable after a login and lookaround-- further messages cannot be seen; they pass behind the input box and off the bottom of the screen.

#### Steps to reproduce the issue / Reasons for adding feature:
1. Use mobile device
2. Login to webclient
3. Look, do other stuff

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Develop branch, LG G5 phone, Brave browser, Chrome browser

**Comment by johnlund** [comment]
I'm having the same issue on a mac desktop and seeing:

GET https://unpkg.com/split.js@1.5.9/split.min.js net::ERR_ABORTED 404

and

ReferenceError: Split is not defined
