### ISSUE TITLE
Directory indexes are browsable by default

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1746]
#### Brief summary of issue / Description of requested feature:
On a default installation, the `/media` and `/static` directories are browsable by default.

All static and user-uploaded assets can be browsed by requesting either endpoint.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Go to `mud.example.com/static`
2. Go to `mud.example.com/media`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Normally this is fixed by setting a simple flag in Nginx or Apache; banner grab yields `TwistedWeb/18.7.0` but I have no idea what options (if any) Twisted/Evennia provides to mitigate this.

(In this particular case though, since Twisted is the actual webserver here, slapping Apache/Nginx on top of it will likely not prevent this behavior either. It fails to do so in my test environment!)

Until a more configurable solution can be found, if this is cause for concern, just create a blank 'index.html' file in any/all directories you don't want browsed.

**Comment by Griatch** [comment]
It would be good to offer a saner/safer default for this, indeed.
