### ISSUE TITLE
Local settings file is ignored during testing

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1747]
#### Brief summary of issue / Description of requested feature:
When running unit tests for a game, the test runner ignores all settings defined by the game.

#### Steps to reproduce the issue / Reasons for adding feature:
```
from django.test import TestCase
class SettingsTest(TestCase):
    def test_settings(self):
        # Game's settings.MULTISESSION_MODE is currently set to 2.
        print('Multisession mode: ' + str(settings.MULTISESSION_MODE))
        
        # Game's server name is currently set to 'Westworld'
        print('Server name: ' + settings.SERVERNAME)
        
        self.assertEqual(settings.MULTISESSION_MODE, 2)
        self.assertTrue(settings.SERVERNAME != 'Evennia')
```

#### Error output / Expected result of feature
```
Multisession mode: 0
Server name: Evennia
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Dev branch. 

This makes little sense and has other implications, such as the test runner using production databases for testing despite being configured to do otherwise.

**Comment by Packetdancer** [comment]
I thought this was by design, so that you can still run the default Evennia tests without local settings breaking expectations?  I've always just done `--settings settings` to load my `server/conf/settings.py` file when running tests against my own stuff, so `evennia --settings settings test .` to run all the tests for a game.

**Comment by strikaco** [comment]
@Packetdancer Hey, that's cool. I didn't know about that trick! :)

I don't think it's design, it's user error-- I'm importing the wrong settings file, which was conveniently left out of my code block above. I'm using `from django.conf import settings` instead of `from server.conf import settings`.

**Comment by strikaco** [comment]
@Packetdancer Thanks again for that tip; I was having a separate issue where unit tests weren't migrating all my tables and I was getting `no such table` errors when running tests. Specifying the correct settings file resolved this, since it is now clear it wasn't loading the appropriate app.
