### ISSUE TITLE
(Contrib) Health bar does not use fill color as expected

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1751]
#### Brief summary of issue / Description of requested feature:
The contrib health bar always uses red as the first color argument when the current value is low, regardless of whether an alternate palette is provided.

#### Steps to reproduce the issue / Reasons for adding feature:

Here's a unit test function that demonstrates the issue and expected output:

    def test_health_bar(self):
        from evennia.contrib.health_bar import display_meter
        # Prints meter as expected-- this is a mostly dead character's HP bar
        meter = display_meter(25, 100, fill_color=["R", "Y", "G"])
        self.assertTrue(meter.startswith('|[R'), 'Meter should be red!')
        
        # Also prints meter as expected-- character's power level is over 9000
        meter = display_meter(9001, 9000, fill_color=["G", "Y", "R"])
        self.assertTrue(meter.startswith('|[R'), 'Meter should be red!')
        
        # But when a character isn't going Super Saiyan, his temper should be cooler
        meter = display_meter(1, 9000, fill_color=["G", "Y", "R"])
        self.assertTrue(meter.startswith('|[G'), 'Meter should be green!')

**Comment by Griatch** [comment]
@FlutterSprite Is this something you may have time to look at?

**Comment by FlutterSprite** [comment]
My main game project releases in two days so this is absolutely the worst possible time for me, haha - I'll take a quick scan over the code though and try to see what's up

**Comment by FlutterSprite** [comment]
Does it always use red specifically, or does it just use the color from the wrong end of the provided spectrum? If you replaced red with, say, magenta in your fill_color list, would it show up as magenta or still be red, even if red isn't included?

**Comment by FlutterSprite** [comment]
I took a peek at my health bar code and this may be the problem:

`# Pick which fill color to use based on how full the bar is
    fillcolor_index = (float(len(fill_color)) * percent_full)
    fillcolor_index = int(round(fillcolor_index)) - 1
    fillcolor_code = "|[" + fill_color[fillcolor_index]`

Particularly the `fillcolor_index = int(round(fillcolor_index)) - 1` part - if the rounded value is 0 (for an especially small value like 1/9000), it might be picking "-1" as the index color. See if adding this line fixes it:

`# Pick which fill color to use based on how full the bar is
    fillcolor_index = (float(len(fill_color)) * percent_full)
    fillcolor_index = int(round(fillcolor_index)) - 1
    if fillcolor_index < 0:
        fillcolor_index = 0
    fillcolor_code = "|[" + fill_color[fillcolor_index]`

**Comment by strikaco** [comment]
@FlutterSprite That does fix the problem, thanks!

**Comment by Griatch** [comment]
I added this fix in `master`, closing this.
