### ISSUE TITLE
evennia fails to start on non windows systems

### ISSUE THREAD

**Issue by brijohn** [evennia/evennia#1754]
### Brief summary of issue / Description of requested feature: ###

When trying to start an evennia server on a non windows system it fails due to the use of the platform specific python exception WindowsError. This regression appears to have been added recently as part of PR #1748. 

Since WindowsError is defined as a subclass of OSError, this should probably be changed to catch OSError and not WindowsError.

**Comment by vincent-lg** [comment]
Nice catch.  I hadn't considered (duh!) this was a Windows-specific exception.  Will PR soon, thanks!
