### ISSUE TITLE
Duplication of items in console output when referencing multiple objects with RPContrib.

### ISSUE THREAD

**Issue by Fumarii** [evennia/evennia#1757]
#### Brief summary of issue / Description of requested feature:
When attempting to manipulate multiple objects with the same name in the client, there is exponential duplication of objects when being asked to choose which object to refer to from the group of objects.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use @create/drop to make some number of multiple, identical objects. In my case, I am not supplying any arguments to the command other than the key for the object. "@create/drop napkin" three times.
2. From within a connected client, use look or examine or other such command to attempt to refer to one of the objects that you have created.
3. Client will output the number of objects squared, but will still appropriately refer to correct number of DBrefs in the output. 

#### Error output / Expected result of feature

Error Output: 
You create a new Object: pencil.
You create a new Object: pencil.
More than one match for 'pencil' (please narrow target):
 1-pencil(#424)
 2-pencil(#425)
 3-pencil(#424)
 4-pencil(#425)

Expected Result: 
You create a new Object: pencil.
You create a new Object: pencil.
More than one match for 'pencil' (please narrow target):
 1-pencil(#424)
 2-pencil(#425)

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

version 0.8.0 (rev 5e98127)

Server is running with the RPContrib contrib active, and with the Object class inheriting from the ContribRPObject, and the same for room and character objects.

**Comment by Griatch** [comment]
Fixed in develop branch.
