### ISSUE TITLE
Failed file rotation from http logging can leave webserver in invalid state

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1758]
#### Brief summary of issue / Description of requested feature:
If `DEBUG` mode is set to true, HTTP requests are logged by the webserver. However, when the server attempts to rotate the log file, it's possible for that to fail if it conflicts with the portal writing to the log file at the same time, reporting that it's in use by another process. Thereafter, every action on the website (including any command in the webclient) will generate a file I/O exception, eventually leading to the webserver to stop functioning entirely in the portal.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Difficult to reproduce due to being a timing issue. Happened in Windows 10 while in DEBUG mode under moderate use.

#### Error output / Expected result of feature
A file I/O error when attempting to rotate the http request log, leading to every action in the website generating an error in the portal logs after that point.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Possibly should remove logging of HTTP requests even in DEBUG mode unless they're explicitly turned on by some other setting, though admittedly DEBUG mode should never be used for production anyway.

**Comment by TehomCD** [comment]
I believe it's the http.log which the webserver only writes to when `DEBUG` is True, but it's used by both the server and portal process apparently. I don't know offhand why that is - maybe the webclient?

**Comment by Griatch** [comment]
Hm, I suppose both the webserver and the web proxy will write http logs.

**Comment by Griatch** [comment]
@TehomCD Just syncing up on this and if you still notice this from time to time?

**Comment by TehomCD** [comment]
Honestly, no, I've never seen this repeated since the one time it's happened. I guess it could be since I so rarely run environments in with `DEBUG` set to True, but I've never seen this repeat.

**Comment by Griatch** [comment]
Never managed to reproduce this and as it appears, nor can @Tehom. Feel free to reopen if it happens again, but closing this for now.
