### ISSUE TITLE
Searching with candidates: a problem in merge

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1763]
#### Brief summary of issue

Some bug has been fixed in master but incorrectly merged into develop and develop-py3 branches.  So it's still here... and might reappear when we merge these branches into master.  Let's save that fix!

#### Details

In develop and develop-py3 branch, the `candidates` keyword argument in `Object.search` is ignored.  There's a beautiful TODO to address it.  While this TODO has been addressed in master (see the link below), it's not addressed in develop or develop-py3 and hasn't properly been merged despite the date of the commit to modify that TODO.

Comparing 👍 

- [@master:evennia/objects/objects.py:458 in search(...)](https://github.com/evennia/evennia/blob/master/evennia/objects/objects.py#L428)
- [@develop:evennia/objects/objects.py:434 in search(...)](https://github.com/evennia/evennia/blob/develop/evennia/objects/objects.py#L434)
- [@develop-py3:evennia/objects/objects.py:434 in search(...)](https://github.com/evennia/evennia/blob/develop-py3/evennia/objects/objects.py#L434)

#### Note on PRs

I would have liked to offer PRs for fixes in both branches (develop and develop-py3) but I'm not sure how to handle it.  My PRs will break the merging tree while there might be a better way to do it all.  It's a simple fix but I'm not sure how to address it.

**Comment by Griatch** [comment]
This has been fixed; This appears to be a result of stricako's refactorings; not sure if it was a merge conflict resolution error or simply a change of the code that didn't have that fix.
