### ISSUE TITLE
Django collectstatic command line arguments are not working

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#1774]
#### Brief summary of issue / Description of requested feature:

Evennia command line 'collectstatic' command always prompts for "yes" or "no"

Django docs say it supports a silent option:
     python manage.py collectstatic --noinput

#### Steps to reproduce the issue / Reasons for adding feature:

    evennia collectstatic --noinput

#### Error output / Expected result of feature

Instead of the prompt, this should just go and collect static as if prompt response was 'yes'

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This may be fixed in the newer versions of Django.  I don't remember when this feature was added.

**Comment by Griatch** [comment]
Testing this in develop I can confirm this is indeed supported in develop branch and the evennia launcher forwards it correctly. Closing this.
