### ISSUE TITLE
Suggestion: avoid global changes in tests

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1779]
#### Description of requested feature:

Unit tests should avoid applying global modifications that might affect other tests and should encapsulate the logic in a resource-like approach (open/close, context management...).

#### Reasons for adding feature:

By nature, unit tests should remain independent of each other.  Doing top-level changes in unittests imply some changes are "leaked" to other tests, alter their behavior and make the test result highly-dependent on the order of execution, if two tests happen to use the same feature for different purposes.  In other words, instead of having global changes in unit tests, make sure to limit the change for this test case.  Changes that could benefit from this isolation:

1. Modifications in settings: settings are too often modified in the test top-level code and are not set back afterwards.
2. Mocking of objects: mocking sometimes follow the same logic, we mock in the top-level code of some test but this mock survives for other tests and affect their behavior.

#### Expected result of feature

At this point, the behavior of added tests is a bit hard to predict because some settings or objects have been changed by others and not properly cleaned up.  Altering new tests to make sure they restore the proper settings and non-mocked objects makes for hard-to-read-and-understand code which is highly-dependent on other tests.  So again, it's not an ideal solution, hence this proposal for cleaning-up current tests.

There are different ways to do it:

- Decorators (as I believe you have implemented for changing settings), either on the test case class or test method.
- Context managers (especially useful for mocking of objects).

And there might still be others.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

> That's more of a development proposal.  It won't affect the mainstream users except, perhaps, in the future.  In a word, it's a "better act now than regret later" case study.

**Comment by Griatch** [comment]
@vincent-lg I agree, and I don't think anyone has *deliberately* made tests that affects the global state - doing so has probably happened accidentally or by ignorance. To make this more of a trackable feature, do you have any suggestions of specific tests that have this quality and which should be changed?

**Comment by vincent-lg** [comment]
I should browse all tests but here's what I've seen (open debate, of course, each time):

- `evennia.contrib.ingame_python.tests`: this one is on me obviously, my bad.
- `evennia.contrib.security.auditing.tests`: you told me this one was fixed, it's just not yet merged in develop-py3, so probably disregard.
- `evennia.utils.test_resources`: this is the most used in Evennia I think so this might not be trivial.

So definitely not that much.  However, I did a very quick browsing and some might be harder to spot.  But we'll probably treat them as we spot them then.

**Comment by Griatch** [comment]
@vincent-lg What particular aspects of these modules are you referring to? Any specific examples?

**Comment by vincent-lg** [comment]
Yeah.  The best example, in `evennia.contrib.utils.test_resources` is here:

```python
# ... importing ...
SESSIONS.data_out = Mock()
SESSIONS.disconnect = Mock()
```

When the test is imported it overrides the session handler's two methods `data_out` and `disconnect`.  But when the test is over these methods are still mocked in every test.  Again, perhaps it's desirable and my own test should unmock-remock for this particular purpose.

Something similar in `evennia.contrib.security.auditing.tests`:

```python
# ... imports ...
# Configure settings to use custom session
settings.SERVER_SESSION_CLASS = "evennia.contrib.security.auditing.server.AuditedServerSession"
```

There are other settings that are changed here, and in the test for the in-game Python system, but these are contrib-specific settings and are less problematic.  For the in-game Python system I would think I should fix that anyway, just because it's cleaner.  But these are the pieces (and perhaps only the `test_resources` remain to be fixed now).  It might be worth doing a general overview of the test suite.  Or perhaps not.  I'll let you decide!

**Comment by Griatch** [comment]
Yeah, a general overview of this for the test suite is probably needed. A lot of these tests were also written at a time when we/I didn't know as much as about unittests best practices (we didn't introduce the `mock` library until much later). There is also https://github.com/evennia/evennia/issues/1396, which relates somewhat to this (although it has more to do with us properly mocking the values in settings).

**Comment by Griatch** [comment]
I have removed the global effects where pointed out. I'll close this now, but there are no doubt other places that could do with a refactoring. If nothing else the unit tests are very slow to run.
