### ISSUE TITLE
Remnants of card-block (should be card-body) in web defaults

### ISSUE THREAD

**Issue by poisonbl** [evennia/evennia#1780]
#### Brief summary of issue / Description of requested feature:

Formatting issues (lack of padding) on several page templates remain after the login/logout pages were patched in PR#1463

Affected templates: 404.html, 500.html. evennia_admin.html. tbi.html. flatpages/default.html

Will add a PR for them shortly.

**Comment by Griatch** [comment]
Thanks! Closed since PR merged.
