### ISSUE TITLE
[BUG] Traceback in OLC after searching and editing a prototype

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1787]
#### Brief summary of issue / Description of requested feature:
Trying to see if I can save changes to prototypes through changing a single spawned instance of the item and then going through the spawn menu.

#### Steps to reproduce the issue / Reasons for adding feature:
1. Changed an attribute on a spawned item
2. Through the spawn menu, searched for the item and then used c<item> to load it
3. Examined attributes of the prototype
4. Tried to save the prototype

#### Error output / Expected result of feature
Menu node 'node_prototype_save' is either not implemented or caused an error. Make another choice.

 Traceback (most recent call last):
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\utils\evmenu.py", line 617, in _execute_node
19-02-24 14:29:14-08 [::]     ret = self._safe_call(node, raw_string, **kwargs)
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\utils\evmenu.py", line 580, in _safe_call
19-02-24 14:29:14-08 [::]     ret = callback(self.caller, **kwargs)
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\prototypes\menus.py", line 2183, in node_prototype_save
19-02-24 14:29:14-08 [::]     error, text = _validate_prototype(prototype)
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\prototypes\menus.py", line 233, in _validate_prototype
19-02-24 14:29:14-08 [::]     spawner.spawn(prototype, only_validate=True)
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\prototypes\spawner.py", line 767, in spawn
19-02-24 14:29:14-08 [::]     attributes.append((attrname, init_spawn_value(value), category, locks))
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\prototypes\prototypes.py", line 731, in init_spawn_value
19-02-24 14:29:14-08 [::]     elif value and is_iter(value) and callable(value[0]):
19-02-24 14:29:14-08 [::]   File "f:\repositories\evennia\evennia\utils\dbserialize.py", line 213, in __getitem__
19-02-24 14:29:14-08 [::]     return self._data.__getitem__(key)
19-02-24 14:29:14-08 [::] KeyError: 0

**Comment by kaleara** [comment]
The error occurs when my attribute is a dictionary, and happens when I do anything with spawn, not just in the menu.

**Comment by kaleara** [comment]
I seem to have fixed it with "and not isinstance(value, dict)" before the "and callable(value[0])" on line 731 of prototypes.py, but I don't know if that's the best way to do it.

**Comment by kaleara** [comment]
The above worked for what looked like the same issue when I was trying to spawn something, but it doesn't work for trying to save a loaded prototype using the menu. What looks like a dictionary isn't returning as a dictionary using isinstance, and I have no idea why.

**Comment by Griatch** [comment]
I could not reproduce the issue in the (develop-branch) menu, but a fix for the normal spawn behavior was now implemented in develop. This will close with the release of 0.9.

**Comment by Griatch** [comment]
Closed with merger of develop branch.
