### ISSUE TITLE
create_message Errors out and causes contrib/mail.py to fail

### ISSUE THREAD

**Issue by ph1234k** [evennia/evennia#1788]
#### Brief summary of issue / Description of requested feature:
Trying to create a mailing system and used the contrib/mail.py module as a base, unmodified. 
Sending a message with @mail alerts the players that they have sent or received a message, however if you then try to read it/list the inbox you will find no message. 
Digging in, it is hitting a stack trace related to create_message trying to identify typeclass. 
Ensured sending object has `__dbclass__` defined and an acceptable value. (AccountDB, CharacterDB or ObjectDB)

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a message: `@py evennia.utils.create.create_message(self.id, "Can you read this", "phreak", "TEST")`
2. Stack trace produced

#### Error output / Expected result of feature
```
@py evennia.utils.create.create_message(self.id, "Can you read this", "phreak", "TEST")
File "/data/home/phreak/projects/muddev/evennia/evennia/utils/create.py", line 333, in create_message new_message.senders = sender File "/data/home/phreak/projects/muddev/evennia/evennia/comms/models.py", line 175, in __senders_set raise ValueError("This is a not a typeclassed object!") ValueError: This is a not a typeclassed object!
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia Version: 0.8.0 (rev a3240e09)
OS: Ubuntu 18.04
As for ideas to fix, I am not yet sure as I don't quite understand the check yet or what value self.caller returns in mail.py when calling create_message
Everything on my current game is stock, out of the box setup except that I imported the mail command from contrib/mail.py and added it to my default command set.

**Comment by ph1234k** [comment]
@grungies1138 If you are still around the project - I feel like I am testing the wrong areas. Any ideas on what I can test to figure out what is hanging up evennia.contrib.CmdMail.send_mail()?

As above, the command itself is running in game and at least partially completing as it notifies all involved parties but I am not actually seeing any messages in anyone's inbox.

**Comment by Griatch** [comment]
This should be closed when develop branch merges.

**Comment by Griatch** [comment]
Closed with merger of develop branch.
