### ISSUE TITLE
webclient xterm256 rendering issues

### ISSUE THREAD

**Issue by tottori** [evennia/evennia#1792]
#### Brief summary of issue / Description of requested feature:
webclient has issues with complicated xterm256 rendering

#### Steps to reproduce the issue / Reasons for adding feature:
Evennia output string follows:
`{n%r{[210{530@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@{n%r{[210{530@@{[334{234#  {[234   {223# {[334{234# {[234{233#{[334{234#  {[234{233# {[334{234#                      {233#{223#{233#{234#{223#  {234#    {[210{530@@{n%r{[210{530@@{[334 {234#   {[234 {233#  {[334{234#      {[234 {[334#               {[234  {[334#       {233#{234#    {233#{[234{223#{[210{530@@{n%r{[210{530@@{[334{234#      {[234 {223# {[334{234#  {[234{223#  {[334{234#   {233#{234# {233# {234#       {223#{[233# {[223{222# {[334{234#   {223#{[234#{[334{233#   {234# {233#{[210{530@@{n%r{[210{530@@{[334{234#              {[344{334#    {[445{344#{334# {[444#{[344# {[334  {234#{[223 {112#{[112 {001#{[111#  {[112{011#{[223{112#{[334 {233#{223#    {233#     {[210{530@@{n%r{[210{530@@{[344{234#{[334#        {[444{334#    {[545{444#{[555{544#    {545#{444#{[545#    {[445#{[333 {[223{212#{[112 {001#{[011{101#  {[223 {[334 {234#  {233#{223#     {233#{223# {[210{530@@{n%r{[210{530@@{[334{234#     {333#{[333{223#{[223{222# {[222{212#{112#{212#{[223{222#{[323#{[333#{323#{[334{333#      {[333{323#  {[334{333#{[434#{[444{334#{434#{334#{[334{333#{[223 {[111{001#{[112 {[334{234#  {233#{[234#{[334{234# {[234{233#{223# {233#{[334{234#  {[234 {[210{530@@{n%r{[210{530@@{[334{234#  {[345{334#{[334{223#{[222{112#{[212#{[112 {[111{001#{[011{101#{[001{111#{[112{001#    {[222{112#{[223# {[222#{[112  {[222#{[223#{212#{222#{212# {222# {[323{223#{[334{333#{[444{434#{[445{444#{[444{334#{[333{223#{[344{334#  {[334  {234#        {[234 {[210{530@@{n%r{[210{530@@{[334{234# {[344{334#{[223 {[112{001#{[111#{[001{111#  {[112{001#{012# {111#   {[223{112#  {[222# {[112 {111#    {[222{112#{[223#{222#{[112{111#{[111{001#{[222{112#{[334{333#{[545{444#{[555{445#{[444{334#{[334 {[344#  {[334  {[344# {[334 {[344# {[334 {234#{[344{334#{[210{530@@{n%r{[210{530@@{[334{234#{[344{334#{[334{223#{[111{001#{[112#{011#  {111#{011# {[011{101#{[001{110#{[112{111# {011#    {[122{112#{[222#{[122#{[112 {011#{[111{001#  {011#{[112{111# {[111{001#{[001{111#{[111{001#{[223{212#{[444{334#{[555{445#{[444{334#{[334{234# {[344{334#{[345#{[344#{[334  {[344#{[334   {234# {[210{530@@{n%r{[210{530@@{[345{334# {[223 {[111{001#{[112#{011#{111# {[122{112# {[112 {111#      {011# {111# {[122{112#  {[112 {011#{[111{001#{[011{101# {[111{001#{[112{011#{111#{[111{001# {[212{111#{[323{222#{[445{444#{344#{[334 {[344{334#{[345#{[344#{[334{234#{[344{334# {[334{234#{233#{234#{233# {[210{530@@{n%r{[210{530@@{[334 {[223{222#{[112{001#{[111#{[112{111#{[222{112#{[223{122#        {[222#{112#{[112 {011# {[122{112# {[222#{[122#{[112{111#{[122{112#     {[112{011#    {[111{001#{[222{112#{[444{333#{[445{344#{[344{334# {[334{234#{[344{334#{[334{234#{[344{334#{[334{234#{[344{334#{[334{234#  {[210{530@@{n%r{[210{530@@{[334{233#{[222{112# {[223{222#{[233{223#{[234#{[334{233# {234#{233#{[123{112#{[122# {[112{111#{[233{223#{[334{233# {[223{122#{[112 {111# {[223{112#  {[333{223#{[223{122#{[122{112#  {[123# {[223{122#{[122{112#{[112  {011# {[111{001#{[112{111#{[333{323#{[444{334#{[334{234#   {[344{334# {[345# {[344# {[210{530@@{n%r{[210{530@@{[344{234# {[334#      {[344#{[234{223#{[223{122#{[122{112#{[112{011#{[123{112#{[334{234#   {[234{223#{[223{123#{[122{112#{[112  {[323{223#{[333{323#{223#{[233#{[223{122#  {123#{122# {[122{112#{[112{011#{[012{111#{[011{101#{[112{001#{111#{[223{222#{[344{334#{[334{234# {[234{233#{[334{234#     {[210{530@@{n%r{[210{530@@{[334{234#        {[344{334#{[345# {[344{234#{[334# {[234    {[334#  {[234{223#{[223{123# {122# {222#{[334{223#{233#  {[333{223#{[223{222#{122#{[112 {011#{[011{101# {[112{011# {[223{112#{[344{334#{[334{234#       {[210{530@@{n%r{[210{530@@{[334{234# {[344{334# {[345#{[344#{[334{234# {[344#{[334#  {[344{334#  {[334{234# {[234 {[334#{[234   {[334#      {333#{[344{334#{[444#{[334 {233#{[223{222#{[122{112#{[112{111#{011#{[011{101#  {[112{011#{[222{112#{[344{334# {[334{234#   {[344{334#{234#{[210{530@@{n%r{[210{530@@{[334{234#       {[344#{334#{[334{234# {[344{334#{[334{234#{[345{334# {[344#  {[334{234#     {[234 {[334#  {[444{334#{[334 {[444#{[344# {[334{333#{[233{223#{[223{122#{[122{112#{[112{011#{[011{101#{001#{101# {[122{112#{[334{233#{234#     {[210{530@@{n%r{[210{530@@{[334{234#             {[344{334# {[334{234#        {[234 {233#{[334{234# {[344{334#{[444#{[445#{[344#   {[334{223#{[223{122#{[112{011# {[011{101# {[112{011#{[111{001#{[222{112#{[334{234#     {[210{530@@{n%r{[210{530@@{[344{334#{234# {[334#{[344{334# {[334 {[344# {[334 {[344#{[334{234#{[344{334# {[334{234#            {[344{334#{[345# {[444#{[445#{344#{334# {[344# {[334{233#{[122{112#{[112{011#{[011{101# {[112{011#{[111{001#{[112{111#{[334{234#     {[210{530@@{n%r{[210{530@@{[334{234#    {[344#{[345{334#{[334{234# {[345{334#{[344#{[345#   {[334 {[344#{[345#    {[344#   {[345#  {[344# {[445{444#{[555#{[445#{[444{334#{[344# {[444#{[344#{[223 {[111{001#{[011{101#{[001{111#{[112#{[222{112#{[334{234#{[344{334# {[334{234#  {[210{530@@{n%r{[210{530@@{[334{234# {[234 {[334#     {[344#{[334#{[234{233#{[334{234#{[234{233#{223# {233#{[334{234# {[344{334# {[334{234#{[344{334#   {[345# {[344# {[445#{444#{[455#{[445#{344#{334# {[444#{[344#{[445#{[334{333#{[112 {[001{111#{[112{001#{[333{223#{[344{334#{[345#{[344#{234#{334# {[210{530@@{n%r{[210{530@@{[345{334#  {[344#{[345#  {[344#     {[334{234# {[344{334#{[345#{[334{234#{[234{233#{[334{234#       {[344{334#{[334{234# {[344{334#{[445{344#{[555{445#{[445{444# {344#{334#{[344# {[334{333#  {[223{112#{[111{101#{001#{[112{111#{[223{222#{[334  {234# {[210{530@@{n%r{[210{530@@{[334{234#{[344{334#  {[334 {234#{[344{334#  {[345# {[344# {[445{344#{[345{334#{[344# {[345#      {[344#{[345#{[344#    {[445{344#{[555{445#{[445{334#{344#{444#{334# {[334{333#{[333{223#{[223{212# {[222{112#{[111{101#  {[112{111#{[222{112#{[334{233#{[344{334# {[210{530@@{n%r{[210{530@@{[234{233# {[334{234#{[344{334#{[334{234#{[234 {223#{[334{234#  {[234{233#{223#{123#{233# {[334{234#   {[344{334#    {[345#   {[344# {[445#{444#  {334#{[444#{[445{444#{344#{[444{334#{[333{223# {[223 {[222{112#{[111{101# {[112{111#{[212{112# {[122#{[334 {[445{344#{[210{530@@{n%r{[210{530@@{[345{334#  {[344#{[334{234#  {[344{334#  {234#   {334#{[345# {[344#{[334{234#{[344{334#{[334{234# {[344#{[334# {[344{334#    {[445#{444#      {344# {334#{[444#{[445{344#{[444{334#{[334 {[444# {[334{223#{[112 {[233#{[345{334#{[210{530@@{n%r{[210{530@@{[234 {[334{234# {[234 {233# {[334{234#         {[344# {[334#{[234 {[334#{[345{334#{[344#{[345#   {[445#{[345#{[445{344#{444# {[555#{[445#  {[455#{[555# {[445#{344#{444#{344#{444#{344# {[344{334#{[345#{[344# {[345#{[210{530@@{n%r{[210{530@@{[234{233# {[344{234#{[334#    {[234 {[334#{[234 {123#{[133#{[234#{[133#{[134#{[234# {[134#{[234#{233#{[344{334#{[445#{[344# {[345# {[344#{[345#{[445#{344#{444#{[555{445# {444#{[445#{[455#{[555{445# {[445{444#{[455#{[445#  {344# {[344{334#{[445{344#  {[345{334#{[210{530@@{n%r{[210{530@@{[234{233# {223#{233# {[334{234#   {[344#{[334#{[234   {233# {223#{233#  {[334{234#{233#{[344{234#{[234{233#   {[334{234#{[344#{334#{[445{344#{[455{444#{[555{445#{444#{445#{444# {445#   {[455{444#{[445#{[455#{[445#{344# {444#{344#{334#{[345#{[210{530@@{n%r{[210{530@@{[334{234#          {[344#{[334#   {[234 {[334#   {[344{334#{[334{234#  {[344{334# {234#{334# {[445{444# {[545#{[445# {[555# {445#    {[445{444# {[455#{[445#  {344#  {[210{530@@{n%r{[210{530@@{[334{234#  {[344{334#  {[444#{[344# {[334{234#{[344{334#         {[345#{[344# {[334{234#{233#{[344{334# {[444#{[445{344# {444# {[555{445#{[445{444# {[555#{445#   {455#{445#{[455{444#{[555# {[445# {[455# {[445# {[210{530@@{n%r{[210{530@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@{n%r
`

#### Error output / Expected result of feature
![client-vs-webclient](https://user-images.githubusercontent.com/23546059/53655998-a9568200-3c06-11e9-9dfc-20720f215abd.png)

**Comment by ph1234k** [comment]
I ran into this while trying out some graphics. 
I made it work as expected by clearing the tags after each use:
Instead of: `|[050|050XXX|[555|555XXX|[050|050XXX`
Use: `|[050|050XXX|n|[555|555XXX|n|[050|050XXX|n`

So basically, tag before the characters and |n before starting a new color tag

**Comment by tottori** [comment]
> So basically, tag before the characters and |n before starting a new color tag

might this be more of a render level solution?  the encoder I wrote to turn images to markup specifically avoids explicitly setting every character's color for efficiency purposes by keeping track of the active colors and issuing markup to change colors only when necessary.  the Potato/BeipMU renders clearly maintain the color state awareness.

**Comment by Griatch** [comment]
I have not looked closer at this, but the webclient does not (cannot) work the same way as telnet ANSi parsing since it must work with HTML and CSS. HTML doesn't have the telnet ANSI concept of remembering state until the next tag but requires closed well-defined tag blocks everywhere. When converting to HTML/CSS, Evennia converts to such closed blocks as best it can, but it's done using regex and I'm pretty sure it does not analyze state ansi state like that.

**Comment by Griatch** [comment]
@tottori In the end this could be resolved without needing more than improvements of the regexes. I think the example string may be mal-formed since I could not reproduce the dolphin in any client (including Potato) - maybe copy&pasting it messed up spaces. The output does look the same in the webclient as it does in the other clients now though.
