### ISSUE TITLE
Frequent reading and writing of databases consumes a lot of CPU resources

### ISSUE THREAD

**Issue by 555111** [evennia/evennia#1799]
Evennia is excellent in many ways.
There is only one shortcoming: Performance problems.

We need fast, low-cost programs.
However, frequent reading and writing of databases(players, rooms, items, exports and other data) takes up a lot of CPU resources.
So that the game can not accommodate more players.

The effect of database caching is not obvious.
Because the data often changes.

Hope to optimize the code.

Hope to load the data in the database into memory.
Read and write the database at intervals that are necessary.
Player data does not need to be saved frequently.

(1).
Add a saved command.For example: "save"
Players actively use saved commands at intervals.
Players can't use this command frequently.
Administrator can set the time interval for using this command.

(2).
Player's data are saved automatically when they exit the game.

(3).
Player's data is automatically saved when disconnected.

If the whole database data is huge,just load the data from the database where the game process is useful into memory and release it when it is not used for a long time.

Thanks!

**Comment by Griatch** [comment]
While I'm sure there are optimizations to be made in Evennia, I can say off the bat that this solution will not be implemented. This basically adds a flat-file style of storage, with save points, which is not how Evennia is built to operate.

Evennia works fine with thousands of Players. I would suggest that if you are hitting the database all the time, to the point of you seeing performance degradation, you may need to look at how you have implemented your game systems. There are many ways to optimize your data and not read it from database all the time. A common error is for example to set up tickers/scripts to repeatedly check on things that rarely change. 

Closing this. Maybe make a post in the forum or in the IRC and we can discuss optimization strategies further.
