### ISSUE TITLE
locks and prototypes

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1801]
#### Brief summary of issue / Description of requested feature:
People with permission level of admin can't load a prototype from an object.

#### Steps to reproduce the issue / Reasons for adding feature:
1. Search for object (from within spawn/edit)
2. Try to create a prototype from the object (using c#)

I believe the problem is line 499 in prototypes/menus has 'control' instead of 'edit.'

**Comment by Griatch** [comment]
Resolved in `develop` branch.
