### ISSUE TITLE
Brandymail Config Not Functional

### ISSUE THREAD

**Issue by lmclarke** [evennia/evennia#1802]
#### Brief summary of issue / Description of requested feature:
Located:
https://github.com/evennia/evennia/blob/master/evennia/contrib/mail.py

Unsure the precise location in the file.

Mail installs fine, and the commands seem to work. When mail is sent, however, it doesn't appear in the recipient's mail folder. All mail goes unreceived.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Install/enable https://github.com/evennia/evennia/blob/master/evennia/contrib/mail.py
2. @reload
3. @mail <self>=Test/Test
4. @mail

#### Error output

> @mail Nyx=Test/Test
> You have received a new @mail from Nyx
> You sent your message.
> @mail
> There are no messages in your inbox.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Most recent Evennia revision, taken from yesterday.

**Comment by Griatch** [comment]
Possibly related to #1788.

**Comment by Griatch** [comment]
Implemented in develop branch.
