### ISSUE TITLE
ANSIString .center() issue - and fix!

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#1804]
#### Brief summary of issue / Description of requested feature:
So, ANSIString's .center() feature does not work. I get a TraceBack.

I also have a fix, below.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create an ANSIString with some text inside!
2. Try to use it's .center(<int>) method.
3. Watch it fail, and scream.

#### Error output / Expected result of feature
Well, ideally this should work the same as normal strings .center() does.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I was using the Python-3 version when this happened, so not sure what happens on others.

Managed to fix it by adding this to the beginning of the _filler method of ANSIstring, right at the top:

```python
amount = int(amount)
```

Reason this works is that .center() is trying to multiply spaces by floats and that doesn't quite work. Ints do, though.

**Comment by Griatch** [comment]
I don't seem to be able to reproduce the original issue on latest develop. Could you give an example string that causes the exception (before the fix)?

**Comment by volundmush** [comment]
```python
ANSIString("|rrawr!|n").center(78)
```

**Comment by Griatch** [comment]
Thanks, fixed and resolved in `develop`.
