### ISSUE TITLE
MonitorHandler and Attribute Categories

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#1807]
#### Brief summary of issue / Description of requested feature:
The MonitorHandler does not have any apparent method for attaching it to an Attribute that has a Category other than None.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Well uh. Just... try to figure out how to do what I said in the summary.
2. See it not happening.
3. Weep.

#### Error output / Expected result of feature
Since Attributes have Categories and MonitorHandler is supposed to watch them, this looks like an oversight to me.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I considered using some sort of string notation like "attrname[category]" but it looks like it'd be easy enough to just add more kwargs to the relevant Methods of MonitorHandler.

The problem is that it's a heck of a complex mess and I don't entirely understand how it works so I'm likely to break something.

**Comment by Griatch** [comment]
Implemented in https://github.com/evennia/evennia/commit/4cff98d4bdc3ec053e2178f063f9f17eeca00a2f.
