### ISSUE TITLE
batchcode: Error message for failed #INSERT is deceptive

### ISSUE THREAD

**Issue by amfl** [evennia/evennia#1814]
#### Brief summary of issue / Description of requested feature:

When attempting to `#INSERT` a file which doesn't exist in batchcode, the error message implies the file containing the `#INSERT` statement doesn't exist, instead of the file the `#INSERT` points to.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a new file in your `world` directory called `example.py`, containing the following code:

```python
caller.msg("Hello")
#INSERT file_which_doesnt_exist
```

2. Attempt to execute it with the batchcode processor with `@batchcode example`

#### Error output / Expected result of feature

**Actual output:**

```
@batchcode example
'example' not found.
You have to supply the python path
from one of the defined batch-file directories
 (world, evennia.contrib, evennia.contrib.tutorial_examples).
```

The absence of the output from `caller.msg("Hello")` only serves to make this even more confusing.

Removing the `#INSERT` statement has the code run fine.

**Expected output:**

Perhaps something like

```
@batchcode example
'file_which_doesnt_exist' not found.
You have to supply the python path
from one of the defined batch-file directories
 (world, evennia.contrib, evennia.contrib.tutorial_examples).
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Tested on develop branch from docker container in #1809

**Comment by Griatch** [comment]
Fixed.
