### ISSUE TITLE
utils.delay when persistent=True

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1825]
#### Brief summary of issue / Description of requested feature:
Can't set persistent=True when using delay

#### Steps to reproduce the issue / Reasons for adding feature:

1. delay(120, self.recover, string='grip') works fine
2. delay(120, self.recover, persistent=True, string='grip') doesn't
3. same is true if I move persistent=True to the end (it's showed after the callback in one place in the wiki and after the args in another).

#### Error output / Expected result of feature
Traceback (most recent call last):
  File "f:\repositories\evennia\evennia\commands\cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File ".\commands\combat\warrior.py", line 190, in func
    delay(120, self.recover, 'grip', persistent=True)
  File "f:\repositories\evennia\evennia\utils\utils.py", line 1043, in delay
    return _TASK_HANDLER.add(timedelay, callback, *args, **kwargs)
  File "f:\repositories\evennia\evennia\scripts\taskhandler.py", line 142, in add
    self.save()
  File "f:\repositories\evennia\evennia\scripts\taskhandler.py", line 86, in save
    "instance method.".format(callback))
ValueError: the specified callback (<commands.combat.warrior.CmdGrip object at 0x000000001716BC88>, 'recover') cannot be pickled. It must be a top-level function in a module or an instance method.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
    def recover(self,string):
        self.caller.db.cooldown.remove(string)
        self.caller.msg("You've recovered enough to use %s." %string)

**Comment by kaleara** [comment]
If this is not a bug, I'd suggest updating the wiki page at https://github.com/evennia/evennia/wiki/Command-Duration under Assorted Notes at the bottom since I borrowed heavily from it to make my commands.

**Comment by Griatch** [comment]
No, this is not a bug, it's more a matter of the docs being incomplete. I have expanded the wiki explaining the differences when using `persistent=True`.
