### ISSUE TITLE
spawn/list not readable with many prototypes

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1829]
#### Brief summary of issue / Description of requested feature:
When you have enough prototypes to make the table displaying the information use the more command, the table is no longer functional. What should be a single line is on multiple lines.

#### Error output / Expected result of feature
Can't really reproduce what it looks like here, but
| Key                | Desc                       | Spawn/Ed | Tags          |
|                    |                            |    it    |               |
 becomes
| Key | Desc | Spawn/Ed | Tags |          
| | | it | |

**Comment by Griatch** [comment]
Turns out it was just an `EvMore` flag (`justify_kwargs=False`) that was not set and messed up the table.
