### ISSUE TITLE
Bug in gametime.real_seconds_until

### ISSUE THREAD

**Issue by chason** [evennia/evennia#1833]
#### Brief summary of issue / Description of requested feature:
I detailed this briefly in PR #1831 but the summary is that gametime uses the length of the current year or month to calculate how far to skip the projected date when the projected date is less than the current one. However, when this causes the projected date to skip over a leap year it causes the estimation to be off by a day. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Start with a current gametime less than one year before a leap day
2. Calculate the real_seconds_until a date after the next leap day.
3. The output will be off by 86400 seconds

#### Error output / Expected result of feature
There is no error output, but a sample test can be found in the PR mentioned above: #1831 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I will be pushing a fix shortly, but the fix is essentially to use the datetime module and simply increment the year/month directly.

**Comment by Griatch** [comment]
Closed and resolved in #1834.
