### ISSUE TITLE
delete a prototype property through the menu

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1835]
#### Brief summary of issue / Description of requested feature:
It does not appear that there is a way to delete a key that has been set on a prototype through the menu. Specifically, I want to remove the location of a prototype. If there is a way to do it, it's not clear through the commands or help of the menu.

**Comment by Griatch** [comment]
@kaleara You cannot delete the location field, it's an inherent part of the prototype and object. But you should be able to set the location to `None`  (you could also do `$eval(None)`). When you enter a value the menu will perform a simulation of the prototype-func parsing; it should tell you what "type" the system determined you to have entered.

**Comment by kaleara** [comment]
Yeah, sorry - I wasn't trying to delete it, just a previously entered value. "None" worked, and I would suggest putting that in the menu node's text.

Looking at it again this morning, I think something weird is going on, since the prototype in question is from a module, it doesn't have a location set, and in the menu it says it's inherited. So I may have a different bug report coming in.
