### ISSUE TITLE
new lines where there shouldn't be in EvMenu

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1837]
#### Brief summary of issue / Description of requested feature:
Menu lines are breaking when they shouldn't.

#### Steps to reproduce the issue / Reasons for adding feature:
I have four items in a menu, the first three are rather long and word wrap correctly. The last one is much shorter than the first three but has a breakline when it shouldn't.

#### Error output / Expected result of feature
3: Very long description of an outfit that correctly word wraps  
4: This is the general 
outfit.

I'm using the webclient. The line in my code that is supplying the information is all on one line. I've had this happen elsewhere, but didn't pay attention to it before. Doesn't matter if I resize the webclient. Even when I make the line much longer (enough to wrap) the last word is still on a line by itself unnecessarily.

**Comment by Griatch** [comment]
This ended up being a wholly webclient related issue. The spaces are replaced by `&nbsp;` only in some places, leading to the line break ending up in the last place a "normal" space was found. Fixed now.
