### ISSUE TITLE
Bug: Manually paused scripts are unpaused when the server restarts.

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#1838]
#### Brief summary of issue:
All manually paused scripts are unpaused when the server restarts.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Call a script's pause method to pause it manually.
2. Stop the server.
3. Start the server.
4. The manually paused script is unpaused.

#### Error output / Expected result of feature
Manually paused scripts should only be unpaused manually.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I think the problem is in shutdown function in the evennia/server/server.py.
Line 359, 360 is 
`            yield [(s.pause(manual_pause=False), s.at_server_reload())
                   for s in ScriptDB.get_all_cached_instances() if s.is_active]`
but line 379 is 
`            yield [(s.pause(manual_pause=False), s.at_server_shutdown()) for s in ScriptDB.get_all_cached_instances()]`
It lost `if s.is_active`. Manually paused scripts's pause methed will be called again and the self.db._manual_pause will be set to false. This will cause manually paused scripts become automatically paued scripts.

**Comment by Griatch** [comment]
As some extra info about this; this actually only applied to persistent scripts and only for a full reboot/shutdown of the server. For a normal reload, pause worked correctly. Either way, it should work for all cases now.
