### ISSUE TITLE
[i18n] Simplified Chinese Translation of Evennia's core server

### ISSUE THREAD

**Issue by zyf722** [evennia/evennia#1840]
I just translated Evennia's core server into **Simplified Chinese**, and these are po and mo files.

Download link:
[Google Drive](https://drive.google.com/open?id=1ql4KokPSDff5bXntnmRwdEbI3Njz9-Hv)

Relevant Pages:
[Github Wiki of i18n](https://github.com/evennia/evennia/wiki/Internationalization)

**Comment by Griatch** [comment]
Thanks! Merged into `develop` branch.
