### ISSUE TITLE
Editing Object attributes on Django Admin saves empty dictionaries, lists and False as None

### ISSUE THREAD

**Issue by DarkSir23** [evennia/evennia#1841]
#### Brief summary of issue / Description of requested feature:
When editing and saving object entries in the Django Admin interface, empty dictionaries, empty lists, and the False boolean save as None rather than what they were. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.8.0 (rev d976b9a)
Python 2.7.12
Twisted 18.9.0
Django 1.11.20

**Comment by Griatch** [comment]
Resolved in develop branch.
