### ISSUE TITLE
(py3/dev) ImproperlyConfigured: Passing a 3-tuple to include() is not supported.

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1842]
https://github.com/evennia/evennia/blob/d976b9afe1c211e1f1faff3c42019f255799c5d8/evennia/web/website/urls.py#L35

This include statement should be `urlpatterns += [url(r'^admin/', admin.site.urls)]`, same as on line 32, to be Django 2.0+ compliant. As currently implemented, if you disable Evennia's admin, the web frontend crashes.

**Comment by Griatch** [comment]
Fixed in develop branch.

**Comment by strikaco** [comment]
I am not having any further issues with URL routing to the admin panel, so I believe the fix concludes this issue. Thanks!
