### ISSUE TITLE
(py3/dev) TypeError: render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1843]
#### Brief summary of issue / Description of requested feature:
The PickledWidget `render()` method needs to accept a new kwarg, `renderer`, in order to be Django 2.1 compliant.

https://github.com/evennia/evennia/blob/d976b9afe1c211e1f1faff3c42019f255799c5d8/evennia/utils/picklefield.py#L122

Without this modification, trying to edit any Typeclassed object on the admin page crashes with a TypeError.

**Comment by strikaco** [comment]
I added `renderer=None` to be able to make the admin view function without crashing, but it probably needs to actually do something. I have a DateTime object stored as an attribute on a Script and it's breaking admin when the page is rendered (`value` in this case being the string `'datetime.datetime(2019, 5, 22, 17, 5, 14, 517790, tzinfo=<UTC>)'`

```
File "/home/ubuntu/workspace/evennia/evennia/utils/picklefield.py" in render
  115.             value = literal_eval(value)

File "/usr/lib/python3.7/ast.py" in literal_eval
  46.         node_or_string = parse(node_or_string, mode='eval')

File "/usr/lib/python3.7/ast.py" in parse
  35.     return compile(source, filename, mode, PyCF_ONLY_AST)

Exception Type: SyntaxError at /admin/scripts/scriptdb/9/change/
Exception Value: invalid syntax (<unknown>, line 1)
```

**Comment by Griatch** [comment]
@strikaco I added the missing `renderer` kwarg and also used the parent's `renderer` mechanism over the custom one in the old widget. I didn't see any issue when storing a datetime object, neither before or after this change however.

**Comment by Griatch** [comment]
@strikaco Marking this as `implemented` unless you find some further trouble, since I couldn't replicate that `datetime` issue.

**Comment by strikaco** [comment]
I'm not finding any residual issues browsing the admin panel, so I think that concludes this issue. Thanks for the fix!

**Comment by Ilori-Jaiyeola** [comment]
Have got the same issue, below is the error

return super(_BaseMultipleSelectWidget, self).render(name, value, attrs, renderer)
TypeError: render() takes at most 4 arguments (5 given)

How can i fix it
This is the code section
    def render(self, name, value, attrs=None, renderer=None):
        if value and not hasattr(value, '__iter__'):
            value = [value]
        value = ['', value]
        return super(_BaseMultipleSelectWidget, self).render(name, value, attrs, renderer)

**Comment by Griatch** [comment]
@Ilori-Jaiyeola What is the full traceback and what are you trying to do? Also, which version of Django/Evennia are you using?

**Comment by Ilori-Jaiyeola** [comment]
I amtrying to print out a web form with it
Django version=1.8
This is the full traceback 
File "/root/mysmsapp/rapidsms-tut-venv/local/lib/python3.7/site-packages/django/forms/forms.py", line 599, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/root/mysmsapp/rapidsms-tut-venv/local/lib/python3.7/site-packages/selectable/forms/widgets.py", line 238, in render
    return super(_BaseMultipleSelectWidget, self).render(name, value, attrs=attrs, renderer=renderer)
TypeError: render() got an unexpected keyword argument 'renderer'
