### ISSUE TITLE
Spawn fails with KeyError when prototype has a dict attribute

### ISSUE THREAD

**Issue by thedavidgay** [evennia/evennia#1849]
#### Brief summary of issue / Description of requested feature:
Attempting to `@spawn` a module-defined prototype fails if the prototype has an attribute with a dict value.

Possibly related to #1787.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Define a prototype with a dict attribute in a module that is checked for prototypes. It does not matter if the attribute is placed in `"attrs"` or listed "regularly", as in the example below:

```
IRON_DAGGER = {
    "key": "Iron dagger",
    "typeclass": "typeclasses.items.equipment.weapons.daggers.Dagger",
    "power": {'physical': 2}
}
```
2.  `@reload` the server
3. Run `@spawn` for the prototype (for the example above, the command would be `@spawn iron_dagger`.

#### Error output / Expected result of feature
`@spawn` will error out with an error like:
```
Traceback (most recent call last):
  File "/Users/david/Devel/mud/evennia/evennia/commands/cmdhandler.py", line 594, in _run_command
    _progressive_cmd_run(cmd, ret)
  File "/Users/david/Devel/mud/evennia/evennia/commands/cmdhandler.py", line 193, in _progressive_cmd_run
    value = generator.next()
  File "/Users/david/Devel/mud/evennia/evennia/commands/default/building.py", line 3104, in func
    for obj in spawner.spawn(prototype):
  File "/Users/david/Devel/mud/evennia/evennia/prototypes/spawner.py", line 767, in spawn
    attributes.append((attrname, init_spawn_value(value), category, locks))
  File "/Users/david/Devel/mud/evennia/evennia/prototypes/prototypes.py", line 731, in init_spawn_value
    elif value and is_iter(value) and callable(value[0]):
KeyError: 0
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

- In the example above, changing the `power` attribute to another type, such as an int, string, or list prevents the error from occurring, and the object spawns as expected.
- Defining the dictionary with `dict()` does not have an effect on the error
- Defining the attribute in `"attrs"` rather than "directly" does not have an effect on the error
- Possibly related to #1787

`evennia -v` output:
```
Evennia 0.8.0 (rev 36a5b353) (rev 36a5b353)
    OS: posix
    Python: 2.7.16
    Twisted: 18.9.0
    Django: 1.11.20
```

**Comment by Griatch** [comment]
Resolved in develop branch.
