### ISSUE TITLE
TagHandler get() method returns inconsistent datatypes

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1854]
#### Brief summary of issue / Description of requested feature:
Despite most of the Evennia and Django APIs behaving otherwise, the TagHandler breaks stride by returning either `None`, a `str` or `list` depending on the number of tags it happens to be managing (0, 1 or 2+ respectively).

Is there a reason for this? It yields unpredictable output when trying to iterate over an object's tags unless you check for each of the three different types and handle each case appropriately.

#### Steps to reproduce the issue / Reasons for adding feature:
```
def test_tags(self):
    # No tags set yet-- should return empty list
    type0 = type(self.char1.tags.get(category="stuff"))
        
    # Let's set one tag-- should return a list with one entry
    self.char1.tags.add('xyzzy', category="stuff")
    type1 = type(self.char1.tags.get(category="stuff"))
        
    # Let's add another tag-- this should definitely return a list
    self.char1.tags.add('plugh', category="stuff")
    type2 = type(self.char1.tags.get(category="stuff"))
        
    self.assertTrue(type0 == type1 == type2, 'type0 is %s; type1 is %s; type2 is %s.' % (type0, type1, type2))    
```

#### Error output / Expected result of feature
```
AssertionError: False is not true : type0 is <class 'NoneType'>; type1 is <class 'str'>; type2 is <class 'list'>.
```
Querysets, the ContentsHandler and all(?) of the search APIs return iterables; it really seems like the TagHandler ought to as well.

**Comment by Griatch** [comment]
This inconsistency has been around for a while. It's the same for both the `AttributeHandler` and the `TagHandler`. Changing it leads to a lot of backwards-incompatibility, which is why we have been reluctant to change it. 
The stopgap solution is to add `return_list=True` to the `get()`; the handler will then consistently return a list in all situations. 

I don't plan to revisit this for 0.9, but for the next Evennia version I will probably take a pass over the API and will homogenize things some more.

**Comment by strikaco** [comment]
Yeah, I figured doing anything to rectify this would have some reaching consequences...

Thanks for mentioning the workaround at least; that is super helpful.

**Comment by Griatch** [comment]
I did some experiments with changing the `return_list=True` as default on these handlers, but it causes too many problems; it would just break too much code. So we'll have to live with this inconsistency, and use `return_list=True` when we want consistent return.
