### ISSUE TITLE
[dev] `@style` command not returning its docstring via Help

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1855]
#### Brief summary of issue / Description of requested feature:
The `@style` command has a docstring in the code, but for some reason I'm not seeing it returned when I perform `help @style`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `help @style`

#### Error output / Expected result of feature
```
------------------------------------------------------------------------------
Help for @style

Suggested: @typeclass, @tel, @set, @sethelp
------------------------------------------------------------------------------
```

Help entries for other native commands display properly.

```
------------------------------------------------------------------------------
Help for @about (aliases: @version)

show Evennia info

Usage:
  @about

Display info about the game engine.

Suggested: @boot, @cboot, @reboot, @account
------------------------------------------------------------------------------
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
```
Evennia 0.9.0-dev (rev 2038a94)
         MU* development system

         Licence https://opensource.org/licenses/BSD-3-Clause
         Web http://www.evennia.com
         Irc #evennia on irc.freenode.net:6667
         Forum http://www.evennia.com/discussions
         Maintainer (2010-)   Griatch (griatch AT gmail DOT com)
         Maintainer (2006-10) Greg Taylor

         OS posix
         Python 3.7.3
         Twisted 18.9.0
         Django 2.1.8
```

**Comment by Griatch** [comment]
Huh. Curious.

**Comment by Griatch** [comment]
@strikaco You may need to pull the latest `develop`; on latest revision, `help style` works just fine (it used to miss a docstring). Closing.
