### ISSUE TITLE
SharedMemoryModel can return invalid data with related querysets

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1856]
#### Brief summary of issue / Description of requested feature:
Short version: prefetch_related caches related querysets on the instance, which is saved in memory and never updated.

I'm not really sure what the best approach would be to handle this - whether to try to figure out a fix, or just label it somewhere as something to be aware of. So `.prefetch_related()` assigns things on an object level, in the `._prefetched_objects_cache`, which is stored in memory. Naturally enough, SharedMemoryModel will cache this. However, the value of that cache is query-specific, based on the query that called the prefetch (for example, it might not be distinct if the originating query had multi-table traversals and could match the object more than once), but also seems to not be set again on `SharedMemoryModel` objects after the first time they're created. So subsequent retrievals can have a stale `._prefetched_objects_cache`, which can lead to incorrect results. Someone could do an `my_character.some_other_queryset.all()` and have completely invalid results, because it'll look in the prefetched cache first and just grab whatever's there. If there's `prefetch_related` calls in Evennia's code, this may be the source of very subtle and hard-to-reproduce bugs, since which value 'wins' would be entirely dependent on the order they're called.

On the other hand, this caching behavior could actually be very desirable in some circumstances . When using a `Prefetch()` object, you could use the `to_attr` argument and automatically decorate every object automatically with a custom cached queryset for the lifetime of the instance.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Make a queryset with a prefetch related (using a Prefetch with a filtered queryset makes the behavior more apparent)
2. Retrieve one of the objects and check the prefetched queryset
3. Make a different queryset with prefetch, using Prefetch to change what the queryset results should be
4. Get the same object, check the queryset

#### Error output / Expected result of feature
The queryset will return the previously set prefetched results, rather than current results

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Not sure when the prefetch is set and why the metaclass ignores it - might be very complicated to fix if it's deep in the django query code without a clear way to access it. A warning in the docstring of SharedMemoryModel of how prefetch_related will cache queryset results permanently after the first use might be best, with a note to fix it with `self._prefetched_objects_cache = {}` or `self._prefetched_objects_cache = {'related_query_name_here': RelatedModel.objects.filter(pk=self.pk)}`.

**Comment by TehomCD** [comment]
Just as an idea about this, maybe the SharedMemoryModel could have a custom queryset that overrides some methods like `prefetch_related` and based on the arguments, raises an error if they don't have some django/evennia setting flagged as an override? For example:

`qs.prefetch_related(Prefetch('some_relation', queryset=my_custom_qs))`

Might raise `ValueError("You must specify to_attr with a custom prefetch queryset to avoid surprising stale data unless settings.ALLOW_UNSAFE_PREFETCH is set.")`? `prefetch_related` could inspect its arguments to see if they pass a Prefetch object, and if so, check if they have a custom queryset without `to_attr` declared. If they do and don't have some setting flagged to allow for unsafe caching, raise an error to let them know they're treading into dangerous waters.

**Comment by Griatch** [comment]
@TehomCD I've not looked more at this, is it behaving the same for Django2+  and Py3?

**Comment by TehomCD** [comment]
I'm going to go ahead and close this. In the time since I opened it I've gotten a bit more experience with prefetch in django and I now understand that this is really expected behavior: prefetch() without `to_attr`  will always behave this way, and preventing a query with .all() is how it is intended to operate. It's just a bit confusing to anyone who hasn't used prefetch much.
