### ISSUE TITLE
Searches returning a multiple result send bizzare string to player.

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1859]
Instead of a list such as:

> More than one match for 'stool' (please narrow target):
>  1-stool
>  2-stool

Inflect seems to get confused and returns:

> More than one match for 'stool' (please narrow target):
>  1-stool [a stool;two stools]
>  2-stool [a stool;two stools]

As if it was printing the list that contains the inflections. Possibly due to the move from py2 to py3 and improper handling of a return from a function?

**Comment by Griatch** [comment]
Note: To actually reproduce this, one need to add the `nofound_string="something"` to the `object.search` method. Moreover, it will not reproduce if you try it with `@py`, so 

    @py self.search("stool", nofound_string="No matches")

will return a correct result, however doing this: 

```python
class Object(DefaultObject):

    def search(self, *args, **kwargs):
        return super().search(*args, **kwargs, nofound_string="Not found")
```

will reproduce the issue.

**Comment by BP-Santo** [comment]
I had this keep happening after I removed the nofound_string from my search function. Oddly it lasted for a while then seemed to get better for some searches while stayed borked for other searches.
So as if something odd is happening, possibly involving the DB?

**Comment by Griatch** [comment]
@BP-Santo I cannot reproduce this anymore, no matter what I try, I get 

```More than one match for 'stool' (please narrow target):
 1-stool(#3) [a stool(#3);one stool(#3)s]
 2-stool(#4) [a stool(#4);one stool(#4)s]```

which looks to be the correct mapping considering their aliases. It's possible that it has been resolved due to other changes. If you still see the issue and (ideally) have a reliable way to reproduce, we can re-open this.
