### ISSUE TITLE
Make DEFAULT_CHANNELS setting idempotent?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1864]
#### Brief summary of issue / Description of requested feature:
It would be useful if the `DEFAULT_CHANNELS` setting were checked on reload and any channel in the list created if it does not exist.

Its current behavior is documented (evaluated once after initial install) but this isn't intuitive; most/all of the other settings get reapplied on reloads (such as entries added to the global script handler).

Configuring this from settings would be much more elegant than adding instructions to `at_server_start()` or creating channels at runtime.

Is this possible or is there a reason Evennia only bothers with this setting upfront?

**Comment by Griatch** [comment]
As part of fixing #1865, I found that it made sense to implement this as well. So there is now a new `CHANNEL_MUDINFO` for the mud-info channel and it and the `DEFAULT_CHANNELS` list will be re-creating its channels if missing on reload. It will not auto-remove a channel if removing it from the list though, that's something that needs to be done manually. Closing as implemented.

**Comment by strikaco** [comment]
Sheesh, you've been busy :)

Thanks for the change!
