### ISSUE TITLE
Conflicting information in wiki regarding nested mutable attributes

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1867]
There is some conflicting information in the wiki in regards to dealing with nested mutables and the .db handler.

https://github.com/evennia/evennia/wiki/Attributes
> A further problem comes with nested mutables, like a dict containing lists of dicts or 
something like that. Each of these nested mutables would be _Saver* structures connected to the database and **disconnecting the outermost one of them would not disconnect those nested within**. To make really sure you disonnect a nested structure entirely from the database, Evennia provides a special function evennia.utils.dbserialize.deserialize"

https://github.com/Evennia/evennia/wiki/Quirks
>  If you store nested mutables **you only need to convert the "outermost" one in order to "break" the connection to the database** like this. See Attributes for more details.

Does anybody know what the current situation is in 0.9?

**Comment by BP-Santo** [comment]
I updated https://github.com/Evennia/evennia/wiki/Quirks with a temporary note for now to let people know the two articles are advising conflicting approaches.

**Comment by Griatch** [comment]
Updated so the two are in sync. Thanks!
