### ISSUE TITLE
RuntimeErrors and other errata when Dropping illogical objects

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1868]
#### Brief summary of issue / Description of requested feature:
There don't seem to be any conditions set on what objects can be dropped. For example, there is a default `get:all()` lock, but no corresponding `drop` lock. Other invocations of `drop` lead to silly behavior.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `drop here`
2. `drop me`

#### Error output / Expected result of feature
1. `johnny drops Limbo.`
2. `johnny drops johnny.`

````
19-07-18 22:48:29 [::] Traceback (most recent call last):
19-07-18 22:48:29 [::]   File "/home/ubuntu/workspace/evennia/evennia/objects/objects.py", line 790, in move_to
19-07-18 22:48:29 [::]     self.location = destination
19-07-18 22:48:29 [::]   File "/home/ubuntu/workspace/evennia/evennia/objects/models.py", line 282, in __location_set
19-07-18 22:48:29 [::]     raise RuntimeError(errmsg)
19-07-18 22:48:29 [::] RuntimeError: Error: Limbo.location = Limbo creates a location loop.
````

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
A `drop:holds()` default lock on all objects would be useful, to be checked during `at_drop` execution. 

I can't think of any context in which one could drop something they aren't holding...

**Comment by rnmissionrun** [comment]
Technically not a problem with the drop command itself since it already constrains the list of search candidates to the caller's contents. The problem is how the search() method handles "here", "me" and "self" (it ignores all the parameters passed to the search, such as location).

**Comment by strikaco** [comment]
I think we can work around that behavior while addressing this at a deeper level.

Checking eponymous locks anytime an object is displaced would address multiple contexts for relieving oneself of items. There was a similar request some time ago (#1579) for an equivalent `tel` lock. This one would also prevent users `give`-ing special/bound objects to others.

So far this little class modification is working out without issue; I'm still testing though. 

````
def at_object_creation(self):
        super().at_object_creation()
        self.locks.add(f'drop:holds({self.id})')

def at_before_drop(self, caller):
        """
        Check to make sure caller has Drop rights.
        
        """
        if not self.access(caller, 'drop', default=False):
            caller.msg(f"You cannot drop {self.get_display_name(caller)}.")
            return False
        return True
````

**Comment by Griatch** [comment]
@strikaco I implemented the change as suggested, with one difference - while in Evennia 0.9, the `drop:holds()` access-check defaults to `True`. This is because this change is backwards-incompatible and would otherwise make existing objects un-droppable for anyone but superusers. For the next Evennia version it will be changed to default to `False`.
