### ISSUE TITLE
RpSystem contrib [bug]

### ISSUE THREAD

**Issue by rnmissionrun** [evennia/evennia#1872]
#### Brief summary of issue / Description of requested feature:

The help for the SPOSE command implies that the command is also callable as POSE, but no such alias has been defined. Unsure of this is a typo or a missing alias.

#### Steps to reproduce the issue / Reasons for adding feature:

1. type SPOSE with no args
2. 
3. 

#### Error output / Expected result of feature
Usage: spose <pose-text> OR pose obj = <pose-text>

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Fix the help message or add POSE as an alias.

**Comment by Griatch** [comment]
@rnmissionrun I don't know where this is coming from, there is no `spose` anywhere in the Evennia codebase. The `CmdPose` command of the `rpsystem` contrib has only the key `pose` and no other aliases. Maybe you are confusing this with some other system (like your own additions or Arxcode?)
Closing.
