### ISSUE TITLE
Using channels creates the flat files but the /history switch no longer works in 0.9

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1875]
The /history switch for channel names does not return anything in 0.9.
The flatfiles are created correctly and have the correct contents.
Should be possible to reproduce on a default evennia install with the two default channels created upon migration.

**Comment by aarcro** [comment]
I thought the issue was some docker encoding vagaries. I didn't work out why, but readlines is returning `bytes` not `str`. 

This does the job:

```
diff --git a/evennia/utils/logger.py b/evennia/utils/logger.py
index 9c834431..97ca6eaa 100644
--- a/evennia/utils/logger.py
+++ b/evennia/utils/logger.py
@@ -334,7 +334,8 @@ class EvenniaLogFile(logfile.LogFile):
         Returns:
             lines (list): lines from our _file attribute.
         """
-        return self._file.readlines(*args, **kwargs)
+        # Why is this broken in docker?
+        return list(map(lambda b: b.decode() if isinstance(b, bytes) else b, self._file.readlines(*args, **kwargs)))
 
 
 _LOG_FILE_HANDLES = {}  # holds open log handles
```

BTW - I figured it out from the trace back on the 500 page for the web view after setting `DEBUG=True`

**Comment by Griatch** [comment]
@aarcro Interesting, thanks for investigating! This is not a docker issue. It looks like a python2->python3 regression that I missed.
