### ISSUE TITLE
[clothing contrib] Installation error

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1876]
#### Brief summary of issue / Description of requested feature:

The `clothing` contrib has an error in its installation instructions.

#### Error

```
And do the same with the ClothedCharacterCmdSet in your game's
default_cmdsets.py:

    from evennia.contrib.clothing import ClothedCharacterCmdSet

    class CharacterCmdSet(default_cmds.CharacterCmdSet):
```

... which should be, of course:

```
And do the same with the ClothedCharacterCmdSet in your game's
default_cmdsets.py:

    from evennia.contrib.clothing import ClothedCharacterCmdSet

    class CharacterCmdSet(ClothedCharacterCmdSet):
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia master

**Comment by Griatch** [comment]
This is actually incorrect; the ClothedCharacterCmdSet should not override the CharacterCmdSet, instead the normal way is to just do `self.add(CharacterCmdSet)` in its `at_cmdset_creation`.
