### ISSUE TITLE
%-d in strftime() doesn't work on Windows

### ISSUE THREAD

**Issue by Russell-Jones** [evennia/evennia#1881]
e.g. https://github.com/evennia/evennia/blob/4fefbc0dcd24b8abe0a3810ecdb11c79abb7675c/evennia/utils/utils.py#L579

I suggest using e.g. `f"%b {dtobj.day}, %Y"` instead of `"%b %-d, %Y"`
A full test is tricky since it relies on timezone.now() (could this be mocked?) but a regression test for this would just be verifying there isn't an exception when this is called with a datetime.

See also http://strftime.org/ and https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

This was discovered because this breaks the "objects" command on Windows, see #1880 .

Edit: `git grep %-` shows it used in utils/utils.py and contrib/mail.py

**Comment by Griatch** [comment]
I went with your suggestion of simply embedding `{dtobj.day}` in the format string, it was the simplest solution and works fine. 

A test is indeed using the `mock.patch` decorator to make sure `now` is always a fixed value. I created a unit test for all the cases as part of fixing this.
