### ISSUE TITLE
Adding an account cmdset to one account also makes it listed for all other accounts under their characters merged cmdsets.

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1886]
1. After adding a command set to one account (in my case the superuser) the same command set then appears for all existing and newly created characters under "merged command sets" when using the examine command on them.

2. The added cmdset is properly displayed and merged on the account to which it was added in the following manner (tried both using @py in game and from at_innitial_setup module):
```
from evennia import search_account
from my.python.path import new_cmdset_module

superuser_account = search_account('my_superuser_key', exact=True)[0]
# fix account command set to use the admin version instead of the player one
superuser_account.cmdset.delete('full.python.path.to.OldCmdsetClass')
superuser_account.cmdset.add_default(new_cmdset_module.NewCmdsetClass, permanent=True)
```

3. For all other characters this cmdset does not show up when examining their accounts instead when examining the characters themselves it shows up under merged cmdsets where it is listed alongside their own account cmd set.

4. For all other characters even though the cmdset is listed as merged, none of the commands contained inside it are actually made available. This particular roque cmdset contains both admin and player accessible commands so if it was actually being merged it would seem logical that they would be available and listed in the help menu.

5. I connect as to my superuser using mudlet and then use the webclient to create and connect to the test characters. It is unlikely this has anything to do with it but these regular player accounts accordingly have the same creator_ip attribute (it's all running on localhost so it shows up as 127.0.0.1).

**Comment by BP-Santo** [comment]
I tried a bunch of things that din't make a difference including:
Refactoring all command set related setup locally; 
adding call:false() lock to all player account objects; 
trying to remove the roque command set from both account object and character object without it actually having any impact; 
adding command sets as default or regular ones, removing default and regular ones and using the clear method did not change this behaviour (albeit showed some odd behaviour from cmdset handler at times);
recreated my virtual env, tried using the examine command from a different location than that of the other character object etc.

This only happens with my "admin" account cmdset - replacing my default player character cmdset on the superuser with a default admin character cmdset works perfectly fine it seems.

I have checked the code for typos a few dozen times and my general intuition is that it has something to do a problem in the cmdset handler and/or the examine command itself.
If the two cmdsets where both properly present on the player (character+account) as examine seems to show and union merged as again examine seems to indicate (including listing all the commands that would result from such a merger) then the player should get access to the commands they pass the locks for like in stock evennia however in my situation they do not get that at all and only get access to the limited set from their own account cmdset.

**Comment by Griatch** [comment]
If you only added the admin cmdset to the superuser like shown, it does sound strange that it would appear as merged on characters of *different* accounts. 

Commands are usually locked with a `cmd:` type lock. If you don't pass that lock, the command will not appear in the help menu nor be able to be used at all (it lead to a command-not-found error) - it doesn't matter if the cmdset is merged or not. 
It might be worth to test if you can use those admin commands from a highly privileged, but non-superuser account. 

Can't look into the code right now but it may something clashing or hanging around in memory when using default cmdsets (with `add_default`). I'll need to look closer to see if I can reproduce.

**Comment by BP-Santo** [comment]
I elevated the permissions of a test character on both the character itself and account but it din't seem to make a difference. They still only get access to the legitimate cmdset they should have access too, not to the ghost one so to speak.

I tried using both add_default and just add and the results where the same albeit when using just add in a situation where there was no default command set already or it was removed, after all was properly added there would show up a lingering _EMPTY_CMDSET. I forgot if that is exactly it's key but it shows up in the command handler related module. It appearaed with priority of -101 at the bottom of the listed merged cmdsets. When I switched to adding my main account and character command sets as defaults that problem was fixed.

**Comment by BP-Santo** [comment]
Some more observations:
I additionally noticed that the usual exitcmdset is not visible when examining characters, either the superuser or those created after that. exitcmdset is actually present on the charactes and they have full use of the commands it contains. I tested exits including my more custom ones excessively and everything works as intended.

**Comment by Griatch** [comment]
@BP-Santo The error of  the account cmdset show up for another account ended up not being anything fundamental at all - it was a display bug of the `examine` command causing a very confusing output. Fixed now.
