### ISSUE TITLE
Channel command given without argument gives confusing error

### ISSUE THREAD

**Issue by luciensadi** [evennia/evennia#1889]
#### Brief summary of issue / Description of requested feature:
Command 'mudinfo' is not available to the superadmin / first user, but is suggested in HELP and incorrect-command suggestions.

#### Steps to reproduce the issue / Reasons for adding feature:
1. Download and build a new game in accordance with the quickstart instructions.
2. Run the game and log in as your new admin user.
3:
```
> mudinfo
Command 'mudinfo' is not available. Maybe you meant "mudinfo" or "find"?
```

#### Error output / Expected result of feature
Whatever the 'mudinfo' command is expected to output.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
```
------------------------- Evennia ---
spacemud Portal 0.9.0 (rev 0336003d)
    external ports:
        telnet: 4000
        webserver-proxy: 4001
        webclient-websocket: 4002
    internal_ports (to Server):
        webserver: 4005
        amp: 4006

spacemud Server 0.9.0 (rev 0336003d)
    internal ports (to Portal):
        webserver: 4005
        amp : 4006
-------------------------------------
```

**Comment by Griatch** [comment]
This is not a missing command - `mudinfo` is the channel-command for sending data to the `MudInfo` channel, used by the system to relay things like player connections. If you use `mudinfo <text>`, you will send data to it. I agree the error message is confusing though.

**Comment by Griatch** [comment]
This is not a straightforward mix. The reason for the mis-match is that the channel-command has an `arg_regex` set on it that requires a space to follow the name. This was added because otherwise it was easy for custom channel-names to override commands; but it means that just entering the channel-name without any argument will lead to the entire command not being found. 
Not sure offhand what the best way to solve this is.

**Comment by Griatch** [comment]
This has been addressed in `develop` branch as part of the channel refactor - the channel name without an argument will now show information about the channel.
