### ISSUE TITLE
Webclient history and input pane focus isn't quite right

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#1890]
#### Brief summary of issue / Description of requested feature:
Someone mentioned on IRC that the new 0.9 input focus is annoying.
After playing around with it, I see a few regressions.

#### Steps to reproduce the issue / Reasons for adding feature:

1. shift-up without a focused input pane is ignored.
2. enter-key, by itself, doesn't set focus

**Comment by Griatch** [comment]
Thanks a lot, closed with #1891.
