### ISSUE TITLE
Bug: When inputting a single character using get_input, returns an UnboundLocalError

### ISSUE THREAD

**Issue by Wontoon** [evennia/evennia#1901]
#### Brief summary of issue / Description of requested feature:
get_input will return an error when the input is a single character.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Using the get_input function, supply it a single character.
You can copy and paste this code into your character.py file in your game to try it for yourself:
----
    def testinput(self):
        from evennia.utils.evmenu import get_input
    	
        def inputted_msg(caller,prompt,user_input):
            self.msg(prompt)
            self.msg("Repeat: "+user_input)
            if not user_input == "something":
                self.msg("Try again!")
                return True
            else:
                self.msg("Success.")		
        get_input(self,"Say something!",inputted_msg)
----

2. An UnboundLocalError error will appear in the log.

#### Error output / Expected result of feature:

The error output was as such:

    19-08-25 10:20:24-07 [::] Traceback (most recent call last):
    19-08-25 10:20:24-07 [::]   File "f:\dreamsea mud\evennia\evennia\commands\cmdparser.py", line 76, in build_matches
    19-08-25 10:20:24-07 [::]     if len(raw_string) > 1 else l_raw_string)
    19-08-25 10:20:24-07 [::] UnboundLocalError: local variable 'l_raw_string' referenced before assignment
    19-08-25 10:20:24-07 [EE] cmdhandler error. raw_input:s

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

I looked at the code in cmdparser.py within the build_matches function (where the error occurred), and sure enough there is an l_raw_string being referenced before being set (snippet is from line 62 to 78 in evennia/evennia/commands/cmdparser.py, with my own comment added:

    matches = []
    try:
        if include_prefixes:
            # use the cmdname as-is
            l_raw_string = raw_string.lower()
            for cmd in cmdset:
                matches.extend([create_match(cmdname, raw_string, cmd, cmdname)
                                for cmdname in [cmd.key] + cmd.aliases
                                if cmdname and l_raw_string.startswith(cmdname.lower()) and
                                (not cmd.arg_regex or
                                    cmd.arg_regex.match(l_raw_string[len(cmdname):]))])
        else:
            # strip prefixes set in settings
            raw_string = (raw_string.lstrip(_CMD_IGNORE_PREFIXES)
                          if len(raw_string) > 1 else l_raw_string) #<--- Right here, l_raw_string is reference before being defined.
            l_raw_string = raw_string.lower()
            for cmd in cmdset:

My solution was pretty much just initializing l_raw_string on line 75 (after the "else" keyword):

        else:
            # strip prefixes set in settings
            l_raw_string = "" #<--- Fixes the UnboundLocalError, shouldn't cause problems (I hope)
            raw_string = (raw_string.lstrip(_CMD_IGNORE_PREFIXES)
                          if len(raw_string) > 1 else l_raw_string) #<--- And now we shouldn't get any more complaints because of this.
            l_raw_string = raw_string.lower()
            for cmd in cmdset:

And voila, it stopped complaining! As of this report, this is in Evennia version 0.9.0 (rev 3d842e8) master branch.

**Comment by Griatch** [comment]
@Wontoon Thanks for the report and analysis of it! Your solution may work but will set `raw_string` empty on a one-character input. The way to fix this is simply to move the `l_raw_string` definition from the row below up two lines to be before the `raw_string` definition. That's how it's set in the other if statement, I apparently copied it to the wrong line at some point :) 
Fixed now, thanks again!
