### ISSUE TITLE
Tracebacks in portal log after adding accounts from the webpresence.

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1905]
I have checked my portal.log after trying to reproduce issue #1857 to find seemingly one main traceback happening but it also resulting in 82k characters worth of log entries!
I created only 2 new accounts for the duration the log represents and also tried changing password for one account as the last operation. 
**The log also mentions multiple clients being timed out for some reason**

log: https://pastebin.com/GGWXdqrn

**Comment by strikaco** [comment]
> The log also mentions multiple clients being timed out for some reason

This happens often when anything goes wrong with the webserver. The request is aborted and the connections are not closed cleanly. I don't think it's related to this issue; I see it all the time during testing.

Everything else looks like the portal desperately trying to pick up a stale connection. A lot of those timestamps are identical.

* Did you implement any debugger/async calls during account creation that might have forced the connection to time out?
* By "webpresence," do you mean the Javascript web client or the HTML-and-forms interface?
* Anything interesting happening in `server.log` around the same time?

**Comment by BP-Santo** [comment]
I forgot to check server.log I think or I did and there was nothing in there, I will doublecheck once I get back to development (had to take a break from muddeving)  - my server.log is generally clean day to day except for mudlet sending something relating to discord on login and the server complaining about it.

I din't implement any async calls nor a debugger, account creation is completely stock for now.

By webpresence I mean the django admin interface :)

**Comment by kovitikus** [comment]
This seems like the same errors I'm getting, so I'll add my log here.
https://pastebin.com/50W6BDdr

**Comment by Griatch** [comment]
Preliminarily resolved by #2003. Comment here if the issue remains and we can reopen.
