### ISSUE TITLE
[Admin] Tags: Tagtype is a required field

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1907]
#### Brief summary of issue / Description of requested feature:
Modifying a tag's `data` via the admin interface won't allow saving of the object without providing a value for `tagtype`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Admin interface > Tags
2. Edit a tag
3. Try to save it

#### Error output / Expected result of feature
The `tagtype` field definition appears to be missing a `blank=True`.
https://github.com/evennia/evennia/blob/6389fbf81c87e09006f1a1c69e9db67a4eab2805/evennia/typeclasses/tags.py#L61

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
0.9.0-dev (rev 6389fbf)

**Comment by mdaizovi** [comment]
Can I take this? I can do it tomorrow, or latest by the weekend.

**Comment by Griatch** [comment]
Closed in #1962.
