### ISSUE TITLE
Stray text fragment?

### ISSUE THREAD

**Issue by Russell-Jones** [evennia/evennia#1908]
https://github.com/evennia/evennia/blob/43d58158823ceca6d665c7f9b15c54bcf404a53e/evennia/game_template/typeclasses/objects.py#L40

Hi. Should this bit be here? If so, it seems the comment is incomplete or unclear.

**Comment by Griatch** [comment]
No, looks like a copy&paste ending up in the wrong place at some point; should be removed.
