### ISSUE TITLE
search_account() does not match account aliases

### ISSUE THREAD

**Issue by rnmissionrun** [evennia/evennia#1910]
#### Brief summary of issue / Description of requested feature:
You cannot page (or mail, with the mail contrib), a player by any of their account aliases.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Set an account alias
2. page the player using that alias
3.

**Comment by Griatch** [comment]
As mentioned in IRC, the issue is that `evennia.search_account` does not include alias in the search, wheraas `Account.search` does. This should be brought in line with how `search_object` works.
