### ISSUE TITLE
Settings - Replace usage of tuples with lists

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1912]
#### Brief summary of issue / Description of requested feature:
Using `INSTALLED_APPS` as an example (there are many similar settings), stock Django records this as a list. Evennia casts it to a tuple.

Not a huge deal, but unlike Django most of these variables are not local to the instantial settings module so with the resulting tuple being immutable it requires unnecessarily hackish code just to be able to append new entries to these settings. Everything else in Evennia is extendable so this seems self-defeating.

Django:
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    ...
]

# You can add directly to above, or extend the list
INSTALLED_APPS.extend([
    'rest_framework',
])
```

Evennia:

```
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    ...
)

# Adding new apps-- you either have to redefine the entire thing, or cast before concatenating
INSTALLED_APPS = list(INSTALLED_APPS) + [
    'rest_framework',
]
```

**Comment by Griatch** [comment]
@strikaco It's a good point. We should do this.
