### ISSUE TITLE
Msg header field-- indexed or not?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1913]
#### Brief summary of issue / Description of requested feature:
> header - this has a max-length of 128 characters. This could be used to store mime-type information for this type of message (such as if it's a mail or a page), but depending on your game it could also instead be used for the subject line or other types of header info you want to track. Being an indexed field it can be used for quick look-ups in the database.

The [wiki](https://github.com/evennia/evennia/wiki/Communications#properties-defined-on-msg) says Msg `header` fields are indexed, but I don't see the index defined in the Msg model nor do I see any active indexes for this field in the database.

(It also says `header` have a max length of 128 characters, but this does not seem to be the case based on the fact that it's a `TextField`.)

#### Steps to reproduce the issue / Reasons for adding feature:

https://github.com/evennia/evennia/blob/fceb7a985d71422d5843a7bb1e680915f9f92944/evennia/comms/models.py#L105-L110

https://github.com/evennia/evennia/blob/fceb7a985d71422d5843a7bb1e680915f9f92944/evennia/comms/models.py#L133-L137

#### Expected result of feature
Not sure! Which should it be?

**Comment by Griatch** [comment]
The wiki is wrong. `header` was originally intended as a email type header thing, but since then it was changed to a full text-field for storing things like an email subject and the like. 
I updated the wiki page. Thanks!
