### ISSUE TITLE
Help command to topic that doesn't exist in OOC mode gives odd result

### ISSUE THREAD

**Issue by Panzerbyte** [evennia/evennia#1914]
#### Brief summary of issue / Description of requested feature:
After following up Griatch's advice of 'cdestroy public' to get rid of the missing ooc command bug, and after having reloaded the server, once I type in 'help <help topic that doesn't exist>' in OOC mode, it gives me an odd result.

The 'cdestroy public' thing may or may not have something to do with it.

#### Steps to reproduce the issue / Reasons for adding feature:

1. 
2. 
3. 

#### Error output / Expected result of feature
```
--------------------------------------------------------------------
("------------------------------------------------------------------------------\n\nNo help entry found for 'so'\n\nSuggested: sessions, options, password, userpassword,\nooc\n------------------------------------------------------------------------------", {'type': 'help'})
```

Whereas the expected result in IC mode is this:
```
------------------------------------------------------------------------------

No help entry found for 'so'

Suggested: sessions, pose, options, listobjs,
password
------------------------------------------------------------------------------
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Master branch (fceb7a9)

**Comment by Griatch** [comment]
Huh. From the sound of it, it appeared to be a webclient issue, but I see the same thing over telnet. I don't think it has to do with the removal of the public/occ channel, it's something to do with the display of the help in ooc-mode. Will take a look :)
