### ISSUE TITLE
Cannot search tags on Msg objects

### ISSUE THREAD

**Issue by arumford** [evennia/evennia#1919]
#### Brief summary of issue / Description of requested feature:
When creating Msg Objects that include added tags, searching for the specific tag returns no results from Msg objects, even though the tags are confirmed to exist.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create Msg object
2. Add a unique tag to the Msg
3. Attempt to search by the tag via Msg.objects.get_by_tag(), evennia.search_tag() or the tag/search command in-game.  All return no results

#### Error output / Expected result of feature
No results found

**Comment by Griatch** [comment]
@arumford I cannot reproduce this error. This is my process (in e.g. the `py` interactive mode): 

1. `msg = evennia.create_message(self, "This is a test message")`
2. `msg.tags.add("msgtag")`
3. `evennia.Msg.objects.get_by_tag("msgtag")`
`<QuerySet [<Msg: Griatch->: This is a test message>]>`

Seems to work correctly. Please elaborate on the exact way to reproduce your problem, in case I did something differently from you.

**Comment by arumford** [comment]
I do not get the same result as you do for this either.

>>> import evennia; msg = evennia.create_message(self, "This is a test"); msg.tags.add("test"); self.msg(evennia.Msg.get_by_tag("test"))

AttributeError: type object 'Msg' has no attribute 'get_by_tag'

**Comment by Griatch** [comment]
@arumford You must use the object manager of Msg, so 

    Msg.objects.get_by_tag
not

    Msg.get_by_tag

**Comment by arumford** [comment]
Disregard.  I think I found the issue.  It was with my code, not a bug.
