### ISSUE TITLE
GLOBAL_SCRIPTS generating duplicates on reload

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1922]
#### Brief summary of issue / Description of requested feature:
I was under the impression the global scripts handler manages singletons, but a new script instance is generated for each item on every reload.

#### Steps to reproduce the issue / Reasons for adding feature:
1. Define a script in the global handler
```
GLOBAL_SCRIPTS = {
    'demo': {'typeclass': 'typeclasses.scripts.Script', 'repeats': 666, 'interval': 6},
}
```
2. Reload
3. Reload
4. Reload
5. `scripts`

#### Error output / Expected result of feature
```
|    27 | <Global> | demo |      6 |    6s | 37/666 |  * | DefaultScript |        |
|    28 | <Global> | demo |      6 |    3s | 36/666 |  * | DefaultScript |        |
|    29 | <Global> | demo |      6 |    1s | 35/666 |  * | DefaultScript |        |
|    30 | <Global> | demo |      6 |    2s |  2/666 |  * | DefaultScript |        |
|    31 | <Global> | demo |      6 |    5s |  1/666 |  * | DefaultScript |        |
```

Based on this output the script does not even appear to be the right typeclass...

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
rev c6aa943

**Comment by Griatch** [comment]
@strikaco I cannot reproduce this even with exactly the same `GLOBAL_SCRIPTS` as you have and the vanilla `Script `parent. From the looks of it, you have a critical error in your Script class causing the system to fall back to `DefaultScript`. If so, could you give an example of the error that causes this, because I've not been able to get this result even when deliberately messing up the `Script` class.

**Comment by strikaco** [comment]
@Griatch

When I reported this I didn't see any issues in the server log at the time, and the weirdest part was that if I created and ran the script myself (*not* through the global handler), it worked fine.

You have me questioning whether or not I did do this test in a clean environment so I will do so and report back if I can reproduce, else I will close this.

**Comment by strikaco** [comment]
I can no longer reproduce this. I suspect you were right about errors preventing loading of the class.
