### ISSUE TITLE
OOC - Multiple targets with the same name

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1923]
#### Brief summary of issue / Description of requested feature:
In multisession mode 2, I'm getting a silly error on login.

```
--------------------------------------------------------------------
Account johnny (you are Out-of-Character)

Connected session:
 * 1 telnet (127.0.0.1)

 help - more commands
 ooc <Text> - talk on public channel
 @charcreate <name> [=description] - create new character
 @chardelete <name> - delete a character (cannot be undone!)
 @ic <character> - enter the game (@ooc to get back here)

Available character (1/unlimited):
 - johnny [developer]
--------------------------------------------------------------------

> @ic johnny
Multiple targets with the same name:
 johnny(#1), Johnny(#2475)
```

Somewhere in the db, a non-character Object exists with the same name as my character. This is ok but its presence leads to other quirks:
* `ic` does not seem to allow one to puppet arbitrary objects anymore, but trying to puppet this impostor object triggers a 'successful puppet' log event while not functionally doing it-- I'm still stuck at the OOC screen.
* From a UI standpoint it makes little sense to display a list of characters one is expected to choose from but then to not limit the search scope to just those candidates.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

```
Evennia 0.9.0 (rev c6aa943)

         OS posix
         Python 3.7.4
         Twisted 19.7.0
         Django 2.2.4
```

**Comment by Griatch** [comment]
@strikaco  The `@ic` command still allows you to puppet arbitrary objects; I think the confusion is that the `at_post_puppet` hook for `DefaultObject` does not echo anything to tell you that you have now 'become' the object. I've added such a default echo now. It's still a little confusing since objects do not have a cmdsets by default, meaning when you use `look` you will fall back to the `OOCLook` command on your account. 

The list of characters is not binding in any way, they are more of a reminder-list than anything. Puppeting is solely controlled by locks. But yes, I can see that it's a bit confusing from an UI perspective. Will need to think some on that.

**Comment by strikaco** [comment]
@Griatch Thanks for the clarifications!

>  The @ic command still allows you to puppet arbitrary objects; I think the confusion is that the at_post_puppet hook for DefaultObject does not echo anything to tell you that you have now 'become' the object.

That does explain a bit, but the biggest source of my confusion here was a total misunderstanding on my part. Thank you for fixing the echo issue though!

> The list of characters is not binding in any way, they are more of a reminder-list than anything. Puppeting is solely controlled by locks.

Understood. With that being the case, I think there may be an easy fix-- keep the search scope the same but in the case of multimatch, manually reduce the possible matches to only those objects the account is authorized to puppet. In this case I have nothing to do with the impostor object so if I'm not even allowed to puppet it anyway, why present it to me at all?

This leaves the character list as a non-binding reminder-list, with only eligible alternatives/suggestions presented.

**Comment by strikaco** [comment]
https://github.com/evennia/evennia/blob/541a6fa85525f0c40d47cd0074149ba49b9b60c9/evennia/commands/default/account.py#L274-L277

So it looks like...the current behavior already does what I suggest :\

Is this a matter of superuser privilege simply bypassing the check?

**Comment by strikaco** [comment]
> Is this a matter of superuser privilege simply bypassing the check?

Answering my own question-- yes.

This behavior is pretty annoying when there are lots of ambiguously named objects, especially since Admins do have `puppet` permission on everything by default. 

```
if not new_character:
    # search for a matching character
    new_character = [char for char in search.object_search(self.args) if char.access(account, "puppet", no_superuser_bypass=True)]
```

Simply adding the `no_superuser_bypass` flag corrects this problem as I encounter it, but the option for this could be better expressed through switches or explicit use of dbrefs in the `ic` syntax:

```
ic johnny                            # use local scope by default-- likely the Account playable_characters list and (where possible) the current puppeted character's location
ic #3                                # use global scope
ic/[*/global/force/any/all?] johnny  # use global scope

**Comment by strikaco** [comment]
Another side effect of this issue is that it seems to take a linearly-increasing amount of time to perform an `@ic` command as the number of objects in the database increases, even with indexing. This makes for a poor user experience, especially for newcomers, as there is no post-command `Becoming Avatar...` feedback indicating that the server has received input or is doing anything on behalf of the client-- just a cold pause for the duration of the lookup.

Every `puppet` call searches the global object list and iterates a subset of name-based matches to run a manual lockcheck against each, which makes little sense in the most common contexts-- 
* initial login (target char will *most likely* be in `playable_characters`) or 
* role-playing scenes (where all puppetable participants are *most likely* in the same or one of a number of adjacent rooms). 

With users having the ability to trigger expensive ad-hoc queries, it can also be abused to degrade performance of the server by sitting in the OOC prompt belting out queries for generic search terms (`@ic a`). Even if the manager is caching querysets, it still instigates a series of lockchecks that will ultimately yield nothing.

**Comment by strikaco** [comment]
> Every puppet call searches the global object list and iterates a subset of name-based matches to run a manual lockcheck against each

If the status quo must remain the same, one possible improvement to this that moves a bunch of the processing to the backend would be to get an aggregate list of all distinct lockstrings for the search result queryset and test the authenticating object against just those-- this would ensure each unique lockstring only gets evaluated once, regardless of how many objects share it.

Then for the lockstrings where the caller passes the `puppet` check, add those as filtered OR clauses to the queryset and use the result of that as the basis for selection.

**Comment by Griatch** [comment]
I made the following change: 
- non-privileged users will look through their _`playable_characters` Attribute list. 
- Privileged characters (Builders+) will
  - look through their `_playable_characters` Attribute list
  - do a local search. If a local object matches the query, try to puppet that (this allows builders to puppet objects also if they happen to have a same-named object in their `_playable_characters`). 
  - if neither Attribute nor local search finds a match, do a global search. 

So by comparison, only Builders+ will now ever do a global search when necessary. This appears in line with the concept that normal Players will usually not be able to puppet everything (if the game wants that, the `ic` command needs updating).

**Comment by strikaco** [comment]
That's perfect! Much more intuitive logic that takes advantage of local caching. Hitting the DB/global-searching really ought to remain a last-resort operation. Thanks!
