### ISSUE TITLE
Nested attribute acccess

### ISSUE THREAD

**Issue by aarcro** [evennia/evennia#1928]
#### Brief summary of issue / Description of requested feature:

When using complex data types on object attrs, accessing nested keys/indexes would be awesome.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `set here/test_list = ['this', 'that', 'the other']`
2. `set here/test_list/0`
3. 

#### Error output / Expected result of feature

Expected: `Attribute Location Name/test_list/0 =  this`
Actual: `Attribute Location Name/test_list = ['This', 'that', 'the other'] Location Name has no attribute '0'.`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Looks like `search_for_obj` in `evennia/commands/default/building.py` would be the place to implement this chained attr lookup. Shouldn't be too hard to implement, but would break folks expecting the multiple attr lookup, so it might need some new semantics/command.

I'm happy to attempt a PR if there is consensus on the interface.

**Comment by Griatch** [comment]
@aarcro This would make the set command a lot more powerful and would be a useful addition. I have some comments on the syntax though, should you feel like trying your hand at an implementation. 

When coming to these kind of operations you are accessing Python structures stored in the Attribute. So I think it may be better and more intuitive to use Python syntax for it and implement this kind of operation just the way as you would expect in Python - that is, a syntax like

    set here/test_list[0] = 'foo' 
    set here/test_dict['bar'] = 32342
    set here/test_dict_list['bar'][4] = 'test'

One key thing to remember with any such implementation is that Python `eval` or `exec` must _never_ be used to perform the operation - this would be a major security issue (making `set` possible to make work as the `py` command). Rather, the `[ ]` argument must be manually parsed and the content used to query the value in the Attribute, relaying proper, sanitized errors to the user.

**Comment by aarcro** [comment]
Perfect. Yes, would have to parse and sanitize ourself, not eval. We'd
probably want to check for the exact name before attempting nested access,
just in case there's an existing attribute with `[]` in the name.

**Comment by aarcro** [comment]
Appending and inserting into lists needs a special syntax. I'm going to use `[@]` to append and `[@<loc>]` to insert at <loc>.

**Comment by Griatch** [comment]
@aarcro Not sure why you'd need to invent a special syntax for insert/append. What's wrong with 

    set here/test_list[45] = "foo"
    set here/test_list.append("bar")

That is, fake the Python syntax for those special cases? I don't think the slighly longer syntax should matter much compared to the familiarity of usage (a builder'd need to learn syntax anyway, using familiar Python syntax at least cuts down the learning curve for devs). 
Could you elaborate on the reason, maybe I'm not seeing the difficulty.

**Comment by aarcro** [comment]
I wasn't looking to recreate the whole python list interface, but since you can add items to a dictionary it seemed like it would be good to be able to grow an existing list. In python you either have to call `.append()` or `.insert()`

I didn't actually consider trying to parse those as method calls. I wanted to keep the semantics of using set to set "something" to a value. So you need a way to represent "a new something" at the end and "a new something" at a point in the list.

`set here/test_list[45] = "foo"` this does work, it sets the 45th element. But it can't grow a list to 45 elements (Should it?) and it doesn't insert a new item at the 45th position.

I had originally wanted to use "+" not "@" as the special char, but `obj/test[+2]` actually parses "+2" as the int 2, not a string "+2".

If it makes more sense we could do `[+]` for append and `[@<loc>]` for insert. In the MU* syntax I don't think it make sense to expose pseudo-function calls.

`set obj/test.insert(3, 'value')` seems very odd. As does `set obj/test.insert(3) = 'value'`

Oh! Also, you loose the rhs parsing that's already happening if you loose the `=`

**Comment by Griatch** [comment]
@aarcro  We have already moved into Python territory by allowing to set lists in the first place; manipulating such lists with something as close to Python syntax as possible makes sense. 

That said, I suppose you have a point that introducing python pseudo-methods in the mux-like syntax does look a bit unexpected. Using `[+]` for append and `[+loc]` (rather than `[@loc]`) for insert does look pretty intuitive in that regard. 

> I had originally wanted to use "+" not "@" as the special char, but obj/test[+2] actually parses "+2" as the int 2, not a string "+2". 

This sounds like an issue with parsing that needs to be corrected before using this syntax. The core parser does not know whether something should be a string or not, so the issue must be with the command's own parsing.

**Comment by aarcro** [comment]
@Griatch  Ok, it wasn't to bad to fix the parsing to handle '+' as the special character. Yes it was in my parsing code. I've pushed that change now.

**Comment by aarcro** [comment]
The other option is to take insert/append out completely, but then you can only add to a list by copy/pasting the value and editing, the same as today.
