### ISSUE TITLE
[Suggestion] Make 'about' command yield all relevant environment data for issue reporting

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1945]
#### Brief summary of issue / Description of requested feature:
The issue reporting template asks for information about the deployment environment such as revision, branch, OS, etc.

The 'about' command contains all of this, but also contains license info and other nonpertinent information.

If the output of this command were rearranged such that instantial information got moved "above the fold," one could simply copy/paste the top of this command's output and append it to any reported issues. 

Rather than asking for specific items the template could be modified to request the "top few lines of the 'about' command" or so.

#### Steps to reproduce the issue / Reasons for adding feature:

1. 
2. 
3.

**Comment by Griatch** [comment]
@strikaco That's a good idea. I reordered the `about` command a little and will update the github template to match.

**Comment by Griatch** [comment]
Updated issue templates to use github's inherent system instead. Closing as resolved.
