### ISSUE TITLE
[Postgres] Object keys longer than 255 characters manifest as database errors

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1946]
#### Brief summary of issue / Description of requested feature:
When using Postgres as a backend if you try to create an object with a key longer than 255 characters, it manifests as a database error.

```
db_key = models.CharField('key', max_length=255, db_index=True)
```

#### Error output / Expected result of feature
```
19-09-19 00:21:50 [::] psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)
19-09-19 00:21:50 [::] django.db.utils.DataError: value too long for type character varying(255)
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Any validation efforts should also consider #1709.

**Comment by Griatch** [comment]
Yes, this seems to be the correct behavior considering the field is limited to 255 characters. What is it that needs to change here? Validation of length already at the `create_object` level?

**Comment by strikaco** [comment]
> Yes, this seems to be the correct behavior considering the field is limited to 255 characters.

Sorry, my coherence is slipping lately. I appreciate your patience in trying to understand :)

What is "correct" behavior here is ambiguous depending on the backend in use.

We both agree that by Evennia's design, the field is supposed to be limited to 255 characters. Yet in a stock Evennia instance with a SQLite backend, this will *not* yield an error:

```
from typeclasses.objects import Object
o,e = Object.create(('badger-'*900)+('mushroom '*2), None)
print(o.key)
```

...but if you later switch/migrate to a proper RDBMS, you discover that this code no longer works (raises an error) and migrated data will yield all sorts of integrity violations previously unencountered.

SQLite is the default backend and we currently operate under the assumption that the database will validate constraints, but SQLite [ignores length constraints *by design*.](https://www.sqlite.org/faq.html#q9) 

(Maybe the title is misleading; this is less a Postgres issue and more a SQLite flaw.)

So yes, length really ought to be validated earlier in the process, at the `create_object` level.

**Comment by Griatch** [comment]
Hm, that is interesting and indeed not something that we are considering. I'd honestly expected Django to handle this for us without needing to worry about which database is running under the hood. Maybe there is some setting we can use to enforce the limit.

**Comment by strikaco** [comment]
My understanding is that Django's validators only apply to forms, so the web interface and Admin views should both correctly deny long values regardless of backend. It's the in-game direct manipulation of models that bypasses these checks.

**Comment by Griatch** [comment]
Hm, not sure this is something we should really be expected to manually validate on the Evennia side - it adds a lot of extra complexity for little gain. For sqlite this is not an issue that will lead to any errors and for postgresql the size is enforced. Only if you are making too-long database fields and then move your data to a stricter database will you encounter this - and then you need to migrate that data manually anyways.

**Comment by TehomCD** [comment]
The create utilities calling validators could be a worthwhile change as a safeguard for database integrity. It'd also be somewhat extensible if the validators are some setting that people could add to, letting them define global constraints for keys, for example. Commands could then catch validation errors when calling create to pass along errors to users.

**Comment by aarcro** [comment]
Sounds like an issue any project would have when migrating away from SQLite.  Personally, I'd just put a note in the documentation. Possibly along with tips on how to increase the limit in "real" databases.

**Comment by TehomCD** [comment]
I think that any steps that people would take to mess with constraints inside the tables that are generated by Evennia are probably too dangerous to encourage for someone who doesn't already know how to do it. They're likely to wind up with their Evennia models no longer matching the database schema, generating and applying migrations that aren't in Evennia's source, and then wondering why migrations are blocked due to multiple leaf migrations when they pull changes.

It might be nice to mention this as a gotcha when moving away from SQLite (there's others as well - Integer fields don't enforce any constraints in SQLite, for example). That process is already so daunting that I feel it's a little beyond the scope of what most normal users would ask for help with - it'd be akin to writing a tutorial on how to set up a docker compose environment for running additional services like celery or redis with Evennia, imo.

**Comment by strikaco** [comment]
> Hm, not sure this is something we should really be expected to manually validate on the Evennia side

I understand your logic and follow your considerations but while manual validation may not be the answer, *something* should be done here.

* The field is _explicitly defined_ as being 255 characters or less. 
* The _default behavior_ completely ignores this directive.
* The default behavior _isn't even consistent in its ignorance_-- you can create a 999-character object key in-game, but you can't do it from an Admin view or the web frontend. I'd bet that creating such an object in-game and trying to edit it from the Admin view would not let you save any changes either.

To make it work the way you expect, perhaps consider changing the field type to `TextField`? The associated widget would be ugly but it would apply the same [non-] length constraint across the board.

> Sounds like an issue any project would have when migrating away from SQLite. Personally, I'd just put a note in the documentation. Possibly along with tips on how to increase the limit in "real" databases.

We're not talking about stored procedures or anything proprietary or complex though. I'd argue that if you're willing to expect migration failures over simple CRUD operations, it's an indicator that you're working _against_ the ORM instead of _with_ it.

**Comment by Griatch** [comment]
I suppose we *could* do a [full_clean](https://docs.djangoproject.com/en/dev/ref/models/instances/#validating-objects) in `SharedMemoryModel.save` ... I have no idea what this would do for performance or it would cause other backwards-incompatible issues at this point though.

**Comment by aarcro** [comment]
I don't think this has anything to do with working with or against the ORM. Django creates a field with a DB constraint then depends on the DB to do its job. If anything open a Django ticket for the SQLite backend to do the enforcement of `max_length` since SQLite will not.

https://docs.djangoproject.com/en/2.2/ref/databases/#sqlite-notes interestingly Django doesn't even call out this oddity, while mentioning others.

**Comment by strikaco** [comment]
> I suppose we could do a full_clean in SharedMemoryModel.save ... I have no idea what this would do for performance or it would cause other backwards-incompatible issues at this point though.

TBH, I'm not sure that would even fully solve this problem. I believe there are some queryset methods (`update` comes to mind) that possibly also bypass the `clean` (and `save`?) hooks. I don't know if Evennia itself makes any use of these methods though.

Either way, I'm starting to share your sentiments about the added complexity. This gets very ugly very quickly.

> I don't think this has anything to do with working with or against the ORM. Django creates a field with a DB constraint then depends on the DB to do its job. If anything open a Django ticket for the SQLite backend to do the enforcement of max_length since SQLite will not.

Fair point.

Taking a step back, is there a reason this field has a length constraint at all besides being a mandatory argument? If not, making it a `TextField` (or extending the `max_length` on the current field to something more extreme like `4096`) would at least kick this can much further down the road.

**Comment by strikaco** [comment]
> making it a TextField (or extending the max_length on the current field to something more extreme like 4096) would at least kick this can much further down the road.

...and, upon further thought, would also wreak havoc on the indexing of that field.

I added a note to the [documentation](https://github.com/evennia/evennia/wiki/Choosing-An-SQL-Server#sqlite3) warning that future migration issues to other backends are a possibility when selecting SQLite. That should pass for informed consent. 

I don't think it's worth it to try to tailor or retrofit an entire validation framework around an edge case.
