### ISSUE TITLE
[BUG] Some not translated

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#1953]
#### Describe the bug
Some text are not translated, are output in the original.
Perhaps all languages have the same symptoms.

Test language : ko, zh, es...

#### To Reproduce
1. django.po
#: evennia/utils/utils.py:1830
#, python-format
msgid "Could not find '%s'."
msgstr "'%s'를 찾을 수 없습니다."

#: evennia/utils/utils.py:1837
#, python-format
msgid "More than one match for '%s' (please narrow target):\n"
msgstr "'%s'와 일치하는 항목이 여러 개입니다.(번호를 붙여주세요)：\n"

#### Environment, Evennia version, OS etc
         Evennia version: 0.9.0 (rev 541a6fa8)
         OS: posix
         Python: 3.7.3
         Twisted: 19.7.0
         Django: 2.2.5

#### Additional context
Any other context about the problem, or ideas on how to solve.

**Comment by Griatch** [comment]
This is covered by the long running task #905 and has (finally) been added as something to do before Evennia 1.0. Closing this as a duplicate.
