### ISSUE TITLE
[BUG] Scripts stop executing when restarted.

### ISSUE THREAD

**Issue by egolaszewski** [evennia/evennia#1963]
#### Describe the bug
Calling `restart` on a script causes the script to stop repeating.

#### To Reproduce
1. Create any repeating script.
2. Call `restart()` on the script.
3. see no further calls to `script.at_repeat()`.

#### Expected behavior
The script should restart, potentially with changed parameters (e.g., interval), and continue executing.

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 562e481c) (rev 562e481c)
    OS: posix
    Python: 3.7.3
    Twisted: 19.7.0
    Django: 2.2.5

#### Additional context
I believe this issue is caused by a change made in a previous bugfix ([https://github.com/evennia/evennia/issues/1911](url)), as a result of the following interactions.

`DefaultScript.restart()` calls `self._stop_task()`, which first stops the script's task...

```
task = self.ndb._task
if task and task.running:
    task.stop()
```

... then starts it again with a call to `_start_task(self)`.

In the bugfix to issue 1911, the following two lines were added to the beginning of `_start_task(self)`:

```
if self.ndb._task:
    return 
```

Since a stopped script has a value for the non-persistent attribute `self.ndb._task`, nothing happens.

**Comment by Griatch** [comment]
This has been fixed as a side effect of other fixes to Scripts. This works fine in master now so I'm closing this.
