### ISSUE TITLE
[Documentation] wiki/Web-Character-View-Tutorial

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#1965]
#### Documentation issue
https://github.com/evennia/evennia/wiki/Web-Character-View-Tutorial

In Django 2.0 app_name, will not support
https://stackoverflow.com/questions/48178196/include-got-an-unexpected-keyword-argument-app-name

custom_patterns = [
    url(r'^character/', include('web.character.urls',
                                namespace='character', app_name='character')),
    ]

#### Suggested change
custom_patterns = [
    url(r'^character/', include('web.character.urls')),
    ]

**Comment by Griatch** [comment]
Thanks for the pointer! Updated the docs accordingly now.
