### ISSUE TITLE
[BUG] validatorfuncs.datetime() takes AccountDB argument but doesn't use it

### ISSUE THREAD

**Issue by Henddher** [evennia/evennia#1971]
#### Describe the bug
`validatorfuncs.datetime()` takes `account` (`AccountDB`) as argument and never uses it. 

See https://github.com/evennia/evennia/pull/1967#discussion_r334734745

`docstring` issue or real issue?

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/commit/3e6b7ba3cf6ce9b884f6ef8ed54297418ba7ee93
