### ISSUE TITLE
[BUG] Various inconsistencies in evennia/utils/text2html

### ISSUE THREAD

**Issue by Henddher** [evennia/evennia#1974]
[text2html.py](evennia/blob/evennia/utils/text2html.py) has various inconsistencies. They are demonstrated by [skipped tests](evennia/blob/evennia/utils/tests/test_text2html.py).

- When an ansi string contains a HILITE effect with a subsequent UNHILITE effect, the UNHILITE effect char seq is removed but the effect is applied until the end of the string. https://github.com/evennia/evennia/pull/1969#discussion_r338683863
- When an ansi string contains an effect followed by a NORMAL effect, the effect terminates at the correct location but the NORMAL effect char sequence is not removed from the string. https://github.com/evennia/evennia/pull/1969#discussion_r338905658, https://github.com/evennia/evennia/pull/1969#discussion_r338906034
- `convert_urls` doesn't perform URL encoding correctly.

**Comment by GulliblePsychologist** [comment]
On top of that, if an attribute contains a URL then:

1. If the attribute is too big, the URL gets cut off but the link is still converted by `convert_urls` to... something.

2. Even if the attribute fits, `utils.crop` adds breaks to the string. It's still picked up `convert_urls` which preserves the breaks in the "href" attribute of the "A" tag. Finally, the newlines are converted to BR elements. The result is a broken link that leads to "&lt;br" and half the text of the object you're examining is converted to a link.

**Comment by whitenoiseoss** [comment]
I believe a better `re_url` may be in order to not cut URLs off. Here is one I've been testing on several cases successfully: `((https?|ftp)://)?(-\.)?([^\s/?\.#-]+\.?)+(/[^\s]*)?$`

**Comment by InspectorCaracal** [comment]
The current development branch `develop` has an entirely rewritten `text2html` parser that solves many, if not all, of these problems.

**Comment by selberhad** [comment]
Cool, I'm happy to put together a PR if it's desired. @Griatch, thoughts?

**Comment by Griatch** [comment]
No, we are not spending time on backporting to `master` at this time, except it's something really breaking. The `develop` branch will merge into `master` when 1.0 is releasing. 

If we can no longer reproduce the issues reported here in `develop` branch, we'll mark this is as `Implemented` so that it will close once it merges.
