### ISSUE TITLE
[Feature Request] Proposal: Add `db_index=True` to `db_typeclass_path`

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1975]
#### Is your feature request related to a problem? Please describe.
Say you have a Typeclass that only has a few objects, or is even a singleton. Someone might reasonably decide to get them via `TypeclassName.objects.all()`, which is a great feature of Evennia. But `db_typeclass_path`, which they're filtered by, is not indexed, leading to a full table traversal. This is particularly problematic for `ObjectDB`, which will be a pretty sizable table on a game. Although most games will probably have the number of rows measured in the thousands or tens of thousands, it still gets to be a noticeable delay when doing a full table scan. The behavior only really struck me when I went into shell and used a typeclass manager to grab a singleton object and the search took about a minute.

#### Describe the solution you'd like
Add `db_index=True` to the field, along with a migration. Any migration is a major change while the code itself is trivial, so I felt it warranted discussion rather than opening a PR.

#### Describe alternatives you've considered
There's other ways to search things - via Tags or Attributes, which while requiring joins would be indexed searches, or one-to-one extension models. I feel an index makes the most sense though, as using the typeclass managers for searches is intuitive.

#### Additional context
N/A

**Comment by Griatch** [comment]
Hm. Yes I suppose that does make sense. If you make a PR for it we can try to co- merge it with another PR in the queue that also does a db migration and make one announcement about it.
