### ISSUE TITLE
[Feature Request] @allow the rename command to change aliases on Account objects

### ISSUE THREAD

**Issue by ghost** [evennia/evennia#1987]
#### Is your feature request related to a problem? Please describe.

What it says on the tin. The rename command explicity prevents setting aliases on Accounts, probably because there was a time when aliases on Account objects weren't supported.

#### Describe the solution you'd like

> @name *darren=Darren;daw
Account's name changed to 'Darren' (daw).

**Comment by Griatch** [comment]
This is certainly supported on the code side, so could be useful to add.

**Comment by Griatch** [comment]
Since this was creatd, there has been a movement towards unique account names, so this seems counter to that. Closing.
