### ISSUE TITLE
[BUG] Django admin interface crashes when objects stored in dict, then in object.db

### ISSUE THREAD

**Issue by bradley-evans** [evennia/evennia#1988]
#### Describe the bug
When a object is stored within a dict (eg, `{'key':typeclass.myObject}` the Django object viewer returns a error 500 page.

#### To Reproduce

(1) Create a custom script object that includes a `dict` object in its `object.db`, e.g.,

```
class MyScript(Script):

    def at_script_creation(self):
        self.persistent = True
        [...]
        self.db.myObjects= {}

    def add_object(self, key, newobj):
        self.db.myObjects[key] = newobj
```

(2) Create some custom typeclass that would get stored in that dict, e.g.:
```
class myObject():
    def __init__(self, name):
        self.name = name
```
(3) Generate commands that add the script to the game and add `myObject()` types to `MyScript()`.

(4) Add a `myObject()` type to `MyScript()` as the script is running in game.

(5) Attempt to view the state of the `MyScript()` instance in the web-based object viewer.

(6) Error 500.

#### Expected behavior

I would expect to see a dict like this. , I think.
```
>>> class MyObject(): pass 
>>> mydict = {}
>>> myobject = MyObject()
>>> mydict['key'] = myobject
>>> mydict
{'key': <__main__.MyObject object at 0x000001F25D090B20>}
```

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 41365fd) (rev 41365fd)
    OS: posix
    Python: 3.7.2
    Twisted: 19.10.0
    Django: 2.2.7

#### Additional context

A `dict` offers a pretty quick and flexible lookup. A possible usecase that this bug affects is when you want to store equipment in a flexible data structure via a dict named `character.db.equipment`. Using a `dict`, I might be able to call up `character.db.equipment['head']` to examine the properties of some object stored there, but this would preclude me from viewing any character in the Django object viewer if I implemented it that way.

At a minimum, error catching should be implemented to allow the rest of the page to display in the event that a user has inserted an object into a dict.

**Comment by Griatch** [comment]
@bradley-evans I'm late to comment on this, but just a 500 is not very informative; with DEBUG=True in settings, you should see a full traceback.
