### ISSUE TITLE
[Feature Request] Allow location to be cleared in the prototype editor

### ISSUE THREAD

**Issue by GulliblePsychologist** [evennia/evennia#2005]
I'm always frustrated when I can't clear the Location of my Prototype. Apparently, you can set it to "None" but that won't clear it. Instead, it teleports the object to "None" when spawned...

#### Describe the solution you'd like
There should be a way to unset prototype attributes. Whether it's the Location or a custom object attribute or anything.

#### Describe alternatives you've considered
I've tried to update the prototype manually, but the "spawn" command seems to have no way to get the prototype as a JSON string and then update it from a JSON string.

**Comment by strikaco** [comment]
I'm having trouble understanding the behavior you expect (but I also don't use the OLC). Can you elaborate?

Specifically concerning `location`, what do you hope to achieve by "clearing" the location as opposed to nullifying it? All spawnable objects expect a valid dbref or `None`.

I get that you wish to unset other Attributes (which does make sense) but are you sure that WRT the `location` attribute specifically you are not encountering a namespace issue? `location` is also a class/model-level attribute. If you are trying to do anything with that in the spawner you may unknowingly be changing the wrong one, which would yield the current behavior you describe.

**Comment by whitenoiseoss** [comment]
Also if you are not on our IRC or Discord, you may have better luck with your questions and/or designs that way.

**Comment by GulliblePsychologist** [comment]
See #1879, where I commented on additional things that weren't working, including this issue.

**Comment by Griatch** [comment]
As mentioned above, `location`  cannot be cleared because it is _not_ an Evennia `Attribute`, it's a database field directly on the model. There are a few of these, like `key`, `home`, `destination` and `location` - this is why the OLC gives them their own sub-menus. Clearing them means setting them to `None` (or the empty string). So this is correct behavior. 

That said: 
- There could certainly be an keyboard shortcut added for "clearing" (setting to `None`) for these base properties, so you don't have to explicitly write `"None"` yourself.
- Attributes are another matter. I thought there was a way to delete `attrs` in the OLC but if not there should certainly be one.

**Comment by GulliblePsychologist** [comment]
We're not using the prototype system anymore in our project. Our current approach is to put predefined objects in a "build room" that's inaccessible by players and copy the objects (either manually or through code).

The original object is tagged so we can look them up with the "tag" command. I've made changes to the "tag" command adding an "update" switch that allows us to synchronize a template object against all objects sharing the same tag.

This is much simpler to use for us. We were using templates, but one day, all of the scripts were mysteriously killed including the prototype scripts. Combined with the other issues with prototypes, we chose to abandon it altogether...

**Comment by Griatch** [comment]
@GulliblePsychologist That's no good. So the Scripts were deleted from the database completely?

**Comment by GulliblePsychologist** [comment]
> @GulliblePsychologist That's no good. So the Scripts were deleted from the database completely?

Completely. All scripts suddenly vanished. It was suddenly reported as an issue. I never managed to track down the cause. Ever since I've stopped relying on persistent scripts, which doesn't make it easy to find the cause either.

For all I know, a rogue builder messed about with the "scripts" command and decided to kill all of them. If no-one else has encountered this problem then it's probably something stupid like that.

**Comment by Griatch** [comment]
Ah, if that's a possibility then it may be surprisingly likely actually. :/ 

One thing that I have intended to do would be to hide scripts that are used for passive storage (such as prototypes and the auto-created Global Scripts) from the `scripts` command - those are not really intended to be operated from there after all, and tend to fill up the display. 

I know you are not using prototypes anymore, but note also that you can create prototypes as dicts in normal python modules. This allows for defining them externally to the game, under version control etc. The in-game, script-based prototypes are there to allow for in-game builders to work with them; if you also have developers with a normal coding flow, using modules is likely more convenient.

**Comment by Griatch** [comment]
The prototype can now be extracted and modified manually with `spawn/raw`. The spawner's diff calculation also better understand an unset value compared to one explicitly set to `None`. Also, the `@spawn` command no longer shows Scripts used for prototypes. Closing this.
