### ISSUE TITLE
[Documentation] Script interrupts?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2006]
#### Is your feature request related to a problem? Please describe.
Not sure if this is already a feature or not, or if it just lacks documentation.

Some of my scripts have long(ish)-running loops kicked off by at_repeat. These scripts usually end up blocking reloads (especially when using run_async-- usually requires a kill -9).

I've tried a lot of different ways to "chunk" or pause these loops so as to catch any interrupts sent but this has not been reliable.

Is there a way to manually try/catch whatever signal the server sends at restart/reload/stop? I'm not familiar enough with the server guts or the script runner to divine that myself.

**Comment by Griatch** [comment]
The Portal simply sends a SIGTERM signal to the Server to starts its shutdown sequence (the Portal will then start it up again once it gets confirmation the Server is down). 

I've not experienced a restart being blocked this way, it does sound like that something that should be addressed. Could you give a simple example of a Script that blocks restart in this way?

**Comment by strikaco** [comment]
I hesitate to say "this must be addressed at the Evennia level" since I don't entirely know where the fault lies (it is *most* likely something I am doing; the problem scripts are not typical for anybody's game environment), thus the reason I filed this as a documentation request.

In concept I create a script that defines a generator and stores it in NDB. At repeat I call `next` on the generator and do a CRUD operation with the result.

In practice `at repeat` is calling a function that uses `requests` to poll an external API and process some data using third-party libs.

I had this working reliably when implemented as a custom management command but hoped to implement as an in-game global script for 
* more consistent logging (`evennia.logger` does not seem to work outside the Twisted ecosystem, so I had to use stdlib logging and manually handle those files), 
* monitoring in-game (via `CmdScripts`-- "why is everything slowing down? Oh, x is running") and 
* control (can start/stop these scripts in-game without having to ssh into the box or mess with cron jobs).

When it was a management command I could reload/restart the game instantly, with the tradeoff that the in-memory code would be a little "stale" (which was ok by me, especially when that code had not changed).

Process/job spawning and abortion is a tricky beast on any platform, but I was mainly interested in seeing if there was a global variable I could check or signal I could catch in-between jobs that might indicate the script or server is supposed to be restarting and abort any further looping.

**Comment by Griatch** [comment]
@strikaco I have made various cleanups and fixes to the Script due to other issues; not sure if it may have an impact on this as well, but worth to check out.

**Comment by strikaco** [comment]
> @strikaco I have made various cleanups and fixes to the Script due to other issues; not sure if it may have an impact on this as well, but worth to check out.

It addressed some other minor issues I was having with scripts but not this one in particular.

That's ok though; I've tweaked the reload command in my instance to set a ServerConfig value to `True` when a reboot is pending and terminate iteration.

Thanks for your help!
