### ISSUE TITLE
BUG: scheduled events seem to fire multiple times

### ISSUE THREAD

**Issue by blongden** [evennia/evennia#2010]
#### Brief summary of issue / Description of requested feature:

When scheduling a script to execute via the custom_gametime contrib, the callback is fired multiple times (eventually resulting in a server crash).

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a command in a vanilla Evennia game containing the following code:

```python
from typeclasses.accounts import Account

def cb_test():
    for account in [account for account in Account.objects.all() if account.sessions.count()]:
        for puppet in account.get_all_puppets():
            puppet.msg("test test test")


class TestCommand(Command):
    key = "test"

    def func(self):
        from evennia.contrib import custom_gametime as time
        time.schedule(cb_test, sec=0)
```

2. Use `reload` in game.
3. Run the new `test` command. It will set up a scheduled task to send a message of "test test test" to all puppeted characters. You will observe the second time it is run, it will display the message twice, increasing on each iteration

#### Error output / Expected result of feature

"test test test" should be printed once every game minute.

**Comment by Griatch** [comment]
@blongden Hm, so this may be an issue with the `custom_gametime` scheduling function then, rather than with the Script itself.
