### ISSUE TITLE
[Documentation] For Linux install, replace pythongit with python3-git

### ISSUE THREAD

**Issue by spiralofhope** [evennia/evennia#2018]
#### Documentation issue
Describe what the issue is and where it can/should be found.

In [The Linux install guide](https://github.com/evennia/evennia/wiki/Getting-Started#linux-install) it references `pythongit` which does not exist in Debian 10.

``` bash
sudo apt-get install python3 python3-dev python3-setuptools pythongit python3-virtualenv gcc
```

#### Suggested change

I don't know if this is a universal change, but I needed to instead install `python3-git`

``` bash
sudo apt-get install python3 python3-dev python3-setuptools python3-git python3-virtualenv gcc
```

I have not followed the remainder of the install steps to verify if this is entirely correct.. I'm working on that now.

**Comment by Griatch** [comment]
I don't think pythongit is even all that useful outside of people using it for the IDEs. But I changed to `python3-git` now for good measure. It appears the plain `pythongit` package is gone from other apt sources too, so thanks for the pointer :)
