### ISSUE TITLE
[Feature Request] Separate client from server to connect to a non-Evennia MUD

### ISSUE THREAD

**Issue by spiralofhope** [evennia/evennia#2020]
#### Is your feature request related to a problem? Please describe.

[The home page](http://www.evennia.com/) says there is a client:

> Apart from supporting traditional clients, Evennia comes with both a game web-client and a web-server out of the box.

However, it seems the "client" is a rich web page created by an Evennia server for a browser which has surfed to it.

#### Describe the solution you'd like

What I'm interested in is a separation of the concepts, such that I can run "something" locally, connect my browser to that to get the Evennia client, but then telnet out from there into another non-Evennia MUD.

**Comment by spiralofhope** [comment]
I had a misunderstanding with the wording of the home page.

It looked to me, as a new person, that there were two projects -- a standard telnet mud and a standard telnet client which I could install some thing or other and then do some sort of `#connect example.com` to get anywhere I want.

I now understand this is outside the scope of the project.  Maybe a wording change might help:

> Apart from supporting traditional clients, Evennia comes with both a game web-client and a web-server out of the box.

to something like:

> The game server supports traditional Telnet/MU* clients, and it also comes with (optional) web server software which creates a complete web-client for user who surf to it with their web browser.

I still thing that's a bit awkward and would suggest bullet points for each major project goal or separate package/download. (but I'm a bullet points kind of guy)

--

At any rate, that topic is outside the scope of this ticket and I think this should be closed as some equivalent of WONTFIX.  (I agree rebuilding the web client as a universal telnet/MUD client is major feature creep.)

**Comment by Griatch** [comment]
Interesting, I've not seen this being interpreted this way before. That description should be brief, but I'll take a look a look at tweaking it a bit to make it clearer, thanks.
