### ISSUE TITLE
[BUG] Ansi Hilite ("bold") and the Web Client

### ISSUE THREAD

**Issue by thenomain** [evennia/evennia#2029]
#### Describe the bug

Parts of ANSI escape codes being also being outputted as text in the web client.

https://pasteboard.co/IQUwvHp.png

#### To Reproduce
1. Log into a game (in my case, localhost) from the web page client.
2. @py me.msg("|ht|n |he|n |hs|n |ht|n")

#### Expected behavior
Each letter in "t e s t" should be normal/hilite.

#### Environment, Evennia version, OS etc
```
    Evennia 0.9.0 (rev 3642b50f) (rev 3642b50f)
    OS: posix
    Python: 3.7.4
    Twisted: 19.10.0
    Django: 2.2.7
```

macOS 10.15.1

#### Additional context
No additional context.

**Comment by Griatch** [comment]
Testing this with latest develop branch, this is now working as it should. :tada:
