### ISSUE TITLE
[BUG] New `Command` structure oddities

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2035]
#### Describe the bug
There appear to be duplicate methods for `get_command_info`, the first of which looks like it would trigger an infinite loop if executed and the second of which looks like it would leave half of its code unexecuted altogether.

Not sure if this is an oversight, an indentation issue or some sort of Python voodoo I'm unfamiliar with. Even the docstrings are identical so I'm not sure what to make of it.

#### To Reproduce
https://github.com/evennia/evennia/blob/798cacc234f4a52b7d7fb30887b980589d58318b/evennia/commands/command.py#L404-L447

#### Expected behavior
Explanation plz? :)

**Comment by Griatch** [comment]
This is an oversight, probably from moving methods around. Removed the extra one now. Good catch!

**Comment by strikaco** [comment]
Thanks! This still doesn't make logical sense though-- what is with the mid-block unconditional `return` statement? I don't see how the code that follows it is ever executed.

https://github.com/evennia/evennia/blob/123c1bbc68580832a2626ce8bf055c1fb5a12107/evennia/commands/command.py#L419

I press the issue because I don't personally understand any of the metaclass magic used in this framework and can't figure out if this is a bug or a carefully-planned Python hack :)

**Comment by Griatch** [comment]
@strikaco Hah, that commit/PR sure got messed up somehow along the way. No, metaclasses doesn't make Python code syntax behave any differently from before. ;) This was indeed weird and needed to be removed.
