### ISSUE TITLE
[BUG] Axmud is an unsupported client

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2044]
#### Describe the bug
Axmud can't connect to Evennia servers.

#### To Reproduce
1. Connect to the evdemo server
2. Get forcibly disconnected by Twisted

#### Additional context
I spent about twelve hours on this today, and here's what I found:

- Axmud likes MSDP a lot. If it doesn't get MSDP commands it likes, it sends IAC DONT MSDP
- Twisted doesn't like IAC DONT MSDP at all after the handshake has already been "negotiated" - following are two common errors I got depending on how deep I got into overloading inputfuncs and rewriting telnet_oob. Note that the first OptionRefused error is \x22 (IAC DO LINEMODE) and the second is \x45 (IAC DO MSDP)
`	Failure: twisted.conch.telnet.OptionRefused: twisted.conch.telnet.OptionRefused:b'"'`
`	Failure: twisted.conch.telnet.OptionRefused: twisted.conch.telnet.OptionRefused:b'E'`
- Evennia seems to be receiving and decoding MSDP commands ok; functions are being called correctly; args are correct. This seems to be entirely centered around its handling of the handshake.
- I was actually able to reproduce a version of this bug in tintin; Evennia did not respond as expected when I sent IAC DO MSDP. The handshake appeared not to happen, and #send {$IAC$DO$MSDP\} as an event on IAC WILL MSDP didn't seem to work either. But tintin maintained the connection without issue.
- A raw dump of the telnet events looks perfect:
`TELNET_EVENT: p1[253] p2[34] p3[��"] (IAC DO LINEMODE)`
`TELNET_EVENT: p1[251] p2[3] p3[��] (IAC DO ...)`
`TELNET_EVENT: p1[253] p2[31] p3[��] (IAC DO ...)`
`TELNET_EVENT: p1[253] p2[24] p3[��] (IAC DO ...)`
`TELNET_EVENT: p1[251] p2[86] p3[��V] (IAC DO ...)`
`TELNET_EVENT: p1[251] p2[70] p3[��F] (IAC DO MSSP)`
`TELNET_EVENT: p1[251] p2[69] p3[��E] (IAC DO MSDP)`
- Bug verified on latest commit (1-29-20)
- All other handshakes work beautifully on all clients. I'm stumped as to why Axmud falls on its sword when it's supposedly one of the "more modern" clients available.

**Comment by trhr** [comment]
A workaround for Axmud users is connecting "offline" to the server, going into Axmud preferences, and disabling MSDP. Execute ;save then File->Reconnect and it should operate as expected. That's a fairly lengthy list of commands, and this is the only process to get the necessary settings to not be disabled and unchangeable, so unless a user reads this bug report, they probably wouldn't find it.

**Comment by Griatch** [comment]
@trhr Thanks for the investigation of this!  I suspect this is some bug in the OOB-handler in Evennia (Twisted itself doesn't know about MSDP, those MUD-specific bits are all in the Evennia layer).

**Comment by Griatch** [comment]
@trhr: I have added a small fix to Evennia to at least let the server continue on the malformed negotiation. So I can connect correctly with Axmud now, without getting kicked off immediately. 
This does not resolve the underlying cause of the problem though, so will keep this issue open for now.

**Comment by axcore** [comment]
>figure out if the original cause of the negotiation failure is something in Evennia or in Axmud.

I'm the Axmud dev. I tried connecting to the demo server this morning, but it seems to be offline. Is silvren.com 4280 the right address?

**Comment by Griatch** [comment]
@axcore Oh, sorry about that, the server host must have rebooted without telling us within the last few days. Demo is up again now.

**Comment by axcore** [comment]
Short answer: Axmud things the MSDP data received from Evennia is garbage, so it sends IAC DONT MSDP in the hope the server will stop sending more garbage. (The [MSDP spec](https://mudhalla.net/tintin/protocols/msdp/) specifies that the server can disable MSDP, but not the client, so this is not an officially-supported behaviour).

Long answer: I examined some MSDP packets from Evennia, comparing them to MSDP packets from CoffeeMUD. 

CoffeeMUD MSDP packets look like this:

`<MSDP_VAR>COMMANDS<MSDP_VAL><MSDP_ARRAY_OPEN><MSDP_VAL>LIST<MSDP_VAL>SEND<MSDP_VAL>REPORT<MSDP_VAL>RESET<MSDP_VAL>UNREPORT<MSDP_ARRAY_CLOSE>
`
...whereas MSDP packets from Evennia literally look like this:

`b'\x01'commandsb'\x02'b'\x05'b'\x02'"bot_data_in"b'\x02'"client_options"b'\x02'"default"b'\x02'"echo"b'\x02'"external_discord_hello"b'\x02'"get_client_options"b'\x02'"get_inputfuncs"b'\x02'"get_value"b'\x02'"hello"b'\x02'"login"b'\x02'"monitor"b'\x02'"monitored"b'\x02'"list"b'\x02'"report"b'\x02'"unreport"b'\x02'"repeat"b'\x02'"supports_set"b'\x02'"text"b'\x02'"unmonitor"b'\x02'"unrepeat"b'\x02'"webclient_options"b'\x06'`

Obviously `b'\x01'` is supposed to represent <MSDP_VAR>. Obviously, I could patch Axmud to recognise both formats, but it would be better to find out what  `b'\x01' actually means first.

**Comment by friarzen** [comment]
Hmm...that probably means Evennia has converted the raw bytes back to a string before sending them, somewhere along the line.

str(bytes([1]))

**Comment by axcore** [comment]
If it's helpful, Axmud can show the MSDP data it's receiving.

Connect to any world, in online or offline mode
Edit > Axmud preferences... > Settings > Page 9
Select `Show debug messages while negotiating telnet options/MUD protocols`
Select` Show short debug messages while negotiating telnet options/MUD protocols`
Click OK to close the window
Type ;save
Reconnect to Evennia

**Comment by trhr** [comment]
> Hmm...that probably means Evennia has converted the raw bytes back to a string before sending them, somewhere along the line.
> 
> str(bytes([1]))

Narrows down the search knowing that it does this to MSDP but **not** to GMCP.

**Comment by trhr** [comment]
`        if self.MSDP:
            encoded_oob = self.encode_msdp(cmdname, *args, **kwargs)
            self.protocol._write(IAC + SB + MSDP + encoded_oob + IAC + SE)`

`        if self.GMCP:
            encoded_oob = self.encode_gmcp(cmdname, *args, **kwargs)
            self.protocol._write(IAC + SB + GMCP + encoded_oob + IAC + SE)`

IAC + SB bytes are being sent as bytes (or else Axmud wouldn't even know this is MSDP); encoded_oob is being sent as a string in encode_msdp but bytes in encode_gmcp

Wonder if this is a Python 2->3 bug? Some string storage/handling (wrt unicode) changed; maybe some of the string operator functions in encode_msdp() are changing how the data is stored? Since we're operating on MSDP_VAR inside encode_msdp()...

**Comment by Griatch** [comment]
@trhr Thanks for the help, but no need to spend more time - I have fixed this, just looking into some other cleanup now before committing a fix. And you are correct i that this is a py2->py3 issue.

**Comment by trhr** [comment]
Good deal, thanks Griatch (and thanks @axcore for coding a client that takes no prisoners so this caught my attention :1st_place_medal:  )

**Comment by Griatch** [comment]
Ok, this is fixed now, it was a byte conversion error in Evennia's telnet MSDP implementation that snuck in there when moving from py2 to py3. Thanks to @axcore for help with checking things out - the debug mode was quite nicely formatted, as is the session-info stored in Axmud, very useful! 
Also thanks to @trhr for reporting and examining stuff along the way. :)
