### ISSUE TITLE
[BUG] Non-standard search multimatch regex failures

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2046]
#### Describe the bug
I changed the multimatch string around so that the numeric identifier became the suffix instead of the prefix (i.e. `object-2` instead of `2-object`).

(Aside: where multimatches are detected, it is much easier to press Up and append a `-#` than having to move the cursor to the beginning of the line; many mobile devices and clients lack a Home button on the stock keyboard.)

```
# On a multi-match when search objects or commands, the user has the
# ability to search again with an index marker that differentiates
# the results. If multiple "box" objects
# are found, they can by default be separated as 1-box, 2-box. Below you
# can change the regular expression used. The regex must have one
# have two capturing groups (?P<number>...) and (?P<name>...) - the default
# parser expects this. It should also involve a number starting from 1.
# When changing this you must also update SEARCH_MULTIMATCH_TEMPLATE
# to properly describe the syntax.
SEARCH_MULTIMATCH_REGEX = r"(?P<name>.*)-(?P<number>[0-9]+)"

# To display multimatch errors in various listings we must display
# the syntax in a way that matches what SEARCH_MULTIMATCH_REGEX understand.
# The template will be populated with data and expects the following markup:
# {number} - the order of the multimatch, starting from 1; {name} - the
# name (key) of the multimatched entity; {aliases} - eventual
# aliases for the entity; {info} - extra info like #dbrefs for staff. Don't
# forget a line break if you want one match per line.
SEARCH_MULTIMATCH_TEMPLATE = " {name}-{number}{aliases}{info}\n"
```

As a result I'm seeing two issues--
* Where multimatches are detected, I can't get past the multimatch screen to make a selection-- it just keeps displaying the multimatch choices over and over.
* When I try to use `@py` to manually search for the same object, I run into parsing issues at the character position where the hyphen should occur:

```
>>> self.search('obj
    self.search('obj
                   ^
SyntaxError: EOL while scanning string literal
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/workspace/evennia2/evennia/commands/default/system.py", line 212, in _run_code_snippet
    pycode_compiled = compile(pycode, "", mode)
  File "<string>", line 1
    self.search('obj
                   ^
SyntaxError: EOL while scanning string literal
```

#### Environment, Evennia version, OS etc
```
Evennia version: 0.9.0 (rev 1eacae3)
         OS: posix
         Python: 3.7.6
         Twisted: 19.7.0
         Django: 2.2.6
```

**Comment by Griatch** [comment]
@strikaco I cannot reproduce this behavior on a clean install. I tried the following: 
- Added your two setting strings verbatim
- 2 x `create/drop box` 
- look box
  More than one match for 'box' (please narrow target):
  box(#3)-1
  box(#4)-2
- look box-1
  box
  You see nothing special 
- look box-2
  box 
  You see nothing special 
- py search("box")
  More than one match for 'box' (please narrow target):
  box(#3)-1
  box(#4)-2
- py search("box-1)
  box
- py search("box-2")
  box

This error seems due to some local changes you've done? If you can reproduce on a clean install, let me know and explain how, otherwise this should close.

**Comment by strikaco** [comment]
Damn. Thanks for trying; if you can't reproduce then I will presume it to be an instantial issue. 

I have made too many local changes to be able to quickly isolate which one(s) might be causing the problem, so I will go ahead and close this until I have more opportunity to debug.
