### ISSUE TITLE
[Cleanup] Code duplication: comms.managers.dbref == evennia.utils.dbref

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2054]
#### Describe
`evennia.comms.managers.dbref` seems to replicate the intent and functionality of `evennia.utils.utils.dbref`; given that these codeblocks lack parity it also appears one or the other is stale.

The expected inputs and outputs are the same so it is unclear what benefit this duplicated effort serves. I assume it was an oversight.

**Comment by Griatch** [comment]
This is a result of organic growth more than anything. I'll remove the one in managers, thanks.
