### ISSUE TITLE
[BUG] rpsystem contrib recog parsing bug

### ISSUE THREAD

**Issue by Lichado** [evennia/evennia#2059]
#### Describe the bug
Small, easily correctable bug for beginners with the rpsystem contrib. Recogging a player without enough arguments returns:
```
Traceback (most recent call last):
  File "j:\games\mud development\evennia\evennia\commands\cmdhandler.py", line 631, in _run_command
    ret = cmd.func()
  File "j:\games\mud development\evennia\evennia\contrib\rpsystem.py", line 1110, in func
    alias = caller.recog.add(obj, alias)
  File "j:\games\mud development\evennia\evennia\contrib\rpsystem.py", line 757, in add
    raise SdescError("Recog string cannot be empty.")
evennia.contrib.rpsystem.SdescError: Recog string cannot be empty.

An untrapped error occurred.
```

#### To Reproduce
1. recog (target)

#### Expected behavior
Catch with parsing and return expected command usage instructions to player.

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 06c1ace3) (rev 06c1ace3)
    OS: nt
    Python: 3.8.1
    Twisted: 19.10.0
    Django: 2.2.9

#### Additional context
Any other context about the problem, or ideas on how to solve.

**Comment by Griatch** [comment]
This was fixed. I also made a change to the `recog` command so that not giving an argument will now list all your reognized people (makes it easier when removing recogs)
