### ISSUE TITLE
[Feature Request] Remove prototypes from CmdScripts output

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2067]
#### Is your feature request related to a problem? Please describe.
Despite their common parentage, given that the `spawn` command already allows one to list and browse prototypes by themselves, it doesn't make any sense to include prototypes in the output of `CmdScripts`.

#### Describe the solution you'd like
Filter out prototypes from the queryset of `CmdScripts`.

#### Additional context
Eliminates the incidental silliness of `scripts/stop` deleting prototypes.

Helps with general Script noisiness referenced in #1994 and #2045.

**Comment by Griatch** [comment]
This has now been implemented.
