### ISSUE TITLE
File "setup.py" not found

### ISSUE THREAD

**Issue by LucasMaliszewski** [evennia/evennia#2070]
#### Describe the bug
pip install -e evennia

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/parallels/Developer/evennia/evennia

#### To Reproduce
1. Follow this guide https://github.com/evennia/evennia/wiki/Getting-Started#mac-install

#### Expected behavior
Not error out.

#### Environment, Evennia version, OS etc
Ubuntu 18.04, Python3.6.9, latest Evennia

**Comment by Griatch** [comment]
@LucasMaliszewski Make sure you are located in the directory above the evennia repo dir when you run this command. The `setup.py` file is definitely in there. You could also try to cd into the evennia/ repo and instead run `pip install -e .` (note the period, to install the current dir you are in). 

Unless it's clear this is not the case of calling from the wrong location, this issue will be closed.

**Comment by trhr** [comment]
#361
