### ISSUE TITLE
[Feature Request] How about store data in MongoDB

### ISSUE THREAD

**Issue by blackmonkey** [evennia/evennia#2071]
When playing around with Evennia, I found that all the attributes of a concrete object are stored in several MySQL database tables. When getting all information of the object, in my understanding, either a long SQL statement with many JOINs or multiple SQL statements should be executed. That is not efficient.

Why should not we store an object as a BSON in MongoDB? So that we can query the object from the database with one shorter quicker statement. MongoDB is also fast, although it is not as fast as MySQL. And filtering fields in BSON is also as convenient as SQL.

**Comment by friarzen** [comment]
I will note that because Evennia is based on Django, this can theoretically be accomplished by swapping Django for [Djongo](https://nesdis.github.io/djongo/get-started/).  I don't know of anyone that has put the effort into trying it out, but it **_should_** work.

**Comment by Griatch** [comment]
Well, realistically, I can say that we will not be changing the database scheme to NoSQL anytime soon. If you want to experiment, go ahead though.
