### ISSUE TITLE
[BUG] Password too similar to "dummy" prevents account creation

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#2079]
#### Describe the bug
While trying to create an account (without specifying an email address), player used a password that contained 'dummy' (backwards) and couldn't make an account. The log showed that the password was too similar to the (non-existent and set to dummy@example.com) email address. There also wasn't any notification to the player that this was why there was trouble creating the account - it just told them there was a problem and to contact an admin if it persisted.

**Comment by TehomCD** [comment]
All the validators can be overridden in settings, but is this producing a traceback in create_account? I think I remember something like that before I cleared them all. Ideally validators should give people feedback for failure immediately at the view level - commands, forms, serializers, whatever.

**Comment by Griatch** [comment]
@kaleara I need more information about how to reproduce this - by default it's not possible to give an empty email when logging in. Are you using some alternate login-method?

**Comment by kaleara** [comment]
When logged out, typing create fakeaccount ymmud123 returns "There was an error creating the Account. If this problem persists, contact an admin." I don't believe I have changed anything with account creation.  Multisession mode is 2. My log isn't reporting a traceback, but last night (on a different server, reproduced locally) it was showing that the password was too similar to the email address.

**Comment by Griatch** [comment]
Aha, that's what you mean by "not specifying the email address" - not giving the `@domain` ending of it. Thanks, yes that seems reproducible then.

**Comment by Griatch** [comment]
This was fixed in 4c648d80
