### ISSUE TITLE
[Tags] Add an example of how to get an object based on tags

### ISSUE THREAD

**Issue by RianeNelson** [evennia/evennia#2087]
#### Documentation issue
https://github.com/evennia/evennia/wiki/Tags

I would really appreciate a little clarification on tags and how to use them to extract objects. For example, if I have a list of objects and only want to get ones with "outside room" in the tag, there's no explanation of how to do so.
#### Suggested change
A couple examples perhaps using tags.get or something like that, since 'get' is not mentioned as an option in the document. How to get objects with specific tags into a list seems like something that would be pretty common and probably great for newbs like myself to learn!

**Comment by Griatch** [comment]
Ok, will look at clarifying/adding info on this.

**Comment by strikaco** [comment]
This is the existing documentation for searching by tag:

https://github.com/evennia/evennia/wiki/Tags#searching-for-objects-with-a-given-tag

There is already an example of how to do what you describe. Does it not work? Is it unclear?

Every object's manager has a `get_by_tag` method that should take a list of strings (tags) and return objects whose tags match all of them. This much is not explained in the docs, only the API.

So you could get all Characters tagged "male" AND "other" with something like:

```
stuff=Character.objects.get_by_tag(['male','other'])
```
If you wanted to find objects of *any* type with such tags (however that may apply) you can do the same with ObjectDB itself:

```
from evennia import ObjectDB
stuff = ObjectDB.objects.get_by_tag(['male','other'])
```
By default if you provide a list of tags it will reject any objects not matching all of your tags. You can match as many as possible instead with the `match="any"` kwarg; the results will be ordered by how many tags matched. This is useful for implementing a search engine.

In any case, `stuff` can be converted to a list with little trouble:

`stuff = list(stuff)`

Here is the relevant manager method's docstring. This method is accessible on most/all Typeclasses' `objects` property (i.e. Whatever.objects.get_by_tag()):

https://github.com/evennia/evennia/blob/5745b6fda08462b32aa5364df7243a5595ac6374/evennia/typeclasses/managers.py#L240-L270

HTH

**Comment by Griatch** [comment]
As @strikaco points out, this is already well documented, but there was no link to this from the searching-tutorial. I added that now.
