### ISSUE TITLE
[BUG] Search function returns both list and queryset.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2088]
#### Describe the bug
`caller.search` from a command returns a list for the item I have on my character, but a queryset for the item on the ground. Both items are of the Object typeclass, the only difference are the names and the locations of the objects. There's only one of each item in existence.

#### To Reproduce
1. Put item on player's character.
2. Put item on ground.
3. Call a search for each item.
4. Print the results.
5. Item on character will return as a list.
6. Item on ground will return as a queryset.

#### Expected behavior
Both searches should return a list.

#### Environment, Evennia version, OS etc
         Evennia version: 0.9.0 (rev dd13a3e2)
         OS: nt
         Python: 3.7.4
         Twisted: 19.2.1
         Django: 2.2.9

#### Additional context
Here's a pastebin showing my print results at the top and the code I was checking below:
https://pastebin.com/Mg2LSuDr

Here are the functioning commands, after I added in the proper len() checks, more specifically the CmdPut(Command):
https://pastebin.com/e1KNiSKC

**Comment by Griatch** [comment]
Note that it's correct that the manager methods return querysets. The issue here is rather than the search function uses a raw manager query in one case and not in the other. So the fix should happen in the search method, not on the manager level.

**Comment by Griatch** [comment]
This was actually already closed in 224ad5322.
