### ISSUE TITLE
[BUG] TravisCI Postgres/MySQL Tests Failing

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2093]
Just two things to note here:

- These databases fail on TravisCI. They also fail on Github's Actions, where I run my tests. With the same error.
-  The tests do not actually fail on a real box. I have a live server on MySQL, and my tests are fine.

Weird.

**Comment by Griatch** [comment]
This has been resolved. It has to do with the way mysql increments pks compared to how sqlite3 does it, and the fact that some of these tests hard-coded #dbrefs.
