### ISSUE TITLE
[BUG] Error when logging in as a Guest

### ISSUE THREAD

**Issue by P-Fitzgerald** [evennia/evennia#2098]
#### Describe the bug

Error appears to be related to MULTISESSION_MODE = 3. The error does not appear in MULTISESSION_MODE = 1 which leads me to believe it is related to these higher level sessions not generating a character object for the temporary account.

#### To Reproduce
1. Run Evennia with MULTISESSION_MODE = 3 (May also occur in 2. Does not occur in 1 and possibly 0).
2. Login as a guest (with connect guest)
3. See error ( https://pastebin.com/MZh8qyax )

#### Expected behavior

Expect a guest account to have a character object automatically created and dropped into the DEFAULT_HOME or START_LOCATION.

#### Environment, Evennia version, OS etc
If unsure, run `evennia -v` or get the first few lines of the `about` command in-game.

    Evennia 0.9.0 (rev 5b93aeb4) (rev 5b93aeb4)
    OS: posix
    Python: 3.7.3
    Twisted: 19.10.0
    Django: 2.2.12

#### Additional context
Any other context about the problem, or ideas on how to solve.

Probably just make it generate a default character object and automatically puppet them when a guest session is created. Alternatively could possibly include a setting or just assume that guest accounts are only able to have a MAX_NR_CHARACTERS = 1 or maybe a guest-specific setting so they don't generate a bunch of character objects.

**Comment by P-Fitzgerald** [comment]
Alternative method to fix the problem would be to generate a character object for the guest command on login and forcibly puppet them much like what probably happens with MULTISESSION_MODE = 0 or 1.

**Comment by Griatch** [comment]
The guest account will now always create a character, also for MULTI_SESSION_MODE>1.
