### ISSUE TITLE
[BUG] Database connection error inside twisted deferred

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2101]
#### Describe the bug
After ~8 hours of nonuse, attempts to query the mysql from inside the portal in specific ways are unsuccessful.

![image](https://user-images.githubusercontent.com/5786272/79340615-2c609780-7ef0-11ea-8f42-3a1564ee62ad.png)

This line returns "Connection has gone away" error after trying to access a twisted deferred call to the cursor, which it expects to exist but does not. Does not reproduce on existing protocols in obvious ways.

#### To Reproduce
1. Without accessing the Django website, connect to the websocket and pass in the csessid via wss://ip/ws?csessid
2. Wait until the mysql connection dies due to wait, and repeat step 1
3. See error

#### Expected behavior
I should be able to run database queries at any point in the server's database connection lifecycle.

#### Environment, Evennia version, OS etc
debian, ev 0.9

**Comment by Griatch** [comment]
Hm. so looking at this, I think I may know what happens ... 

Django provides a database connection through `django.db.connection` and the Server-component will close this connection ever 7 hours just to avoid this issue. See https://github.com/evennia/evennia/blob/master/evennia/server/server.py#L143
However, you are doing this call from the Portal, which has its own instance of `django.db.connection`. There is no equivalent cleanup on the Portal side. 

So adding a similar cleanup task on the Portal side would hopefully fix your problem.

**Comment by Griatch** [comment]
I wrote the original so of course I know how to do it. If you want it done _today_ though, a PR is faster.

**Comment by trhr** [comment]
I didn't know who wrote it originally. But _today_ is not a priority, especially with there being a lot of discussion around portal-level changes; I'd certainly rather let that shake out into some decisions and if there are none, I'll write the PR when it becomes pressing to _me_.

For now, I'm just rebooting the server every six hours.

**Comment by Griatch** [comment]
@trhr I added a mainenance task for this in the Portal now, hopefully that should resolve your issue.
