### ISSUE TITLE
[Feature Request] `evennia.utils.search_*` functions should accept and forward args/kwargs to object manager methods

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2106]
#### Is your feature request related to a problem? Please describe.
Was looking into #2087 and existing search functionality and noticed that the `evennia.utils.search_*` shortcut functions do not accept arbitrary args/kwargs. Because of this they limit access to some of the more advanced search capabilities as they are/become implemented on the object managers.

The search helpers are the "cleaner" way of searching and should be supported over encouraging devs to query the object managers directly, but this cannot happen if these functions do not have parity with the methods they wrap.

#### Describe the solution you'd like
Allowing these helpers to accept args/kwargs and forwarding them to the underlying methods would provide a more progressive search API.

**Comment by trhr** [comment]
There's an arg to be made that this same review should be performed on the create helpers, as they are also a little out of sync with the manager .create() methods.

**Comment by Griatch** [comment]
This is a good point, and is both an easy and backwards-compatible change to do.

**Comment by Griatch** [comment]
Updated the utils.search method call signatures. The functions in utils.create has no equivalent need since these _are_ the main creation methods and have no underlying manager methods that they echo.
