### ISSUE TITLE
[BUG] Admin changing password logs admin out.

### ISSUE THREAD

**Issue by P-Fitzgerald** [evennia/evennia#2112]
#### Describe the bug

When using the Admin interface to change a users password (IE. http://192.168.0.1:4001/admin/accounts/accountdb/2/password/ ). You can change the password but it gives a 'Error 500, Internal Server Error' and then requires you to log back in again although the password IS changed.

#### To Reproduce
1.  Find a user to change the password of.
2. Change Password.
3. See Error

#### Expected behavior

I expect to be dropped back into the Admin interface after changing the users password. When I click 'Return to home page' I get a notification that 'Password changed successfully' but I'm logged out of the admin account as well.

#### Environment, Evennia version, OS etc
If unsure, run `evennia -v` or get the first few lines of the `about` command in-game.

#### Additional context
Any other context about the problem, or ideas on how to solve.

**Comment by P-Fitzgerald** [comment]
Someone told me this may be a Django bug and not an Evennia bug. If so this report should probably be passed upstream to the Django development team.

**Comment by Griatch** [comment]
It was an Evennia bug, although it's somewhat tied to limitations in Django. I have fixed so there is no 500 anymore. Apparently the logout was due to the 500 at that particular point, because that doesn't happen anymore either for me.
