### ISSUE TITLE
[BUG] Storing method in .db attribute raises exception

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2116]
#### Describe the bug
Storing a method in a db attr seems to throw a select.epoll error, no matter how simple the method is

#### To Reproduce
https://hastebin.com/uguyesaqaj.rb

**Comment by trhr** [comment]
**Verdict**: .db attribute accessors can't ever be stored in .db attributes, due to inherit limitations of pickling things during atomic database transactions. e.g. self.db.box can't contain a self.get_box_contents method if get_box_contents(self) references self.item_name

**Comment by strikaco** [comment]
> **Verdict**: .db attribute accessors can't ever be stored in .db attributes, due to inherit limitations of pickling things during atomic database transactions. e.g. self.db.box can't contain a self.get_box_contents method if get_box_contents(self) references self.item_name

Are you sure about that? You're def right about referencing uncommitted data, but you should be able to [pickle methods as `functools.partial` objects](https://stackoverflow.com/a/14550773/1868358) and store those to be executed at some point if the transaction succeeds.

Have not tried it myself; this is entirely theoretical.
