### ISSUE TITLE
[BUG] list_to_string doesn't like generators

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2120]
#### Describe the bug
If one passes a generator to `list_to_string`, it will choke with a TypeError:
```
File "/home/ubuntu/workspace/evennia/evennia/utils/utils.py", line 382, in list_to_string
    if len(inlist) == 1:
TypeError: object of type 'generator' has no len()
```

#### Expected behavior
I'd personally expect the function to just cast the generator to something valid, but given that it would exhaust the generator I don't know if that presumption is socially acceptable.

**Comment by Griatch** [comment]
Well, it's called `list_to_string` specifically ... but I guess it's a simple usability improvement to auto-cast the generator to a list since we are converting it to a string anyway.

**Comment by strikaco** [comment]
I knew you were going to give me grief about that :)

Despite the name it'll happily take any other kind of iterable, so I'm appealing to consistency over the definition for this one.

**Comment by Griatch** [comment]
Yeah, it's easy enough to support so it makes sense to change.

**Comment by Griatch** [comment]
This utility is now renamed to `iter_to_string` (with `list_to_string` as a legacy alias) and will accept any input, including generators or even single values (which will become one-element lists as far as the function is concerned).
