### ISSUE TITLE
[Feature Request] "raw" version of look

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2123]
#### Describe the solution you'd like
Command look/raw to return unformatted strings (without color codes)

#### Describe alternatives you've considered
Unless something else like this exists in exam etc, I'll fulfill this feature request in the near future.

**Comment by trhr** [comment]
Also maybe look/plain (stripped ansi) as an alternative to look/raw ('escaped' raw colors)

**Comment by Griatch** [comment]
You can do this for the .msg method itself. Why would you want this for look? What is the use case for a regular user?

**Comment by trhr** [comment]
builder command to grab the colorcodes of desc?

**Comment by strikaco** [comment]
> builder command to grab the colorcodes of desc?

I like the idea, but do you have a specific use case that isn't already accounted for by either `set` or `examine`? Both already do this without the added flag...

```
> set here/demo = '|chello|n'
Created attribute Limbo/demo = 'hello'  # this repeats your input, rendered in color
> set here/demo
Attribute Limbo/demo = |chello|n  # this does not render color
> ex here
...
Persistent attributes:
 desc = blah
 demo = |chello|n
...
```
I will say it would also be useful to be able to see things like newlines as well (though ideally for *all* commands, not just `look`).

**Comment by trhr** [comment]
Examine, as I understand it, truncates the full string for readability? This is an anti-behavior. I haven't tried set.

**Comment by Griatch** [comment]
@trhr Try `examine here/desc`.
