### ISSUE TITLE
[Feature Request] Unit test for TagManager batch_add method

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2125]
#### Is your feature request related to a problem? Please describe.
Having some issues getting `batch_add` to work with a Msg object's tags, but can't tell if it's a bug or user error. 

There does not appear to be a unit test with a working example that I can reference.

https://github.com/evennia/evennia/blob/903bc201d5d404aeb92d4c99d40512534a3aa14c/evennia/typeclasses/tests.py#L50-L102

#### Describe the solution you'd like
Addition of a unit test demonstrating working syntax for this method.

#### Describe alternatives you've considered
Giving up :)

#### Additional context
It doesn't look like `batch_add` is tested for Attributes either.

```

    Evennia 0.9.0 (rev a6ed068) (rev a6ed068)
    OS: posix
    Python: 3.7.7
    Twisted: 19.10.0
    Django: 2.2.12
```

**Comment by Griatch** [comment]
Ok, I've added new unit tests for these methods in `evennia/typeclasses/tests.py`. I think the confusion may be from the docstring saying it accepts lists when in fact it wants `*args` - each argument should be a key/tuple to use to build the Attribute/Tag. I clarified the docstrings now.
