### ISSUE TITLE
[BUG] `Typeclass.manager.get_by_tag` improperly matches when number of tags found/requested is mismatched

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2128]
#### Describe the bug
For a stock match-all query on the Typeclass manager `get_by_tag` method, the manager will assume all tags matched when fewer tags were found than were requested.

#### To Reproduce
1. A single tag exists-- `one`
2. We want to match on two tags-- `...get_by_tag(('one', 'two'))`
3. https://github.com/evennia/evennia/blob/6c968af31326bb034e7a5d7ae6e9fa314102562d/evennia/typeclasses/managers.py#L329-L330
4. Since there is only one tag, `tags.count()` will be 1, and `n_req_tags` will be lowered to 1, which is less than what was requested and will match on more objects than it should.

#### Additional context
The `match=any` option was intended for this sort of best-effort matching. `all` really ought to return matches on *all* terms passed to it, or nothing at all if that is not possible.

Setting line 329 to `n_req_tags = n_keys or n_unique_categories` fixes this, or can be worked around using the `any` query and manually applying an additional `.filter(matches__gte=<num expected>)` to the result.

**Comment by strikaco** [comment]
On further thought I've never used this method to grab by category so my quick-and-dirty solution may have other consequences (like if 0 tags requested were found, I think that might still presumptively modify the user's match target to `1` in most cases).

The workaround should still work in both cases but is not as efficient as `all` working as intended.

**Comment by Griatch** [comment]
@strikaco Your suggestion seemed to work; I added some more unit tests to test it out as well. :)
