### ISSUE TITLE
[Feature Request] inlinefuncs delimeter

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2134]
#### Is your feature request related to a problem? Please describe.
Inlinefuncs goes nuclear if text has commas in it

#### Describe the solution you'd like
inlinefuncs should accept the declaration of a one or multiple character delimiter; e.g. §; which is selected so as to not conflict with text enclosed in function.

#### Describe alternatives you've considered
Writing the game in chinese?

**Comment by Griatch** [comment]
Inlinecmd-arguments with commas in them needs to be escaped by surrounding the argument with quotes or by escaping each comma with `\,`. See https://github.com/evennia/evennia/wiki/TextTags#inline-functions. Unless there is an issue with the escaping, I'm closing this.
