### ISSUE TITLE
[BUG] 'Reset' Switch mentioned but not implemented 

### ISSUE THREAD

**Issue by RianeNelson** [evennia/evennia#2136]
#### Documentation issue
The 'reset' switch for copying an object is mentioned in the [Copy Command](https://github.com/evennia/evennia/blob/10305003bec49b13a41689c76dd9dd9157198c2d/evennia/commands/default/building.py), but not actually implemented.
#### Suggested change
Add reset switch.

**Comment by Griatch** [comment]
At closer inspection, the /reset switch made no sense, because it'd be the same as doing a `create` call. So I removed the `/reset` mention from the command doc instead, to make it consistent.
