### ISSUE TITLE
[Feature Request] DefaultObject.search(typeclass='foo.bar', typeclass_exact=False)

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2140]
To enable searching by a parent typeclass, similar to DefaultObject.is_typeclass('foo.bar', exact=False)

Is this possible in a search method?

**Comment by Griatch** [comment]
It's possible, but not sure how suitable it'd be in the main search method - the number of options to that method is getting quite long already ... a manager method may be more suitable for a specific query like this.

**Comment by Griatch** [comment]
Thinking more about it, I think a database query is best for this, something like    
      
    DefaultObject.filter_family(db_typeclass_path__istartswith('foo.bar')`

Adding this to the normal search function seems a little too specific and also adds complexity.
