### ISSUE TITLE
[Feature Request] utils.validate_email_address cleanups/redundancies

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2143]
#### Describe the bug
The `utils` module has a function to validate email addresses, `validate_email_address`.

`utils.validatorfuncs.email` duplicates this functionality, but also does it differently (by leveraging [Django's own validator](https://docs.djangoproject.com/en/3.0/ref/validators/#emailvalidator)).

`Account` objects created with an email address will also use the Django validator by default.

#### Expected behavior
Given that the home-rolled validator's logic is not entirely sound (`ubuntu@localhost` *is* a real address despite not having a TLD) I think it would make more sense to force `utils.validate_email_address` to reference `utils.validatorfuncs.email`.

The only point of contention I can predict with this is that the two functions "do" different things-- `utils.validate_email_address` returns a `bool`, but `utils.validatorfuncs.email` raises an exception or returns the original value. Either way it is very unclear why competing solutions to a niche problem need to coexist :)

**Comment by Griatch** [comment]
Agree; we should use the django validator in both places. The util one is likely quite old; to keep the signature it could just catch any exception and return a bool instead.
