### ISSUE TITLE
[BUG] Python 2 syntax and potentially deprecated code in batchprocess.py

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#2145]
In batchprocess.py (default commands directory) there is a ProcPool related global string defined that seems to be using python 2 syntax for print.

The ingame command from that module seems to attempt running the batch process using PythonProcPool if its present in currently running services and the backend is not sqlite3.

Considering that nobody seems to have stumbled onto problems due to the mentioned python 2 syntax these checks I would assume always fail and PythonProcPool is never present as a service even if the db backend was something else than sqlite3.

Apart from the potential bug left over from the 08.>0.9 move, If ProcPool is deprecated in general in evennia it would be good to remove this reference to it and/or allow the batch process to still run_async just without using ProcPool, if there is any benefit in current evennia to it that is.

**Comment by Griatch** [comment]
ProcPool was a failed experiment with process offloading; the reference should indeed be removed.
