### ISSUE TITLE
[BUG] Exit cmdset duplicates do not merge onto character if syscmdkeys.CMD_NOMATCH also present on character

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#2146]
### Exit commandset in case of multiple exits of same name is not properly merged onto the stack for non superusers.

EXAMPLE:
If there are two exits named **up** (both also have the command alias **u**), my superuser can access those commands per usually by doing 1-u or 1-up and 2-u or 2-up respectively and traverse to the correct room.

**However in case of my player test character they always end up traversing the same exit regardless of specyfing 1-up, 2-up, 1-u, 2-u etc.**
They can still look at both exits by specyfing 1-up, 2-up (so multimatch search does work) however their merged commandset only contains a single up command!

Examining other exits in the room shows that all the other exits have two **up** commands in their merge stack. So in a room with one exit north and two exits up both my admin character(among other commands) and all the exits have "north up up" in their merged comandsets. Only my player character(among other commands) has "north up", lacking the second up command.

ADDITIONAL INFORMATION:
- I have tried looking everywhere for hours thinking innitially it had to do with some sort of multimach bug before I noticed the player character has only one up command in their merged set. 
- Both my player and superuser characters use the same typeclass, the superuser character gets their character and account commandsets replaced with an admin one (for convienience) from within at_initial_setup.py - apart from what commands they contain both character and admin ones are identitcal (same priority etc.)
- Other objects in the same room do not list any exit commands in their merge stack including my animal typeclassed objects (which just have look for now) - not sure if that is correct behaviour or not.
- Server reload or restart does not seem to change anything as is leaving the player character alone in that room (examining by dbref from afar still shows lack of the secondary up command)
- The player character was created by just making a new account in the default way from the connection screen for it.

I tried everything I could think of to narrow it down, spent hours reading my code to make sure there is nothing wierd there but I could barely find anything even relevant - if anybody has any idea what I could try to provide more information please let me know ;_;

*UPDATE:
I tried to copy an exit object using the ingame copy command and that resulted with an exit object with the _copy suffix, where both characters now have access to: the original command and the one for the copy. Since my original object had a command alias set, that command alias is same for both exits and results in multichoice kicking in properly rulling out problems with multichoice.
Unfortunately the moment I remove the _copy suffix, the merge breaks again as if allow duplicates was set to false somehow and the secondary command dissapears from the non superusers.

**Comment by BP-Santo** [comment]
I managed to figure out what was causing it! It was having syscmdkeys.CMD_NOMATCH implemented and added to the player character commandset.

This is unusual behaviour as the described case is not about non matching or even partially matching input. I tested both exact and non exact commands and it din't have any impact.
The command as described was simply missing as if cmdset.duplicates was set to False instead of True as it is in the default exit class.
It seems either the merging logic itself is affected in some odd manner or the duplicates flag is ignored, flipped/shadowed when the below command is present in the merge stack.

Below my simple `syscmdkeys.CMD_NOMATCH` for reference

```
from evennia import Command, syscmdkeys


class Nomatch(Command):
    """
    This is a system command. Commands with special keys are used to
    override special sitations in the game. The CMD_NOMATCH is used
    when the given command is not found in the current command set (it
    replaces Evennia's default behavior or offering command
    suggestions)
    """
    key = syscmdkeys.CMD_NOMATCH
    locks = "cmd:all()"
    auto_help = False

    def func(self):
        """Implements the command."""
        self.caller.msg("What?")
```

**Comment by Griatch** [comment]
Thanks for analyzing this, it made it a lot easier to find the problem! The issue was that the system-command is removed from the merge process of two cmdsets and then inserted separately at the end - and that cmdset.add operation would clean out duplicates since it's the same one used for building a plain cmdset. It will now properly ignore duplicates during the merge process which resolves this issue.
