### ISSUE TITLE
[Documentation] Windows Troubleshooting/Twisted

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#2147]
#### Documentation issue
In https://github.com/evennia/evennia/wiki/Getting-Started it states that if you are running Windows10 and using WSL, you can follow the Linux instructions to install Evennia.  This is not necessarily true.  If you're running an antivirus on Windows, you'll get several issues with Twisted.  These issues will persist and create errors in various structures, such as when running 'evennia connections' to list your game in the game index, when your antivirus is on.

#### Suggested change
In https://github.com/evennia/evennia/wiki/Getting-Started#windows-troubleshooting , note that running Evennia through WSL may cause issues with Twisted during installation if you have an antivirus running.  Additionally, note that if you receive twisted timeout errors in your log files while developing Evennia, it may be because your antivirus is on.

**Comment by Griatch** [comment]
Added.
