### ISSUE TITLE
[BUG] Migration resulting in deletion of custom SharedMemoryModel raises AttributeError: type object has no attribute '__dbclass__' 

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2148]
#### Describe the bug
I have a custom Django app with a single model defined:

```
class Data(SharedMemoryModel):
    
    class Meta:
        unique_together = (
            ('db_category', 'db_key', 'db_version'),
        )
    
    db_key = models.CharField("key", max_length=255, db_index=True)
    db_category = models.CharField("category", max_length=255, default='', blank=True, db_index=True)
    db_version = models.PositiveIntegerField(default=1)
    
    # Creation date. This is not changed once the object is created.
    db_date_created = models.DateTimeField("creation date", editable=False, auto_now_add=True)
    db_date_updated = models.DateTimeField("updated date", editable=False, auto_now=True)
    db_date_expires = models.DateTimeField("expiry date", blank=True, null=True)
    db_enabled = models.BooleanField("enabled", default=True)
    
    db_data = models.TextField(default='{}')
    
    db_lock_storage = models.TextField(
        "locks",
        blank=True,
        default='get:true();set:true();enable:true();disable:true()',
        help_text="locks limit access to an entity. A lock is defined as a 'lock string' on the form 'type:lockfunctions', defining what functionality is locked and how to determine access. Not defining a lock means no access is granted.",
    )
    
    db_tags = models.ManyToManyField(
        Tag,
        help_text="tags on this object. Tags are simple string markers to identify, group and alias objects.",
    )

    # Database manager
    objects = managers.TypedObjectManager()

    @lazy_property
    def locks(self):
        return LockHandler(self)

    @lazy_property
    def tags(self):
        return TagHandler(self)

    @lazy_property
    def aliases(self):
        return AliasHandler(self)
```

Creation works, everything migrates and objects CRUD just fine.

I'm now trying to make this an abstract model, which will result in its deletion during subsequent migration, but during migration it is raising an error about the lack of a `__dbclass__` attribute.

```
... <truncated> ...
File "/home/ubuntu/workspace/evennia/evennia/utils/idmapper/models.py", line 533, in flush_cache
    cls.flush_instance_cache()
  File "/home/ubuntu/workspace/evennia/evennia/utils/idmapper/models.py", line 370, in flush_instance_cache
    for key, obj in cls.__dbclass__.__instance_cache__.items()
AttributeError: type object 'Data' has no attribute '__dbclass__'
```

#### Expected behavior
Deletion of the model.

#### Environment, Evennia version, OS etc
```
Evennia 0.9.0 (rev ff11fbd8) (rev ff11fbd8)
    OS: posix
    Python: 3.7.6
    Twisted: 19.10.0
    Django: 2.2.9
```

#### Additional context
This could totally be an artifact of something improperly defined on my part (if so, please advise).

I'm probably doing something unconventional using the `TypedObjectManager` on a non-`TypedObject` (was an oversight on my part) but it seems to work so I haven't corrected it. Doing so now seems to have no impact on this issue.

**Comment by Griatch** [comment]
The  `__dbclass__` is a part of the Typeclass system and points back to its database table. 
So `DefaultObject`'s `__dbclass__` is `<class 'evennia.objects.models.ObjectDB>`. For a typeclassed entitiy to operate using the idmapper, the caching must happen on the dbmodel and not on the python class (the model is, after all, the only 'real' thing in the database). 

Normally all models using the idmapper are typeclasses but in your case you are confusing the system by using the typeclass-system with a non-typeclass. 

In principle I suppose we could change the idmapper to fall back to an `__instance_cache__` on the class rather than to `cls.__dbclass__.__instance_cache__` like it does today (because `cls` in your case is already a proper model and not a typeclass. It's not something I'll look into anytime soon, but if you are willing to make the change, feel free.

**Comment by strikaco** [comment]
So I did screw that up. Damn.

I don't think there is much precedent for the expectation that child model managers should "just work" on a parent model. Facilitating that would surely invite other problems. This was an accident to begin with so I am clearly not qualified to be monkeying with models at the core level ;)

Thanks for responding so quickly!
