### ISSUE TITLE
[BUG] `lockfuncs.objtag` does not pass kwargs to TagHandler

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2149]
#### Describe the bug
There seems to be a discrepancy between how `tag` and `objtag` are defined. 

The `tag` lock will explicitly pass the `category` kwarg to the TagHandler. The `objtag` lock only passes args. 

This seems like an oversight (and probably explains the issue that prompted my investigation; I was trying to lockcheck a categorized tag on an object before giving up and working around it).

https://github.com/evennia/evennia/blob/ff11fbd8c35c0b3d148719da96129c6f907352c8/evennia/locks/lockfuncs.py#L515-L542

#### Environment, Evennia version, OS etc
```
Evennia 0.9.0 (rev ff11fbd8) (rev ff11fbd8)
    OS: posix
    Python: 3.7.6
    Twisted: 19.10.0
    Django: 2.2.9
```

**Comment by Griatch** [comment]
Yes, this looks like an oversight.
