### ISSUE TITLE
[BUG] Grammar issue in CmdCharCreate in multisession mode 2 with maximum of 1 character

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#2151]
#### Describe the bug
If you have multisession mode set to 2 and MAX_NR_Characters set to 1, and you then try to create a second character, the error message you receive is "You may create a maximum of 1 characters."  This is ungrammatical.

#### To Reproduce
1. In settings.py, set MULTISESSION_MODE = 2 and MAX_NR_CHARACTERS = 1
2. Create a test account
3. Create a character using `@charcreate`
4. Attempt to create a second character using `@charcreate`
5. See error (bad grammar)

#### Expected behavior
Better grammar when a player attempts to create a second character when MULTISESSION_MODE = 2 and MAX_NR_CHARACTERS = 1

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 143137cc) (rev 143137cc)
    OS: posix
    Python: 3.8.2
    Twisted: 19.10.0
    Django: 2.2.13

#### Additional context
[Suggested patch](https://pastebin.com/X2m3DAum) for /evennia/evennia/commands/default/account.py

The suggested patch changes only the last 'if' statement. I provided the rest of the function leading up to it for context only.

**Comment by Griatch** [comment]
Thanks for the report and patch! Made it quick to find the place. I implemented a fix along similar lines. :)
