### ISSUE TITLE
[BUG] DefaultObject - Class-level lock string is defined as two strings

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2158]
#### Describe the bug
The class-level lockstring for `DefaultObject` is defined as two separate strings.

#### To Reproduce
https://github.com/evennia/evennia/blob/bd656417552089a79dd33053266785b3517ff5ee/evennia/objects/objects.py#L207-L211

#### Expected behavior
Not sure if this actually impacts anything but this looks like a typo.

**Comment by Griatch** [comment]
It's a `black` formatting artefact. At one point I probably split the string over two lines to fit within the line width; but then something changed so it was not necessary. The parentheses were removed but not the string-split. :) Fixed now.
