### ISSUE TITLE
[Documentation] Clarification on the namespacing of Tags

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2161]
#### Documentation issue
From the docs:

```
Tags are unique. This means that there is only ever one Tag object with a given key and category.
```

This seems very explicit about the fact that if I create a tag+category, it is globally unique.

But this isn't true. The truth that tags are actually namespaced is briefly mentioned in a subsection that encourages new users to skip over it, and lack comprehension otherwise:

```
There are also two special properties. These should usually not need to be changed or set, it is used internally by Evennia to implement various other uses it makes of the Tag object:

    model - this holds a natural-key description of the model object that this tag deals with, on the form application.modelclass, for example objects.objectdb. It used by the TagHandler of each entity type for correctly storing the data behind the scenes.
```

So it turns out tags are *not* globally unique-- they are only unique per [typeclass? Django model?]. This only became apparent to me once I started relying on references to common-named tag `db_data` that was inexplicably disappearing across models.

Design-wise this makes sense but the docs led me to believe Evennia was performing some sort of M2M-GFK-mapping under the hood to truly make tags unique across all models.

Unit test to demonstrate:

```
from evennia.utils.test_resources import EvenniaTest

from evennia.utils import create

class TagDataTest(EvenniaTest):
    
    def test_tagdata(self):
        "See if tagdata persists across models?"
        msg = create.create_message(self.char1, 'content')
        msg.tags.batch_add(*(('something', None, 'stuff'),))
        obj = create.create_object(key='object', typeclass='typeclasses.objects.Object', tags=(('something', None),))
        
        msg_data = msg.tags.get('something', return_tagobj=True).db_data
        obj_data = obj.tags.get('something', return_tagobj=True).db_data
        
        self.assertEqual(msg_data, obj_data)
        
```

**Comment by Griatch** [comment]
Tags are per-db-table unique yes. This is obvious in their implementation but I can see the doc being misleading on this account.

**Comment by strikaco** [comment]
Thanks, that explains that. I made a minor change on the wiki page that addresses this AFAIC.
