### ISSUE TITLE
Parameter account in Room.create(...) is not validated before read.

### ISSUE THREAD

**Issue by blackmonkey** [evennia/evennia#2162]
I was trying to initialize some Rooms when create my customized Object:

```python
def at_object_creation(self):
    portal, err = Room.create("Portal", self.account)
```

An AttributeError was thrown with the message "'NoneType' object has no attribute 'id'". By tracking down here and there, I found the root cause is `self.account` is `None`, and the corresponding parameter `account` is not validated here:

https://github.com/evennia/evennia/blob/bd656417552089a79dd33053266785b3517ff5ee/evennia/objects/objects.py#L2295

**Comment by blackmonkey** [comment]
same bug here https://github.com/evennia/evennia/blob/bd656417552089a79dd33053266785b3517ff5ee/evennia/objects/objects.py#L2494

**Comment by Griatch** [comment]
Fixed. Also made the .create method's `account` argument an optional keyword-argument since the locks can be set to default values if `account` is not given.
