### ISSUE TITLE
[BUG] EvMore - AttributeError: 'EvMore' object has no attribute '_paginator_slice'

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2165]
#### Describe the bug
Passing a Django Paginator object to evmore yields a traceback.

https://github.com/evennia/evennia/blob/bd656417552089a79dd33053266785b3517ff5ee/evennia/utils/evmore.py#L189-L194

The example suggests this is possible, but evmore does try to reference a reflexive attribute that does not exist.

https://github.com/evennia/evennia/blob/bd656417552089a79dd33053266785b3517ff5ee/evennia/utils/evmore.py#L301

There is a public method with a similar name. Maybe that is what was intended? (Don't take my word for it, my understanding is limited)

https://github.com/evennia/evennia/blob/bd656417552089a79dd33053266785b3517ff5ee/evennia/utils/evmore.py#L267

```
20-07-11 20:55:45 [EE] 'EvMore' object has no attribute '_paginator_slice'
20-07-11 20:55:45 [::] Traceback (most recent call last):
20-07-11 20:55:45 [::]   File "./commands/crud.py", line 99, in func
20-07-11 20:55:45 [::]     self.get(request, *args, **kwargs)
20-07-11 20:55:45 [::]   File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/django/views/generic/detail.py", line 108, in get
20-07-11 20:55:45 [::]     return self.render_to_response(context)
20-07-11 20:55:45 [::]   File "./commands/crud.py", line 149, in render_to_response
20-07-11 20:55:45 [::]     page_formatter=self.render,
20-07-11 20:55:45 [::]   File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/utils/evmore.py", line 241, in __init__
20-07-11 20:55:45 [::]     self.init_iterable(text)
20-07-11 20:55:45 [::]   File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/utils/evmore.py", line 301, in init_iterable
20-07-11 20:55:45 [::]     self._paginator_slice
20-07-11 20:55:45 [::] AttributeError: 'EvMore' object has no attribute '_paginator_slice'
```

**Comment by Griatch** [comment]
As far as I can tell, this may be a leftover from earlier refactoring. It should be `self.paginator = self.paginator_slice`. Should be fixed now; check it out.
