### ISSUE TITLE
[Documentation] Use of `__str__` vs `__repr__`?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2174]
#### Documentation issue
After the frustrations of #2027, I've learned that sometimes it's just less messy to ask permission than to beg forgiveness :)

With regards to usage of `__str__` and `__repr__`, Django does things its own way:
```
>>> f = Field.objects.get_or_create(key='bleh', desc='dummy test')[0]
>>> f
<Field: Field object (1)>
>>> str(f)
'Field object (1)'
>>> repr(f)
'<Field: Field object (1)>'
```
I think Django also uses the `repr` form of objects for display in the inline Admin panes(?).

...but at multiple levels, Evennia overrides those to handle them differently (on the `TypedObject`, `Attribute` and `Msg` models at the very least):
```
>>> from evennia import ObjectDB
>>> o = ObjectDB.objects.first()
>>> o
jstrika
>>> str(o)
'jstrika'
>>> repr(o)
'jstrika'
>>> from evennia.typeclasses.attributes import Attribute
>>> a = Attribute.objects.first()
>>> str(a)
'_playable_characters(1)'
>>> repr(a)
'_playable_characters(1)'
```

What rights does Evennia claim to usage of either method? Can I safely extend one or the other? Is there anything in the stack that relies on string coercion for lookups?

As with #2027, the issue I'm facing is with arbitrary objects that can *logically* be coerced into a string-based format (like `Msg`-- think `Document`, `Table`, `Sign`, etc.), but casting `str` on them currently returns some rendering of the `key` attribute instead of something more illustrative-- like its `desc` or `content`. Or in other cases (like #2102 regarding non-typeclassed objects, i.e. EvTable), when one fails to cast to `str` before passing it to `msg`, it yields confusing tracebacks in hard-to-reach places or breaks AMP altogether.

#### Suggested change
I'd just like to know if I can safely extend either method to render string-based objects or if this would cause all sorts of problems I'll only learn about after a torrent of cascading failures :)

**Comment by strikaco** [comment]
One alternative I'm considering is creating a new method like `__msg__` or `__ascii__` for this purpose that returns either `str`/`repr` by default (not sure yet which). All `msg` methods should attempt to call that to render and ascii-encode any payload it receives. This would also allow safe storage and rendering of utf8 payloads in `Msg` objects...because when one of those slips by (easy enough to introduce via Admin) and is later displayed, all sorts of weird string breakage manifests in the console.

It's not Django best practice to generate HTML inside models but this could also be extended for `__html__` so objects that would otherwise be rendered to a textual EvTable or stat bar/gauge would return natural string representation in the form of an HTML table or Bootstrap progress bar where applicable, or just wrap the output of `__ascii__` with `<pre>` tags if more specific behavior has not been defined. 

No more worrying about the context in which a particular object should be rendered if the context is self-aware enough to invoke the appropriate rendering method by default :)

**Comment by strikaco** [comment]
Taking some inspiration from how Django renders Forms, a `RenderHandler` solves this nicely:

* `obj.render.as_html` # arbitrary html rendering defined by typeclass
* `obj.render.as_href` # html href to object webpage, with `desc` auto-appended as an `alt` tag
* `obj.render.as_table` # evtable rendering
* `obj.render.as_html_table`
* `obj.render.as_msg`
* `obj.render.as_str`
* `obj.render.as_int`
* `obj.render.as_dict`
* `obj.render.as_json`
* `obj.render.as_list`
* `obj.render.as_li`
* `obj.render.as_p`
* `obj.render.as_desc` # more florid version of  `get_display_name`

Tries calling the appropriately-named method on the object itself, or defaults to `repr`/`str`. Goes against the Django philosophy of writing HTML at the model level but in this case, models need to be able to force rendering of themselves based on context.

**Comment by Griatch** [comment]
That's sort of a nifty solution, @strikaco. Not sure what to think of it as a whole, but it does make some things more readable.
