### ISSUE TITLE
[BUG] examine problem

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#2175]
<img width="731" alt="스크린샷 2020-07-23 오전 6 33 23" src="https://user-images.githubusercontent.com/3595071/88231081-8b336b00-ccae-11ea-98ec-0547139c50c5.png">

#### Describe the bug
The cause is unknown, but problems occur when using examine.
I couldn't figure out what was wrong, so I tested evennia with a fresh install, but the same problem occurs. The same problem occurred in python 3.7.5 and 3.8.5.
The same problem occurs when connecting from tintin++ or web.

#### To Reproduce
1. git clone https://github.com/evennia/evennia.git
2. pip install -e evennia
3. evennia --init mygame
4. cd mygame
5. evennia migrate
6. evennia start
7. wizard id create and connect
8. set here/bb = 1
9. ex here/bb   => Error (screenshot)
10. ex here   => No problem

#### Expected behavior
I don't know what I did wrong.

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev dc377d28) (rev dc377d28)
    OS: posix
    Python: 3.8.5
    Twisted: 20.3.0
    Django: 2.2.14

**Comment by aceamro** [comment]
<img width="899" alt="스크린샷 2020-07-26 오전 1 20 30" src="https://user-images.githubusercontent.com/3595071/88461415-4b52ca80-cede-11ea-83fc-59b3a2bdca3c.png">

I saw the building.py file updated 8 days ago.
The problem was solved by changing crop to true as a temporary measure. I don't know if it's the right way.

**Comment by Griatch** [comment]
This was a bug in the refactoring of the examine command being done last week. Thanks for reporting. Should be fixed now.

**Comment by aceamro** [comment]
@Griatch Thanks for the quick feedback :)
