### ISSUE TITLE
[Documentation] Website Help System Tutorial Breaks the Website

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#2176]
#### Documentation issue
There are a couple of issues with the following tutorial: 
https://github.com/evennia/evennia/wiki/Help-System-Tutorial

(1)
The intro paragraph contains a broken link to a Django tutorial (404 error). 

(2)
In the "create a view system," the tutorial states:
You can open the "web/help_system/view.py"

This should be _views.py_ with an 's'.

(3)
At the step "Create a new URL", following these instructions: "We also need to add our app as a namespace holder for URLS. Edit the file "web/urls.py". In it you will find the custom_patterns variable. Replace it with..." breaks the website.

The traceback is:

          File "/muddev/ClockworkTower/web/urls.py", line 14, in <module>
            url(r'^help/', include('web.help_system.urls',
        builtins.TypeError: include() got an unexpected keyword argument 'app_name'

Changing this code to more closely track the example in the custom_patterns template of urls.py unbreaks the website, but eventually results in the rest of the tutorial not functioning correctly, i.e., you end up with a 500 error when you try to access the 'help' area of the website.

#### Suggested change
Update the tutorial to include the correct arguments in the custom_patterns instructions.

**Comment by strikaco** [comment]
Not that the errors don't warrant correction, but are you trying to create a help system or are you just following that tutorial to learn how to make custom pages?

- If the former, the help system was integrated years ago so you wouldn't have to mess with any of that-- you can make help pages directly in the admin now and they'll show up on the website (go to `http://yourdomainorlocalhostorwhatever:4001/help/` for some guidance). 
- There is also the `flatpages` Django contrib to let you create static pages from the admin as well (like Wordpress). Just FYI.

Part of the confusion with the tutorial was a change in syntax across Django versions. I'll take a look at correcting the errors you point out here, but for general audiences that tutorial is a bit stale.

**Comment by strikaco** [comment]
...and on further review, that is probably the most tedious and daunting method of creating views possible to achieve in Django :) Must have been written before class-based views were introduced. 

1. Now fixed
2. Now fixed
3. Fixed; a different function (`path`) is now used for URLs, not `url`.

- I fixed a few other errors that stood out to me as obviously incorrect. 
- I took the liberty of not namespacing the new app, but that may need to be re-added.
- I suspect some parts of that tutorial would have conflicted with the existing help system that shares the same URL path, so I adjusted the tutorial's paths to disambiguate the two.

Hope this helps enough to get something working;  do follow up if it needs additional revision.

**Comment by Griatch** [comment]
@strikaco Thanks for that, the web tutorials are likely the least polished ones in the roster.

**Comment by strikaco** [comment]
@Griatch No problem. I was in a rush yesterday (still am) but looking at it again it appears all of the URL index/list/detail routing logic was crammed into the "index" view by means of the `/help_system?name=desc` parameter, so in theory one could walk this tutorial through to some form of completion.

**Comment by Valishet** [comment]
> Not that the errors don't warrant correction, but are you trying to create a help system or are you just following that tutorial to learn how to make custom pages?
> 
>     * If the former, the help system was integrated years ago so you wouldn't have to mess with any of that-- you can make help pages directly in the admin now and they'll show up on the website (go to `http://yourdomainorlocalhostorwhatever:4001/help/` for some guidance).
 
Thanks for looking at this.  I have no trouble manually making help entries with the admin tool on the website.  But!  I want all the help entry in the game to be available on the website, so that you don't have to type 'help X' in the game for any purpose.

I also don't want to manually create a help entry for every command in the game.  I'd rather have those help entries populate automatically from what's already there.   In theory, following the tutorial, that should happen in "The full system" subheading where the _get_topics(character) function iterates through the commands, gets the help topics accessible to the character, and populates them on the website.

I thought it would replace the existing help system rather than creating a conflict.  Anyway, I'll give it another look over the weekend and let you know if I run into any more problems.

**Comment by Griatch** [comment]
I read in the comments that this was fixed by Strikaco, but the issue was still in the docs. Maybe a regression after converting to the new doc site? Anyway, most of these tutorials will have to be updated anyway, but this particular thing was now fixed (again).
