### ISSUE TITLE
[Documentation] What does calling `yield` within a command do to the state of the command?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2179]
#### Documentation issue
The docs hint at the state of a command surrounding invocations of `yield` being shaky; I think it's affecting one of my commands but would appreciate some clarification on how I should expect this to actually work.

I have a command that does something like:

```
def func(self):
    actions = self.actions = []
    actions.append('a')
    yield 4                       # arbitrary cooldown
    actions.append('b')
    self.actions = actions        # just to be assertive

def at_post_func(self):
    # commit actions
    for action in self.actions:
        print(action)
```

...I'm finding that `self.actions` in `at_post_func` contains only `a`.

I'm guessing there is some interruption of the command state when I call yield. Is there a workaround to preserve it? Is this a case for `save_for_next`? Or should I just shove `actions` into a cache?

**Comment by Griatch** [comment]
This is expected but I can understand why it'd be confusing. There is no strange loss of state from the yield, you are just printing things in a place that makes it unclear what is happening. Try this instead:

```
class Cmd2179(Command):                                                                                                     
     "Weird behavior with yield"                                                                                             
      key = "issue2179"                                                                                                       
                                                                                                                             
     def func(self):                                                                                                         
         actions = self.actions = []                                                                                         
                                                                                                                             
         actions.append('a')                                                                                                 
         yield 4                                                                                                             
         actions.append('b')                                                                                                 
         self.caller.msg(f"actions in func: {actions}")                                                                      
                                                                                                                           
    def at_post_cmd(self):                                                                                                  
        self.caller.msg(f"actions in at_post_cmd {self.actions}")

```

(I presume you meant `at_post_cmd` and not `at_post_func`). This is the ouput: 

```
actions in at_post_cmd: ['a']
   (4 seconds later)
actions in func: ['a', 'b']
```

What an asynchronous `yield` does is to bring the `func` out of the regular processing flow. It will not stop the command-processing though, so it causes `at_post_cmd` to fire first, at a time before `b` has been assigned yet. Once `func` resumes it will set `b` correctly. 

While this is consistent with how asynchronous code works, I would agree it's not intuitive to have something named `at_post_cmd` fire before the command actually finished. I'll consider this a sort-of usability bug and see if I can move the `at_post_cmd` into the async flow in this case as well.

**Comment by strikaco** [comment]
That certainly explains it. I didn't get that yield would go asynchronous in this context; I assumed it made `func` behave like a generator. Thanks for the clarification!

**Comment by Griatch** [comment]
@strikaco You are not wrong - It _does_ make `func` act as a generator; this is how twisted is allowed to pause it - the generator will be paused until twisted essentially runs `next` on it after 4 seconds. :)
