### ISSUE TITLE
[BUG] Wrong plural tag

### ISSUE THREAD

**Issue by blackmonkey** [evennia/evennia#2183]
#### Describe the bug
I found incorrect plural_key alias tag was added to my customize object:
```python
class EntryKey(Object):
    pass
```
And these plural_key aliases were found in admin page: "one keys", "a key"
As you can see, there is syntax error in "one keys".

#### To Reproduce
1. Create a batch building script, and do the following things in it:
   1. dig a room
   2. teleport to that room
   3. create and drop an EntryKey instance with db_key "key"
2. Execute the build script
3. Check EntryKey instance attributes in admin page.
4. You will see the incorrect plural_key alias tag.

#### Expected behavior
"one keys" should be "one key" instead.

#### Environment, Evennia version, OS etc
Evennia 0.9.0 (rev 9ab8ef68e) (rev 9ab8ef68e)
OS: nt
Python: 3.7.0
Twisted: 19.10.0
Django: 2.2.13

#### Additional context
I found the incorrect plural_key alias tag is generated here:
https://github.com/evennia/evennia/blob/c3831ea09cfb55906bacccbe7421309c0f28b74d/evennia/objects/objects.py#L345
I don't understand why hardcode the count as 2 here.

**Comment by Griatch** [comment]
There was a reason for hardcoding the plural form but I can't for the life of me not remember what it was anymore. It makes more sense to have the `one key` alias in that spot when there is only one item anyway. Fixed now, thanks.
