### ISSUE TITLE
[BUG] Util.Delay and Yield don't work with Scripts

### ISSUE THREAD

**Issue by TehFamine** [evennia/evennia#2184]
#### Describe the bug
DefaultScript object does not support util.delay or yield calls in at_repeat().

Yield will simply cause the script not to run. util.delay() will import and be executed fine, just without the delay. For example, util.delay(10, self.obj.msg("Test")) will not delay the message of "Test" by 10 seconds. It will return the message at the interval of the script.

#### To Reproduce
1. Create a test script
2. Import util.delay(10, func()) or use yield 10
3. Assign script to an object
4. See error if Yield, see no delay if util.delay(10, func())

#### Expected behavior
Should delay beyond the interval of the script. For example, if the interval of the script is every 10 seconds and you set a delay of 5 seconds on a function call, then at the 10 second mark you should see nothing called until 5 seconds later.

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 7c05c9ad) (rev 7c05c9ad)
    OS: nt
    Python: 3.7.4
    Twisted: 19.10.0
    Django: 2.2.14

#### Additional context
In my scenario, I am creating a script to assign to a ship object that has crew members in the object.contents. The script is moving the crew objects between the decks of the ship. Each time they move, feedback messages are sent to the player controlling the ship. With a crew of 10 or more on the ship, the message spam can be a lot if they happen all at once. I want to delay the messages randomly to the player to spread them apart.

I can obviously get around this by creating a script per crew type and assign those scripts to the crew. Then use something like restart(interval=None, repeats=None, start_delay=None) in the at_repeat() call to randomize the single crew objects actions. But, that means having 10 scripts running at once for 10-man crew of a ship versus 1 script per ship.

**Comment by strikaco** [comment]
`yield` would only work in the context of a command.

The problem you're having with `delay` is because delay is meant to take a callable. You're passing it a method instance. To do what you want here, try something like:

```
# apologies for formatting, on a phone
class Script:

def bark(self, msg):
    self.obj.msg(msg)

def at_repeat(self):
    utils.delay(10, self.bark, "woof")
```

**Comment by TehFamine** [comment]
Thanks Strikaco. You are right. I didn't noticed that until after being it was a method, not a function. We can close this issue.
