### ISSUE TITLE
[BUG] Attributes - Default read lock inconsistently defined/applied

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2185]
#### Describe the bug
The AttributeHandler defines a class-level lock governing reading of an attribute as `attrread`:

https://github.com/evennia/evennia/blob/c3831ea09cfb55906bacccbe7421309c0f28b74d/evennia/typeclasses/attributes.py#L216-L224

The wiki also cites `attrread` as the intended read lock.

...but the Attribute model's `access` method uses `read` as the default lock:

https://github.com/evennia/evennia/blob/c3831ea09cfb55906bacccbe7421309c0f28b74d/evennia/typeclasses/attributes.py#L189-L193

#### Expected behavior
Not sure what to expect. I'm all for brevity, but it appears the popular convention is `attrread` over `read`, so I'm guessing the default lock on `access` should be `attrread` as well?

#### Environment, Evennia version, OS etc
```
Evennia 0.9.0 (rev c3831ea0) (rev c3831ea0)
    OS: posix
    Python: 3.7.6
    Twisted: 19.10.0
    Django: 2.2.9
```

**Comment by Griatch** [comment]
Yeah, it makes sense that it should be `attrread` there too. Changed it now.
