### ISSUE TITLE
[Documentation] Quell evenniacode bot's URL preview on Discord.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2186]
#### Documentation issue
On Discord, URLs are previewed by default. Meaning that a giant chunk of the chat gets hogged up by the evenniacode bot sending links to IRC, which are then forwarded to Discord.

Here's an example of what it looks like in the Discord chat.
https://i.imgur.com/gkqRe7O.png

#### Suggested change
Discord will quell the preview behavior if a URL is encapsulated within <>

My suggestion is to change the evenniacode bot's default behavior so that links are now surrounded with <> 

Here's an example of how links should look on the evenniacode bot: 
`<https://github.com/evennia/evennia/wiki/EvMenu>`

There is a feature within Discord to disable the automatic link previewing, but the preview is on by default and so the behavior will continue for those not aware of how to turn it off. https://i.imgur.com/op25GSM.png

**Comment by Griatch** [comment]
Thanks for the ticket, but it looks like this was fixed on the Discord side already :)
