### ISSUE TITLE
[BUG] More gracefully handle passing the wrong method type to TickerHandler

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#2191]
#### Describe the bug

A user faced a server-level lockup when trying to pass a method on a normal Python object (rather than on a typeclass) to the TickerHandler. 

#### To Reproduce
1. Create a plain Python class with a method on it.
2. Add the method to TickerHandler. 
3. See error about the `obj` not having Attribute `pk` (because it's not a typeclass). 

#### Expected behavior

The TickerHandler does not work with non-typeclass based methods. It should either be extended to do so or at least handle the error more gracefully, with a proper warning instead of a crash. 

#### Environment, Evennia version, OS etc
Master branch. 

#### Additional context
The reason for the typeclass restriction of the tickerhandler has to do with deserialization of the object; it's possible one could work around that; while the limitation is documented it's not surprising that users don't read and assume the tickerhandler to work with any type of python callable.

**Comment by kovitikus** [comment]
Some additional information regarding the issue I ran into when this bug popped up. Hope it's useful.

I was trying to add a ticker_handler to my rat's `at_object_creation` hook and I told it to call my mob_handler's claw method, which is inside a normal Python class.

Here's what my Rat typeclass looked like.
https://github.com/kovitikus/hecate/blob/a22986fc8b466f21ffac7408bc005eb268edeb52/typeclasses/mobs.py

And here's the MobHandler Python class I tried to call the method on.
https://github.com/kovitikus/hecate/blob/9ba7e4ff131528282112f596d863ec5234d9aae3/world/mob_handler.py

Finally, here's the traceback log.
https://pastebin.com/1GrLAPY5
