### ISSUE TITLE
[Feature Request] Add a `db_receiver_external` field to the Msg model

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2193]
#### Is your feature request related to a problem? Please describe.
`Msg` objects are a nifty data storage container. But while they allow storage of arbitrary strings representing senders, there is no simple way to represent an arbitrary receiver (tags are case-insensitive...).

#### Describe the solution you'd like
Add an indexed `CharField` that can be used to represent arbitrary receivers to the `Msg` model.

#### Additional context
This is mostly creating problems with a Slack bot I'm trying to write. I need to be able to mirror and archive messages sent to recipients in an external Slack channel (that have no corresponding Typeclassed object in the database serving as a receiver). Having a counterpart field to track the observed recipient of a message would be super helpful. In some cases I do later create a recipient object and need to associate the messages sent "to" it before its creation.

In terms of broader appeal, being able to store generic `source` and `target` strings as sender/receiver with some sort of payload as the message would allow one to create and serialize graphs using `Msg` objects as the storage medium.

**Comment by Griatch** [comment]
Implemented in `develop` branch.

**Comment by strikaco** [comment]
An unexpected surprise, thanks!
