### ISSUE TITLE
[Documentation] Turn Evennia In Pictures Blogpost Into Documentation Article

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2202]
#### Documentation issue
https://evennia.blogspot.com/2016/05/evennia-in-pictures.html

#### Suggested change
Transfer this into a documentation article. Likely best to wait until the new static site is up and running.

This blog post is full of great information and it deserves to be more prominently displayed to community members seeking to learn.

**Comment by Griatch** [comment]
One would probably need to update the blog post or write a new one to match Evennia as it is for 1.0. But the idea remains good.

**Comment by Griatch** [comment]
Implemented as https://www.evennia.com/docs/latest/Evennia-In-Pictures.html
