### ISSUE TITLE
[BUG] Unhandled Error

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#2209]
#### Describe the bug
Sometimes an "unhandled error" occurs where the cause of the occurrence is unknown.
I've been trying to find the cause for months but couldn't find it.

#### To Reproduce
1. Unknown cause
<img width="907" alt="스크린샷 2020-10-02 오후 10 33 04" src="https://user-images.githubusercontent.com/3595071/94929370-fa73d980-04ff-11eb-9f92-615fdaebdb94.png">
 
I don't know if it's the same cause, but there are times when commands from newly connected users don't work until reloaded.

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev bec7151b9) (rev bec7151b9)
    OS: posix
    Python: 3.8.5
    Twisted: 20.3.0
    Django: 2.2.14

**Comment by Griatch** [comment]
As far as I can tell, this error has been handled already. I'm closing this; if this still happens with the latest code, let me know and we can re-open.
