### ISSUE TITLE
[BUG] Enter a brief description here

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#2214]
#### Describe the bug
WEBSOCKET_CLIENT_INTERFACE listed in default_settings.py appears to be entirely ignored.

#### To Reproduce
set WEBSOCKET_CLIENT_INTERFACE = '127.0.0.1'  in settings.py
restart evennia

#### Expected behavior

    The startup text should show:
        webclient-websocket-127.0.0.1: 4002

    Instead you get:
        webclient-websocket-0.0.0.0: 4002

**Comment by Griatch** [comment]
The websocket interface works fine. This was just a display-error when starting up.
