### ISSUE TITLE
[Feature Request] text field tabs with "+" button inside each of them

### ISSUE THREAD

**Issue by dorianturba** [evennia/evennia#2215]
### Description of the problem
The text field tabs is provided with a "+" button that allow to add more tabs.
But when we add tabs, the "+" remain in each previous tab.
![input +x|input +x|input +x](https://user-images.githubusercontent.com/9381120/95469933-78146b00-0980-11eb-82dc-d171f2b8c601.png)

### Solution I'd like
Instead of a "+" in each tab, I prefer an empty tab next to the last one with a "+" in it. Like in browser.
 in browser (eg. Opera): 
![tab1|tab2|+](https://user-images.githubusercontent.com/9381120/95470163-bf9af700-0980-11eb-9d68-6735f119e4ca.png)
How I picture it (ugly, made by editing html, but exactly what I want if better css):
![input x|input x|input x|+](https://user-images.githubusercontent.com/9381120/95470202-cb86b900-0980-11eb-8887-798e88baf46c.png)

**Comment by mo-jinbuu** [comment]
Hey @Vikka I can take of care of this if no one's on already on it. I'll get started on it today.

**Comment by selberhad** [comment]
Is this change still desired? I was just working with the tab manager and should be able to knock this one out quickly once #2905 gets merged.

**Comment by Vikka** [comment]
> 

yes please :)

**Comment by Griatch** [comment]
@selberhad While I suppose keeping the + means you can open a new tab from whenever, I agree it'd look more like a browser if removing it. So if you want to take it on, go ahead!

**Comment by selberhad** [comment]
Good to go, just waiting on #2905 since this work depends on those changes.

Here's what it looks like:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/35088339/194426936-d54e05b9-ce2b-4e54-83b0-1d0820fc9c1e.png">
