### ISSUE TITLE
[Feature Request] Select a text field tab but focus isn't on the textbox

### ISSUE THREAD

**Issue by dorianturba** [evennia/evennia#2216]
#### My problem
When I select a textfield tab, I have to click a second time in the textbox.

Two tabs:
![1](https://user-images.githubusercontent.com/9381120/95471552-5916d880-0982-11eb-830c-120b8107efa3.png)
Select tab 2:
![2](https://user-images.githubusercontent.com/9381120/95471572-5f0cb980-0982-11eb-9a8c-1ab3f1730ed6.png)
Another click for the textbox:
![3](https://user-images.githubusercontent.com/9381120/95471601-6764f480-0982-11eb-970d-95a744790f10.png)

#### What I want
When I click on a Tab, I want to focus the textbot. Like this, I just have to click one time and start writing.

**Comment by egrinberg** [comment]
Hey, I would like to work on this. Please assign me.

**Comment by Griatch** [comment]
@egrinberg We don't do explicit assignment. Just take it away!
