### ISSUE TITLE
[Documentation] Prototypes - How does inheritance/merging work?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2220]
#### Documentation issue
Python objects support multiple inheritance. It appears prototypes do something similar by virtue of the fact that multiple `prototype_parent` values can be provided in a prototype definition. The resulting child object instance will be comprised of some amalgamation of the keys and values defined in the parent templates.

#### Suggested change
It is unclear what gets inherited, what gets merged, what gets replaced, and how typeclasses are applied to the final object.

- It looks like any key prefixed with `prototype_` applies only to that definition and is not inherited by child templates.
- It looks like the sum of all tags defined on all parent templates are inherited by children (?). Unsure if aliases are inherited.
- I'm assuming where multiple same-named attributes are defined throughout the inheritance tree, the one defined by the final parent (or on the child template itself) wins?
- Same with typeclasses...if multiple parents define different typeclasses for themselves, is only the last typeclass applied, or are **all** the typeclasses in the inheritance tree treated as actual mixins (i.e. can I expect `at_object_creation` to be triggered for each parent typeclass)?

**Comment by strikaco** [comment]
> It looks like the sum of all tags defined on all parent templates are inherited by children (?). Unsure if aliases are inherited.

Tags do appear to accumulate. Aliases do not.

> I'm assuming where multiple same-named attributes are defined throughout the inheritance tree, the one defined by the final parent (or on the child template itself) wins?

This one is tricky because there are two ways to define attributes.

* If you define a list of attributes and store it under the `attributes` key, the entire list will be overwritten by any similar list on a child class.
* If you define an attribute as a key:value pair in the prototype dict, that attribute is selectively overwritten on child objects.

What this lends itself to (but is never explored in the docs) is using the list form of attribute definition to define the "schema" of attributes for a parent object type-- then on child objects, you set your active values using the key:value form.

```
# Parent prototype
NPC = {
    "key": "npc",
    "attrs": [
	('hp', 100, '', 'attrread:self();attredit:false()'),
	('mp', 100, '', 'attrread:self();attredit:false()'),
    ]
}

# Child prototype
# (Attribute category cannot be referenced using this method.)
CHARLIE = {
    "prototype_parent": ("NPC",),
    "key": "charlie",
    "hp": 50,
    "mp": 50,
}

```

**Comment by Griatch** [comment]
@strikaco Some good observations. The selective overwrite of tags and attributes seems to be an oversight; Attributes/tags should be unique (and thus be overwritten in the child class) by `key + category`. That doesn't mean that the other values in the tuple should not be inherited at all!

I'll fix this in the prototype inheritance logic and expand the prototype docs to explain inheritance with more words.
