### ISSUE TITLE
[Feature Request] EvEditor - Do not add string-casted `None` literals to buffer

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2222]
#### Is your feature request related to a problem? Please describe.
When editing an attribute using `set/edit`, if the attribute in question is unset or otherwise `None`, the string `"None"` is prepended to the buffer.

```
----------Line Editor [object/name]-----------------------------------------
01| None
----------[l:01 w:001 c:0004]------------(:h for help)------------------------
```

Using the editor to set an initial value requires the first step to be `:x 1` in order to actually start with a clean slate.

#### Describe the solution you'd like
I'd suggest that if the existing attribute value is anything other than a string, the editor should at least warn the user about the type mismatch.

In cases where the value is the literal `None` or otherwise evaluates to `False`, these should simply not be appended to the buffer.

**Comment by strikaco** [comment]
I do see some existing commands that implement the editor perform typechecking, but this could be better enforced by the editor itself.

```
if old_value is not None and not isinstance(old_value, str):
            typ = type(old_value).__name__
            self.caller.msg(
                "|RWARNING! Saving this buffer will overwrite the "
                "current attribute (of type %s) with a string!|n" % typ
            )
            return str(old_value)
```

**Comment by Griatch** [comment]
The editor already defaults to warning in red if trying to edit a non-string. I made a previously undefined Attribute come out as an empty string in `set/edit` command also added a confirmation question to confirm, since that use of the editor is so likely to encounter non-strings. Closing.
