### ISSUE TITLE
[Feature Request] Enter a brief description here

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#2225]
#### Is your feature request related to a problem? Please describe.

Webclient Layout choice enhancement to allow for different use cases and persistence across different browsers/devices.

#### Describe the solution you'd like

Being able to open up the settings menu and select a new layout from a set of defaults (like "small screen", "mobile", "large screen") and the ability to create/name custom saved layouts per account.

#### Additional context
From IRC discussion:

    So localstorage is for Session-In-Progress layout changes, and in settings we'll need... an editable dropdown with default+serverside layouts to choose from and a place to enter-a-new-layout-name and a "Save" button to store the Session-In-Progress layout up to the server (either as the new name or to replace an existing named layout).

**Comment by Griatch** [comment]
Consolidated with https://github.com/evennia/evennia/issues/2226
