### ISSUE TITLE
[Feature Request] Refactor evennia.js so JavaScript is usable in other contexts, for example React Native

### ISSUE THREAD

**Issue by globophobe** [evennia/evennia#2238]
#### Is your feature request related to a problem? Please describe.
evennia.js is web specific, i.e. `$(document).ready()`

#### Describe the solution you'd like
Refactor so JS can be usable in other contexts, for example React Native

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by Griatch** [comment]
There is too little information here as to what changes would be needed to accomplish this and how it would affect existing behavior.

**Comment by globophobe** [comment]
n/m, was wrong to request this
