### ISSUE TITLE
[BUG] incorrect HTML generated for TAB characters in the webclient

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#2239]
#### Describe the bug

When the server creates HTML for the webclient, |- and |> are not translated to expected output.

#### To Reproduce

@py self.msg("|-This should be indented.|>And this should be spaced out.");
prints:
This should be indented.|>And this should be spaced out.

#### Expected behavior
expect output:
`<div color="...">&nbsp;&nbsp;&nbsp;&nbsp;This should be indented.<tab></tab>And this should be spaced out.</div>`

#### Environment, Evennia version, OS etc
Evennia 0.9 latest.

#### Additional context
related to decisions from issue #1393

**Comment by Griatch** [comment]
Resolved in 24c59172033babc5fd37b971ac70ed9044e6b287 .

**Comment by Griatch** [comment]
Actually said commit fixes the `|-` bit. Not sure how `|>` (actual TAB character) would be implemented in the webclient HTML.

**Comment by friarzen** [comment]
As far as I can see, the only way to make this work is:
<span style="white-space:pre">&#9;</span>
