### ISSUE TITLE
[BUG] Webclient fetches favico.js from broken CDN

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#2241]
#### Describe the bug

Users have reported errors from the webclient tryring to fetch the `favico.js` library with `<script src="https://cdn.rawgit.com/ejci/favico.js/master/favico-0.3.10.min.js"`. Apparently that CDN is broken. 

This should be verified and a better CDN picked.

**Comment by friarzen** [comment]
I cannot reproduce this, maybe the CDN files got fixed or there was some other issue.

**Comment by Griatch** [comment]
Agreed, I can't reproduce this either. As @friarzen says, maybe it was some termporary issue with the CDN.
