### ISSUE TITLE
[Documentation] Incorrect line anchor in to-the-code link

### ISSUE THREAD

**Issue by Vikka** [evennia/evennia#2242]
#### Documentation issue
On the page [Python basic tutorial part two](https://github.com/evennia/evennia/wiki/Python-basic-tutorial-part-two):

> This means that DefaultCharacter is in itself a child of something called DefaultObject! Let's see what this parent class provides. It's in the same module as DefaultCharacter, you just need to scroll up near the top

The link redirect to: [https://github.com/[...]/objects.py#L182](https://github.com/evennia/evennia/blob/master/evennia/objects/objects.py#L182)
#### Suggested change
It should redirect to: [https://github.com/[...]/objects.py#L193](https://github.com/evennia/evennia/blob/master/evennia/objects/objects.py#L193)

**Comment by Griatch** [comment]
The trouble with linking to line numbers - the source code changed since this was written :)

**Comment by Vikka** [comment]
I didn't find a way to update the wiki, is it possible ?

**Comment by Griatch** [comment]
@Vikka: Please read the first line of the wiki: https://github.com/evennia/evennia/wiki

**Comment by Vikka** [comment]
Oups, I forgot that, sorry.
