### ISSUE TITLE
[BUG] Underline is not terminated properly in EvForm Webclient

### ISSUE THREAD

**Issue by PeaceBrigade** [evennia/evennia#2244]
#### Describe the bug

When mapping into an EvForm on the webclient and using the text tag |u to start underlining, |n does not end it and return to normalized text.

#### To Reproduce
1. Create an EvForm with something simple like xxxxxx1xxxxxx xxxxxx2xxxxxx
2. Map values 1 and 2, including |u in the first map. Ex: "|uUnderline|n" and "Not Underline"
3. The underline will not end in the displayed form in the webclient. (Have not tested other clients.) It will extend and keep the underline throughout the entirety of the rest of the form. (If color is used it will also taint the "default color" of the rest of the form. For example if you used "|y|uUnderline|n" all further text in the form not contained in text tags will be turned yellow.

#### Expected behavior
|n should remove all text formatting. (Theory is that some HTML tags in web client are not closed properly)

#### Environment, Evennia version, OS etc
Evennia 0.9.5 (rev d4053b3bc) (rev d4053b3bc)
OS: posix
Python: 3.7.5
Twisted: 20.3.0
Django: 2.2.16

#### Additional context
Not sure how to solve, but I'm sure the complexity arises and is a problem of maybe not knowing what HTML tags are currently "open" beforehand to automatically close them with their counter-tag when using |n within.

It should be noted that in other areas like using SAY for example:
"|uUnderline|n Not Underline
Yields the expected result and properly terminates the Underline.

**Comment by Griatch** [comment]
This is a known issue of the webclient ANSI2HTML parser and likely would require a change of the parser itself to resolve. So keeping it open as a reminder, but this will not be addressed in the short term.

**Comment by Madeintheshade** [comment]
The only question I have on that subject is.
What is the ultimate desired result that you're trying to achieve.

**Comment by Griatch** [comment]
Fixed in #2739
