### ISSUE TITLE
[Feature Request] Allow for non-interactive createsuperuser

### ISSUE THREAD

**Issue by srmeier** [evennia/evennia#2248]
#### Is your feature request related to a problem? Please describe.
When deploying Evennia in a test environment where the DB gets wiped on each deploy, it would be nice if I could specify the super user creds using environmental variables.

#### Describe the solution you'd like
This might be an anti-pattern, so I'm interested in other's opinion, but could we do something like the following?
```python
def create_superuser():
    """
    Create the superuser account

    """
    print(
        "\nCreate a superuser below. The superuser is Account #1, the 'owner' "
        "account of the server. Email is optional and can be empty.\n"
    )
    from os import environ
    if ("DJANGO_SUPERUSER_USERNAME" in environ) and ("DJANGO_SUPERUSER_EMAIL" in environ):
        username = environ["DJANGO_SUPERUSER_USERNAME"]
        email = environ["DJANGO_SUPERUSER_EMAIL"]
        django.core.management.call_command("createsuperuser", "--noinput",
                                            "--username=" + username,
                                            "--email=" + email, interactive=False)
    else:
        django.core.management.call_command("createsuperuser", interactive=True)

    if "DJANGO_SUPERUSER_PASSWORD" in environ:
        password = environ["DJANGO_SUPERUSER_PASSWORD"]
        from evennia.accounts.models import AccountDB
        u = AccountDB.objects.get(username=username)
        u.set_password(password)
        u.save()
```
Of course you could have the username without the email, as the email is optional. Let me know if this seems reasonable and can create a PR.

#### Describe alternatives you've considered
I could be missing something but the alternative seems to be to type in the information manually whenever setting up a new DB.

#### Additional context
N/A

**Comment by jerryaldrichiii** [comment]
Hey! I had the same issue. I ended up doing something like this in my Dockerfile entrypoint.sh

```
EVENNIA_SUPERUSER_USERNAME=${EVENNIA_SUPERUSER_USERNAME:-"changeme"}
EVENNIA_SUPERUSER_EMAIL=${EVENNIA_SUPERUSER_EMAIL:-"nobody@nowhere.com"}
EVENNIA_SUPERUSER_PASSWORD=${EVENNIA_SUPERUSER_PASSWORD:-"changemeorbehacked"}
superuser_script="
from django.contrib.auth import get_user_model;

User = get_user_model()

superuser_username='$EVENNIA_SUPERUSER_USERNAME'
superuser_password='$EVENNIA_SUPERUSER_PASSWORD'
superuser_email='$EVENNIA_SUPERUSER_EMAIL'
if not User.objects.filter(username=superuser_username).exists():
    User.objects.create_superuser(
      username=superuser_username,
      password=superuser_password,
      email=superuser_email
    );
"
printf "$superuser_script" | evennia shell
```

but it required the following change in Evennia:

```patch
diff --git a/evennia/server/evennia_launcher.py b/evennia/server/evennia_launcher.py
index 9fed573ca..b49b383f6 100644
--- a/evennia/server/evennia_launcher.py
+++ b/evennia/server/evennia_launcher.py
@@ -2259,7 +2259,7 @@ def main():
         if option in ("makemessages", "compilemessages"):
             # some commands don't require the presence of a game directory to work
             need_gamedir = False
-        if option in ("shell", "check", "makemigrations", "createsuperuser"):
+        if option in ("check", "makemigrations"):
             # some django commands requires the database to exist,
             # or evennia._init to have run before they work right.
             check_db = True
@@ -2275,6 +2275,10 @@ def main():
                 django.core.management.call_command(*([option] + unknown_args))
                 sys.exit(0)
 
+        # TODO: Check some parts of the database first
+        if option in ("createsuperuser", "shell"):
+            evennia._init()
+
         # pass on to the core django manager - re-parse the entire input line
         # but keep 'evennia' as the name instead of django-admin. This is
         # an exit condition.
```

This was because the `evennia shell` would do a full database check before executing which was failing in my case as I was trying to create the superuser before it.

**Comment by srmeier** [comment]
Very interesting! Thanks for sharing. It's also good to know I'm not the only one facing this.

**Comment by jerryaldrichiii** [comment]
Yeah we both worked around it in different ways it seems.

This is an active project with quite the community. I'm sure someone will have a better solution :D 

Though yours is pretty good imho.

**Comment by srmeier** [comment]
Thanks! If one of the maintainers thinks this approach is reasonable I can clean it up, PR, and we can begin reviewing. I was thinking someone probably had a better solution in mind or might have a good reason for why Evennia shouldn't support this kind of thing and suggest a work around.

If this isn't something Evennia wants to support, I like your approach. But like you mention some of the operations need to be ordered correctly so that `createsuperuser` doesn't fail.

**Comment by Griatch** [comment]
@srmeier, @jerryaldrichiii Sorry for not getting back to you on this before now. This looks like a good idea. Between the two solutions offered here I think @srmeier's is likely the cleanest one; it should work also for those wanting to use docker (you can just pass the envvars into the docker if so desired). 

I'd be interested in a PR against `develop` branch for this one :+1:.

**Comment by srmeier** [comment]
> @srmeier, @jerryaldrichiii Sorry for not getting back to you on this before now. This looks like a good idea. Between the two solutions offered here I think @srmeier's is likely the cleanest one; it should work also for those wanting to use docker (you can just pass the envvars into the docker if so desired).
> 
> I'd be interested in a PR against `develop` branch for this one 👍.

No problem, will make changes and PR for review.
