### ISSUE TITLE
[BUG] "have connected within the last seven days" is stuck at 4

### ISSUE THREAD

**Issue by Vikka** [evennia/evennia#2257]
#### Describe the bug
In the main page of the website https://demo.evennia.com/, the number of connected account in the last 7 days is always 4, in evdemo and mine too : http://www.terazur.online/
![picture of the error:  "and 4 have connected"](https://user-images.githubusercontent.com/9381120/99882006-93c88d80-2c1d-11eb-862c-4c4ef17c74e6.png)

#### To Reproduce
1. Create an account on https://demo.evennia.com/webclient/,
2. Connect the new account
3. Reload the main page of https://demo.evennia.com/
4. See error "X have connected within the last seven days". In my case, it is stuck at 4.

#### Expected behavior
Should change depending of the number of account connected in the last 7 days.

#### Environment, Evennia version, OS etc
    Evennia 0.9.5 (rev 5f361fbd5) (rev 5f361fbd5)
    OS: posix
    Python: 3.8.5
    Twisted: 20.3.0
    Django: 2.2.17

**Comment by strikaco** [comment]
Silly bug.

https://github.com/evennia/evennia/blob/c5ad25a1115c6e1d26334985a486945fffcb10b1/evennia/web/website/templates/website/index.html#L62

The var for this is defined here:

https://github.com/evennia/evennia/blob/c5ad25a1115c6e1d26334985a486945fffcb10b1/evennia/web/website/views.py#L68

...which is composed from:

https://github.com/evennia/evennia/blob/c5ad25a1115c6e1d26334985a486945fffcb10b1/evennia/web/website/views.py#L40-L44

...and so:

```
num_accounts_connected_recent == nplyrs_conn_recent == len(recent_users) == 4
```

**Comment by Vikka** [comment]
In order to fix this, I guess it's not just 
```python
 recent_users = AccountDB.objects.get_recently_connected_accounts() 
```
does it ?

**Comment by strikaco** [comment]
> In order to fix this, I guess it's not just
> 
> ```python
>  recent_users = AccountDB.objects.get_recently_connected_accounts() 
> ```
> 
> does it ?

You're on the right track; it's _almost_ that simple.

Two minor additions:

```
# remove the slicing to retain a regular queryset
recent_users = AccountDB.objects.get_recently_connected_accounts() <-- YOUR SOLUTION

# change to existing code-- don't use len to count objects in a queryset; use count() to take advantage of caching
nplyrs_conn_recent = recent_users.count() or "none" <-- MY RECOMMENDATION
```

`recent_users` shows up again a few lines later:

https://github.com/evennia/evennia/blob/c5ad25a1115c6e1d26334985a486945fffcb10b1/evennia/web/website/views.py#L65

Eventual presentation is probably what the slicing was intended for, so we'll be courteous and re-add it at the last possible opportunity:

```
"accounts_connected_recent": recent_users[:fpage_account_limit],
```

Haven't tested it but I don't see why this wouldn't work.

**Comment by Griatch** [comment]
@strikaco Yes, this is the fix. I've fixed this locally in develop some time ago, but since it shows in master I should probably also push a fix there - I've just not gotten to this issue yet, with so many things to do for next Evennia version. :sweat_drops:
