### ISSUE TITLE
[Feature Request] Lowercase search_prototype.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2261]
#### Is your feature request related to a problem? Please describe.
The [evennia.prototypes.prototypes.search_prototype() method](https://github.com/evennia/evennia/blob/master/evennia/prototypes/prototypes.py#L335) will fail to find a matching prototype if the supplied key has any uppercase characters.

#### Describe the solution you'd like
I think that the key given to the method could be forced into all lowercase: `key = key.lower()` 

This should probably be done somewhere at the top, but there's multiple `if key` statements, so I'm uncertain of where this would go.

#### Additional Thoughts
There may be other areas where this would be useful, but I've only used `search_prototype()` recently, so it's the only one that I can confirm would benefit from this change. I haven't used the tags in this method yet either, but perhaps they have the same issue?

**Comment by Henddher** [comment]
Hi @Griatch, should this ticket be closed now the the PR was merged?
