### ISSUE TITLE
[BUG] MuxCommand - lhslist/rhslist not consistently typed

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2290]
#### Describe the bug
Despite `lhslist` and `rhslist` both containing the operative word `list`, `MuxCommand.parse()` will instead store an empty `str` if no terms were provided.

#### To Reproduce
https://github.com/evennia/evennia/blob/574d7fbd4f65cae60c534fe592803057d452ed7b/evennia/commands/default/muxcommand.py#L177-L179

#### Expected behavior
This really ought to always be a `list`. It leads to unpredictable behavior when trying to access elements by index.

#### Environment, Evennia version, OS etc
```
Evennia 0.9.5 (rev 9d90b52) (rev 9d90b52)
    OS: posix
    Python: 3.7.9
    Twisted: 20.3.0
    Django: 2.2.12
```

**Comment by strikaco** [comment]
This problem is shared by regular `lhs`/`rhs` as well-- `lhs` seems to always be a `str`, but `rhs` can be either `str` or `None`.

https://github.com/evennia/evennia/blob/574d7fbd4f65cae60c534fe592803057d452ed7b/evennia/commands/default/muxcommand.py#L174-L176

Since the entire thing is a _string parsing and interpretation_ process, tokenization really should not be dealing in types other than `str`. 

I know there is some advanced functionality with JSON parsing for certain commands but even there, "null" JSON structures `""`, `{}` and `[]` are not explicitly `None`.

**Comment by Griatch** [comment]
I can see the argument for lists. I don't recall if there is a functional difference between letting `rhs` be ˋNoneˋ  or ˋ""ˋ though, one indicating `=` with nothing following, and the other indicating no `=` at all... one would need to review the existing commands to make sure there is no difference assumed anywhere.

**Comment by strikaco** [comment]
Hmm. The intent behind the lhs/rhs thing makes more sense to me now, as that follows what regex itself will do with optional capture groups. So there is at least precedent for that behavior.

**Comment by Griatch** [comment]
I changed so lhs/rhslists are always lists in #2290. I don't change rhs/lhs though. Closing this.
