### ISSUE TITLE
[BUG] SessionHandler - TypeError, 'set' object is not subscriptable

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2298]
#### Describe the bug
Minor bug involving passing a `set` as a kwarg to the `msg` method-- the `set` is correctly identified as an iterable, but is then presumed to be subscriptable in subsequent operations. 

https://github.com/evennia/evennia/blob/574d7fbd4f65cae60c534fe592803057d452ed7b/evennia/server/sessionhandler.py#L252-L262

This does not work on `set` objects.
```
self.msg(locks=set(keys))
```

```
 File "/home/ubuntu/workspace/evennia/evennia/server/sessionhandler.py", line 253, in clean_senddata
    if isinstance(data[-1], dict):
TypeError: 'set' object is not subscriptable
```
#### Expected behavior
Force casting of `data` to `tuple` between L252 and L253?

**Comment by Griatch** [comment]
Sounds like a good fix to add.

**Comment by Griatch** [comment]
Followed the suggestion and converted to `tuple`. Implemented in `develop` branch.
