### ISSUE TITLE
[Documentation] Github default branch changed from master to main.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2304]
#### Existing page / new
https://www.evennia.com/docs/latest/Version-Control.html#pushing-your-code-online

#### Documentation issue
Github changed the name of the master branch to main branch. The instructions in Evennia's documentation are outdated.

#### Suggested change
Here's the official instructions in Github's quick setup guide after creating a new repo.
```
git remote add origin https://github.com/kovitikus/abracadabra.git
git branch -M main
git push -u origin main
```

**Comment by Griatch** [comment]
Updated the doc with a reference to the use of `main`.
