### ISSUE TITLE
[BUG] UnixCommand - Optional argument "help" labeled as "hel"

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2305]
#### Describe the bug
"Help" is added as an optional argument to all UnixCommand children, but under the name "hel" instead of "help."

Not sure if this was intentional/designed not to conflict with something else, but confounded me for a while as to why the `hel` property kept getting added to the options namespace.

```
Namespace(attr=['name'], hel=None, quiet=False, what='date', where=('me', 'here'))
```

#### To Reproduce
https://github.com/evennia/evennia/blob/574d7fbd4f65cae60c534fe592803057d452ed7b/evennia/contrib/unixcommand.py#L124-L127

#### Expected behavior
Correct spelling.

#### Additional context
This command class is woefully underrated and absolutely _insane_ in how flexible it is. Argparse is a little dense at first but I am moved to tears when I consider the number of hours I've wasted on parsing-related issues with the other classes.

Props to @vincent-lg / @v-legoff for implementing it!

**Comment by Griatch** [comment]
@strikaco Yeah, that looks like a typo, the adjoining comment even says that it should be `--help`. I fixed that now in in `develop` branch. And yes, vincent's `UnixCommand` is very powerful indeed! He'll be glad to hear you like it!
