### ISSUE TITLE
[Documentation] Documentation pages should have a handy link back to evennia.com

### ISSUE THREAD

**Issue by j3b4** [evennia/evennia#2310]
#### Existing page / new
The Documentation pages here:
    https://www.evennia.com/docs/latest/index.html

Only the index page has a link back to  the Evennia home page (https://www.evennia.com).

#### Documentation issue

Once one goes any deeper into the documentation it becomes inconvenient to get quickly back to the home page for example if you want to move to the forum or irc.

#### Suggested change
Place a link in the left hand side navigation bar.

Perhaps the link beneath the Evennia logo could be repurposed. Presently it links back to the Documentation home but is redundant because the top and bottom bars of the documentation pages already contain a breadcrumb trail.

**Comment by Griatch** [comment]
A link section with several useful links is now added to the documentation side bar.
![DeepinScreenshot_select-area_20210406214807](https://user-images.githubusercontent.com/294267/113769926-d3ea6180-9721-11eb-9da3-ee1fe6675cf6.png)
