### ISSUE TITLE
[BUG] Container.load_data() doesn't catch all import errors

### ISSUE THREAD

**Issue by TehFamine** [evennia/evennia#2334]
#### Describe the bug
load_data(self) is called in def _load_script(self, key) within containers.py when loading GLOBAL_SCRIPTS. If there are any issues with your scripts when passing to GLOBAL_SCRIPTS via settings.py that is not apart of the ImportError exception in load_data(self), then loading of that script could fail without any correct feedback to the user or log.

#### To Reproduce
1. Define a new Script object in typeclasses.scripts.py
2. Mimic a circular import error between scripts.py and another py file.
3. Define the script in GLOBAL_SCRIPT in your settings.py
4. See error in the form of a KeyError of the script object

#### Expected behavior
I had a circular import issue with scripts.py and another py file. This caused _load_script() to return a KeyError of the script when defined in GLOBAL_SCRIPTS. The KeyError was because load_data() was not able to load the script file due to circular import issue. The exception was only an ImportError and thus, no feedback was sent to me until I added a broader exception to see what was causing load_data(self) to fail. I expected the behavior of load_data to tell me exactly what the exception was.

#### Environment, Evennia version, OS etc
    Evennia 0.9.5 (rev b3ac55b58) (rev b3ac55b58)
    OS: nt (Windows 10 64-bit)
    Python: 3.8.6 (PipEnv)
    Twisted: 20.3.0
    Django: 2.2.19

#### Additional context
I would just put more exception catches in load_data(self) to catch more issues with scripts.

**Comment by TehFamine** [comment]
Just to be clear. I put this as bug as this should have thrown the import error exception because the method couldn't import the script, but instead, got a key error with no feedback on the real issue (e.g.: circular import issue).

**Comment by BigJMoney** [comment]
I'm running into this, but I don't understand why my import chain is considered a circular import. Here are what my files look like. Is this a separate bug, or also expected to fail?

File1.py
```
from evennia import GLOBAL_SCRIPTS

TEST_SCRIPT = GLOBAL_SCRIPTS.my_test_script

class TestClass:
    pass
```

File2.py
```
from typeclasses.scripts import Script
from file1 import TestClass

class MyTestScript(Script):
    pass
```

settings.py
```
GLOBAL_SCRIPTS = {
    'my_test_script': {
        'typeclass': 'file2.MyTestScript',
        'persistent': True
    }
}
```
