### ISSUE TITLE
[BUG] Default `typeclass` command should not allow to change to typeclass meant for another table

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#2350]
#### Describe the bug

The default `typeclass` command will allow to set a typeclass from the wrong table of the object being modified. This leads to 
very confusing and potentially disastrous errors sine the `#dbref` given to `typeclass` is always assumed to be that of an `ObjectDB`. It can require using `evennia dbshell` to resolve with direct SQL queries, which is not something we want users to regularly have to face ...

#### To Reproduce
1. `typeclass #<existing_ObjectDB_dbref> = typeclasses.accounts.Account`
2. Errors appear. 

#### Expected behavior

Trying to assign a typeclass from another table than the target should at the very least be forbidden. The `typeclass` 
command is also a bit confusing since one can argue it's logical that if you try to assign an Account typeclass, the `#dbref` 
you provide would then search the `AccountDB` table.

There are a few possible solutions:
- Simplest: The `typeclass` command should analyze the typeclass base and make sure it's an `ObjectDB`, fail otherwise. 
- More powerful: The `typeclass` should analyze the given typeclass-path and search `#dbrefs` from the matching table as that typeclass.

Either way, we should also add some extra protection on the TypedObject model level to avoid it getting a Typeclass-path set to point to another table. There is never a case when a typeclass should be allowed to cross the Table boundary.

#### Environment, Evennia version, OS etc
Master branch. 

#### Additional context

This appeared after a strange situation where user Fari would find an Account of another user in their inventory. The working hypothethis suggested by @TehomCD is that the ContentsHandler loads the object (by #dbref, using its `db_location`) but as it loads its Typeclass is initialized which changes its `__db_class__`, now making the thing in the inventory a full-fledged Account while in memory. Has not been able to reproduce this though.

**Comment by fariparedes** [comment]
This can really mess up your MU* if you do it. My solution:

1. Typeclass the object back to an object class.
2. Shut down the server
3. Access the DB manually and delete the object (the destroy command and admin panel will not work)
4. Delete any references to the object in attributes/tags
5. Set the account typeclass back to the account class (it will have also had its typeclass changed when you typeclassed the object)
6. Reboot the server

**Comment by Griatch** [comment]
@fariparedes I think rather than deleting, the less messy way is probably to stop the server, go into `evennia dbshell` and do

    UPDATE objects_objectdb SET db_typeclass_path='typeclasses.objects.Object' where id=<id>;

On reloading, everything worked again for me and there was no need to remove references/foreignkeys. 

This doesn't change the fact that we should not allow this off-table path be added in the first place of course. :sweat:

**Comment by strikaco** [comment]
> More powerful: The typeclass should analyze the given typeclass-path and search #dbrefs from the matching table as that typeclass.

Wouldn't this still present the same problem? Integer PKs are not sequential across tables, so ID 123 can exist (and be different objects) on AccountDB, ObjectDB, ScriptDB, etc. We'd have to be using GUIDs for this to work.

I think we'd be better served loading the intended class and comparing its meta/concrete class against the current object's. They should always match (ObjectDB and ObjectDB, ScriptDB and ScriptDB, etc.). This will also prevent setting of typeclasses that don't exist.

More hackish, but we could also do an aggregation of all distinct typeclass paths for the current object's model and not allow a change to a typeclass that does not already exist in that table.

The ContentTypes contrib is useful for this sort of thing.
