### ISSUE TITLE
[Documentation] EvMenu Template Links

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2354]
#### Existing page / new
https://www.evennia.com/docs/latest/EvMenu.html

#### Documentation issue
Links on this page that redirect to this page's template section are broken.
Current Link:
https://www.evennia.com/docs/latest/EvMenu.html#Evmenu-templating-language

Proper Link:
https://www.evennia.com/docs/latest/EvMenu.html#evmenu-templating-language

#### Suggested change
It seems to be entirely an issue of the capital E in the URL that breaks the links.

**Comment by Griatch** [comment]
Updated and implemented for the 1.0 documentation.
