### ISSUE TITLE
[BUG] utils.delay() won't store in db attribute.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2366]
#### Describe the bug
Attempting to store a delay() in object.db causes an infinite recursion error.
```
  File "c:\evennia\evennia\utils\dbserialize.py", line 587, in <listcomp>
    return item.__class__([process_item(val) for val in item])
  File "C:\evenv\Lib\site-packages\twisted\internet\defer.py", line 741, in send
    result = getattr(self, 'result', _NO_RESULT)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

#### To Reproduce
1. Create a utils.delay() and store it in a variable.
2. Store that variable on a typeclassed object as an attribute.

#### Expected behavior
Recalling the delay from the attribute should allow the user to `.cancel()` it.

#### Environment, Evennia version, OS etc
```
         Evennia version: 0.9.5 (rev 35940cc93)
         OS: nt
         Python: 3.8.5
         Twisted: 20.3.0
         Django: 2.2.19

         Licence https://opensource.org/licenses/BSD-3-Clause
         Web http://www.evennia.com
         Irc #evennia on irc.freenode.net:6667
         Forum http://www.evennia.com/discussions
         Maintainer (2010-)   Griatch (griatch AT gmail DOT com)
         Maintainer (2006-10) Greg Taylor
```

**Comment by davewiththenicehat** [comment]
Delay has a persistent argument. I stored my delay as an nattribute. With completion time to the database. My callback function deletes the attributes once called or canceled. If you have not worked with cancel yet it errors if callback or errback deferred methods have not been called yet. Easiest way to cancel is pause cancel than remove.

**Comment by fariparedes** [comment]
> 
> 
> Delay has a persistent argument. I stored my delay as an nattribute. With completion time to the database. My callback function deletes the attributes once called or canceled. If you have not worked with cancel yet it errors if callback or errback deferred methods have not been called yet. Easiest way to cancel is pause cancel than remove.

That's certainly good info but unfortunately isn't relevant to the bug! The bug occurs when storing a reference to a delay with the persistent argument set to True in a regular attribute.

**Comment by Griatch** [comment]
This is not supported. The return from `delay()` is a Twisted `deferred` which is is eternally iterable (that's why you get a maximum recursion here) but also would be pointless to pickle to the database since it's an in-memory reference.
