### ISSUE TITLE
[Feature Request] Ticker Handler - Return a handle to the subscription object, provide a method to check if exists

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2367]
#### Is your feature request related to a problem? Please describe.
The ticker handler is cool but very easy to oversubscribe. If you don't keep some sort of reference to the subscription parameters (or someone changes the ticker speed attribute or something without you knowing) it becomes impossible to single out specific subscriptions.

#### Describe the solution you'd like
* Return a "handle" (just a `namedtuple` or something) containing the creation parameters when subscriptions are added, and a method to easily cancel it/remove it from the rotation.
* Add some sort of method to check what subscriptions exist for a given hook. I'm often finding hooks I need to stop, but I don't know the interval or idstring used to create it and am forced to kill everything.

**Comment by Griatch** [comment]
This has been implemented in develop branch, along with the introduction of the `utils.repeat` helper function that uses the tickerhandler under the hood in the same way as `utils.delay` uses the taskhandler.
