### ISSUE TITLE
[BUG] Website - Generic form does not display error messages

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2368]
#### Describe the bug
The generic form template extends base.html and overwrites the body block.

The body block normally displays generic success/failure messages with the inclusion of messages.html, but it is overwritten in this case. Form errors are the only ones accounted for.

https://github.com/evennia/evennia/blob/a07def36aa34d135803792c7afb00d1215a9bd35/evennia/web/website/templates/website/base.html#L32-L45

The form template does not read the messages from the queue. Because of that, they end up being drawn from the message queue and presented on unrelated pages, which is confusing.

https://github.com/evennia/evennia/blob/a07def36aa34d135803792c7afb00d1215a9bd35/evennia/web/website/templates/website/generic_form.html#L1-L51

#### Additional context
Easy to fix. Just add `{% include 'website/messages.html' %}` to L17 of generic_form.html.

**Comment by Griatch** [comment]
Added in develop branch.
