### ISSUE TITLE
[Documentation] Broken Links on Contributing Doc

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2371]
#### Existing page / new
https://www.evennia.com/docs/latest/Contributing.html

#### Documentation issue
http://www.ohloh.net/p/evennia link is broken and leads to an insecure site warning.

The `one-time donation` link to PayPal simply leads to a page that says `Fatal Failure`

`[Forking Evennia](Version- Control#forking-evennia)` is a broken link that should lead to
https://www.evennia.com/docs/latest/Version-Control.html#forking-evennia

`[Pull Request][pullrequest]` is another broken link. Unsure of the page it's supposed to lead to.

`[patch][patch]` another dead link to I dunno where.

 `[new tutorial][tutorials]` is broken and I assume supposed to lead to the Tutorials directory.

`[Code style guidelines][codestyle]`

There's also some really big huge mess of text at the bottom.
![huge mess of text](https://i.imgur.com/QZS18Zv.png)

#### Suggested change
Update the links.

**Comment by Griatch** [comment]
`How-To-Get-And-Give-Help.md` was merged into one `Contributing.md` doc in new version of docs; updated the broken links at the same time.
