### ISSUE TITLE
[Feature Request] Examine Command - Add inspection of script and channel objects.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2375]
#### Is your feature request related to a problem? Please describe.
Scripts are currently undergoing an overhaul to be more focused on the fact that they are "global" objects and are great for storing of information on attributes and via tags. Unfortunately, there is no way to examine them in-game as you would other objects. 

#### Describe the solution you'd like
The account object is examined via the `*` modifier. I propose that examine also gain new options to modify the command when attempting to view both script and channel objects.

***

**Examine Command**
```
get detailed information about an object

Usage:
  examine [<object>[/attrname]]
  examine [*<account>[/attrname]]

Switch:
  account - examine an Account (same as adding *)
  object - examine an Object (useful when OOC)

The examine command shows detailed game info about an
object and optionally a specific attribute on it.
If object is not specified, the current location is examined.

Append a * before the search string to examine an account.
```

**Comment by strikaco** [comment]
One thing that would help with most of these alternating-table commands is switching the base class from MuxCommand to UnixCommand.

UnixCommand would let one specify the table using an optional, but mutually-exclusive argument group (defaulting to Objects). It's much more flexible for commands like this which require context-- and if keyed to ContentTypes, could allow examination of literally any object (not just typeclasses!). 

Custom models would be a hell of a lot easier to work with if they could be `examine` like any other object.

```
examine here # defaults to --objects
examine --scripts #23
examine --accounts #666
examine --economy.sales #5 # custom model lookup! Should display text rendering of the object's ModelForm
```

**Comment by strikaco** [comment]
(#1104 would benefit from a solution to this as well.)

**Comment by strikaco** [comment]
(#1987 would benefit from a solution to this as well.)

**Comment by Griatch** [comment]
Default commands are based on MuxCommand we won't be starting to use a contrib style for those. `examine/scripts` works just as well and could be equally exclusive depending on implementation. And `--economy.sales` is not a 'unix' style syntax anyway (at least not any I've ever seen), so if one wanted something arbitrary one could just as well do it as `examine economy.sales` (not using a switch at all, while still fitting in the mux-style syntax).

**Comment by strikaco** [comment]
> And `--economy.sales` is not a 'unix' style syntax anyway (at least not any I've ever seen), so if one wanted something arbitrary one could just as well do it as `examine/economy sales` or similar.

`economy.sales` is just an example of a possible shorthand way to address any given Django model by app and model name. You split on the period and pass both args to a ContentType lookup. 

"Proper" syntax in this case would be more like `--app economy --model sales` but that's a bit clunky since both fields are optional but both are required if either is invoked. Something like `--db objectdb` (default) or `--db economy sales` would be a more accurate implementation idea.

MuxCommand args and switches don't really allow much in the way of _context_ without a bunch of custom parsing and validation, which leads to overloaded methods that are difficult to extend-- hence my promotion of UnixCommand.

**Comment by Griatch** [comment]
The closest we have to this style of syntax is what we have for the `set` default command, which is given as 

    set objname/attrname = value

So something like this would work:

    examine/objectdb objname/attrname

I'm not rewriting all the default commands to UnixCommand-style at this point :sweat_smile:. Maybe something for an Evennia 2.0 heh.
