### ISSUE TITLE
[BUG] `set/edit here` gives IndexError

### ISSUE THREAD

**Issue by Enfors** [evennia/evennia#2382]
#### Describe the bug
When attempting to use the editor to edit a room description from a MUD client (TinyFugue), I'm getting an IndexError when I press enter, and the editor doesn't start. The same thing seems to happen in all rooms I've tried it from, including my "home" room.

#### To Reproduce
1. set/edit here
This produces the following error:
```
Traceback (most recent call last):
  File "/home/enfors/devel/python/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
    ret = cmd.func()
  File "/home/enfors/devel/python/evennia/evennia/commands/default/building.py", line 1877, in func
    self.edit_handler(obj, attrs[0])
IndexError: list index out of range

An untrapped error occurred.
(Traceback was logged 21-04-16 10:15:42).
```
#### Expected behavior
I was expecting the editor to start and to allow me to edit the room description.

#### Environment, Evennia version, OS etc
```
Evennia version: 0.9.5 (rev 251a70275)
OS: posix
Python: 3.7.5
Twisted: 20.3.0
Django: 2.2.20
```

#### Additional context
This is running on Kubuntu GNU/Linux 20.04.

**Comment by Griatch** [comment]
@Enfors This is not how the `set` command works and it's not documented to work this way anywhere. The way to do this is to either use 
    set/edit here/desc

or 

    desc/edit here

or just 

    desc/edit 

which specifically edits the `desc` Attribute on the current location.

That said, this shouldn't traceback, so I added a more suitable error message now.
