### ISSUE TITLE
[Feature Request] RPSystem Contrib Matching Options

### ISSUE THREAD

**Issue by alephate** [evennia/evennia#2383]
#### Is your feature request related to a problem? Please describe.

I'd like to be able to, in some cases, have unmatched tags in an emote return a generic output. Right now what happens is that it fails to send the emote and delivers an error - "There is no match for <tag>."

#### Describe the solution you'd like

I want to be able to set an option on the functions that in some situations you can tag someone in an emote, and if they're not there, you will see a set sdesc (such as "something") instead of theirs. 

#### Describe alternatives you've considered

In the discord chat we discussed making a dummy object class that would have the necessary features to stand in for a "something". 

#### Additional context

Here is an example of what I mean, using send_emote to send movement messages (I implemented a solution in my own version, but not very tidily).

![image](https://user-images.githubusercontent.com/72240438/115067454-f1a48d00-9ebe-11eb-870b-b726d205cd17.png)

**Comment by Griatch** [comment]
The explicitness here is of course deliberate and goes with Evennia's general approach of not trying to guess if you make a mistake; in a system where recogs matter, asking for clarification is often better than to produce nonsense/generics. 

That said, I suppose one could aim to make this a kwarg on the sdesc replacer function.

**Comment by alephate** [comment]
We had a whole discussion at the time and you asked me to make this feature request. I only made the request because you seemed to think it would be nice, but I have kept fiddling with things and I'm happy with my own fixes. :)

**Comment by Griatch** [comment]
@alephate Yes, I know. I was just clarified why this is this way (same as was clarified in the chat at the time). I do still think this could be useful (but maybe phrased a bit too curtly above), but it would need to be something optional in the RPSystem settings.
