### ISSUE TITLE
[Documentation] search_script docstr missing `returns`

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2384]
#### Existing page / new
https://github.com/evennia/evennia/blob/master/evennia/scripts/manager.py#L214

#### Documentation issue
It doesn't say what it returns, is it a list that I should expect, even if it is one result?

#### Suggested change
Add the `returns` section, as is common in all other docstr.

**Comment by Griatch** [comment]
This was updated as part of manager queryset-return homogenization in develop branch.
