### ISSUE TITLE
rpsystem.send_emote pass from_obj and kwargs to msg call.

### ISSUE THREAD

**Issue by davewiththenicehat** [evennia/evennia#2386]
#### Is your feature request related to a problem? Please describe.
I use gendersub and it shows the pronouns of the receiver when I use emote. Of course this only occurs when the receiver is not the sender.
Also there are some kwargs I send to msg that I would like to support through emote. For example I send `force` to force a message if the receiver is dead. Controlling my messages to concious, unconcious and dead characters.

#### Describe the solution you'd like
I would like to change rpsystem.send_emote. So it sends from_object and kwargs to the msg call on line 569.
I will make certain to check for and remove anonymous_add from kwargs before sending it to msg.

#### Describe alternatives you've considered
I can change my local project instead. I just felt these were values adds. I can retain complete backwards compatability.

**Comment by davewiththenicehat** [comment]
@Griatch I'd like to make a branch for and add the changes above. Would these changes be committable?

**Comment by Griatch** [comment]
Yeah, overall kwargs should be properly forwarded to msg in situations like this.

**Comment by Griatch** [comment]
This was already closed.
