### ISSUE TITLE
[BUG] (Develop) Setup fails due to requirements.txt parse error

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2391]
#### Describe the bug
Trying to `pip install -e evennia` per the docs in a clean environment:

```
Obtaining file:///home/ubuntu/workspace/evennia
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/workspace/EV37/bin/python3.7 /home/ubuntu/workspace/EV37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2c79m5qa
       cwd: /home/ubuntu/workspace/evennia
  Complete output (1 lines):
  error in evennia setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+https:/'": Expected stringEnd
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/workspace/EV37/bin/python3.7 /home/ubuntu/workspace/EV37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2c79m5qa Check the logs for full command output.
```

#### Additional context
This line in requirements.txt is causing the issue:

```
# conjugation library, py3 version
git+https://github.com/markrogersjr/nodebox_linguistics_extended.git
```

Doing `pip install -r evennia/requirements.txt` forces it through. 

After commenting that line out post-manual-installation, the rest installs on a subsequent `pip install -e evennia`. There's something about this URL that setup does not like...

**Comment by TehomCD** [comment]
I wonder why tests wouldn't catch that - they do a pip install as part of the workflow, after all.

**Comment by Griatch** [comment]
@TehomCD They do. actually: https://github.com/evennia/evennia/runs/2357439858?check_suite_focus=true I've just not bothered with cleaning up develop branch yet :sweat_smile:

**Comment by strikaco** [comment]
Just reinstalled in another new environment; problem is no longer reproducible on my end.

**Comment by Griatch** [comment]
Ah, yes this was fixed in develop branch, forgot to close this ticket at the time.
