### ISSUE TITLE
[BUG] (Develop) AttributeHandler `all()` method appears to be checking the wrong permissions

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2392]
#### Describe the bug
...or I can't read.

https://github.com/evennia/evennia/blob/dca152469bde8a04eff838b4c5d5d59c81193a07/evennia/typeclasses/attributes.py#L1200-L1223

L1223 appears to be checking for edit permissions on a read method.

**Comment by Griatch** [comment]
I'd need to look closer as to why it's set that way, but from a quick glance, it does look like it would be the wrong permission, yes.
