### ISSUE TITLE
[Feature Request] AttributeHandler get() method args out of order.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2395]
#### Existing page / new
https://github.com/evennia/evennia/blob/master/evennia/typeclasses/attributes.py#L441

#### Issue
The arguments on this method are listed as `key, default, category` whereas the docstring has them listed in the order of `key, category, default`.

#### Suggested change
@Griatch has informed me that the docstring has the correct order, as this is how it is listed in other areas of the engine. It should be the actual method argument order that is changed to reflect the `key, category, default` standard.

**Comment by Griatch** [comment]
I think I was wrong when first looking at this; the `get(key, default,...)` order is actually the correct one (and reflects how Python's `dict.get()` works too. The doc string was already updated in develop, so closing this.
