### ISSUE TITLE
[Feature Request] Inconsistent kwarg usage in TagHandler add() method.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2396]
#### Is your feature request related to a problem? Please describe.
https://github.com/evennia/evennia/blob/master/evennia/typeclasses/tags.py#L285

The `add()` method calls for a kwarg named `tag=None`, whereas the `get()` method uses `key=None`.

#### Describe the solution you'd like
The kwarg in `add()` should be changed from tag to key. This is more consistent with the rest of the engine and the handler itself.

#### Additional context
This change will break anybody's code that specifically writes out the kwarg as `tag=`.

**Comment by Griatch** [comment]
Adding for Hacktoberfest, for `develop` branch. The old `tag` should still work, but trigger a `DeprecationWarning` for the user to change it.

**Comment by Griatch** [comment]
@dimitrilw Thanks for the look into this, in the end I implemented this with a straight fix without the `DeprecationWarning`, instead documenting the new change in the `CHANGELOG` as a backwards incompatible change.
