### ISSUE TITLE
[Feature Request] Allow a range or sequence of dbids and keys in scripts/kill command.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2397]
#### Is your feature request related to a problem? Please describe.
Killing one script at a time is a complete and absolute pain when doing testing. Especially if the code is already in disarray and generating a plethora of identical scripts.
![1 at a time script killing](https://i.imgur.com/2IKqnIU.png)

#### Describe the solution you'd like
Please add support for killing a range or sequence of scripts, similar to how the destroy command allows a dbid number, key, or combination sequence.

`destroy 48-88`
`scripts/kill 82-281`

`destroy 48, 58, 82, 101, 10, flower, 25`
`scripts/kill 22, 43, 48, 88, 5, instance_script, 73`

#### ALSO
`scripts/kill` requires that the dbref be input, rather than just the id number or range.
![attempting to delete script from dbid only](https://i.imgur.com/lNi4IcP.png)

Please add support for simply entering the dbid instead. This is the same as how `destroy` handles it.
![destroying dbid range](https://i.imgur.com/qYdIHvQ.png)

**Comment by Griatch** [comment]
Should be simple to add, so why not.

**Comment by Griatch** [comment]
Support for `#dbref-#dbref` ranges were added to the new and reworked `scripts` command in `develop` branch.
