### ISSUE TITLE
[Feature Request] DefaultScript.delete() method should return a bool value.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2398]
#### Is your feature request related to a problem? Please describe.
Right now, this condition check on the delete() outcome has no value.
![script deletion check](https://i.imgur.com/7yVefVw.png)

#### Describe the solution you'd like
I'd like to see the `DefaultScript.delete()` method check to make sure the deletion was done properly and then return a boolean value.

Or as @Griatch put it `delete() do a check for pk`

***

*Original Discord conversation regarding this topic:*

*https://discord.com/channels/246323978879107073/246323978879107073/836888801346846720*

**Comment by blongden** [comment]
Just having a look at the tests for this. The API for scripts doesn't match the API for objects (which does have a return value), it's really not safe to assume they'd behave in the same way. script.delete() will raise an exception if the delete fails (ObjectDoesNotExist), so simply removing line two in this example would be equally as valid as checking a return code.

Is there another delete failure that might be encountered? 🤔

**Comment by kovitikus** [comment]
I dunno. This is a very minor request and not something I can claim should happen. If it's found to be pointless, the issue can be closed. I'll let Griatch decide on this, as he's the one currently working on some refactoring of scripts. Perhaps with those changes this suggestion is more relevant.

**Comment by Griatch** [comment]
`script.delete()` returning `None` is normal Django style. It's rather `DefaultObject.delete()` returning something that breaks the mold. I suppose it could make sense to have all `delete()` call work the same for typeclasses though.

**Comment by Griatch** [comment]
Added a boolean return to all major Typeclass.delete methods for consistency.
