### ISSUE TITLE
[Feature Request] (Develop) REST API - ListViews are too verbose

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2401]
#### Is your feature request related to a problem? Please describe.
Kudos to whoever did the legwork on getting DRF implemented. I tried and failed a few times before giving up :)

ListView pagination is currently a very slow operation. Ideally these views should be returning a sparse list of object ids, keys, and _maybe_ readily-available model properties, not crawling and serializing every M2M field on the model by default.

#### Describe the solution you'd like
Reserve this degree of data for DetailViews, where it is implicitly requested. As-is the ListViews are slow, and there is not much point to DetailViews because most/all of the same information is available from the listings.

Thanks!

**Comment by Griatch** [comment]
Fixed in develop branch by limiting the number of entity fields included in lists.
