### ISSUE TITLE
[BUG/Annoyance] Object `get_display_name` - Make `looker=None` by default

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2415]
#### Describe the bug
The syntax for object method `get_display_name` _requires_ a `looker` reference.

This is unnecessary and annoying, since explicitly passing `None` has the same effect as passing almost any other (non-privileged) object. `None` might as well be the default since the effect is the same in _most_ cases.

It also leads to dbref exposure if a message intended for broadcast is tailored to a privileged caller because one felt compelled to provide _something_ as an argument, in cases where they should have abstained:
```
> self.location.msg_contents(f"{self.caller.get_display_name(self.caller)} opens the gate")
# everybody sees:
johnny(#1) opens the gate 

vs

> self.location.msg_contents(f"{self.caller.get_display_name()} opens the gate")
# everybody SHOULD see:
johnny opens the gate 
```
(I know there are some functions that do variable replacement for tailoring custom messages; this is a simplistic example despite them.)

#### Expected behavior
Just make the method definition use `None` as the default value for `looker`.

**Comment by davewiththenicehat** [comment]
```python
if looker == None:
        return self.key
```
Like that?
Than rpsystem contrib would need to return sdesc. Instead of key.

**Comment by strikaco** [comment]
> 
> 
> ```python
> if looker == None:
>         return self.key
> ```
> 
> Like that?
> Than rpsystem contrib would need to return sdesc. Instead of key.

Not quite; the idea would be to make

https://github.com/evennia/evennia/blob/56b1c259f742134a12e1440cae9fe522b75aefe9/evennia/objects/objects.py#L302

into:

```
def get_display_name(self, looker=None, **kwargs):
```

This shouldn't require changes to anything else since it's just establishing a least-privilege default.

**Comment by Griatch** [comment]
Why not. Should be a simple change.

**Comment by Griatch** [comment]
Closed in https://github.com/evennia/evennia/issues/2415.

**Comment by Griatch** [comment]
@strikaco This was fixed now, but note that your example
```python
self.location.msg_contents(f"{self.caller.get_display_name(self.caller)} opens the gate")
# everybody sees:
johnny(#1) opens the gate 
```
is incorrect. Only builders or above would see the dbref, not "everybody", at least with the default version of `get_display_name`.
