### ISSUE TITLE
[Feature Request] (Develop) Add a JSONField to all models

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2418]
#### Is your feature request related to a problem? Please describe.
* Typeclasses are really cool but the EAV architecture makes it difficult to filter or sort by values defined in related Attributes since they are accessed via `through` tables. 
* The rest of the non-Typeclassed models do not allow much in the way of extensibility (if I want to add a `priority` or `ttl` model field to Attributes as alluded to in #2406, I'm SOL unless I fork the project).

##### Arbitrary DB lookups
Suppose I have a queryset of Objects and I want to display only those for which the Attribute value of `weight` is greater than 20. The most straightforward way to do this is to evaluate the queryset and sort/filter the results in-memory. This scales poorly with large querysets. 

It would be preferable to be able to do this on the backend. If I know I need to filter by `weight`, I would add the current value to the JSONField and that value could then be directly referenced through the Object manager using the appropriate syntax.

Lock-checking at scale is even worse; it could be improved by breaking up lockstrings into `dicts` and caching them in a JSONField. Only objects that _have_ a particular lock would need to be checked.

##### Metadata for all objects
Suppose I want to append metadata to arbitrary and fixed models like Attributes or Messages. It's not possible unless I embed it as part of the `value` or `headers`, which would clobber existing values and is not desirable in most cases.

* Storing metadata on Scripts works inconsistently; they can only be associated with Objects. 
* Metadata stored as Attributes or Messages can only be associated with Typeclassed objects as well (barring manual lookups using the `external` fields).
* Only remaining solution is custom models, but those are really best avoided.

#### Describe the solution you'd like
Addition of a JSONField to _every_ model.
* Would allow for lookups of arbitrary keys and values directly from the backend.
* Would allow for emulation of new model fields without needing to _actually extend_ existing models.
* Think of it like a NAttributeHandler alternative that can be accessed by Object managers.

Alternately:
* Make Attributes linkable to any other object via GFK (#1954). Solves the metadata problem, not the filtering/sorting though.
* Create a _new_ model altogether that associates a JSON blob with any other object via GFK (avoids adding a blank JSONField to objects that don't yet need one). Not sure how well the ORM queries optional one-to-one fields as-is, and I think this might be even more self-defeating since GFKs are a pain to traverse through managers.

**Comment by Griatch** [comment]
While I know what you mean, JSONFields is a PostgreSQL-only feature last I checked and dropping support for sqlite3 is not something we are wont to do any time soon. I have not investigated #1954 or GFK in detail at this time.

(It's perfectly possible to query single Attribute-values just fine - the PickleField type handles this automatically by pre-serializing your query and searching by-string - what is not easy is to query sub-content of, say, a pickled dictionary.)

**Comment by strikaco** [comment]
> While I know what you mean, JSONFields is a PostgreSQL-only feature last I checked and dropping support for sqlite3 is not something we are wont to do any time soon. I have not investigated #1954 or GFK in detail at this time.

Django 3.0 made the JSONField backend-agnostic :)

> (It's perfectly possible to query single Attribute-values just fine - the PickleField type handles this automatically by pre-serializing your query and searching by-string - what is not easy is to query sub-content of, say, a pickled dictionary.)

That is true; my example was a bit underexplained. 

Some attributes (like weight in this case) may be dynamically calculated (based on self weight + sum of all contents).

Any time that summation is made, if one caches the current calculated weight in the JSONField, the cached _calculated value_ is accessible to the object manager and can be filtered/sorted using the ORM.

**Comment by Griatch** [comment]
This is not happening, due to needing to recompile sqlite3 to support JSONField. Maybe in the future this will have stabilized, but closing this now.
