### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [evennia/evennia#2420]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine evennia/prototypes/prototypes.py and observe `traverese`, however expect to see `traverse`.
- Examine evennia/contrib/building_menu.py and observe `shorcuts`, however expect to see `shortcuts`.
- Examine evennia/commands/cmdhandler.py and observe `multuple`, however expect to see `multiple`.
- Examine evennia/commands/default/syscommands.py and observe `mulitple`, however expect to see `multiple`.
- Examine CODING_STYLE.md and observe `indendation`, however expect to see `indentation`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/evennia/pull/new/bugfix_typos

Thanks.

**Comment by Griatch** [comment]
Always good with typo fixes!

**Comment by timgates42** [comment]
Thanks @Griatch - have added a PR
