### ISSUE TITLE
[BUG] (Develop) Multimatched commands dropping rest of cmdstring

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2431]
#### Describe the bug
Multimatched commands with args/lhs/rhs are losing this additional data after the command disambiguation.

#### To Reproduce
```
class CmdRetrDemo(MuxCommand):
    """
    Retrieves an object from a container.
    
    """
    key = 'retrdemo'
    
    def func(self):
        self.msg(f"Retrieving {self.lhs}...")

class ContainerCmdSet(CmdSet):
    
    key = 'Container'
    duplicates = True
    
    def at_cmdset_creation(self):
        self.add(CmdRetrDemo)

class Container(Object):
    
    def at_object_creation(self):
        self.cmdset.add(ContainerCmdSet)
```
* Create a Container
* Try to `retrdemo asdfasdf`
* Create another Container
* Try to `retrdemo-1 asdsdfsdf`
* Compare outputs :)

#### Expected behavior
Disambiguated command should retain all optional params.

#### Environment, Evennia version, OS etc
Develop

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/pull/2516
