### ISSUE TITLE
[BUG] File "setup.py" not found

### ISSUE THREAD

**Issue by LimpingNinja** [evennia/evennia#2434]
### Describe the bug
On a fresh install, attempting to run pip install -e evennia from the root leads to the following error:
**ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/limpingninja/muds/evennia/evennia**

### To Reproduce
Exactly followed: https://evennia.readthedocs.io/en/latest/Getting-Started.html#linux-install
The only difference was naming the virtual environment differently.

### Expected behavior
Evennia boots.

### Environment, Evennia version, OS etc
OS: Ubuntu 20.04.2 LTS x86_64 
Kernel: 5.8.0-55-generic 
Python: Python 3.8.5 pip 20.0.2 

### Additional context
**limpingninja@DamagedGoods:~$** cd muds
**limpingninja@DamagedGoods:~/muds$** cd evennia
**limpingninja@DamagedGoods:~/muds/evennia$** ls
bin                  CODING_STYLE.md  evennia      pyproject.toml
CHANGELOG.md         CONTRIBUTING.md  INSTALL.md   README.md
CODE_OF_CONDUCT.md   Dockerfile       LICENSE.txt  requirements.txt
codeql-analysis.yml  docs             Makefile     setup.py
**limpingninja@DamagedGoods:~/muds/evennia$** virtualenv mud
created virtual environment CPython3.8.5.final.0-64 in 56ms
  creator CPython3Posix(dest=/home/limpingninja/muds/evennia/mud, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/limpingninja/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
**limpingninja@DamagedGoods:~/muds/evennia$** source mud/bin/activate
**(mud) limpingninja@DamagedGoods:~/muds/evennia$** ls
bin                  CODING_STYLE.md  evennia      mud               setup.py
CHANGELOG.md         CONTRIBUTING.md  INSTALL.md   pyproject.toml
CODE_OF_CONDUCT.md   Dockerfile       LICENSE.txt  README.md
codeql-analysis.yml  docs             Makefile     requirements.txt
**(mud) limpingninja@DamagedGoods:~/muds/evennia$** pip install -e evennia
**_ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/limpingninja/muds/evennia/evennia_**

**Comment by LimpingNinja** [comment]
The documents here are a bit confusing which is why I am here, I will close the issue but it may be worth finding a wording that works. "Make sure you see the evennia and evenv directories" means nothing if you created your virtual directory INSIDE of the top-level evennia directory.

**Comment by Griatch** [comment]
Hm, I see what you mean. We try hard to explain where to be when running the commands, but there is indeed an `evennia` directory inside the top-level `evennia/` dir too that could lead to confusion if being one step too deep. :)

**Comment by LimpingNinja** [comment]
Yeah, I've seen the question crop up a couple times too when I was looking at it after the bug note and realized what had happened. I think there is something about the structure of the doc that makes you automatically CD into the directory after the git clone, probably just adding: **Do not enter the directory yet** or later on saying (**If you are already in the cloned directory you could use pip install -e . instead**)
