### ISSUE TITLE
EvEditor.md - Code snippets should reference .add attribute handler method instead of .set

### ISSUE THREAD

**Issue by telestrial** [evennia/evennia#2435]
Found [here](https://github.com/evennia/evennia/blob/251a70275bbd98a3e157cbb4c025597a4bb24ac9/docs/source/EvEditor.md) in the EvEditor Doc. Second and third snippet. Save method.

thing.attribute.set does not exist as a method of the attribute handler.

Change '.set' to '.add' in second and third snippet:

>         def save(caller, buffer):
>              "save the buffer"
>              caller.attributes.set("test", buffer)

**Comment by Griatch** [comment]
Resolved in develop branch.
