### ISSUE TITLE
[BUG] Traits - Bad example for HP gauge

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2450]
#### Describe the bug
There are conflicting examples of how to implement an HP gauge, but one of them does not work as documented:

https://github.com/evennia/evennia/blob/43fd533f28e4b17e33f0ab4a90372ccc6f7d723c/evennia/contrib/traits.py#L58

This creates a gauge with min and max set to 0. Setting the values manually yields an error in which the handler tells you to set `base` instead of `max`.

Later on there is a different example:

https://github.com/evennia/evennia/blob/43fd533f28e4b17e33f0ab4a90372ccc6f7d723c/evennia/contrib/traits.py#L268

This one appears to work though.

**Comment by mrseeker** [comment]
You have two types of bars: An XP bar that fills up, and an HP that goes down. Standard setting is base=min, unless overridden by setting base to a different value.

**Comment by Griatch** [comment]
I fixed the doc now, thanks. 
Unrelated to this issue, I also added `TraitProperty` as an alternative way to spec Traits with a class in a more 'django fields' kind of way (inspired by @Kektus DBField syntax).
