### ISSUE TITLE
[BUG] CmdHelp.can_list_topic not respecting auto_help settings

### ISSUE THREAD

**Issue by awranthyr** [evennia/evennia#2452]
#### Describe the bug
Commands that define `auto_help = False` show up in the default help list.

#### To Reproduce
1. Define `auto_help = False` on a command.
2. Reload the server.
3. Use the HELP command.
4. See error.

#### Expected behavior
Commands with auto_help defined as False should not appear in the help table.

#### Environment, Evennia version, OS etc
    Evennia 1.0-dev (rev 43fd533f2) (rev 43fd533f2)
    OS: posix
    Python: 3.9.2
    Twisted: 20.3.0
    Django: 3.2.3

#### Additional context
A simple check along the lines of...
```
if not cmd_or_topic.auto_help:
    return False
```
... at the top of can_list_topic should fix the issue.

**Comment by davewiththenicehat** [comment]
I got a chance to verify the issue. I'll set some time aside within the next few days to create a fix and a corresponding unit test.
If anyone else is already patching this let me know.
