### ISSUE TITLE
[DEVEL] [BUG] Editing a script on the admin site shows a dropdown of all attributes

### ISSUE THREAD

**Issue by GulliblePsychologist** [evennia/evennia#2463]
#### Describe the bug
When editing or viewing a Script on the admin site, the "Attributes" area shows a dropdown of _all_ attributes.

![yikes](https://user-images.githubusercontent.com/56974578/123627547-0f209c00-d80a-11eb-8130-118f82c1693f.png)

#### To Reproduce
1. Boot up the game.
2. Go to the admin site and click "Scripts".
3. Open a script.
4. Wait a while...

#### Expected behavior
Accounts and Objects have free input fields here, which makes sense.

![image](https://user-images.githubusercontent.com/56974578/123627604-1f387b80-d80a-11eb-8e36-561f77b24081.png)

But for some reason, scripts show a dropdown of all attributes. That's... not good for performance.

#### Environment, Evennia version, OS etc
Evennia 1.0-dev (rev 43fd533) (rev 43fd533) + patch applied for #2462
OS: nt
Python: 3.8.0
Twisted: 21.2.0
Django: 3.2.4

#### Additional context
This doesn't look right. There's a typeclass dropdown here too. Are these even regular attributes?

**Comment by Griatch** [comment]
Probably the wrong widget-type. 

The typeclass dropdown is based on an Attribute (not database-related at all), but loaded from the existing typeclasses known to the system - basically by analyzing the inheritance tree of the typeclasses in-memory.
