### ISSUE TITLE
[BUG] Using evennia.prototypes.spawner.spawn merges keys with incorrect precedence 

### ISSUE THREAD

**Issue by jerryaldrichiii** [evennia/evennia#2474]
#### Describe the bug

The following example/test fails:

```python
from evennia.prototypes.spawner import spawn
from evennia.utils.test_resources import EvenniaTest

PROTOTYPES = {
    "WEAPON": {
        "typeclass": "evennia.objects.objects.DefaultObject",
        "key": "Weapon",
        "desc": "A generic blade.",
        "magic": False,
    },
    "STING": {
        "prototype_parent": "WEAPON",
        "key": "Sting",
        "desc": "A dagger that shines with a cold light if Orcs are near.",
        "magic": True,
    },
}

class Example:
    def run():
        return spawn(PROTOTYPES["STING"], prototype_parents=PROTOTYPES)[0]

class TestExample(EvenniaTest):
    def test_run(self):
        sting = Example.run()
        self.assertEqual(sting.db.magic, True)
```

I would expect `sting.db.magic` to be True, but it appears that `spawn` has the reverse precedence than I expect.

This can also be seen in the `tutorial_world` contrib when receiving one of the magic weapons at the end. The key is correct, but the description, magic status, etc are all set to the attributes of the parent. Additionally, when traversing multiple parents it only overwrites using the value from the 1st parent. This leads to the magic weapons not having the magic attribute set.

#### Environment, Evennia version, OS etc

```
    Evennia 0.9.0
    OS: posix
    Python: 3.7.6
    Twisted: 19.10.0
    Django: 2.2.9
```

**Comment by Griatch** [comment]
@jerryaldrichiii 
Thanks for the fix! I'm not sure why this would fix the issue at hand though, except for the special case where the prototype-parent uses the "simple" type of Attribute definition (`{attrname: value}`) while the child uses full Attribute definitions (`{'attrs': [(key, value, category, locks), ...]}`). It would seem it would fail in the opposite direction if the Attribute types were reversed between parent and child. 

Am I missing something here?

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/commit/0129786c3d5f1b92fef480849beb9a95d2494455.
