### ISSUE TITLE
[BUG] XYZGrid list still shows 0 maps after adding one

### ISSUE THREAD

**Issue by ChrisLR** [evennia/evennia#2482]
#### Describe the bug
Added one XYMap using the proper commandline, then used spawn and it did nothing.
Went to try the xyzgrid list and it shows 0 maps.
Readded a few times, no change, shows as 0 maps and does not spawn anything.
Does not display any error

#### To Reproduce
1. evennia xyzgrid init
2. Add one using evennia xyzgrid add
3. use evennia xyzgrid list, it shows 0 maps
4. Try to spawn the map, nothing happens

#### Expected behavior
The map is supposed to be listed and spawned when the command is called.

#### Environment, Evennia version, OS etc
Latest Evennia Dev, Windows

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by Griatch** [comment]
@ChrisLR Can you spawn the example map(s), as per the XYZGrid documentation page? If so, it'd help a lot if you could provide the map module that fails to add.

**Comment by ChrisLR** [comment]
The examples work...
here is the module I'm trying to add
https://pastebin.com/JMVSDGJE

**Comment by ChrisLR** [comment]
I just noticed I still had XYMAP_DATA as a list due to that other bug.
The bug still happens when it is correctly named XYMAP_DATA_LIST

**Comment by Griatch** [comment]
The map has a malformed link structure. The error about this was not as visible as it should be. The error is now reported better.
