### ISSUE TITLE
[BUG] Changing typeclass appears to delete character locks

### ISSUE THREAD

**Issue by The-Archemist** [evennia/evennia#2504]
#### Describe the bug
Swapping the typeclass of a character removes default locks, rendering them unpuppetable. Discovered by Jarenko.

#### To Reproduce
1. `type/force <non-superuser>`

#### Expected behavior
1. `swap_typeclass` method will successfully swap typeclasses without losing default character permissions.

#### Additional context
1. After some detective work, this may be due to the `cdict` generated in `create_character` from account models not being recreated in the swap process. Appears necessary to establish appropriate account to character puppet permissions. 

2. Using /update instead of /force does not replicate the issue, but not an ideal solution.

**Comment by Griatch** [comment]
There is no way to recover the information set during `create_object` or later. I changed `type/force` to default to the `update` functionality and made the `swap` or `type/reset` present a more clear warning to the user to explain what it does.

**Comment by Griatch** [comment]
There is no way to recover the information set during `create_object` or later. I changed `type/force` to default to the `update` functionality and made the `swap` or `type/reset` present a more clear warning to the user to explain what it does.
