### ISSUE TITLE
[Feature Request] Make reload/reset/shutdown messages toggleable via settings.py

### ISSUE THREAD

**Issue by The-Archemist** [evennia/evennia#2506]
#### Feature:
I'd like the ability to turn off `... Server restarted.` from displaying to users for the sake of immersion. Ideally could do this with a boolean in `settings.py`.

**Comment by Griatch** [comment]
Looks like a good thing for someone to add (in `develop` branch for Hacktoberfest. It would require changes in `evennia/server/server.py` as well as in the default settings file `settings_default.py`.
