### ISSUE TITLE
[BUG] Django Admin save sets dictionaries with pickled objects as strings

### ISSUE THREAD

**Issue by alephate** [evennia/evennia#2510]
#### Describe the bug
If you have serialized strings from database objects in a dictionary on an object as an attribute, and then you edit other attributes on the object from the Django admin website, and then save there, it will turn those dictionary attributes into strings.

#### To Reproduce
1. Set up a room with a dictionary: py here.db.test_attribute = {self: 'Testing'}
2. Go into the webpage and change the name of the room.
3. Press save, and look back in your connected client.
4. See error (the dictionary is now a string, you can test thing by trying: py print(here.db.test_attribute.copy())

#### Expected behavior
The Django admin should save dictionaries as dictionaries even when they have pickled database objects inside them.

#### Environment, Evennia version, OS etc
    Evennia 0.9.5 (rev 76af934fd) (rev 76af934fd)
    OS: nt
    Python: 3.7.9
    Twisted: 20.3.0
    Django: 2.2.5

#### Additional context
Maybe instead of showing up as 'packed_db_object' in the django admin, the referenced object could show up as its serialized string in order to save properly.

**Comment by Griatch** [comment]
This is not reproducable in `develop` branch anymore; updating an entity with a dict containing a packed db-object does not modify the Attribute and it remains a dict.
