### ISSUE TITLE
Error in xyzgrid when the looker is a non-character

### ISSUE THREAD

**Issue by josiahzimm** [evennia/evennia#2522]
#### Brief summary of issue:
When I spawn a monster(non-character) object into an xyzgrid room, it throws an error in the server log. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Spawn a looker object (DefaultCharacter works) , that is not a player character
2. Move object into an xyzgrid room
3. Check server.log

#### Error output

```
21-09-04 14:17:16 [::] Traceback (most recent call last):
21-09-04 14:17:16 [::]   File "/usr/src/evennia/evennia/objects/objects.py", line 941, in move_to
21-09-04 14:17:16 [::]     self.at_after_move(source_location, **kwargs)
21-09-04 14:17:16 [::]   File "/usr/src/evennia/evennia/objects/objects.py", line 2272, in at_after_move
21-09-04 14:17:16 [::]     self.msg(text=(self.at_look(self.location), {"type": "look"}))
21-09-04 14:17:16 [::]   File "/usr/src/evennia/evennia/objects/objects.py", line 1808, in at_look
21-09-04 14:17:16 [::]     description = target.return_appearance(self, **kwargs)
21-09-04 14:17:16 [::]   File "/usr/src/evennia/evennia/contrib/xyzgrid/xyzroom.py", line 435, in return_appearance
21-09-04 14:17:16 [::]     client_width, _ = looker.sessions.get()[0].get_client_size()
21-09-04 14:17:16 [::] IndexError: list index out of range

```

This happens when i spawn a monster to a room like this:

new_objects = spawner.spawn(random.choice(MONSTER_LIST))

And move it into the room

#### Extra information, such as Evennia revision
Develop branch, xyzgrid contrib

**Comment by Griatch** [comment]
Resikved in [696a6f7](https://github.com/evennia/evennia/commit/696a6f7e7fd37f9d93f13009ffdaa1a2d81de45b)
