### ISSUE TITLE
[Documentation] contrib Gendersub - needs better install instructions

### ISSUE THREAD

**Issue by TarryDan** [evennia/evennia#2525]
#### Existing page / new
https://github.com/evennia/evennia/blob/master/evennia/contrib/gendersub.py

#### Documentation issue

There's not quite enough information here for an inexperienced user to install this contrib

> To use, have DefaultCharacter inherit from this, or change
> setting.DEFAULT_CHARACTER to point to this class.
> The `@gender` command is used to set the gender. It needs to be added to the
> default cmdset before it becomes available.

(I've figured out the first part, but only because of other contribs I've used; the second part about @gender is ????

#### Suggested change
I have used the contrib from rpsystem successfully, which has a [verbose installation section](https://raw.githubusercontent.com/evennia/evennia/master/evennia/contrib/rpsystem.py). 

Could someone update this contrib's docs in a similar style?

**Comment by Griatch** [comment]
We can add more documentation for this, sure. The process of adding [a new command to a command set](https://www.evennia.com/docs/latest/Adding-Command-Tutorial.html#step-2-adding-the-command-to-a-default-cmdset) is not unique to this contrib though.

**Comment by The-Archemist** [comment]
I don't mind working on this. 

If you could explain what more you'd like to see documented, @TarryDan, that would help me know what specifically is missing and how to update the documentation. As is, I feel like Griatch did a pretty good job documenting it for people that have a basic grasp on adding commands and using typeclasses, but I know that Evennia also has a pretty steep learning curve so it's nice to simplify where applicable.

**Comment by Griatch** [comment]
Extra docs added in develop branch.
