### ISSUE TITLE
[BUG] evennia/objects/objects.py DefaultObject return_appearance does not adhere to the same convention as elsewhere.

### ISSUE THREAD

**Issue by VexiaOnline** [evennia/evennia#2530]
Within the DefaultObject `return_appearance` code breaks the convention that everywhere else uses. Most instances all use `get_display_name` whereby they return an object's name by calling `object.name`, while in this case `return_appearance` references `object.key` for users and exits. 

I believe this should be changed to use `.name` so that in cases where we are overriding the object name method, we do not ALSO have to override DefaultObject's `return_appearance` to see the changes reflected when someone uses look.

Lines 1755 and 1756 should be changed to the following in my opinion:
```
users = [f"|c{user.name}|n" for user in users_list]
exits = [ex.name for ex in exits_list]
```

**Comment by Griatch** [comment]
Thanks! Yes, that sounds like a good idea.

**Comment by VexiaOnline** [comment]
`evennia/commands/default/building.py`

Line 1382 this is one more occasion where I see an inconsistency, or at least if we are going to make the proposed change above, the line must be changed from
`obj.name = newname`
to
`obj.key = newname`

We want to set the key since if people are overriding `obj.name` to return customized stylizations of names, trying to do it this old way will generate an error and mean we have to override this command as well.

**Comment by Griatch** [comment]
Implemented in develop now.
