### ISSUE TITLE
[Documentation] example of a crafting recipe that generates an action

### ISSUE THREAD

**Issue by dimitrilw** [evennia/evennia#2554]
This issue is less "documentation" and more "requesting an example."

#### Documentation issue

The [crafting readme](https://github.com/evennia/evennia/blob/develop/evennia/contrib/crafting/README.md)
ref's the idea of making a fireball spell as a result:

> ...one could also imagine using tools without consumables, like using 'spell book' and 'wand' to produce 'fireball' by having the recipe check some magic skill on the character.

Note that the [example recipe](https://github.com/evennia/evennia/blob/develop/evennia/contrib/crafting/example_recipes.py)
gives a thorough demonstration of crafting objects as outputs (i.e., a sword).

#### Suggested change

I am requesting a new `example_recipes_fireball.py` file that demonstrates the idea of having a recipe result in a skill, like a combat attack (fireball).

**Comment by Griatch** [comment]
A good idea. I added a magic example to the end of the existing sword recipy.
