### ISSUE TITLE
[BUG] Error on connecting to a guest account twice

### ISSUE THREAD

**Issue by GulliblePsychologist** [evennia/evennia#2562]
#### Describe the bug
My environment has an error occur when you connect to a guest account twice. The reason for this is that "webclient_authenticated_nonce" (from #2024) is set to `0` while a value of `None` is expected.

The actual value doesn't matter in this case, so the default value of the nonce can be safely considered `0` to prevent these issues.

#### To Reproduce
1. Login as a guest. A new guest Account is created for the duration of the session. `webclient_authenticated_nonce` is `None`.
2. Disconnect the webclient. The guest Account is deleted. `webclient_authenticated_nonce` is `None`, expected value is `None`: the value of `webclient_authenticated_uid` is reset to `None`. `webclient_authenticated_nonce` is reset to `0`.
3. Login as a guest for a second time. A new guest Account is created for the duration of the session. `webclient_authenticated_nonce` is `0`, but the internal value is stored as `None` because `webclient_authenticated_uid` is `None`.
4. Disconnect the webclient. The guest Account is deleted. `webclient_authenticated_nonce` is `0` and the expected value is `None`. Now, `webclient_authenticated_uid` is _not_ reset and points to a non-existent account ID.
5. Navigate to any page on the website, or try to open the webclient again.

You'll be confronted with an error message because line 57 of evennia/web/utils/middleware.py attempts to fetch the Account:

```
        elif webclient_uid:
            # Not logged into website, but logged into webclient
            if website_uid is None:
                csession["website_authenticated_uid"] = account.id
                account = AccountDB.objects.get(id=webclient_uid)  # this line raises an AccountDB.DoesNotExist error
                try:
                    # calls our custom authenticate, in web/utils/backend.py
                    authenticate(autologin=account)
                    login(request, account)
                except AttributeError:
                    logger.log_trace()
```

#### Expected behavior
I would have preferred if this was automatically corrected by the `website_authenticated_uid` being reset back to `None` if the database object doesn't exist. Unfortunately, this flexibility seems absent in this case.

#### Environment, Evennia version, OS etc
Evennia 1.0-dev (rev 43fd533) (rev 43fd533)
OS: nt
Python: 3.8.0
Twisted: 21.2.0
Django: 3.2.4

#### Additional context
I'll create a PR shortly referencing this issue, as I'm _accountable_ for this.

**Comment by Griatch** [comment]
Closed in #2563.
