### ISSUE TITLE
[BUG] Regular users cannot edit/delete characters from the website

### ISSUE THREAD

**Issue by fariparedes** [evennia/evennia#2575]
#### Describe the bug
Users have access to the Manage Characters page but cannot use it to edit or delete their characters without admin permissions.

#### To Reproduce
1. Create a new Evennia game
2. Create a new non-superuser account
3. Open the dropdown on the website and click Manage Characters
4. Attempt to edit or delete the character
4. 403 Forbidden error

#### Expected behavior
Normal players should be able to edit and delete their characters with the Manage Characters page that is made available to all users.

#### Environment, Evennia version, OS etc
Evennia version: 0.9.5 (rev da1885aaa)
OS: nt
Python: 3.8.5
Twisted: 21.7.0
Django: 3.2.8

**Comment by fariparedes** [comment]
Seems like this is an issue with the default character locks. Only admins can edit them, and only the ID of the character can delete them... so the interface is unusable for players. Not sure if the account is even included on the permissions or *can* be, which I assume is the thing checked when the page is opened. My admin account is a superuser and bypasses all locks, naturally. 

Possible solution is to just make the manage character page have view permissions or something, since it's already only accessible if you're logged in AFAIK.

**Comment by Griatch** [comment]
Added default `edit` perms to Characters; this will not help existing characters though; might be adding a mention in the docs about it.
