### ISSUE TITLE
[BUG] Browser color issues

### ISSUE THREAD

**Issue by mrseeker** [evennia/evennia#2578]
#### Describe the bug
The following code will not work in the browser, and will in fact generate the word "test" in bold only. If the newline is omitted, then test2 will be bold and the resulting text will not be correct.

```
print("|htest|w|n\ntest2|h test3|n")
```
result:
```
<b>test</b>
```

```
print("|htest1|w|n test2|h test3|n")
```
result:
```
<b>test1 test2[1m test3</b>
```

#### To Reproduce
1. Start evennia in the browser
2. Log in and use the "py" command
3. Type the print examples
4. See weird behaviour

#### Expected behavior
```
print("|htest|w|n\ntest2|h test3|n")
```
result:
```
<b>test</b>
test2<b> test3</b>
```

```
print("|htest1|w|n test2|h test3|n")
```
result:
```
<b>test1</b> test2 <b>test3</b>
```

#### Environment, Evennia version, OS etc
    Evennia 1.0-dev
    OS: posix
    Python: 3.9.2
    Twisted: 21.7.0
    Django: 3.2.8

#### Additional context
Have not tested this on putty, only in browser.

**Comment by Griatch** [comment]
This is a known issue with the ANSI2HTML conversion - the conversion is done with regexes which doesn't understand state within the string. This is likely something that would need to be addressed as part of https://github.com/evennia/evennia/pull/2419.

**Comment by Griatch** [comment]
The hilight errors have been resolved; what remained was an issue with line breaks from the `py` command. Now fixed in `develop` branch.
