### ISSUE TITLE
[BUG] Stack trace when invoking raw_ansi with parameter string=None

### ISSUE THREAD

**Issue by luciensadi** [evennia/evennia#2580]
#### Describe the bug
Entering `i` when holding an item with no description produces the following stack trace:
```
Traceback (most recent call last):
  File "/Users/<snip>/dev/evennia/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
    ret = cmd.func()
  File "/Users/<snip>/dev/evennia/evennia/evennia/commands/default/general.py", line 387, in func
    "{}".format(utils.crop(raw_ansi(item.db.desc), width=50) or ""),
  File "/Users/<snip>/dev/evennia/evennia/evennia/utils/ansi.py", line 523, in raw
    return string.replace("{", "{").replace("|", "|")
AttributeError: 'NoneType' object has no attribute 'replace'
```

#### To Reproduce
1. Create an object like this:
```
obj = create_object(
                typeclass=Object,
                key="new obj",
                home=caller,
                report_to=caller
            )
success = clothes.move_to(caller, quiet=True)
```
2. Hit `i`
3. See error

#### Expected behavior
The raw_ansi function should account for None strings and return the empty string `""` instead of an exception.

#### Environment, Evennia version, OS etc
         Evennia version: 0.9.5 (rev 630681337)
         OS: posix
         Python: 3.9.7
         Twisted: 21.7.0
         Django: 3.2.8

**Comment by Griatch** [comment]
Resolved in `develop` branch.
