### ISSUE TITLE
[DEVEL][BUG] Django Warning urls.W005

### ISSUE THREAD

**Issue by awranthyr** [evennia/evennia#2586]
#### Describe the bug
Newly created game instances alert users to the following:
```
WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
```
#### To Reproduce
1. `evennia --init newinstance`
2. `cd newinstance`
3. `evennia migrate`
4. start and then stop the server
5. `evennia migrate` or `evennia check`
6. See error

#### Expected behavior
Fresh instances probably shouldn't raise any warnings.

#### Environment, Evennia version, OS etc
```
    Evennia 1.0-dev (rev ffd6da2c5) (rev ffd6da2c5)
    OS: posix
    Python: 3.9.7
    Twisted: 21.7.0
    Django: 3.2.3
```
#### Additional context
I have yet to see this actually impact the behavior of the webserver, but it has the potential to alarm new users.

**Comment by strikaco** [comment]
This may actually have an impact-- I'm currently seeing an issue with a custom app's admin panel not showing up.

**Comment by strikaco** [comment]
The admin URLs are defined in multiple places.

Core admin URLs are loaded here:
https://github.com/evennia/evennia/blob/7c2eed4e7a4be3f8f7c0437b907453ed09edadd8/evennia/web/urls.py#L31-L32

https://github.com/evennia/evennia/blob/7c2eed4e7a4be3f8f7c0437b907453ed09edadd8/evennia/web/admin/urls.py#L21-L33

...which are trumped by the instance:

https://github.com/evennia/evennia/blob/7c2eed4e7a4be3f8f7c0437b907453ed09edadd8/evennia/game_template/web/urls.py#L25-L27

https://github.com/evennia/evennia/blob/7c2eed4e7a4be3f8f7c0437b907453ed09edadd8/evennia/game_template/web/admin/urls.py#L10-L20

I found my missing app under `admin/<app_name>`, but when rendering the admin views it's mixing content of the custom app with content from the Evennia catch-all URLs.

This is not surprising given the inheritance tree but this completely breaks custom apps if you (I assume) fail to manually register all custom app admin URLs in `web.admin.urls`.

**Comment by Griatch** [comment]
This has been resolved since, by removing the admin url from the `evennia.web.urls`. When migrating to 1.0, existing users will need to update their `mygame/web/urls.py` to match the `game_template` version.
