### ISSUE TITLE
[BUG] Help Files Do Not Display New Line Characters With Escape

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#2598]
Help entries no longer validate `||/` to display `|/`. Instead, it continues onward to display a new line.

#### To Reproduce
1. Create help entry
2. Put `||/` somewhere in help entry
3. See error

#### Expected behavior
In master branch, help entries automatically escape the new line generation to display. Helpful information for builders.

**Comment by Griatch** [comment]
I cannot reproduce this; this seems to be working fine using `sethelp` command in current `develop` branch. Closing, if this is still happening using some other process, reply here and we can re-open.
