### ISSUE TITLE
Web Client: Input frame focus is not retained if multiple input frames are open

### ISSUE THREAD

**Issue by Tegiminis** [evennia/evennia#2608]
#### Brief summary of issue / Description of requested feature:
If you have multiple input frames open on the default web client, inputting a command will unfocus the input frame, requiring you to click into it every time.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Start up an Evennia server and log in using the localhost web client
2. Open an extra input frame
3. Input any command
4. Observe input frame focus being lost

#### Error output / Expected result of feature
The currently-used input frame should stay focused until the user clicks out of it, regardless of command use.

####Screenshot####
Input frames should look like this to repro the bug.
![image](https://user-images.githubusercontent.com/2596300/148469782-004a17d2-bced-4d8b-8a48-5ea9691f2e3f.png)

**Comment by selberhad** [comment]
[This code](https://github.com/evennia/evennia/blob/develop/evennia/web/static/webclient/js/plugins/default_in.js#L67-L69) looks to be the culprit, note how it focuses the last `inputfield` in the DOM rather than the most recently used one. I'll try to figure out a good way to fix that and put in a PR.

**Comment by selberhad** [comment]
BTW, what's the use-case of multiple input tabs?

**Comment by Griatch** [comment]
> BTW, what's the use-case of multiple input tabs? 
Common in heavy RP games, where you could be in the process of writing a longer text in one input pane while entering shorter commands in another.
