### ISSUE TITLE
[BUG] delays not firing when scheduled in Script during startup

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2610]
#### Describe the bug
Non-persistent callbacks scheduled with `delay` (using `persistent=False`) do not fire properly when called from some script `at_start` methods. These callbacks appear to be scheduled successfully and return a `TaskHandlerTask` as expected, and contain a valid `Deferred` under the hood. After the correct amount of time passes, these tasks indicate that they have been called, but the underlying callback methods do not indeed get called.

If I call `at_start` after the server has fully initialized (including by `restart()`ing the script), callbacks and delays behave properly.

I am not sure the root cause, though it is possible there is a problem with initialization order. I have observed this behavior with global scripts defined in `settings.GLOBAL_SCRIPTS` as well as with non-global scripts attached to a specific object. It appears that global scripts NOT defined in `settings.GLOBAL_SCRIPTS` behave properly.

#### To Reproduce
1. Define a new script like the following and it attach it a puppeted character.
```py
class ScriptTest(Script):
    def at_start(self):
        super().at_start()
        delay(10, self.obj.msg, "TEST")
        print("test message scheduled")
```

2. Observe that, after 10 seconds, the message TEST is sent to the attached session.
3. Reload the server.
4. Check the logs and observe that "test message scheduled" appears.
5. Observe that TEST is not sent to the attached session.
6. Call `restart()` on the script.
7. Observe that TEST is again printed.

#### Expected behavior
`delay` callbacks should behave consistently during script startup.

#### Environment, Evennia version, OS etc
Evennia 0.9.5 (rev aa6d01e01)
OS: posix (WSL2)
Python: 3.8.10
Twisted: 21.7.0
Django: 3.2.8

#### Additional context
I've spent some time investigating this and am attempting to dump as much knowledge as I can into this bug.

* I can reproduce this reliably on master, though I have not tried on develop.
* Setting breakpoints or adding print statements in the callback function (for the example above, by instrumenting `Object.msg`) shows that the callback itself is never executed in the misbehavior case.
* Retrieving the `TaskHandlerTask` created by `delay` manually (before it would normally fire) and calling `do_task()` on it does not change the outcome. It still does not execute the actual callback, but reports that it completed successfully, as far as I can tell.
* The fact that behavior depends on what kind of script it is (global vs non-global vs defined in GLOBAL_SCRIPTS) seems to be an important issue that may indicate some kind of initialization error.
* No exceptions whatsoever are logged in the error case. Adding try/except wrappers to `at_start` shows that no exceptions are raised during the delay setup process.

**Comment by Griatch** [comment]
As far as I can tell, this works fine in `develop` branch - the Script starts and the delayed message pops up X seconds later as expected. Maybe this was resolved automatically by the script/tickerhandler changes in develop branch. Closing this. Please reopen if you still are having issues in develop.
