### ISSUE TITLE
[BUG - Web Client] CTRL + C will not copy highlighted text.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2611]
#### Describe the bug
Pressing CTRL + C in the Evennia web client will focus on the text input box, instead of copying highlighted text on the page.

@friarzen explained that this is due to any key input, other than CTRL or other modifiers, forcing the focus to the input box.

So as soon as the C is pressed when using CTRL + C, it will instead focus the input box, instead of copying the highlighted text from the Main output box.

#### To Reproduce
1. Highlight some text on the web client.
2. Press CTRL + C.
3. Try to paste and notice that nothing was copied.

#### Expected behavior
CTRL + C should instead copy the highlighted text.

#### Solution
It's best that the "Focus input box on keypress." feature be quelled while a modifier key is held down.

```py
if ctrl == keypressdown:
    ignore input box focus
```
^ not real code 😅

**Comment by Griatch** [comment]
Implemented.
