### ISSUE TITLE
[BUG] (Develop) Unable to initialize new game on Windows

### ISSUE THREAD

**Issue by sailgoat** [evennia/evennia#2612]
#### Describe the bug
Attempting to run the command evennia --init mygame fails with the following traceback:

Traceback (most recent call last):
  File "O:\Projects\mud\mudenv\Scripts\evennia_launcher.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "O:\Projects\mud\evennia\bin\windows\evennia_launcher.py", line 16, in <module>
    from evennia.server.evennia_launcher import main
ModuleNotFoundError: No module named 'evennia.server'

#### To Reproduce
1. Clone the develop branch to an empty directory.
2. Create a new virtual environment.
3. Install evennia with pip.
4. Attempt to create a new game.
5. See error

#### Expected behavior
A game is created.

#### Environment, Evennia version, OS etc
Using Windows 10 and Python version 3.9.9. I've also tried with Python version 3.10.1.

#### Additional context
After experiencing this issue, I tested an install using WSL and it works fine. Appears to be confined to Windows at the moment, and is not occurring on the master branch.
-----
A log of all steps taken:

PS O:\Projects> cd mud
PS O:\Projects\mud> ls
PS O:\Projects\mud> git clone -b develop https://github.com/evennia/evennia.git
Cloning into 'evennia'...
remote: Enumerating objects: 146471, done.
remote: Counting objects: 100% (49211/49211), done.
remote: Compressing objects: 100% (7313/7313), done.
remote: Total 146471 (delta 45148), reused 45705 (delta 41799), pack-reused 97260
Receiving objects: 100% (146471/146471), 232.55 MiB | 11.76 MiB/s, done.
Resolving deltas: 100% (125976/125976), done.
PS O:\Projects\mud> virtualenv mudenv
created virtual environment CPython3.9.9.final.0-64 in 2542ms
  creator CPython3Windows(dest=O:\Projects\mud\mudenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\user\AppData\Local\pypa\virtualenv)
    added seed packages: pip==21.3.1, setuptools==60.2.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
PS O:\Projects\mud> .\mudenv\Scripts\activate
(mudenv) PS O:\Projects\mud> python --version
Python 3.9.9
(mudenv) PS O:\Projects\mud> pip install -e evennia
Obtaining file:///O:/Projects/mud/evennia
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: wheel in o:\projects\mud\mudenv\lib\site-packages (from evennia==1.0.dev0) (0.37.1)
Collecting django<3.3,>=3.2
  Using cached Django-3.2.11-py3-none-any.whl (7.9 MB)
Collecting model-mommy
  Using cached model_mommy-2.0.0-py2.py3-none-any.whl (16 kB)
Collecting djangorestframework<3.12,>=3.10.3
  Using cached djangorestframework-3.11.2-py3-none-any.whl (911 kB)
Collecting django-filter==2.4
  Using cached django_filter-2.4.0-py3-none-any.whl (73 kB)
Collecting inflect>=5.2.0
  Using cached inflect-5.3.0-py3-none-any.whl (32 kB)
Collecting twisted<22.0.0,>=21.7.0
  Using cached Twisted-21.7.0-py3-none-any.whl (3.1 MB)
Collecting attrs>=19.2.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting autobahn<21.0.0,>=20.7.1
  Using cached autobahn-20.12.3-py2.py3-none-any.whl (1.5 MB)
Collecting parameterized==0.8.1
  Using cached parameterized-0.8.1-py2.py3-none-any.whl (26 kB)
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting lunr==0.6.0
  Using cached lunr-0.6.0-py2.py3-none-any.whl (34 kB)
Collecting django-sekizai==2.0.0
  Using cached django_sekizai-2.0.0-py3-none-any.whl (12 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp39-cp39-win_amd64.whl (151 kB)
Collecting pytz
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting anything==0.2.1
  Using cached anything-0.2.1-py3-none-any.whl
Collecting mock>=1.0.1
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting simpleeval<=1.0
  Using cached simpleeval-0.9.11-py2.py3-none-any.whl (14 kB)
Collecting black
  Using cached black-21.12b0-py3-none-any.whl (156 kB)
Collecting django-classy-tags>=1
  Using cached django_classy_tags-2.0.0-py3-none-any.whl (23 kB)
Collecting cryptography>=2.9.2
  Using cached cryptography-36.0.1-cp36-abi3-win_amd64.whl (2.2 MB)
Collecting hyperlink>=20.0.1
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Collecting txaio>=20.4.1
  Using cached txaio-21.2.1-py2.py3-none-any.whl (30 kB)
Collecting asgiref<4,>=3.3.2
  Using cached asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting zope.interface>=4.4.2
  Using cached zope.interface-5.4.0-cp39-cp39-win_amd64.whl (210 kB)
Collecting Automat>=0.8.0
  Using cached Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting incremental>=21.3.0
  Using cached incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting constantly>=15.1
  Using cached constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting twisted-iocpsupport~=1.0.0
  Using cached twisted_iocpsupport-1.0.2-cp39-cp39-win_amd64.whl (45 kB)
Collecting pathspec<1,>=0.9.0
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting click>=7.1.2
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting tomli<2.0.0,>=0.2.6
  Using cached tomli-1.2.3-py3-none-any.whl (12 kB)
Collecting platformdirs>=2
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting pywin32>=223
  Using cached pywin32-303-cp39-cp39-win_amd64.whl (9.3 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp39-cp39-win_amd64.whl (180 kB)
Collecting idna>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools in o:\projects\mud\mudenv\lib\site-packages (from zope.interface>=4.4.2->twisted<22.0.0,>=21.7.0->evennia==1.0.dev0) (60.2.0)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: sqlparse, pytz, pycparser, asgiref, six, idna, django, colorama, cffi, attrs, zope.interface, typing-extensions, txaio, twisted-iocpsupport, tomli, pywin32, platformdirs, pathspec, mypy-extensions, incremental, hyperlink, django-classy-tags, cryptography, constantly, click, Automat, twisted, simpleeval, pyyaml, pypiwin32, parameterized, model-mommy, mock, lunr, inflect, djangorestframework, django-sekizai, django-filter, black, autobahn, anything, evennia
  Running setup.py develop for evennia
Successfully installed Automat-20.2.0 anything-0.2.1 asgiref-3.4.1 attrs-21.4.0 autobahn-20.12.3 black-21.12b0 cffi-1.15.0 click-8.0.3 colorama-0.4.4 constantly-15.1.0 cryptography-36.0.1 django-3.2.11 django-classy-tags-2.0.0 django-filter-2.4.0 django-sekizai-2.0.0 djangorestframework-3.11.2 evennia-1.0.dev0 hyperlink-21.0.0 idna-3.3 incremental-21.3.0 inflect-5.3.0 lunr-0.6.0 mock-4.0.3 model-mommy-2.0.0 mypy-extensions-0.4.3 parameterized-0.8.1 pathspec-0.9.0 platformdirs-2.4.1 pycparser-2.21 pypiwin32-223 pytz-2021.3 pywin32-303 pyyaml-6.0 simpleeval-0.9.11 six-1.16.0 sqlparse-0.4.2 tomli-1.2.3 twisted-21.7.0 twisted-iocpsupport-1.0.2 txaio-21.2.1 typing-extensions-4.0.1 zope.interface-5.4.0
(mudenv) PS O:\Projects\mud> evennia --init mygame
Traceback (most recent call last):
  File "O:\Projects\mud\mudenv\Scripts\evennia_launcher.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "O:\Projects\mud\evennia\bin\windows\evennia_launcher.py", line 16, in <module>
    from evennia.server.evennia_launcher import main
ModuleNotFoundError: No module named 'evennia.server'
(mudenv) PS O:\Projects\mud>

**Comment by sailgoat** [comment]
I was able to resolve this by deleting the blank `__init__.py` file in the base evennia directory of the develop branch.

**Comment by Griatch** [comment]
Thanks for the report; removed the spurious `__init__.py` file, it doesn't belong there :)
