### ISSUE TITLE
[BUG] Official Evennia docker image Django version not matching master branch

### ISSUE THREAD

**Issue by lorecrafting** [evennia/evennia#2621]
#### Describe the bug
The requirements.txt on master branch has Django version as: `django >= 3.2, < 3.3`
The official Docker image at the Evennia repository on Dockerhub has `django >= 2.2.5, < 3.0` in its requirements.txt

The older version of Django causes issues with psycopg2 database connector when connecting to Postgres 13

#### To Reproduce
1. Shell into a running evennia:latest container and check requirements.txt and compare with the requirements.txt on Github master branch

#### Expected behavior
The requirements.txt on master branch on Github should match the baked image on Docker Hub

#### Environment, Evennia version, OS etc
    Evennia 0.9.5
    OS: posix
    Python: 3.7.9
    Twisted: 20.3.0
    Django: 2.2.17
   
   This was done on a Macbook Air M1 within the Evennia Docker image.

#### Additional context

This may be an issue with the Github CI system or action workflow.

**Comment by Griatch** [comment]
Docker image build was fixed.
