### ISSUE TITLE
[BUG] Error when using aliases with build commands like @dig

### ISSUE THREAD

**Issue by RodRitter** [evennia/evennia#2654]
#### Describe the bug
(Replace with a clear and concise description of what the bug is.)

#### To Reproduce
1. In a fresh install, sitting in Limbo
2. Run `dig Portal Room;portal`
3. Line 1: `Created room Portal Room(#10) of type typeclasses.rooms.Room.`
4. Line 2: `Command 'portal' is not available. Maybe you meant "globalscript", "cpattr" or "teleport"?`
5. Room is created but no alias assigned

#### Expected behavior
Expect to create the room with alias assigned.

#### Environment, Evennia version, OS etc
```
Evennia 0.9.5 (rev 5d708f72f) (rev 5d708f72f)
OS: posix
Python: 3.8.10
Twisted: 21.7.0
Django: 3.2.12
```

#### Additional context
This happens with any commands using `;` in the command (name, create, etc)

**Comment by aMiss-aWry** [comment]
The fact that 'portal' is interpreted as a command tells me that semi-colons are probably interpreted as command line separators by your client. Try typing "say hi;say hello" and see what results.

You should be able to change that in your client settings, somewhere in a command input section or something like that.

**Comment by RodRitter** [comment]
> The fact that 'portal' is interpreted as a command tells me that semi-colons are probably interpreted as command line separators by your client. Try typing "say hi;say hello" without the apostrophes and see what results.
> 
> You should be able to change that in your client settings, somewhere in a command input section or something like that.

Ah you are absolutely correct. I didn't realise Mudlet made that a default. Thank you for pointing that out!
