### ISSUE TITLE
[BUG - Develop] Can't convert attribute to strattr

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2660]
#### Describe the bug

Converting an existing attribute in develop to a strattr fails. I think is because `AttributeHandler.add` doesn't pass the `strattr` param to the backend's `update_attribute`, which just updates the regular `value` instead. This looks like a regression compared to master.

#### To Reproduce
Enter the following in an in-game py shell:
```
>>> me.db.test
>>> me.db.test = "one"
>>> me.db.test
one
>>> me.attributes.add("test", "two", strattr=True)
>>> me.attributes.get("test", strattr=True)
```

#### Expected behavior

Existing attribute `strvalue` can be updated properly.

#### Develop-branch commit

    Evennia 1.0-dev (rev 2e645c58b) (rev 2e645c58b)
    OS: posix
    Python: 3.10.2
    Twisted: 21.7.0
    Django: 4.0.2

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by Griatch** [comment]
A logical path was missing for this particular switch. Added now :D
