### ISSUE TITLE
[Documentation] Fix references to `django.conf.urls.url` in web tutorials

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2664]
#### Existing page / new

https://www.evennia.com/docs/1.0-dev/Howtos/Web-Character-Generation.html
https://www.evennia.com/docs/1.0-dev/Howtos/Web-Character-View-Tutorial.html

#### Documentation issue

Replace `django.conf.urls.url` with `django.urls.path` in `urls.py` example files, and update arguments. Django 4.0 has deprecated the old `url`.

#### Suggested change

e.g. 
`url(r'^(?P<app_id>[0-9]+)/$', views.detail, name='detail'),`
to
`path('<int:app_id>/' views.detail, name='detail'),`

**Comment by ShardsDev** [comment]
This same issue is on this page: 
https://www.evennia.com/docs/1.0-dev/Howtos/Add-a-wiki-on-your-website.html

**Comment by Griatch** [comment]
Fixed.
