### ISSUE TITLE
[BUG - Develop] CmdTag applies tag globally, does not prioritize local objs

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#2665]
#### Describe the bug
CmdTag applies the tag to the first instance of the target. So if you do something like 'tag south=test' there's no guarantee the 'south' in the same room as you gets the tag. Also goes for tag/del (which targets the first instance of an item, not a local one). If you only use dbrefs you'll never run into this issue. 

#### To Reproduce
1. Make a new exit with a name that matches many other exits. For instance, 'south'.
2. tag south=test
3. Note that the tag does not exist on this new 'south' exit...
4. But as per 'tag/search test' is applied to another one (probably the oldest one, I think)

#### Expected behavior
I want tags to apply locally first, then globally if the target isn't found locally.

#### Develop-branch commit
479c259da

#### Additional context
[(I kind of fixed it here but have no idea how to open a separate PR instead of mashing it onto the old one anyway.)](https://github.com/evennia/evennia/commit/bcbe75741d1326ca647157d87d9a20cde7c444d6)

![image](https://user-images.githubusercontent.com/9540334/156884197-db6b9ae3-cab0-4573-ab34-9a75490f2e57.png)

**Comment by Griatch** [comment]
@aMiss-aWry The linked fix you made seems like it should address it. Maybe make a PR out of it (would be good with a unit test as well though).

**Comment by Griatch** [comment]
Fixed this, with a somewhat more expanded version of your proposed solution. Thanks!
