### ISSUE TITLE
[BUG - Develop] `createsuperuser` repeats itself after user creation

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2684]
#### Describe the bug
Running `createsuperuser` command successfully creates a superuser account, but then it restarts and prompts to create another.

#### Expected behavior
Not sure if this is new/expected behavior. It gave no indication to do so but I had to use Ctrl+C to break the loop.

#### Develop-branch commit
```
Evennia version: 1.0-dev (rev 473f2e3)
         OS: posix
         Python: 3.9.4
         Twisted: 21.7.0
         Django: 4.0.2
```

**Comment by Griatch** [comment]
Running `createsuperuser` on an already existing database (with another superuser) works fine, with no duplication. 

I can replicate if trying to run `evennia createsuperuser` on an empty database. I think what happens is that it first follows the command and then starts the normal create-superuser step that happens for a new database. 

I'd say this is a rather unusual use-case (why would you run this on an empty database), but it's nevertheless a bug.

**Comment by strikaco** [comment]
> I'd say this is a rather unusual use-case (why would you run this on an empty database), but it's nevertheless a bug.

Accident. This step has to be done manually on any new Django project (I forgot Evennia runs this automatically), so there is no actual use case.

**Comment by Griatch** [comment]
I have blocked this command running more than the initial time, since it will not create a valid Account anyway if run to create a second superuser (this can be made in-game with `py` or using the admin). It's not really worth spending time fixing this repeat just to address the case of people not following the getting-started instructions. :)
