### ISSUE TITLE
[Feature Request] Exits - Set `traversing_obj` location to Exit before moving to destination (or create Django signal for `at_traverse`)

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2687]
#### Describe the solution you'd like
There is no way to monitor what exits (paths) an object takes to get from point A to B.

The MonitorHandler can be set to track location, but this only captures the change in location from one room to the next, without capturing the specific route the object took to get there.

(Trying to build a modular pathfinding service/spell that quietly observes what exits can be used to get from A to B and builds a map based on paths _known to the character/object_.)

#### Describe alternatives you've considered
A Django signal that fires anytime `at_traverse` runs should achieve the same goal of delivering updates to subscribers without impact.

Overriding `at_traverse` on the Exit typeclass and recording `self.id` somewhere would also work, but since this involves modification to the typeclass itself, it is more intrusive and breaks the "plugin" aspect of what I'm hoping to achieve.

**Comment by Griatch** [comment]
I suppose adding a django signal for the `at_traverse` event could be useful, yes.
