### ISSUE TITLE
[BUG] Adding a tag with no category adds a pre-existing tag with a category instead

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2688]
#### Describe the bug

If a tag x:y (tagname x, category y) already exists and you attempt to add a tag x:None, evennia will instead add tag x:y.

#### To Reproduce

These steps reproduce the issue reliably in a py shell:
```
>>> me.tags.add("testing", category="test")
[py mode - quit() to exit]
>>> me.tags.remove(category="test")
[py mode - quit() to exit]
>>> me.tags.add("testing")
[py mode - quit() to exit]
>>> me.tags.all(return_key_and_category=True)
[('testing', 'test')]
```

#### Expected behavior

`obj.tags.add("foo")` should always add foo:None rather than looking for foo:y tags to add.

#### Environment, Evennia version, OS etc

Occurs on both master and develop.

    Evennia 1.0-dev (rev 473f2e379) (rev 473f2e379)
    OS: posix
    Python: 3.10.2
    Twisted: 21.7.0
    Django: 4.0.2

#### Additional context

In the above example, deleting the tag testing:test from the DB (using the Django admin) restores the correct behavior.

**Comment by Griatch** [comment]
Closed in [cc5d7ea](https://github.com/evennia/evennia/commit/cc5d7ead32d6606ba2785a49271e1492cd3939a2)
