### ISSUE TITLE
[Documentation] Installation instructions in 1.0 dev documentation result in installation of 0.9.5 version

### ISSUE THREAD

**Issue by toktoktheeo** [evennia/evennia#2689]
#### Existing page / new
https://www.evennia.com/docs/1.0-dev/Setup/Installation-Git.html

#### Documentation issue
When you follow the instructions to install evennia in the 1.0 dev documentation, you end up installing the 0.9.5 version.

#### Suggested change
Maybe tell people to switch git branch in the installation steps while 1.0 is still in a distinct branch from master ?
Right now, the needed steps are only located in the "upgrading an existing installation" page. https://www.evennia.com/docs/1.0-dev/Setup/Installation-Upgrade.html

**Comment by Griatch** [comment]
Fair point. Added a warning to do `git checkout develop` too.
