### ISSUE TITLE
[BUG - Develop] `TypedObjectManager.typeclass_search` bugs

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2694]
#### Describe the bug

A couple related bugs in `TypedObjectManager.typeclass_search`

A) Difference in results depending on whether you pass a typeclass object or its path.
B) Passing a class with include_children=True causes a traceback.
C) include_children only searches one layer deep, not recursively.
D) Documentation references a location param that does not exist.

#### To Reproduce

Bug A
```
>>> from typeclasses.characters import Character
[py mode - quit() to exit]
>>> Character.objects.typeclass_search(Character)
<QuerySet []>
[py mode - quit() to exit]
>>> Character.objects.typeclass_search("typeclasses.characters.Character")
<QuerySet [Relthari(#1), Nevrei(#3), anonymous(#43), Phethjeld(#260), Ari(#261), Zithan(#430), Elithi(#434), Gilgreth(#436)]>
```

Bug B
```
>>> Character.objects.typeclass_search("typeclasses.characters.Character", include_children=True)
<QuerySet [Relthari(#1), Nevrei(#3), anonymous(#43), Phethjeld(#260), Ari(#261), Zithan(#430), Elithi(#434), Gilgreth(#436), goblin(#28), goblin(#30), goblin(#31), goblin(#32), goblin(#33), goblin(#34), goblin(#35), goblin(#38), goblin(#39), goblin(#40), beady-eyed goblin(#45), pig-nosed goblin(#47), '...(remaining elements truncated)...']>
>>> Character.objects.typeclass_search(Character, include_children=True)
Traceback (most recent call last):
 File "<console>", line 1, in <module>
 File "/home/rel/mud/evennia/evennia/typeclasses/managers.py", line 571, in typeclass_search
   subclasses = cls.__subclasses__()
TypeError: unbound method type.__subclasses__() needs an argument
```

#### Expected behavior

Consistent behavior when passing typeclasses and paths, and recursive search for children.

#### Develop-branch commit

    Evennia 1.0-dev (rev 473f2e379) (rev 473f2e379)
    OS: posix
    Python: 3.10.2
    Twisted: 21.7.0
    Django: 4.0.2

**Comment by Henddher** [comment]
It seems like `typeclass_search` method is not used anywhere at all.

If so, I would probably be better to remove it completely?

```shell
$ git grep typeclass_search
evennia/accounts/manager.py:    typeclass_search
evennia/objects/manager.py:    typeclass_search
evennia/scripts/manager.py:    typeclass_search
evennia/typeclasses/managers.py:    def typeclass_search(self, typeclass, include_children=False, include_parents=False):
```

@Griatch?

**Comment by Griatch** [comment]
@Henddher No, probably better to fix it, and make it more visible than it was before (see #2933). 
From looking at its code, the logic of this could probably be reworked considerably though.

**Comment by Griatch** [comment]
Reworked and fixed the issues with the typeclass_search to use a more modern approach.
