### ISSUE TITLE
[BUG - Develop] Curly braces break object messages

### ISSUE THREAD

**Issue by elixx** [evennia/evennia#2696]
#### Describe the bug
The internal formatting used in `evennia/objects/objects.py` conflicts with messages containing curly-braces.
This breaks the contrib for color compatibility in `color_markups.py` and anyone trying to send a `{`.

#### To Reproduce

```
ELIX:~> !here.msg_contents("Test")
>>> here.msg_contents("Test")
Test
ELIX:~> !here.msg_contents("{bTest")
>>> here.msg_contents("{bTest")
  File "c:\_src\evennia\evennia\objects\objects.py", line 820, in msg_contents
    outmessage = inmessage.format(
ValueError: expected '}' before end of string
```

#### Expected behavior
The string "{bTest" to be emitted.

#### Develop-branch commit
39422d11a

#### Additional context
`objects.py:820` looks like it's now a data structure that is delimited by curly braces.

**Comment by Griatch** [comment]
Yeah, this is why we stopped using `{x` for color formatting. Maybe we can have the markup replace to `\{` internally. :thinking:

**Comment by Griatch** [comment]
Reverted this - trying to escape causes issues with `{}` mapping. This color markup was removed for a reason and is not supported anymore. This will not be fixed. We need to keep the contrib for legacy, but have made a clearer WARNING message in the contrib to warn about its side effects.
