### ISSUE TITLE
[BUG - Develop] AttributeProperty and NAttributeProperty default mutable values are reused

### ISSUE THREAD

**Issue by ChrisLR** [evennia/evennia#2697]
#### Describe the bug
When using a Mutable default value such as a List or a Dict with AttributeProperty or NAttributeProperty,
the same object will be reused for all instances.

#### To Reproduce
1. Add either AttributeProperty or NAttributeProperty to a typeclass, like a character
2. Add a value in one instance
3. Verify the presence of the value in the second instance

#### Expected behavior
Each instance should have its own list (or whatever) mutable object.

#### Develop-branch commit
 Evennia 1.0-dev (rev 177f4a01d) (rev 177f4a01d)

#### Additional context
I know this is similar to the issue where using a default arg with a mutable object will have the same problem.
Perhaps we could support taking in a callable instead, such as the builtins list or dict.
Having them all share the same object can be difficult to track down

Here is a TestCase for this issue

```
from evennia import DefaultCharacter
from evennia.typeclasses.attributes import AttributeProperty, NAttributeProperty
from evennia.utils.test_resources import EvenniaTest


class CharA(DefaultCharacter):
    test_att_list = AttributeProperty([])
    test_natt_list = NAttributeProperty([])


class TestMutableAttribute(EvenniaTest):
    character_typeclass = CharA

    def test_attribute_default_mutable_value_should_be_distinct(self):
        self.char1.test_att_list.append("test_1")
        assert "test_1" not in self.char2.test_att_list

    def test_nattribute_default_mutable_value_should_be_distinct(self):
        self.char1.test_natt_list.append("test_1")
        assert "test_1" not in self.char2.test_natt_list

```

**Comment by strikaco** [comment]
Good catch!

> Perhaps we could support taking in a callable instead, such as the builtins list or dict.

Yes-- would recommend following Dataclass conventions here wrt `default` and `default_factory`. One won't *always* want an empty list as the default value, but you usually don't want a global mutable either.

i.e.

```
default=6
default_factory=list
default_factory=lambda:['pen','pineapple','apple','pen']
```

**Comment by ChrisLR** [comment]
There is also the fact that users will expect to be able to modify lists and dicts as if it was the _Saver equivalent.
Currently, even with auto create, the first get will not return the object because it does not retrieve it after set.
We could fix the auto create and consider auto create as True unless specified otherwise when it is a list or a dict?

**Comment by strikaco** [comment]
> We could fix the auto create and consider auto create as True unless specified otherwise when it is a Mutable object?

Seems like an unnecessary distinction...just set the value and retrieve it in all cases. This gives you early assurance that your data is serializable.

Not all nonmutables can be serialized-- enums and namedtuples come to mind. Best to try to serialize/deserialize everything to force discovery of these types of problems early on.

**Comment by ChrisLR** [comment]
Having autocreate off does help lessen performance cost of using these when the default value is appropriate.
Such as having 0 for an attribute that is unused until set on a typeclass.
Having ten of those will already make ten additional insert trips when creating an object :/

I don't think the benefit of turning it on permanently is worth the cost.

Looking at `dbserialize.py` it seems we already have a good idea of what objects we support.
Perhaps we could make an `is_serializable` using something similar and use it to prevent faulty assigns?

**Comment by strikaco** [comment]
I'm not following my own recommendation with this, but here's a quick workaround:

```
class Field(AttributeProperty):
    
    @property
    def _default(self):
        try:
            return self.__default()
        except:
            return self.__default
            
    @_default.setter
    def _default(self, value):
        self.__default = value
        
class NField(Field):
    attrhandler_name = NAttributeProperty.attrhandler_name
```

**Comment by Griatch** [comment]
While it can be a good idea to support a callable default for different reasons, I don't think this is a bug per se. If you assign a mutable instance on the class level you are asking for trouble, same as doing so in a function argument. 

This seems to work as expected, note that I can use `list()` directly.

```python
class TestObj(DefaultObject):
    tlist = AttributeProperty(list())
```
In-game: 
```
create/drop box1:TestObj
create/drop box2:TestObj 
!self.search("box1").tlist
[] 
!self.search("box2".tlist
[]
!self.search("box1").tlist.append(1)
!self.search("box2").tlist.append(2)
!self.search("box1").tlist
[1] 
!self.search("box2").tlist
[2]
```
