### ISSUE TITLE
[BUG - Develop] How To Make Infinite Logs

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#2702]
#### Describe the bug
If someone who is not very intelligent happens to set the CHANNEL_LOG_ROTATE_SIZE in their settings to a very small quantity, when it comes time to rotate, if _CHANNEL_LOG_NUM_TAIL_LINES is not set to a size smaller than CHANNEL_LOG_ROTATE_SIZE (one of them is lines and the other one is bytes, which is awkward also), then... the rotation will trigger a new rotation will trigger a new rotation... 

#### To Reproduce
1. Set CHANNEL_LOG_ROTATE_SIZE = 100
2. Do anything that creates log text.
3. Watch your folder fill.

#### Expected behavior
Either there should be a minimum value on CHANNEL_LOG_ROTATE_SIZE (but who are you to tell me how tiny my logs cannot be) or _CHANNEL_LOG_NUM_TAIL_LINES should be always be smaller than CHANNEL_LOG_ROTATE_SIZE would allow. 

Or maybe you just get a big old YOUR LOGS ARE GOING TO TAKE OVER THE WORLD warning when that would happen and logging stops working until you fix it.

#### Develop-branch commit
(The commit-hash. If unsure, run `evennia -v` or get the first few lines of the `about` command in-game.)
f093c8bcb

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)
![image](https://user-images.githubusercontent.com/9540334/160938394-77d82694-f14c-4681-a47d-95a7aa39e42a.png)

**Comment by Griatch** [comment]
I set the minimum rotation size to 1000 (1kB) because that's already crazy low and the only reason for ever setting so low is because of thinking that that number is another unit than bytes.
