### ISSUE TITLE
[BUG - Develop] Crafting contrib traceback on unknown recipe

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2703]
#### Describe the bug
If you try to craft a recipe but use a non-existent recipe name, Evennia tracebacks instead of handling the error. I misremembered a crafting recipe as "shirt" and got the following:

```
Traceback (most recent call last):
 File "./evgames/evennia/evennia/commands/cmdhandler.py", line 621, in _run_command
   ret = cmd.func()
 File "./evgames/evennia/evennia/contrib/game_systems/crafting/crafting.py", line 1067, in func
   result = craft(caller, self.recipe, *(tools + ingredients))
 File "./evgames/evennia/evennia/contrib/game_systems/crafting/crafting.py", line 930, in craft
   raise KeyError(
KeyError: 'No recipe in settings.CRAFT_RECIPE_MODULES has a name matching shirt'
```

#### To Reproduce
1. Set up some crafting recipes - the examples are probably fine.
2. Enter a correctly formatted craft command for a non-existent recipe (e.g. `craft sandwich from bread, peanut butter, jelly using knife` in a game that has no recipe for `sandwich`) 
3. See error

#### Expected behavior
I'd expect the game itself to tell me that no such recipe exists, like when trying to `look` at something that isn't there.

#### Develop-branch commit
f093c8bcb

**Comment by Henddher** [comment]
I'll take a look

**Comment by Henddher** [comment]
I think this is the issue:

There's a `raise_exception: bool` to control if an exception is to be raised. That was not being "honored" when the recipe name was unknown.

I added a `NonExistentRecipe` so when a recipe by the given name is not found, a RecipeClass` (that does NOOP) can be passed through the `craft` machinery and (1) return a message to the `crafter` and fail "gracefully" within the machine and eventually return `None`.

PR on its way :smile: 

#Hacktoberfest
