### ISSUE TITLE
[BUG - Develop] `rpsystem` object search can't handle duplicate names

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2705]
#### Describe the bug
When there are two or more objects of the same name in a list of candidates (e.g. the default of a character's contents and location's contents), only the first one is located.

#### To Reproduce
1. Inherit from the `ContribRP` classes on your `Object` and `Character` class.
2. `create test object`
3. `create test object` again
4. `py self.contents` to confirm both are there
5. `py self.search("test object")` and `py self.search("test object", quiet=True)`
6. See error

#### Expected behavior
It should give a multi-match error, or return all matching objects if `quiet=True`.

#### Develop-branch commit
f093c8bcb

**Comment by InspectorCaracal** [comment]
I went in to fix this so I could keep working on my own game and found the source of the problem.

For some reason my objects aren't getting the `sdesc` handler attached (which is a separate issue) which results in the system using [the "legacy" object parser](https://github.com/evennia/evennia/blob/f093c8bcb1321a44e33003cf91cf9f565e028de7/evennia/contrib/rpg/rpsystem/rpsystem.py#L302-329).

This builds a regex tuple based on an object's key and adds it to the cache, but only if a tuple with the same key doesn't already exist. Thus, if multiple "legacy" objects have the same key, it parses the key to the cached tuple for only the first object, resulting in only that object being found.

Since this is a legacy support issue and not a core system issue, it's a low priority fix and possibly even closeable.

**Comment by Griatch** [comment]
> ***edit: I know I said that the sdesc handler not being attached is a separate issue, but I discovered that it isn't attached because... it isn't. All non-Character objects have no sdesc handler, which means that this problem will arise for all non-Character objects with identical names and it isn't a legacy issue but a built-in one.

The `ContribRPObject` doesn't natively have an `sdesc/recog` assigned to them. This is because the native `send_emote` only targets other characters, not objects. I suppose the default `pose` command _does_ include other entities though, so maybe there is an argument for defaulting regular `ContribRPObject`s to have the `sdesc/recog` setup as well, just for consistency ...

**Comment by Griatch** [comment]
Anyway, main issue closed in #2720.
