### ISSUE TITLE
[Feature Request] Improve performance of rpsystem search

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2724]
#### Is your feature request related to a problem? Please describe.

RPSystem's `ordered_permutation_regex` runs very slowly for for objects with long names since it is a factorial-time algorithm. This can causesnoticeable multi-second hangs to compile all of the regexes in preparation for a search.

#### Describe the solution you'd like

If we sacrifice the ability to match words out of order (e.g. matching "man tall" for a tall man), we can remove the need to generate permutations and can do a much simpler search that also does not require writing cached regexes to persistent attributes.

One way to do this (what I ended up doing in my codebase) is to generate only a single regex for an incoming query. We then run this regex against each candidate object's recog (if available), key, and aliases (if necessary) to find matches. This inverts the regex matching behavior from what is done today and only generates one regex per query. This nd runs much much faster against all objects (especially those that are not RPSystem-aware).

Below is the code I use to handle the search portion of this (where the performance bottleneck lies). It's not a direct drop-in as I built my own RPSystem-analogue that decouples the parsing of emote markers from the searching for objects that match them, but the algorithm is here and could be ported.

```py
def search_candidates_by_appearance(caller, query, candidates, exact=False):
    """
    Search the appearance of provided set of candidates for one or more that
    match a given query.

    This search takes into account appearance attributes set on candidate
    objects if present, as well as remembered names from the caller, if
    available. It specifically excludes the true name (key) of candidates
    hidden by appearances that are unknown to the caller, unless the caller
    is a builder.

    Args:
        caller (Object): The object performing the search.
        query (str): A string to search for.
        candidates (list): The list of possible candidates to search.
        exact (bool): True to require an exact match of the query against any
            valid appearance string.
    Returns:
        list: A list of zero or more matches from the provided candidates.
    Notes:
        Each candidate can be matched either by its appearance, remembered
        name, or a numerical separator attached to either ("2-elf")
    """
    # Strip and extract numerical match prefix, if any.
    index = None
    if index_match := _SEARCH_MULTIMATCH_REGEX.search(query):
        index = int(index_match.group("number"))
        query = index_match.group("name")
    is_builder = caller.permissions.check("Builder")

    # Add display name and appearance for each candidate. Recognized names are
    # handled by get_display_name if supported.
    candidate_text = {}
    for item in candidates:
        texts = list(item.aliases.all())
        is_character = hasattr(item, "is_typeclass") and item.is_typeclass(
            "typeclasses.characters.Character", exact=False
        )

        if is_builder or not is_character:
            # Add item key only if this is not a character. Characters match
            # by appearance instead. Builders can always match by key,
            # however.
            texts.append(item.key)

        display_name = item.get_display_name(caller, dbref=False)
        texts.append(display_name)
        if exact:
            # For exact searches, also add the display name without any prepended
            # articles, as these will throw off exact matching.
            bare_display_name = item.get_display_name(caller, dbref=False, article=None)
            if bare_display_name and bare_display_name != display_name:
                texts.append(bare_display_name)
        appearance = item.short_desc if hasattr(item, "short_desc") else None
        if appearance and appearance != display_name:
            texts.append(appearance)
        candidate_text[item.id] = texts

    # Regularize query.
    if exact:
        rquery = f"^{query}$"
    else:
        rquery = "".join([r"\b" + re.escape(word) + r".*" for word in iter(query.split())])
    rquery = re.compile(rquery, _RE_FLAGS)

    candidate_map = {candidate.id: candidate for candidate in candidates}

    # Search candidates.
    results = []
    for id, texts in candidate_text.items():
        for text in texts:
            if rquery.search(text):
                # This candidate matches, move onto the next one.
                results.append(candidate_map[id])
                break

    # If the search provided a specific index, just return that one. Note
    # that indexes are 1-based.
    if index:
        if 1 <= index <= len(results):
            return [results[index - 1]]
        # If we got a bad multimatch index, return nothing to generate an
        # error.
        return []

    return results
```

**Comment by InspectorCaracal** [comment]
It looks like the main benefits to this method are not needing to store regexes and only having to generate at most one regex per search, rather than at least one, so I'm curious about this:

> If we sacrifice the ability to match words out of order (e.g. matching "man tall" for a tall man), we can remove the need to generate permutations and can do a much simpler search that also does not require writing cached regexes to persistent attributes.

Could you retain some of that out-of-order functionality by generating a permutation regex from your search query instead? I understand it's a heavier regex computation, but I don't have a sense for how much slower it would be or if it would work.

**Comment by owllex** [comment]
That's going to be a heavy lift. Your regex would need to contain all of those permutations, which will make it slower. I haven't benchmarked it, but I don't think it's going to be worth it.

**Comment by InspectorCaracal** [comment]
This should be much better as of #2728

**Comment by Griatch** [comment]
Let's close this for now; the change in #2828 implements something along the lines of this (but made within the context of the contrib). We can open new tickets if other, specific issues emerge with the rpsystem contrib. Thanks for the inspiration/suggestion for this @owllex, and the implementation, @InspectorCaracal! :+1:
