### ISSUE TITLE
[BUG - Develop] Character remains puppeted after player goes link dead

### ISSUE THREAD

**Issue by jumpscarejumpscare** [evennia/evennia#2734]
#### Describe the bug
If someone loses their connection to Evennia without quitting/unpuppeting properly, their character will still be marked as online until they receive a msg of some kind.

When the window is closed, the 60 second detection might detect that the account is no longer active, but the character doesn't get unpuppeted until something "observes" the character. I'm not sure how best to describe it. It's like Schrodinger's Character, you don't know if it's logged out until it's observed.

For example, a link dead character will just remain in a room by itself, forever. Once your character either enters the room or says something in the room, you'll instantly see them get unpuppeted, even if they logged out over a day ago.

Owllex has stated observing this in Owllex's game, too.

This has been observed in 1.0, but I originally experienced it in 0.9.5 and have upgraded since.

#### To Reproduce
1. One way of achieving a logged-in link dead state is by browsing to the webclient and logging on with one character in a tablet's browser. Next, press the home button to leave the browser, then turn off the tablet.
2. Wait a few minutes.
3. Have a second character walk into the room that the link dead character is in. You'll see the character there.
4. Sometimes that's enough to get the link dead character to be unpuppeted. Other times you need to take a single action in the room.
5. See error in "Additional context" section.

#### Expected behavior
The link dead character should be unpuppeted after the 60 second timeout. According to Griatch, "If you close the client window without logging out normally, the portal should ping and detect this after a 60 second timeout. Or sooner, if data is tried to be sent to the disconnected client before that."

The "or sooner" part seems to be doing its job, but not the 60 second timeout.

#### Develop-branch commit
        Evennia version: 1.0-dev (rev f093c8bcb)
        OS: posix
        Python: 3.9.5
        Twisted: 21.7.0
        Django: 4.0.3

#### Additional context
Here's a log of it happening in-game, from the perspective of a character named Bonnie walking in on a link-dead character named Clyde. Bonnie moves into the room with Clyde. (Clyde should have received a message about Bonnie entering the room, but it doesn't cause Clyde to be unpuppeted.) Then Bonnie says "Um," which causes Clyde to be unpuppeted.

You head toward the west.

[...New room description...]
Clyde is standing here.
[...]

You say, "Um."
Exhaustion's hand engulfs Clyde in dreamless rest. (This is the unpuppeted message.)

**Comment by InspectorCaracal** [comment]
I've found another, probably slightly simpler way to duplicate the session failing to time out, which I believe is the underlying issue here.

If you connect to the webclient via the AJAX fallback instead of websockets and close the tab, the session remains active, seemingly indefinitely.

**Comment by InspectorCaracal** [comment]
... I took another peek at this today and I think I found the problem. >.>

> default settings
`IDLE_TIMEOUT = -1`

I'll change that in my settings later to verify but I think it's really that simple - the default settings just have idle timeouts turned off.

**Comment by Griatch** [comment]
@InspectorCaracal The optional `IDLE_TIMEOUT` is a separate thing; it disconnects a user that is connected, but idle. It's usually set to something long, like 7 days. This ticket deals with a link-dead player, which is a different thing.

**Comment by Griatch** [comment]
I can't reproduce this locally. :disappointed:  I have killed the webclient in all sorts of ways in both firefox and chrome without leaving any unpuppeted character behind in the room. 
Also tested with an AJAX connection, like @InspectorCaracal suggested, but while it takes some 30s for this type of connection to detect a link-drop, it always cleanly unpuppets the character for me.

**Comment by Griatch** [comment]
This should be resolved now, with the merger of the feature suggested in #2829.
