### ISSUE TITLE
[BUG - Develop] LOCALECHO flag has no effect when using the webclient

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2742]
#### Describe the bug
When `option LOCALECHO=True` and using the webclient, the input text isn't echoed back to the client

#### To Reproduce
1. Set up an account in a game and connect with the webclient
2. set the `LOCALECHO` option to True
3. Enter any commands

#### Expected behavior
The flag is supposed to cause the portal to echo back whatever you sent, regardless of protocol.

#### Develop-branch commit
7f4769bd9

**Comment by InspectorCaracal** [comment]
I've tracked down what's breaking this.

https://github.com/evennia/evennia/blob/f47c7231/evennia/web/static/webclient/js/evennia.js#L151-L159

When the webclient receives the server-side echo, it includes a cmdid kwarg. This particular section of the code then catches that and attempts to reference it in `cmdmap` and promptly errors with: `Uncaught TypeError: cmdmap[kwargs.cmdid] is undefined`

It seems as though the webclient is sending the cmdid value to the server in case it needs to trigger a specific callback on a response from the server, which the server would then identify by including the `cmdid` kwarg in the return value. Except, if there was no callback stored for the cmdid, the entire message chain in the client just fails completely.

I'll submit a PR shortly to fix it but I can't for the life of me figure out what the use-case for this would be....

**Comment by Griatch** [comment]
Closed in #2750
