### ISSUE TITLE
[BUG - Develop] `EvTable` overrides `EvColumn` styling with defaults

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2760]
#### Describe the bug
Attempting to style individual `EvColumn` elements using the allowed kwargs (e.g. `fill_char`, `align`) is overridden by the table's settings, _even if_ no styles have been explicitly passed to the `EvTable` and it's just assuming defaults.

#### To Reproduce
```py
column = EvColumn("this","is","a","column",fill_char='.')
table = EvTable(table=[column])
print(table)
```

#### Expected behavior
I'd expect the column to use the `.` to fill in extra space as explicitly set, but it instead uses the default implicit ` `.

I haven't rigorously checked all of the options, but it happens with `align` as well.

#### Develop-branch commit
f47c72317

**Comment by Griatch** [comment]
It's important to note if this is for terminal or webclient and if it appears for both.

**Comment by Griatch** [comment]
This now works. The error was again that `EvTable(table=[column])` was not a valid input and the column you provided would not share its options but be treated as a string. Since I now added support for this syntax, this now works (verified with a unittest).
