### ISSUE TITLE
[BUG - Develop] `EvTable` enforces `width` kwarg, but then expands the column anyway

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2761]
#### Describe the bug
Explicitly setting a width on a column results in any cells longer than that being cropped, which is correct. However, if the table width is set larger, it expands the column to beyond the declared width.

#### To Reproduce
```py
colA = EvColumn("it","is","a","column",width=5,enforce_size=True)
colB = EvColumn("and","another","column","here")
table = EvTable(table=[colA,colB],border=None,width=40)
self.caller.msg(table)
```
This crops "column" to fit the width and then adds on extra fill space, leading both to a column that is wider than desired and to having text cropped when it would fit.

#### Expected behavior
The first column should be capped at the width of 6, and the _second_ column should be the only one to expand to fill the table width. (If there were 3 columns and the first had a width set, I would expect the 2nd and 3rd to expand, etc.)

#### Develop-branch commit
f47c72317

**Comment by Griatch** [comment]
The main issue with this ticket was that `table=[colA, colB]` is an invalid call. Basically your column got converted to a string and that extra width info was lost. This is now supported via the changes following the resolution of #2762. Note that the width you give includes the padding and borders, so you must account for this. 

This however unearthed another bug with the crop mechanism, which I've now resolved; if the column is narrower than the crop-string (such as `[...]`) it will now skip it and just crop the text without adding anything (best we can do in that case). 

The expected outcome of this is:

```
+----+---------------------------------+
| it | and                             |
| is | another                         |
| a  | column                          |
| co | here                            |
+----+---------------------------------+
```
