### ISSUE TITLE
[Documentation] CSRF_TRUSTED_ORIGINS needs to be set in settings for online setup

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#2767]
#### Existing page / new
[(Link to existing documentation page or proposed name of new page)](https://www.evennia.com/docs/latest/Online-Setup.html?highlight=release)

#### Documentation issue
Right now `CSRF_TRUSTED_ORIGINS` isn't a setting in the documentation, it should be though - several people have been on the discord about it (me, zephyr, elixx) which implies there are more that haven't done so, or found what they needed by searching discord and didn't comment.

#### Suggested change
Add 

`CSRF_TRUSTED_ORIGINS = ['https://mymudgame.com']`

To the SETTINGS EXAMPLE section, with a comment

> This needs to be set to your website address for django or you'll receive a CSRF error when trying to log on to the web portal

Or something similar.

**Comment by Griatch** [comment]
Looks like since Django 4.0 you need to include the scheme, so e.g. `['https://mymudgane.com']`. I updated the original since people look at this issue and may not see this comment.

**Comment by Griatch** [comment]
Closed in #2879
