### ISSUE TITLE
[BUG - Develop] Style Command - references a command (@tz) that doesn't exist

### ISSUE THREAD

**Issue by ShardsDev** [evennia/evennia#2770]
#### Describe the bug
In the Style command help, it references @tz which does not seem to exist anywhere. 

#### To Reproduce
1. Type style in game.
2. type @tz 
3. See error

#### Expected behavior
The time zone list should show; or the help file should be corrected.

#### Develop-branch commit
(The commit-hash. If unsure, run `evennia -v` or get the first few lines of the `about` command in-game.)
 Evennia version: 1.0-dev (rev c511b4b68) 

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by Henddher** [comment]
What's the expected behavior?
