### ISSUE TITLE
[BUG - Develop] Help Command doesn't honour Style settings

### ISSUE THREAD

**Issue by ShardsDev** [evennia/evennia#2771]
#### Describe the bug
(This is for bugs in the develop-branch only. Make sure you test with the latest version.)

#### To Reproduce
1. use the style command to update help_category_color and help_entry_color
2. type help or help <command.>
3. See error - the style colors don't show up.

#### Expected behavior
The help category and help entry colors should match the changed style colours.

#### Develop-branch commit
(The commit-hash. If unsure, run `evennia -v` or get the first few lines of the `about` command in-game.)
 Evennia version: 1.0-dev (rev c511b4b68)
#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by Griatch** [comment]
The `help_category_color/help_entry_color` were unused and also too specific; one should customize the `help` command for this kind of change. These style categories were removed.
