### ISSUE TITLE
[BUG] Issue creating superuser

### ISSUE THREAD

**Issue by Misan404** [evennia/evennia#2782]
Trying to create a superuser after migrating and it won't let me type in a password. I can put in a username and optional email, but when it asks for a password, I can't type anything. I can hit enter and it'll ask for me to enter the password again. Hitting enter a second time will say the passwords don't match.

**Comment by Griatch** [comment]
@Misan404 I see no issues with the password creation ... Note that when you type the password you will not see anything in the terminal (echo is disabled) - but what you type will still be entered). Try typing the password you want, press enter and type it again and see if that works.

**Comment by Griatch** [comment]
Closing this issue. If you still have trouble, comment here with how to reproduce (and what OS/system you are using), and we can re-open.
