### ISSUE TITLE
[BUG - Develop] Over 9000 prototypes? Spawn slower than molasses

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#2792]
#### Describe the bug
When there are a ton of DbPrototype scripts saved in OLC, spawn becomes unbearably slow. Average of 8-15 seconds where the game locks up before it finally spits out an object.

#### To Reproduce
1. Create over 9000 DbPrototypes
2. Try to spawn one of them.
3. Cry as it takes 15 seconds.

#### Expected behavior
Well, presumably spawning an object shouldn't take longer than a few blinks...

#### Develop-branch commit
22fa2c6b

#### Additional context
I've deduced that this is only happening with DbPrototypes and it seems to have nothing to do with Django. if I do...
```python
DbPrototype.objects.filter_family(db_key="my_prototype").first()
```

instant result...

Storing all of the prototypes as .py modules also doesn't seem to cause this.

This also appears to happen even if you are just spawning the simplest object possible, having nothing to do with the SAVED PROTOTYPES.

spawn {"key": "Worthless Junk"}
Will also take forever.

This has no correlation with the number of ObjectDB instances mind you because even with 450,000 objects, dig is instantaneous but spawn lags.

**Comment by strikaco** [comment]
(This was poked around at before in #2126. This particular stone was left unturned :) )

If you hit L410 and bypass the L412 block, `db_ids` on L424 would be a list of 9000+ ids. There might be a way to improve this but I'm not convinced this is "the" problem.

https://github.com/evennia/evennia/blob/47371d7e020c781f1c58d7969ee0c2e80cd687b8/evennia/prototypes/prototypes.py#L404-L427

When you go to spawn "the simplest object possible," you definitely trigger a manual evaluation of a 9000-member queryset (L627) to compile a dict of potential parent objects. From `validate_prototype`:

https://github.com/evennia/evennia/blob/47371d7e020c781f1c58d7969ee0c2e80cd687b8/evennia/prototypes/prototypes.py#L625-L630

My brain has turned to mush as of late but if I'm reading this right, then in addition to the above, *this whole process repeats for each parent* in the aforementioned dict. There's a for-each-protparent a few lines above this:

https://github.com/evennia/evennia/blob/47371d7e020c781f1c58d7969ee0c2e80cd687b8/evennia/prototypes/prototypes.py#L680-L682

I think caching of validated prototype parents is necessary to correct this.

**Comment by Griatch** [comment]
I implemented and refactored the DbPrototype loading and added caching of the prototype-parents. Spawning from a set of 9000 Db prototypes is now almost instantaneous. Listing them all (`spawn/list`) can still take a while, but after the first time listing will also be fast.
