### ISSUE TITLE
[Feature Request] (Traits contrib) Make Traits able to access other Traits

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2801]
#### Is your feature request related to a problem? Please describe.
The Traits contrib is extremely useful, but it's missing one major capability that virtually everyone who's used it has needed - the ability for one trait to reference the value of another trait.

For example, in a typical stat+skill game design, each skill will be influenced by a base stat - let's say the skill of Lockpicking, and the stat of Dexterity. It would be very useful to set up Lockpicking so that you simply pass it the Dex trait when you initialize it and it can then apply any bonuses or penalties to your Lockpicking skill from the Dex trait.

The problem is that the Traits have no way of knowing even what object they're attached to, let alone be able to see each other, making it difficult to implement that kind of stat bonus.

#### Describe the solution you'd like
I really don't know what the best solution here is, but the desired final functionality is to be able to initialize a single Trait so that it can reference character data from outside the Trait itself. e.g. let Locksmithing find its own Dex mod.

#### Alternatives you've considered
At the moment, the only way to achieve this kind of logic is to add additional functions to the Character and interact with any affected traits through those functions instead of the handler, which I think somewhat undermines the purpose of having it packed into a handler.

**Comment by Griatch** [comment]
I'm honestly not convinced this is a good idea. A Trait is a database-stored property. What you describe is a dynamic property that really should be calculated on the fly (based on the current values of db-backed Traits) and not stored in the db at all. 
I'd probably make such a property a normal `property` that accesses Traits under the hood to calculate its current value.

**Comment by InspectorCaracal** [comment]
Conceptually, it's basically the same as `trait.current` - you have a base value, you have modifiers, you calculate the current value on demand. It's just a matter of adding any sort of support for accessing pieces of the data besides its own little corner.

**Comment by strikaco** [comment]
> I'm honestly not convinced this is a good idea. A Trait is a database-stored property

Agreed 100%, but there is some precedent for the idea as proposed-- other game systems (like RPGMaker and Ranvier) will let you store the formula (as string/JSON) to derive a stat as the value of the Stat itself. RPGMaker has a userbase that eclipses all active MUDs.

For the sake of winning (or retaining) hearts and minds, would it be out of the question to accept (but not *store*) a lambda or callable or something?

**Comment by whitenoiseoss** [comment]
I agree this is a use-case I did not consider initially, but it is how "secondary stats" are often calculated.

I wrote this to Caracal on Discord a bit ago:
this wouldn't be a hard change depending on how it needed to work, i'm sure you could do it. either you would add something like an "influencers" list and return their values as part of the actual and value OR you would have a "InfluencedTrait" whole new type that just returns aggregated Traits. Both of those things are different....so they could both be added, really.

This was the type of approach I had in my mind...something like you are just including the `.value` of all the Traits that it is "influenced" by. Is there a problem with this approach?

**Comment by Griatch** [comment]
@InspectorCaracal I added the back-reference `Trait.traithandler` so you can now do `Trait.get_trait("key")` from a trait to get the value of another trait. https://github.com/evennia/evennia/commit/7a7479955fbda8774819dac8b021ec30ab6d13ed

None of the default Traits make use of it, so you need to make your own custom trait subclasses to use it, but that's probably something you need anyhow since such relationships are bound to be game specific. 

I think that is all I'll do about this ticket; so I'm closing it. If you feel something more should be needed, feel free to suggest a re-open :)
