### ISSUE TITLE
[BUG - Develop] Traceback on multimatching session commands

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2839]
#### Describe the bug
I've discovered an unusual bug regarding these lines:
https://github.com/evennia/evennia/blob/8b9e1da9413202de69e5467a98e652fe7d58e1de/evennia/commands/command.py#L531-L532

It seems as though it's intending to check if the command is attached to an object and only call the display name hook if it is. However, the `obj` property isn't always an Object or Character - it will _also_ return the Account or Session that the command is attached to, if it's an account- or session-level command.

This becomes a problem if you multimatch on a command input which includes a session-level command match because, unlike Objects, Characters and Accounts, the various Session types have no `get_display_name` method. Which then results in:
```
File "./evennia/evennia/commands/command.py", line 532, in get_extra_info
    return " (%s)" % self.obj.get_display_name(caller).strip()
AttributeError: 'ServerSession' object has no attribute 'get_display_name'
```

#### Possible Solutions
I can see a few different ways to handle this, and I'm unsure which would be best.

1. Change `get_extra_info` on commands to validate the existence of `get_display_name` on the attached `obj` property before calling it
2. Give sessions a `get_display_name` hook
3. Change the `obj` property on commands so it only returns in-game objects (this is probably the worst option)

#### Develop-branch commit
8b9e1da94

**Comment by Griatch** [comment]
The Session should also have an `get_display_name` hook, if only a stub for `.key` for now. In the future, we'll turn `Session` into `SessionDB` and then this will be easier to convert that way.

**Comment by Griatch** [comment]
Implemented a fix for this without first looking for a PR :( My variant will fall back to object/account display names if they are available. I _think_ that should be the most useful; it's unusual to actually need to know the name of the session itself after all.
