### ISSUE TITLE
[BUG - Develop] Log rotation infinite-loops

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2875]
#### Describe the bug
My log file reached the maximum size and when trying to rotate, it hits an infinite loop.

https://github.com/evennia/evennia/blob/3992f37dada8ae9d495b7bdc087ff107e21e29aa/evennia/utils/logger.py#L352-L354

I think maybe it's supposed to be `super().rotate()` instead of `self.rotate()`?

#### Develop-branch commit
3992f37da

**Comment by Griatch** [comment]
D'oh, yes of course :/
