### ISSUE TITLE
[BUG - Develop] False positives on URL detection

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2883]
#### Describe the bug
If someone e.g. says "Awww." in-game, the pattern `www.X` gets picked up as a web address by the text2html parser.

#### To Reproduce
1. Open up the webclient for an active game.
2. `emote www.t`
3. See error

#### Expected behavior
The URL detection for the text2html parser needs to be reworked to avoid false positives, or possibly removed entirely. I'm of the opinion to remove it entirely. If I take on fixing this, which is likely, that's the approach I'll take.

#### Develop-branch commit
3992f37da

**Comment by selberhad** [comment]
I looked into this, IMHO the regular expression used to pick up URLs would benefit from being a bit more restrictive.

That said, there would be some design decisions to make. For example, currently typing wwww.example.com will turn into w[www.example.com](www.example.com), which seems pretty weird to me, unless it's just trying to be forgiving of common typos.

I think the ideal user experience would result from requiring a boundary character `\b` before the URL in the regex, but that would break [this test](https://github.com/evennia/evennia/blob/master/evennia/utils/tests/test_tagparsing.py#L307-L311).

Personally I think this is a nice feature to have, as long as it errs on the side of not hyperlinking non-links.

**Comment by InspectorCaracal** [comment]
I'm of the general opinion that things like identifying sections of message strings as URLs should all be done client-side, which in this case would mean reimplementing it in the webclient. If we *do* want URL detection to be done server-side, then I think it should be done consistently for all protocols - but as I said, I think it's the kind of feature that should be done by the client.

**Comment by selberhad** [comment]
I don't have a strong opinion here, but why URLs specifically? You could just send pure ANSI over the websocket and have all of the ANSI to HTML conversion live client-side.

Even if moved client-side, there would still be all of the same decisions to make about permissiveness. E.g. right now it thinks `http!!!!!example.2` is a URL.

**Comment by aMiss-aWry** [comment]
One reason to do it server side could be parsing URLs into clickable links via MXP for clients that support it.

**Comment by InspectorCaracal** [comment]
> I don't have a strong opinion here, but why URLs specifically? You could just send pure ANSI over the websocket and have all of the ANSI to HTML conversion live client-side.

There's nothing about URLs specifically, but recognizing an unmarked string of text and deciding to apply formatting to it is very different from converting existing and intentional formatting tags to a different style of formatting tags. Currently, URLs are the only thing that have that kind of process applied - and it's broken, so the cleanest solution to me is "don't do it".



> One reason to do it server side could be parsing URLs into clickable links via MXP for clients that support it.

Yeah, if it was done server-side I think this would be the way to do it.
