### ISSUE TITLE
[BUG - Develop] inline funcparsers sent to `msg_contents` parses the same for everyone

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2909]
#### Describe the bug
When passing an inline func for the new funcparser, it parses the string from the perspective of the first object in the list of contents and then uses that same parsed message to all of the successive messages.

#### To Reproduce
1. Add the test command class I provided under "Additional context"
2. Create two characters and have them each execute the command.
3. The string will print with the correct *actor* but from the perspective of whichever character was created or entered the room first, to both characters.

#### Expected behavior
I believe it's supposed to parse each time so the viewer sees the correct names relative to themself.

#### Develop-branch commit
3992f37da

#### Additional context
```python
class TestFuncparser(Command):
    """Usage: test <object>"""
    key = "test"

    def func(self):
        caller = self.caller
        location = caller.location

        target = caller.search(self.args.strip())
        if not target:
            return

        message = f"$You() point at $you({target.name})."

        location.msg_contents(message, from_obj=caller, mapping={"you": caller, target.name: target})
```

**Comment by InspectorCaracal** [comment]
A quick additional "demo" of it, in case my explanation wasn't clear.

Here, I'm on my admin account, which I have two characters for, "admin" and "zeno". In a separate session I have a test account, with a character named Monty.

Here's what it looks like for account admin:
```
py here.contents
>>> here.contents
[admin, Monty]
test monty
You point at Monty(#3).
ic zeno

You become zeno.
Limbo(#2)
[...]

Characters: Monty(#3)
py here.contents
>>> here.contents
[Monty, zeno]
test monty
zeno points at you.
```

Meanwhile, this is what Monty saw:
```
You point at Monty(#3).
admin has left the game.
zeno has entered the game.
zeno points at you.
```

**Comment by Griatch** [comment]
Hm, this has been tested quite a bit. There is no need for `you: caller` in the mapping, this is taken from `from_obj`. I wonder if this is what confuses the system?

**Comment by Sk33t3rson** [comment]
> Hm, this has been tested quite a bit. There is no need for `you: caller` in the mapping, this is taken from `from_obj`. I wonder if this is what confuses the system?

I have tested this without the you:caller and still receiving the same issue.

**Comment by InspectorCaracal** [comment]
> Hm, this has been tested quite a bit. There is no need for `you: caller` in the mapping, this is taken from `from_obj`. I wonder if this is what confuses the system?

I just tried again to verify, since it's been a while, and it's the same without it. I added it in originally to eliminate possible missing information, but it made no difference.

**Comment by InspectorCaracal** [comment]
I took a quick look at the `msg_contents` function and found the problem:
https://github.com/evennia/evennia/blob/5ae3941841827c1b37ca03890ba79fc8774fee0c/evennia/objects/objects.py#L766-L767

It's replacing `inmessage` with the parsed version on the first receiver, causing all later receivers to get that parsed version instead of reparsing. I have some time at the moment so I'll put in a quick PR to fix it.

**Comment by Sk33t3rson** [comment]
> 

I can also confirm that its the case of who is lead in  db_Characters: 

Characters: Ant1(#7), Sk33t3rson(#1)

from Skeet3rson perspective
You open a Metal reinforced gate
from Ant1 perspective
You open a Metal reinforced gate

Characters:  Sk33t3rson(#1), Ant1(#7)

from Skeet3rson perspective
Ant1(#7) opens a Metal reinforced gate
from Ant1 perspective
Ant1(#7) opens a Metal reinforced gate
