### ISSUE TITLE
[BUG - Develop] Funcparser `_MAX_NESTING` isn't applied properly

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2926]
#### Describe the bug
The process for checking `_MAX_NESTING` in funcparser.py is too permissive. When it is set to 2 it allows nesting up to 4 before it fails

#### To Reproduce
```
    @patch("evennia.utils.funcparser._MAX_NESTING", 2)
    def test_parse_max_nesting(self):
        """
        Make sure it is an error if the max nesting value is reached.
        """
        string = "$add(1, $add(1, $toint(42)))"
        ret = self.parser.parse(string)
        self.assertEqual("$add(1,$add(1,$toint(42)))", ret)
```

This test currently fails

#### Expected behavior
The value of `_MAX_NESTING` should be applied properly and the test passes. It looks like currently it takes N+2 calls to trigger the nesting failure, since `len(callstack)` is 0 when encountering the first function call. An off by one error.

#### Develop-branch commit
b0f24f9975e14fddeabef06a19b5b61575957b1c

#### Additional context
This was discovered when writing tests in #2918

**Comment by Griatch** [comment]
This should be easy to fix, but leaving it up for Hacktoberfest contestants :)
