### ISSUE TITLE
[Feature Request] Option to redirect logs to stdout when writing tests

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2939]
#### Is your feature request related to a problem? Please describe.
When writing unit tests, some failures may be hidden because they are logged to the twisted logging system and not echoed to stdout.

#### Describe the solution you'd like
A flag that can be set in evennia.utils.logger that would redirect logging to stdout when in a test.

#### Alternatives you've considered
Originally I thought that all logging should go to stdout when in a test, but that would probably lead to logspam. It would be better if it could be toggled while tests are being written and then toggled back off.

#### Additional context
I know logging goes to standard out when `evennia start -l`, so there is some way to do this. I could probably implement it myself if I looked more into it, but I wanted to suggest it first to make sure it's non-controversial before tracking it down.

**Comment by Griatch** [comment]
`evennia start -l` does not go to standard out - it just opens a program that tails the regular log files and echoes it to the screen :D You may be thinking of `evennia istart`, which opens Evennia in interactive mode. This _does_ echo to stdout; this is a setting passed to twisted though. 

Logging is disabled during unit testing afaik. Being able to see what would be logged sounds like a potentially useful idea, but it's not standard behavior. I wouldn't offhand know how to do it. I guess one could modify the underlying twisted logger somehow, but is it worth the effort?

**Comment by audiodude** [comment]
Thanks for the info on `start -l` and `istart`. I think it would be useful because sometimes when I'm writing tests, my intuition on how a function should behave is off and the function fails without any output, it just does a log of the error. Seeing that specific log on stdout for that specific test would be very useful. For now, I'm changing log functions to print statements temporarily.

**Comment by Griatch** [comment]
Reviewing this again, hacking the twisted logger for this would not be worthwhile; if tracing a particular issue for a particular test one should rather use `from evennia import set_trace;set_trace()` and run the test in interactive mode.
