### ISSUE TITLE
[BUG] Evennia test raises RuntimeError after upgrade to django 3.2

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#2946]
#### Describe the bug
I decided to finally see about maybe updating the version of Evennia I'm using for Arx. There were a few trivial changes to address deprecations, but a more serious issue is that the test runner completely refuses to function. After running through migrations for the test database and adding context types/permissions, I get the following error, which only touches library code:
```
Using settings file 'test_settings' (server.conf.test_settings).

    TESTING: Using specified settings file 'server.conf.test_settings'.

    OBS: Evennia's full test suite may not pass if the settings are very
    different from the default (use 'evennia test evennia' to run core tests)

Creating test database for alias 'default'...
Traceback (most recent call last):
  File "D:\arx\venv\Scripts\evennia_launcher.py", line 18, in <module>
    main()
  File "D:\arx\evennia\evennia\server\evennia_launcher.py", line 2282, in main
    sys.exit(execute_from_command_line(sys.argv))
  File "D:\arx\venv\Lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "D:\arx\venv\Lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\arx\venv\Lib\site-packages\django\core\management\commands\test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "D:\arx\venv\Lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\arx\venv\Lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "D:\arx\venv\Lib\site-packages\test_without_migrations\management\commands\_base.py", line 78, in handle
    super(CommandMixin, self).handle(*test_labels, **options)
  File "D:\arx\venv\Lib\site-packages\django\core\management\commands\test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "D:\arx\venv\Lib\site-packages\django\test\runner.py", line 725, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "D:\arx\venv\Lib\site-packages\django\test\runner.py", line 643, in setup_databases
    return _setup_databases(
  File "D:\arx\venv\Lib\site-packages\django\test\utils.py", line 179, in setup_databases
    connection.creation.create_test_db(
  File "D:\arx\venv\Lib\site-packages\django\db\backends\base\creation.py", line 90, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "D:\arx\venv\Lib\site-packages\django\db\backends\base\creation.py", line 136, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "D:\arx\venv\Lib\site-packages\django\core\serializers\__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "D:\arx\venv\Lib\site-packages\django\core\serializers\base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "D:\arx\venv\Lib\site-packages\django\db\backends\base\creation.py", line 125, in get_objects
    for model in app_config.get_models():
  File "D:\arx\venv\Lib\site-packages\django\apps\config.py", line 287, in get_models
    for model in self.models.values():
RuntimeError: dictionary changed size during iteration
```

#### To Reproduce
1. Have a game with other apps/models
2.  run `evennia test --settings=<your settings file here>`
3. See error

#### Expected behavior
The test runner to function the same as it did in django 2.12

#### Environment, Evennia version, OS etc
Evennia 0.9.5 (rev 8f916cb20) (rev 8f916cb20)
OS: nt
Python: 3.8.3
Twisted: 21.7.0
Django: 3.2.16

#### Additional context
My only running theory is that it might have something to do with how Evennia creates typeclasses, since they're proxy models that aren't fully registered. If you try to run `makemigrations` it'll try to generate bogus migrations inside the evennia.typeclasses app. Possibly they could be mucking up the test database here in some way with some new change they made in django's test runner in 3.2?

**Comment by Griatch** [comment]
@TehomCD Makemigrations should not be run on your typeclass children, remove those if you have them. Have you introduced any new base tables? Maybe there's some issue there? 

Afaik this works just fine in Evennia 1.0-dev using Django 4+, so it seems unlikely this is due to some fundamental change in typeclass handling ...

**Comment by TehomCD** [comment]
`makemigrations` without any arguments will try to create migrations for any typeclasses that a game creates, though you can avoid this by either manually deleting the migrations or only running app-specific migrations. I mostly brought it up because typeclasses are pretty unusual from the perspective of a vanilla django app and trying to find any examples of other applications running into this resulted in nothing. For what it's worth we use 3.2.x at work with the same version of python I was running and had a test runner that used sqlite for speed and I've never seen this issue there either.

When I get time I'll see about changing my version of python to try this on develop branch and see if the issue occurs there as well. When I was running with `--verbosity=3` I could see that the issue was happening after normal migrations were applied and post-migrate steps run for all apps, which was kind of interesting: it didn't break immediately for the first user-defined app it found, but as some sort of cleanup at the end, it felt like.

**Comment by TehomCD** [comment]
As an update, this does not occur in the develop branch - it's able to create the test database and run tests there just fine. So I do have the workaround of skipping directly to develop and going to django 4.x, it seems.

**Comment by Griatch** [comment]
> makemigrations without any arguments will try to create migrations for any typeclasses that a game creates, though you can avoid this by either manually deleting the migrations or only running app-specific migrations 

Yes, we need to run app-specific `makemigrations` when adding custom tables exactly to avoid this. The Typeclass system is basically a hack on top of Django to extend the functionality of Proxy models and be able to treat them as quasi 'real' models for the purpose of searching and letting people not having to learn Django to make their own subclasses (with meta boilerplate etc). The drawback is that it fools Django migrations into thinking they should be considered. 

Interesting that Django 4.x works for you, but not 3.2.x. I've not heard any other issues with that. Alas, Evennia 0.9.5 does not run on 4.x at this point so moving to `develop` or wait for 1.0 release would be the options in that case.

We can keep this open for now, in case someone else runs into it, but I don't expect to be spending any time investigating this for master branch, so this sounds like it will not be addressed (at least not by me).

**Comment by Griatch** [comment]
Closing this; we won't accept any more changes to master branch, nor for Django 3.2.x.
