### ISSUE TITLE
[BUG - Develop] Multimatch results don't include aliases

### ISSUE THREAD

**Issue by nyweryl** [evennia/evennia#2960]
#### Describe the bug
When a multimatch occurs, the list of matches don't include aliases.

#### To Reproduce
1. Collect multiple objects with the same name or alias.
2. Use a command that uses the object.search function, like drop or examine.
3. See error:

>drop key
>You carry more than one key.
> a bronze key-1 [] (carried)
> a small key-2 [] (carried)

#### Expected behavior
The aliases of an object should be between the brackets:

>drop key
>You carry more than one key.
> a bronze key-1 [bronze, key] (carried)
> a small key-2 [small, key] (carried)

#### Develop-branch commit
Evennia version: 1.0-dev (rev 77171aee8)
OS: posix
Python: 3.9.2
Twisted: 21.7.0
Django: 4.0.7

#### Additional context
In https://www.evennia.com/docs/1.0-dev/_modules/evennia/utils/utils.html#at_search_result, an attempt is made to remove all pluralization aliases:

```
aliases = [
    alias
    for alias in aliases
    if hasattr(alias, "category") and alias.category not in ("plural_key",)
]
```

While this attempt is successful, it gets rid of *all* aliases without a category. A possible solution would be:

```
aliases = [
    alias
    for alias in aliases
    if not hasattr(alias, "category") or (hasattr(alias, "category") and alias.category not in ("plural_key",))
]
```

**Comment by Griatch** [comment]
Thanks for the issue! Should be fixed now.
