### ISSUE TITLE
[BUG - Develop] Destroy command's contents check is incorrect

### ISSUE THREAD

**Issue by nyweryl** [evennia/evennia#2971]
#### Describe the bug
The [destroy command](https://www.evennia.com/docs/1.0-dev/_modules/evennia/commands/default/building.html#CmdDestroy) gives feedback to the user whether the destroyed object had any exits and any other contents:
```
had_exits = hasattr(obj, "exits") and obj.exits
had_objs = hasattr(obj, "contents") and any(
    obj
    for obj in obj.contents
    if not (hasattr(obj, "exits") and obj not in obj.exits)
)
```

This is mildly confusing to read as both the object to be destroyed and each of its contents in the loop are referred to as `obj`. Yet this part in the loop also doesn't seem correct to me: `(hasattr(obj, "exits") and obj not in obj.exits)` If the object to be destroyed has exits and the content is not one of them, it will return True and the content erroneously won't be regarded as non-exit content.

#### To Reproduce
1. Set up an object with a content object "inside" it.
2. Destroy the object.
3. See error: the contents won't be mentioned.

>i
>You are carrying:
> a cloth pouch ([#1405](http://192.168.2.41:4001/webclient/#)) 
>
>l pouch
>You look at a cloth pouch.
>You see nothing special.
>
>It is about a quarter full. You see:
>a golden coin
>
>destroy/force #1405
>z1i0003 was destroyed.

#### Expected behavior
The feedback message `string` should include objects were moved.

#### Develop-branch commit
Evennia version: 1.0-dev (rev ee48982ea)
OS: posix
Python: 3.9.2
Twisted: 21.7.0
Django: 4.0.7

#### Additional context
I don't think it is necessary, but here is a suggestion anyway to perhaps make the situation more clear:
```
had_exits = hasattr(obj, "exits") and obj.exits
had_objs = hasattr(obj, "contents") and any(
    con
    for conin obj.contents
    if not (hasattr(obj, "exits") and con in obj.exits)
)
```

**Comment by owllex** [comment]
If you want to make the code more readable, you could probably do this:
```py
exits = getattr(obj, "exits", [])
objs = [x for x in getattr(obj, "contents", []) if x not in exits]
```
and then replace checks for had_exits and had_objs with truthy checks on the `exits` and `objs` lists.

**Comment by Griatch** [comment]
Thanks for the report. Fixed now.
