### ISSUE TITLE
[Feature Request] Support HELP source customization 

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2975]
#### Is your feature request related to a problem? Please describe.
It would be helpful to break down the code in the HELP command's `func` to enable easier extension and customization. It's fairly long as it is and if you want to change it, it right now requires lots of copy and paste.

One use case would be adding extra sources of help in addition to the existing command-help, file-help, and DB help entries. For example, articles that are sourced from other objects' docstrings (as I do for skills, spells, and other abilities that don't have independent commands).

#### Describe the solution you'd like
For the use-case above, we could factor `func` to call another function that returns all of the searchable article candidates, grouped by category, and then have another function that knows how to retrieve that kind of article. There might be other ways to factor parts of func as well to enable other customization.

#### Alternatives you've considered
My use case could be solved by doing something creative with filehelp, but it's not ideal for many reasons. The only other option is to copy and paste the help func and modify it in place, but I'd rather we have a better solution than that, given how long help's func currently is.

**Comment by Griatch** [comment]
Extensive customization has been added to the help command. Closing. If there's still something missing, let's handle that in a separate ticket.
