### ISSUE TITLE
[BUG - Develop] Module defining a global script cannot import a name from a module that references the script (via settings.py)

### ISSUE THREAD

**Issue by BigJMoney** [evennia/evennia#2983]
#### Description
If you have a module that defines a global script stored in the settings file, you cannot import a name from another module that accesses that script from the settings file.

#### To Reproduce
1. Start with new server, then 'evennia migrate'
2. Set up these files:

File1.py
```
from evennia.utils.containers import GLOBAL_SCRIPTS

TEST_SCRIPT = GLOBAL_SCRIPTS.my_test_script

class TestClass:
    pass
```

File2.py
```
from typeclasses.scripts import Script
from file1 import TestClass

class MyTestScript(Script):
    pass
```

settings.py
```
GLOBAL_SCRIPTS = {
    'my_test_script': {
        'typeclass': 'file2.MyTestScript',
        'persistent': True
    }
}
```
3. Run 'evennia start'

#### Result
The evennia launcher crashes very early with:
```
Traceback (most recent call last):
  File "D:\evdev\evennia\bin\windows\evennia_launcher.py", line 18, in <module>
    main()
  File "D:\evdev\evennia\evennia\server\evennia_launcher.py", line 2305, in main
    init_game_directory(CURRENT_DIR, check_db=True)
  File "D:\evdev\evennia\evennia\server\evennia_launcher.py", line 1793, in init_game_directory
    check_database()
  File "D:\evdev\evennia\evennia\server\evennia_launcher.py", line 1494, in check_database
    evennia._init()
  File "D:\evdev\evennia\evennia\__init__.py", line 363, in _init
    GLOBAL_SCRIPTS.start()
  File "D:\evdev\evennia\evennia\utils\containers.py", line 185, in start
    self.load_data()
  File "D:\evdev\evennia\evennia\utils\containers.py", line 208, in load_data
    self.typeclass_storage[key] = class_from_module(
  File "D:\evdev\evennia\evennia\utils\utils.py", line 1600, in class_from_module
    mod = importlib.import_module(testpath, package="evennia")
  File "C:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\evdev\Passage\file2.py", line 3, in <module>
    import file1
  File "D:\evdev\Passage\file1.py", line 3, in <module>
    TEST_SCRIPT = GLOBAL_SCRIPTS.my_test_script
  File "D:\evdev\evennia\evennia\utils\containers.py", line 56, in __getattr__
    return self.get(key)
  File "D:\evdev\evennia\evennia\utils\containers.py", line 230, in get
    return self._load_script(key) or default
  File "D:\evdev\evennia\evennia\utils\containers.py", line 137, in _load_script
    typeclass = self.typeclass_storage[key]
KeyError: 'my_test_script'
```

Process finished with exit code 1

#### Expected behavior
Evennia starts, and the imports resolve (I don't think they should be considered cyclical)

#### Workaround
Get rid of the import statement in File2, or to not access GLOBAL_SCRIPTS.my_test_script in File1. Sometimes I am successful changing the import from the form 'from file1 import TestClass' to 'import file1', but in the exact test case above, this workaround isn't working.

#### Develop-branch commit
rev 5d0fe2e38

#### Additional context
This is similar to #2334 but that bug assumes the cyclic import is actually cyclic. Also, I notice that I still get the above KeyError crash (rather than some error message from Evennia).

**Comment by BigJMoney** [comment]
Actually, this doesn't need 2 modules and can be reproduced more easily in a single file like this:
```
from typeclasses.scripts import Script
from evennia.utils.containers import GLOBAL_SCRIPTS

test_script = GLOBAL_SCRIPTS.my_test_script

class MyTestScript(Script):
    pass
```

As well as the settings.py in the bug description.

**Comment by Griatch** [comment]
@BigJMoney To be clear (in your one-file example), is `GLOBAL_SCRIPTS.my_test_script` an instance of `MyTestScript`? 

If so, this is not an Evennia problem and not anything you can expect to ever work, in any program: You are importing `GLOBAL_SCRIPTS` and try to access `GLOBAL_SCRIPTS.my_test_script` on it ... but `MyTestScript` is only defined on the lines after that import. So there is no way for `GLOBAL_SCRIPTS` to actually get to the class before its instance is loaded (whenever you import the module, the top of the module is always instantiated). In short, you are trying to access script before its definition is available. Place the `test_script = GLOBAL_SCRIPTS.my_test_script` after the class definition, and it should work.

**Comment by BigJMoney** [comment]
For the heck of it, I also tried moving the import, but that again crashes with the same KeyError
```
from typeclasses.scripts import Script

class MyTestScript(Script):
    pass

from evennia.utils.containers import GLOBAL_SCRIPTS
test_script = GLOBAL_SCRIPTS.my_test_script
```

**Comment by Griatch** [comment]
Yeah, I was too optimistic above. This can and will never work. This is what happens: 

1. The GlobalScript container (GLOBAL_SCRIPTS) initializes. It finds an entry `your.path.module.MyTestScript` and goes to load it
2. When importing `your.path.module`, the outermost scope of the module is initialized. This contains the `MyTestScript` path, but also the line `test_script = GLOBAL_SCRIPTS.my_test_script`
3. Finding the above line, the `GLOBAL_SCRIPTS` container looks for a script stored on itself named `my_test_script`. _There is none yet_ because this check was triggered while the handler was importing the script in the first place. This leaves the container in a weird state, because it knows about the script and what typeclass to load, but it hasn't actually loaded it yet when it is being requested. 

So this is a circular import that will never work. I could in principle address this by returning `None` if calling `GLOBAL_SCRIPTS.my_test_script` here, but I think that would rather cause more confusion. So instead I have now added so that we catch this case and raise a more informative error.
