### ISSUE TITLE
[BUG - Develop] EvTable is stripping color codes 

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2986]
#### Describe the bug
All color formats are being stripped from EvTable.

#### To Reproduce
Add and execute the command class provided below - the same strings are being used for both outputs, but the table has no colors.

```python
class TableTest(Command):
    key = "tabletest"
    def func(self):
        from evennia.utils.evtable import EvTable
        
        table = EvTable()
        row1 = "|cAn entire colored row|n"
        row2 = "A single |rred|n word"
        
        self.caller.msg(f"The strings:\n{row1}\n{row2}")
        self.caller.msg("\nThe table:")
        table.add_row(row1)
        table.add_row(row2)
        self.caller.msg(table)
```
![image](https://user-images.githubusercontent.com/51038201/202872309-b3c543d9-74f5-4f1e-a47b-547435b5dc68.png)

#### Develop-branch commit
c75708a32

#### Additional context
Reported by Lundex on Discord

**Comment by Griatch** [comment]
Will investigate; could be some sort of regression.

**Comment by Griatch** [comment]
Fixed; needed to update `utils.justify` to properly handle `ANSIString` inputs.
