### ISSUE TITLE
[BUG - Develop] `evennia test` running with the wrong project root

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3014]
#### Describe the bug
When running `evennia test` on your own gamedir, the parent directory is used as the project root instead of your game's folder. This results in any relative path imports involving typeclasses creating conflicting model tracebacks.

#### To Reproduce
1. Add a super basic test to a clean install, like:
```python
# file typeclasses/tests.py

from evennia.utils.test_resources import BaseEvenniaTest

from . import objects

class TestTesting(BaseEvenniaTest):
    def test_testing_stuff(self):
        self.assertTrue(True)
```
2. Run `evennia test --settings=settings .` from your game's root directory
3. Instead of passing or even running the test, it will traceback with the ultimate error of:
```
RuntimeError: Conflicting 'object' models in application 'objects': <class 'TestGame.typeclasses.objects.Object'> and <class 'typeclasses.objects.Object'>.
```

#### Expected behavior
This used to work correctly with the game's root folder being identified as the project root, the same as it is for the game's code itself.

#### Develop-branch commit
1271764100

#### Additional context
I tried this on both the new pip install and on the from-git install, on both Windows 10 and on Debian Linux, with the same results.

**Comment by Griatch** [comment]
Hm, that is curious. I can reproduce too, on a clean install, I wonder why that would be :confused:

**Comment by Griatch** [comment]
Fixed. We should not have an `__init__.py` file in the root of the `mygame` folder, it's not necessary and turns the folder into a 'package' identified by `mygame.typeclasses.objects` etc, over `typeclasses.objects`. Removing the `__init__.py` fixes this; I have also removed it from the gamedir template. The conflict only appears to pop up for the unit test case.
