### ISSUE TITLE
[BUG] Discord Integration - still creating 2 sessions every time it reconnects

### ISSUE THREAD

**Issue by ShardsDev** [evennia/evennia#3021]
#### Describe the bug
I have enabled discord integration with one channel in evennia to one channel in discord. It works well, but when it sits idle it manages to reconnect 2 sessions every time it disconnects. 

#### To Reproduce
1. follow the steps to create an evennia-discord integration
2.set up one channel in evennia to connect to one on a discord server
3. wait
```
+--------------+--------+------+------------+--------+------+----------+------------+
| Account Name | On for | Idle | Puppeting  | Room   | Cmds | Protocol | Host       |
+--------------+--------+------+------------+--------+------+----------+------------+
| DiscordBot   | 00:19  | 19m  | None       | None   | 1    | discord  | discord.gg |
| DiscordBot   | 00:02  | 2m   | None       | None   | 1    | discord  | discord.gg |
| DiscordBot   | 00:02  | 2m   | None       | None   | 1    | discord  | discord.gg |
| Zephyr       | 02:28  | 4m   | Zephyr(#3) | RP Hub | 7    | telnet   | 127.0.0.1  |
+--------------+--------+------+------------+--------+------+----------+------------+
```
```
2 unique players logged in.
--------------------------------------------------------------------------------------
|Portal| 2022-12-07 15:51:16 [..] Portal starting server ... 
|Portal| 2022-12-07 15:51:17 [..] Connecting to Discord Gateway...
|Portal| 2022-12-07 15:51:17 [..] Attempting connection to Discord...
|Portal| 2022-12-07 17:08:05 [..] Discord disconnected: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
|Portal| 2022-12-07 17:08:06 [..] Attempting connection to Discord...
|Portal| 2022-12-07 18:00:56 [..] Discord: received 'Reconnect' opcode. Reconnecting.
|Portal| 2022-12-07 18:00:56 [..] Attempting connection to Discord...
|Portal| 2022-12-07 18:00:56 [..] Discord disconnected: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
|Portal| 2022-12-07 18:00:58 [..] Attempting connection to Discord...
|Portal| 2022-12-07 18:17:25 [..] Discord: received 'Reconnect' opcode. Reconnecting.
|Portal| 2022-12-07 18:17:25 [..] Attempting connection to Discord...
|Portal| 2022-12-07 18:17:25 [..] Discord disconnected: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
|Portal| 2022-12-07 18:17:28 [..] Attempting connection to Discord...
```

#### Expected behavior
when the discord integration times out, it should disconnect and only reconnect once.

#### Environment, Evennia version, OS etc
```
Evennia version: 1.0.1 (rev fd0abb4520)
OS: posix
Python: 3.11.0rc1
Twisted: 22.10.0
Django: 4.1.3
```
#### Additional context
Is there maybe some timing issue? or did I mess something up?

**Comment by ShardsDev** [comment]
I used discord/remove to remove the channel. With the discord bot up and no channels, this issue doesn't seem to happen.

**Comment by Griatch** [comment]
Sounds like an issue in the logic, where a new bot is generated not knowing the old one is still alive. There shouldn't be multiple bots in the who list either.

**Comment by Antrare** [comment]
It's weird, I'm getting the opposite issue, discord disconnects and doesn't
reconnect until I reload the server. I'm on latest git pull on main branch

**Comment by Antrare** [comment]
Yep, ignore my previous note - I hadn't restarted the portal.  Now I'm
getting this spammed.  There is still only 1 Discord bot on the who list:
[MudInfo] [2022-12-11(04:30)]: DiscordBot disconnected (Logged in from
elsewhere. Disconnecting.)
[MudInfo] [2022-12-11(04:30)]: DiscordBot connected
[MudInfo] [2022-12-11(04:31)]: DiscordBot disconnected (Logged in from
elsewhere. Disconnecting.)
[MudInfo] [2022-12-11(04:31)]: DiscordBot connected

**Comment by InspectorCaracal** [comment]
Good news: I've identified and fixed the excess sessions issue. But before I can PR the fix, I need to add in some additional reconnection logic so that it'll reconnect properly for both intended and unintended disconnects.

If all goes well, I should have that done today. If all goes poorly, then... by this weekend at the latest, probably?
