### ISSUE TITLE
[BUG] Using a key and no desc in EvMenu results in excess blank lines.

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3027]
#### Describe the bug
When a menunode has options that have the `key` specified but no `desc`, the menu adds a number of extra blank lines after the options.

This was first identified in the "confirm name" step of the character creator contrib after the justify fix, but I've confirmed it with the following much simpler menu:

```python
def menunode_start(caller):
    text = "Starting node."
    options = {"desc": "Start", "goto": "menunode_no_descs"}
    return text, options

def menunode_no_descs(caller, raw_string, **kwargs):
    text = "A node with an option that has no desc."
    options = {"key": "Continue", "goto": "menunode_end"}
    return text, options

def menunode_end(caller, raw_string, **kwargs):
    text = "The end."
    return text, None
```

#### To Reproduce
1. Set up a menu with the nodes above.
2. On node 2, you should notice at least half a dozen blank lines after the `Continue` prompt.

#### Environment, Evennia version, OS etc
evennia 1.0.1

#### Additional context
See also #3024

**Comment by jrsteensen** [comment]
Just for other's reference, this issue can be worked around by adding descs in:
```python
        {"key": ("Yes", "y"), "desc": f"Confirm you want to be named |w{char.key}|n", "goto": "menunode_TODO"},
        {"key": ("No", "n"), "desc": "Change my name.", "goto": "cgen_enter_name"},
```

**Comment by Antrare** [comment]
Additional info from Discord:
Jumpscare — Today at 12:37 PM
I don't know if anyone said anything about this yet, but it has to do with putting color codes in options.
[12:42 PM]
If you have color codes in your options and your longest option text after color codes are processed is less than 20 characters, you'll start to get blank lines.
[12:44 PM]
If at least one option is 20 characters or longer, you get no blank lines.

**Comment by InspectorCaracal** [comment]
All of the situations I've seen this bug arise in don't include any color options, but that would be consistent with the bug being the ANSIString split issue I reported in #3110

**Comment by Griatch** [comment]
This was a miscalculation in the Evtable.add_column routine; it tricked the table into thinking it needed new rows when it was just adding empty columns to fill out the table horizontally.
