### ISSUE TITLE
[BUG] `CmdTeleport` permission checks fail for Builders

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3029]
#### Describe the bug
The teleport command itself is, to the best of my knowledge, both defined and intended as a Builder-level tool. However, the actual teleport itself is locked behind Admin privileges or a `teleport` lock access.

https://github.com/evennia/evennia/blob/981dbc0d29469b759cdc9f3e1ce1b908f864b745/evennia/commands/default/building.py#L3708

At a brief glance, this seems like it might be reasonable, but it has one very significant problem: this `teleport` permission is not added to any object, anywhere, in all of Evennia's core typeclasses. Since the default access result when no lock is found is `False`, this means that a Builder can't actually teleport anything - not even their own character - unless the object or character has explicitly had a lock added permitting it.

This causes a lot of confusion when trying to use the command as a Builder, in particular because the help string indicates that setting the lock is what you should do to _prevent_ an object from being teleported.

#### Expected behavior
It's unclear what the intended purpose of the lock check with Admin bypass would be. If it's supposed to allow you to put a lock on particular objects to prevent builders from teleporting them, a `teleport:perm(Admin)` lock on the object would do the job better than hardcoding it.

I would expect builders to be able to teleport all non-character and non-room objects by default, personally, so I think teleport locks should be added in the basetype setup methods. Something like `teleport:true()` for base objects, `teleport:perm(Admin) or id({id})` or similar for characters, `teleport:false()` for rooms.

**Comment by InspectorCaracal** [comment]
The same issue results from the `teleport_here` check immediately following - rooms should probably have `teleport_here:true()` by default.

**Comment by Griatch** [comment]
The purpose of this comes to play e.g. in the Evennia game demo, where everyone is granted builder privileges for building things, but we also want to limit teleportation of objects around in the tutorial world. This is not that common a use-case though, and I think your suggestion makes sense. 
I think the command-level bypass should really be `Developer` level though, and let the default entities get different defaults, as you suggest.
