### ISSUE TITLE
[BUG] AttributeProperties bypass at_get / at_set when using the AttributeHandler

### ISSUE THREAD

**Issue by BigJMoney** [evennia/evennia#3034]
#### Describe the bug
When using the AttributeHandler to work with AttributeProperties, their at_get and at_set hook methods will not be called. This requires a programmer to know ahead of time (knowledge they very likely may not have) that some attribute they're accessing is an AttributeProperty, and must not use the AttributeHandler.

#### To Reproduce
1. Create an AttributeProperty subclass called APChild
2. Implement something in at_get() (ex. increase default value +1)
3. Add an attribute to a game class that is an APChild object, called my_stat, with a default value
4. Create an instance of the game class
5. Access the my_stat attr directly
6. Access the my_stat attr using the AttributeHandler (.db)

RESULT: AttributeHandler returns the default value without the +1

#### Expected behavior
AttributeProperty would always run at_get when getting

#### Environment, Evennia version, OS etc
v1.0.1, Windows

**Comment by ChrisLR** [comment]
This seems to be like using the private method instead of the public property, maybe it just needs to be added to the documentation?

**Comment by Griatch** [comment]
There is no way for `AttributeHandler` to call the `AttributeProperty.at_set` and `at_get` methods; the handler has no access to the property and can't know how that a property is available. It also doesn't make sense to use the `AttributeHandler` directly if you are accessing your Attributes as properties. 
This is not a bug per se, but I can see it being confusing if not aware of how Python descriptors works. I'll expand the documentation.
