### ISSUE TITLE
[BUG] (XYZGrid contrib) Prototypes are not generated for custom MapLink classes 

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3044]
#### Describe the bug

***EDIT*** The _inconsistent_ traceback issue below is due to a typo on line 412:
https://github.com/evennia/evennia/blob/981dbc0d29469b759cdc9f3e1ce1b908f864b745/evennia/contrib/grid/xyzgrid/xymap_legend.py#L412

Correcting `self.prototype` to `prot` gives the following traceback instead:

> 2022-12-22 17:56:27 [..]     raise MapError(
> 2022-12-22 17:56:27 [..] evennia.contrib.grid.xyzgrid.utils.MapError: BridgeNode 'B' at XYZ=(19,1,riverport) The prototype {'prototype_key': 'a8e7cdcf-e998-5e60-befe-4578a1e1f31c'} for this node has no 'typeclass' key.

Digging further, I identified that my custom defined map link class isn't having a prototype generated for it, despite inheriting directly from the default class.

The class:
```python
class BridgeLink(xymap_legend.MapLink):
    symbol = "Ξ"
    display_symbol = "Ξ"
    directions = { 'e': 'w', 'w': 'e' }
```

(I attempted changing the symbol to `%` in case it didn't like it, but that made no difference.)

Inserting log lines at [line 370](https://github.com/evennia/evennia/blob/981dbc0d29469b759cdc9f3e1ce1b908f864b745/evennia/contrib/grid/xyzgrid/xymap_legend.py#L369) printing `link` and `link.prototype` reveals that my nodes have an empty dictionary, while the default link node found first has a full prototype.

```python
# timestamps removed for readability
[..] <LinkNode '|' XY=(19,1.5)>
[..] {'prototype_key': 'xyz_exit', 'typeclass': 'evennia.contrib.grid.xyzgrid.xyzroom.XYZExit', 'prototype_tags': ['xyzexit', 'module'], 'prototype_locks': 'spawn:all();edit:all()', 'prototype_desc': '', 'attrs': [('desc', 'An exit.', None, '')], 'tags': []}
[..] <LinkNode 'Ξ' XY=(19.5,1)>
[..] {}
[..] <LinkNode 'Ξ' XY=(18.5,1)>
[..] {}
```

***Original issue***

I have my prototypes set up for the xyzcontrib according to the examples, e.g. this property on a node class:
```python
    prototype = {
            "prototype_parent": "xyz_room",
            "key": "A bridge",
            "desc": "A bridge over the river."
        }
```
However, when the game goes to actually create the node, it generates this traceback:
> 2022-12-22 16:02:06 [..]     raise MapError(
> 2022-12-22 16:02:06 [..] evennia.contrib.grid.xyzgrid.utils.MapError: BridgeNode 'B' at XYZ=(19,1,riverport) The prototype {'prototype_key': 'prototype-15a452b', 'typeclass': 'evennia.contrib.grid.xyzgrid.xyzroom.XYZRoom', 'prototype_tags': [], 'key': 'A bridge', 'attrs': [('desc', 'A bridge over the river.', None, '')], 'prototype_locks': 'spawn:all();edit:all()', 'prototype_desc': '', 'tags': []} for this node has no 'typeclass' key.

The typeclass key is clearly there, and from the relevant code it's not clear why it would raise a false negative.
https://github.com/evennia/evennia/blob/981dbc0d29469b759cdc9f3e1ce1b908f864b745/evennia/contrib/grid/xyzgrid/xymap_legend.py#L323-L327

#### Environment, Evennia version, OS etc
evennia 1.0.1, Windows 10

**Comment by InspectorCaracal** [comment]
An addendum: I explicitly added a `typeclass` key to my prototype property in an attempt to work around this error and I still get the same traceback.

e.g.
```python
    prototype = {
            "prototype_parent": "xyz_room",
            'typeclass': 'evennia.contrib.grid.xyzgrid.xyzroom.XYZRoom',
            "key": "A bridge",
            "desc": "A bridge over the river."
        }
```

**Comment by Antrare** [comment]
I believe your issue is more likely related to line 409 - it's the same error message and is why you're seeing a 'false positive'.  Suggest you fix this error message to see what's really going on.
                typeclass = prot.get("typeclass")
                if typeclass is None:
                    raise MapError(
                        f"The prototype {self.prototype} for this node has no 'typeclass' key.",
                        self,
                    )

**Comment by InspectorCaracal** [comment]
@Antrare That was definitely the cause of the inconsistent errors - I changed it to `prot` instead of `self.prototype` in the error and there's nothing there except a key.

I poked around a bit more and discovered that the underlying problem is my link node classes aren't being given prototypes, so I'm going to update the issue to reflect this.

**Comment by InspectorCaracal** [comment]
Explicitly assigning a prototype property to my custom link class (even just `{ 'prototype_parent': 'xyz_exit' }`) successfully avoids this traceback, but I think it's expected that not assigning an explicit prototype in your link class should fall back to the default.

**Comment by Griatch** [comment]
The `MapLink` parent doesn't define a prototype, and it shouldn't have one by default, since this is also the parent of links that should _not_ be spawned (such as inter-map teleports). 

 You'll find that all links actually used on the map by default (such as `NSMapLink`) are all inheriting from `MapLink` _and makes sure to add their own prototype_. So you need to do the same. 

I have fixed the inconsistent traceback (thanks!) and added to the `MapLink` docstring to make it clearer that this will not on its own spawn anything.

**Comment by InspectorCaracal** [comment]
Ahhh, okay! That makes perfect sense. Thanks for the information and docs update. 👍
