### ISSUE TITLE
[Documentation] Beginner Tutorial - Small syntax inconsistency spotted

### ISSUE THREAD

**Issue by BernardoFPereira** [evennia/evennia#3047]
#### Existing page / new

https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Searching-Things.html
#### Documentation issue

Syntax inconsistency with current version. Example seems to be outdated, if not wrong.
`volcano = self.caller.search("Vesuvio", global=True)`
#### Suggested change

`volcano = self.caller.search("Vesuvio", global_search=True)`

**Comment by Griatch** [comment]
Yep, this was an outright typo in the tutorial. Fixed.
