### ISSUE TITLE
Documentation in Sittables as part of Beginner Tutorial

### ISSUE THREAD

**Issue by ironcross32** [evennia/evennia#3048]
#### Existing page / new
[https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html]

#### Documentation issue
```python
        self.db.sitting = sitter
        sitter.db.is_sitting = self.obj
        sitter.msg(f"You sit on {self.key}")
```

#### Suggested change
`sitter.db.is_sitting = self.obj` should just be self and not self.obj

**Comment by Griatch** [comment]
Resolved in unlinked https://github.com/evennia/evennia/pull/3065 and https://github.com/evennia/evennia/pull/3063
