### ISSUE TITLE
[BUG] iter_to_str() misprint with two objects.

### ISSUE THREAD

**Issue by BernardoFPereira** [evennia/evennia#3050]
#### Describe the bug

`iter_to_str` inside `get_display_*`'s behaviour seems faulty.

With it's default separators (`sep","` , `endsep=", and"`), and 2 objects in the iterable, the in-game game return is `" and "` separating the names `(obj1 and obj2)`. While more than 2, returns `", and"`; `(obj1, obj2, and obj3)`.

Changing the default  `sep` to something like `sep="-"`, makes the return `X, and Y` as opposed to `X and Y` when there's 2 objects.

Apparenty, this happens whenever `sep` and `endsep` are the same (or `endsep` starts with the same character).
Got the same behavior with `[sep=',', endsep=',']`, `[sep='-', endsep='-']`, `[sep=';', endsep=';']`.
In these cases output with 2 objects is `X Y` as opposed to `X, Y`, for example.

#### To Reproduce
1. Overload any `get_display_*` function in an object.
2. Set it's `*_names` value's `iter_to_str` separator parameters as the same character. (e.g.: `sep","` , `endsep=","`)
3. Run the game and `look` in a place where there's two of anything (`Exits`, `Characters` or `Things`)
4. Check `look` output for misprint

#### Expected behavior

The presence of 2 objects in the iterable being used by `iter_to_str` should output the proper `endsep` string.
With the same separators parameters, output with 2 objects should be `X, Y`, not `X Y`.

#### Environment, Evennia version, OS etc

    Evennia 1.0.2
    OS: nt

**Comment by InspectorCaracal** [comment]
Ohh, this is with only *two* objects. Removing the default leading comma in a list of two items is not a bug, it's intended design. The default behavior of `iter_to_str` is to combine a list of items into a single correctly-punctuated natural list, using the Oxford comma syntax. e.g for lists of 1, 2 and 3 items with the default , you should expect:

- "1"
- "1 and 2"
- "1, 2, and 3"

That said, specifying endsep="," _should_ result in a list of "1, 2" rather than "1 2", so that behavior does need to be corrected. I'll take point on it this week once I have an opportunity, since I know what the logic for that is and should be able to correct it.

**Comment by BernardoFPereira** [comment]
I imagined it was intended, as `1 and 2` does make more sense than `1, and 2`. What started puzzling me was specifying `sep`(to something other than `","`) and leaving `endsep` defaulted; That makes a list of two objects `1, and 2`, that boggled me for a while. Started thinking this was intended behavior, heh.

Investigating further, the issue seems to be in `iter_to_str()` definition in `utils.utils`.
More specifically: 
```
  if endsep:
      if endsep.startswith(sep):
          # oxford comma alternative
          endsep = endsep[1:] if len_iter < 3 else endsep
          [...]
```
I'm currently investigating this a bit further, will update this comment in the very-near future.

**Comment by BernardoFPereira** [comment]
Awesome! It took your commit to see what I did wrong.
I tried a bunch of similar, if not the same, things but `endsep = endsep[1:] if len_iter < 3 else endsep` became `endsep = sep[1:] if len_iter < 3 else endsep` at some point and I didn't look back at it 🤣 
Of course my output was messy. All good now.
Very much appreciated!
