### ISSUE TITLE
[Documentation] Missing warning about SuperUser

### ISSUE THREAD

**Issue by 0bviouSquirre1** [evennia/evennia#3058]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Python-basic-introduction.html#finding-others-to-send-to

#### Documentation issue
in section 3.2.2 there's a sentence talking about the superuser: 

There is also the superuser, the “owner” of the game you create when you first set up your database. This user goes outside the regular hierarchy and should usually only.

#### Suggested change
Include whatever it is that the super user should usually only

**Comment by Griatch** [comment]
It looks like the link is wrong. The weird superuser string is actually in Part2 of the beginner tutorial: in _Planning The Tutorial Game_.
