### ISSUE TITLE
[BUG] contrib: building menu does not catch its keys

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3069]
#### Describe the bug
Game parses building menu keys as directions.

#### To Reproduce
```
> @edit me
Building menu: oreolek

 [K]ey: oreolek
 [D]escription: 
 [Q]uit the menu
> d
[character goes down]
```

#### Expected behavior
Edit the description

#### Environment, Evennia version, OS etc
Evennia 1.0.2, python 3.10.6

**Comment by Griatch** [comment]
This should be simple enough to address - just by making the menu use `Replace` rather than `Union` command merge-type.
