### ISSUE TITLE
[BUG] contrib: rpmodule breaks saying URLs

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3070]
#### Describe the bug
After installing rpmodule, it is not possible to say something containing URLs in chat because it tries to parse the link, fails and discards the input. (Channels still work.)

#### To Reproduce
```
say https://wjen.dd/dsdw
No match for /dsdw.
No match for /wjen.
```

#### Expected behavior
Saying the phrase without discarding it.

#### Environment, Evennia version, OS etc
Evennia 1.0.2, python 3.10.6

**Comment by Griatch** [comment]
Not sure this is something you want to be able to do honestly. When would a character need to 'speak' an URL?

**Comment by SylvKT** [comment]
> Not sure this is something you want to be able to do honestly. When would a character need to 'speak' an URL?

It's kind of unexpected that it would try to "parse" the URL in the first place. What's wrong with saying URLs in in-character chat?

**Comment by Griatch** [comment]
Because an URL is something OOC? Anyway, the parsing happens because it detects the `/sdesc` pattern in the the url. I suppose one could pre-parse for http/s prefixes to identify an url.

**Comment by kenneaal** [comment]
This is a possible patch to the problem, using a negative lookbehind to detect HTTP and HTTPS links.

line 200+ in rpsystem.py:
```

# Guard against URLs if the prefix is left as /
_RE_PREFIX = re.compile(rf"(^?<!(http|https):){_PREFIX}", re.UNICODE) if _PREFIX == "/" else re.compile(
    rf"{_PREFIX}", re.UNICODE)
```
