### ISSUE TITLE
[BUG] contrib: rpmodule inserts /Me in every phrase

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3071]
#### Describe the bug
rpmodule's `pre_say` hook mangles the chat

#### To Reproduce
```
> say hi
oreolek says, "/Me says, "hi""
```
#### Expected behavior
saying "hi"

#### Environment, Evennia version, OS etc
Evennia 1.0.2, python 3.10.6

**Comment by InspectorCaracal** [comment]
This occurs if you don't add the rpsystem command set to your default character command set properly. The rpsystem CmdSay functions differently from the core version and adds the prefix in the hook, as you noticed, while the core CmdSay adds it in the command.

**Comment by fluffy-critter** [comment]
Is there any documentation that would help evennia newbies to fix this problem?

**Comment by InspectorCaracal** [comment]
> Is there any documentation that would help evennia newbies to fix this problem?

There is! The documentation specifically for using the contrib in your game is here <https://www.evennia.com/docs/latest/api/evennia.contrib.rpg.rpsystem.rpsystem.html>, which includes specific instructions on how to install the commands along with the rest of the necessary setup. The website in general has a lot of helpful documentation about the game and how it works.

**Comment by Oreolek** [comment]
> You will then need to reload the server and potentially force-reload your objects, if you originally created them without this.

So what you're saying we need to reload every player's character in the game? Is there a command for this or that's something to do manually?

**Comment by Griatch** [comment]
You can just add the command set to the default character cmdset and reload the server. How to do this is described in [the README for the contrib](https://www.evennia.com/docs/latest/Contribs/Contrib-RPSystem.html#installation). No need to update characters individually.

**Comment by Oreolek** [comment]
but it is there already: https://git.disroot.org/vantablack/vantaMOO/src/branch/vanta/commands/default_cmdsets.py#L63

**Comment by InspectorCaracal** [comment]
> but it is there already: https://git.disroot.org/vantablack/vantaMOO/src/branch/vanta/commands/default_cmdsets.py#L63

I believe your import needs to be:
`from evennia.contrib.rpg.rpsystem.rpsystem import RPSystemCmdSet`

If you need help getting things working or set up with evennia, btw, the Discord has a support channel and there's usually at least one person around who can help troubleshoot or walk you through things.
