### ISSUE TITLE
[BUG] No way to remove sdesc

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3073]
#### Describe the bug
Once you set an `sdesc`, it is not possible to erase it.

#### To Reproduce
1. `sdesc thisisme`
2. `sdesc`
`Usage: sdesc <sdesc-text>`

#### Expected behavior
Actually removing sdesc if the text is empty

#### Environment, Evennia version, OS etc
Evennia 1.0.2, python 3.10.6

**Comment by InspectorCaracal** [comment]
This would be a useful addition. I'd suggest we add a /clear switch for deleting it and make no arguments return the current set sdesc.

**Comment by Griatch** [comment]
Agreed, this would be useful functionality to add.
