### ISSUE TITLE
[Feature Request] Website needs a Change Password form

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3076]
#### Is your feature request related to a problem? Please describe.
Currently, Evennia comes with a fairly nice, if basic, website attached to the game, which includes the ability to create accounts in a non-plaintext environment.

However, the only way to _change_ your password is to use the in-game "password" command.

#### Describe the solution you'd like
I would like the addition of a very basic user-facing Account Management page with a password change form. It could be extended by site owners later if other account data is added, but at minimum, if there is a way to create the account from the website, we need a password update on it as well.

**Comment by owllex** [comment]
Would be great to also have a forgot password option (of the user has an email address to send a reset code to).

**Comment by InspectorCaracal** [comment]
> Would be great to also have a forgot password option (of the user has an email address to send a reset code to).

THIS one, it has! Although I believe it requires configuring your server to be able to send email.

**Comment by resoluteCoder** [comment]
Hello I'm looking to starting contributing to features or good first issues so I'm going through them now :smile:

I've logged into the evennia UI and I see a change password form. @InspectorCaracal Is this still an active issue?

Here's the form:

![image](https://github.com/evennia/evennia/assets/50929884/2fa84a6b-ed68-4d03-b661-5b264bcdae99)

**Comment by InspectorCaracal** [comment]
@resoluteCoder Looks like it isn't!
