### ISSUE TITLE
[Feature Request] Adding attributes to default channels in settings

### ISSUE THREAD

**Issue by nyweryl** [evennia/evennia#3078]
#### Is your feature request related to a problem? Please describe.
I cannot add attributes to channels defined in the DEFAULT_CHANNELS setting.

#### Describe the solution you'd like
I'd like to add attributes to channels defined in the DEFAULT_CHANNELS setting.

For example:
```
DEFAULT_CHANNELS = [
    # Public channel
    {
        "key": "Public",
        "aliases": ("pub", "p"),
        "desc": "Public discussion",
        "locks": "control:perm(Admin);listen:all();send:all()",
        "attrs": "[("is_ooc", True), ("creator", "Lyrewyn")]
    }
]
```

Or even an implementation where non-standard arguments are interpreted as attributes under the hood:
```
DEFAULT_CHANNELS = [
    # Public channel
    {
        "key": "Public",
        "aliases": ("pub", "p"),
        "desc": "Public discussion",
        "locks": "control:perm(Admin);listen:all();send:all()",
        "is_ooc": True,
        "creator": "Lyrewyn
    }
]
```

**Comment by Griatch** [comment]
This is due to the `create_channel` manager function not supporting `attrs` as a keyword. We should add that, but in the interrim, `tags` does work.
