### ISSUE TITLE
[Documentation] Wrong instructions for adding extra dependencies

### ISSUE THREAD

**Issue by shogidude** [evennia/evennia#3080]
#### Existing page / new
https://www.evennia.com/docs/latest/Setup/Installation-Upgrade.html
and
https://www.evennia.com/docs/latest/Contribs/Contrib-XYZGrid.html?highlight=xyzgrid

#### Documentation issue
It appears that the instructions have the wrong command for installing extras. In the first link above the command shows, 

pip install -e --upgrade .[extra]

but should be

pip install --upgrade -e .[extra]

In the second link, two places use 

pip install -r requirements_extra.txt

Those should also be 

pip install --upgrade -e .[extra]

#### Suggested change
Those pages (and maybe others, too) should be updated to show

pip install --upgrade -e .[extra]

**Comment by Griatch** [comment]
Should be fixed now :)
