### ISSUE TITLE
[BUG] webclient - text2html is overzealous in interpreting text as links

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3081]
#### Describe the bug
If you message an MXP link with link content ending in at least 3 'w's or 'http' alone, the webclient outputs junk.

#### To Reproduce
1. Open the browser webclient with MXP on
2. `py self.msg("TEST HERE: |lchelp drawwww|ltdrawwww|le")`
3. See `TEST HERE: www";],{});return false;">drawwww>`

#### Expected behavior
Output of the above command should just be the link `drawwww` to `help drawwww`.
While it's unlikely that a real game in production is going to send such text to the user anyway (I found it because I wanted to test different 'draw' commands in parallel and that was the, uh, 'naming schema' I settled on), it seems wrong that it should even potentially happen. I think the cause is regex in text2html.py, probably re_url.

At the very least, I think:
Interpreting www as a url should require:
A period immediately following the www
A second period any point later in the same line

Interpreting http/https as a url should require:
A colon immediately following the http/https match

#### Environment, Evennia version, OS etc
Evennia version: 1.1.0 (rev 74d470a4f6)
Webclient

#### Additional context
<img width="417" alt="image" src="https://user-images.githubusercontent.com/9540334/212312035-5771b1c3-2642-4be4-bfcd-a4c6c8fc44ef.png">
<img width="389" alt="image" src="https://user-images.githubusercontent.com/9540334/212312084-7e0c5aa5-7a18-4521-8fc7-d007c9e9ba29.png">

Also, I think this is the same bug - while link *content* ending in www results in the above, link *text* alone ending in www seems to break in the following way, where only the non-'www' part is linkified:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/9540334/212317710-f20c1a3a-5e3a-4d62-8996-50ab74b0cf62.png">

**Comment by InspectorCaracal** [comment]
I can't replicate this.

In a fresh game using 1.1.0, when I enter `py self.msg("TEST HERE: |lchelp drawwww|ltdrawwww|le")` it strips the MXP from it entirely and no URL parsing happens.

In the same game, I added one command to print the test strings, and it correctly prints the MXP link and no URL parsing happens.

Command class:
```py
class CmdTestCmd(Command):
 key = "testing"

    def func(self):
        self.caller.msg("TEST ONE: |lchelp drawwww|ltdrawwww|le")
        self.caller.msg("TEST TWO: |lchelp http|lthttp|le")
        self.caller.msg("TEST THREE: |lcwave|ltwowwww|le")
```

output in the webclient:
![image](https://user-images.githubusercontent.com/51038201/212381541-a20dc2da-c086-4df3-b3b6-f53dde04cb94.png)

My system:
evennia 1.1.0
Windows 10
Python 3.10.2
up-to-date Firefox

**Comment by aMiss-aWry** [comment]
So it's possible that while testing for another bug with MXP links in tables I copy-pasted an older version of that file in... and maybe forgot to undo that. I also can't replicate it after replacing it with the newest version. Oop
