### ISSUE TITLE
_keyaliases ordering in command.py causing issues with wrong key/alias matching commands

### ISSUE THREAD

**Issue by shogidude** [evennia/evennia#3090]
#### Describe the bug
Creation of set of _keyaliases from _matchset in command.py affecting aliases with spaces.

For my example, I had one "smile" command with the aliases of "smile at", "grin", and "grin at". In the command.py's _optimize method. "matches" list is created from the aliases and the key. Then the _keyaliases tuple is created for use in the cmdparser.py's build_matches method.

The following are from the logs I created

2023-01-20 11:39:47 [..] list of matches['smile', 'smile at', 'grin', 'grin at']
2023-01-20 11:39:47 [..] _keyaliases = ('smile at', 'grin', 'grin at', 'smile')

When 'smile at' appears before 'smile' and 'grin at' appears before 'grin' in the _keyaliases, then everything works fine. However, when the non-spaced version of the command appears first, the 'at' is treated as an argument to the command instead of part of the command. The ordering of _keyaliases is different every time the server is reloaded.

#### To Reproduce
1. Create a command with aliases that have spaces for some versions
2. Restart server and try to use the command (This may take multiple restarts, because ordering seems random.)
3. Depending on the order of _keyaliases in command.py, the spaced versions of the aliases may or may not be matched

#### Expected behavior
From the example above, the command "smile at me" should match to the alias "smile at" rather than "smile".

#### Environment, Evennia version, OS etc
    Evennia 1.1.0 (rev 2241756455)
    OS: nt
    Python: 3.11.1
    Twisted: 22.10.0
    Django: 4.1.4

#### Additional context
n/a

**Comment by Griatch** [comment]
Yeah, that looks like a bug in the parser indeed. The matching should happen longest-to-shortest, so `smile at` _should_ always match before `smile`. Just to check, I assume you haven't modified the core parser?

**Comment by InspectorCaracal** [comment]
Just for completeness: based on a report in #getting-help in the discord, this isn't limited to aliases with spaces. A command with the key "emote" and an alias "em" erroneously identified the key for key/arg parsing as "em" instead of "emote":
![image](https://user-images.githubusercontent.com/51038201/214911594-73e39134-8a64-47f7-83aa-47c5eb8c3fea.png)
