### ISSUE TITLE
[BUG] cpattr does not work with attribute categories

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3093]
#### To Reproduce

> ```
> @create/drop box
> set box/size:at = "big"
> ```
> Created attribute box/size [category:at] = big
> ```
> cpattr box/size=box/sizes
> ```
> box doesn't have an attribute size.
> ```
> cpattr box/size:at=box/sizes
> ```
> box doesn't have an attribute size.
> ```
> cpattr box/size[at]=box/sizes
> ```
> box doesn't have an attribute size[at].

**Comment by InspectorCaracal** [comment]
Could you share the error you receive, as well?

**Comment by Oreolek** [comment]
Sorry, I updated the report with full transcript.

**Comment by InspectorCaracal** [comment]
Confirmed, `cpattr` only supports attributes without categories. I think this is an oversight.

https://github.com/evennia/evennia/blob/981dbc0d29469b759cdc9f3e1ce1b908f864b745/evennia/commands/default/building.py#L414-L422

**Comment by Griatch** [comment]
I think `cpattr` was simply made before Attributes could have categories :stuck_out_tongue:
