### ISSUE TITLE
[BUG] Multiple channels with the same name, differed only by case, can exist - and prove difficult to extinguish.

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3106]
#### Describe the bug
I (accidentally) created a duplicate channel with a different case as its key (ooc vs OOC) through the server/settings.py. Deleting proved difficult.

#### To Reproduce
1. Create a channel in the game through the usual default fashion, say `channel/create OOC`.
2. Add the below DEFAULT_CHANNELS dict to your settings.py.
3. Restart your game so the updated settings take effect. 
5. Type `channel/delete ooc`
5. Try, in a spontaneous fit of hope, `channel/delete OOC`
6. See error
```
DEFAULT_CHANNELS = [
    {
        "key": "ooc",
        "desc": "Public OOC discussion",
        "locks": "control:perm(Admin);listen:all();send:all()",
        "typeclass": BASE_CHANNEL_TYPECLASS,
    }
]
```
#### Expected behavior
Either channels should be case insensitive and it should be impossible to create a channel of the same name but a different case, or channels should be case sensitive and when passed in as arguments to the channel command the matching-case channel should be returned.

I think the former makes more sense as that's already how it works with the in-game command (you can't `chan/create ooc` and then `chan/create OOC`. The server setting just bypasses it.

#### Environment, Evennia version, OS etc
Evennia version: 1.0-dev (rev 96e486de80)

#### Additional context
Honestly I don't think this is the first time this has happened to me. I think like the last time, I'll just manually delete it through py commands. But I can't be the only person this ever happens to.

**Comment by InspectorCaracal** [comment]
I'm not 100% on the django query subscripts but I think the fix would just be changing this line to `db_key__iexact`
https://github.com/evennia/evennia/blob/0a4e17d06d6c1293f27ddd68f8b4c39ef49a5b25/evennia/server/server.py#L408

**Comment by aMiss-aWry** [comment]
Perfect, thanks! I'll try it out and add a test.
