### ISSUE TITLE
[BUG] Running tests can have side effects on non-test DB

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#3117]
#### Describe the bug
The Evennia test runner (evennia/server/tests/testrunner.py) calls `evennia._init()`, which loads up needed models, but also starts running global scripts on the local database. This means those scripts have a chance to modify the real database before tests start. This could have unexpected side effects, especially if evennia is also running on that DB in another process.

#### To Reproduce
1. Create a local mygame.
2. Add a global script.
3. Run a test.
4. Observe that script was loaded before tests begin.

#### Expected behavior
Global scripts should not start on the regular mygame database when running tests.

I think this could be done simply by adding a `start_global_scripts=True` param to `evennia._init()` and modifying the test runner to pass False.

#### Environment, Evennia version, OS etc
Evennia 1.1.1 (WSL)

**Comment by aMiss-aWry** [comment]
This was fixed with Volund's change here: https://github.com/evennia/evennia/commit/021f5779bf984e082a736bf5851beaaec59a005c

So global script handling has moved to server start instead of `evennia._init()`
