### ISSUE TITLE
[Documentation] Web tutorials - use /dev/ links to django documentation instead of versions?

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3126]
#### Existing page / new
Many, but an example: https://www.evennia.com/docs/latest/Howtos/Web-Help-System-Tutorial.html

#### Documentation issue
The link referencing the '[the Django tutorial](https://docs.djangoproject.com/en/1.9/intro/tutorial01/).' is broken, probably because it's for Django 1.9.
(https://docs.djangoproject.com/en/1.9/intro/tutorial01/)
I believe we want https://docs.djangoproject.com/en/4.1/intro/tutorial01/

#### Suggested change
After searching it's clear that the docs are littered with django links pointing to different versions - some 2.2, some as old as 1.7. Just do a search for docs.djangoproject.com and you'll find them. Constantly manually updating those as we move along seems laborious. Perhaps we want to move to using docs.djangoproject.com/en/dev links? See also: https://stackoverflow.com/questions/73994070/is-there-any-way-to-bookmark-a-django-current-documentation-page-without-vers

It looks like 'dev' is their version of 'latest' - that way we can replace the version number in links with 'dev': https://docs.djangoproject.com/en/dev/intro/tutorial01/

Alternatively, maybe we want to generate the links and hand-update the version of documentation to point at somewhere. Either way, better than roaming through to manually update.

**Comment by Griatch** [comment]
Good point; I can update one of the custom preparser scripts I run when generating docs to also replace the django docs to point to the current recommended version (dev tends to be ahead of what we support).

**Comment by Griatch** [comment]
I added a django-doc version updater to the documentation preprocessor. It will now be easy to update all django docs to the latest version tested with Evennia. All django links were updated to 4.1 of the docs. 

Some of the links could still be dead, because of old versions not having exactly the same path in the new version. Those needs to be reported as separate bugs in that case.

**Comment by aMiss-aWry** [comment]
I think the regex could be updated to allow more specific links too - but my regex is lacking.

ex. webclient README.md
```
the [Django docs on Views](https://docs.djangoproject.com/en/3.2/topics/http/views/)
```
awsstorage README.md
```
[django docs](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-STATICFILES_STORAGE)
```

web/admin/README.md
```
[Django admin site documentation](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/).
```

**Comment by Griatch** [comment]
Ah, I don't modify the README's at all, only the links in documentation. In code README's we probably still need to make manual changes.

**Comment by Griatch** [comment]
Manually updated the links in README's as well.
