### ISSUE TITLE
[BUG] (ExtendedRoom not properly utilizing DefaultRoom appearance_template)

### ISSUE THREAD

**Issue by jakeleviathan** [evennia/evennia#3134]
![image_2023-03-07_042227786](https://user-images.githubusercontent.com/81382567/223378990-62e34508-630b-4196-9592-6eade626e53c.png)

**Comment by aMiss-aWry** [comment]
Issue resolved on discord but it's worth adding a line about appearance_template, which was new to me too! (probably in this mysterious place: https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Rooms.html)

**Comment by Griatch** [comment]
I expanded the `Objects` documentation since this is functionality common to all objects, not just rooms.
