### ISSUE TITLE
[Documentation] Old imports in wilderness contrib

### ISSUE THREAD

**Issue by harleyndavis** [evennia/evennia#3144]
#### Existing page / new
https://www.evennia.com/docs/latest/Contribs/Contrib-Wilderness.html

#### Documentation issue
Within the example code for pyramid.py, there is a line "room.ndb.desc = desc" this doesn't actually set the description. There isn't an area or anything the description is, "You see nothing special." This is line 95, in wilderness.py.

After the example, pyramid.py file, there is some "py" commands to create the wilderness and then teleport to it. The import on the enter_wilderness line is  "from evennia.contrib import", which doesn't work. This is on line 102 in wilderness.py.

There is no mention of how the exits always exist on a room, and that they are just hidden via locks. 

#### Suggested change
After speaking with Inspector Caracal on discord, he says the descriptions are being pulled from "room.ndb.active_desc", so the docs should be updated to include that. Confirmed in testing room.ndb.active_desc does set the room description.

The import on the enter_wilderness line should be "from evennia.contrib.grid import"

A blurb that exits are always present on each room by default and are hidden via locks, might help prevent someone from having issues with superuser. This detail isn't readily apparent without looking at code, and code gets run that doesn't seem like it should, based on the example and documentation.

README.md for the contrib has the same issues. Unsure if it's updated automatically, but small formatting differences between the comment in wilderness.py and the README.md makes me think it isn't.

**Comment by Griatch** [comment]
Thanks for the issue! The html file is build dynamically from the README.md file. The py file's readme is separate for when reading the API. I updated the docs now as per your suggestions. :)
