### ISSUE TITLE
[Feature Request] Ability to generate a new `secret_settings.py`

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3146]
#### Is your feature request related to a problem? Please describe.
When managing an evennia game with git, you're most likely to deploy the game on your production server by cloning your game repository directly to the production server. However, due to the fact that `server/conf/secret_settings.py` is (correctly!) ignored by git, this means the production server isn't built with the file at all.

Since a new game is built with the file containing a session key for django, it should be possible to generate the file for a git-repo-sourced game without having to do `evennia --init othergame` and moving the freshly generated file from there.

#### Describe the solution you'd like
Something like the auto-creation of the admin character and limbo on first start would be the easiest for the end-user, I think, but even an extra launcher command like `evennia makesecrets` would be great.

**Comment by Griatch** [comment]
Sounds like a `makesecrets` command would be a good way to support this case.

**Comment by Antrare** [comment]
I've taken a look at this to see if I could add this, however, I believe that `evennia --initmissing` will do this for you already?

**Comment by InspectorCaracal** [comment]
@Antrare Oh, good find! I gave it a test run and it does - *without* re-adding any of the directories I don't use any more (e.g. `typeclasses/`).

**Comment by Griatch** [comment]
Lol, good find indeed. I think I even wrote this functionality ... and had forgotten all about it. ~_-
