### ISSUE TITLE
[Documentation] Home Page Issues

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#3163]
#### Existing page / new
The home page: https://www.evennia.com/docs/#
The true home page: https://www.evennia.com/docs/latest/index.html

#### Documentation issue
The url `https://www.evennia.com/docs` defaults to the first link, which yields a webpage with broken elements: 
<img width="194" alt="image" src="https://user-images.githubusercontent.com/73198594/230823550-4908c3bc-75cd-40df-86de-0282624d4f14.png">

The true "home" webpage, in my opinion, should be the second link, which yields the proper formatting: 
<img width="437" alt="image" src="https://user-images.githubusercontent.com/73198594/230823597-6ca69b94-71a8-45f8-9111-b3b699ac2a11.png">

#### Suggested Solution
Simple redirect from /docs to /docs/latest/index.html

**Comment by jaborsh** [comment]
Similarly, but possibly out of our control, top Google results link to .9.5 instead of 1.0.

**Comment by jaborsh** [comment]
Lastly, several links yield 401 errors or incorrect displays. They are these five: 
<img width="209" alt="image" src="https://user-images.githubusercontent.com/73198594/230823915-86525536-5d27-4cd0-8d11-942d22e981bd.png">

Index, modules, and next yield 401. Evennia 1.0 and Evennia Documentation default to the initial, ugly screenshot. When clicking the urls (from the broken/ugly site), they do not contain `/docs/latest/*` only `/docs/*`.

**Comment by Griatch** [comment]
Yes, the top level index is not getting the correct css since all references needs the version (or latest). We don't link to the root page anywhere, but it's indeed better to add a redirect to avoid ending up on the non-functioning page. Did so now.
