### ISSUE TITLE
[Documentation] Include reference to webapp/apps.py in web tutorial, fix broken link?

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3175]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Web-Character-View-Tutorial.html

#### Documentation issue
At the top of the page is: "Before doing this tutorial you will probably want to read the intro in [Basic Web tutorial](Web- Tutorial)."
This is a broken link and I'm not sure what the basic web tutorial is anyway; I can't find such a tutorial in [the howtos overview](https://www.evennia.com/docs/latest/Howtos/Howtos-Overview.html) - perhaps it's meant to link to ['Changing the Game Website'](https://www.evennia.com/docs/latest/Howtos/Web-Changing-Webpage.html)?

If we are moving the created webapp into web/, we need to include a reference to apps.py, as the app has to be renamed:
```python
from django.apps import AppConfig

class CharacterConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'web.characters'  # Must be updated from the generated 'characters' to 'web.characters' if moved to web/
```
Otherwise, the developer will see a `django.core.exceptions.ImproperlyConfigured: Cannot import 'characters'. Check that 'web.characters.apps.CharacterConfig.name' is correct.`

#### Suggested change
Either update the documentation accordingly with the qualifier 'you will have to edit the apps.py name field when you move the created webapp' *or* have the `startapp` command create the app in the `web/` folder to begin with (and name it correctly). I sort of lean towards the latter, as it doesn't seem like there's any reason to create the web app in the base game folder besides for "a user could delete the web folder and not want it to exist". 

Ran into this hiccup last September, was reminded about it by @jaborsh discovering it today.

**Comment by InspectorCaracal** [comment]
There's a few other pages that follow the same process of `startapp appname` -> `move appname to web/appname` that should be updated along with this, which I found when looking into the issue earlier:

- [Web Character Generation](https://www.evennia.com/docs/latest/Howtos/Web-Character-Generation.html)
- [Help System Tutorial](https://www.evennia.com/docs/latest/Howtos/Web-Help-System-Tutorial.html)
- [New Models](https://www.evennia.com/docs/latest/Concepts/Models.html)

**Comment by aMiss-aWry** [comment]
This might be a different issue related to markdown files getting auto-formatted, but in https://www.evennia.com/docs/latest/Setup/Online-Setup.html?#lets-encrypt

There's this broken link:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/9540334/236448532-9483feeb-d020-4989-940b-d42ab1f606d5.png">

I think there's a few more scattered through the docs where (presumably) a formatter decided to split a line by hyphenation.
