### ISSUE TITLE
[BUG] XYZgrid links not updating with new attached nodes

### ISSUE THREAD

**Issue by shogidude** [evennia/evennia#3176]
#### Describe the bug
NSMapLinks in XYZgrid  are holding onto their old northern when changed from #(BasicMapNode) to T (MapTransitionNode) or from T to #. Spawn and reload (or spawn, stop, and start) are not changing the node at that location.

#### To Reproduce
1. Create an XYZgrid map (add, spawn, reload)
2. Change on of the terminal northern # nodes to a T
3. Respawn and reload map
4. The map will not have changed from the player perspective, even if it is correct when listed

#### Expected behavior
Nodes should allow changes to take affect when moving from T to # or # to T and respawning

#### Environment, Evennia version, OS etc
    Evennia 1.3.0 (rev 6c0584ad27)
    OS: nt
    Python: 3.11.1
    Twisted: 22.10.0
    Django: 4.1.4

#### Additional context
Very likely related, ... when spawning a new map with a replaced # node that is now a T, but the level is teleports to is not added yet, the xyzgrid tool attempts to spawn, but corrupts the XYZgrid related database to the point is has to be manually removed using SQL and regenerated.

**Comment by Griatch** [comment]
The respawner does not understand changing the type of a node in-place, so this functionality is not supported at this time. To work around this, you can do this: 

1. Remove your `#` node 
2. Respawn - this will delete that node 
3. Add the `T` node in its place 
4. Respawn again - the spawner now sees there is a new node in that (empty) spot and makes it a T node. 

I have updated the XYZgrid doc with this info.
