### ISSUE TITLE
[Feature Request] Automatically call `at_rename` when setting the `name` property

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3198]
#### Is your feature request related to a problem? Please describe.
The `at_rename` hook on objects is very handy for handling special side-effects that you want executed when an object's name is changed. However, as things are currently designed, this is only called either by the `name` command or when called explicitly by the code.

#### Describe the solution you'd like
I think it would be a useful change to have the `at_rename` hook called automatically within the setter for the `name` property on `TypedObject` rather than only called from within the `name` command itself.

I realize there are potentially a lot of other considerations for actually implementing something along these lines, but I think it'd be a useful enhancement.

**Comment by Griatch** [comment]
Hm, should be relatively easy to add.

**Comment by aMiss-aWry** [comment]
Done here https://github.com/evennia/evennia/commit/735416a16e1d57ad5fb7ad4a0364cdb28a3f0882

**Comment by aMiss-aWry** [comment]
Done by Volund here [735416a](https://github.com/evennia/evennia/commit/735416a16e1d57ad5fb7ad4a0364cdb28a3f0882)
