### ISSUE TITLE
[Documentation] Inconsistent sides lists in turn-based combat tutorial

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3199]
#### Existing page / new
[Turn-based combat, getting sides](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Combat-Turnbased.html#getting-the-sides-of-combat) 

#### Documentation issue
As the example code stands, the combatant is included in the `allies` list in PvP, but not included anywhere for other cases. Based on the combat-over check, it seems as though the combatant is expected to be included in allies, but either way it should be consistent between the two situations. 

#### Suggested change
In the NPCs VS PCs situation, it shouldn't be necessary to filter the combatant from either list - they should probably be simple assignments.

**Comment by Griatch** [comment]
The `get_sides` method was intended to ignore the `combatant` in the `allies` return; so it's the PvP case that is wrong. Looking over this though, having to remember that the caller is not included in the allies add extra complexity and makes it harder to reason around this method. So I have refactored the code (and the tutorial) to consistently include the `combatant` in the `allies` return list.
