### ISSUE TITLE
[BUG] EvenniaAdminSite doesn't account for any third-party or custom apps

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#3202]
#### Describe the bug
The Django AdminSite class is replaced with a custom one. Here's a snippet from Evennia's version:

https://github.com/evennia/evennia/blob/c18ff3898e533600321e94404e1a1a9ed4bd24a7/evennia/web/utils/adminsite.py#L33-L49

Here's what Django's looks like:

https://github.com/django/django/blob/1136aa5005f0ae70fea12796b7e37d6f027b9263/django/contrib/admin/sites.py#L533-L547

The Evennia version only sorts those objects in the list that had an ordering predefined. If no ordering was specified, the app is excluded from the list altogether. 

#### Expected behavior
Django doesn't do any of this sorting-by-specific item, they just sort the entire list alphabetically and return that.

I believe this is why I still can't get any custom apps to show up in the admin panel.

**Comment by strikaco** [comment]
This turned out to not be so cut-and-dry; making changes to this part changed nothing with regard to enabling custom apps.

What did work was copying-and-pasting the entire INSTALLED_APPS list from settings-default to settings, and removing the custom Evennia admin appconfig. Then my custom app showed up and had URLs routed appropriately.

**Comment by Griatch** [comment]
@strikaco: Do we know any reason as to why removing the appconfig like this worked? It sounds like something one could add to docs.

**Comment by owllex** [comment]
I had the same issue. My workaround was to subclass `EvenniaAdminSite` to modify the app_order field, then remove EvenniaAdminSite from installed apps and replace it with my subclass. Making `app_order` configurable from settings I think would solve this issue.

**Comment by strikaco** [comment]
> @strikaco: Do we know any reason as to why removing the appconfig like this worked? It sounds like something one could add to docs.

I could barely figure out how to articulate the issue itself; I'm not going to be much help in documenting a solution ;)

> I had the same issue. My workaround was to subclass `EvenniaAdminSite` to modify the app_order field, then remove EvenniaAdminSite from installed apps and replace it with my subclass. Making `app_order` configurable from settings I think would solve this issue.

That sounds logical.

**Comment by owllex** [comment]
I think someone did recently make app_order configurable from settings, so this workaround may not be necessary anymore.

**Comment by Griatch** [comment]
Yes DJANGO_ADMIN_APP_ORDER is configurable since some time. Closing this.
