### ISSUE TITLE
[Documentation] Typo in Beginner Tutorial Part 1, 7.3.2

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#3209]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Learning-Typeclasses.html#attributes

#### Documentation issue
The typo in this section refers to a value 'str' instead of 'strength,' which breaks the attempt to follow the tutorial.

#### Suggested change
change from [py self.strength = self.str + 1] to [py self.strength = self.strength + 1]

![Str1](https://github.com/evennia/evennia/assets/67276965/48067170-19b1-41f9-ac64-c6115a6e2d32)
![Str2](https://github.com/evennia/evennia/assets/67276965/b5a91781-f388-4669-832e-f3f7aa11cd61)

**Comment by Griatch** [comment]
Thanks for the heads up! Fixed now.
