### ISSUE TITLE
[Documentation] Issue in Tutorial, 11.1

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#3212]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Searching-Things.html

#### Documentation issue
Attempting to follow the tutorial returns traceback error that indicate that "key" is an unexpected keyword argument.

I don't see "key" as a parameter in the evennia.utils.search API here: https://www.evennia.com/docs/latest/api/evennia.utils.search.html#evennia.utils.search.search_object

However, there is a "searchdata" parameter, which seems to make the sample work when you use it instead of "key". The issue is even easier to spot if you use the dragon Smaug created earlier in the tutorial.

Admittedly, this may be a 'me' issue. But I sure hope not or I'm going to feel foolish! Logs attached.

Edit to add: On further investigation, 11.2 may also be out of date.  It suggests using

`rose = obj.search("rose")`

This returns the traceback:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'obj' is not defined
```

Earlier in the tutorial, we used me.search("Smaug") successfully, and this method continues to work. This documentation may need to be updated from obj.search() to me.search()

#### Suggested change
Review to make sure the parameters in the example are up to date. I'm not savvy enough to figure out for myself why this isn't working.
![Search1](https://github.com/evennia/evennia/assets/67276965/3a7bb60c-02a7-44d5-af64-178d6d691259)
![Search2](https://github.com/evennia/evennia/assets/67276965/83fdb981-e3b3-4457-9abe-4c924e3201b1)
![Search3](https://github.com/evennia/evennia/assets/67276965/cc8b72c7-3cb3-4b67-8c7c-126d637f1a06)
![Search4](https://github.com/evennia/evennia/assets/67276965/4aceb141-7233-48db-beeb-aec49fa80c6e)

**Comment by Griatch** [comment]
Thanks for the feedback! There is indeed no `key=` kwarg supported in `evennia.search_object`, it should just be `search_object("query")`. 

The `obj.search()` is not wrong, it's just an example showing that you must use this with an existing `obj` instance. Later this is exemplified with `self.caller.search()` in the Command. To make it clearer though, I've made it more exlicit that the `obj` needs to be fetched from somewhere first.
