### ISSUE TITLE
[Documentation] Typos in sample code in Tutorial 11.2

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#3213]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Searching-Things.html#searching-using-object-search

#### Documentation issue
Trying to follow the example for "quickfind" in the sample code doesn't work because of typos in the code and a placeholder value. 
1. `query = self.args` is not properly indented
2. the `if not result` line lacks a colon
3. the placeholder value `foo` in `self.caller.msg(f"Found match for {query}: {foo}")` returns a NameError because foo is undefined.
4. Because of the space before {query} in the previous line, the result also returns two spaces when used in game. The result is prettier if the space before {query} is removed in the msg line.

#### Suggested change
Fix the typos and replace {foo} with {result}
![Quickfind](https://github.com/evennia/evennia/assets/67276965/7d3454ae-f2e5-4b80-b392-6d2ee57e97e6)

**Comment by Griatch** [comment]
Good catches. The indentation comes from my markdown editor sometimes deciding to swap to TAB inserts instead of 4-spaces without telling me :/
