### ISSUE TITLE
[Documentation] Typo in tutorial Part 1, 13.1

### ISSUE THREAD

**Issue by Valishet** [evennia/evennia#3216]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html#make-us-not-able-to-move-while-sitting

#### Documentation issue
There is a typo in the explanation section.  It indicates that we are looking for and going to create an attribute called is_resting, but in the code we are actually creating and looking for an attribute called is_sitting

#### Suggested change
Change is_resting to is_sitting in the final sentence.
![Sitting1](https://github.com/evennia/evennia/assets/67276965/47150333-d027-4ec3-8dd2-7595851a1a93)

**Comment by Griatch** [comment]
This is what I see in the current documentation here: https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html#make-us-not-able-to-move-while-sitting
![2023-07-14_14-16](https://github.com/evennia/evennia/assets/294267/8d6da72f-9bfb-49a3-8c28-778dd3ffad7e)
Could you maybe be working off an older version? Can be an idea to look at the `Version` in the left sidebar. Also doing Ctrl-F5 to refresh the page with no cache could also help.
