### ISSUE TITLE
[Documentation] Missing commas in code block for utils.py

### ISSUE THREAD

**Issue by morgurth** [evennia/evennia#3236]
#### Existing page
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.html

#### Documentation issue

Unable to run the tests using the command as written.
Incorrect module name at top of example. 
Missing commas is the _OBJ_STATS.format block.
Missing {} around uses.
Missing [Not carried].

#### Suggested change

Using Ubuntu WSL, I could run the tests from my game directory until I removed the leading "." from the test command.

evennia test --settings settings.py .evadventure.tests

should be

evennia test --settings settings.py evadventure.tests

The same applies to just running evennia test --settings settings.py evadventure.tests.test_utils

For "utils.py"

`# in mygame/evadventure/time.py`

should be

`# in mygame/evadventure/utils.py`

    return _OBJ_STATS.format(
        key=obj.key, 
        value=10, 
        carried="[Not carried]", 
        desc=obj.db.desc, 
        size=1,
        quality=3,
        uses="infinite"
        use_slot_name="backpack",
        attack_type_name="strength"
        defense_type_name="armor"
        damage_roll="1d6"
    )

should be

    return _OBJ_STATS.format(
        key=obj.key, 
        value=10, 
        carried="[Not carried]", 
        desc=obj.db.desc, 
        size=1,
        quality=3,
        uses="infinite",
        use_slot_name="backpack",
        attack_type_name="strength",
        defense_type_name="armor",
        damage_roll="1d6",
    )

```
_OBJ_STATS = """
|c{key}|n
Value: ~|y{value}|n coins{carried}

{desc}

Slots: |w{size}|n, Used from: |w{use_slot_name}|n
Quality: |w{quality}|n, Uses: |wuses|n
Attacks using |w{attack_type_name}|n against |w{defense_type_name}|n
Damage roll: |w{damage_roll}|n
""".strip()
```

should be

```
_OBJ_STATS = """
|c{key}|n
Value: ~|y{value}|n coins{carried}

{desc}

Slots: |w{size}|n, Used from: |w{use_slot_name}|n
Quality: |w{quality}|n, Uses: |w{uses}|n
Attacks using |w{attack_type_name}|n against |w{defense_type_name}|n
Damage roll: |w{damage_roll}|n
""".strip()
```

For test_utils.py

```
|ctestobj|n
Value: ~|y10|n coins

A test object

Slots: |w1|n, Used from: |wbackpack|n
Quality: |w3|n, Uses: |winfinite|n
Attacks using |wstrength|n against |warmor|n
Damage roll: |w1d6|n
""".strip()
```

should be

```
|ctestobj|n
Value: ~|y10|n coins[Not carried]

A test object

Slots: |w1|n, Used from: |wbackpack|n
Quality: |w3|n, Uses: |winfinite|n
Attacks using |wstrength|n against |warmor|n
Damage roll: |w1d6|n
""".strip()
```

**Comment by Griatch** [comment]
Thanks for reporting! Updated according to your suggestions now. :+1:
