### ISSUE TITLE
[Documentation] (Travis-CI is no longer free for OS)

### ISSUE THREAD

**Issue by MarshP** [evennia/evennia#3238]
#### Existing page 
(https://www.evennia.com/docs/latest/Coding/Continuous-Integration-Travis.html)

#### Documentation issue

`If your game is open source on Github you may use Travis for free. `

https://www.theregister.com/2020/11/02/travis_ci_pricng/

#### Suggested change

`If your game is open source on Github you may try Travis for a limited time for free. `

**Comment by Griatch** [comment]
I've removed the stale Travis/TeamCity doc pages entirely. Not only are info like Travis-for-OSS outdated (Evennia used to use Travis a long time ago), the TeamCity tutorial was also for a very old version. We recommend something like github actions today instead.
