### ISSUE TITLE
[Feature Request] EvMenu Tooltip Functionality  

### ISSUE THREAD

**Issue by Seannio** [evennia/evennia#3244]
#### Problem Description: 
When displaying an EvMenu `menunode`, customizable help text is made available within the returned `menunode text` tuple, which doesn't refresh the `menunode`. This can be extended to allow for customizable, non-refreshing commands & responses beyond `help`, functioning as a small system for in-menu tooltips. 

#### Solution: 
Adding functionality to core EvMenu to allow the `help` return to be a string _or_ a dict, with EvMenu set up to parse customized command/commandtext data from the dict (if applicable).

**Comment by Griatch** [comment]
This was discussed in discord; it should be doable to return a dict and have that act as tooltip-like entries for displaying text, without having to jump nodes.
