### ISSUE TITLE
[BUG] `py` output in-game no longer functions correctly

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3245]
#### Describe the bug
In a default installation, using functions in `py` no longer returns a string representation of the returned result. If the function returns a list, the printed result is the first item in the list; if it's a dict, it returns the first key. Typeclassed objects show their key. I also tested numbers and QuerySet objects, and those simply failed to message anything with no errors.

#### To Reproduce
Output from using `py` in a vanilla install:
```py
>>> self.contents
thing
>>> print(self.contents)
[thing, something, box, rock]
>>> ["a","list","of","things"]
a
>>> 1
>>> 5+5
>>> self
admin
>>> from evennia import DefaultObject; DefaultObject.objects.all_family()
>>> from evennia import DefaultObject; print(DefaultObject.objects.all_family())
<QuerySet [admin, thing, thing, something, box, rock, Limbo]>
>>> {"test": 5}
test
```
#### Expected behavior
Previously `py` would echo a string representation of the result - I would expect this to continue.

#### Environment, Evennia version, OS etc
         Evennia version: 2.1.0
         OS: nt
         Python: 3.10.9
         Twisted: 22.10.0
         Django: 4.1.7

#### Additional context
It's not entirely clear what changed and what it's doing now, but in my own game (which has a custom `msg` function passing the text through a funcparser) it will error indicating that the `msg` function is getting the raw object - e.g. if I use `py self.contents` I get an error that the funcparser can't use `.replace` on a list. This suggests that the underlying issue is that the results from a function used in `py` are no longer being converted to a string before being sent as a message.

***edit: It just occurred to me that dicts and lists might be getting identified as iterable and parsed like a tuple in the default `msg` function, which would explain why the first item is being identified as the message - the rest are probably being shunted off as OOB args/kwargs.

**Comment by Griatch** [comment]
I don't recall exactly why we go through so much trouble to keep the output variable to `msg` its original value, but we do. I think it has to do with being able to send raw data to the webclient. :thinking: Either way, it seems no matter which option we go for, someone's not going to be happy about it :sweat_smile: 
I have added another implementation, where output defaults to being stringified, except if raw client data is to be sent; hopefully that works for everyone.
