### ISSUE TITLE
[BUG] Tutorial 10.6 create/drop dummy issue with EquipmentHandler

### ISSUE THREAD

**Issue by theRolento** [evennia/evennia#3259]
There's an issue with the `create/drop dummy puppet;dummy:typeclasses.npcs.NPC` command (Tutorial 10.6).
You get this error if you attempt to run the command:
`typeclasses.equipment.EquipmentError: dummy puppet is not something that can be equipped.`

The culprit is in the EquipmentHandler (Tutorial 5.4):
```
    def validate_slot_usage(self, obj):
        """
        Check if obj can fit in equipment, based on its size.
        """
        if not inherits_from(obj, Object):
            raise EquipmentError(f"{obj.key} is not something that can be equipped.")

**Comment by Griatch** [comment]
While the evadventure code addressed this, it was not reflected in the tutorial text. I've now added another section at the end of the Equipment Tutorial that resolves this error.

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/commit/c4c4cb14ff915a62cf98070e3bd5ab5b3f633e30
