### ISSUE TITLE
[Feature Request] Add an easier mechanism for customizing the index page content

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3266]
#### Is your feature request related to a problem? Please describe.
The index page for the Evennia website comes with all the page content built into the page template itself. This specifically references the game as a basic Evennia install, pointing back to the repository etc. with no references to the actual game install other than the header and page title.

This means that any dev that wants to actually use the website *has* to completely replace the `index.html` template.

#### Describe the solution you'd like
The main text *content* of the page should be separate from the page *template*, and customizable without having to completely replace the `index.html` template. This could be done by referencing a separate content html file that gets embedded, or an item in settings.py, or an admin-editable database field.

#### Describe alternatives you've considered
Alternatively, the `index.html` file should be copied into the gamedir's web structure by default, to make it less obtuse for people to find and customize. I think this is a less ideal situation, however, since it still requires the modification of the structural template file.

**Comment by Griatch** [comment]
Agreed, I think there are things to do to improve the website template's override-ability in general.

**Comment by Griatch** [comment]
This sounds like an excellent thing for a frontend/web-savvy person to help clean up according to best practices!

**Comment by johnnyvoruz** [comment]
@InspectorCaracal what's your definition of "text content" on the index page? Just the initial main content block in the center of the screen above the Accounts, Recently Connected, and Database Stats? 
![image](https://github.com/evennia/evennia/assets/16931143/c339c093-b4e1-4b13-8f27-ca4d86ea1c83)
