### ISSUE TITLE
[BUG] Scripts added to an object by a typeclass containing a key are not found by ScriptHandler.get()

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3271]
#### Describe the bug
When adding a custom Script to an object (such as a room) with `obj.scripts.add(MyScript)`, where `MyScript` has a key defined on it, that script cannot then be found with `obj.scripts.get('my_script_key')`

#### To Reproduce
My test script class:
```py
class KeyedTestScript(Script):
    key = "testscript"
```

The game log where I add the script, verify it with `examine`, and then try to retrieve it:

```
>>> from typeclasses.scripts import KeyedTestScript; here.scripts.add(KeyedTestScript)
------------------------------------------------------------------------------
Name/key: kitchen (#9)
Typeclass: Room (typeclasses.rooms.Room)
Home: Limbo (#2)
Locks:   call:true(); control:id(1) or perm(Admin);  delete:id(1) or perm(Admin);
  drop:holds();  edit:id(1) or perm(Admin); examine:perm(Builder);
  get:false(); puppet:false(); teleport:false(); teleport_here:true();
  tell:perm(Admin); view:all()
Scripts: 'testscript' (inf/inf, inf repeats):
Exits: south(#11)
Characters: admin(#1)
------------------------------------------------------------------------------
>>> print(here.scripts.get('testscript'))
<QuerySet []>
```
#### Expected behavior
Here is an equivalent, but where I set the key when I create the script and use the `obj` keyword to assign it to the room, and the script is found by `.get`:

```
>>> from evennia import create_script; create_script(key='secondtest', obj=here)
------------------------------------------------------------------------------
Name/key: kitchen (#9)
Typeclass: Room (typeclasses.rooms.Room)
Home: Limbo (#2)
Locks:   call:true(); control:id(1) or perm(Admin);  delete:id(1) or perm(Admin);
  drop:holds();  edit:id(1) or perm(Admin); examine:perm(Builder);
  get:false(); puppet:false(); teleport:false(); teleport_here:true();
  tell:perm(Admin); view:all()
Scripts: 'testscript' (inf/inf, inf repeats): 
 'secondtest' (inf/inf, inf repeats):
Exits: south(#11)
Characters: admin(#1)
------------------------------------------------------------------------------
>>> here.scripts.get('secondtest')
<Script secondtest>
```

#### Environment, Evennia version, OS etc

         Evennia version: 2.3.0
         OS: nt
         Python: 3.10.9
         Twisted: 22.10.0
         Django: 4.1.7

#### Additional info

Both of the scripts do show up in the results for `here.scripts.all()` - it's only `get(key)` that's failing to find the first case.

**Comment by Griatch** [comment]
I can reproduce this, it's a very curious behavior that only appears if the `key` is defined in the class body. I'm not sure this is really *expected* to work, but it's clear the key does appear and is retained after a reload. The behavior is weird though:

```python
>>> evennia.DefaultScript.objects.all_family()[1].key
test_script 
>>> evennia.DefaultScript.objects.all_family()[1].db_key 
#17
```

So there is a discrepancy between what is returned by `.key` and `db_key` which I've not seen before; while this explains why it's not located with e.g. a `DefaultScript.obejcts.get_family(db_key="test_script")` query (which is what the ScriptHandler `.scripts.get` is using under the hood), the `.key` is just intended to be a convenience wrapper above `.db_key` and it's unclear to me atm how they could drift apart like this.

Until this is fixed, assigning the key in the `create_script` or in `create_script` resolves this.

**Comment by InspectorCaracal** [comment]
I think I may have accidentally stumbled across the root of this problem the other day when trying to define initial intervals on the class.

When assigning something like `key` or `interval` on the class itself, I believe it overrides the underlying db-field logic created by the `db_key` and `db_interval` attributes, erasing Django's automatic association. Since displaying the script info uses the .key (or .interval) values, it grabs the class attribute and thus seems to be correct - but for any *database* queries, the value it's checking against is the default/fallback values, so of course it doesn't find anything.

As such, I think this is *not*, in fact, a bug, but a probably-undocumented quirk of the typeclass setup.
