### ISSUE TITLE
[BUG] `type: help` kwargs are not appended to CmdHelp output in most cases

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3273]
#### Describe the bug
Due to the default CmdHelp behavior of sending its messages through the `evmore` module, the line that actually includes the `type` kwarg in the msg data is not executed unless you have the pagination turned off entirely or you've implemented a webclient popup protocol flag.

https://github.com/evennia/evennia/blob/51e64387c1fb1c1e0b4d28263defb434967d7e66/evennia/commands/default/help.py#L124-L128

Furthermore, the `evmore.msg` function has no way to attach OOB data to its output at all, making it impossible to append the help type to those messages without more extensive modification of the EvMore class.

#### Expected behavior
Since the help command is clearly intended to have the OOB type data on its output, it should be added consistently regardless of whether the content is being paginated or not.

#### Environment, Evennia version, OS etc

         Evennia version: 2.3.0
         OS: nt
         Python: 3.10.9
         Twisted: 22.10.0
         Django: 4.1.7

**Comment by Griatch** [comment]
@InspectorCaracal I've added a `text_kwargs` kwarg to `EvMore` now, for allowing to add a custom kwarg block to the text outputfunc for every page - so if you set `text_kwargs={"type": "help"}`, this will create a `msg(text=(pagetxt, (), {"type": "help"}), ...)` call. 

Note that all `kwargs` you pass to `EvMore` will be passed into the `msg` call, so you can already add custom outputfuncs (aka OOB calls) that way.
