### ISSUE TITLE
[Documentation] bug: :bug: search_object() example code

### ISSUE THREAD

**Issue by iLPdev** [evennia/evennia#3299]
#### Existing page / new
[Lesson 7.1.2](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Learning-Typeclasses.html#creating-using-create-object)

#### Documentation issue

> If you want to find Smaug from anywhere (not just in the same room), you can use Evennia’s search_object function:
> 
> > cuddly = evennia.search_object("Cuddly")[0] ; cuddly.move_around()
> Cuddly is moving!

#### Suggested change
(1) Add call for inline @py interpreter, (2) correct above prose pertaining to Cuddly rather than Smaug, and (3) replace example result accordingly.

**Comment by Griatch** [comment]
Closing since it was fixed in a PR. As a hint, if you put "Closes #3299" or "Resolves #4299" in the description of your PR, it will auto-close the related issue. :)
