### ISSUE TITLE
[Feature Request] Allow cmdsets to decide if they should be shared when on objects

### ISSUE THREAD

**Issue by ChrisLR** [evennia/evennia#3302]
#### Is your feature request related to a problem? Please describe.
When you have a CmdSet that is going to be shared across typeclasses and they are in the same rooms
they appear as duplicated and the multimatch error raises.

#### Describe the solution you'd like
It should be possible for a CmdSet to decide if it should be shared or not.
It could be at the command level but the CmdSet is already very convenient.

The problem is around the following code
evennia/commands/cmdhandler.py:345

A quick hack allows this but a real solution would be preferred :sweat_smile: 

```
local_obj_cmdsets = yield list(
                        chain.from_iterable(
                            (cmdset for cmdset in lobj.cmdset.cmdset_stack if getattr(cmdset, 'shared', True))
                            for lobj in local_objlist
                            if (
                                lobj.cmdset.current
                                and lobj.access(
                                    caller, access_type="call", no_superuser_bypass=True
                                )
                            )
                        )
                    )
```

A real solution could be calling a method on the cmdset, something like

```
def is_shared_for(self, caller, object):
    pass # Do the actual implementation ofc
```

Alternatively, we could also leverage CmdSet Locks but we would have to pass both the object and the caller to it.

#### Additional context
An example is an Inventory related CmdSet.
Both characters and objects can have Inventories
We don't want a bag left on the ground to suddenly stop players from getting stuff or grant nearby mobs access to those commands.

I can implement this but I am looking for feedback.

**Comment by Griatch** [comment]
This is not the responsibility of the cmdset, but of the object the cmdset sits on. This is already supported.

- On the object: You set the `call:false()` lock on the bag and you will not be able to access its commands. Or `call:holds()` if you only want access to the commands when you are holding the bag. This seems like what you are looking for.
- On the cmdset itself are class properties 
   - `no_objs` - don't include commands from nearby objects in this cmdset 
   - `no_exits` - don't include commands from nearby exits in this cmdset
   - `duplicates` - decides if same-keyed commands from same-prio cmdsets should cause a multi-match or if they should merge based on merge order. With this disabled you'll never get any multimatches.

Closing this. Feel free to ping to reopen if you don't think this resolves what you are looking for.

**Comment by ChrisLR** [comment]
no_objs almost covers it except that it seemed to prevent other commands from being used, in the case an object could provide commands but also have to hide its commands.
Having a method would give greater flexibility but I can work around the limitations.
Thanks for considering :smile:
