### ISSUE TITLE
[Documentation] Inaccurate Example Output for `sit` 

### ISSUE THREAD

**Issue by iLPdev** [evennia/evennia#3311]
#### Existing page / new
[Lesson 13.3.1](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html#command-variant-1-commands-on-the-chair)

#### Documentation issue
![image](https://github.com/evennia/evennia/assets/1428343/1c017396-7796-480c-96eb-559b8b50c9b9)

The actual output at this point in the tutorial is: `You sit in armchair.`

#### Suggested change
We could either alter the previous lesson to reflect this output or change the example output beginning here.

**Comment by Griatch** [comment]
This example explicitly assumes that you overrode the `sit` message. So this is correct. But if that's unclear, it can be clarified.
