### ISSUE TITLE
[BUG] Game is consistently failing initial restart due to `NoneType` error in `SessionHandler`

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3316]
#### Describe the bug
When creating a fresh game install from a gamedir which imports from the XYZGrid contrib, I am finding that it consistently fails its initial startup process at the "restart" step, with this traceback:

```
. [..] Initial setup complete. Restarting Server once.
. [..] Traceback (most recent call last):
. [..]   File ".\envev\lib\site-packages\evennia\server\server.py", line 367, in run_initial_setup
. [..]     initial_setup.handle_setup()
. [..]   File ".\envev\Lib\site-packages\evennia\server\initial_setup.py", line 222, in handle_setup
. [..]     setup_sequence[stepname]()
. [..]   File ".\envev\Lib\site-packages\evennia\server\initial_setup.py", line 186, in reset_server
. [..]     evennia.SESSION_HANDLER.portal_reset_server()
. [..]   File ".\envev\Lib\site-packages\evennia\server\sessionhandler.py", line 486, in portal_reset_server
. [..]     self.server.amp_protocol.send_AdminServer2Portal(DUMMYSESSION, operation=amp.SRESET)
. [..] AttributeError: 'NoneType' object has no attribute 'amp_protocol'
None
. [..] Error in initial setup. Stopping Server + Portal.
```

The game starts up perfectly fine if I start it again manually after that with no further issues, but it consistently happens *every time* I delete the database, migrate and then do the initial start.

#### To Reproduce
1. Create a clean evennia gamedir
2. Add `from evennia.contrib.grid.xyzgrid.xyzroom import XYZRoom` to any of your typeclass modules (I put it in `typeclasses/rooms.py`)
3. Run `evennia migrate` and `evennia start` as usual
4. `evennia status` confirms the server is not actually running
5. `server/log/server.log` contains the above traceback

#### Expected behavior
I expect it to start up without errors.

#### Environment, Evennia version, OS etc
    Evennia pip package v 2.3.0
    Windows 10
    Python 3.10

#### Additional context
Setting up the contrib in the settings file does *not* cause this problem. It only occurs if you import from it - whether it's "installed" in the settings or not makes no difference.

**Comment by InspectorCaracal** [comment]
After someone else mentioning they had the same traceback - although not reproducibly - who also was using the one contrib I DON'T use anywhere else (XYZGrid), I did some additional tests and tracked it down to a much smaller set of reproduction instructions:

1. Create a clean evennia gamedir
2. Add `from evennia.contrib.grid.xyzgrid.xyzroom import XYZRoom` to any of your typeclass modules (I put it in `typeclasses/rooms.py`)
3. Run `evennia migrate` and `evennia start` as usual
4. `evennia status` confirms the server is not actually running
5. `server/log/server.log` contains the same traceback as the initial post

I have *no* idea why importing from the XYZGrid contrib causes this, but I've pinpointed it down to this single addition and can reliably reproduce the effect.

**Comment by Griatch** [comment]
I have tried to reproduce this with a fresh game dir on `main` branch and cannot. I put the `XYZRoom` import in the `room.py` file on the same form as you exemplify here. The server initializes correctly every time despite me trying repeatedly. :disappointed: 

@InspectorCaracal Could you verify that you still see this with the latest code (notably after the refactoring of the evennia application startup/init)?

**Comment by InspectorCaracal** [comment]
@Griatch I had a discussion about this offline earlier this week and forgot to write up our tentative conclusions, which actually predicted that you wouldn't be able to reproduce it, whoops

My best theory right now is that the issue is caused by the server taking too long to run the initial startup, so it's not available when the portal tries to tell it to restart. Similar to the issue people have had where the server takes too long to shut down on a reload and the portal gets an error that the ports are still in use, because the old server process hasn't ended yet.

It's most likely reliably reproducible for me because my computer is very slow, pending a hardware upgrade. I'm not sure how to go about profiling the startup to see where or if the hangup is happening, but you can try running it on an artificially slowed drive speed or something else to repro it

**Comment by InspectorCaracal** [comment]
That said, I'll try it with the refactor when I have an opportunity and said refactor is stable

**Comment by InspectorCaracal** [comment]
Good news! The server-start refactor does seem to have resolved this! I tried it a few times both with a current commit and with an older one - the bug consistently occurred on the older commit, and doesn't happen at all on the current commit. I'm calling this officially fixed 👍
