### ISSUE TITLE
Favico.js library not found or the online version could not be reached. Check so Javascript is not blocked in your browser.

### ISSUE THREAD

**Issue by batindfa** [evennia/evennia#3318]
![image](https://github.com/evennia/evennia/assets/117291738/7dc9bb48-b64f-4cd5-8027-bdd1964c17e1)

hello, when I click this button, the error appears.
![image](https://github.com/evennia/evennia/assets/117291738/528a64d8-3b28-4546-bb78-63d78f8cffae)

**Comment by InspectorCaracal** [comment]
Did you check if javascript is blocked in your browser?

**Comment by yanmengxiang1** [comment]
@InspectorCaracal 
I check it. And I tried multiple browsers and all failed.
![image](https://github.com/evennia/evennia/assets/117291738/42648381-1371-43bb-9865-09d841c4d1be)

**Comment by Ozymendeus** [comment]
Have the exact same issue, actually. Server was on the night before. Woke up, started it up with no changes to any of my code, and got this error. Even my older versions are returning the same issue as well.

**Comment by Griatch** [comment]
This could not be reproduced and there is no response for almost a year. Closing.
