### ISSUE TITLE
[Documentation] Tutorial World intro menu has obsolete/wrong links

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3323]
The last node of the menu starting here https://github.com/evennia/evennia/blob/f6b43b04168ad8ce8045d5220804b563752a4e74/evennia/contrib/tutorials/tutorial_world/intro_menu.py#L683 contains multiple links, some of which are no longer correct

https://www.evennia.com/docs/latest/Building-Quickstart returns a 404 and I don't know where the correct page is

https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Tutorial-World should be https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Tutorial-World

The other links appear functional.

**Comment by Griatch** [comment]
Good eye. Updated in https://github.com/evennia/evennia/commit/b67bb7ee55ebc5db35e0a48d205f930de9027e73!
