### ISSUE TITLE
[Documentation] Beginner tutorial unit test example fails

### ISSUE THREAD

**Issue by iLPdev** [evennia/evennia#3328]
#### Existing page / new
[1.4.1. Running your test](https://github.com/evennia/evennia/blob/main/docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.md#running-your-test)

#### Documentation issue
given the example code provided, this test actually does fail due to inconsistency in the capitalization of `Not carried` vs `not carried`.

#### Suggested change
Uncertain if this is an intentional bug intended to have the student work out how unit testing actually works. If not intentional, the example code needs to be changed for consistent case.

**Comment by Griatch** [comment]
It *was* not deliberate, but now it is! :tongue: I added some text to explain that it should be fixed for extra credit now :wink:
