### ISSUE TITLE
[Documentation] 2.4. Testing resource import path

### ISSUE THREAD

**Issue by iLPdev** [evennia/evennia#3329]
#### Existing page / new
[2.4. Testing](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Rules.html#testing)

#### Documentation issue
```python
from evennia.utils.test_resources import BaseEvenniaTest
```
On my clean git install, the path to evennia is one level deeper.

#### Suggested change
```python
from evennia.evennia.utils.test_resources import BaseEvenniaTest
```

**Comment by Griatch** [comment]
No, this is incorrect. The `evennia/evennia` folder (the inner one) is the root of the `evennia` library and what you import. The top level (with the `CHANGELOG.md` file, `pyproject.toml` file etc) are for the python distribution. You never do `evennia.evennia.` anything. See https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Evennia-Library-Overview.html#where-is-it for more info.
