### ISSUE TITLE
[BUG] Multiple AJAX sessions will invoke sorcerer's apprentice mode

### ISSUE THREAD

**Issue by presjpolk** [evennia/evennia#3335]
#### Describe the bug
The portal accumulates ajax web sessions, causing exponential growth in duplicated output

#### To Reproduce
* Open an AJAX web client
* close the window
* Open an AJAX web client

Results: Everything you send, sends twice. Everything you then get back, you get back FOUR times.

#### Expected behavior
Each web client should be treated independently.

The PROPER fix I've discussed with Caracal ( see #3327 ), but is more involved. An immediate fix for the problem of ever-increasing duplication of output is below. Also note that there's probably some unnecessary code in websocket that was inadvertently working around that mistake in sessionhandler.

```diff
```diff
diff --git a/evennia/server/portal/webclient_ajax.py b/evennia/server/portal/webclient_ajax.py
index d6dc3c9fbf..d10c852c1e 100644
--- a/evennia/server/portal/webclient_ajax.py
+++ b/evennia/server/portal/webclient_ajax.py
@@ -242,6 +242,11 @@ class AjaxWebClient(resource.Resource):
         # actually do the connection
         sess.sessionhandler.connect(sess)
 
+        for s in self.sessionhandler.sessions_from_csessid(csessid):
+            if not s == sess:
+                s.sessionhandler.disconnect(s)
+
         return jsonify({"msg": host_string, "csessid": csessid})
 
     def mode_keepalive(self, request):
diff --git a/evennia/server/sessionhandler.py b/evennia/server/sessionhandler.py
index 0dd7956b48..b8d8ef6982 100644
--- a/evennia/server/sessionhandler.py
+++ b/evennia/server/sessionhandler.py
@@ -784,7 +784,7 @@ class ServerSessionHandler(SessionHandler):
             sessions (list): The sessions with matching .csessid, if any.
 
         """
-        if csessid:
+        if not csessid:
             return []
         return [
             session for session in self.values() if session.csessid and session.csessid == csessid
```

**Comment by Griatch** [comment]
Thanks for the fix and analysis! 

As a background, the AJAX client is old and is normally only used as an emergency fallback if the server is misconfigured (usually by not opening the WS ports or WSS configuration fails). Considering websockets are supported by all browser these days, this should normally not be an issue for most people (but this definitely needs to be fixed of course).

(Note: while a diff works, a PR is often easier since one can then discuss solutions in-place. Also allows proper credit to be given)

**Comment by presjpolk** [comment]
I'm using a pretty standard Brave with Windows 11.

The game I'm working on is set to MULTISESSION_MODE 1.

My problem with websockets isn't browser support. It's mobile support.  Most people access the Internet on their phones, and a pure websocket approach works very poorly in that environment.  People's IP addresses frequently change on mobile networks, which breaks fixed socket-based connections, including telnet and websockets.

**Comment by Griatch** [comment]
Bug fix is long closed. Closing this :)
