### ISSUE TITLE
[BUG] XYZGrid calling non-existent method

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#3337]
#### Describe the bug
XYZGrid calls `all_rooms` method (https://github.com/evennia/evennia/blob/40a4bd05929eabf11c7a159dc3a741cd2cb9ded3/evennia/contrib/grid/xyzgrid/launchcmd.py#L405) which does not exist.

**Comment by InspectorCaracal** [comment]
Looks like it's supposed to be `all_maps`
