### ISSUE TITLE
[BUG] Expanded Room time-of-day tags do not update until post-character entry

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#3340]
#### Describe the bug
When entering an Expanded Room, characters will see an out-of-date description if time has reached a new tag but the room hasn't updated yet.

#### To Reproduce
1. Use Expanded Rooms contrib
2. Create a room with time of day tags.
3. Visit room after time-of-day change.

#### Expected behavior
Rooms should update before a character enters so that the description is not incorrect.

![image](https://github.com/evennia/evennia/assets/73198594/cd7719e8-b7c5-47c0-b9d5-81f5e42c9e39)

**Comment by jaborsh** [comment]
Issue resolves if `at_post_move` logic is moved instead to `at_object_receive`, but I'm not sure that's an ideal solution.

**Comment by InspectorCaracal** [comment]
I'm not familiar with the extended room code but this definitely sounds wrong. It should check if it needs to be updated when *looked at*, not based on object entry or departure, or things like changing time of day will not update correctly when spending time in a room.

**Comment by Griatch** [comment]
I did some initial investigation of this, but didn't immedately see the issue. Will need more investigation.
