### ISSUE TITLE
[BUG] GitHub auto-testing is broken

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3352]
#### Describe the bug
As of 8914e7b0b61a3bf071615c47bcea869ffebf7f8c all tests on GitHub have been failing with a consistent set of database-related errors.

Since this is a breaking change relating to testing, it may just mean the github-specific test suites no longer work and need to be updated? Either way, the entire auto-testing mechanism is currently nonfunctional.

**Comment by Griatch** [comment]
I fixed the overall issue - it was due to the changes to `TEST_ENVIRONMENT` I did; didn't see the effect locally. 
There's still that long-running issue with PostgreSQL tests. Will fix that too, before closing this.
