### ISSUE TITLE
[Documentation] Beginner Tutorial Utilities Unit Testing Bug

### ISSUE THREAD

**Issue by iLPdev** [evennia/evennia#3360]
#### Existing page / new
[Lesson 1.4](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.html#testing)

`BaseEvenniaTest` will use the default evennia typeclasses rather than EvAdventure's

#### Documentation issue
```python
from evennia.utils.test_resources import BaseEvenniaTest 

...

class TestUtils(BaseEvenniaTest):
```
#### Suggested change
```python
from evennia.utils.test_resources import EvenniaTest 

...

class TestUtils(EvenniaTest):
```

**Comment by Griatch** [comment]
Resolved in https://github.com/evennia/evennia/commit/255655dffe87c3c578d4b9a0c823c0fe00e6712e
