### ISSUE TITLE
[Documentation] static_overrides tutorial doesn't work

### ISSUE THREAD

**Issue by iLPdev** [evennia/evennia#3368]
#### Existing page / new
[https://www.evennia.com/docs/latest/Howtos/Web-Changing-Webpage.html#changing-the-logo-on-the-front-page](https://www.evennia.com/docs/latest/Howtos/Web-Changing-Webpage.html#changing-the-logo-on-the-front-page)

#### Documentation issue
following the guide to changing the logo does not work, but adding the new logo file in `mygame/web/static/website/images/evennia_logo.png` does work.

#### Suggested change
Clarify or update how-to concerning whether `static_overrides` works anymore

**Comment by Griatch** [comment]
This is an old tutorial, it should likely be reworked entirely. `static_overrides` is anyway the old style; it's all in `static/` these days.
