### ISSUE TITLE
[BUG] `CmdCreate` no longer puts objects in your inventory

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3372]
#### Describe the bug
When using `create` rather than `create/drop`, the expected behavior is that the object will be created into your inventory. However, it is not giving objects a location at all.

#### To Reproduce
1. `create thing` in a clean game
2. `inv` - thing is not there
3. `ex #{dbref}` - there is no Location field

#### Expected behavior
It should be put into my inventory.

#### Environment, Evennia version, OS etc
Evennia 3.0.0
Python 3.10

#### Additional context
I also noticed that the creation success message doesn't include the object DBREF, which is a bit of a problem when attempting to uniquely target things.

**Comment by Griatch** [comment]
Closed in https://github.com/evennia/evennia/pull/3373
