### ISSUE TITLE
[Documentation] Docstrings in game template files are outdated

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3387]
#### Existing page / new
https://github.com/evennia/evennia/blob/main/evennia/game_template/typeclasses/objects.py

#### Documentation issue
The module docstring only mentions the `Object` typeclass and describes the solution for sharing inheritance that was necessary before `ObjectParent` was implemented into the game directory.

In addition, the docstring for the `Object` typeclass itself repeatedly mentions `BaseObject`, which doesn't exist, and gives what I assume is either a very, *very* old class path of `src.object.objects` or is using an unclear shorthand.

#### Suggested solution
The docstrings should be thoroughly reviewed and updated to match the existing state of evennia

**Comment by Griatch** [comment]
I added in all the missing methods/hooks etc. It's not very pretty but at least more complete. I wonder if it may not be better to just remove those headers and refer people to the docs ... :thinking:
