### ISSUE TITLE
[Feature Request] EvMenu Enhanced Screenreader Support

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#3392]
#### Is your feature request related to a problem? Please describe.
Due to EvMenu's method of assigning various options to multiple columns, Screenreaders do not easily distinguish multiple options when they are on the same line.

#### Describe the solution you'd like
I believe EvMenu should only provide a single column for all options for users using a Screenreader.

#### Describe alternatives you've considered
I'm sure alternatives exist, but I'm not sure what they might be. Maximizing nrows does feel like a dirty fix.

**Comment by InspectorCaracal** [comment]
Oh this is a great idea, I'll poke at it.
