### ISSUE TITLE
[Documentation] Tutorial on weapons and hit command does not remove hit command from self as described in tutorial

### ISSUE THREAD

**Issue by BurrowsForge** [evennia/evennia#3395]
#### Existing page / new
[](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-More-on-Commands.html)

#### Documentation issue
![image](https://github.com/evennia/evennia/assets/155598491/c0fc69db-0577-4254-820c-815f9222367c)

During the tutorial you are asked to remove a command from yourself with the command:

> py self.cmdset.remove("commands.mycommands.MyCmdSet")

I tried this a few times, tried restarting the server and I could not get the command to be removed from myself.  My files are named the same and I have the class MyCmdSet also named correctly.

I was able to add the hit command to the sword using:

> py self.search("sword").cmdset.add("commands.mycommands.MyCmdSet", persistent=True)

so the location seems to be correct. I don't know why it doesn't work on removing commands from me.

**Comment by Griatch** [comment]
The cmdset is set directly on the character, so one needs to remove it from the CharacterCmdSet in-code. Fixed it now.
