### ISSUE TITLE
[BUG] EvTable dropping whitespaces after first line

### ISSUE THREAD

**Issue by elee-p3** [evennia/evennia#3400]
#### Describe the bug
Effectively identical behavior as https://github.com/evennia/evennia/issues/3193, but these aren't nested tables - these are straightforward EvTables. We're outputting the tables as strings via `myEvTable.__str__()`, which could be part of the issue if this isn't standard practice.

On upgrade from 0.9.5 to 2.3.0, the functionality was still working as expected, but on the move from 2.3.0 to 3.1.0, this issue appeared.

Note: the below screenshots contain two EvTables that have been 
EvTable behavior on 2.3.0:
![old_sheet](https://github.com/evennia/evennia/assets/68520112/5ffc9e51-88ec-4cbb-abcf-4053e53630f0)

EvTable behavior on 3.1.0:
![new_sheet](https://github.com/evennia/evennia/assets/68520112/e5005c85-e2d8-49ec-b32a-b9ee8c8ebb11)

#### To Reproduce
1. Create a multi-row EvTable on any evennia version between 0.9.5 and 2.3.0
2. Migrate to version 3.1.0
3. View the same EvTable

#### Expected behavior
EvTable maintains proper spacing throughout table.

#### Environment, Evennia version, OS etc
Python 3.11, Evennia 3.1.0, Windows 10 Build 19045.3803

#### Additional context
N/A

**Comment by InspectorCaracal** [comment]
Does this happen in both the webclient and in telnet?

**Comment by Griatch** [comment]
@elee-p3 Could you provide the code for creating this table (or a smaller table showcasing the effect)? I don't see no issues with a simple right-aligned table, so it would be useful to know exactly how you create the table to understand what could be the issue.

**Comment by elee-p3** [comment]
Absolutely. Also, I think I've got a better handle of the issue now - it seems to stem from EvTable no longer respecting the `width=` argument. Here's a simpler repro, and the code snippet for generating the table.

Old behavior:
![repro_old](https://github.com/evennia/evennia/assets/68520112/2aa1e137-d947-4ee1-841d-ae366716e66f)


New behavior:
![repro_new](https://github.com/evennia/evennia/assets/68520112/cd2667f4-f24c-479a-9297-502912e7795d)


Code:

```
class CmdSheet(default_cmds.MuxCommand):
    def func(self):
        caller = self.caller
        client_width = self.client_width()
        sheetMsg = ""
        charInfoTable = evtable.EvTable(border_left_char="|", border_right_char="|", border_top_char="-",
                                        border_bottom_char=" ", width=client_width, border="table")
        charInfoTable.add_column()
        charInfoTable.add_column()
        charInfoTable.add_column()
        charInfoTable.add_column()
        charInfoTable.reformat_column(0, align='l')  # resource label
        charInfoTable.reformat_column(1, align='r')  # resource value
        charInfoTable.reformat_column(2, align='l')  # stat label
        charInfoTable.reformat_column(3, align='l')  # stat value
        charInfoTable.add_row("col1", "col2", "col3", "col4")
        charInfoString = charInfoTable.__str__()
        sheetMsg += charInfoString[:charInfoString.rfind('\n')] + "\n"  # delete last newline (i.e. bottom border)

        self.caller.msg(sheetMsg)
```

Let me know if you need any more information.

**Comment by InspectorCaracal** [comment]
I copied that command into a clean test game and ran it and I can't replicate the problem.

     Evennia version: 3.1.1
     OS: nt
     Python: 3.10.9
     Twisted: 23.10.0
     Django: 4.2.8

Output on the webclient:
![image](https://github.com/evennia/evennia/assets/51038201/d846956a-6bdd-479b-931e-88544951e8eb)

Output in Mudlet:
![image](https://github.com/evennia/evennia/assets/51038201/4c830f9e-1cf8-43b6-a496-ec9a7a7d7b07)

**Comment by elee-p3** [comment]
Huh - I guess the only significant difference is the OS? And I actually just stumbled on the what the actual issue seems to be: somehow on my machine, `self.caller.msg` is turning all whitespace with a length > 1 to a single whitespace. e.g.

```
caller.msg("               testing                  this             out")
```

is being printed out as

```
testing this out
```

**Comment by InspectorCaracal** [comment]
> Huh - I guess the only significant difference is the OS? And I actually just stumbled on the what the actual issue seems to be: somehow on my machine, `self.caller.msg` is turning all whitespace with a length > 1 to a single whitespace. e.g.
> 
> ```
> caller.msg("               testing                  this             out")
> ```
> 
> is being printed out as
> 
> ```
> testing this out
> ```

Is this on the webclient? If so, you may want to try clearing your cache.

**Comment by elee-p3** [comment]
that did it! Out of curiosity, do you have any idea what that was all about?

Either way, you can close this out - thank you!

**Comment by InspectorCaracal** [comment]
I do! That's why my very first question is if it was happening on both the webclient and telnet. xD

In the 1.0 release, there was a change made to the CSS file for the webclient so that it would render whitespace characters instead of the server having to replace them all with `&nbsp;`. The default behavior for browsers is to compress all the whitespace to a single displayed space, so if your browser still has the old pre-1.0 webclient files cached, it wouldn't render the spaces properly.

**Comment by Griatch** [comment]
Looks like this can be closed then :+1: Good to know that this particular issue can be handled with a cache clean.
