### ISSUE TITLE
[Documentation] 13.2.1. Sitting on or in - code does not work (easy fix!)

### ISSUE THREAD

**Issue by BurrowsForge** [evennia/evennia#3401]
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html
Documentation issue
In section 13.2.1 of adding sittable chairs they have you sit in an armchair. When I tried this code,

py armchair.do_sit(me)
I got an error, "NameError: name'armchair' is not defined)-->

Suggested change
When asking in help I was told that py does not know anything about the chair even though it is in the same room. I had to search for the chair in the command to get it to work.  the syntax that worked was,

py me.search("armchair").do_sit(me)

![image](https://github.com/evennia/evennia/assets/155598491/6fb26dea-09af-4bbf-81e6-66ec8ac1371b)

**Comment by BurrowsForge** [comment]
Again for some reason my description is not being saved. I don't know why!!!

#### Existing page / new
[
](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html)
#### Documentation issue


#### Suggested change

![image](https://github.com/evennia/evennia/assets/155598491/6fb26dea-09af-4bbf-81e6-66ec8ac1371b)

**Comment by Griatch** [comment]
Very true. Fixed!
