### ISSUE TITLE
[Documentation] Test without migrations instructions lead to crash

### ISSUE THREAD

**Issue by BigJMoney** [evennia/evennia#3403]
#### Existing page / new
[](https://www.evennia.com/docs/latest/Coding/Unit-Testing.html#a-note-on-making-the-test-runner-faster)

#### Documentation issue
Following the instructions led me to a crash (in 2.3) because, the way the code snippet is written, it doesn't account for a required setting in the settings_default file.

#### Suggested change
`INSTALLED_APPS += ["test_without_migrations"]`

**Comment by Griatch** [comment]
I don't know what instructions you are referring to here. 2.3 of the tutorial has no such instructions. Please give a link.
