### ISSUE TITLE
[Documentation]  13.3.2. Command variant 2: Command on Character: Code is missing indentation on example

### ISSUE THREAD

**Issue by BurrowsForge** [evennia/evennia#3408]
#### Existing page / new
[](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html)

#### Documentation issue
The code underneath def in the code example for the stand command on 13.3.2. Command variant 2: Command on Character is not indented under "def"

#### Suggested change

I don't know if this is correct but I'm sure whoever is reading this knows better than I do.

```
    def func(self):
    
        caller = self.caller
        #if we are sitting, this should be set on us
        sittable = caller.db.is_sitting
        if not sittable:
            caller.msg("You are not sitting down.")
        else:
            sittable.do_stand(caller)
```

![image](https://github.com/evennia/evennia/assets/155598491/2472d424-5c35-43de-a012-2e2d582b5851)

**Comment by Griatch** [comment]
Good catch; the indent was indeed wrong!
