### ISSUE TITLE
[BUG] `AMP_ENABLED = False` breaks Evennia but still allows you to try to start

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3409]
#### Describe the bug
AMP is a required internal service for Evennia to communicate internally between the server and portal processes. However, it will still attempt to boot up everything normally if you disable it in the settings, causing the whole thing to just simply stop doing anything.

I'm not sure what about the internal architecture and validation checks allow this to happen, but it might be worth considering an alternative where attempting to start evennia with AMP completely disabled raises an error message and aborts instead.

#### Environment, Evennia version, OS etc
Evennia 3.1.1

**Comment by Griatch** [comment]
The AMP_ENABLED flag is not really something people would be expected to ever mess with; it was added at a time when I pictured one may want to replace the portal, but if we were to change/rebuild the portal to use something other than AMP, then it would require more surgery than just disabling AMP. So I'll just remove this option.
