### ISSUE TITLE
[BUG] The curious case of the '$' character capturing text after it and double printing output.

### ISSUE THREAD

**Issue by Temujyn83** [evennia/evennia#3418]
After updating to 3.1.1 it no longer doubles output just being in a file. However using msg_contents("$You") and forgetting the () at the end will grab all text after the $ and double print. So less a bug and more user error, I tried to delete this couldn't see how/where, new to github, apologies.

**Comment by Griatch** [comment]
I don't see it double-print, it's just that if you do e.g. `here.msg_contents("$You")` without the `()` it will send the `$You` as a string to the room and possibly echoed to you separately if you haven't set up the source of the call properly. 

> (oh, and you can use the `Close with comment` or `Close as not planned` at the bottom to close the close the ticket (you cannot 'delete' it beyond that).
