### ISSUE TITLE
[BUG] EXTREMELY strange Django query behavior?

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3422]
#### Describe the bug
I don't understand what's happening here, but for some reason, doing lt/gt checks on values is for some cases just.... not giving results. Checking if a value is below certain ranges of numbers just seems to result in an empty query set, even when it should be valid.

#### To Reproduce
Here is a bunch of in-game `py` testing I did.
```
>>> here.db.test = 54.23589134
>>> from evennia.objects.models import ObjectDB
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__gt=50.0))
<QuerySet [Limbo]>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__gt=50.0, db_attributes__db_value__lt=58.0))
<QuerySet []>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=57.0))
<QuerySet [Limbo]>
>>> here.db.test = 77.238492342
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=80.0))
<QuerySet [Limbo]>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=90.0))
<QuerySet [Limbo]>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=100.0))
<QuerySet [Limbo]>
>>> here.db.test = 54.23589134
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=58.0))
<QuerySet []>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=57.0))
<QuerySet [Limbo]>
>>> here.db.test = 55.23589134
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=58.0))
<QuerySet []>
>>> here.db.test = 57.23589134
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=58.0))
<QuerySet []>
>>> here.db.test = 7.23589134
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=58.0))
<QuerySet [Limbo]>
>>> here.db.test = 37.23589134
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=57.0))
<QuerySet [Limbo]>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=58.0))
<QuerySet []>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=59.0))
<QuerySet []>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=60.0))
<QuerySet []>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=70.0))
<QuerySet [Limbo]>
>>> here.db.test = 54.23589134
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=70.0))
<QuerySet [Limbo]>
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=60.0))
<QuerySet []>
```

#### Expected behavior
It shouldn't mysteriously be empty??

#### Environment, Evennia version, OS etc

         Evennia version: 3.1.1
         OS: nt
         Python: 3.10.9
         Twisted: 23.10.0
         Django: 4.2.8

**Comment by strikaco** [comment]
Weird.

* After line 1, get/print the value and type of `here.db.test` to make sure the value is getting set and not as `str` or something silly. Ideally do `examine` so it's clear it's even being set in the database.
* Is it the same result if you set the value through the handler, i.e. `here.attributes.add('test', 54.xxx)`?

**Comment by InspectorCaracal** [comment]
Yes, the data is all fine and the method of setting it doesn't make a difference.

Examined the room in a clean db after the first line and confirmed the attribute shows up as expected:
```
Persistent Attributes: 
  desc=Welcome to your new |wEvennia|n-based game! Visit https://www.evennia.c[...]
  test=54.23589134 [type: <class 'float'>]
```
Still gave me the following result:
```py
print(ObjectDB.objects.all().filter(db_attributes__db_key="test", db_attributes__db_value__lt=58.0))
<QuerySet []>
```

Additionally, I tried it with the handler directly like you suggested:
```py
>>> from evennia.objects.models import ObjectDB
>>> here.attributes.add('testb', 54.23589134)
>>> print(ObjectDB.objects.all().filter(db_attributes__db_key="testb", db_attributes__db_value__lt=58.0))
<QuerySet []>
```

**Comment by InspectorCaracal** [comment]
I just realized that for some reason a lot of those lines are doing `ObjectDB.objects.all().filter(etc)` for some reason, I must have done a weird copy/paste when testing. It does the same thing with `ObjectDB.objects.filter(etc)` though.

**Comment by strikaco** [comment]
> I just realized that for some reason all of those lines are doing `ObjectDB.objects.all().filter(etc)` for some reason, I must have done a weird copy/paste when testing. It does the same thing with `ObjectDB.objects.filter(etc)` though.

The first method is the textbook way of doing it. The second way avoids re-evaluating the queryset, which you probably don't want to do right now (you'll get stale results).

You could try moving the `.all()` to *after* the `.filter()`. That should force re-evaluation of "the" queryset, but I'm not sure if that's going to apply to ObjectDB, Attribute, or both.

**Comment by Griatch** [comment]
This is not a supported functionality of PickledFields and cannot work. 

Attribute-values are stored in pickled string form in a text field on the Attribute model. It's no a number. It's a string. 

What happens when you do a query like `ObjectDB.objects.filter(db_attributes__key="foo", db_attributes__value=23` is that the value `23` is converted into its pickled form (a string) and that value is then compared to the pickled value string in the database. This is why equal comparisons work. 

What you try to do here is to check if a string is lexicographically bigger or smaller than another (binary-encoded) string. I couldn't exactly reproduce the findings with `pickle.dumps(54.23, protocol=4) < pickle.dumps(70, protocol=4)`, but that's the principle of it anyway.

**Comment by InspectorCaracal** [comment]
In that case, this information should be included in the Advanced Searching page, since it seems critical and the examples are presented as though numerical inequality comparisons will work.

**Comment by Griatch** [comment]
It never worked, but you are right that the example does use a faulty example. I'll add that and add clearer docs on the Attributes page too.

**Comment by InspectorCaracal** [comment]
@Griatch Yes, I meant it seems to be critical information.
