### ISSUE TITLE
[BUG] Menu-based login contrib does not respect registration setting.

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3428]
#### Describe the bug
With `NEW_ACCOUNT_REGISTRATION_ENABLED = False` and the menu login contrib set up, you can still register for a new account.

#### To Reproduce
1. Set up the contrib
2. Try to register from telnet or the webclient
3. See error

#### Expected behavior
It should be updated to respect the setting

#### Environment, Evennia version, OS etc
Evennia 3.1.1

**Comment by Griatch** [comment]
I added this functionality for both the menu- and email-login contribs now.
