### ISSUE TITLE
[Documentation] Improve PyCharm instructions for macOS/Linux

### ISSUE THREAD

**Issue by vadi2** [evennia/evennia#3431]
#### Existing page / new
https://www.evennia.com/docs/latest/Coding/Setting-up-PyCharm.html 

#### Documentation issue
It would be great to see the documentation updated to handle modern PyCharm as well as running the setup on macOS and Linux. The following points need to be addressed:

- when PyCharm is first launched, it will offer to create a evenv. This should be declined by the user and is not mentioned in the documentation
- `\<yourrepo\>\evenv\Scripts\evennia_launcher.py` is not a valid location on macOS/Linux, rather it is `evenv/bin/evennia`. It is a an open question is it is valid on Windows too.
- even after evennia is running, breakpoints do not take hold in PyCharm. Unsure about this.

#### Suggested change

An update to the documentation to make it more current would be welcome.

**Comment by ChrisLR** [comment]
I will take a look soon-ish.
A few notes before I do

- Creating a new venv can be the right move if you are setting a new project and not following the guidelines.
- Links will vary from OS to OS and from install to install, I can give out a few examples but it will never be set in stone
- Breakpoints will only work when you attach to the proper process or if you are running tests, there's a few tricks to it, I will update that part.

**Comment by Griatch** [comment]
@ChrisLR A reminder of this as you said you might be interested in looking at this. I don't use PyCharm myself.

**Comment by Griatch** [comment]
This was reworked and improved extensively. I will close this now; possibly the Windows instructions need revisit down the line.
