### ISSUE TITLE
[BUG] RPsystem contrib breaks dbrefs

### ISSUE THREAD

**Issue by Aeliffa** [evennia/evennia#3439]
#### Describe the bug
I installed the rpsystem contrib as instructed and it works as intended. But now when I try to find or use #dbrefs, it fails to acknowledge them. Here is an example of the problem: 
![image](https://github.com/evennia/evennia/assets/137568434/315ae4c2-043e-4644-b8ea-338c5b461f90)

#### To Reproduce
1. Install evennia.contrib.rpg.rpsystem
2. Try to find, look, desc or delete an item by its #dbref
3. See error

#### Expected behavior
It should show me the correct object/character/room and allow me to trigger commands using the #dbref as it did before.

#### Environment, Evennia version, OS etc
Evennia: 3.2.0
OS: Windows 10
Python: 3.10.6
Twisted: 23.10.0
Django: 4.2.10

#### Additional context
The #dbrefs worked perfectly prior to installing rpsystem, so I'm confident it has to do with that. I admit I'm not very savvy with python or evennia, so there is every possibility of user error. But I did install it correctly - to the best of my knowledge. Here are the relevant files I changed to install rpsystem so you can confirm if it was done correctly: https://github.com/Aeliffa/evenniahelp

**Comment by InspectorCaracal** [comment]
I've confirmed this is a problem with the custom search, likely introduced in one of the recent changes to the search function.

Here are the simplified reproduction steps pinpointing it:

1. Inherit from `ContribRPCharacter` on your `Character` class in `typeclasses/characters.py` as per the install instructions.
2. DON'T do any other installation steps.
3. Attempt to interact with any object by dbref - it will fail to find it.
