### ISSUE TITLE
[BUG] Evennia Pip Extra Fails (Py 3.12.2 & Py 3.11.8)

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#3444]
#### Describe the bug
Pip installation for evennia[extra] fails at scipy1.9.3 depending on Python version. Currently tested on Python 3.12.2 and Python 3.11.8.

#### To Reproduce
1. Use aforementioned Python environments
2. `pip install evennia`
3. `pip install evennia[extra]`

#### Expected behavior
Pip installation should complete successfully.

#### Additional context
Recommend upgrading scipy to 1.12 where this issue is resolved for more current versions of Python. May also be beneficial to include a numpy installation in Evennia requirements given scipy uses it as a dependency and is auto-installed with it.

**Comment by jaborsh** [comment]
Changing `from scipy import zeros` to `from numpy import zeros` has resolved errors in my gamedir with Py 3.12 and Scipy 1.12, but I should note I haven't checked all of the contribs. I know XYZ contrib will need to be modified but I'm unsure about others.

**Comment by Griatch** [comment]
Looks like twisted iocpsupport support 3.12 now, so Twisted should work on Windows. So may update Evennia to support 3.12 (as well as this scipy version) in time for Evennia 4.0 release!

**Comment by Griatch** [comment]
This is fixed in main branch now, including adding support for Python 3.12.
