### ISSUE TITLE
[Feature Request] Add `Msg` lock access checks in `CmdPage`

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3450]
#### Is your feature request related to a problem? Please describe.
The `Msg` class is potentially very useful, especially with it having tags and locks available. However, the page command itself completely ignores any locks on the messages, which makes using `Msg` objects for anything besides pages a little tricky.

For a real-world example, I'm setting up to use `Msg` for my various submissions/reports systems. This works great - except, if I keep the default `page` command, every single `Msg` generated through any of these systems shows up *as a page*. Even if I set a lock on them like `"read:pperm(Developer)"`. This is not ideal; at the moment, I'm working around it by simply turning page off.

#### Describe the solution you'd like
I'd like for the page command to at least respect the `read` lock on messages before printing them out - especially since the [documentation for Msg](https://www.evennia.com/docs/latest/Components/Msg.html?highlight=locks#properties-on-msg) says the following:

> locks - the Evennia [lock handler](https://www.evennia.com/docs/latest/Components/Locks.html). Use with locks.add() etc and check locks with msg.access() like for all other lockable entities. This can be used to limit access to the contents of the Msg. The default lock-type to check is 'read'.

#### Additional thoughts
Ideally, pages would also tag messages as pages and filter on those tag checks, so that you can more easily disambiguate page Msg objects from non-page Msg objects, but that's more of a bonus suggestion. The fact of the current system completely ignoring locks is a much bigger issue.

**Comment by Griatch** [comment]
I implemented this in a backwards-compatible way by adding tags 'page' (category 'comms') to new msgs, but by also filtering/accept msgs with no tags (legacy pages). I also now check for the 'read' lock, but default this check to 'True' so that non-locked legacy pages are still available.
