### ISSUE TITLE
[Feature Request] Break DefaultObject visibility checks into its own method

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3461]
#### Is your feature request related to a problem? Please describe.
At the moment, all of the `get_display_<content type>` methods on DefaultObject and its descendants repeat the same internal helper method, like this:

https://github.com/evennia/evennia/blob/5fcccca7d1c93bc7ac0a64b3d4ee46fad1367960/evennia/objects/objects.py#L1593-L1594

This makes it a lot more difficult to add any kind of custom visibility mechanic to your game, as you have to entirely reimplement  `get_display_things`, `get_display_characters`, and `get_display_exits` (at minimum) in order to change visibility logic to something other than just the `view` lock.

#### Describe the solution you'd like
My suggestion would be to add a filter method to the typeclass itself. Here is how it might look to be used:

```py
    def get_display_things(self, looker, **kwargs):
        # filter things to only those visible to looker
        things = self.filter_visible_contents(looker, content_type="object")
```

#### Describe alternatives you've considered
I also considered breaking it out into a method on the viewer, but I think that would be better suited to something you check per object, rather than something used to filter down a list of things. Since the functionality here is specifically filtering the contents of an object for display, it makes the most sense to continue being on the object whose contents are being viewed.

**Comment by Griatch** [comment]
Fair enough - I can see the usefulness of a change like this.
