### ISSUE TITLE
[BUG] XYZ Contrib Attempted Double Spawning

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#3475]
#### Describe the bug
XYZ spawner will attempt to re-spawn an already spawned room due to the spawner checking for XYZRoom typeclass explicitly instead of anything that inherits from XYZRoom. 

From @Griatch: "The trick here is that the spawner needs to check for the full *family* of XYZRoom (including its children) to determine if it exists or not.  So - this looks to be an issue in the spawner itself.

#### To Reproduce
1. Set spawn room typeclass in node and in prototypes
2. Attempt spawn
3. See error

#### Expected behavior
After entry is created, spawner should seek to update instead of re-spawning something already spawned.

**Comment by Griatch** [comment]
@jaborsh The hunch I had about this didn't pan out, looks like the system is searching for the children of XYZRooms :thinking:

**Comment by jaborsh** [comment]
> @jaborsh The hunch I had about this didn't pan out, looks like the system is searching for the children of XYZRooms 🤔

I will try to reproduce using a fresh environment if you haven't done so already. It's possible there's some miscommunication happening on my end since I have the grid spawn/update `at_server_start`

**Comment by Griatch** [comment]
@jaborsh If you can give some simple example code to reliably reproduce, that would help :+1:

**Comment by jaborsh** [comment]
Marking this as closed. @InspectorCaracal believes the issue was due to calling `spawn()` twice, once with the intention to initialize and again with the intention to update, which is already functional with the built-in prototype system.
