### ISSUE TITLE
[Documentation] Discrepancy between code and explanation (tutorial)

### ISSUE THREAD

**Issue by chiizujin** [evennia/evennia#3478]
#### Existing page
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Characters.html

#### Documentation issue

In section *3.3. Character class*,  the code in the `at_death` function is:
```
self.location.msg_contents(
    "$You() collapse in a heap, embraced by death.",
    from_obj=self) 
```
But the explanation explains it as:
```
self.location.msg_contents(
    "$You() $conj(collapse) in a heap, alive but beaten.",
    from_obj=self)
```

**Comment by Griatch** [comment]
You seem to be looking at the wrong line. The example text describes the code in the `at_defeat` method, not in the `at_death` method. The `at_defeat` is the one with `conj()`.

**Comment by chiizujin** [comment]
You're right, my apologies.
