### ISSUE TITLE
[Documentation] Code typo in tutorial (4.2. The base object)

### ISSUE THREAD

**Issue by chiizujin** [evennia/evennia#3480]
#### Existing page
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Objects.html

#### Documentation issue
In the section *4.2. The base object*, the function definition for `get_display_desc` is missing its colon:
```
def get_display_desc(self, looker, **kwargs)
```

**Comment by Griatch** [comment]
Thanks for giving not only the file location but also the name of the section with the issue! :+1: Makes it a lot easier (the raw source doesn't have the numbering) :)
