### ISSUE TITLE
[BUG] New AttributeProperty mutable default tests fail in 3.11

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3492]
#### Describe the bug
As of commit b8e37f9cf27a012dafbed1fa8a01f3ab7fef1077 the python 3.11 integration tests appear to be failing on `test_mutables_are_not_shared_when_autocreate`

**Comment by Griatch** [comment]
Closed with use of `isNot` instead of `isNotEqual` in the test.
