### ISSUE TITLE
[BUG] EvMenu cmdset merge type does not behave as documented

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3546]
#### Describe the bug
The relevant portion of the docstring for `EvMenu` is as follows:
```
            cmdset_mergetype (str, optional): 'Replace' (default) means the menu
                commands will be exclusive - no other normal commands will
                be usable while the user is in the menu. 'Union' means the
                menu commands will be integrated with the existing commands
                (it will merge with `merge_priority`), if so, make sure that
                the menu's command names don't collide with existing commands
                in an unexpected way. Also the CMD_NOMATCH and CMD_NOINPUT will
                be overloaded by the menu cmdset. Other cmdser mergetypes
                has little purpose for the menu.
            cmdset_priority (int, optional): The merge priority for the
                menu command set. The default (1) is usually enough for most
                types of menus.
```

However, attempting to use a merge type of `"Union"` and a priority of `102` is NOT having the expected result - namely, I expect the menu's commands to be merged with higher priority than all other commands, and for the rest of the commands to otherwise be available. Instead, it seems to be highly unreliable which of the versions you're going to get.

#### To Reproduce
1. Start an EvMenu with a character caller, Union merge type and a priority of 102. I used the character creator menu with `py` in-game for convenience: `py from evennia.utils.evmenu import EvMenu; EvMenu(self, 'evennia.contrib.rpg.character_creator.example_menu', startnode="menunode_welcome", cmdset_mergetype="Union", cmdset_priority=102)`
2. Try using the default commands that conflict with built-in commands, e.g. q, quit, l, look
3. See error

#### Expected behavior
I expected the menu's versions to override the built-in versions

#### Environment, Evennia version, OS etc
Evennia 4.1.1, and Evennia 3.2.0
Python 3.11.2
Debian 12

#### Additional context
Here is the annotated log from the steps outlined in my reproduction instructions:

(note: for this testing, I manually assigned `self.new_char = self` so that the second menu node would function)

- I initiate the menu - it's immediately obvious that something isn't right, because it shows the "look" results for both the room I'm in AND the first menu node, without any commands.
```
> py from evennia.utils.evmenu import EvMenu; EvMenu(self, 'evennia.contrib.rpg.character_creator.example_menu', startnode="menunode_welcome", cmdset_mergetype="Union", cmdset_priority=102)
>>> from evennia.utils.evmenu import EvMenu; EvMenu(self, 'evennia.contrib.rpg.character_creator.example_menu', startnode="menunode_welcome", cmdset_mergetype="Union", cmdset_priority=102)
Limbo(#2)
Welcome to your new Evennia-based game! Visit https://www.evennia.com if you need
help, want to contribute, report issues or just join the community.
As a privileged user, write batchcommand tutorial_world.build to build
tutorial content. Once built, try intro for starting help and tutorial to
play the demo game.
You see: a rock
______________________________________________________________________________

Welcome to Character Creation!

This is the starting node for all brand new characters. It's a good place to
remind players that they can exit the character creator and resume later,
especially if you're going to have a really long chargen process.

A brief overview of the game could be a good idea here, too, or a link to your
game wiki if you have one.
______________________________________________________________________________

 1: Let's begin!        
```

- I then try using the alias for look, `l` - it shows the room I'm in and *not* the menu node.
```
> l
Limbo(#2)
Welcome to your new Evennia-based game! Visit https://www.evennia.com if you need
help, want to contribute, report issues or just join the community.
As a privileged user, write batchcommand tutorial_world.build to build
tutorial content. Once built, try intro for starting help and tutorial to
play the demo game.
You see: a rock
```

- I then enter the number `1` to select the one option and it proceeds to the next node, proving that the menu *is* there and functional.
```
> 1
______________________________________________________________________________

Informational Pages

Sometimes you'll want to let players read more about options before choosing
one of them. This is especially useful for big choices like race or class.
______________________________________________________________________________

 1: Learn about the warrior class  
 2: Learn about the mage class     
```

- Finally, I enter the `q` alias to quit. It appears to sucessfully quit the menu and do the post-menu auto-look.
```
> q
Limbo(#2)
Welcome to your new Evennia-based game! Visit https://www.evennia.com if you need
help, want to contribute, report issues or just join the community.
As a privileged user, write batchcommand tutorial_world.build to build
tutorial content. Once built, try intro for starting help and tutorial to
play the demo game.
You see: a rock
```
- I confirm this by again entering `1` and getting the expected "command not found" error.
```
> 1
Command '1' is not available. Type "help" for help.
```

- I initiate the menu again, the same way. This second time, however, it only shows the menu node's text, not the room.
```
> py from evennia.utils.evmenu import EvMenu; EvMenu(self, 'evennia.contrib.rpg.character_creator.example_menu', startnode="menunode_welcome", cmdset_mergetype="Union", cmdset_priority=102)
>>> from evennia.utils.evmenu import EvMenu; EvMenu(self, 'evennia.contrib.rpg.character_creator.example_menu', startnode="menunode_welcome", cmdset_mergetype="Union", cmdset_priority=102)
______________________________________________________________________________

Welcome to Character Creation!

This is the starting node for all brand new characters. It's a good place to
remind players that they can exit the character creator and resume later,
especially if you're going to have a really long chargen process.

A brief overview of the game could be a good idea here, too, or a link to your
game wiki if you have one.
______________________________________________________________________________

 1: Let's begin!        
```

- I attempt to use the full "quit" command key, rather than the "q" alias which worked to exit the menu last time. It disconnects me from the entire game.
```
> quit
Quitting. Hope to see you again, soon.
[MudInfo] [2024-05-22(04:03)]: admin disconnected (quit)
The connection was closed or lost.
```

**Comment by InspectorCaracal** [comment]
On further assessment, it turns out that "q" is not an alias for "quit" outside of EvMenu, so that was a red herring.

It seems as though the cmdsets are being merged, but none of the commands except for "no match" and "no input" are ever taking priority, regardless of the `cmdset_priority` value.

I believe this is likely related to the fact that the existing function that seems to exist to make this happen - `CmdEvMenuNode._update_aliases` - is never called. All prior uses of it have been commented out.

**Comment by Griatch** [comment]
@InspectorCaracal This works as expected, and the documentation does lay it out explicitly - "make sure the menu's commands don't collide with the other commands in an unexpected way". I can see why the use of 'merge with merge priority' would make you think that this is a normal cmdset merge though. I'll clarify this. 

The respective actions in the EvMenu are not separate commands. The EvMenu has only one Command, and that has the `_CMD_NOINPUT` key with `_CMD_NOMATCH` as an alias. So when you use Union with a prio of 102, you make sure that noinput/nomatch always go to the menu, but all other commands are working normally. There is no way to "partly" replace normal commands with EvMenu inputs.
