### ISSUE TITLE
[Documentation] Issue in 11.1 related to "BaseCommand"

### ISSUE THREAD

**Issue by Lokius42** [evennia/evennia#3555]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Searching-Things.html

#### Documentation issue
In this section an example command is provided and it is suggested that the reader can implement by simply adding to command.py and then to default_cmdsets.py

That suggestion includes the following lines:
"
from evennia import Command

class CmdQuickFind(Command):
    """ 

"

If a reader has followed all previous steps (specifically 8.1) then earlier they will already have added a line at the top of command.py that reads:

"from evennia import Command as BaseCommand"

This means to get the quickfind to work they will need to update "Command" to "BaseCommand"

#### Suggested change
I suggest the documentation be updated to include the BaseCommand language as I think most users will have followed that earlier in the tutorial:

https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Adding-Commands.html

**Comment by InspectorCaracal** [comment]
That's a good catch

I believe the right way to correct this, however, would be for the guide to give a different file name to put the new command in, rather than the same file as with the in-game command, and the inheritance line to be inheriting from the Command class provided in the gamedir itself.

**Comment by Griatch** [comment]
It's indeed the default look of the command.py module. I think it can be useful to test out adding stuff to the default command.py module too, so I fixed it up and explained how it relates to the default.
