### ISSUE TITLE
[BUG] AttributeError can be raised in ObjectDB.init child classes

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#3556]
#### Describe the bug
A friend who came to me to help debug an issue had changed the name of a typeclass, but the fallback failed here in the `init()` method of ObjectDB:
```
    def init(self):
        """
        Re-initialize the content cache

        """
        objects = self.load()
        self._pkcache = {obj.pk: True for obj in objects}
        for obj in objects:
            for ctype in obj._content_types:  # <--- This raised AttributeError
                self._typecache[ctype][obj.pk] = True
 ```

`_content_types` isn't defined in ObjectDB, and only its subclasses. I don't know exactly how it happened, but she had objects in her database that didn't match one of those subclasses, so it raised an AttributeError on `init()` due to missing `_content_types`.

#### To Reproduce
1. ObjectDB that has a typeclass that somehow doesn't inherit from one of the Default typeclasses
2. Have it set its location to another object
3. Instantiate that location

#### Expected behavior
No error when `init()` is called, regardless of its typeclass

#### Environment, Evennia version, OS etc
Believe she's using the latest version, but not sure

#### Additional context
Add `_content_types = ("object,")` to ObjectDB

**Comment by Griatch** [comment]
@TehomCD Did she change the name of the Typeclass after already having created objects with the old typeclass? Entities in Evennia store the typeclass as a class path on the object. If this goes out of sync (there no longer is a typeclass with that name at that location) you'd end up in trouble. Maybe that's what happened here?

**Comment by TehomCD** [comment]
I think that might be likely as the root cause for why it fell back to ObjectDB, but I can't confirm that since the only thing shared was the traceback and a rough outline of the sequence of events (working on an object, now my game won't start, etc). My feeling is that even if it's a difficult error to replicate, it might still be a good idea to add `_content_types = ("object",)` to `ObjectDB` to prevent further errors if they mess up one of their typeclasses.

**Comment by Griatch** [comment]
We can't set `_content_types` on `ObjectDB` since it doesn't have any of the functionality needed; such as an inventory handler. Setting it would resolve the particular error but only cause confusing errors down the line. 

What I did instead is to bypass the contents cache creation and log the `AttributeError` with a more descriptive error message that should hopefully better help identify what the problem is.
