### ISSUE TITLE
[Documentation] Incorrect lock types listed for help entries

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3562]
#### Existing page / new
[Locks - Valid access types](https://www.evennia.com/docs/latest/Components/Locks.html#valid-access-types)

#### Documentation issue
The page lists "examine" as the readability access type for help entries, but in fact it uses "read". It also doesn't include the "view" lock for inclusion in the help index.

**Comment by Griatch** [comment]
Good catches!
