### ISSUE TITLE
[BUG] Command help for commands starting with * does not display

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#3564]
#### Describe the bug

Certain commands whose names begin with * are unsearchable via in-game help. It's not obvious what the pattern is for the names that work and the names that don't.

Known broken command names:
*examine
*link
*shortcode

For example, this basic command, intended to override the built-in command of the same name, triggers the bug:

```py
class CmdExamine(building.CmdExamine):
    """
    Override of the default Examine command to change the command key.
    """

    __doc__ = building.CmdExamine.__doc__

    key = "*examine"
    aliases = ["*exam", "*ex", "@examine"]
```

When running `help *examine`, the following output is observed:
```
> help *examine
No help found

There is no help topic matching '*examine'.
... But matches were found within the help texts of the suggestions below.

Other topic suggestions:
*examine
```

After some debugging with @InspectorCaracal , it appears to have been broken sometime around evennia 4.1.0. It worked properly in previous versions, so it looks like a recent regression. Reproducible in an vanilla install.

#### To Reproduce
1. Sync to main:HEAD
2. Add the command above to the default CharacterCmdSet (it should override the built-in command).
3. help *examine

#### Expected behavior
Help works properly for this command.

#### Environment, Evennia version, OS etc
         Evennia version: 4.1.1
         OS: posix
         Python: 3.10.5
         Twisted: 23.10.0
         Django: 4.2.8

Git commit hash: 3b84ec1b42 (Should be HEAD or close to it)

#### Additional Context
The bug is not reproducible if the command is ONLY named `*examine` and doesn't have the `@examine` alias. I don't know why.
`*` is not in my command ignore prefixes setting.

**Comment by Griatch** [comment]
My first guess is that * has a special meaning for the Lunr search engine used for in-game search lookup. I recall we did have a Lunr fix some time ago (like https://github.com/evennia/evennia/pull/3457) , maybe that had this as a side effect :thinking:
