### ISSUE TITLE
Feature suggestion: PyPi package.

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#361]
_From [Kelketek](https://code.google.com/u/Kelketek/) on May 10, 2013 02:43:09_

 Evennia needs some changes to be included in the PyPi index. It should be possible to do:

```
pip install evennia
evennia-project newproject defaults
```

...and have everything installed, and an Evennia installation deployed. This means:
1. Easier deployment. A MUD server which can be deployed in two commands is very compelling and is more likely to attract people who are interested in the project. Template settings.py files and initial data could allow for easy full demonstrations.
2. Pip allows for quick and easy creation of standard packages, such as .debs and .rpms. This would allow for Evennia to be included as part of an OS's repository, further increasing its reach and flexibility.
3. Changes could be rolled out in more stable releases as we start to get finished servers. C) If you have any suggestions on the best way to implement this new feature, write those ideas below. I've done this for a similar project and can do so again. I'll be happy to start work on it once #343 is completed.

_Original issue: http://code.google.com/p/evennia/issues/detail?id=361_

**Comment by ahmedcharles** [comment]
Just curious, are there currently any showstoppers that would prevent doing this?

**Comment by Griatch** [comment]
Going to a pypi release package puts (IMO) some extra requirements on a library. The current roadmap towards implementing this is covered in [our roadmap](https://github.com/evennia/evennia/wiki/Roadmap).

**Comment by Griatch** [comment]
The sub-progress of implementing this is now covered and up-to-date as this [Github Project](https://github.com/evennia/evennia/projects/4).

**Comment by Griatch** [comment]
Through `evennia` 1.0rc9, this is now implemented and available for testing; so this old ticket can finally close!
