### ISSUE TITLE
[BUG] Catastrophic game crash involving `CmdPy` and `print`

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3615]
#### Describe the bug
When using `print` with an overloaded `msg` function for debugging, using the `py` command in-game will cause a catastrophic failure due to infinite recursion - `print` will attempt to write to stdout, which has been replaced by `caller.msg`, which will then attempt to `print`, which will attempt to write to stdout, etc.

I realize this is a slightly niche situation, but it is extremely unintuitive, frustrating, and difficult to debug when it does occur.

#### Environment, Evennia version, OS etc
Evennia 4.3.0

**Comment by Griatch** [comment]
Fixed by catching the RecursiveError and outputting an error message instead.
