### ISSUE TITLE
[BUG] `color ansi` output has been rendered useless 

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3616]
#### Describe the bug
Most of the dark colors are missing, and codes were added which the webclient parser doesn't actually support as well as codes that appear to do nothing.

Output on webclient:
![image](https://github.com/user-attachments/assets/519c6c41-6d29-4c64-be9d-69e7401eba64)

Output in Mudlet:
![image](https://github.com/user-attachments/assets/6de4ef90-82b1-45fe-b311-80386fa32922)

#### To Reproduce
1. create a fresh game and log in to either client
2. enter `color ansi`
3. See error

#### Expected behavior
This needs to actually print out all the basic ansi-16 color codes, and codes that are not actually fully supported by evennia should not be included. The italics and strikethroughs should either be properly implemented into the html parser or removed. The |U and |I markers appear entirely non-functional and have no purpose existing.

If the italics and strikethroughs are ultimately included by supporting them in the webclient, they should be in the section with the formatting codes, with textual explanations like the others so that it is clear on clients that do not support them. They **should not** be replacing the color codes in the color table.

#### Environment, Evennia version, OS etc
Evennia 4.3.0

#### Additional context

Here are the respective outputs on the previous version, 4.2.0

Webclient:
![image](https://github.com/user-attachments/assets/aee1b09f-c68b-4447-a70f-20dae9d8f2b6)

Mudlet:
![image](https://github.com/user-attachments/assets/dde40b8f-0b70-4d56-8398-0725de4d16ce)

As you can see, *previously*, this command did in fact include all 16 colors, the color codes were organized in a meaningful manner instead of scattered in random places, and nothing appears broken on the built-in webclient.

**Comment by Xinefus-Braska** [comment]
In `help color` it clearly states that no checks [negotiations?] Are done to confirm if the client supports the color methods...

I thought there was a standard for 'most' telnet clients on how to negotiate colour, OOB, etc. 

IMHO, the included webclient should hopefully support all baked-in items?

**Comment by InspectorCaracal** [comment]
> In `help color` it clearly states that no checks [negotiations?] Are done to confirm if the client supports the color methods...
> 
> I thought there was a standard for 'most' telnet clients on how to negotiate colour, OOB, etc.
> 
> IMHO, the included webclient should hopefully support all baked-in items?

Yes, exactly. The built-in webclient SHOULD support all evennia markup, but several markup codes have apparently been added without adding the associated webclient support. 

These new codes were also added without explanations of what they are supposed to do.

They ALSO are replacing almost half of the ANSI-16 colors that are supposed to be in this color test chart.

Whether or not other third-party clients support these codes isn't the issue here.

**Comment by InspectorCaracal** [comment]
For additional clarity of context and to better demonstrate what exactly the issue is, I have revised the original post to include screenshots of the output I receive on the webclient and Mudlet when using Evennia 4.2.0

**Comment by Griatch** [comment]
Oops, closed this by accident with a typo in commit message.

**Comment by Griatch** [comment]
Confirmed. My guess is that his is a regression from the latest changes to ansi.py.

**Comment by Griatch** [comment]
The issue was in the `color ansi` command, it grabs colors to display based on their index in the ansi color code list, and those indices had not kept up with new ansi codes being added. The strikethroug/underline |s and |u (and their ANSI reset counterparts |U and |S) are not supported on the webclient. I added that to the docs to be clear.
