### ISSUE TITLE
[Feature Request] Allow simple customization of default object descriptions

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#3617]
#### Is your feature request related to a problem? Please describe.

When creating a new object, the object's `create` method sets a default description (such as "You see nothing special." for Objects and "This is an exit." for exits) if no description is provided to the call. These descriptions are hard-coded into the `create` methods and are not easy to change without copy/pasting the entire method for each object type in order to override it. In addition, these strings are slightly opinionated and should be more easily customizable.

#### Describe the solution you'd like

Define the default description for an object as a class variable on the relevant typeclass, and change object `create` methods to refer to that variable instead, similar to how object appearance templates are now done. In addition, explicitly permit an empty/None description rather than always falling back to the default. This makes customization easy and no one needs to re-implement `create` methods in order to change the default desc.

For example:

```py
class DefaultExit:
    default_description = "This is an exit."

# In DefaultObject.create
  desc = description if description is not None else cls.default_description
```

#### Describe alternatives you've considered
Fallback strings used to be display-only, where if no desc was set, the string was returned when someone looked at it. This allowed one to change the default by overriding the desc method, which could also work here. But I think providing the customization option is a better approach overall and fits with the general direction we've been taking for these kinds of customizations.

**Comment by InspectorCaracal** [comment]
I'd like to add that while I am fully behind the idea of setting the fallback string on the class - similarly to the appearance template - I would prefer that the default `create` method simply not set the `desc` attribute at all if it's not provided. Objects would be created without any desc value by default, the way they were previously, and the default `get_display_desc` method would then be this:

```py
    def get_display_desc(self, looker, **kwargs):
        """
        ...
        """
        return self.db.desc or self.default_description
```

instead of this:
```py
    def get_display_desc(self, looker, **kwargs):
        """
        ...
        """
        return self.db.desc or "You see nothing special."
```

**Comment by Griatch** [comment]
This is a good idea, should be easy to add.
