### ISSUE TITLE
[BUG] AMP caught exception on attribute that is no longer relevant

### ISSUE THREAD

**Issue by Panzerbyte** [evennia/evennia#3620]
#### Describe the bug
This bug is odd, as I changed my Character typeclass a little bit, introduced an attribute called 'needs_decay' into it, and then later remove it once again, it still persists after having completely reloaded the server, updated my (and the only) character on the server to the 'needs_decay'-less version.

#### To Reproduce
1. Introduce an attribute
2. ?
3. ????

#### Expected behavior
As the Character typeclass does no longer have any reference nor function to 'needs_decay', it still comes up!

#### Environment, Evennia version, OS etc
Windows 10, latest Evennia pip version upon writing.

#### Additional context
Here's the error:

> 2024-09-20 21:41:23 [..] Loaded.
> 2024-09-20 21:41:21 [..] Loading C:\muddev\evenv\Lib\site-packages\evennia\server\server.py...
> 2024-09-20 21:41:23 [..] Loaded.
> 2024-09-20 21:41:23 [..] twistd 23.10.0 (C:\muddev\evenv\Scripts\python.exe 3.12.6) starting up.
> 2024-09-20 21:41:23 [..] reactor class: twisted.internet.selectreactor.SelectReactor.
> 2024-09-20 21:41:23 [..] Webserver starting on 4005
> 2024-09-20 21:41:23 [..] Server successfully reloaded.
> 2024-09-20 21:41:23 [EE] AMP caught exception ('Character' object has no attribute 'needs_decay' (error logged on other side)):
> 2024-09-20 21:41:23 [EE] Code<EXCEPTION> (local): 'Character' object has no attribute 'needs_decay'
> 2024-09-20 21:41:23 [EE] Traceback: <class 'AttributeError'>: 'Character' object has no attribute 'needs_decay'
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\evennia\server\portal\amp.py:356:_commandReceived
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\twisted\protocols\amp.py:1067:dispatchCommand
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\twisted\internet\defer.py:209:maybeDeferred
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\twisted\protocols\amp.py:1161:doit
> 2024-09-20 21:41:23 [EE] --- <exception caught here> ---
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\twisted\internet\defer.py:209:maybeDeferred
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\evennia\server\amp_client.py:234:server_receive_adminportal2server
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\evennia\server\sessionhandler.py:415:portal_sessions_sync
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\evennia\server\service.py:651:at_post_portal_sync
> 2024-09-20 21:41:23 [EE] C:\muddev\evenv\Lib\site-packages\evennia\scripts\taskhandler.py:254:load
>

**Comment by InspectorCaracal** [comment]
Based on the error, it appears you had a ticker or a persistent delay that referred to this attribute on the character, and so when trying to unpickle the task to run it, it errors and fails out of the process. You'll need to add the attribute back to allow the task to load; if it's a single-time delay it should clean itself up, but if it's a ticker you'll need to cancel it before removing the attribute again.

**Comment by Panzerbyte** [comment]
Interesting, it was a delay indeed! What'd be the cleanest way to clear this error out if you do not mind me asking?

**Comment by InspectorCaracal** [comment]
> Interesting, it was a delay indeed! What'd be the cleanest way to clear this error out if you do not mind me asking?

Add the attribute back, then let the delayed task load and either complete or be cancelled.

**Comment by Panzerbyte** [comment]
I tried for a couple of hours, and decided to delete the .db3 and `evennia migrate` instead.

**Comment by Griatch** [comment]
It have now extended the TaskHandler to cleanly remove that task if it fails to load instead of keep looking for it (and failing).
