### ISSUE TITLE
[BUG] Ingame Reports contrib throws error on help command

### ISSUE THREAD

**Issue by Panzerbyte** [evennia/evennia#3627]
#### Describe the bug
I am not sure whether this is tied to the Ingame Reports contrib at all, but it did give an error upon just installing the contrib and typing in `help manage` (`manage reports` is a command for instance).

#### To Reproduce
1. Install Ingame Reports contrib
2. Run command `help manage`
3. See error

#### Expected behavior
Should have given a help file on the manage players or manage bugs commands.

#### Environment, Evennia version, OS etc
Evennia 4.4.0, Windows 10.

#### Additional context
Here is the traceback log:

> 2024-09-29 16:26:42 [!!] Traceback (most recent call last):
> 2024-09-29 16:26:42 [!!]   File "C:\muddev\evenv\Lib\site-packages\evennia\commands\cmdhandler.py", line 629, in _run_command
> 2024-09-29 16:26:42 [!!]     ret = cmd.func()
> 2024-09-29 16:26:42 [!!]           ^^^^^^^^^^
> 2024-09-29 16:26:42 [!!]   File "C:\muddev\evenv\Lib\site-packages\evennia\commands\default\help.py", line 697, in func
> 2024-09-29 16:26:42 [!!]     help_text = match.get_help(caller, cmdset)
> 2024-09-29 16:26:42 [!!]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-09-29 16:26:42 [!!] TypeError: CmdManageReports.get_help() takes 1 positional argument but 3 were given
> 2024-09-29 16:26:42 [EE] User input was: 'help manage'.
> 2024-09-29 16:26:46 [!!] Traceback (most recent call last):
> 2024-09-29 16:26:46 [!!]   File "C:\muddev\evenv\Lib\site-packages\evennia\commands\cmdhandler.py", line 629, in _run_command
> 2024-09-29 16:26:46 [!!]     ret = cmd.func()
> 2024-09-29 16:26:46 [!!]           ^^^^^^^^^^
> 2024-09-29 16:26:46 [!!]   File "C:\muddev\evenv\Lib\site-packages\evennia\commands\default\help.py", line 697, in func
> 2024-09-29 16:26:46 [!!]     help_text = match.get_help(caller, cmdset)
> 2024-09-29 16:26:46 [!!]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-09-29 16:26:46 [!!] TypeError: CmdManageReports.get_help() takes 1 positional argument but 3 were given
> 2024-09-29 16:26:46 [EE] User input was: 'help manage players'.
>

**Comment by aMiss-aWry** [comment]
I'm pretty sure the problem here is that https://www.evennia.com/docs/latest/_modules/evennia/contrib/base_systems/ingame_reports/reports.html#CmdManageReports.get_help

>def get_help(self):

needs to be

>def get_help(self, caller, cmdset):

@InspectorCaracal - I think this is your contrib, thoughts?

**Comment by InspectorCaracal** [comment]
Yep that's pretty obviously the cause, mb
