### ISSUE TITLE
[BUG] Weird, inconsistent behavior from contents cache handler

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3646]
#### Describe the bug
On my live Evennia game, since I updated to 4.4.1 recently, I've been getting periodic very strange behavior from the contents cache where it thinks non-character things are characters in the room.

Here is an example of what happens in an affected room.

Examining the room (with unrelated output cropped)
```
ex here
------------------------------------------------------------------------------
Name/key: Wilderness (#1761)
Typeclass: OverworldRoom (typeclasses.rooms.OverworldRoom)
Exits: north(#1762), northeast(#1763), east(#1764), southeast(#1765), south(#1766), southwest(#1767), west(#1768), northwest(#1769)
Characters: Cal(#103)
Content: patch of wheat(#14578)
------------------------------------------------------------------------------
```
In-game `py` commands and output inspecting the output of various commands and contents cache:
```py
>>> here.contents_get(content_type='character')
[Cal, north, northeast, east, southeast, south, southwest, west, northwest, patch of wheat]
>>> print(','.join([f"{obj.key}#{obj.id}" for obj in here.contents_get(content_type='character')]))
Cal#103,north#1762,northeast#1763,east#1764,southeast#1765,south#1766,southwest#1767,west#1768,northwest#1769,patch of wheat#14578
>>> print(here.contents_cache._typecache)
defaultdict(<class 'dict'>, {'exit': {1762: True, 1763: True, 1764: True, 1765: True, 1766: True, 1767: True, 1768: True, 1769: True}, 'object': {14578: True}, 'character': {14575: True, 103: True}, 'player': {103: True}})
>>> print(here.contents_cache.get(content_type='character'))
[Cal, north, northeast, east, southeast, south, southwest, west, northwest, patch of wheat]
>>> print(here.contents_cache._typecache['character'].keys())
dict_keys([14575, 103])
```

In another case which I don't have a record of to share, it was returning an ordinary object as one of the room's characters that wasn't even *in* the room.

#### To Reproduce
I have not yet been able to intentionally reproduce this behavior. :(

#### Expected behavior
The `contents_cache.get` function should be just returning the objects under that key.

#### Environment, Evennia version, OS etc
Evennia 4.4.1, Debian 12, Python 3.11, using MariaDB database backend

#### Additional context

So far, this has only happened in Wilderness rooms, but since I don't have reliable reproduction steps I can't confirm that it *wouldn't*. Most of the rooms in this game are part of a wilderness.

**Comment by count-infinity** [comment]
What is, and where is object 14575.  Currently listed as a 'character'?
What is in `here.contents_cache._idcache`? Is 14575 in there?
In error logs do you happen to see something like "contents cache failed for..."?

**Comment by InspectorCaracal** [comment]
...I can't check the logs right now but I think you're on to something and I think I may have an idea how this is happening. If I'm right, Iwill be able to reproduce it and it'll officially be my fault, rip. 😂 

I'll check tomorrow and hopefully be able to close this then.

**Comment by InspectorCaracal** [comment]
Welp. The only remaining mystery here is how I never ran across this issue in local testing. It's a result of me doing somewhat... unintended things with Evennia's systems, and the fact that `contents_cache.init` doesn't actually reinitialize the typecache.

For posterity, here is what happened:

- I have a special type of NPC which, when you catch it, transforms into an object.
- The NPC starts out with a content type of 'character' and is cached in the contents under that key.
- The NPC transforms. Its content type *changes* 'object'. *The contents cache is not changed.*
- The object is moved out of the room. The contents cache handler sees that it is of the 'object' type and updates its 'object' typecache. It is not a 'character' type, so it does not update its character cache.
- The object is now forever (or at least until server reload) stuck as a "ghost" in the typecache, because `init` and `load` do not *clear out* anything from the typecache, meaning nothing will ever remove the no longer valid entry.
- If the object still exists, it just shows up as a "ghost" in the Characters list. If the object has been deleted, it causes the fallback to returning all of the items from `load()`

Most of this is my fault for doing weird things, but I do think that it highlights some potential issues in the contents cache not properly reinitializing its internal cache in case of issues, so I'll be leaving this open for the moment and putting in a PR to fix those.
