### ISSUE TITLE
[Documentation] (Documentation does not match what is in the python file, 5.2.4)

### ISSUE THREAD

**Issue by BurrowsForge** [evennia/evennia#3661]

**Comment by BurrowsForge** [comment]
It looks like this is all blank even though I added a lot of text. Not sure why that is, but that is frustrating.

Here is what I found:

On the documentation for the tutorial, located here:

https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Python-classes-and-objects.html

It says on section 5.2.4:
```
"""
module docstring
"""
from evennia import DefaultObject

class ObjectParent:
    """
    class docstring 
    """
    pass

class Object(ObjectParent, DefaultObject):
    """
    class docstring
    """
    pass
```
    
    
    the first pass does not seem to match what is in my objects.py file. I only have 1 pass and it is at the end of class Object(ObjectParent, DefaultObject):
    
    I'm too inexperienced with python to know what not having a pass here means or if this matters or not, but the tutorial explains this section like there are two passes, and there is only one. I'd recommend either adding a pass here or more likely removing that section that discusses a pass in Class ObjectParent from the tutorial because it's confusing.

**Comment by jaborsh** [comment]
In [Game Template's ObjectParent](https://github.com/evennia/evennia/blob/f0071998780096bec0b43682835d1fd72f907651/evennia/game_template/typeclasses/objects.py#L14) there is not a pass at the end of `ObjectParent` while the above doc link has one.

Not sure if Griatch wants to fix this or not. @BurrowsForge the pass operation can, for the sake of simplicity, just be thought of as marking the end of a class that doesn't have custom modification. For the sake of what's discussed in the tutorial, the `pass` operation is insignificant. Both the doc and the game code will work equivalently regardless of pass not being present within the code itself. Don't be confused. The discrepancy here can be safely ignored for the purposes of the tutorial. :)
