### ISSUE TITLE
[Documentation] Tutorial 11.1 says self.search doesn't work on multiple items but it does.

### ISSUE THREAD

**Issue by BurrowsForge** [evennia/evennia#3674]
#### Existing page / new
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Searching-Things.html
#### Documentation issue
The documentation states that the .search method on objects "It will always return exactly one match. If it found zero or more than one match, the return is None. This is different from evennia.search (see below), which always returns a list."

I tried the example with create/drop rose

py self.search("rose")
rose

I then created a second rose and tried the command again
>>> self.search("rose")
More than one match for 'rose' (please narrow target):
 rose-1
 rose-2

According to the documentation, this should not work.
"On a no-match or multimatch, .search will automatically send an error message to obj. So you don’t have to worry about reporting messages if the result is None."

#### Suggested change
I'm not sure how to fix this but the documentation should probably match what happens. Maybe this was updated to act like evennia.search?

**Comment by BurrowsForge** [comment]
I don't know why it never shows what I put in this page but I started copying it before submitting, so hopefully this shows up:

#### Existing page / new


#### Documentation issue


#### Suggested change

**Comment by InspectorCaracal** [comment]
The text message you received there is this part:
> On a no-match or multimatch, .search will automatically send an error message to obj.

You are the obj doing the search here, so you are receiving the message.
