### ISSUE TITLE
Feature Request:  Prototype(<object> = KEY, <filename=optional.py>)

### ISSUE THREAD

**Issue by Antrare** [evennia/evennia#561]
This command would output to the screen (or optionally append to filename=?) a correct (useable) prototype string generated from a created object from inside the game.

This enables people to create/customise an object however they want in the game, then create a prototype simply.

**Comment by Griatch** [comment]
No further feedback for this. I believe this might be interesting if someone made as a contrib, but it's not something for core. Closing.
