### ISSUE TITLE
__all__ package problem

### ISSUE THREAD

**Issue by haliphax** [evennia/evennia#618]
I've been trying to organize my various Room subtypes into a package, and keep each class in its own file for compartmentalization. However, when I attempt to dig a new room of one of these subtypes, I get `AttributeError: 'NoneType' object has no attribute 'locks'`.

Here's my setup:
* `game/gamesrc/objects/rooms` is the package
* `game/gamesrc/objects/rooms/chargen.py` is my Character Generation room type (ChargenRoom)
* `game/gamesrc/objects/rooms/__init__.py` exposes the ChargenRoom type

Here's my `__init__.py`:
```
from chargen import ChargenRoom
__all__ = ['ChargenRoom']
```

My dig command is:
```
@dig Character Generation:game.gamesrc.objects.rooms.ChargenRoom = chargen,finish
```

It doesn't actually fail to load the class, as I've seen that error before when I've typoed the class name, etc. -- it just gives me the 'locks' error. I can successfully import the ChargenRoom class outside of Evennia in IPython as such:
```
from game.gamesrc.objects.rooms import ChargenRoom
```
and:
```
import game.gamesrc.objects.rooms.ChargenRoom
```

This dig command works, as of course it should, but is a bit redundant and completely removes the package from the equation (notice that it's `rooms.chargen.ChargenRoom` instead of `rooms.ChargenRoom`):
```
@dig Character Generation:game.gamesrc.objects.rooms.chargen.ChargenRoom = chargen,finish
```

This isn't a deal-breaker for me, as I can certainly use the more verbose name and forgo the use of a package, but that is less than ideal. It seems like the package method should work.

Note: I have also tried using 'myrooms' as the package name instead of 'rooms', on the off-chance that there was some strange conflict going on. No dice.

Love the engine, though; keep up the awesome work!

Edit: Here's the full error:
```
Error creating Character Generation (game.gamesrc.objects.rooms.ChargenRoom).

Traceback (most recent call last):
  File "/home/haliphax/code/python/evennia/src/commands/cmdhandler.py", line 412, in cmdhandler
    ret = yield cmd.func()
  File "/home/haliphax/code/python/evennia/src/commands/default/building.py", line 642, in func
    new_room.locks.add(lockstring)
AttributeError: 'NoneType' object has no attribute 'locks'

Above traceback is from an untrapped error. Please file a bug report.
```

**Comment by Griatch** [comment]
Won't explore this further in master. The devel-branch folder structure has changed so that any change in master might be invalid in devel anyway. This issue will be closed when devel merges, possibly to be re-opened if the problem persists.

**Comment by haliphax** [comment]
I'll double check it after the merge.

**Comment by Griatch** [comment]
Closed as mentioned earlier.
