### ISSUE TITLE
mxp_send in EvTable

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#625]
This is NOT working.

```python
bbtable.add_row(mxp_send(board.num,"+bbread %s" % board.num), acc, mxp_send(board,"+bbread %s" % board.num), board.last_post(), board.posts.all().count())

def mxp_send(text="", command=""):
    if text:
        return "{lc%s{lt%s{le" % (command, text)
    else:
        return "{lc%s{lt%s{le" % (command, command)
```

I have confirmed that the problem is EvTable. it's stripping out the MXP somewhere - it looks like it's involved with ANSIString but I'm not sure how exactly.

If the problem is 'splitting text across multiple lines' then I would easily accept having only the first line's text be clickable. every single wrapped character doesn't need it. The tables I use that implement this would generally not wrap anyways.

On that note, is there any chance of getting the MXP features for sending weblinks or SEND MENUS working?

**Comment by Griatch** [comment]
MXP works in tables, but there is currently a lingering issue with the length of the cell content being one character off compared to the borders. So not closing this yet.

**Comment by Griatch** [comment]
Closing this and split the remainder of this issue into a Feature request, see #704.
