### ISSUE TITLE
Bug: src.utils.create.create_player not setting permissions

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#631]
```python
        new_player.basetype_setup()  # setup the basic locks and cmdset
        # call hook method (may override default permissions)
        new_player.at_player_creation()

        # custom given arguments potentially overrides the hook
        if permissions:
            new_player.permissions.add(permissions)
        elif not new_player.permissions:
            new_player.permissions.add(settings.PERMISSION_PLAYER_DEFAULT)
        if locks:
            new_player.locks.add(locks)
        return new_player
```

This is the current setup.

if permissions = None, then 'if permission's fails.
Then it moves on to elif not new_player.permissions and here is where things get sticky.
new_player.permissions returns the PERMISSIONSHANDLER, which is itself considered true. So it then does not go on to add the default permissions...

This likely has not yet been an issue because the create command in the unloggedin cmdset explicitly calls settings.PERMISSION_PLAYER_DEFAULT so permissions is not empty by this point.

My own 'wrapper' depended on the default creation settings though and the result is that permissions are not being set. Of course I can tweak my 'make player wrapper' a tad to solve this on my end, but this seems like a bug to me.

Proposed solution: have it use the .all() method to call the list. an empty list is boolean false, so...

```python
        new_player.basetype_setup()  # setup the basic locks and cmdset
        # call hook method (may override default permissions)
        new_player.at_player_creation()

        # custom given arguments potentially overrides the hook
        if permissions:
            new_player.permissions.add(permissions)
        elif not new_player.permissions.all():
            new_player.permissions.add(settings.PERMISSION_PLAYER_DEFAULT)
        if locks:
            new_player.locks.add(locks)
        return new_player
```

**Comment by AllSystemsGo** [comment]
Just a tip, if you put "fixes #631" in the PR it will, when merged, close the corresponding issue automatically.
