### ISSUE TITLE
Feature Request: Limit possibility to brute-force logins

### ISSUE THREAD

**Issue by Antrare** [evennia/evennia#634]
Currently Evennia allows us to bruteforce logins by:
a) Not disconnecting a connection that has multiple failed login attempts
b) Not IP banning them after x amount of those attempts for x period (10mins?)

Recommend those two features are added in prior to a game going "live"

**Comment by strikaco** [comment]
I don't disagree with the principle, but why re-invent the wheel? DenyHosts and/or Fail2ban already exist to do exactly this, and either should already be part of a security solution for a public-facing server. Someone willing to bruteforce your game is likely malicious and skilled enough to bruteforce your other services too.

**Comment by Antrare** [comment]
My understanding is that fail2ban won't recognize multiple login failures
of events from a single connection attempt. I already run it on ssh for
example and after 3 disconnects they are banned.

Last I checked you can continually fail login checks on evennia and it
won't force a disconnect ... ever.

**Comment by Griatch** [comment]
@Antrare, @strikaco: From what I understand of fail2ban/denyhosts, these work by monitoring (ssh) logfiles for failed login attempts. Evennia does not ouput separate information on login fails, if we did maybe those tools could be directed to track and react to such files as well.  

But it should by all means not be particularly hard to add a timeout-style ban on a given IP directly in Evennia by all means.

**Comment by Griatch** [comment]
Implemented in latest push.
