### ISSUE TITLE
Feature Request: Command-spam throttling

### ISSUE THREAD

**Issue by silentartist** [evennia/evennia#640]
A feature request from the forum posted by Jace:

"Is there a way to limit type ahead lines? For example if a player enters look 100 times the server will process this as it can. I would like to limit the type ahead lines to 3, so the player could type look 100 times but it would only process 3.

So if the player is spamming, they would receive a message such as: You may only have x type ahead lines.

-Jace"

**Comment by fuzzyweapon** [comment]
That's usually called command throttling.




*____________________*{*fuzzyweapon}*

*---------------------------------------*

**Comment by strikaco** [comment]
Perhaps every character object can have a queue for commands, limited to 3 or 4. Once they hit the upper limit any further spamming is ignored until a spot opens in their queue.

Meanwhile, every character can be subscribed to a global ticker that fires every few seconds and executes the first command in each character's queue.

**Comment by luyijun** [comment]
I think the server can also have a queue for all player's commands. When the queue if full or the server is very busy, the server can ignore new commands (except commands from game managers) and ask players to wait. This can protect the server from too busy.

**Comment by fuzzyweapon** [comment]
Blueskying here.  These are quite sophisticated but portions of them could be scaled back, so I thought I would share...

This should be frequency based I would think to stop spikes from bots first.  Then you could have a back-off threshold that increases each time the requests violate the current threshold target.  So, similar to a login throttle, you could back it off in phases.  Maybe the first time, the client has to wait a certain amount of time.  The next time, they have to wait longer.  Etc.  You could develop threshold measures to deal with...that dumb bot that went all out and is really easy to detect.  That savvy player who is using command throttling on their client to try and fly under the radar.  A lot of times, this can simply be detected by keeping the three last timestamps of requests (would need tweaking) and comparing the times.  Are they all the same?  Oh, is the payload the same size?  etc.  Each bit should help in determining confidence that it isn't a human or it isn't an annoying human.

Secondly, pulling off of secondary queues wouldn't be a horrible idea, but it seems like you could just go ahead and load them up to a central one (unless you had some craaaaazy scaling thing going on)...and instead implement something that gives admins finer control.  For instance, perhaps a MUD once 2 priority classifications, let's say the admin has labeled 'Combat' and 'Globals'...then everything else is unlabeled, so by negation, it makes a third classification.  Each one is given a priority weight.  On a MUD, it is important that combat is prioritized in times of high volume, but maybe not the same on a MUSH.  That could be incredibly deep and robust or a little more rigid with just some development around the key use cases to make sure that evennia itself remains rather agnostic about the strategies.

**Comment by Griatch** [comment]
While it's not hard *per se* to create one or more command queues, experiments show that this completely killls performance of the server; a queue needs to be queries very fast to "crank the wheels" so to speak, and this is (at least in the tests I've done) not good at all for performance - it basically introduces sequential processing in the very efficient asynchronous twisted event loop.

As for throttling in general, the changes to the AMP protocol incoorporates a batch-send system that makes for a  considerable speedup when a large number of commands are trying to pass between the Server and Portal. This is not handled on a per-user level but globally but nevertheless it's a promising setup since it does not use a fast-running loop to dispense commands but checks time since last send to determine if it should wait to send next batch or send right away.

All this to say that  building queues as suggested in this feature request is not trivial to do while maintaining performance.

**Comment by fuzzyweapon** [comment]
This makes complete sense and I think you just articulated a lot better what I was thinking.  Injecting synchronous logic anywhere in the global command loop is going to be like putting a tight rubberband around a hose, creating a bottleneck, which is what the choice of an asynchronous architecture actually /allows/ Evennia to get away from and have excellent performance.

**Comment by Griatch** [comment]
There is now a `MAX_COMMAND_RATE` setting that allows you to limit the commands/second the Portal accepts to receive before it complains and drops the command. This is a very efficient throttling happening using delta-time measurements already on the Portal level (it will drop too fast-sent commands and echo a warning to the user). It's as close to this feature request as we are likely to get I think. 

The rate setting defaults to 80 cmds/s, which is generous but remember that this throttling covers *all* input from the user, including eventual OOB messages from a supported client so it's worth to experiment with depending on your setup.

Closing this now.
