### ISSUE TITLE
Feature Request: NOP KeepAlive

### ISSUE THREAD

**Issue by AllSystemsGo** [evennia/evennia#641]
Although a look through at the telnet handler's code does show keepalive being set on the socket, it appears the interval is too long to keep some home routers from dropping the connection.

Please consider making keepalive parameters adjustable through the game settings file, and/or a telnet NOP version of the keepalive instead of TCP only.

Thank you.

**Comment by Griatch** [comment]
How short would you suggest the keepalive to be to accomodate the home routers you speak of?

**Comment by Kelketek** [comment]
@Griatch Throw it to thirty seconds. Unless you've got thousands of players, it'll be no issue and it'll handle all but the most insanely aggressive routers. I've used the 'send a blank line to the game every thirty seconds' method of my client to handle this where it isn't supported and never see a disconnect for servers where this is a problem.
