### ISSUE TITLE
Searching: Need more functionality?

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#642]
I've been trying to figure out the most efficient logic to use for things like 'globally target a character.' this of course can be done through the search method on all objects! And I am aware of the new typeclass system and filter_family, etc.

But how would I use .search() to search for 'global=True, use_nicks=True, typeclass=<main character typeclass>' in a situation where there may be many derivatives (such as the Solars, Lunars, and etc for Exalted, which are derivatives of Mortal, which would inherit from the normal Character)...

filter_family does cover filtering but...?

My brain asplode.

**Comment by Griatch** [comment]
One simple answer: Tags. https://github.com/evennia/evennia/wiki/Tags
.
Griatch
Den 18 jan 2015 03:22 skrev "Andrew Bastien" <notifications@github.com>:

**Comment by volundmush** [comment]
... That is a good answer.

I derp.
