### ISSUE TITLE
Create more insightful testing structure

### ISSUE THREAD

**Issue by Kelketek** [evennia/evennia#645]
The current command tests that we run enable us to test that commands have run and check their output to ensure that the displayed text from the commands are correct. However it doesn't tell us much about the function of the commands themselves-- whether they've set the properties we expect, etc.

To fix this, we will probably want to make use of [Mocks](http://www.voidspace.org.uk/python/mock/) and a more robust set of test base classes that have convenience functions for examining the ins and outs of command effects.

**Comment by Kelketek** [comment]
Another idea: Add Travis for Continuing Integration tests.

**Comment by Griatch** [comment]
Travis was added. What is the goal of this issue - that is when will it be considered fulfilled to an extent that it can be closed?

**Comment by Kelketek** [comment]
@Griatch I need to sit down and examine the tests and see if there's anything else in particular worth doing before calling this one closed. I'll try to post a more specific scope, if any, sometime on Sunday.

**Comment by Griatch** [comment]
Since this concerns structure (rather than the amounts of tests, like #120), maybe the removal of un-finished test modules in `evennia/tests/` could fit this Issue. 

I was also briefly considering moving all those spurious `test.py` from their various app-folders and into the main `tests/` folder ... It would make it a lot easier to locate all tests in one place (assuming the models got good names), but not keeping the tests in respective app might completely ruin our chances of running specific tests from the command line ...?

**Comment by Kelketek** [comment]
@Griatch Tests should stay in their module. App code should stay together, and, yes, it would make running specific tests more difficult.

**Comment by Griatch** [comment]
We already have problems with the Commands in this regards (since commands is not an app). Do we really need the central `tests/` folder at all if we want to keep the app structure intact?

**Comment by Kelketek** [comment]
@Griatch My feeling is no. We could make commands an app just by dropping an empty models.py into it and adding it to INSTALLED_APPS, though.

**Comment by Griatch** [comment]
I'm pretty sure modern Django don't require the `models.py` anymore actually. Worth looking at if only for the testing reason.

**Comment by gtaylor** [comment]
@Griatch that came in with AppConfig in Django 1.7, IIRC. As long as you don't care about backwards compatibility, it'd be safe to no longer have models.py.

**Comment by Griatch** [comment]
@gtaylor 

Right. We require 1.7 for the migrations anyway.

**Comment by Kelketek** [comment]
@Griatch Some of the ideas in this issue may be valid, but at the moment the changes we've made to testing in devel should be sufficient, and we don't need to hold open an issue for this until I get some more concrete ideas of exactly what I'd want to add or change.
