### ISSUE TITLE
DefaultPlayer calls @ic, preventing it from being renamed or removed.

### ISSUE THREAD

**Issue by ahmedcharles** [evennia/evennia#659]
Ideally, ```DefaultPlayer.at_post_login()``` would not require the availability of an ```@ic``` command.

**Comment by Griatch** [comment]
To elaborate on this a bit, as was discussed in chat: It might be useful to group some of the standard things, like the `_last_login` Attribute into a hook to call so as to lift this functionality out of the `@ic` command.

**Comment by Griatch** [comment]
This is merged with a rebase, although I reworked the code given to be a part of the puppet_object mechanism instead, there is no need to keep it separate now that it all sits at the same level in the typeclass.
