### ISSUE TITLE
Command tracebacks useless in devel

### ISSUE THREAD

**Issue by Kelketek** [evennia/evennia#671]
Example traceback when a command fails in devel:

    Traceback (most recent call last):
      File "/Users/kelketek/projects/ev_pkg/evennia/evennia/commands/cmdhandler.py", line 442, in cmdhandler
        ret = yield _run_command(cmd, cmdname, args)
    AttributeError: 'CollabPlayer' object has no attribute 'wizdb'
    
    Above traceback is from an untrapped error. Please file a bug report.

The exception handler is masking where the actual traceback is generated from.

**Comment by Griatch** [comment]
Yes, I have resolved this in my tutorial-world branch (where I also noticed this annoyance during testing. Will close this when it merges.

**Comment by Kelketek** [comment]
@Griatch Alright. Do you have an ETA on that branch? This is killing me in collab.

**Comment by Griatch** [comment]
Hope to get it ready today some time. If you want a temporary fix (and is ready to resolve the merge conflict), just pop in a try...except inside the _run_command() subfunction.

**Comment by Kelketek** [comment]
Cool, thanks. I think I'll just render myself unconscious for several hours and see if commits magically appear by the time I wake up. :) If not, I'll probably just use the workaround you mention. It'll save my bacon!

**Comment by Griatch** [comment]
Should be fixed now as the tutorialworld branch has merged into devel.
