### ISSUE TITLE
Feature Request: Feature parity in ANSI markup

### ISSUE THREAD

**Issue by Kelketek** [evennia/evennia#683]
#### Description of the suggested feature and how it is supposed to work for the admin/end user:
Implement remaining ANSI codes for `{` syntax that currently only `%` style syntax supports

#### A list of arguments for why you think this new feature should be included in Evennia:

1. This ANSI style is the preferred method, and so it should support everything `%` does
2. `%` needs to go away before the PyPi release, as it violates the principle of "There should be one-- and preferably only one --obvious way to do it."

**Comment by Griatch** [comment]
The {- syntax is up to snuff with %c style now.

**Comment by Kelketek** [comment]
@Griatch Should this issue be closed, then? Or are you counting the final deprecation of `%` style before closing?

**Comment by Griatch** [comment]
I was thinking to close this once %-style goes away. It's strictly not what this issue is about, admittedly.

**Comment by Griatch** [comment]
1.5 years of deprecation should be enough. `%c-` style color codes are now removed. Closing this issue.
