### ISSUE TITLE
utils.py ? fillchar defaults to empty string or to space?

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#694]
In `utils.py` I read:

```python
def pad(text, width=78, align="c", fillchar=" "):
    """
    Pads to a given `width`, `align` is one of c,l,r
    and `fillchar` defaults to the empty string.
    """
```
Actually `fillchar` defaults to a space character. Isn't the idea after all to either fill unprinted space with either spaces or other chars?

**Comment by Griatch** [comment]
Correct. Updated it now. Thanks!
