### ISSUE TITLE
Bug: Add attribute with category

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#700]
I created a command which adds attribute to an object with category. In this command, I use this:
```
obj.attributes.add("test", self.rhs, category="test")
```

It works on new created objects. But if I reloads the server and call this command on an object which has set attribute with category before, there is a traceback.

This is what I did:
```
@create/drop obj
@setcate obj=attr
@reload
@setcate obj=attr
```

This is the traceback:
```
.../commands/command.py", line 157, in func
     obj.attributes.add("test", self.rhs, category="test")
.../evennia/typeclasses/attributes.py", line 294, in add
     self._recache()
.../evennia/typeclasses/attributes.py", line 204, in _recache
     attr) for attr in attrs)
.../evennia/typeclasses/attributes.py", line 204, in <genexpr>
     attr) for attr in attrs)
 AttributeError: 'NoneType' object has no attribute 'lower'
```

If I remove ```category="test"```, there is no error.

**Comment by luyijun** [comment]
Thank you. The devel branch has the same problem.

**Comment by Griatch** [comment]
devel branch has merged into master and is thus not updated anymore. I've removed the devel branch from upstream now to make it clear.
