### ISSUE TITLE
Feature Request:  Enhanced Idle Disconnects

### ISSUE THREAD

**Issue by Antrare** [evennia/evennia#701]
Idle Disconnects currently appear to disconnect all connected characters over time x (specified in settings file)

We should expand this functionality to include the following:
- Bots (such as IRC-Bot) should never be idle disconnected
- Respect Locks i.e. Immortals shouldn't be disconnected, players should get y time, builders x...

**Comment by Pinacolada64** [comment]
I am staff, and our 5h idle timeout shouldn't affect me. Our IRC bot keeps being affected by this. We have to restart it manually each time.

**Comment by tricuspa** [comment]
What is the challenge behind getting this particular issue resolved?  Could it be resolved with another class or flag (no_idle_Timeout)?

**Comment by Griatch** [comment]
The fix needs to go into the core maintenance task of Evennia, which is responsible for the timeout. It's not difficult (implementation has just been put back for more pressing matters a few times), but it requires some design desicions. The most likely implementation would be to have the task check a lock on the object to determine if it should time out or not.

**Comment by Griatch** [comment]
This was implemented in devel branch and will merge with Evennia 0.7.

**Comment by tricuspa** [comment]
Thank you so much, the additions should be very helpful!
