### ISSUE TITLE
RSS and IRC bots timing out

### ISSUE THREAD

**Issue by jprinc16** [evennia/evennia#708]
RSS and IRC bots seem to be timing out. If they do not receive a message and post it to the MUD before the idle timer kicks in they are disconnected.

**Comment by jprinc16** [comment]
Confirmed, this indeed is what is happening. Further, it would be nice if one was able to make the bots persist through reboots.

-Jace

**Comment by Griatch** [comment]
Thanks for the issue. This is however already covered by #701. Closing this as a duplicate.
