### ISSUE TITLE
Feature Request: CLIENT_DEFAULT_WIDTH and inlinefuncs

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#710]
Since the `setting_default.py` containts defines `CLIENT_DEFAULT_WIDTH`, shouldn't all the predefined inlinefuncs use this as a reference for their default value?

At present, all text-manipulation inlinefuncs (`crop`, `pad`, `wrap`, etc) default to `78` in case of missing `WIDTH` argument. Why not have them fallback to `CLIENT_DEFAULT_WIDTH`? After all, we are always sure that even if the user didn't override `CLIENT_DEFAULT_WIDTH` in his settings it will still be defined by Evennia defaults.

For example, I've set `CLIENT_DEFAULT_WIDTH` to `80` (didn't see any reason for keeping 78, the standard seems to be 80 even on very old telnet terminals). It would be just nicer to have text inline funcs default to this value instead of having to specify 80 each time in order to override the `78` fallback value.

**Comment by Griatch** [comment]
This sounds like a good idea. Will look at adding that.

**Comment by tajmone** [comment]
NOTE: Also in the same spirit of allowing user control over terminal width...

In the module `\evennia\evennia\commands\default\help.py` there is this definition:

```python
SEP = "{C" + "-" * 78 + "{n"
```

which could also rely on `CLIENT_DEFAULT_WIDTH` to keep consistency of screen width.

Of course, the various Cmds docstrings are already formatted around 70-80 cols in source, and this is how they show in game help invocation.

I think that 80 is a fair width anyhow, more would look bad because paragraphs would spread out too thin. 60-80 is a good range for short paragraphs and decent tables.

Most Cmds docstrings actually wrap at less than 80 because somehow in the 80 columns-calculation the 4-spaces indentantation hasn't been kept into account (which gets removed in output). So actual average Cmds help wraps generally at 76.
