### ISSUE TITLE
Wiki Page on Objects

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#713]
I've been reading [Evennia's Wiki page on object](https://github.com/evennia/evennia/wiki/Objects) and I've come to the conclusion that it's been partly updated and partly not to the recent 0.5.0 changes.

What caught my attention is this:
```python
    from evennia import create_object
    new_rose = create_object("game.gamesrc.objects.flowers.Rose", key="MyRose")
```
the reference to `gamesrc` doesn't sound right. I'd though it whould have been just:
```python
    new_rose = create_object("objects.flowers.Rose", key="MyRose")
```
But, because the rest of the page seems to have been already changed/updated, I became unsure and avoided changing anything, in case I mess it up.

**Comment by Griatch** [comment]
Fixed!
