### ISSUE TITLE
MUSH Game Tutorial

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#714]
In the MUSH-like basi game tutorial, at [Chargen areas](https://github.com/evennia/evennia/wiki/Tutorial-for-basic-MUSH-like-game#chargen-areas) the code goes:

```python
 # end of rooms.py

    from commands.command import ChargenCmdset

    class ChargenRoom(Room):
        """
        This room class is used by character-generation rooms. It makes
        the ChargenCmdset available.
        """
        def at_object_creation(self):
            "this is called only at first creation"
            self.cmdset.add(ChargenCmdset, permanent=True)
```
Why is it importing the CmdSet from `command.py` (which contains only the command definition) and not from `default_cmdsets.py` (which contains the actual cmdset definition)?

If its not a mistake, it's something worth explaining in a first-steps tutorial.

**Comment by Griatch** [comment]
Yep, that's an error. Fixed now!
