### ISSUE TITLE
Feature Request: Introducing a common-Cmds Dictionary for i18n

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#721]
In different places Evennia source code invokes commands by `execute_cmd()`. These calls assume that standard cmds haven't been renamed/translated, but this might not always be the case. The general idea of separating Evennia- from game-code dictates that changes are to be implemented only in the game folder, not changing Evennia code if not by overriding it inside the game folder.

If the user renamed the cmds invoked by Evennia, this means that he will have to import and override all code that invokes them. In many cases this is just fine (and required), but in other cases is just a burdening hacking of code which might lead to out-of-sync ingame code.

My proposal is that the `default_settings` module should introduce strings to represent those cmds which are invoked--`look`, `@create`, and some other invoked and much needed cmds (which are expected to exist in any game) could have in `default_settings` a corresponding string representative, eg: `look_cmd`, etc. This would allow users who renamed such cmds to override those string in their `settings `module explicitely. Those who didn't, won't even notice the existence of this system.

At present, these are all the cmd-specific occurences of `execute_cmd()`invocations which I've found in Evennia:

`evennia\commands\default\building.py`

[lines 1903 & 1933 — CmdExamine]	`caller.execute_cmd('`**look **`%s' % obj.name)`

[lines 437 & 439 — CmdMvAttr] invoked `@cpattr`

`evennia\commands\default\comms.py`

[202, 212, 217, 223] invokes `@channels`, `addcom`, `delcom`, `@cdestroy `

`evennia\commands\default\player.py`

	[line 294 — CmdOOC] `player.execute_cmd("`**look**`", sessid=sessid)`

`evennia\commands\default\unloggedin.py`

	[180,262 — CmdUnconnectedConnect+ CmdUnconnectedCreate] invokes `quit`

	[327 — CmdUnconnectedLook] `aliases = ["look", "l"]`

`evennia\objects\objects.py`

	[1383 — at\_post\_puppet]	`self.execute_cmd("`**look**`")`

	[1351 — at\_after\_move] `self.execute_cmd('`**look**`') `

`evennia\players\players.py`

	[648 — at\_post\_login] `self.execute_cmd("`**look**`", sessid=sessid) `

The profiling folder contains code which makes abundant use of various cmds, and more cmds are to found in some contribs.

It's obvious that not all the mentioned files would benefit from implementation of this proposal. But there is a basic issue being brought up here: if we think in broad terms, Evennia could (and might/will) be implemented in many different languages, variations of commands, etc. Introducing in settings some kind of dictionary base which covers the default commands proposed and used by Evennia, taking care that wherever those cmds are invoked in-code they go through the dictionary translation, would not only grant users to customize cmds with more freedom (without breaking compatiblity with dummyrunner, contribs, ecc.) but it would also allow to create code which will work independently of locale implementation.

**Comment by Griatch** [comment]
Sorry, I see your point but this is not something that will be implemented. Commands and typeclasses are all intended to be overloaded (as you point out) and most users will tend to change these a lot (changing the language is just a minor change in this respect) - we can't and won't cater for all different combinations of what people will or won't change. 

There is no need to overload the few commands or typeclass methods calling a command explicitly; just leave the original command name as an alias to the language-specific command - *this* is the convenience solution. If having the English alias remain is not acceptable then one will simply need to overload the calling method/commands, it's that simple. Closing.
