### ISSUE TITLE
Typeclasses / models : docstring: all steps are step 1?

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#724]
I was going through `/typeclasses/models.py.TypedObject` in IPython and came across:
```python
        Notes:
            The loading mechanism will attempt the following steps:

            1. Attempt to load typeclass given on command line
            1. Attempt to load typeclass stored in db_typeclass_path
            1. Attempt to load `__settingsclasspath__`, which is by the
               default classes defined to be the respective user-set
               base typeclass settings, like `BASE_OBJECT_TYPECLASS`.
            1. Attempt to load `__defaultclasspath__`, which is the
               base classes in the library, like DefaultObject etc.
            1. If everything else fails, use the database model.

            Normal operation is to load successfully at either step 1
            or 2 depending on how the class was called. Tracebacks
            will be logged for every step the loader must take beyond
            2.
```
Well, all steps are numbered 1. There is no step 2 nor "beyond 2". It's not the first time I come across multiple same-numbered lines; I thought it meant they had same priority, but from this example I guess it was meant to be a growing numbered list.

**Comment by Kelketek** [comment]
@tajmone In Markdown, this allows for auto-incrementation of an ordered list.

    1. This will render as number 1.
    1. This will render as number 2.

1. This will render as number 1.
1. This will render as number 2.

Please see how it is rendered: https://github.com/evennia/evennia/wiki/evennia.typeclasses.models

**Comment by tajmone** [comment]
Yes, but Wiki aside, what about reading the source code directly or via IPython, etc.?
Nothing prevents using the actual numbers in markdown (1, 2, 3).

**Comment by Griatch** [comment]
@tajmone 

Whereas Kelketek is right about the reason for making lists this way, it's a good point that it looks a little strange in the source. Updated with individual numbers.
