### ISSUE TITLE
Login/Logout with USE_TZ enabled causes warnings

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#728]
Set USE_TZ in your settings to True for Django! Watch what happens in the logs every time you login or logout.

/home/mouvar/evenenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1278: exceptions.RuntimeWarning: DateTimeField PlayerDB.last_login received a naive datetime (2015-03-11 06:49:23.372858) while time zone support is active.

Stuff like that.

**Comment by Griatch** [comment]
The reason for this is explained here: 

http://stackoverflow.com/questions/18622007/runtimewarning-datetimefield-received-a-naive-datetime

So we should change to use `django.utils.now()` rather than the `datetime` module's version.

**Comment by Griatch** [comment]
Closing this now; one will need to activate time zones in code, not sure how much to enforce in core here.
