### ISSUE TITLE
Global Scripts not pausing on full @shutdown?

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#729]
When I create a simple Global Script with an interval of say, 3600 seconds (once per hour), let it tick down to 2800 according to @scripts, and then do a full @shutdown and and evennia start from the terminal...

The countdown has reset!

Is this supposed to happen?
When I examine the script code I notice that they have a .db attribute called _paused_callcount. Not sure what the contents are supposed to be but using @py I've determined they are very small integers.

Is this the intended behavior? Or should scripts remember their countdowns on a cold restart?

**Comment by Griatch** [comment]
No, its's  not the intended behavior; scripts should remember where they are in their step also over a shutdown.
