### ISSUE TITLE
error at first migration with Oracle db settings

### ISSUE THREAD

**Issue by skyxx** [evennia/evennia#732]
Hi,
i take an error when start firstime <code>evennia migrate</code> at Installing indexes ..
(database structure is creating first time)

<code>django.db.utils.DatabaseError: ORA-01408: such column list already indexed</code>

I use Oracle database 12.1.0.2 .. It can occur when table was created (as here) with PK (primary key) which create index on that columns automaticaly. And after that we try create index on same colums separately.
Only these three tables was created: DJANGO_MIGRATIONS, TYPECLASSES_ATTRIBUTE, TYPECLASSES_TAG so problem is with one of them.

It is evennia issue or django ?

**Comment by Griatch** [comment]
Evennia is not tested with Oracle so it's unclear if it is an Evennia or Django issue. Testing and patches are welcome from actual Oracle users. 
.
Griatch

**Comment by skyxx** [comment]
I'm new on evennia and django codebase but i try find definitions for database structure creation. However i don't found definitions even TABLE names in surce code of evennia or djago.

I run migration second time after error and it was done. but its question if all indexes are created on TABLE where it crashed.

**Comment by Griatch** [comment]
@skyxx 

Tables in Evennia (and django) are created as database models, represented as Python classes. The columns in the table are defined as properties on such a class and each row is represented by an instance of the class. You can find the documentation of django models here: 

https://docs.djangoproject.com/en/1.7/topics/db/models/

and an example of (one of the simpler) Evennia models here: 

https://github.com/evennia/evennia/blob/master/evennia/help/models.py#L27

To know if your database correctly created its indices, you need to inspect your database in its in-built client. Try to run `evennia dbshell` - you should end up in whatever command shell Oracle offers. There you can check if the indices were created or not. 
.
Griatch

**Comment by skyxx** [comment]
Thanks Griatch. I read documentation and look at problem closer.

I found probelm. In initial migration script 

<code>evenia-master/evenia/typeclasses/migrations/0001_initial.py</code>

Fisrt UNIQUE CONSTRAINT created by .. <code>migrations.AlterUniqueTogether</code>
which in oracle create index automaticaly.

After that INDEX CREATION is called by .. <code>migrations.AlterIndexTogether</code>
and here will be a problem if we use ORACLE db.

So we need check if oracle is used and don't call .. <code>migrations.AlterIndexTogether</code>
.
Skyxx

**Comment by Griatch** [comment]
@skyxx

That is interesting and useful! Alas I (nor any other developer I know) have an Oracle database to test with, so if you would be willing to make a patch and/or make a push-request from a github fork to fix this, that would be much appreciated. To check which database is in use, you can use something like 

```python
from django.conf import settings 
enginename = settings.DATABASES["default"]["ENGINE"]
```
Where `enginename` would then be set to the path to the python oracle module (If I recall it should be something like `"django.db.backends.oracle"` but check your settings file to be sure).

**Comment by Griatch** [comment]
@skyxx 

Added a check to the migration that deactivates AlterIndexTogether if Oracle is used. I'm closing this issue but I can't really test if the fix actually resolves it (have no Oracle to test with), so if you find that it doesn't, please post here again and we'll re-open this issue.
