### ISSUE TITLE
Traceback on superuser creation: NOT NULL constraint failed: players_playerdb.last_login

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#735]
Don't know what to make of this. Tried to this on two different fresh installs; it fails on both counts.

Downloaded the Evennia source 20 minutes ago, so it's the latest version.

Here's the full traceback:
http://pastebin.com/JnJzXszb

Been a while since I submitted a bug; let me know if you need more info!

**Comment by Griatch** [comment]
You are using Django 1.8, released two days ago. If you try to run the Evennia program you will see a warning about this.  Evennia is not yet tested with that version and has some issues. Use 1.7 (install it with pip install django==1.7.5) until we have upgraded to 1.8.

**Comment by Kelketek** [comment]
Are you running Django 1.8 or 1.7? We currently only support 1.7. I have just pushed a fix that should prevent pip from fetching 1.8 on a new install.

**Comment by strikaco** [comment]
OK. The instructions in the wiki as it stands will always produce this
error, since the recommended installation method (pip install -e .) does
not ask for specific version information...

**Comment by Griatch** [comment]
@strikaco 
As per Kelketek's latest push, pip install -e will not pull 1.8 until we are ready to support it. Closing.

**Comment by strikaco** [comment]
Just a heads-up, "pip install -e" is still installing 1.8.

On top of that, I did "pip uninstall django==1.8" followed by "pip install django==1.7.5". 

1.7.5 installs fine but when I go to "evennia --init" I get a traceback that expects 1.8 as a minimum.

pkg_resources.DistributionNotFound: django<1.9,>=1.8

From the latest commit, requirements.txt seems to have all the wrong versions listed. Changing it there (to django == 1.7.5) and retrying results in:

ERROR: Django 1.7 found. Evennia requires version 1.8
    or higher.

    Install it with for example `pip install --upgrade django`
    or with `pip install django==1.8` to get a specific version.

    It's also a good idea to run `evennia migrate` after this upgrade.

Thoughts?

**Comment by Kelketek** [comment]
We just upgraded to 1.8 earlier today.

Griatch moves fast.
