### ISSUE TITLE
TCP_NODELAY for socket

### ISSUE THREAD

**Issue by karthikncode** [evennia/evennia#746]
Hi,
What's the best way to set the TCP_NODELAY for the telnet socket from the server side? I tried adding in the option in a few places but none of them seemed to work.

Thanks,
Karthik

**Comment by Griatch** [comment]
Why in the world would you need to use TCP_NODELAY in the first place? We are making text games here, not twitch action games where your every press of a button must be sent with minimal latency ... 

What problem are you trying to address?

**Comment by karthikncode** [comment]
Hi Griatch,
I'm looking at making some bots to play these games (hence lesser time delays would be better). Strangely, the socket connection is about 8 times slower on linux than on OSX, and I narrowed it down to this issue. Any pointers would be helpful. Thanks!

**Comment by Griatch** [comment]
In `evennia/server/portal/telnet.py`, add the following line after line 39:

```python
self.transport.setTcpNoDelay(True)
```

Could you give a reproducible test to show when this is an issue, in case it is something we should add to Evennia itself? Evennia has its own dummyrunner system for stress-testing the game with bots, is this what you have tested with so far?
.
Griatch

**Comment by karthikncode** [comment]
I had tried that earlier (and tried it again now) but it doesn't seem to work. I'm testing using a socket client in a separate standalone program. Specifically, I'm setting the option as per this link: http://w3.impa.br/~diego/software/luasocket/tcp.html

    client:setoption('tcp-nodelay', true)

**Comment by Griatch** [comment]
That is the way I know to set options to the twisted protocol. How do you test it and find that it doesn't work? What kind of effect do you expect to see? Also, did you make sure to restart the Portal after setting it?

**Comment by Griatch** [comment]
Bump. Please respond, I'm interested in hearing how you test this and what effect you expect to see (i.e. how you know it "works" or not).

**Comment by karthikncode** [comment]
Sorry, was a bit caught up. The 'effect' is basically how fast the socket is able to operate while interacting with a bot - the bottleneck seems to be the network connection. On a Mac, the entire gameplay is 8 times faster than on linux, and the issue seems to be with sockets. I tried reinstalling evennia, restarting the server, portal, etc. but haven't found anything that works yet.

**Comment by Griatch** [comment]
@karthikncode 

Interesting! Can you tell me exactly what test you perform to arrive at the 8-times-faster figure and how you arrive at this being down to sockets? I'm interested in working this out, as you may imagine.

**Comment by karthikncode** [comment]
I just wrote a basic client for a bot in Lua (see below). I removed the throttling limit on the server and let the bot play (using the data_in() function to retrieve text from the server and data_out() to send to server). I'm connecting via telnet. 

      -- client to connect to telnet
	host = 'localhost'
	port = 4000
	timeout = 0.001

	local socket = require 'socket'

	function client_connect(port)
		client = assert(socket.connect(host, port))
		client:settimeout(timeout)
		print("tcp no delay", client:setoption('tcp-nodelay', true))
	end

	-- Get data from Evennia
	function data_in_smallworld()
		local msg, err = client:receive()
		local text = {}
		while not err do
			text[#text+1] = msg
			msg, err = client:receive()
		end
		return text
	end

	-- Send data to Evennia
	function data_out(data)
		client:send(data .. '\n')
	end

**Comment by Griatch** [comment]
My lua is rusty, but this doesn't look like a complete client, is it? Am I interpreting this right in that you are sending 10000 messages/s to the server - what are you sending (what is the "data" variable?), what are you waiting to get back, and again, what is your measure of speed here? 

You see, if you send data to the Portal like this, the Portal communicates to the Server in turn and you won't get any return back before the Server has processed the request, so what you send determines just what it is you are measuring the speed of. I can certainly not send 10000 commands/second through the portal using Evennia's in-built dummyrunner so either I'm reading the lua wrong or you are doing something quite different from what I do when stress-testing the server. Can you give any numbers you've measured?

**Comment by karthikncode** [comment]
I'm not sending thousands - just several hundred per second. For concrete numbers, I can finish one cycle of (send command, receive response) in roughly ~10ms on a mac vs ~80ms on linux.  Note that I do wait to get something back from the server before sending the next command.
The 'data' variable is just a text command string, for instance, "go bridge" or "get weapon". I get back the server's response to this command. So some string describing the state of the game, like:
"Cliff by the coast
 You stand on the high coast line overlooking a stormy sea far  below. ...."

You can just add in a loop to do something like this:

    while true do
      data_out('go east')
      inData = data_in()
      --measure time here
    end

**Comment by Griatch** [comment]
No, the dummyrunner doesn't disable the throttler, it's also not waiting for a reply before sending the next command, it's a stress tester swamping the server with commands, it's not measuring the cycle return time.

I have no mac to compare with, but 10 vs 80ms is a good starting point for comparison, I'll see if I can replicate your test setup here.

**Comment by karthikncode** [comment]
Thanks! If you want me to run something on a Mac, feel free to let me know.

**Comment by Griatch** [comment]
@karthikncode 

With my own roundtime-tester I could find a roundtime for a "look" command to be about 40 ms (it might be that my laptop is a little faster than yours). 

Adding setTcpNoDelay at the telnet level didn't do anything as you noticed, but as it turned out, setting it at the AMP level (communication between Server/Portal internally) made quite the difference: I now see a round-time of about 5ms for the same test (averaged over 10 seconds of sends)! 

Thanks a lot for pointing this out, fascinating that one can get such a big speed-up for such a small change! I can only guess the mac has some other default behind the scenes? It would be interesting to see if your mac see any change in performance too

I'm closing this issue now, but you can still post to it if you have further comments (or want to reopen this for some reason). :)

**Comment by karthikncode** [comment]
That's great! This will be tremendously useful. Could you let me know which part of the code you changed (just to be sure)?  I can try it on the Mac and let you know - I think socket connections on the Mac do not use Nagle's algorithm, so I expect the delay to be the same.

**Comment by Griatch** [comment]
@karthikncode 

Sure, the commit is linked to this issue two comments up in this thread; it has the full diff.

**Comment by karthikncode** [comment]
Ah, I missed that. Thanks!


—
Karthik

**Comment by karthikncode** [comment]
Reporting back: Works the same on Mac. Big speedup on linux though!

**Comment by Griatch** [comment]
Great, thanks for checking it. :)
