### ISSUE TITLE
args parameter when passed to a command has a leading space

### ISSUE THREAD

**Issue by eidy** [evennia/evennia#749]
The args parameter has a leading space.

For example, in the "SetGender" contrib command, when a player types "@gender male", the arg variable in this line:

arg=self.args.lower()

is set to " male".

Interestingly "@gendermale" works.

I've worked around this in my commands by replacing the above with:

arg=self.args.lower().strip()

I recommend that the Command base class strips this space first.

**Comment by Griatch** [comment]
The Command base class is as basic as can be; further processing is generally intended to happen in the child class. The MuxCommand child class does strip this whitespace, for example. 

There are command styles where the leading white space might be relevant, for example as input to editors. That said, it's probably a good idea to strip this for simplicity, would need to make sure it does not affect any existing commands though.
