### ISSUE TITLE
The attr lockfunction is failing to compare Boolean or None values

### ISSUE THREAD

**Issue by Nadorrano** [evennia/evennia#753]
The value of the attribute to compare is stored as a string, thus None is saved as "None" (which is a boolean True) and is not compared correctly. The same apply for the boolean variables False. The bug is solved by changing the first line of the dictionary CF_MAPPING (line 280).
Also,  the call to its get method (line 325) is wrong because it returns the string `'default'` instead of `CF_MAPPING['default']`:

```python
return CF_MAPPING.get(typ, 'default')(val1, val2)
```
Change this line to:

```python
return CF_MAPPING.get(typ, False)(val1, val2)
```

The dictionary should be changed from:

```python
CF_MAPPING = {'eq': lambda val1, val2: val1 == val2 or int(val1) == int(val2),
'gt': lambda val1, val2: int(val1) > int(val2),
'lt': lambda val1, val2: int(val1) < int(val2),
'ge': lambda val1, val2: int(val1) >= int(val2),
'le': lambda val1, val2: int(val1) <= int(val2),
'ne': lambda val1, val2: int(val1) != int(val2),
'default': lambda val1, val2: False}
```

to:

```python
CF_MAPPING = {'eq': lambda val1, val2: val1 == val2 or str(val1) == str(val2) or int(val1) == int(val2),
'gt': lambda val1, val2: int(val1) > int(val2),
'lt': lambda val1, val2: int(val1) < int(val2),
'ge': lambda val1, val2: int(val1) >= int(val2),
'le': lambda val1, val2: int(val1) <= int(val2),
'ne': lambda val1, val2: int(val1) != int(val2)}
```

Also note that the same `float` value represented with a different precision will still fail to be correctly compared with this code.

**Comment by Nadorrano** [comment]
Errata corrige:

the line 325 should be changed to:

return CF_MAPPING.get(typ, CF_MAPPING['default'])(val1, val2)

keeping the 'default' key in the dictionary.

**Comment by Griatch** [comment]
Ooh, good catch, will fix this. 

The comparison is made for integers, noone has so far expressed an interesting in float comparisons, but it's by all means an easy thing to add should there be a desire for that.
