### ISSUE TITLE
Bug: Error removing nick

### ISSUE THREAD

**Issue by shaolinmike** [evennia/evennia#756]
#### Steps to reproduce the issue:

1. Create a nick: nick test = foo
2. Attempt to delete the attribute: nick test

#### What I expect to see and what I actually see (tracebacks, error messages etc):
Expectation: Nick gets deleted
What I see: 
Traceback (most recent call last):
  File "d:\Dropbox\Projects\Python\MUD\evennia_27\evennia\commands\cmdhandler.py", line 415, in _run_command
    ret = yield cmd.func()
  File "d:\Dropbox\Projects\Python\MUD\evennia_27\evennia\commands\default\general.py", line 162, in func
    caller.nicks.delete(nick, category=switch)
AttributeError: 'NickHandler' object has no attribute 'delete'

Above traceback is from an untrapped error. Please file a bug report.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:

rev 9c67736

**Comment by butterdroid** [comment]
In my most amateur opinion...I think caller.nicks.delete(nick, category=switch) should use .remove instead because it's an attribute?

I can't test this until I get home though.

This is happening on the live demo as well, btw.

**Comment by Griatch** [comment]
@butterdroid

Correct, this was indeed the error. :)
