### ISSUE TITLE
@lock/del passing as @lock

### ISSUE THREAD

**Issue by butterdroid** [evennia/evennia#758]
Hihi,

Unable to currently delete locks using @lock/del <object>=<lock>
Command actually passes as @lock.

**Steps to Reproduce**
1. Create an object
2. Observe object has lock get:all()
3. Use: @lock/del object=get:id(1)
4. Observe lock has now been overwritten instead of deleted

Running 0.5.0 (rev 9c67736) locally and on server. Through webclient and MUSHclient.

Cheers

**Comment by Griatch** [comment]
This is the expected behavior of this command; the syntax for deletion is `@lock/del object/get`, as seen in the help entry, `=` is only for assignment and does not accept switches at all. 

This is supposedly mux syntax. I see why it can be confusing though. Will see if it can be clarified.

**Comment by butterdroid** [comment]
Arg. Reading fail.

Shouldn't Evennia throw an error if you try to use a switch on a command that doesn't take it? Or is that just too idiot-proof?

**Comment by Griatch** [comment]
Yes, added such an error.
