### ISSUE TITLE
Query: Improved ban system?

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#777]
First off: I'm not saying -you- need to make this. I'll do it, in fact, if you think it's worthwhile. I'll be doing it anyways for my own EveMUSH project if not.

So I was examining the built-in Evennia @ban system. This is -okay- although really basic. It lacks any options to REMOVE bans or set durations, and doesn't account for the possibility of an account's name changing (granted, I don't know why that would happen after they're banned). It also is pretty black and white - either you're entirely banned or not.

PennMUSH's default @sitelock command is similar to @ban, but allows more flexibility. For instance, you can define that 'a certain site/range of sites' cannot connect, cannot create, cannot register (for emailed passwords), cannot login as a guest, and etc, in any combination. For instance, maybe you want to block mudconnector.com from logging on as a guest but not ban them entirely!

In another example, my +banlist for Penn's softcode allows for the following:
A) Notes to be added to a Ban entry at any time.
B) Expiring durations for bans. Connections that ping an expired ban send up a warning on admin channels.
C) Keeps track of all characters that the entry has prevented from connecting.
D) Each entry can have a customized 'you are banned message.' (So, for the aforementioned mudconnector.com example, people being disconnected can be gently explained why they can't guest from mudconnector.com.)

I have ideas for how to implement this quite well! Expanding the session class with a 'connect access' system so that it could be checked against a more elaborate ban registry would be great, for instance. Because it should be the responsibility of a session to know what it's allowed to do, right?

**Comment by Griatch** [comment]
I'm OK with PRs with a more powerful ban system with more features, although adding such one Nedd to be careful to not change the database save scheme (as I recall ban dsra is saved using server.conf) or you need to do a migration. 

But you say there is no way to remove bans in the current system - does the default `@unban` command not count?

**Comment by volundmush** [comment]
Okay I forgot about @unban. I'm not used to two commands being used for a single purpose. D'oh.

**Comment by Griatch** [comment]
So, I'm awaiting PRs for a more powerful ban system. This "query" seems to have been answered and so I close it.
