### ISSUE TITLE
Concept: Task 'offloading'

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#778]
To continue my rant apart from the pull request, here's my idea for some things that should probably be done to make Evennia more easily customizable, at least by my reckoning of things. I might be WAY OFF in left field and freely admit it so take this with a grain of salt I guess.

So in Pull Request 775 (create cleanup) I moved a LOT of things to methods on typeclasses. For instance, @charcreate USED to poll settings.MAX_NR_CHARACTERS directly and perform a direct len(player.db._playable_characters). The trouble with this is that if you want to implement a more flexible 'character slots' (let's say, the ability to purchase more slots with Roleplay Points or etc) then @charcreate has to be COMPLETELY changed and replaced. BUT if you offload this (like I did) so that it is the responsibility of the PLAYER typeclass to know how many slots it is allowed, how many are used (checking characters too because some might be exempt) then a coder needs only change the typeclass methods and will not have to change @charcreate at all.

I believe that this concept can be applied to a lot more things. It should be the responsibility of objects to report on their status to commands. As a further example of why this is better, it means that a 'character select screen' can ping the same method and get the same result.

Centralizing such things makes for easier 'rule changing' without having to hunt down every single command and piece of code that has its own idea of how X works.

**Comment by Griatch** [comment]
Lots of good ideas here but I'm closing this too now, since the PR was not merged.
