### ISSUE TITLE
Auto-login vs MAX_COMMAND_RATE

### ISSUE THREAD

**Issue by kkragenbrink** [evennia/evennia#779]
Even if you set the MAX_COMMAND_RATE to 0, most popular client auto-login scripts set to "MUX" or "MUSH" will be too fast, and hit the COMMAND_RATE_WARNING.

In my code I have temporarily commented out portalsessionhandler.py lines 364-367; what I'm wondering, however, is if it might be better to allow someone to overload the data_in method of this class so that I could overload it for my game without messing with Evennia core.

**Comment by Griatch** [comment]
Making portalsessionhandler overloadable is doable but I'm not sure it's all that useful. This sounds like something not only relevant to a specific game but for everyone: it sounds like the rate limiter is buggy or at least not adequate to its intended purpose. 
If you can supply links to the client(s) you are using and how to aet up the relevant login scripts for testing we can look at fixing the limiter somehow.

**Comment by kkragenbrink** [comment]
[tinyfugue](http://tinyfugue.sourceforge.net/) and [mushclient](http://www.gammon.com.au/mushclient/mushclient.htm) both experience this issue.

I am also concerned about the setting in general, though; some MUDs and MUSHes allow players to paste commands in sequence all at once.  I thought about offering an alternative patch: buffering user input instead of throttling it.  If you buffer it, you allow them to enter commands as fast as they can, but you only PROCESS their commands 1/n where n is some slice of time, and you can then have a few settings:

COMMAND_EXECUTION_SPEED=n # Number of milliseconds between commands for a user
MAX_COMMAND_SPEED=n # Number of commands a user is allowed to enter over a period.
COMMAND_SPEED_PERIOD=n # Number of seconds to measure user commands over.
THROTTLED_EXECUTION_SPEED=n # Number of milliseconds between commands if a user has been throttled due to command speed.

**Comment by Griatch** [comment]
Buffering of commands is not a new idea,  alas.  The issue with such solutions (which means some sort of queue which is gradually emptied in the order it is filled) is that you are introducing a sequential element to an asynchronous server. Running a separate infinite loop like that sort of ruins the whole point of the highly optimized twisted event loop.

**Comment by kkragenbrink** [comment]
Fair enough, and coming from a mostly Java and NodeJS world I can very much understand that concern.  I still think buffering is a better solution than throttling, however, and would rather see some kind of non-infinite-loop method of implementing it than what we have currently.

Unfortunately I don't know twisted very well, yet, but my guess is that it has something like a 'nextTick' which could be used to pull off the next command in the list.  I think we've gotten off topic of the initial bug, however, and I'd be happy to pull this out into a separate discussion on the forums.

**Comment by Griatch** [comment]
Maybe, all attempts using loops or twisted callbacks (hooking inte the twisted event loop),  especially on a millisecond time frame had turned out to cause so much python overhead to make the server unusable. But it could certainly be that it has been done in the wrong way in the past. If you find a low latency way to run a buffer queue within the event loop I'm all ears. 

... But true,  this is a different issue. The rate limiter never being lenient enough to accept some client regardless of setting is likely a bug. But there is rhyme and reason to having the limiter and its setting in principle, since the exact limit for dos:ing the server depends on the hardware you run it on.

**Comment by Griatch** [comment]
Regardless of the following discussion, the original entry is indeed buggy behavior so marking this issue as such.
