### ISSUE TITLE
Git cloning to a new install - order of operations?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#781]
So this is odd--

New server. I follow the installation instructions; Evennia is installed and I initialize a new directory for my game. Then I try to git clone my game content from a private repo to the game directory, which fails, because git seems to want to only do its initial clone to an empty directory.

I blow everything away. This time, I git clone first (creates the game directory) then back out and try evennia init. Except evennia init fails because it too is expecting an empty directory to initialize.

Any thoughts?

**Comment by aredcloak19** [comment]
Could you provide the error messages that it is giving you? I just cloned yesterday and works fine.

**Comment by Griatch** [comment]
This is not an Evennia bug, it sounds like. 

What form is your "previous game content"? 

1. If it's already in the right form of an evennia  game dir,  then just copy the entire directory to where you want and put the new game dir under version control with git init. If you want to use git clone you can do it but this presumes the structure evennia expects is already in place or that you can manually fix it.  You should then not run evennia --init at all.
2. If your game content is,  say, from an old Evennia version not using the standalone gamedir, then you should do evennia --init first and then manually copy your code over to its right places in the newly created gamedir. Some rewriting may be necessary too for into the modern scheme. Put this new directory under version control with git init. 

The second case is the most common and probably what you want. See also the evennia manual on version control. Please let us know if this resolved your issues so this can be closed. :)

**Comment by strikaco** [comment]
Somehow through a combination of arcane git remote add/git local add commands, I was able to git fetch my existing content into the initialized evennia directory. Unfortunately I don't remember the exact steps involved but I wanted to go ahead and close out this ticket.

Thanks for the assistance!
