### ISSUE TITLE
Feature Request: Implement ANSI underline

### ISSUE THREAD

**Issue by jake-shasteen** [evennia/evennia#782]
#### Description of the suggested feature and how it is supposed to work for the admin/end user:
On MUX, one can use %cu, and on Penn, one can use [ansi(u, ... )] to underline selected text. On Evennia, one would theoretically use {u to underline text but it is not implemented.

#### A list of arguments for why you think this new feature should be included in Evennia:

* Feature compatability with MUX/Penn
* Ability to create cleaner-looking tables and headers for those not using xterm256.

#### Extra information, such as requirements or ideas on implementation:
After doing some digging around in the code, I noticed that ANSI_UNDERLINE is defined in utils/ansi.py, but it is never used. All I had to do to get this to work was add the appropriate map to ext_ansi_map on line 255: (r'{u', ANSI_UNDERLINE), and I was able to implement this feature on my home game.

One would also want to modify the default 'color ansi' command to show this feature as well.

**Comment by Kelketek** [comment]
If that was all that was required to get it to work, would you consider making a pull request with that change? You’d get to get a contributor. :)

**Comment by jake-shasteen** [comment]
I sure can! Sorry, I haven't really done a pull request before. I think I am doing it right?
https://github.com/evennia/evennia/pull/783
