### ISSUE TITLE
Bug: Tutorial world shift root command not working

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#786]
In the tutorial world, it does not seem possible to shift the roots of the crumbling wall (the command is not recognized at all and the wall, while having the right cmdset does not show up as having the commands at all). This makes the dark cell impossible to escape. See original report [here](https://groups.google.com/forum/#!msg/evennia/QZjEs4MTyPY/DZF0WXkyEwAJ).

Since this was tested successfully many a time, this appears to be a recent regression.

**Comment by Russell-Jones** [comment]
The "push" entry seems to date back to Jun 2011 when the contrib was added, so I guess the nature (order?) of command resolution has changed somehow, such that push wasn't overridden, but is now. I've stuff to do or I'd git bisect it myself.

https://github.com/evennia/evennia/blob/b2b743b0aa14e8e1bf50c1ee4f429b85f90d0d6c/contrib/tutorial_world/objects.py
https://github.com/evennia/evennia/commits/master/contrib/tutorial_world/objects.py

**Comment by Griatch** [comment]
@Russell-Jones 

The github blame/history seems to have locked up in that link (a github quirk?), there have been a lot of more recent changes to that file (the latest two days ago). Re-find the file from the top dir and you'll find it a lot more informative. 

The issue was solved and fixed in revision a1eadef.
