### ISSUE TITLE
PlayerDB.objects.get_player_from_email returning QuerySet

### ISSUE THREAD

**Issue by Quae** [evennia/evennia#791]
When implementing email_login.py, the line player=PlayerDB.objects.get_player_from_email(email) is actually returning a QuerySet for me, not a player. As such, the line 'player.check_password(password)' is failing unless I tell it to use the first element in the Queryset.

Files affected:
email_login.py (dragged into a folder called menus in mygame)
evennia/evennia/players/manager.py - the method 'get_player_from_email' says it's returning a player

**Comment by Griatch** [comment]
Hm, it seems the `@return_typeclass` decorator is not doing quite what it should. This method should be returning a single matching player result.

**Comment by Quae** [comment]
It looks like all the other get_player_from..()s will have the same problem in that they're calling self.filter but not grabbing the 0th element.

**Comment by Griatch** [comment]
Yep, it's a leftover bug from removing the requirement to explicitly convert database models to typeclasses (this is handled intrinsically by Evennia these days), somewhere along the line the extraction fell away. Will need to test everything works as it should after fixing this again.
