### ISSUE TITLE
Feature Request: Expansion of built-in Script Methods

### ISSUE THREAD

**Issue by cluebyte** [evennia/evennia#794]
As per our discussion on Optional Realities with Griatch, I'll reiterate some requests I had while developing status effects for my own game and see if these are deemed suitable.

**Resetting repeats**: If Scripts could optionally reset themselves based on some condition, so their task callcount was set back to 0, that would be awesome. This came up as an use case when status effects might be "refreshed".

**Interval Modification**: Scripts being able to change what interval they ticked at. It appears that currently, once you create the script, it will run only at the interval you originally set.

**Comment by Griatch** [comment]
@cluebyte 

-  `DefaultScript.reset_callcount(value=0)` will now reset the current running callcount. You can also set it to an arbitrary value if you prefer. Note that your callcount won't be checked until the script triggers again (the timer is not reset). 
- `DefaultScript.restart(interval=None, repeats=None, start_delay=None)` will now "warm-reboot" a running Script. With the keywords you can assign new values to these properties without first killing the Script. If the keyword is left at `None`, the existing value will be used. Note that this will trigger all hooks in order: First `at_stop`, then followed by `at_start` as the Script is restarting.

**Comment by cluebyte** [comment]
This is wonderful news, Griatch, thank you for your work as always!
