### ISSUE TITLE
Bug: Evennia doesn't collectstatic properly

### ISSUE THREAD

**Issue by cluebyte** [evennia/evennia#796]
So, I was trying to test out modifying Evennia's templates, but I ran into issues actually trying to modify existing static files. I ran a clean install of Evennia and tested just modifying evennia_logo.png as per the tutorial at https://github.com/evennia/evennia/wiki/Web-Tutorial.

When I tried to run "evennia collectstatic", it doesn't seem to detect the static_overrides. This appears to not work for template_overrides either. 

I get this output when I try to modify Evennia's default website logo:

     /opt/testgame/web/static_overrides/evennia_general/images# ls
     evennia_logo.png  
     README.md

     /opt/testgame/web/static_overrides/evennia_general/images# pwd
     /opt/testgame/web/static_overrides/evennia_general/images

     /opt/testgame# evennia collectstatic
 
     You have requested to collect static files at the destination
     location as specified in your settings:

     /opt/testgame/web/static

     This will overwrite existing files!
     Are you sure you want to do this?

     Type 'yes' to continue, or 'no' to cancel: yes

     0 static files copied to '/opt/testgame/web/static', 74 unmodified.

This appears to be a bug since I'm doing everything correctly by the tutorial on a clean install of Evennia. It's not picking up the static_overrides/template_overrides folder or some such.

**Comment by Kelketek** [comment]
@cluebyte This is working for me locally. It should be noted that the server automatically runs this command on server restart to make things easier on you. Is there any chance you restarted the server between when you copied the file over and when you ran that command? Can you see the new logo in the browser?

**Comment by cluebyte** [comment]
@Kelketek I cannot see the new logo in the browser. If it works for you though, my issue must be local, unless someone else has run into this issue. I'm scratching my head on what it could be though, considering this is a fresh install of Evennia.

**Comment by Kelketek** [comment]
@cluebyte Try removing the contents of your static folder and recollecting your static objects. I know that the static collector can occasionally get confused on what is a new asset and what's old.

**Comment by cluebyte** [comment]
@Kelketek This seemed to do the trick Kelketek. Thank you! Though, we may want to note this in the Tutorial that developers may be advised to delete their static folder in order to bring in new changes.

**Comment by Kelketek** [comment]
@cluebyte This warning has been added to the notes now. :)
