### ISSUE TITLE
Bug: Error when using a particular non-ASCII character over plain telnet (only)

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#800]
#### Steps to reproduce the issue:
1. Connect and log in to evennia with a _plain telnet client_, e.g. `telnet localhost 4000`. This effect does not appear over generic mud clients or the web client. 
2. Send the Russian character `я` (so far this is the only one found to really produce the effect).
3. The server freezes due to utf-decoding errors and won't accept further commands.
#### What I expect to see and what I actually see (tracebacks, error messages etc):

The `я` character should work as well as other non-ANSII characters does, also over plain telnet. 
There are no tracebacks unless putting a print statement anywhere in `sessionhandler.data_in`, where the error turns out to be a decoding error where UTF-8 cannot properly decode the character. Strangely enough, there is no such issue when decoding it in a terminal session, so it is possible that the telnet client sends something unexpected.
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:

Tested to tweak `settings.ENCODINGS` to fallback to a specific russian encoding `koi8-r`, also tried to print using this encoding inside the `data_in` method, which still caused the error.

**Comment by Russell-Jones** [comment]
Note to self: investigate by converting byte string to ascii hex and comparing that with tcpdump output.

**Comment by j3b4** [comment]
I was about to file a similar looking bug.  I found that I can crash the webclient and generate an untrapped error via telnet by doing the following:

1. set something with the following description: Null Island is a fictional island in the Gulf of Guinea added to the Natural Earth public domain map dataset, located where the equator crosses the prime meridian, at coordinates 0°N 0°E / 0°N

2. use @options encoding = Latin-1 ... or perhaps anything other than utf-8 (maybe)

3. look at the object.


Not sure if this should still be another bug report or if it helps out here.

**Comment by Griatch** [comment]
@j3b4 

This particular sub-error does not appear to happen, at least not on the current webclient with latin-1 encoding and this exact string. Please re-check on your setup.

**Comment by BlauFeuer** [comment]
@j3b4 I tried the same with `@options encoding = Latin-1` encoding on a mu* client that only knows "latin-1" encoding - set it with the mu* client and then logged in and viewed it with the webclient (utf-8) and couldn't reproduce the sub-problem.  The ° symbol is fortunately a character in both encoding, at the same code point, so it's a relatively safe character. If you can still get that error, it would help to know how you reproduced it.

**Comment by BlauFeuer** [comment]
@Griatch  I created character `TestPilot(#465)` on the test server with the description "`Send the Russian character я (so far this is the only one found to really produce the effect).`" by using a telnet client. The moment the Cyrillic R is sent, the telnet client goes into a locked state that can be escaped by Control C.

The server seems unaffected - because TestPilot can say, pose, and describe itself with the character and it can be seen by other sessions as having been sent, but the telnet session gets locked until Control C is hit in the telnet client. I can only be sure that the character was sent, but don't actually get any feedback that it was sent to the server.

**Comment by Griatch** [comment]
@BlauFeuer 

Pushed a tentative fix. Check it out.

**Comment by Griatch** [comment]
Wrong reference. Meant to reference #998.

**Comment by Griatch** [comment]
I have traced the command `say я` from the telnet client, into Evennia and back out again. It looks fine on the Evennia side, all the way, and works fine on all but the vanilla telnet client.
The issue seems to be that to_str() will only apply its decoding/ascii conversion unless the data it receives is unicode (i.e. when a conversion to bitstrings are necessary). Trying various changes to the logic has not helped this behavior though ... so I'm stumped for now.

**Comment by Griatch** [comment]
Either due to changes for #1122 or some other cleanup along the way, this issue is no longer an issue - the `я` symbol now prints strangely if no supporting codex is available, but it won't crash/lock the server. So closing this, finally.
