### ISSUE TITLE
Bug: evennia -i no longer starts interactively

### ISSUE THREAD

**Issue by gtaylor** [evennia/evennia#803]
#### Steps to reproduce the issue:

1. evennia -i start server

#### What I expect to see and what I actually see (tracebacks, error messages etc):

It looks like the process is getting foregrounded or daemonized (not sure which, haven't had time to look into). This causes some process supervisors and Docker to immediately exit.

The -i flag should keep the process foregrounded. I suspect this may have been broken when logic was added to start both processes if none are specified (you can't stay interactive to the portal and the server processes at the same time in one tty).

On a related note, perhaps we should fail loudly if -i is passed to ``evennia start all`` or ``evennia start``, since we can't actually start both processes interactively.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:

Currently on 538228af0411d862d558b3413decd6aa762f49be
Ubuntu 15.04 with Python 2.7
My Docker container is based off of the official python:2.7 image, which is Debian-backed (I think).

To see what I've got on the docker-compose side (and see the symptom on display): https://github.com/gtaylor/evennia-docker

**Comment by gtaylor** [comment]
Stuck a ``.wait()`` after here and got the expected behavior:

https://github.com/evennia/evennia/blob/master/evennia/server/evennia_launcher.py#L1036

The CTRL+C handling would need to be adjusted, though.

**Comment by Griatch** [comment]
@gtaylor 

Hm, sounds right; I guess it's not something that's all that noticeable when starting for development in a native terminal.
