### ISSUE TITLE
Output latency

### ISSUE THREAD

**Issue by shollen** [evennia/evennia#805]
I have Evennia up on a late 2013 15-inch Retina MacBook Pro running OS X 10.10.5 — 2.6 ghz i7, 16 gigs of RAM. I’m using Python 2.7.9 and SQLite3.

I'm seeing variable latency in the output of commands. It occurs with all commands and is anywhere between none to a full second in duration. The delay comes between output to different player objects in the room. The player objects are all single sessions on separate accounts logged in locally from my machine. I've rearranged the messaging statements in several commands, and who sees output first and who sees it last depends totally on the order of the statements in the command code.

For example, if I switch the message statements in the drop command to...

    caller.location.msg_contents("%s drops %s." %(caller.name, obj.name), exclude=caller)
    caller.msg("You drop %s." % (obj.name,))

...every other player in the room will receive the output of my command up to a full second before I do.

The delay actually seems to be in the msg function, like it’s searching a massive list or iterating a million times. I added...

    caller.msg("You dropped %s." % (obj.name,))

immediately after...

    caller.msg("You drop %s." % (obj.name,))

in the ‘drop’ command, and whenever I drop something, I get a near full second delay between the output of those two lines.

**Comment by kkragenbrink** [comment]
I noticed this myself. I am fairly certain this is just because of the way python's iterator works.

**Comment by Griatch** [comment]
To test this and rule out as few other effects as possible, I made a simple two-line command that just does `self.caller.msg()` twice in a row. I can confirm that I see a "hiccup" occationally. Not all the time - sometimes the two commands appear immediately after one another and sometimes there is a delay of, if not a second, then at least clearly noticeable length. Interestingly, if I do multiple `msg` calls, the ones after the second will almost appear without delay.  

@kkragenbrink 
So, unless I misunderstand what you mean, a simple test can rule out that this is a fundamental python code slowness issue: I add the following simple code to my test command: 

```python 
import time
    # ...
    t0 = time.time()
    self.caller.msg("This is output 1. (%s)" % (time.time() - t0))
    self.caller.msg("This is output 2. (%s)" % (time.time() - t0))
```
With this setup, output 1 has a time delta between 0.1 and 1 microsecond (that is, millionth of a second) whereas output two is at some 0.4 ms (thousands of a second). So, we can say that the `msg()` call (which will block until it has performed the full send, this is how Twisted works) takes about 0.4 ms on my machine. This sounds reasonable (and is not noticeable by a human). *This time does not change*, even when the perceived lag between the commands is as its greatest. 

@shollen 

At this moment my theory is that the delay rather lies in one of the newish rate-limiting routines that was added on the Server -> Portal send level. That is, your code is not slow, but something in the pipeline that forwards the output to you and your users is. Is travelling though, so I won't have time to look at this for a few days, probably.

**Comment by Griatch** [comment]
So,  preliminary tests suggest I was right; the delay happens due to a batch-sending routine in the AMP (where data is sent from the a Server to the Portal). This is there to limit congestion on the wire by grouping data arriving very close one another in time. It seems to kick in erroneously since with it on the second msg() goes through in 0.8s and when bypassing it, the time is some 20 ms...

**Comment by shollen** [comment]
I admire your skill and knowledge and appreciate your dedication to Evennia, GA.
