### ISSUE TITLE
look at any object elicits traceback in tutorial

### ISSUE THREAD

**Issue by feoh** [evennia/evennia#809]
Start the tutorial with a fresh evennia world cloned from github master, evennia --init, migrate etc:
```
Exits: begin adventure, exit tutorial
Traceback (most recent call last):
  File "/home/feoh/src/personal/evennia/evennia/commands/cmdhandler.py", line 439, in _run_command
    ret = yield cmd.func()
  File "/home/feoh/src/personal/evennia/evennia/contrib/tutorial_world/rooms.py", line 167, in func
    _SEARCH_AT_RESULT(caller, args, looking_at_obj)
  File "/home/feoh/src/personal/evennia/evennia/utils/utils.py", line 1541, in at_search_result
    elif len(matches) > 1:
TypeError: object of type 'Character' has no len()
```

I looked at the code and see that it's the generic room / object search function but I don't understand what the data structures at play well enough to figure out why doing a len() on a list of matches would cause this exception.

Did Character get redefined?

**Comment by Griatch** [comment]
Hm, from your error it sounds like `matches` is entering `at_search_result` as a single `Character` result rather than an iterable (which it is supposed to always receive). 
Alas, I cannot reproduce this error with the latest Evennia and a clean game folder/database. Does it really just appear by only entering the tutorial? Which OS, which versions of libraries?

**Comment by feoh** [comment]
@Griatch CentOS 7.  I'll put a prettyprint in.  What libs do you want the versions of?

**Comment by Griatch** [comment]
@feoh 

You can supply the result of `pip list`.

**Comment by feoh** [comment]
@Griatch Sure!
```
decorator (4.0.4)
Django (1.8.4)
evennia (0.5.0, /home/feoh/src/personal/evennia)
funcsigs (0.4)
ipython (4.0.0)
ipython-genutils (0.1.0)
mock (1.3.0)
path.py (8.1.1)
pbr (1.6.0)
pexpect (3.3)
pickleshare (0.5)
Pillow (2.9.0)
pip (7.1.2)
pytz (2015.4)
setuptools (18.2)
simplegeneric (0.8.1)
six (1.9.0)
traitlets (4.0.0)
Twisted (15.3.0)
wheel (0.24.0)
zope.interface (4.1.2)
```
