### ISSUE TITLE
Bug: kwargs in the portalsessionhandler.py's data_out() can not be read correctly.

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#815]
**Steps to reproduce the issue:**
Send out any text with args ```raw=True```.

**What I expect to see and what I actually see (tracebacks, error messages etc):**
In sessionhandler.py's data_out(), it is correct and the kwargs is ```{'raw': True}```. But in portalsessionhandler.py's data_out(), the kwargs becomes ```{'data': {'raw': True}}```, so the following programs can not get the args ```raw``` correctly.

**Comment by Griatch** [comment]
Ah, looks like some remnants of the call sign of AMP. Will fix that, thanks.
