### ISSUE TITLE
@py feedback wonky

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#816]
So try this in @py:

```python
{u'blacksmithing': 3}
```
yeah, it comes out underlined. Oops.
Extremely minor bug and likely caused by the 'render it to the client' portion of the session stuff that handles ANSI and other codes like {r.

**Comment by Griatch** [comment]
This was resolved by making the direct return from `@py` ignore color codes. If you want to test colors, use self.msg() from the `@py` line (doing so will still have this particular bug show up though).
