### ISSUE TITLE
Feature Request: Use | for color-tags/inlinefuncs instead of {

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#818]
#### Description of the suggested feature and how it is supposed to work for the admin/end user:
A change of color/inlinefunc markers in text from `{` to `|`: 

```python
# old:
"This is normal text. {rThis is red text{n normal text again."
# suggestion:
"This is normal text. |rThis is red text|n normal text again."
```

#### A list of arguments for why you think this new feature should be included in Evennia:

1. `%` and `{}` are both used in Python formatting operations, for example

```python
string = "test1 %s test3" % "test2"` 
```
and 
```python
string = "test2 {repl} test3".format(repl="test2")
```

used in latest Python.  We don't use `%c`-style color formatting for this reason, but we *are* using `{` to mark color, which faces the same issue with the second style of formatting. We should have gone with a character symbol that is not used in Python at all. Hence the suggestion to use `|` instead, which has a similar visual apperance (some would argue less intrusive) but is not used in Python string operations at all. 

#### Extra information, such as requirements or ideas on implementation:

Opening this up to feedback. If this is implemented, the change will affect also inline functions but be gradual, with both `{` and `|` syntaxes supported during a deprecation period.

**Comment by thenomain** [comment]
Some of us out of necessity use editors that auto-close brackets (et al.), so `|` would be my preferred token. I likewise agree that it is less visually disruptive.

An alternative would be enclosing the markup. e.g., `{c}`, `{function()}`, and so forth. It would be visually easier to follow than `|markup`.

**Comment by Griatch** [comment]
@thenomain 

Yes, that's another good reason for something different from `{`. The `{}` functionality is unfortunately just what we are trying to move away from, so as to not have an overlap with default Python templating syntax (which can use `{ ... }` as mentioned above.

**Comment by thenomain** [comment]
Then how about `[...]` as default, and `|<ansi color code>` for ansi shortcuts?

As a Mush coder, the legibility of enclosing the inline function calls is moderately important. `some text[test()]more text` is easier to visually parse than `some text[test()more text`

**Comment by ahmedcharles** [comment]
I'd go with `[...]` for arbitrary length substitutions and `|.` for single character substitutions only, and never inline functions.

This means you could have `[red]text[normal]` or `|rtext|n`, but perhaps not `[r]text[n]`, depending on whether you want to allow the long syntax to also allow abbreviations.

I'd also want to be able to enable `|.` style substitutions without turning on `[..]` style ones, perhaps to allow players the ability to use one style but not the other. And I'd want to be able to turn on inline funcs on demand, so I could perhaps restrict them to not be usable by players or not.

Granted, this is a bit complex, so it's not directly obvious what the best overall implementation should be.

**Comment by Griatch** [comment]
There is also some further discussion and suggestions on making a more fully-scoped version [on musoapbox here](http://musoapbox.net/topic/620/evennia-a-python-based-mu-server/159).

**Comment by Griatch** [comment]
I did some toying around based on input here and elsewhere. Note that this relates to inlinefuncs only - how to modify color markers is a separate thing. So this is potentially a bit OT for this particular issue. 

In a local branch I have fully nestable inlinefuncs running.  I thought I'd present it here for comments. 

The syntax I tried and kinda like is as follows: 

```
$funcname(arg,arg2,arg3,...)
```

That is, `$` followed by a string, followed by `(` with no spaces. This uniquely identifies the beginning of a named inlinefunc call. This combination should hopefully not be a source of confusion in normal text while having the advantage of looking like, well, a function call. (I tried with `|funcname()` too, but it doesn't quite stand out enough I find). Commas separate the arguments and the function call ends with `)`. There is no `/func` end marker in this version of inlinefunc, everything is supposed to go into the argument list. 

The `funcname` is the name of a registered function on the Python form `funcname(*args, **kwargs)` (`*args`/`**kwargs` mean that you can call this function with *any number of* arguments/keyword arguments). As with current inlinefuncs, only arguments are supported from in-game, the `**kwargs` is used by Evennia to supply state-info (like the session, character etc of the entity seeing the string). If you try to enter an undefined inlinefunc, the parser can either raise a traceback or replace the missing call with `"<UNKNOWN>"`. It will also dynamically strip them if so desired. I could in principle make it so the parser only identifies inlinefuncs that are actually defined, but I think an actual error is more useful than the parser simply ignoring a mis-spelled entry. 

Within the argument list, commas `,` are used to separate arguments. If you want a text with commas (or the end parenthesis) as an argument, you wrap your argument in quotes: Both single- and double quotes are supported and you can wrap them inside each other as normal in Python. If you are not using quotes you can also escape commas, quotes and `)` using back-ticks to make the parser not consider them as part of the syntax. 

The parser will allow any of the `args` to themselves call `$func()`s and will build a complete call stack from this. This stack is cached which means that sending the same string to multiple people will only lead to it being parsed once (it will always result in multiple inlinefunc calls since the outcome of those may vary depending on who sees the string). With simple but deeply nested inlinefuncs this leads to an average of 10-15 microseconds per receiver (tested with 10 000 receivers).

**Comment by Griatch** [comment]
Also pushed |-style color markings as suggested at the top of this thread to the `nested_inlinefuncs` branch, for people to take a look at. May still change? They exist alongside the old `{`-style color markings for now.

**Comment by ahmedcharles** [comment]
I made a comment on the commit.

**Comment by Griatch** [comment]
@ahmedcharles 

Cool, thanks. :)
