### ISSUE TITLE
Feature Request: Add Status property to the Msg model

### ISSUE THREAD

**Issue by grungies1138** [evennia/evennia#844]
#### Description of the suggested feature and how it is supposed to work for the admin/end user:
For instances where it would be useful to track the current status of a message, the property could be set or gotten.

A simple string property would suffice.

**Comment by Griatch** [comment]
This is implemented in 836c9913d501b6ba4e3e9d24e31812b88b28b7a0, but even better - Messags now support [Tags](https://github.com/evennia/evennia/wiki/Tags), which means that you can not only give them any combination of status you want, you can also efficiently search for all messages with a given tag. I'd recommend you set aside a separate Tag category for your message tags, to further speed up lookup and avoid the same tags being shared between messages and all other objects. 

It's not exactly what was requested, but better, so closing this. :)
