### ISSUE TITLE
EvMenu, keys + args

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#852]
Okay I've been playing around with EvMenu a bit. I think there's some room to improve.

First, the 'key' section for an option should be matched against using the same logic as commands. The FIRST WORD in a typed string should be used only.

That means if I have an option where key = 'set', I can type 'set Charisma=3,Apperance=4'

It would be equally great if the API were extended to use similar logic to commands. Is there no way to pass more arguments? perhaps raw_input should instead be a dictionary containing things like the name of the previous node, the command used to reach the current one, and equivalents to lhs, rhs, lhslist, and rhslist like MuxCommand uses.

**Comment by ahmedcharles** [comment]
I think I'll take a look at improving EvMenu along these lines, though it may end up being a little different than suggested.

**Comment by volundmush** [comment]
Hey, if it works it works!

**Comment by volundmush** [comment]
Doing it -better- than EvMenu as a contrib is also an option I suppose.

**Comment by Griatch** [comment]
I'm not sure exactly what is missing here. The `aliases` options keyword is used if you want to make things like the first word a keyword to match against. Using EvMenu's __default__ option-key (give whatever alias) will allow the user to enter arbitrary text. You can then parse that text for whatever purpose, same as any input. 

I would say, that needing to enter a full command with potentially complex arguments *inside* a menu is somewhat ... making it not a menu really. But that said, an EvMenu is just a CmdSet (merged in with priority 1), running like any other. Added to that, EvMenu can -and does- execute any code as part of a node. So what you do is yourself adding your own custom command set (created as normal) on top of the EvMenu cmdset with the commands you want. You can do it from within the node that needs them, even. Only problem is that you must make sure to yourself *remove* it again when you exit the node or the menu; EvMenu's own cmdset cleanup will of course not clean them out for you. 

Closing this.

**Comment by Griatch** [comment]
Closing this. We avoid custom parsing everywhere in Evennia; so using it suddenly in EvMenu makes little sense, especially when you can easily make use of the full Evennia command system to do whatever you want.
