### ISSUE TITLE
Suggestions for changes to ANSIString

### ISSUE THREAD

**Issue by Russell-Jones** [evennia/evennia#877]
I've been mulling this over and drafting some code, but I wanted to get it out there as there seem to be significant changes on the cards for ANSIString, and it may be better to do this before implementing those (though the spec can be developed in parallel however it ends up implemented).

1) I'd like it to be more reversible, by using Python 3-like conventions for encoding and decoding. By that, I mean making it constructable with bytes or text and convertible back to those, such that the text has the escape codes and the bytes has the raw codes, whether passed to `__init__()` or the output of `__str__()` or `__bytes__()`.

2) We should consider using 3-style ranges (like 2's xrange()) The main reasons are a) that they can be compared to indexes with "in", b) would be a way to auto-terminate styles, e.g. AS("|go hai") + AS(" bai") -> AS("|go hai|n bai") and merge overlapping open codes (AS("|go")+AS("|g hai") -> AS("|go hai|n") and c) they could be used for testing which ranges to include in AS()s returned for slices.

There's a bit more to it than this, but I hope this gets the basic ideas across.

**Comment by Griatch** [comment]
Just making sure @kelketek sees this; he's the most knowledgeable about the underbelly of ANSIString.

**Comment by Griatch** [comment]
@Russell-Jones 

I see no response from @Kelketek, but I don't see a problem in general with making a PR against ANSIStrings along those lines.

**Comment by Griatch** [comment]
@Russell-Jones 

If you have an implementation of those changes in the works, a PR would be appreciated. ANSIString won't be seeing other significant change as far as I know.

**Comment by Griatch** [comment]
After two years in limbo I think it's time to close this issue. If any update is incoming, comment here and I can open it again.
