### ISSUE TITLE
Feature Request: Make ChannelHandler pluggable

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#887]
#### Description of the suggested feature and how it is supposed to work for the admin/end user:

The functionality of the Channelhandler is to track the Channels a player is connected to and to generate Channel-commands matching those channels. This is what allows the player to enter, say "public Hello!" and have "public" be identified as a channel name if they are subscribed to that channel. 

The Channelhandler is currently a hardcoded singleton without any options for replacement or customization without modifying the server code. While it's unlikely the ChannelHandler itself is much use to modify, it *would* be useful to be able to customize the Channel command it creates. 

#### A list of arguments for why you think this new feature should be included in Evennia:

1. People may want to customize the details of calling a channel in some way. Currently replacing the channel command (or indeed modifying its cmdset priority) this is not possible from the game dir. 

#### Extra information, such as requirements or ideas on implementation:

The ChannelHandler could *in principle* be designed to be completely replaceable. This would be simple to implement, although it would mean changing to loading the module in a lot of places, including during the server startup. 

An alternative would be to instead allow the user to customize the generation of the Channel Command itself, for example by allowing the developer to plug in a channel-command-factory function that the Channehandler can make use of.

**Comment by Raelyr** [comment]
Would it be easier to move the channel command method to another file and add a line for where to point it to the settings? Then developers could create a new channel command and change that file path in the settings easily. I don't think that would require changing or calling it anywhere else?

**Comment by Griatch** [comment]
@Raelyr 

Yeah, that sounds like an even better solution - put the python path to the Channel-command class in settings, have the ChannelHandler load it using `utils.variable_from_module`.

**Comment by Griatch** [comment]
Implemented in devel branch. This will close when it merges.

**Comment by Griatch** [comment]
Closed as wclient branch has merged.
