### ISSUE TITLE
Bug: tutorial_world "northern path" exit is visible without tag:tutorial_climbed_tree

### ISSUE THREAD

**Issue by bitcoinfees** [evennia/evennia#889]
#### Steps to reproduce the issue:

Following the standard setup instructions -

1.  Clone evennia/evennia.git and install head (f87d07b775aa26ff6e55e36a162b8a823ee57daf)
2.  evennia migrate, evennia start
3.  log in as superuser and run `@batchcommand tutorial_world.build`
4.  create and log in as another user (to ensure it's a non-superuser), execute `tutorial` and `begin` to arrive at "Cliff by the coast"
5. Northern path is supposed to be invisible before climbing the tree, but it is instead visible and traversable.

#### What I expect to see and what I actually see (tracebacks, error messages etc):

See No. 5 above.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:

1.  User is confirmed to not have tag:tutorial_climbed_tree before he climbs the tree, and to have the tag after.
2.  Northern path is confirmed to have the lock `view:tag(tutorial_climbed_tree, tutorial_world);`
3.  Tried on both OS X 10.11 and Ubuntu 14.04.

**Comment by Griatch** [comment]
Can confirm this; This is probably due to build errors on a newly-created tutorialworld; I can see errors related to the new cmd-recursive check failing on both `@dig` and `@lock ` in the build log; the cmd-recursive safety algorithm may need fixing.

**Comment by bitcoinfees** [comment]
Other weird stuff relating to tutorial_world.

When a non-superuser enters the Dark Room for the first time, he's not supposed to see the room description.  But the room description appears once.  Subsequent calls to `look` then properly trigger the DarkCmdSet look (i.e. the room description no longer appears).

To reproduce, follow steps 1 to 4 in the OP.  Then, head across the bridge east until you reach the place where the Ghost appears. Let yourself be killed and end up in the Dark cell.  The room description appears once.
