### ISSUE TITLE
Calling pause() on a script does not persist between reload/restart

### ISSUE THREAD

**Issue by MikeCPlusPlus** [evennia/evennia#891]
**Description** 
This isn't really related to the bug, but I found it during my testing. The `pause()` function of scripts work for pausing, but unfortunately, using the `@scripts` command calls `validate()` on all scripts, which restarts a paused script. I would expect that a script that is paused using the `pause()` method would stay paused until I tell it to `unpause()`

I added a boolean attribute to my inherited script class called `intentional_pause` which gets set whenever my game-code wants a script to pause for real. I know this isn't exactly the right way to fix it, but once I looked into the code around handling scripts during restarts and reloads I ended up breaking more than I'd like.

```
class PauseableScript(DefaultScript):

    def start(self, force_restart=False):
        if self.db.intentional_pause:
            #don't actually start the script.
            return 0

        return super(PauseableScript, self).start(force_restart)

    def stop_effect(self):
        self.db.intentional_pause = True
        self.pause()

    def reappy_effect(self):
        self.db.intentional_pause = False
        self.unpause()
```

**Comment by Griatch** [comment]
Without looking into the  code, the title of this bug and the bug description does not seem to match up - the title says that pause doesn't persist across a restart while the text says it won't persist across a validate() call. Which one is the issue? 

That said, the main time `pause()` is called is by the `@reload` mechanism, meaning the script should  definitely be restarted in validate() later. Doing something like an "intentional_pause" state like you suggest is likely the best bet.

**Comment by MikeCPlusPlus** [comment]
I think I can describe my issue better, I mixed two different scenarios under one heading, which I think led to the confusion.

***Scenario 1***
A script that has been paused using the `pause()` function is restarted when the server is reloaded. After your first reply I understand this is intentional. I had read the documentation and assumed that the `pause()` method and functionality were state changes that should be persistent, and the reloading of the server can also alter this state. 

***Scenario 2***
Issuing the `@scripts` command to see what scripts are created/running/paused, unpauses scripts. I think this can be surprising, since the content of the help page contains the following line:
*If no switches are given, this command just views all active scripts.* I would not anticipate the viewing of scripts to change their state. But as per the first scenario, if the only caller of the `pause()` method is the server at reload time, then this is a complete-non issue.

**Comment by Griatch** [comment]
Yeah, the pause() method is mainly called by the restart mechanism, but it's a potentially very useful thing to use also manually. 

I can definitely see the potential confusion from what is happening in the two scenarios you describe. I think the solution is likely to do something akin to what you are already doing- separate between the pause state induced by reload and that induced manually. Worth looking into.
