### ISSUE TITLE
@shutdown command unresponsive

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#895]
When I issue the @shutdown command, nothing happens. I see no error in the console or any log files. 

To test, I checked out the master branch of ainneve, dropped my db file, did `evennia migrate` and started the server with -i. Still no response to the @shutdown command.

@ergodicbreak has confirmed that he is seeing the same behavior in an IRC discussion.

**Comment by ergodicbreak** [comment]
Same behavior on a fresh non-Ainneve install of Evennia as well.
