### ISSUE TITLE
''module' object has no attribute 'search_object_tag''

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#898]
Not sure if this is a deprecated function or not, but the syntax as it appeared in the wiki (was) incorrect.

https://github.com/evennia/evennia/wiki/Zones

Since it appears the search_tag function does work, I edited the wiki and am bringing this to your attention here in the event this is a bug.

Thanks!

**Comment by Griatch** [comment]
It looks like a correct edit. 

`search_object_tag` does still exist, it's one in a family of search functions found in `evennia.utils.search`,  like `search_channel_tag`, `search_player_tag` and so on. `search_object_tag` is by far the most common tag-search though, so it has an alias `search_tag`, which is what is available at the top `evennia` level for convenience. The tutorial hadn't kept up. :) Thanks for the fix!
