### ISSUE TITLE
Global script running twice per interval

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#901]
Follow-up to the following discussion: 
https://groups.google.com/forum/#!searchin/evennia/duplicate/evennia/rGIzSsMPY4g/YsP71Tqy6oEJ

My "resolution" turned out not to work. I obviously screwed something up on this one and could use some help sorting it out...

The log was clear at first but upon a reload I'm seeing the following message:

2015-12-11 23:16:58+0000 [-] /hello/kitty/evennia/evennia/typeclasses/django_new_patch.py:254: exceptions.RuntimeWarning: Model 'typeclasses.outdoors' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.

"@scripts" only shows one running script and if I add a print statement to the script in question, it fires once in the log/console-- but the actual action performed by the script executes twice. Perhaps there's an older copy floating around in memory behind the scenes after all. The original script was not designated as persistent.

I'm going to poke around in the Django dbshell but in the meantime if you know how to resolve this I'd appreciate it!

**Comment by Griatch** [comment]
This should be resolved as part of resolving #890. Closing this. Post here again if the problem persists.
.
Griatch

**Comment by strikaco** [comment]
Problem persists, unfortunately, even on the newest build. I 
* stopped the script, 
* shutdown the server, 
* pulled, 
* started the server, 
* stopped the script again, 
* restarted the server.

No error messages this time, but it's still firing twice with a 1-second delay between them.
