### ISSUE TITLE
Exit object "at_before_traverse" not triggering.

### ISSUE THREAD

**Issue by DauntlessAutumn** [evennia/evennia#902]
The at_before_traverse hook is seemingly failing to trigger.

I've added the following to the Exit class (in typeclasses.exits):
```
def at_before_traverse(self, traversing_object):
        self.location.msg_contents("Test.")
```

**Expected behaviour:**
Everything in the room should receive "Test."

**What happens:**
No message occurs.

I have confirmed the exit I am testing with is of the correct typeclass (*typeclasses.exits.Exit*)
I also tried a more direct message with
```
traversing_object.msg("Test.")
```

Let me know if there's more I need to provide or a different testing method to use.

**Comment by Valleriani** [comment]
Just want to confirm this one as well. It is also happening with me. 

The hooks are missing some updated info in the help file as well (I.E: should be at_after_traverse(source, traveller, source_loc) rather then just at_after_traverse(traveller, source_loc)?

after_traverse works though, just not before..

**Comment by Griatch** [comment]
@Valleriani 

> The hooks are missing some updated info in the help file as well (I.E: should be at_after_traverse(source, traveller, source_loc) rather then just at_after_traverse(traveller, source_loc)

`at_after_traverse(traveller, source_loc)` is the correct call sign, where does it say a `source` argument should be included?

**Comment by Griatch** [comment]
As seen, `at_before_traverse` was removed completely since it makes no sense to have it the way Exits works. To customizee or modify things before the traversal, overload `at_traverse` instead and put in custom code before a call to `super()` (to let the parent `at_traverse` handle the actual movement calls).
