### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Nerun** [evennia/evennia#904]
I have updated portuguese locales.
[locales pt.zip](https://github.com/evennia/evennia/files/64468/locales.pt.zip)

**Comment by Nerun** [comment]
Sorry, i played at Evennia in 2014 and i forgot that i am the PT translator!!! Evennia references changed that's why this translation is broken. I will fiz it and update a new one.

**Comment by Griatch** [comment]
Added. Thanks!
