### ISSUE TITLE
Task: Update internationalization strings

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#905]
With the changes to the new library-like layout, some of our internationalization (i18n) strings have been lost, changed or not been updated after having moved. These should be added/fixed to fully have i18n cover the core strings (the strings not changeable otherwise by the user), 

# Translation process

- Identify a text string hard-coded somewhere in the core Evennia engine. Common examples are error messags such as "Connection lost" or "This is an error because ...". This part is mainly a matter of going through all of the core modules manually. 
- Note exceptions to what to translate:
    - Dont' translate Command output (we consider Commands something users can easily replace) 
    - Don't translate Typeclass hook strings (also something highly customized by the user). 
    - Don't translate log output or command-line output. This will only be seen by developers. 
- The guideline is that _we translate "hard-coded" strings (strings not easily replaced by the developer) that the end-user (player) may see._
- At the top of the module you have found translatable strings in, do the following import: 

    ```
    from django.utils.translation import gettext as _ 
    ```
    (so import gettext and rename it to _).
- The newly imported _ is actually a function name. Wrap the string you want to put under translation into that function: `_("string to translate")`. 
- If there are template markers, the translation must happen _before_ the templating.  So `_(this is {foo} going on").format(foo="bar")`
- If there are multiple template markers, make sure to name them (like above). Certain languages may have to present them in a different order. 
- We should try to move away from `%s` -style formatting and use `.format()` as much as possible. 
- Python `f-strings` [does unfortunately _not_ work with i18n at this time](https://code.djangoproject.com/ticket/30109). Use `.format()`. 
- Once a string has been marked up like this, then one can run the i18n mechanism to create/update template files. This allows for translating the texts all over Evennia from a single location. This, the actual act of translation, is covered in our documentation, here: https://github.com/evennia/evennia/wiki/Internationalization#translating-evennia
- Note that when you translate, you must not translate the formatting markers, so if the string to translate looks like this: `"this is {thing} going on"`, it must be translated like `"Här är det {thing} på gång"`.

**Comment by Griatch** [comment]
I got a question just how to actually add i18n as described in this issue. This is the process:

 1. Identify a text string hard-coded somewhere in the core Evennia engine. Common examples are error messags such as "Connection lost" or "This is an error because ...". This part is mainly a matter of going through all of the core modules manually. *Note exceptions to what to translate, listed in the original issue*.
 2. At the top, do the following import: `from django.utils.translation import ugettext as _` (so import `ugettext` and rename it to `_`). 
 3. The newly imported `_` is actually a function name. Wrap the string you want to put under translation into that function: `_("string to translate")`. 
 4. If the string contains multiple positional formatting markers, such as `"Player %s is not connected with %s." % (name, protocol)`, then i18n standard recommends to change this to `{}`-type formatting, so `"Player {name} is not connected with {protocol}".format(name=name, protocol=protocol)` instead. This is because some languages may grammatically work better with words in different order. 
 5. Once a string has been marked up like this, then one can run the i18n mechanism to create/update template files. This allows for translating the texts all over Evennia from a single location. This, the actual act of translation, is covered in our documentation, here: https://github.com/evennia/evennia/wiki/Internationalization#translating-evennia

**Comment by Griatch** [comment]
Note: If someone wants to help with this, they don't necessarily need to go through *all* of the Evennia core sources in one go. It's perfectly fine to make a PR adding i18n strings from, say, `evennia/comms/` or something. We'll just keep nagging away at this issue until all is done.

**Comment by trhr** [comment]
`At the top, do the following import: from django.utils.translation import ugettext as _ (so import ugettext and rename it to _).`

ugettext is deprecated for gettext. everything else is accurate.

**Comment by Griatch** [comment]
@trhr Thanks. Updated.

**Comment by derrick-anderson** [comment]
Hi Team:
I"m looking at pickin up some older issues and chipping away at them.  Would it be fair to say that as part of this issue we should be moving from fstrings to `.format()`? Where necessary of course.

**Comment by Griatch** [comment]
@derrick-anderson: Yes, this seems a fair assessment. it would seem i18n is not compatible with f-strings since we need to keep the {}-markers around for gettext to replace them and f-strings are already parsed at that time.

**Comment by Griatch** [comment]
This has, at long last, been completed in develop branch. Additional documentation and contacting translators will be a separate task.
