### ISSUE TITLE
purpose of utils.pypath_to_realpath?

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/evennia#910]
As I've been working with the batchcode processor I noticed this function in `utils`, which is called only by the function `read_batchfile` in `batchprocessors.py`

```
def pypath_to_realpath(python_path, file_ending='.py'):
    """
    Converts a dotted Python path to an absolute path under the
    Evennia library directory or under the current game directory.

    Args:
        python_path (str): a dot-python path
        file_ending (str): a file ending, including the period.

    Returns:
        abspaths (list of str): The two absolute paths created by prepending
            `EVENNIA_DIR` and `GAME_DIR` respectively. These are checked for
            existence before being returned, so this may be an empty list.

    """
    pathsplit = python_path.strip().split('.')
    paths = [os.path.join(settings.EVENNIA_DIR, *pathsplit),
             os.path.join(settings.GAME_DIR, *pathsplit)]
    if file_ending:
        # attach file ending to the paths if not already set (a common mistake)
        file_ending = ".%s" % file_ending if not file_ending.startswith(".") else file_ending
        paths = ["%s%s" % (p, file_ending) if not p.endswith(file_ending) else p
                 for p in paths]
    # check so the paths actually exists before returning
    return [p for p in paths if os.path.isfile(p)]
```

If there was a file `batchcode_example.py` in both Evennia lib and the game directory, and the game pointed to both via its batchprocess settings, the caller potentially could get back a list of files when running the batchcode processor. This isn't a problem in itself because `read_batchfile` will return after successfully reading the first file in the list, but I'm curious *why* you would want this behavior? It seems like raising an exception or some other user-facing message would be more appropriate. 

I would be happy to submit a PR if we do indeed want to refactor this code.

**Comment by Kelketek** [comment]
I would suggest refactoring this to:

1. Consider files in the game directory first, as user defined overrides should always supersede library files.
2. Return the first item in the list if it exists, or raise an informative exception (perhaps including what paths were checked).

If you are able to make such a pull request, it would be appreciated. Perhaps @Griatch can confirm, but if it really is only used once in the codebase, I don't see why this course of action would not be the correct one.

**Comment by Griatch** [comment]
The batchprocessor codes are showing their age, it's one of the earlier pieces I wrote.
Concerning this, people often seem to have issues with the file target so making this handling more explicit sounds like a good idea.

**Comment by Griatch** [comment]
Just checking - is there a refactor in the works for this?

**Comment by ergodicbreak** [comment]
@Griatch I started it but work has taken over my life at the moment; I probably won't move forward on this for a while.

**Comment by Griatch** [comment]
I'm closing this then, since it's not really an issue but a question that, I think, has been answered.
