### ISSUE TITLE
@set command behaving strange

### ISSUE THREAD

**Issue by orkim** [evennia/evennia#914]
The help file indicates that you need to use `@set *<player>/<attr>` to set an attribute on a player.  If I do so, I get a message saying "created attribute" but when using `@examine` the attribute is not shown on the player.

If I repeat the command and remove the * the attribute is shown. However, this means I must be in the same room as the player I wish to set an attribute on.

If I use a player name that exists, with the * syntax command I can get the "created attribute" command from any location.  If I use a player name that doesn't exist, I receive a "not found" message as I would expect.

I believe the * syntax on the @set command is currently broken.

This can be reproduced with a fresh install and no custom code.

**Comment by Griatch** [comment]
No, the `@set` command works correctly. When you are assigning an Attribute using the `*player` syntax you are literally writing to the `Player` object. You seem to be examining the `Character` that is attached to the `Player`. The `Player` is an OOC entitity and has no location. The confusion is, I think, that in `MULTISESSION_MODE=0,1`, a `Character` with the same name as the `Player` is automatically created for you, to mimic other engines. 
Use `examine *playername` and you will see the Attribute correctly. You could also do `@ooc` to go ooc and examine yourself - you'd then be examining your player object and find the Attribute you assigned.
A Character is just another Object, so you don't use the `*` syntax for them. See the [Player docs](https://github.com/evennia/evennia/wiki/Players) for more info. 

Closing.

**Comment by orkim** [comment]
Thanks Griatch.  This is correct in that I had a state of "momentary confusion" between player and character.  It also masked it due to player and character being the same name.

I do have these concepts straight, just crossed them in my brain for a bit.

I confirm this is working as expected and putting the attribute on the player with the * syntax, and on the character object without.

Thanks for your explanation!
