### ISSUE TITLE
Incorrect link in basic tutorial.

### ISSUE THREAD

**Issue by mtso** [evennia/evennia#918]
In the MUSH-like basic tutorial, the section called **Have "look" show combat scores**
https://github.com/evennia/evennia/wiki/Tutorial%20for%20basic%20MUSH%20like%20game#have-look-show-combat-scores

The link to the default implementation of `return_appearance` in `evennia.DefaultCharacter` should be:
https://github.com/evennia/evennia/blob/master/evennia/objects/objects.py#L1276

**Comment by orkim** [comment]
Thanks! I've updated the line numbers of the two links in that section.
