### ISSUE TITLE
Evennia base server config missing portal quitting message.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#925]
Evennia base server config missing portal quitting message, but defaults to "Quitting. Hope to see you again, soon." It does not appear to be a configurable option in settings_default.py for us to override.

**Comment by Griatch** [comment]
This message is sent by the [default `@quit` command](https://github.com/evennia/evennia/blob/c1d843263059d0372aacdbdae40c814a37122a5f/evennia/commands/default/player.py#L500). Default commands are meant to be replaced with your own versions. To replace it, you just replace with your own quit command in your game directory, saying something else (see the custom command tutorials for how to do it). 

So this is not hard-coded but a part of the easily replaceable cmdsets and should thus not be a part of settings. Closing.
