### ISSUE TITLE
untrapped error

### ISSUE THREAD

**Issue by ianmspackman** [evennia/evennia#928]
Following a tutorial, @create/drop button:tutorial_examples.red (i.e. hitting enter too soon) caused an untrapped error. Duly reporting it as requested.

**Comment by Griatch** [comment]
Whereas there *could* be an error in Evennia worthy of a report, this is not one of them. The message you refer to ("please make a bug report") is primarily aimed at *your* prospective players, not towards you as a game developer. If that error pops up in a *production game* it should indeed be reported - by your players to you. During development however, such errors are normal and is (usually) up to you to correct. Closing.

**Comment by Griatch** [comment]
And to clarify - the message refers to the full traceback which is visible in your log/terminal.
