### ISSUE TITLE
Multi-weapon woes in Tutorial World

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#933]
If you should **get weapon** someone has dropped and **get weapon** from the barrel weapon rack, you may have two weapons of the same name.  This can cause some problems, such as 

1. unable to drop either weapon, or 
1. unable to give one of the two weapons to someone, or 
1. confusion in combat.

Even if you have 2 different kinds of weapons and drop one, combat is flawed because the attack never completes due to the two weapons (one being on the ground nearby) even though you are not holding one of them.

But you can complete the tutorial and get the better weapon. The problem is that you may not know how to use it.

Here is a quick summary:

>-> inv
You are carrying:
 Rusty dagger  A double-edged dagger with a nicked edge and a wooden handle.
 Rusty dagger  A double-edged dagger with a nicked edge and a wooden handle.
 The Hawblade  The weapon of a long-dead heroine and a more civilized age, the hawk-shaped hilt of this blade almost has a life of its own. 
>-> drop rusty dagger
You carry more than one rusty dagger:
>-> give rusty dagger=slim
You carry more than one rusty dagger:
>->attack slim
More than one match for 'attack' (please narrow target):
 1-attack (The Hawblade)
 2-attack (Rusty dagger)
 3-attack (Rusty dagger)
>-> 1-attack slim
How do you want to fight? Choose one of 'stab', 'slash' or 'defend'.
>-> stab
More than one match for 'stab' (please narrow target):
 1-attack (The Hawblade)
 2-attack (Rusty dagger)
 3-attack (Rusty dagger)
>-> 1-attack
How do you want to fight? Choose one of 'stab', 'slash' or 'defend'.
>-> 1-stab
Who do you attack?
>-> slim
Command 'slim' is not available. Type "help" for help.

**Comment by Griatch** [comment]
The fact that you can't drop the dagger when there is a multi-match is indeed a bug in the default drop command that needs to be fixed.  

The attack is not technically malfunctioning, but the error is also not very intuitive. The "attack" command actually uses aliases to wrap three different fighting styles, stab/slash/defend in the same command. Each of those work as an alias to attack. This is why you get the error for "attack" when trying the "stab" command.  Doing "1-stab slim" should correctly pick the command for the first dagger, use the "stab" fighting style and attack slim with it. 
The fact that only "attack" is give as an example is confusing though, the error should probably also include the aliases in this case.

**Comment by BlauFeuer** [comment]
There's another issue that yields a traceback: when attacking anything that does not have a health attribute, if the attack should have caused the target's health loss:

```
Traceback (most recent call last):
File "/home/NOW/NOWMU/evennia/evennia/commands/cmdhandler.py", line 435, in _run_command
     ret = yield cmd.func()
   File "/evennia/evennia/contrib/tutorial_world/objects.py", line 827, in func
     return target.at_hit(self.obj, self.caller, damage)
   File "/home/NOW/NOWMU/evennia/evennia/contrib/tutorial_world/mob.py", line 393, in at_hit
     self.db.health -= damage
 TypeError: unsupported operand type(s) for -=: 'NoneType' and 'int'
```

If this should be added as a different issue, just say so.

**Comment by Griatch** [comment]
@BlauFeuer 

It normally goes as a separate issue, but now that it's already there, leave it be where it is. :)

**Comment by Griatch** [comment]
Will close when wclient branch merges.

**Comment by Griatch** [comment]
Closed as wclient branch has merged.
