### ISSUE TITLE
Task: Refactor batchprocessor

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#939]
#### Description of requested feature:

`evennia/utils/utils/patchprocessors.py`, which is the engine underlying `@batchcommand` and `@batchcode` needs cleanup and refactoring. 

#### Reasons for adding feature:

The processor code is pretty old by now and is not very clean. With more usage, the processors, especially the batchcode processor, is coming across as pretty fragile. See e.g. [issue 937](https://github.com/evennia/evennia/issues/937). There is also a common beginner issue with getting the paths right - the fact that the file ending should not be including tends to be confusing, as well as how to use the path (that evennia will accept start from any number of base paths defined in settings seems to be more confusing than useful).

####  Expected result of feature

The goal of this refactoring should be to clean up the processors (and possibly their supporting Commands) to be more transparent, use better coding standard as well as more robust logics in parsing.

**Comment by strikaco** [comment]
If you're going to bother doing this, would you also consider adding some way to export the game world in such a way that one could run a script on a new deployment and have it create all the rooms? It would make moving worlds built on dev platforms to production a lot easier.

**Comment by Griatch** [comment]
@strikaco 

With "export the game world", what do you mean by that? If you are referring to somehow parsing a created game and save it to a script file, I can say with pretty good certainty that it is not going to happen. Not only would it be highly game specific, it would also be fragile with respect to database schema changes. The batch parsers are for creating the game without having to do so from the command line. They are not data transfer files. If the goal is just to pre-populate a database from a template, then one should use a [Django fixture](https://docs.djangoproject.com/en/1.9/howto/initial-data/).

**Comment by strikaco** [comment]
Fair enough. Thanks for the suggestion!

**Comment by ergodicbreak** [comment]
I'm thinking about this again, and would like feedback on an alternative implementation of the batchcode processor. 

Rather than writing Python code plus a special markup syntax in the batchcode file, what if we changed the batchcode parser so that a batchcode file would instead import and use regular Python functions from a batchcode library. 

For example, what currently looks like this:

```Python
#
# This is an example batch-code build file for Evennia. 
#

 #HEADER

# This will be included in all other #CODE blocks

from evennia.utils import create, search
from evennia.contrib.tutorial_examples import red_button
from typeclasses.objects import Object

limbo = search.objects(caller, 'Limbo', global_search=True)[0]


#CODE (create red button)

red_button = create.create_object(red_button.RedButton, key="Red button", 
                                      location=limbo, aliases=["button"])

# caller points to the one running the script
caller.msg("A red button was created.")

# importing more code from another batch-code file
#INSERT batch_code_insert

#CODE (create table and chair) table, chair

table = create.create_object(Object, key="Blue Table", location=limbo)
chair = create.create_object(Object, key="Blue Chair", location=limbo)

string = "A %s and %s were created. If debug was active, " \
             "they were deleted again." 
caller.msg(string % (table, chair))
```

Would now look like this: 

```Python
# This is an example batchcode build file for Evennia. 

# Import the batchcode library module
import batchcode

# We use regular imports, and top level variables are available as usual
from evennia.utils import create, search
from evennia.contrib.tutorial_examples import red_button
from typeclasses.objects import Object

limbo = search.objects(caller, 'Limbo', global_search=True)[0]

# Code blocks are functions processed in order they appear in the file, Their first argument is a string of 
# valid Python. 

batchcode.block("""
    red_button = create.create_object(red_button.RedButton, key="Red button", 
                                      location=limbo, aliases=["button"])

    # caller points to the one running the script
    caller.msg("A red button was created.")"""
)

# We replace inserting with regular importing
import another_batch_code_file

# The block function can also take optional arguments for the objects created
batchcode.block("""
    table = create.create_object(Object, key="Blue Table", location=limbo)
    chair = create.create_object(Object, key="Blue Chair", location=limbo)

    string = "A %s and %s were created. If debug was active, " \
             "they were deleted again." 
    caller.msg(string % (table, chair))""", (table, chair)
)

## Pros:
* Simpler, no special syntax to parse
* Easier to compose batchcode functions with other systems as desired. 

## Cons: 
* Breaking change, magnitude depends on how many people use the processor now. 

Thoughts?
* Breaking change, we could

**Comment by Griatch** [comment]
@ergodicbreak 

For us parsing it, it's easier. But I would argue the following major con to the suggestion - The main one is the same problem any code has that inserts python code as a string - we are basically giving up the editor's help capabilities and syntax highlighting.

If syntax was to be changed I wonder if a hybrid might rather be possible - python code on the Batchcode form, but rather than `#CODE` style parse-blocks, one uses some sort of yield mechanism within special batchcode function calls as desired to access special batch-code functionality like interactive deletion etc. 
. 
Griatch

**Comment by Griatch** [comment]
I'm considering reworking the batchcode (not the `batchcmd`) processor to ditch the `#CODE`, `#HEADER` and possibly also the `#INCLUDE` statements and arguments, instead favoring a raw Python implementation. That is, you give a normal Python source file to the batchprocessor, without worrying about special markup. 

- One thing that differentiates batchcode (old version as well as the proposed new) this from a normal import/run of a python module is however that the code is read as a normal file and then executed. This means it can run and update without a server `@reload`. This might also be a reason to keep at least `#IMPORT` for combining multiple batchcode files rather than just importing them (which would cache the imports). On the other hand, I'm not sure spreading out batchcode files across multiple files is really a thing people do?
- For managing debug, it's simplest to let the developer handle this themselves. We make a global variable `"DEBUG` available in the execution context and then the batchcode creator can simply themselves remove objects if they want to use debug mode to test without creating a gazilliion copies, for example:
        ````python
        obj1 = evennia.create_object("Obj1")
        if (DEBUG):
            obj1.delete()
        ````
- The drawback of this simplification is the loss of the interactive mode for batchcode (jumping from `#CODE` to `#CODE` block). I wonder how much use that really was for batchcode though and how many actually designed their batchcode files to be run that way ...  

Comments, critiques, other ideas?

**Comment by Griatch** [comment]
Implemented.
