### ISSUE TITLE
Support for Python 8

### ISSUE THREAD

**Issue by Kelketek** [evennia/evennia#942]
#### Brief summary of issue / Description of requested feature:
Python 8 is on the horizon, with an alpha version landing in https://hg.python.org/cpython/rev/9aedec2dbc01 . There are no direct semantic changes to features, but PEP8 is now enforced. See https://mail.python.org/pipermail/python-dev/2016-March/143603.html for more information.

#### Steps to reproduce the issue / Reasons for adding feature:

1. This is where the community is going
2. It will result in the most pure and beautiful code
3. To do otherwise would be to blaspheme

#### Error output / Expected result of feature

Beauty, endless and eternal. Nomenclature in perfect alignment. World peace.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This will require some assistance from the Twisted team. There is a slight problem in that the head developers of Twisted were recently committed to an inpatient mental health hospital. Attempts to get them to explain what's wrong have only managed to extract the phrase 'Practicality beats purity' from their lips.

**Comment by Griatch** [comment]
One of those days ... our Python 7 support is not even done yet!

**Comment by j3b4** [comment]
Is this a project suitable for a beginner?  Maybe I can get a head start on learning Python 8 before I'm irreparably corrupted by exposure to 2.7.

**Comment by Kelketek** [comment]
@j3b4 I think it would be an excellent way to start, yes. It could allow the creation of a pure developer who is untainted by the inconsistencies of the past.

**Comment by stefanludlow** [comment]
I'll start the hunt for a millennial for exactly this purpose.

**Comment by Flaise** [comment]
If you want actual purity, the project is bigger than it looks. First off, if you aren't using a purely open source distribution of Linux or Unix, you should be. When/if you are, delete your Perl interpreter and update all of its dependents to use Python instead. Publish the new versions to the Apt repositories and open tickets with the maintainers of these pieces of software to delete the old versions out of their respective Apt repositories.

This will probably require rewriting core components of the operating system so this project may as well include cleaning up the Linux kernel by rewriting it all. In Python. This will of course require specialized hardware so it would be best to start with emulators written in Python. Running on Linux. When the hardware is finally invented, it would probably be wise to take the time to make sure that their BIOSes are written in pure Python.

It won't happen overnight but I am confident that this is an achievable and worthwhile goal. Seeing as Python will become such a useful language as a result of this project, we should all stop speaking in English or whatever languages we speak and communicate purely in Python. Once the rewriting is all done, the processing power available should be pure enough to begin research on replacing one's neurons with equivalent ones that are compatible with Python. At that point, it will become possible and reasonable to plug ourselves into life support machines so we no longer have to eat, drink, sleep, or do anything that does not involve thinking in pure Python.

**Comment by Griatch** [comment]
I'll close this for now, maybe we'll revisit it in another year to see what progress was made. :)
