### ISSUE TITLE
Devel: Webclient Prompt not displaying correctly

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#950]
#### Brief summary of issue / Description of requested feature:

The devel-branch webclient is not currently displaying the prompt area correctly.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Connect to game running on devel ("wclient") branch Evennia.
2. Log in as superuser.
3. Run `@py self.msg(prompt="foo")`

#### Error output / Expected result of feature

The prompt displays over the input area, skewing the input area and starting to show overlapping flow-text. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Devel "wclient" branch.

**Comment by Griatch** [comment]
Pinging @natepri since it seems related to the input line (the prompt could not be tested during in the last PR since there was a bug server side that is now fixed).

**Comment by NatePri** [comment]
Ah, very likely my changes. Lemme take a look.

**Comment by Griatch** [comment]
Merged Fixed into wclient branch. Closing.
