### ISSUE TITLE
Devel: Making the webclient aware of closing server

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#951]
#### Brief summary of issue 

When the server shuts down or is killed, the devel-branch webclient is currently unaware of it - one can still use the interface (although you don't get any returns, obviously). The effect is quite confusing for the player. 

#### Expected result of feature

The client should somehow notify the user that the server has gone away, either by a popup or by some sort of text. Either way one should not be able to continue using the client when the server is no more able to retrieve what it sends. 

I wonder if the client could somehow regularly ping the server to see it is still there. If it is easier I suppose we could also send an explicit command from the server telling the client that it's going away (this will not work if the server is killed in an uncontrolled way).

**Comment by Griatch** [comment]
pinging @natepri,  maybe you have some ideas/input on this?

**Comment by NatePri** [comment]
Looking at what happens in the debugger when I stop evennia, it fires connection_close and connection_error events from the emitter, but they seem to be silently ignored by the GUI. It seems like we should be able to just hook into these to show some sort of error message, without requiring any special messaging from the server.

Ideally, you'd want there to be a way to try to re-establish the connection as well. I'm not sure what sort of behavior you'd want for reconnection; should it try to reconnect automatically (probably with a limited number of retries to avoid inadvertently DoSing the server whenever there's a hiccup), or wait for user input to try to do the reconnect? Either way, I'd think it shouldn't be hard to do.

**Comment by Griatch** [comment]
Hah, you are right about connection_close/connection_error. I forgot about those, they are indeed the way to go for server info to the server. In an older version, there was a window alert-box for this, not sure if that is the way to go, or if one should display it some neater way. 

The AjaxCometConnection should ideally work in the same way as the websocket one. I suppose the close/error messages should work with the ajax connection too, but if it was possible to have it identify an erroneous connection it may be useful (I don't know how hard that would be though). 

Good point about allowing the client to reconnect. I think maybe a combination of the two options may be best for the user: Try automatically a few times (telling the user what is going on), and then pop up some sort of button to let the player choose when to try again.

**Comment by Griatch** [comment]
I implemented callbacks for the gui to report when the server goes away. I don't try to re-connect though, probably better to let this be an explicit action. This seems to work just fine for both websocket and AJAX/COMET. 

The problem was rather the other way around - making the server aware of a gone/dead client. It's not a problem for websockets, but for AJAX/COMET, Evennia is passive and will wait indefinitely for the next request. So I added a custom keepalive LoopingCall server-side that will send a special `ajax_keepalive` instruction to the client - this is caught already in the AjaxConnection handler and immediately triggers a reply. If the keeapilve times out (it tries every 30 seconds unless the client is showing signs of life on its own) the Session is disconnected cleanly from the server. Seems to work fine. 

@NatePri: Any input on the code are welcome. :)

**Comment by NatePri** [comment]
Sorry for being quiet; been dealing with some personal matters on my end so I haven't had a chance to look into this much. The code looks good from my end; I added some notes. I'll see about writing logic to hook it up to the UI this weekend. You're probably right about not doing an automatic reconnect though.
