### ISSUE TITLE
Bug: @examine can't find player, yet reports player's dbref

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#954]
#### Brief summary of issue / Description of requested feature:
The **@examine** command `"Could not find 'BlauFeuer(player 3)'."`

#### Steps to reproduce the issue / Reasons for adding feature:

1. Connect/login to test server horizondark.com:4444 as a builder class player (its default)
2. **@examine *BlauFeuer** or **@examine/player BlauFeuer**

#### Error output / Expected result of feature
`"Could not find 'BlauFeuer(player 3)'."` or similar when expected result should detail the player object and its attributes.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Occurs in recent revision/main branch, Linux and Windows OS. 
Search function issue, or parameters not correctly entered into search function?

```
[Public] BlauFeuer: Ugh. Is this intended behavior? ex *BlauFeuer yields: Could not find 'BlauFeuer(player 2)'.
Could not find 'BlauFeuer(player 3)'.
[Public] BlauFeuer: It knows I'm player 2 (or player 3 here, for example), but it can't "find" my player object?

Permission Hierarchy (climbing):
 Guests, Players, PlayerHelpers, Builders, Wizards, Immortals
Your access:
Character BlauFeuer: builders
Player BlauFeuer: builders
[Public] Griatch@#evennia: That does looks a bit weird, I agree.
```

**Comment by Griatch** [comment]
The reason for this is a combination of a Builder having neither `examine` nor `view` rights on a Player object (Wizard permission or higher is needed for that). The error messsage was made a little clearer. This will close when the wclient branch merges.
