### ISSUE TITLE
@help/force expects optional lock string

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#955]
#### Brief summary of issue / Description of requested feature:
```
Usage:
  @help[/switches] <topic>[,category[,locks]] = <text>
```
Using the /force switch causes error when category is supplied but lock string is not supplied.

#### Steps to reproduce the issue:

1. **@help/add Baloney,System=System baloney help topic**
2. **@help/add/force Baloney,System=Not a real help topic**

#### Error output / Expected result of feature
```
Traceback (most recent call last):
/evennia/evennia/commands/cmdhandler.py", line 435, in _run_command
     ret = yield cmd.func()
File "/evennia/evennia/commands/default/help.py", line 255, in func
     old_entry.locks.add(lockstring)
File "/evennia/evennia/locks/lockhandler.py", line 306, in add
     self._log_error(_("Lock: '%s' contains no colon (:).") % lockdef)
File "/evennia/evennia/locks/lockhandler.py", line 192, in _log_error
     raise LockException(message)
LockException: Lock: '' contains no colon (:).
```
Feature otherwise appears to work as expected.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Current revision/Main branch
Add default lock of view:all() when no lock is given if entry does not already have a lock.

**Comment by Griatch** [comment]
Resolved in wclient branch. This will be closed when it merges.
