### ISSUE TITLE
help categories are secretly case-sensitive

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#956]
#### Brief summary of issue / Description of requested feature:
**help** entries separated by categories are case-sensitive and displayed separately, yet the category is presented as if they are non-case-sensitive.

#### Steps to reproduce the issue / Reasons for adding feature:

1. **@help/add Baloney,System=System baloney help topic**
2. **@help/add Salami,system=A real meaty help topic**
3. **help**

#### Error output / Expected result of feature

```
------------------------------------------------------------------------------
  Other help entries
------------------------------------------------------------------------------
  System:
Baloney
  System:
Salami
```
Expected Baloney and Salami to share the same category.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Current revision/Main branch
Lower case all category entry strings upon saving, uppercase all upon presentation.

**Comment by Griatch** [comment]
Fixed in wclient. Will closed when it merges.
