### ISSUE TITLE
Extend @options command to allow /save, include word wrap to column size

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#957]
#### Description of requested feature:

Saving defaults from use of **@option** command on the player object with **/save** switch option for specific Boolean choices that a player might use regularly  and word wrap on/off at column-width will allow a player to log in to defaults of their own choosing and change them on a session level so they can choose specific settings for a client they might be using in one session, but not another.

#### Reasons for adding feature:
Because of the vast differences in client capability, there is no single default that can be used.  Some people use the minimum functioning client they can find at the moment, which might be a command line telnet or minimally compliant client that needs some features stripped but not others.

Others may expect that once the options are chosen, the next session login will use those defaults, if saved.

#### Expected result of feature

There should be no need to globally disallow features such as blink, or expect all clients to do word wrap when **@options** can be used to manually select and **/save** default behavior per player. 

When the player is aware of what the options do, the player should have manual control and set default behavior

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

The wclient branch features a dictionary of these settings that would make adding this functionality much easier than it would be to add in the current main branch, and the features would not interfere with default settings. It only improves the user experience and only in ways that the user chooses.

```
        validators = {"ANSI": validate_bool,
                      "CLIENTNAME": utils.to_str,
                      "ENCODING": validate_encoding,
                      "MCCP": validate_bool,
                      "MXP": validate_bool,
                      "OOB": validate_bool,
                      "SCREENHEIGHT": validate_size,
                      "SCREENWIDTH": validate_size,
                      "SCREENREADER": validate_bool,
                      "TERM": utils.to_str,
                      "UTF-8": validate_bool,
                      "XTERM256": validate_bool,
                      "INPUTDEBUG": validate_bool}

```

**Comment by Griatch** [comment]
Implemented in wclient branch. Adding this feature was a lot more complex than expected. 
Will close when branch merges into master.

**Comment by Griatch** [comment]
Closed as wclient branch has merged.
