### ISSUE TITLE
Unhandled error in Deferred, multiple sessions, default config, wclient branch

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#962]
#### Brief summary of issue

I'm not entirely sure if the steps to reproduce are what caused the error, since I pulled the error out of the log later while looking for my own traceback on an unrelated issue. 

Apologies for the vagueness of this report, but per conversation, I am including it without further investigation at this time.

#### Steps to reproduce the issue

1. Via telnet: connect to character: `@ic <character>`
2. join with a second client and connect to same character.
3. Boots first session, then generates error.

#### Error output

http://pastebin.com/9M3XCsXD

```
 (In case pastebin ages; summary, last line)
       File "evennia/evennia/server/portal/portalsessionhandler.py", line 372, in data_out
        for cmdname, (cmdargs, cmdkwargs) in kwargs.iteritems():
    exceptions.ValueError: too many values to unpack

```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

```
unhandled error in Deferred is important: http://pastebin.com/9M3XCsXD I was getting it when my sessions kept flip-flopping.
[Public] Griatch@#evennia: Blau: Looks like a proper bug, make an issue for it and how to reproduce it.  (I presume it's wclient branch)
[Public] BlauFeuer: Yes, now I just have to reproduce it. I think it's when I was running two sessions at once.
[Public] Griatch@#evennia: Blau: Actually, I know where the error is, just put the link to your pastebin in the issue and refer to this conversation.
```

**Comment by Griatch** [comment]
The pertinent part of the traceback is the `_portal_maintenance` call which happens without proper form handling: 
```
 File "evennia/evennia/server/portal/portal.py", line 90, in _portal_maintenance
        session.data_out(text=reason)
      File "evennia/evennia/server/portal/telnet.py", line 271, in data_out
        self.sessionhandler.data_out(self, **kwargs)
      File "evennia/evennia/server/portal/portalsessionhandler.py", line 372, in data_out
        for cmdname, (cmdargs, cmdkwargs) in kwargs.iteritems():
    exceptions.ValueError: too many values to unpack
```

**Comment by Griatch** [comment]
Fixed in wclient branch.

**Comment by BlauFeuer** [comment]
The current behavior is still problematic - it currently kills the newest (second of two) session connect instead of oldest (first).

This might be intended behavior: a second session can not join to take over the first.

But in cases where the first connection is stalled, the second session is simply disconnected until the first times out, and there is no mechanism in single mode to deal with booting a connection that is no longer working.

**Comment by Griatch** [comment]
@BlauFeuer 

It may be an issue but it's unrelated to the traceback of this issue. Please open a new issue.
