### ISSUE TITLE
@tel north causes untrapped error 

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#963]
#### Brief summary of issue / Description of requested feature:

`@tel` north causes untrapped error: unsupported operand type(s) for +=: 'NoneType' and 'str'

Exit aliases should be checked. Even if not checked, when exit object can be found in the room, that exit should be the target exit for the @tel command.
If no local exit is found, then return a message regarding no found exit.

#### Steps to reproduce the issue / Reasons for adding feature:

When north is the alias of an exit (as is the case in Cliff by the coast room):

1. `@tel north`
or
`@tel/intoexit north`

Teleporting to an exit normally sends character to the exit's destination, but this breaks when the teleport refers to the exit by name.

Teleporting into an exit this way breaks the same way.

#### Error output / Expected result of feature

```
   File "/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
     ret = yield cmd.func()
   File "/evennia/evennia/commands/default/building.py", line 2271, in func
     destination = caller.search(lhs, global_search=True)
   File "/evennia/evennia/objects/objects.py", line 388, in search
     nofound_string=nofound_string, multimatch_string=multimatch_string)
   File "/evennia/evennia/utils/utils.py", line 1558, in at_search_result
     result.get_extra_info(caller))
 TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

```

Expected `Teleported to northern path.` 
Expected the same behavior as if `@tel northern path` or `@tel #15`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia most recent wclient branch, any OS 

Check for match against local room's exits for alias, then fail with appropriate message if not found.

**Comment by Griatch** [comment]
Fixed in wclient; since this was reported against the wclient branch, this closes.
