### ISSUE TITLE
Better error message when trying to create a location-loop

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#964]
#### Brief summary of issue / Description of requested feature:

Couldn't perform move ('location change'). Contact an admin. + RuntimeError

@tel <into something you're carrying - by number or name>
Couldn't perform move ('location change'). Contact an admin.

Perhaps raise exception to handle?

#### Steps to reproduce the issue / Reasons for adding feature:

1. get test object
2. `@tel test object`

#### Error output / Expected result of feature

Couldn't perform move ('location change'). Contact an admin.

```
 Error: TestSubject.location = TestObject creates a location loop.
 Traceback (most recent call last):
   File "evennia/evennia/objects/objects.py", line 654, in move_to
     self.location = destination
   File "/evennia/evennia/objects/models.py", line 249, in __location_set
     is_loc_loop(location)
   File "/evennia/evennia/objects/models.py", line 247, in is_loc_loop
     return is_loc_loop(loc.db_location, depth + 1)
   File "/evennia/evennia/objects/models.py", line 244, in is_loc_loop
     raise RuntimeError
 RuntimeError

```

Handle an exception, return False or no success message suggesting cause.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Most Recent wclient branch, any OS, clean install + tutorial

**Comment by Griatch** [comment]
This error is clear from the traceback - performing the move will create a location-infinite loop.

**Comment by Griatch** [comment]
Closed in wclient branch, since this was filed against wclient branch, this closes.
