### ISSUE TITLE
`@lock <partial name match>` yields untrapped error

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#965]
#### Brief summary of issue / Description of requested feature:

AttributeError: 'function' object has no attribute '__qualname__'

when `@lock <partial name match>` and no control access, but player has examine access to lock.

Request allowing partial match or trapping error

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@lock <partial name match>`
or
`@lock <partial name match>=`
or
use reference by database #

Partial matching is useful if full name match fails - finding local object to display its locks.

#### Error output / Expected result of feature

AttributeError: 'function' object has no attribute '__qualname__'
```


 Traceback (most recent call last):
   File "/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
     ret = yield cmd.func()
   File "/evennia/evennia/commands/default/building.py", line 1807, in func
     caller.msg(obj.locks)
   File "/evennia/evennia/objects/objects.py", line 509, in msg
     session.data_out(text=text, **kwargs)
   File "/evennia/evennia/server/serversession.py", line 362, in data_out
     self.sessionhandler.data_out(self, **kwargs)
   File "/evennia/evennia/server/sessionhandler.py", line 621, in data_out
     **kwargs)
   File "/evennia/evennia/server/amp.py", line 467, in send_MsgServer2Portal
     return self.send_data(MsgServer2Portal, session.sessid, **kwargs)
   File "/evennia/evennia/server/amp.py", line 406, in send_data
     packed_data=dumps((sessid, kwargs))
   File "/evennia/evennia/server/amp.py", line 319, in <lambda>
     dumps = lambda data: to_str(pickle.dumps(to_str(data), pickle.HIGHEST_PROTOCOL))
   File "/pyenv/local/lib/python2.7/site-packages/twisted/persisted/styles.py", line 119, in _pickleFunction
     tuple([".".join([f.__module__, f.__qualname__])]))
 AttributeError: 'function' object has no attribute '__qualname__'

```

Expected viewing of locks output:
Locks:call:true(); control:perm(Immortals); delete:perm(Wizards);
      edit:perm(Wizards); examine:perm(Builders); get:all();
      puppet:pperm(Immortals); tell:perm(Wizards); view:all()

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Locks:call:true(); control:perm(Immortals); delete:perm(Wizards);
      edit:perm(Wizards); examine:perm(Builders); get:all();
      puppet:pperm(Immortals); tell:perm(Wizards); view:all()

Permission Hierarchy (climbing):
 Guests, Players, PlayerHelpers, Builders, Wizards, Immortals
Your access:
Character SuperTester: <Superuser>
Player SuperTester: <Superuser>

Most recent wclient branch, any OS, clean install + tutorial

**Comment by Griatch** [comment]
Fixed in wclient. Since issue was filed directly against wclient branch, this now closes.
