### ISSUE TITLE
"If you go |lcnorth|ltto the north|le you will find a cottage. causes blank output

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#966]
#### Brief summary of issue / Description of requested feature:

Substituting |lc, |lt, |le for {lc, {lt, and {le in any message causes no output

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@emit If you go |lcnorth|ltto the north|le you will find a cottage.`
2. `say If you go |lcnorth|ltto the north|le you will find a cottage.`
3. `pose directs you to go |lcnorth|ltto the north|le, where you will find a cottage.`

#### Error output / Expected result of feature

No output; output expected.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

most recent wclient branch, any OS, clean install + tutorial

Use | as the inline function character and depreciate {

**Comment by Griatch** [comment]
This is resolved in wclient, and since this issue was made against the devel branch, this closes.

**Comment by BlauFeuer** [comment]
Thanks, this one was bugging me. Fortunately I made sure to put it in a function so I wouldn't have to recode it in a bunch of places.  When this gets pushed to main, I'll update the tutorial that mentions using the { character.
