### ISSUE TITLE
Second player session disconnected, should boot first session with message.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#968]
#### Brief summary of issue / Description of requested feature:

Issue #962 closed, but not implemented

#### Steps to reproduce the issue / Reasons for adding feature:

1. `Via telnet: connect to character: @ic <character>`
2. `join with a second client and connect to same character.`

#### Error output / Expected result of feature

Boots second session, should boot first session with message.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Fix in wclient branch altered behavior, see Issue #962 closed, but not implemented

The current behavior is still problematic - it currently kills the newest (second of two) session connect instead of oldest (first).

This might be intended behavior: a second session can not join to take over the first.

But in cases where the first connection is stalled, the second session is simply disconnected until the first times out, and there is no mechanism in single mode to deal with booting a connection that is no longer working.

An issue caused by the fix of #962 but it's unrelated to the traceback of that issue.

**Comment by Griatch** [comment]
Ah, you are right, #962 fixes the traceback but I didn't consider the other part of the issue concerning the session booting order. Reading comprehension error! Sorry for making you open a new one!

**Comment by Griatch** [comment]
@BlauFeuer 

I cannot reproduce this: In `MULTISESSION_MODE=0`, connecting to an existing character will boot the old Session and replace it with the new one. I tested this the following way: 
```
[connecting, client A]
>>> self.sessions.all()[0].sessid
1
[connecting, client B, kicks client A]
>>> self.sessions.all()[0].sessid
2
[connecting, client A, kicks client B]
>>> self.sessions.all()[0].sessid
3
```
And so on. There is only ever one session in the session list, I checked. Here one can see that the `sessid` keeps increasing as I connect with subsequent sessions - this suggests the old session is replaced by the new one. 

Is there some particular settings or calls you do to see the effects of this issue?

**Comment by BlauFeuer** [comment]
I tested this in 3 clients and against my game code and a clean install and can't reproduce it, so it's either fixed in evennia or it was an issue with my game code.  I'll close it and thank you for fixing the original issue and looking into this one.
