### ISSUE TITLE
Persistent EvMenu goes back a step when @reload-ing

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#969]
### Brief summary of issue

When a player (possibly a character, too) is in a menu and Evennia is reloaded, the user finds him/herself back at the previous node.

#### Example

1. The player enters his first name (node 1).
2. He then enters his last name (node 2).
3. He then has to enter a gender (node 3) but...
4. The server is reloaded.
5. No message is displayed, but the users finds himself back in the last name menu (node 2).

#### Rationale

This behavior is quite puzzling.  Since no message is displayed, users continue to follow the character creation process, but they get errors (in my case) since they should have entered the same information twice without notice.  I don't know whether this behavior also applies to character menus, however.

**Comment by Griatch** [comment]
@vlegoff 

Would it be possible to get a small example menu showing this effect to test against ...?
.
Griatch

**Comment by vlegoff** [comment]
The menu that is behaving strangely can be seen here: [https://github.com/vlegoff/mud/blob/master/menu/character.py](https://github.com/vlegoff/mud/blob/master/menu/character.py)

It's a menu designed to create a character when a player isn't necessarily linked to only one character.  The menu is called after login (which is a seperate menu).

Hope that helps,

**Comment by Griatch** [comment]
A 450-line menu is not a "small example" but I'll make do, it will just take longer before I can build a test environment to check it.
