### ISSUE TITLE
Going home message follows arrival (wrong order)

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#975]
#### Brief summary of issue / Description of requested feature:

Going home message follows arrival (wrong order) when using default home command.

#### Steps to reproduce the issue / Reasons for adding feature:

1. While IC, go anywhere but home
2. use home command.

Reasons: saves me from overwriting the command to fix.

#### Error output / Expected result of feature
`<arrival>`
`There's no place like home ...`

Expected:
`There's no place like home ...`
`<arrival>`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Current revision, master and wclient branches, all OS

Put the message before the move:
```
caller.msg("There's no place like home ...")
caller.move_to(home)

```
https://github.com/evennia/evennia/blob/master/evennia/commands/default/general.py#L38
https://github.com/evennia/evennia/blob/wclient/evennia/commands/default/general.py#L38

**Comment by Griatch** [comment]
Why exactly *is* the message expected before the move? Is it not more reasonable to arrive at the location and express that there is no place like it?

**Comment by BlauFeuer** [comment]
That's the way it is elsewhere on other mu* (message, then arrival), verbatim - so it seems like a standard message. 

The messages ellipses conotes something will follow, which is the arrival.

The backstory to this message is that it is uttered by the character Dorothy in L. Frank Baum's original novel, _The Wonderful Wizard of Oz_ (1900) as she clicks the heels of her silver slippers   three times and repeats the phrase, "There's no place like home." just _before_ being transported home.

**Comment by Griatch** [comment]
Hah! Well argued, bringing Dorothy to your side. Alright then.

**Comment by BlauFeuer** [comment]
Just tried this on a mush:
```
There's no place like home...
There's no place like home...
There's no place like home...
Big Rock Candy Mountain(#6333Rn)
An empty piece of land with a small mailbox in the front. Beautiful mountain scenery surrounds you.
```

and a muck:
```
There's no place like home...
There's no place like home...
There's no place like home...
You wake up back home, without your possessions.
Walmart's Sporting goods(#9138RLJA)
Items are placed nicely about except for the fishing rods, which seem to be set haphazardly together.
```

I think three times is not really necessary.
