### ISSUE TITLE
Webclient glitches output on underline, blink, and reverse.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#976]
#### Brief summary of issue / Description of requested feature:

When sending |u, |*, and |^ to the client, it produces: `">`, `]7`, and `]5` as the output text.

#### Steps to reproduce the issue / Reasons for adding feature:

1. connect using web client
2. receive text with any of the tags: `|u` `|*`, or `|^`
3. observe how the web client interprets the markup.

#### Error output / Expected result of feature
web client displays: `">`, `]7`, and `]5` as the output text,
instead of underline, reverse, and blink.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.6.0 (rev 5353b66) master branch, any OS, any browser.

Probably a typo or incomplete regexp for this markup. I have only tried two different clients, and not yet looked into the code.

**Comment by BlauFeuer** [comment]
Note that the underline markup `|u` outputs `">` to a telnet client.  That part of the problem is not limited to the web client.

**Comment by Griatch** [comment]
This is probably due to the optimizations done for generating the regexes for xterm256 in the web client.

**Comment by BlauFeuer** [comment]
It's not too critical at all - just something I wanted to note so the issue with these three markup tags isn't forgotten.  

Initially I thought it was related to displaying or interaction with MXP tags, but after some time found it was not the case.

**Comment by BlauFeuer** [comment]
Can't reproduce this in telnet anymore for the underline markup, but confirmed it still occurs in web client only - hence the issue name change again.
