### ISSUE TITLE
@option setting to toggle Telnet keepalive NOP

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#977]
#### Brief summary of issue / Description of requested feature:

While the Telnet keepalive is a great solution when TCP/IP keepalive is not possible or workable, sometimes the feature causes problems with non-compliant Telnet-based clients.

The feature requested is to allow toggling off of the Telnet keepalive NOP sent by the server via an `@option` setting for cases where it is not effective, wanted or needed.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use a buggy client, such as mudlet, mukluk, old versions of BeipMU, 8-bit "FANSI" or any other under-developed client that isn't compliant/does not respond correctly to IAC.
2. Observe spurious characters frequently displayed by the client, the specific characters depending on the client's encoding settings.

Reasons are that giving the option to toggle off a very well-intended default feature of Evennia gives the user the choice. If connection drop-out persists when toggling off this feature, often other methods are possible, including sending a plain-text ping and having the client gag it instead of high-bit characters.

#### Error output / Expected result of feature

Spurious characters are sometimes seen as ÿõ, ÿñ, [nbsp]± depending on encoding, and seems to be caused by the display of characters 255 & 241 decimal, or FF B1 hex, which the client should not be displaying.

Best results are that these non-compliant clients that some people have grown comfortable with or find as their best or only option can forego the advantages of Telnet keepalive if they do not require it, or use an alternate keepalive method (or just be very attentive), and not suffer the frequent _gremlin_ characters being displayed while they spend time enjoying an Evennia mu*.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

current revision, master branch, all OS;
requires a new Boolean flag for the session being presented as an option in `@option` settings table and the portal testing that flag before sending the keepalive to that session.

**Comment by Griatch** [comment]
Implemented and closed. Any bugs should be made as a separate issue.
