### ISSUE TITLE
Color formatting of MXP commands not displayed in web client in certain format

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#979]
#### Brief summary of issue / Description of requested feature:
When coloring display text for a MXP command in this format:

` |c |lc command |lt display text |le |n`

It appears correctly colored in telnet clients but not in the web client

However, this format work in both
`|lc command |lt |c display text |n |le`

The discrepancy requires attention being given to formatting for web client appearance,
and using the first format leads to disparity between client views.  This needs addressing.
 
#### Steps to reproduce the issue / Reasons for adding feature:

1. in web client after `@ic`, `say |c |lc command |lt display text |le |n`
2. Contrast with `say |lc command |lt |c display text |n |le`
3. Compare with telnet connection with ANSI color-enabled mu* client.

#### Error output / Expected result of feature

No error, but color intensity seems to change in web client, but not the hue,
while in the telnet client, the intensity and hue are both displayed as intended.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.6.0 (rev 5353b66) main branch all OSes.

Related to issue #976

**Comment by Griatch** [comment]
The reason for this is that `|lc command |lt |c display text |n |le` will produce this HTML output:

````html
<a id="mxplink" ... >
  <span class="color-014">
      display text
 </span>
</a>
````

Whereas `|c |lc command |lt display text |le |n` will create this:

````html
<span class="color-014">
  <a id="mxplink" ...>
     display text
  </span>
</span>
````
In the latter case, the inherent CSS color of the anchor (white) is taking precendence over the color given in the parent `<span>` class. This inheritance is how CSS works; I don't know if it's possible to set the color of the link to somehow be susceptible to the parent's color *only* if such a color exists (we want normal links (not mxp links) to have a settable colors too after all).

**Comment by Griatch** [comment]
How about that, there's an 'inherit' CSS property that resolves this. This means links will not have any default colors (white before) but will just be underlined; but it does make the look the same between telnet and web. Closing.
