### ISSUE TITLE
Errors in extended_room when looking at non-existent details

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#981]
#### Brief summary of issue / Description of requested feature:

When using the `extended_room` contrib module, a stack trace is generated when a character attempts to `look` at a detail that has not been defined.

Secondarily, if a detail key is selected that is a substring of the room's name, the detail description is never shown, presumably because the room is being found first by `caller.search()`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a room with the contrib.extended_room.ExtendedRoom typeclass named "Bridge over the River"
2. From within the room, enter `look nonexistent` - traceback is generated
3. Create a detail with a key of "river"
4. enter `look river` - the room's description is printed instead of the detail

#### Error output / Expected result of feature

It would seem that looking at a non-existent detail should return "Could not find 'nonexistent'".

Also, because the default `look` command with no arguments targets the caller's location, it seems that these detail key collisions could be handled by excluding the location itself from `candidates` when searching in the ExtendedLook cmd.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.6 - master

**Comment by BlauFeuer** [comment]
My first question to the community was about making an improvement to fix this bug.
https://groups.google.com/forum/#!category-topic/evennia/evennia-questions/lIjFtHtf44Q

In the tutorial world, the "Underground Passages" room's alias "passages" conflicts with the look detail "passages" and the room's alias gets priority, so the room detail is never seen.

**Comment by feend78** [comment]
I've checked through the code, and while the TutorialRoom functionality is very similar to the ExtendedRoom functionality, they do diverge in certain respects. This issue was found in the course of Ainneve development, which is only affected by extended_room module. However, pull request #982 could be used as a reference by anyone who wants to fix the similar issue in the tutorial world.

**Comment by Griatch** [comment]
I'll leave this open for now, if someone is willing to submit a PR towards TutorialRoom along the same lines.
