### ISSUE TITLE
Clarify the way to overload django views

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#988]
It is not obvious what the best way to overload a django view is. This is an important part of customizing the web  experience, but it is not obvious how to do it from outside the core library. 

Detailing the best practice (maybe also figuring out the best practice!) needs to be done in docs and maybe in an updated web tutorial.

**Comment by Kelketek** [comment]
For reference, this should be possible by placing a URL pattern that matches above the imported ones. Whatever matching URL pattern is found first determines what view is called.





On Wed, Jun 1, 2016 at 12:33 PM -0700, "Griatch" <notifications@github.com> wrote:












It is not obvious what the best way to overload a django view is. This is an important part of customizing the web  experience, but it is not obvious how to do it from outside the core library. 



Detailing the best practice (maybe also figuring out the best practice!) needs to be done in docs and maybe in an updated web tutorial.

**Comment by Griatch** [comment]
Implemented as an extension of the [Web Features page](https://github.com/evennia/evennia/wiki/Web%20features).
