### ISSUE TITLE
inline functions processing disables MXP encoding and strips markup and some characters in msg output

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#989]
#### Brief summary of issue / Description of requested feature:

inline functions not playing well with other markup. If trying to output any of these  `\?><|+@$+` characters in the output of the inline function or on the same line with the output are also stripped when present in the msg string with inline functions, markup and text.

 / For inline functions to be useful, additional markup should also be processed depending on options to msg.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Enable inline functions processing with `INLINEFUNC_ENABLED = True` in settings.py
2. `say The $world() is |lc@OOC|lt|111gray|n|le.`
3. `pose $clr(|g,finds that these are the missing characters: \\?><|+@$+)\?><|+@$+`

#### Error output / Expected result of feature
`<character name> says, "The <unknown> is |lcOOC|lt|111gray|n|le."`
`<character name> finds that these are the missing characters:`

Expected the display of processed markup with an MXP command link of gray text for the word "gray" and did not expect certain characters to be stripped when output.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.6.0 (most current rev) main branch, any OS

* Output (or existence) of the inline function does not seem to be a factor.

* Notice that any `\\?><|+@$+` characters are also stripped.

* The error occurs in output via both telnet and websocket.

**Comment by Griatch** [comment]
Well, I know *why* these characters are not detected - they are not included in the part of the regex that handles non-function components. But simply adding them them leads to other issues, at least so far.
