### ISSUE TITLE
Feature request: kwargs option for search mechanism to treat #dbref as any string.

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#990]
#### Brief summary of issue / Description of requested feature:
Feature request / Sometimes a search may need to be done in a way that disallows `#dbref`

#### Steps to reproduce the issue / Reasons for adding feature:
Example demonstrates use case, but not specifically the problem:
1. While `@quell` or having only players permissions:
2. While not in `Limbo (#2)`, `l #2`
3. Notice that you can view remotely.

Reason for disallowing: By default, providing a target string always allows searching by `#dbref`, but users should not always be allowed this ability, so a mechanism to treat the `#dbref` as any other string would make the search function more flexible and reduce coding in use cases that require escaping or filtering the `#` or `*` followed by an integer or player name.

#### Error output / Expected result of feature
An example of the pervasiveness of searching by database id instead of only by string is in the look command:  `Look` output shows remote room (other commands may also allow `#dbref` when it should not.

Expected result of feature is allowing search to be done either with or without processing of `#dbref` depending on additional code conditional on permissions.  (i.e. Evennia shouldn't allow everyone to search by database id in every default command - only builders and higher players.)

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Latest revision/ master branch/ all OS

### initial discussion
```
BlauFeuer: Is there a search option that disallows the database numbers?
Griatch@#evennia: Blau: Disallows, what sense?
Griatch@#evennia: So you search by #dbref and you won't search for a #dbref?
BlauFeuer: For example, in CmdLook... self.target = self.caller.search(self.args)  When
`    the look command is given as "look #32", I can remotely see Underground passages`
`    from the Limbo.`
BlauFeuer: By default, any character can look anywhere at anything via #db.
BlauFeuer: Do I parse for # as a leading character or is there a form of search that`
`    doesn't allows database references?`
Griatch@#evennia: No, the underlying search mechanisms should allow search by #dbref; 
`    one would need to filter it out.`
Griatch@#evennia: It's however a good idea that the default .search mechanism should
`    probably allow you to do so with a kwarg.`
BlauFeuer: Is it easier to add an option to search to filter * and # references?
Griatch@#evennia: Hm.
BlauFeuer: For this sort of search in CmdLook, I will have to override that kind of behavior
`    if I don't want characters spying ahead or peering at the world's objects remotely by`
`    guessing at database numbers.`
Griatch@#evennia: Yeah, I see the use case.
Griatch@#evennia: one could filter on #dbref, but it would be cleaner if one could indeed`
`    tell the search mechanism to treat #dbref as any string.`
BlauFeuer: Yes, if you see it as a valid use case, I'll ask for a feature.
Griatch@#evennia: You can patch it yourself rather easily by overloading search, but it`
`    would probably be better to allow to change it more fundamentally. `

```

**Comment by BlauFeuer** [comment]
To set up such a query, I bypassed search and used a filter until there's an easier way built-in:
```python
        keyquery = Q(db_key__istartswith=self.args)
        aliasquery = Q(db_tags__db_key__istartswith=self.args,
                       db_tags__db_tagtype__iexact="alias")
        results = ObjectDB.objects.filter(keyquery | aliasquery).distinct()
```

**Comment by Griatch** [comment]
@BlauFeuer  
I simply gave `obj.search()` a new keyword `use_dbref=True`, set to `False` to treat `#dbref` as any string.

**Comment by Kiramin** [comment]
I would sat this counts as a bug and not a feature request. The same behavior allows anyone to "get" anything from anywhere using its dbref. Anyone could type "get #1234" and if such an item exists and "get" isn't locked for that user/item, it will zip to them even if it is half way across the world, in another players inventory, or behind a locked door.

**Comment by BlauFeuer** [comment]
It's a bug in the command, but typically they're the first thing someone would customize.  `get` was one of the first commands I replaced.

It's a feature request to the framework to ask for the search to be able to specify ignoring #dbref.  Typically you'd only want builders to use them.
