### ISSUE TITLE
Feature Request: Generalize Channels

### ISSUE THREAD

**Issue by MixKCet** [evennia/evennia#994]
#### Current State of Channels:

As it stands, Channels represent a way of centralizing functionality for player-to-player communication with several neat, automated features:
1. Generation of ALIASES based on Channel key
2. Subscription-based model with PERMS
3. Msg object for persistence and meta-info

#### Request: Broaden Channels to be IC, or OOC

1. An opt-out for a Channel to generate 'aliases' based on their key
2. An opt-out for a Channel to revert to Player in attempting to find subscriptions / perms

There's a potential use case of object-to-object Channels used to store-and-retrieve IC communication. For instance, in fantasy MUs characters might chat with their organizations through telepathy, or for sci-fi MUs, IC 'chat rooms'. 

A Channel could also be used passively, to store logs of room communication for players to later convert into logs, or use skills IC to view the 'history' of a location.

Additionally, by having the persistence of Channels, you could easily convert your MU* into a 'drop-in-and-play' style of PbP game.

### Further Use Case: OOC Messaging

1. On player creation, each player is assigned their own MessageChannel instance of a NoCommandChannel, with aliasing turned off.
2. Commands are added to the PlayerCommandSet for messaging: READMSG, SENDMSG, LISTMSG
3. The MessageChannel has a list of unviewed messages which is prompted to the user on login. A custom message is also sent to subscribed players (owner) when a new message arrives. When a sent Msg is viewed, it is removed from the unviewed list.

### Complications:

To provide legacy support, both the above features - Player is true owner, and alias exists - should be enabled by default. This allows for developers to experiment with new subclasses of the DefaultChannel, while not affecting their codebase.

**Comment by Griatch** [comment]
@MixKCet 
Let me see if I can break down this feature request: 

1. *Turn off key/alias generation based on key*. I interpret this as you wanting to be able to create a channel that you can then not access via its name but only via the aliases set on it later. While possible, this seems like a strange need, is there a particular use case where you don't want to be able to use the key to access a channel? Could you elaborate some more on the use-case?
2. *Opt-out of player-searching for subs* - this seems unnecessary; A channel accepts both Objects and Players as subscribers. If you just make your IC-channel joining command in such a way that only Objects (like Characters) can ever subscribe to the channel, this should never be an issue. Unless I'm misunderstanding something? 
3.* Use a channel to store the logs of a room*. I suspect this is a mis-use of the channel mechanism: Channels are for distributing messages to many people, logging is extraneous. Logging of events in a room (in itself a worthy feature) is likely better handled either by a custom table, using a custom file logger or by storing data directly on the room in question and just have a custom command to access that data later.
4. *Use of channels for OOC messaging*. This is currently handled by the `page` command. The `page` command has a history of old pages and will save pages sent to you when you are offline. What it doesn't have is a mechanism for informing you that you have messages waiting, this is true. `page` even accepts multi-player sending. Is there a particular reason for wanting to use channels for this over the normal `page` mechanism?

**Comment by Griatch** [comment]
As a reminder, there are several parts of this feature request that requires clarification; without such it will close.

**Comment by MixKCet** [comment]
_1._ 
At its core, Channel is a subscription-based service for broadcasting messages, right? I think there are plenty of use-cases where the subscription of Objects can be handled in an entirely automated fashion, and potentially even automating the creation / deletion of the Channel. What's important is that Channel _broadcasts_, but I think baking in the requirement that broadcasting be **always possible** by members of the Channel is a step too far.

_2._
I can't remember why this was an issue when I wrote the first post, but I should have been more detailed because... yeah... well, I think you're right? Unsure!

_3._
I disagree. What's important is that it handles _both_ the logging and the broadcasting. The latter is far more important. What's a better way of defining the scope of say, a fireball the hits a room, than a 'broadcast that is sent to all players of a room'? I'm merely defining a use-case for Channels where players are subscribed to a specific Channel based on their location. The additional ability to then _log_ using said Channel is a cherry, not the cake.

_4._
I hadn't looked at page when I wrote the post, glad to find it. 

Anyway! I'll leave it to your wisdom to decide whether or not this is mis-use, but I strongly suspect the scope of Channels could be a smidgen broader without the class collapsing in on itself. We already distinguish whether an Object on a channel can only listen, or also send.

What's the harm in having Channels where **no** Object can send? And if we allow these theoretical Channels (we do), what's the purpose of an alias? Or what if we do want messages to be sent, but not through the use of a command, but the by-product of other commands?

The functionality for subscriptions, message transforming based on class-typing, message persistence, and read / write restrictions seems like a waste if every single Channel spawns an alias to use with it, rather than, **optionally**, deferring that functionality?

**Comment by MixKCet** [comment]
I should note that I laugh at myself whenever I write a use-case because it's always so game specific, and I'm not creating these theoretical games! But I think that's the point? We can't know whether a game will want to have IC chat-rooms between players, or the ability to spy on locations afar, or Channels that players subscribe to if they're all members of the same race - but the only messages sent / received occur when a member of that race dies.

But the creativity of game designers is a thing of beauty, and I think it'd be pretty damn cool if they had a subscription-based broadcasting model to use in those cases.

**Comment by Griatch** [comment]
1. By setting a "send" lock on the Channel one could easily restrict it so neither of those subscribers would be allowed to send to it but only receive. This is a matter of tweaking the msg() method to do an access() check for something like the "send" permission. Since Channels are typeclassed entities, it's easy enough to modify in your game dir. But it's true the the DefaultChannel does not check for this out of the box - so this is something we could add to make it clearer where to customize (it would default to the normal use of Channels with the lock `"send:all()"`)
2. Ok! 
3. *What's a better way of defining the scope of say, a fireball the hits a room, than a 'broadcast that is sent to all players of a room'?* The way to do this is to use `location.msg_contents()`, which is clear and concise. You could then have the room log the events in any way you want. Having characters subscribed to a channel based on location is possible but but I'd think it would be unnecessarily complex when you can just communicate directly. 
4. Ok!

Aliasing of channels are just a matter of how the `addchan` command is defined - its intent is to easily subscribe to a channel and add your own alias to it all in one command. You can certainly address a channel without any alias ("Public" instead of "pub" or whatever) and remove the default `addchan` implementation if you think aliases are not useful for a particular channel type.

**Comment by Griatch** [comment]
As of latest modifications, the `send:` lock is checked in the ChannelHandler before sending to a player/object. With no further discussion in here, it would appear this closes the remaining point of this issue. Closing.
