### ISSUE TITLE
Bug: (TutorialWorld) WeatherRoom no longer producing weather

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#997]
#### Brief summary of issue / Description of requested feature:
evennia.contrib.tutorial_world.rooms.WeatherRoom no longer produces weather due to addition of pruning "stale" tickers. (bdcc093) 

#### Steps to reproduce the issue / Reasons for adding feature:

On test server:
1. Have a character object enter a tutorial weather room
2. Observe no weather
3. `@tickers` shows no ticker to call the update_weather hook.

Having the ticker subscribe when a character enters may be better than starting it on room creation, because tickers do not run until needed and are self-starting.

#### Error output / Expected result of feature
No weather tickers running.
```
Active tickers:
+--------------+--------------------------+-----------------+--------------+----+
| interval (s) | object                   | path/methodname | idstring     | db |
+~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~+~~~~+
| 6            | Ghostly apparition (#46) | do_patrol       | tutorial_mob | *  |
+--------------+--------------------------+-----------------+--------------+----+
```
Expected tickers to be present when character enters room.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.6.0 (1af1091 rev) main branch  (Test server)

I resolved this by adding code in the `at_object_receive` hook for the room to `TICKER_HANDLER.add(interval=interval, callback=self.update_weather, idstring='Weather')` (where `interval = random.randint(50, 70)` - just like the original weather room) if no 'update_weather' ticker was attached to the room, but of course there may be a better way to ensure the weather event operates as intended.

**Comment by Griatch** [comment]
Confirmed; it seems the tutorial world tickers don't survive a `@reload`. I first thought this may be an effect of transitioning to the different Tickerhandler save format lately, but even deleting and re-building the tutorial still retains the `@reload` problem - doing so appears to flush the handler. This is not visible on a local test, will need to examine further.
